import type { Topic } from '../types'

const t: Topic = {
  id: 'acute-abdomen',
  title: 'Acute abdomen',
  short: 'Acute abdomen',
  blurb:
    'Sudden severe abdominal pain needing urgent assessment: resuscitate first, then use the character, site and course of the pain, a careful examination for peritonism and a few decisive investigations to separate the patient who needs theatre now from the one who can be watched.',
  keyPoints: [
    'Resuscitate before you diagnose: ABCDE, IV access, fluids, analgesia. Opioid analgesia does not mask the signs.',
    'Peritonitis patients lie still; colic patients writhe. Sudden pain that becomes generalised = perforation, ruptured AAA or mesenteric infarction.',
    'Every woman of childbearing age with abdominal pain has a pregnancy test — a ruptured ectopic kills.',
    'Pain out of proportion to the signs in an older patient with AF = mesenteric ischaemia until proven otherwise (lactate, CT angiography).',
    'Pain + hypotension + pulsatile mass = ruptured AAA: straight to theatre/EVAR, permissive hypotension, don’t delay for CT if unstable.',
    'Always consider medical mimics: inferior MI, DKA, lower-lobe pneumonia, pyelonephritis, herpes zoster, sickle crisis.',
  ],
  sections: [
    {
      id: 'causes',
      title: 'Causes by site',
      table: {
        head: ['Site', 'Common causes'],
        rows: [
          ['Right upper quadrant', 'Biliary colic, cholecystitis, cholangitis, hepatitis, liver abscess, right lower-lobe pneumonia'],
          ['Epigastrium', 'Peptic ulcer/perforation, pancreatitis, gastritis, ruptured AAA, inferior MI'],
          ['Left upper quadrant', 'Splenic rupture or infarct, pancreatitis (tail), gastric ulcer'],
          ['Periumbilical', 'Early appendicitis, small bowel obstruction, mesenteric ischaemia, AAA'],
          ['Flank/loin', 'Renal or ureteric colic, pyelonephritis, ruptured AAA'],
          ['Right iliac fossa', 'Appendicitis, Crohn’s ileitis, mesenteric adenitis, ectopic pregnancy, ovarian torsion/cyst, PID, caecal pathology'],
          ['Left iliac fossa', 'Diverticulitis, colitis, sigmoid volvulus, ectopic, ovarian pathology'],
          ['Suprapubic', 'Urinary retention, UTI, PID, ectopic, diverticulitis'],
          ['Generalised', 'Peritonitis (perforation), obstruction, mesenteric ischaemia, pancreatitis, DKA, gastroenteritis'],
        ],
      },
      note: 'Visceral pain follows the embryology: foregut → epigastrium, midgut → periumbilical, hindgut → suprapubic. Parietal (somatic) pain localises over the inflamed organ.',
      source: 'Macleod’s 14e · Ch 6 · pp 96–98 (Fig 6.4, Box 6.4)',
    },
    {
      id: 'history',
      title: 'History — SOCRATES and the rest',
      items: [
        '**Site** and where it started; **onset** — sudden (perforation, rupture, infarction, torsion) or gradual (inflammation).',
        '**Character** — colicky (hollow viscus obstruction) or constant (inflammation, ischaemia); biliary and renal “colic” are actually constant.',
        '**Radiation**: shoulder tip (diaphragm — free blood/air), back (pancreas, AAA, posterior DU), loin to groin (renal colic), below the right scapula (gallbladder).',
        '**Associated**: vomiting (before or after pain; bilious, faeculent, blood), bowels (absolute constipation, diarrhoea, blood), urinary symptoms, fever and rigors, jaundice.',
        '**Timing and exacerbating/relieving factors**: movement and coughing hurt in peritonitis; sitting forward relieves pancreatitis.',
        '**Severity** — pain out of proportion to signs suggests ischaemia.',
        '**Women**: LMP, contraception, vaginal bleeding/discharge, sexual history.',
        '**Past and drugs**: previous surgery (adhesions), gallstones, ulcers, AAA, AF and vascular disease, NSAIDs, steroids, anticoagulants; alcohol.',
      ],
      source: 'Macleod’s 14e · Ch 6 · pp 96–98 (Box 6.2)',
    },
    {
      id: 'exam',
      title: 'Examination',
      kind: 'steps',
      items: [
        '**End of the bed**: lying still (peritonitis) or writhing (colic), pallor, sweating, shallow breathing; vital signs and NEWS.',
        '**Hands and pulse**: perfusion (capillary refill, temperature), tachycardia, AF (mesenteric ischaemia), blood pressure.',
        '**Face**: pallor, jaundice, dry mucosae, ketotic breath.',
        '**Inspect the abdomen**: distension, movement with respiration (absent in generalised peritonitis), scars, hernias, bruising (Cullen’s, Grey Turner’s).',
        '**Ask the patient to cough** — pain on coughing indicates peritonism.',
        '**Palpate** gently starting away from the pain, watching the face: tenderness, guarding (voluntary or involuntary), rigidity, masses (pulsatile?).',
        '**Percussion tenderness** — a kinder test for peritonism than rebound.',
        '**Special signs** as indicated: Murphy’s, Rovsing’s, psoas, obturator.',
        '**Auscultate**: absent (ileus, peritonitis), high-pitched tinkling (obstruction), bruits.',
        '**Hernial orifices** and external genitalia (testicular torsion presents with abdominal pain), femoral pulses (AAA, dissection).',
        '**Complete**: DRE, urinalysis and pregnancy test, chest examination.',
      ],
      source: 'Macleod’s 14e · Ch 6 · pp 104–110',
    },
    {
      id: 'signs',
      title: 'Eponymous signs',
      table: {
        head: ['Sign', 'How', 'Suggests'],
        rows: [
          ['Murphy’s', 'Fingers under the right costal margin; patient breathes in — catches breath with pain (not on the left)', 'Acute cholecystitis'],
          ['Rovsing’s', 'Pressing in the left iliac fossa causes pain in the right', 'Appendicitis'],
          ['Psoas', 'Pain on flexing the right hip against resistance (or extending it)', 'Retrocaecal appendicitis, psoas abscess'],
          ['Obturator', 'Pain on internal rotation of the flexed right hip', 'Pelvic appendicitis/abscess'],
          ['Cullen’s / Grey Turner’s', 'Periumbilical / flank bruising', 'Haemorrhagic pancreatitis, ruptured AAA, ruptured ectopic'],
          ['Kehr’s', 'Left shoulder-tip pain', 'Splenic rupture (blood under the diaphragm)'],
          ['Boas’', 'Hyperaesthesia below the right scapula', 'Cholecystitis'],
          ['Carnett’s', 'Tenderness persists or worsens on tensing the abdominal wall', 'Abdominal wall pain (rectus sheath haematoma, nerve entrapment)'],
        ],
      },
      source: 'Macleod’s 14e · Ch 6 · p 106 (Box 6.9)',
    },
    {
      id: 'conditions',
      title: 'Key conditions at a glance',
      table: {
        head: ['Condition', 'History', 'Examination'],
        rows: [
          ['Appendicitis', 'Central pain → RIF, anorexia, nausea, low fever', 'RIF tenderness at McBurney’s point, guarding, Rovsing’s, pelvic tenderness on PR'],
          ['Perforated peptic ulcer', 'Sudden severe epigastric pain → generalised, shoulder tip; NSAIDs, dyspepsia', 'Still, shallow breathing, board-like rigidity, absent bowel sounds; free gas on erect CXR'],
          ['Acute pancreatitis', 'Severe epigastric pain to the back, vomiting; gallstones or alcohol', 'Epigastric tenderness, variable guarding, Cullen’s/Grey Turner’s; lipase > 3× ULN'],
          ['Ruptured AAA', 'Sudden back/loin/abdominal pain, collapse; vascular risk factors', 'Shock, tender pulsatile expansile mass, asymmetric femoral pulses'],
          ['Mesenteric ischaemia', 'Severe constant pain, vomiting, bloody diarrhoea; AF, vascular disease', 'Pain out of proportion to signs early; AF; raised lactate'],
          ['Bowel obstruction', 'Colicky pain, vomiting, distension, absolute constipation', 'Distension, scars, hernias, tinkling bowel sounds'],
          ['Ruptured ectopic', 'Missed period, unilateral pain, shoulder tip pain, collapse', 'Shock, lower abdominal tenderness, cervical excitation; positive β-hCG'],
        ],
      },
      source: 'Macleod’s 14e · Ch 6 · p 98 (Box 6.4)',
    },
    {
      id: 'investigations',
      title: 'Investigations',
      items: [
        '**Bedside**: obs, urine dipstick, **urine/serum β-hCG in every woman of childbearing age**, capillary glucose and ketones, ECG (inferior MI), VBG (lactate, acid–base).',
        '**Bloods**: FBC, U&E, LFT, CRP, **amylase or lipase**, calcium, coagulation, group and save/crossmatch; cultures if febrile.',
        '**Erect CXR**: free gas under the diaphragm (sit up for 10–15 min first; normal in up to 25% of perforations); lower-lobe pneumonia.',
        '**AXR**: obstruction, volvulus; limited role otherwise.',
        '**CT abdomen/pelvis with contrast**: the key test in adults for most diagnoses; **CT angiography** for mesenteric ischaemia and AAA.',
        '**Ultrasound**: biliary disease, pelvic pathology, appendicitis in children and young women, free fluid (FAST).',
      ],
      source: 'Macleod’s 14e · Ch 6 · pp 113–115 (Box 6.17)',
    },
    {
      id: 'scores',
      title: 'Scores',
      items: [
        '**Alvarado (appendicitis, /10 — MANTRELS)**: Migration of pain (1), Anorexia (1), Nausea/vomiting (1), Tenderness in RIF (2), Rebound (1), Elevated temperature > 37.3 °C (1), Leucocytosis (2), Shift to the left (1). ≤ 4 unlikely, ≥ 7 likely.',
        '**Glasgow–Imrie (pancreatitis, within 48 h — PANCREAS)**: PaO₂ < 8 kPa, Age > 55, Neutrophils (WCC > 15), Calcium < 2 mmol/L, Renal (urea > 16), Enzymes (LDH > 600 or AST > 200), Albumin < 32 g/L, Sugar (glucose > 10). ≥ 3 = severe.',
        '**Revised Atlanta (pancreatitis)**: mild (no organ failure), moderately severe (transient organ failure < 48 h or local complications), severe (persistent organ failure > 48 h).',
        '**Hinchey (perforated diverticulitis)**: I pericolic abscess, II pelvic/distant abscess, III purulent peritonitis, IV faecal peritonitis.',
        '**qSOFA**: RR ≥ 22, altered mentation, SBP ≤ 100 — ≥ 2 suggests sepsis with poor outcome.',
      ],
    },
    {
      id: 'management',
      title: 'Management principles',
      items: [
        '**ABCDE**: oxygen, two large-bore cannulae, bloods including crossmatch, fluids (balanced crystalloid), catheter and fluid balance, analgesia (IV opioid titrated), antiemetic, NBM.',
        '**Sepsis**: blood cultures and broad-spectrum antibiotics within an hour, lactate, fluids (Sepsis Six).',
        '**NG tube** for vomiting/obstruction; **VTE prophylaxis** unless bleeding.',
        '**Early senior review** — and early decision about theatre. Do not delay surgery for non-essential imaging in an unstable patient.',
        '**Re-examine** the undiagnosed abdomen regularly — a change in the pattern of pain means the diagnosis was wrong or a complication has occurred.',
        '**Ruptured AAA**: permissive hypotension (SBP 70–90, conscious), O-negative/crossmatched blood, vascular surgeons, theatre or EVAR.',
      ],
      source: 'Macleod’s 14e · Ch 6 · p 98; Ch 18 · pp 341–346',
    },
  ],
  cases: ['appendicitis', 'perforated-du', 'pancreatitis', 'ruptured-aaa', 'mesenteric-ischaemia', 'diverticulitis', 'cholecystitis'],
  qa: [
    { q: 'What is an acute abdomen?', a: 'Sudden onset of severe abdominal pain (usually < 7 days) that may need urgent surgical intervention. The priorities are to resuscitate, identify the life-threatening causes and decide early whether the patient needs theatre.' },
    { q: 'What are the life-threatening causes of acute abdominal pain?', a: 'Ruptured AAA, perforated viscus with peritonitis, acute mesenteric ischaemia, ruptured ectopic pregnancy, strangulated bowel/volvulus, severe acute pancreatitis, ascending cholangitis — plus medical mimics such as MI, DKA and aortic dissection.', k: ['red flags', 'emergencies'] },
    { q: 'Why does appendicitis pain move from the umbilicus to the RIF?', a: 'Early inflammation stretches the visceral peritoneum of the appendix, a midgut structure, so pain is felt vaguely around the umbilicus (T10). When the inflamed appendix irritates the parietal peritoneum, the somatic pain localises to the RIF over McBurney’s point.', k: ['migratory pain', 'visceral somatic'] },
    { q: 'Where is McBurney’s point?', a: 'One-third of the way from the anterior superior iliac spine to the umbilicus — the surface marking of the base of the appendix.' },
    { q: 'What is the Alvarado score?', a: 'A 10-point score for appendicitis (MANTRELS): Migration of pain 1, Anorexia 1, Nausea/vomiting 1, Tenderness RIF 2, Rebound 1, Elevated temperature 1, Leucocytosis 2, Shift to left 1. ≤ 4 appendicitis unlikely; 5–6 equivocal (imaging); ≥ 7 probable.', k: ['MANTRELS', 'appendicitis score'] },
    { q: 'What is the difference between guarding and rigidity?', a: 'Guarding is contraction of the abdominal muscles when palpated — voluntary (anxiety, can be overcome) or involuntary (reflex, from parietal peritoneal inflammation). Rigidity is constant involuntary contraction (“board-like”) — generalised peritonitis.' },
    { q: 'How do you test for peritonism without causing pain?', a: 'Ask the patient to cough, gently percuss the abdomen (percussion tenderness), or gently shake the bed/heel drop. Rebound tenderness is painful and adds little.', k: ['rebound'] },
    { q: 'What does free gas under the diaphragm mean?', a: 'A perforated hollow viscus (most often peptic ulcer, then colon) — unless explained by recent laparoscopy/laparotomy or peritoneal dialysis. Sit the patient upright 10–15 minutes before the erect CXR; CT is more sensitive.', k: ['pneumoperitoneum'] },
    { q: 'Why check a pregnancy test in abdominal pain?', a: 'To exclude ectopic pregnancy (life-threatening), and because pregnancy changes imaging choices (avoid CT radiation where possible) and drug choices. Every woman of childbearing age, regardless of history.', k: ['beta hCG', 'ectopic'] },
    { q: 'What is the classic triad of a ruptured AAA?', a: 'Sudden severe abdominal or back/loin pain, hypotension/collapse, and a pulsatile expansile abdominal mass. Often misdiagnosed as renal colic in an older man.', k: ['AAA'] },
    { q: 'What is permissive hypotension in ruptured AAA?', a: 'Restricting fluid resuscitation to maintain a systolic BP around 70–90 mmHg (or a conscious patient) until the aorta is controlled — raising the pressure increases bleeding and dilutes clotting factors.' },
    { q: 'What are the features of acute mesenteric ischaemia?', a: 'Severe constant pain out of proportion to abdominal signs, vomiting, later bloody diarrhoea and peritonitis; usually an older patient with AF (embolus), vascular disease (thrombosis), low-flow states or hypercoagulability (venous). Raised lactate and metabolic acidosis are late; CT angiography is diagnostic.' },
    { q: 'What are the causes of acute pancreatitis?', a: '“I GET SMASHED”: Idiopathic, Gallstones, Ethanol, Trauma, Steroids, Mumps (and other viruses), Autoimmune, Scorpion venom, Hypertriglyceridaemia/Hypercalcaemia/Hypothermia, ERCP, Drugs (azathioprine, valproate, thiazides). Gallstones and alcohol cause about 80%.', k: ['I GET SMASHED', 'aetiology'] },
    { q: 'How is acute pancreatitis diagnosed?', a: 'Two of three: typical epigastric pain radiating to the back; serum lipase or amylase > 3× the upper limit of normal; characteristic imaging (CT/MRI/US). CT is not needed for diagnosis if the first two are present — it is used after 72 h to assess complications or if the diagnosis is uncertain.' },
    { q: 'What is the Glasgow–Imrie score?', a: 'Severity score for acute pancreatitis within 48 h — PANCREAS: PaO₂ < 8 kPa, Age > 55, Neutrophils (WCC > 15 × 10⁹/L), Calcium < 2 mmol/L, Renal (urea > 16 mmol/L), Enzymes (LDH > 600 IU/L or AST > 200), Albumin < 32 g/L, Sugar (glucose > 10 mmol/L). Score ≥ 3 = severe.', k: ['modified Glasgow', 'PANCREAS'] },
    { q: 'What are the medical causes of abdominal pain you must exclude?', a: 'Inferior MI, lower-lobe pneumonia, DKA, pyelonephritis, herpes zoster, sickle cell crisis, porphyria, Addisonian crisis, hypercalcaemia, lead poisoning, and testicular torsion.' },
    { q: 'Does analgesia mask peritonitis?', a: 'No. Titrated IV opioid analgesia relieves suffering without hiding the signs and makes the patient easier to examine. Withholding it is outdated. Reassess regularly.' },
    { q: 'What is the Hinchey classification?', a: 'For perforated diverticulitis: I pericolic/mesenteric abscess, II pelvic/retroperitoneal/distant abscess, III generalised purulent peritonitis, IV generalised faecal peritonitis. I–II: antibiotics ± percutaneous drainage; III: laparoscopic lavage or resection; IV: resection (Hartmann’s or primary anastomosis with stoma).' },
    { q: 'What is Cullen’s sign and Grey Turner’s sign?', a: 'Cullen’s: periumbilical bruising; Grey Turner’s: flank bruising. Both reflect retroperitoneal haemorrhage tracking — haemorrhagic pancreatitis, ruptured AAA, ruptured ectopic pregnancy. They are late signs.' },
    { q: 'What are the signs of sepsis and what is the Sepsis Six?', a: 'Suspected infection with organ dysfunction (NEWS ≥ 5, qSOFA ≥ 2, lactate > 2). Sepsis Six within an hour (“BUFALO”): Blood cultures, Urine output monitoring, Fluids, Antibiotics, Lactate, Oxygen.', k: ['BUFALO', 'qSOFA'] },
    { q: 'What do you do if the diagnosis is still unclear?', a: 'Resuscitate, give analgesia, keep NBM, re-examine regularly (ideally by the same person), repeat bloods, and image (CT in most adults; US in children and young women). Diagnostic laparoscopy if peritonism persists with no diagnosis.' },
    { q: 'What causes shoulder-tip pain?', a: 'Irritation of the diaphragmatic peritoneum (phrenic nerve, C3–5) referred to the C4 dermatome — free blood (ruptured ectopic, splenic rupture — Kehr’s sign on the left), gas (perforation), pus (subphrenic abscess), or the gallbladder (right).', k: ['Kehr', 'referred pain'] },
    { q: 'What is the role of serum amylase vs lipase?', a: 'Both rise in pancreatitis (> 3× ULN supports the diagnosis). Lipase is more specific and stays raised longer. Neither indicates severity. Modest rises occur in perforated ulcer, mesenteric ischaemia, ruptured AAA, ectopic and renal failure.' },
    { q: 'When should a patient with acute abdominal pain go straight to theatre?', a: 'Generalised peritonitis, an unstable patient with a ruptured AAA or ruptured ectopic, strangulated hernia, perforation with sepsis, or bowel ischaemia — after resuscitation is started (which continues in theatre).' },
  ],
}

export default t
