import type { Topic } from '../types'

const t: Topic = {
  id: 'bariatric',
  title: 'Bariatric surgery',
  short: 'Bariatrics',
  blurb:
    'Surgery for severe obesity and its metabolic disease: who qualifies, how they are assessed, what the operations do, and how to recognise the complications that bring patients back — a leak in the first days, an internal hernia or nutritional deficiency years later.',
  keyPoints: [
    'BMI = weight (kg) ÷ height (m)². Obese ≥ 30, morbidly obese ≥ 40 (Asian thresholds are lower: obese ≥ 25, morbid ≥ 30).',
    'Surgery is offered for BMI ≥ 40, or ≥ 35 with obesity-related disease (type 2 diabetes, hypertension, sleep apnoea), after non-surgical measures, with lifelong follow-up.',
    'Sleeve gastrectomy is restrictive and hormonal; Roux-en-Y gastric bypass adds malabsorption and is preferred with reflux or diabetes.',
    'A sustained heart rate > 120 after bariatric surgery is a leak until proven otherwise — CT with oral contrast, or straight back to theatre if unstable.',
    'Colicky pain years after a bypass: think internal hernia (Petersen’s space) — a normal CT does not exclude it.',
    'Lifelong supplements: multivitamin, calcium + vitamin D, iron, B12 (injections after bypass). Give thiamine before glucose if a patient is vomiting persistently.',
  ],
  sections: [
    {
      id: 'definitions',
      title: 'Obesity and BMI',
      table: {
        head: ['Class', 'BMI (most populations)', 'BMI (Asian)'],
        rows: [
          ['Underweight', '< 18.5', '< 18.5'],
          ['Normal', '18.5–24.9', '18.5–22.9'],
          ['Overweight', '25–29.9', '23–24.9'],
          ['Obese', '30–39.9', '25–29.9'],
          ['Morbidly obese', '≥ 40', '≥ 30'],
        ],
      },
      note: 'Central obesity carries the metabolic risk: waist circumference is measured midway between the lower costal margin and the iliac crest; a high waist : hip ratio (“apple”) predicts coronary disease and the metabolic syndrome.',
      source: 'Macleod’s 14e · Ch 3 · p 29 (Box 3.7)',
    },
    {
      id: 'indications',
      title: 'Who is offered surgery',
      items: [
        '**BMI ≥ 40**, or **BMI 35–40 with obesity-related disease** that weight loss would improve (type 2 diabetes, hypertension, obstructive sleep apnoea, NAFLD, osteoarthritis).',
        '**Recent-onset type 2 diabetes**: assess at BMI ≥ 35; consider at 30–34.9 (metabolic surgery). Thresholds are about 2.5 lower for people of Asian origin.',
        '**Non-surgical measures tried** (diet, activity, behavioural support, drugs such as GLP-1 agonists) without adequate, sustained loss.',
        '**Fit for anaesthesia and surgery**, and committed to **lifelong follow-up** and supplements.',
        'Assessed and treated by a **multidisciplinary team**: surgeon, physician/endocrinologist, dietitian, psychologist, anaesthetist.',
      ],
      note: 'Newer international guidance (ASMBS/IFSO 2022) recommends surgery at BMI ≥ 35 regardless of comorbidity, and considers it from 30 with metabolic disease.',
      source: 'NICE CG189 · ASMBS/IFSO 2022',
    },
    {
      id: 'contraindications',
      title: 'Contraindications',
      items: [
        'Uncontrolled psychiatric illness, active substance or alcohol misuse, untreated eating disorder (binge eating must be treated first).',
        'Unable to understand the operation or comply with lifelong follow-up and supplements.',
        'Prohibitive anaesthetic risk (severe heart or lung disease).',
        'An untreated **secondary cause** of obesity: hypothyroidism, Cushing’s syndrome, drugs (steroids, antipsychotics, insulin).',
        'Pregnancy, or pregnancy planned within 12–18 months of surgery.',
      ],
    },
    {
      id: 'history',
      title: 'History',
      items: [
        '**Weight history**: onset (childhood or adult), maximum weight, triggers, what has been tried (diets, programmes, drugs, balloon) and the effect.',
        '**Eating pattern**: binge eating, grazing, night eating, sweet drinks, alcohol calories.',
        '**Comorbidities**: type 2 diabetes (HbA1c, insulin), hypertension, dyslipidaemia, sleep apnoea (snoring, witnessed apnoeas, daytime sleepiness — STOP-BANG), reflux, joint pain, PCOS and infertility, NAFLD, depression.',
        '**Secondary causes**: hypothyroid symptoms, Cushingoid features, steroid or antipsychotic drugs.',
        '**Previous abdominal surgery** and hernias.',
        '**Social**: smoking (must stop — marginal ulcers, leaks), alcohol, support at home, job, motivation and expectations.',
      ],
    },
    {
      id: 'exam',
      title: 'Examination',
      kind: 'steps',
      intro: 'A general and abdominal examination focused on the consequences of obesity and on secondary causes.',
      items: [
        '**General inspection**: fat distribution (central or peripheral), mobility, breathlessness on undressing, Cushingoid features (moon face, buffalo hump, proximal wasting).',
        '**Measure** height, weight, BMI and waist circumference (midway between costal margin and iliac crest); neck circumference (> 40 cm suggests sleep apnoea).',
        '**Blood pressure** with a large cuff — a standard cuff over-reads.',
        '**Skin**: acanthosis nigricans in the neck and axillae (insulin resistance), intertrigo, striae — broad purple striae suggest Cushing’s, silvery-white ones previous weight change.',
        '**Hands and face**: signs of hypothyroidism (dry skin, slow relaxing reflexes, periorbital puffiness); airway (Mallampati, mouth opening, neck movement) for the anaesthetist.',
        '**Abdomen**: scars from previous surgery, umbilical and incisional hernias (examine standing and on coughing), hepatomegaly (fatty liver).',
        '**Legs**: oedema, venous stasis changes and ulcers.',
      ],
      source: 'Macleod’s 14e · Ch 3 · pp 29–30; Ch 6 · p 103',
    },
    {
      id: 'investigations',
      title: 'Pre-operative assessment',
      items: [
        '**Bloods**: FBC, U&E, LFT, HbA1c and glucose, lipids, TFT; haematinics (ferritin, B12, folate), vitamin D, calcium and PTH — to correct deficiencies before surgery.',
        '**Cortisol** (overnight dexamethasone suppression test) if Cushing’s is suspected.',
        '**OGD** for reflux symptoms (a sleeve can worsen reflux; a large hiatus hernia is repaired at the same time) and **H. pylori** testing.',
        '**Sleep study** if STOP-BANG is high; CPAP before surgery if sleep apnoea is confirmed.',
        '**ECG ± echocardiogram**; spirometry if lung disease.',
        '**Ultrasound abdomen** if biliary symptoms.',
        '**Liver-shrinkage diet**: 2 weeks of a very-low-calorie diet before surgery shrinks the fatty left lobe of the liver so the stomach can be reached laparoscopically.',
      ],
    },
    {
      id: 'operations',
      title: 'The operations',
      table: {
        head: ['Operation', 'How it works', 'Typical points'],
        rows: [
          ['Sleeve gastrectomy', 'Restrictive + hormonal: about 80% of the stomach (greater curve, fundus) removed, leaving a tube; ghrelin falls', 'Most common worldwide; no anastomosis; may worsen reflux; staple-line leak at the angle of His'],
          ['Roux-en-Y gastric bypass', 'Restrictive + malabsorptive: small gastric pouch joined to a Roux limb; bile limb rejoins downstream', 'Best for reflux and diabetes; risks marginal ulcer, internal hernia, dumping, iron/B12/calcium deficiency'],
          ['One-anastomosis gastric bypass', 'Long pouch joined to a loop of jejunum', 'Simpler; bile reflux and malnutrition are concerns'],
          ['Adjustable gastric band', 'Restrictive band around the upper stomach, filled via a port', 'Now uncommon: slippage, erosion, port problems, weight regain'],
          ['Duodenal switch / SADI-S', 'Sleeve + long malabsorptive bypass', 'Most weight loss; most nutritional complications'],
        ],
      },
      note: 'Endoscopic options (intragastric balloon, endoscopic sleeve gastroplasty) are temporary or for lower BMIs.',
    },
    {
      id: 'complications',
      title: 'Complications',
      items: [
        {
          t: '**Early (first days–weeks)**',
          sub: [
            '**Leak** (staple line or anastomosis, peak day 2–7): tachycardia > 120 is often the first and only sign; fever, tachypnoea, left shoulder or abdominal pain. CT with oral contrast; unstable → laparoscopy, washout, drains, antibiotics; endoscopic stent for a sleeve leak.',
            '**Bleeding** (staple line, intraluminal or intra-abdominal).',
            '**VTE** — obese patients need weight-adjusted LMWH and early mobilisation.',
            'Early obstruction, wound infection, rhabdomyolysis after long operations.',
          ],
        },
        {
          t: '**Late (months–years)**',
          sub: [
            '**Internal hernia** after bypass (Petersen’s space, mesenteric defects): intermittent colicky pain, can strangulate; CT swirl sign; low threshold for diagnostic laparoscopy.',
            '**Marginal ulcer** at the gastrojejunostomy (smoking, NSAIDs): pain, bleeding, perforation.',
            '**Anastomotic stricture**: dysphagia and vomiting at 4–8 weeks; endoscopic dilatation.',
            '**Dumping**: early (15–30 min, osmotic — colic, diarrhoea, palpitations) and late (1–3 h, reactive hypoglycaemia). Small, frequent, low-sugar meals.',
            '**Deficiencies**: iron, B12, folate, calcium/vitamin D (osteoporosis), thiamine (Wernicke’s after persistent vomiting), protein malnutrition.',
            '**Gallstones** with rapid weight loss (ursodeoxycholic acid reduces them).',
            'New or worse reflux after a sleeve; weight regain.',
          ],
        },
      ],
    },
    {
      id: 'aftercare',
      title: 'After surgery',
      items: [
        'Staged diet: liquids → purée → soft → normal over about 6 weeks; small meals, eat slowly, drink between meals not with them; protein 60–80 g a day.',
        '**Lifelong supplements**: complete multivitamin, calcium + vitamin D, iron; B12 injections every 3 months after bypass.',
        'Annual bloods (FBC, ferritin, B12, folate, vitamin D, calcium, PTH, LFT).',
        'Review diabetic and antihypertensive drugs early — needs fall quickly (risk of hypoglycaemia).',
        'Avoid NSAIDs and smoking; avoid pregnancy for 12–18 months; oral contraceptives may be poorly absorbed after bypass.',
        'Expected loss: about 60–70% of excess weight after bypass, 50–60% after sleeve; many achieve remission of type 2 diabetes.',
      ],
    },
  ],
  cases: ['bariatric-leak', 'bariatric-assessment'],
  qa: [
    { q: 'How do you calculate BMI and classify obesity?', a: 'BMI = weight (kg) ÷ height (m)². Overweight 25–29.9, obese 30–39.9 (class I 30–34.9, II 35–39.9), morbidly obese (class III) ≥ 40. For Asian populations overweight starts at 23 and obesity at 25.', k: ['body mass index', 'obesity classes'] },
    { q: 'What are the indications for bariatric surgery?', a: 'BMI ≥ 40, or 35–40 with significant obesity-related disease (T2DM, hypertension, OSA) that would improve with weight loss; non-surgical measures tried; fit for anaesthesia; committed to lifelong follow-up; MDT assessment. Consider from BMI 30–34.9 with recent-onset T2DM (lower thresholds for Asian patients).', k: ['criteria', 'NICE', 'who qualifies'] },
    { q: 'What are the contraindications to bariatric surgery?', a: 'Uncontrolled psychiatric illness or eating disorder, active drug/alcohol misuse, inability to comply with follow-up, prohibitive anaesthetic risk, an untreated endocrine cause (hypothyroidism, Cushing’s), and pregnancy planned within 12–18 months.' },
    { q: 'Name the common bariatric operations and how they work.', a: 'Sleeve gastrectomy (restrictive + hormonal, ~80% of stomach removed); Roux-en-Y gastric bypass (small pouch + Roux limb: restrictive and malabsorptive); one-anastomosis gastric bypass; adjustable gastric band (restrictive, now uncommon); duodenal switch/SADI-S (most malabsorptive).', k: ['types of bariatric surgery', 'RYGB', 'sleeve'] },
    { q: 'Why is a sleeve gastrectomy “hormonal” as well as restrictive?', a: 'Removing the fundus removes most ghrelin-producing cells, so hunger falls; faster gastric emptying raises GLP-1 and PYY, improving satiety and glucose control.', k: ['ghrelin'] },
    { q: 'Sleeve or bypass for a patient with reflux?', a: 'Roux-en-Y gastric bypass — it is an effective anti-reflux operation. A sleeve is a high-pressure tube and often worsens or causes reflux.', k: ['GORD', 'GERD'] },
    { q: 'What is the most important early complication and its first sign?', a: 'An anastomotic or staple-line leak (usually day 2–7). Persistent tachycardia > 120 bpm is often the earliest and only sign; others are fever, tachypnoea, left shoulder-tip or abdominal pain, and a falling urine output. Abdominal signs are unreliable in obese patients.', k: ['leak', 'tachycardia'] },
    { q: 'How do you manage a suspected leak after a sleeve?', a: 'ABCDE resuscitation, IV fluids, broad-spectrum antibiotics, NBM; urgent CT with oral contrast if stable, otherwise straight to diagnostic laparoscopy for washout and drainage. Sleeve leaks often need an endoscopic stent or internal drain and nutritional support.' },
    { q: 'Where is the leak after a sleeve classically found?', a: 'At the top of the staple line near the angle of His (gastro-oesophageal junction), where blood supply is poorest and pressure in the tube highest.' },
    { q: 'What is an internal hernia after gastric bypass?', a: 'Small bowel herniating through mesenteric defects created at bypass — Petersen’s space (between the Roux limb mesentery and the transverse mesocolon) or the jejunojejunostomy defect. Presents with intermittent colicky pain, sometimes obstruction or strangulation, often after major weight loss. CT may show the “swirl sign” but can be normal; diagnostic laparoscopy if suspected.', k: ['Petersen', 'swirl sign'] },
    { q: 'What is dumping syndrome?', a: 'Early dumping (15–30 min after a meal): rapid entry of hyperosmolar food into the small bowel draws fluid in — colic, diarrhoea, bloating, palpitations, flushing. Late dumping (1–3 h): rapid glucose absorption → insulin surge → reactive hypoglycaemia. Managed with small, frequent, low-sugar, high-protein meals and fluids between meals.' },
    { q: 'Which deficiencies follow bariatric surgery?', a: 'Iron (anaemia), vitamin B12 and folate, calcium and vitamin D (bone disease), thiamine (Wernicke’s encephalopathy with persistent vomiting), zinc, copper and protein. Hence lifelong multivitamin, calcium + vitamin D, iron, B12 injections after bypass and annual bloods.', k: ['vitamin', 'nutritional'] },
    { q: 'A post-bypass patient is vomiting and confused — what must you give?', a: 'IV thiamine (e.g. Pabrinex) before any glucose — Wernicke’s encephalopathy (confusion, ataxia, ophthalmoplegia) from thiamine deficiency.', k: ['Wernicke', 'thiamine', 'pabrinex'] },
    { q: 'What is a marginal ulcer?', a: 'An ulcer at the gastrojejunal anastomosis after bypass, on the jejunal side. Risk factors: smoking, NSAIDs, steroids, H. pylori, ischaemia. Presents with epigastric pain, bleeding or perforation. Treat with high-dose PPI and removing the cause.' },
    { q: 'Why do patients get a liver-shrinkage diet before surgery?', a: 'A very-low-calorie diet for about 2 weeks depletes glycogen and fat from the enlarged left lobe of the liver, making it easier to retract and improving laparoscopic access and safety.', k: ['LRD', 'pre-op diet'] },
    { q: 'Why test for sleep apnoea before bariatric surgery?', a: 'Untreated OSA increases the risk of airway obstruction, hypoxia and cardiac events around anaesthesia and with post-operative opioids. Screen with STOP-BANG; confirm with a sleep study; start CPAP before surgery.', k: ['OSA', 'STOP-BANG', 'CPAP'] },
    { q: 'What does STOP-BANG stand for?', a: 'Snoring, Tiredness, Observed apnoea, high blood Pressure, BMI > 35, Age > 50, Neck circumference > 40 cm, male Gender. ≥ 3 = increased risk, ≥ 5 = high risk of moderate–severe OSA.' },
    { q: 'What are secondary causes of obesity you should exclude?', a: 'Hypothyroidism, Cushing’s syndrome, drugs (steroids, antipsychotics, insulin, sulphonylureas, some antiepileptics), polycystic ovary syndrome, hypothalamic disease and rare genetic syndromes (e.g. Prader–Willi).' },
    { q: 'What are the comorbidities of obesity?', a: 'Type 2 diabetes, hypertension, dyslipidaemia, coronary disease, stroke, sleep apnoea and obesity hypoventilation, GORD, gallstones, NAFLD, osteoarthritis, infertility/PCOS, depression, VTE, and cancers (oesophageal adenocarcinoma, endometrial, breast, colorectal, renal).' },
    { q: 'Why do bariatric patients get gallstones?', a: 'Rapid weight loss supersaturates bile with cholesterol and reduces gallbladder emptying. Ursodeoxycholic acid for the first 6 months reduces stone formation.' },
    { q: 'How much weight do patients lose?', a: 'Roughly 60–70% of excess weight after gastric bypass and 50–60% after sleeve gastrectomy at 1–2 years, with remission of type 2 diabetes in many patients (higher after bypass).', k: ['excess weight loss', 'outcomes'] },
    { q: 'When can a woman become pregnant after bariatric surgery?', a: 'Advise avoiding pregnancy for 12–18 months, during rapid weight loss. Oral contraception may be less reliable after bypass — use a non-oral method.' },
    { q: 'How should acanthosis nigricans be interpreted?', a: 'Velvety hyperpigmented skin in the neck, axillae and groins — a sign of insulin resistance (obesity, type 2 diabetes, PCOS); rarely a paraneoplastic sign of gastric adenocarcinoma.' },
    { q: 'How do you measure waist circumference?', a: 'Standing, at the end of a normal expiration, midway between the lower costal margin and the iliac crest. High risk: > 102 cm in men, > 88 cm in women (lower cut-offs in Asian populations).' },
    { q: 'What VTE prophylaxis do bariatric patients need?', a: 'Mechanical (stockings/intermittent compression) plus weight-adjusted LMWH, early mobilisation, often extended prophylaxis after discharge in high-risk patients.' },
    { q: 'What complications are specific to gastric bands?', a: 'Band slippage (vomiting, food intolerance, pouch dilatation — deflate and revise), erosion into the stomach (port-site infection, loss of restriction), port or tubing problems, oesophageal dilatation and poor long-term weight loss.' },
  ],
}

export default t
