import type { Topic } from '../types'

const t: Topic = {
  id: 'breast',
  title: 'Breast lump & nipple discharge',
  short: 'Breast',
  blurb:
    'Every breast lump gets triple assessment. The session covers the history and risk factors, Macleod’s breast examination in its positions, the benign lumps that dominate by age, the significance of nipple discharge and changes, and how breast cancer is staged and treated.',
  keyPoints: [
    'Triple assessment: clinical examination + imaging (ultrasound < 40, mammography + ultrasound ≥ 40) + core biopsy. Each graded 1–5 (P, U/M, B).',
    'Age guides the likely lump: fibroadenoma < 35, cyst 35–55, cancer mostly > 50 — but any lump is cancer until proven otherwise.',
    'Inspect with hands on thighs, pressed on hips, raised above the head, and leaning forward; palpate lying with the hand behind the head, clock-face, including the axillary tail, nipple and nodes.',
    'Single-duct, blood-stained discharge needs investigation: intraductal papilloma is the commonest cause, but exclude DCIS/carcinoma.',
    'Nipple eczema that starts on the nipple and spreads to the areola, unilateral, is Paget’s disease until proven otherwise (eczema usually starts on the areola).',
    'Treatment of cancer: surgery (wide local excision + radiotherapy, or mastectomy) with sentinel node biopsy, then adjuvant therapy by receptor status (ER/PR, HER2).',
  ],
  sections: [
    {
      id: 'history',
      title: 'History',
      items: [
        '**The lump**: when and how found, single or multiple, site, size change, pain, relation to the menstrual cycle (cyclical change suggests benign), trauma (fat necrosis).',
        '**Nipple**: discharge (one or many ducts, one or both sides, colour, blood, spontaneous or expressed), inversion (new or longstanding), eczema or itch.',
        '**Skin**: dimpling, redness, swelling, orange-peel change.',
        '**Systemic**: weight loss, bone pain, breathlessness, headache, jaundice (metastases).',
        '**Risk factors**: age, previous breast cancer or atypical hyperplasia, **family history** of breast/ovarian cancer (ages, BRCA), early menarche/late menopause, nulliparity or first child > 30, not breastfeeding, HRT and the combined pill, obesity (postmenopausal), alcohol, previous chest/mantle radiotherapy.',
        '**Breastfeeding/lactation** (abscess, galactocele); **smoking** (periductal mastitis); drugs causing galactorrhoea (antipsychotics, metoclopramide, domperidone).',
        '**Ideas, concerns, expectations** — most women fear cancer; explore it.',
      ],
      source: 'Macleod’s 14e · Ch 11 · pp 212–214',
    },
    {
      id: 'exam',
      title: 'Examination (Macleod’s sequence)',
      kind: 'steps',
      intro: 'Always offer a chaperone (male doctors always have one) and record their name. Undress to the waist; sit upright on the side of the bed.',
      items: [
        '**Hands resting on the thighs** (pectorals relaxed): face the patient — asymmetry, local swelling, skin changes (dimpling, tethering, peau d’orange, erythema, ulceration), nipple changes (inversion, deviation, eczema, discharge).',
        '**Hands pressed firmly on the hips** (pectorals contracted): inspect again — tethering becomes obvious.',
        '**Arms raised above the head**, then **leaning forward** with the breasts pendulous: exposes the lower breast and exaggerates dimpling.',
        '**Lie her at 45° with one pillow, hand behind her head** on the side being examined.',
        '**Palpate with the flat of the fingers**, clock-face, each “hour” from the periphery to the nipple (including under the nipple); start with the normal side; cover clavicle to upper abdomen, midline to latissimus dorsi.',
        '**Axillary tail** between finger and thumb.',
        '**Any lump**: site (quadrant/clock, cm from nipple), size, shape, surface, consistency, mobility, tenderness, temperature, overlying skin; **fixation** — hold the lump and ask her to press on her hips: if it moves with the contracted pectoral, it is fixed.',
        '**Lift the breast** to look for dimpling over a lump.',
        '**Nipple**: palpate gently, try to express discharge; massage towards the nipple; note colour, number and position of ducts; dipstick for blood.',
        '**Nodes**: support her arm at the wrist and palpate the axilla (apical, anterior, posterior, medial, lateral groups), then supraclavicular and cervical nodes (from behind).',
        '**Complete**: examine the other breast, abdomen (hepatomegaly), spine (bone tenderness), chest; arrange triple assessment.',
      ],
      source: 'Macleod’s 14e · Ch 11 · pp 214–215 (Figs 11.9–11.11)',
    },
    {
      id: 'lumps',
      title: 'Benign and malignant lumps',
      table: {
        head: ['Lump', 'Who', 'Feel', 'Notes'],
        rows: [
          ['Fibroadenoma', '15–35', 'Smooth, firm/rubbery, very mobile (“breast mouse”), discrete, painless', 'Benign overgrowth of the terminal duct lobule; core biopsy; excise if > 3–4 cm, growing or patient wish'],
          ['Cyst', '35–55 (perimenopausal)', 'Smooth, fluctuant or tense, may be tender; can be multiple', 'Ultrasound; aspirate if symptomatic; investigate blood-stained fluid or a residual mass'],
          ['Fibrocystic change', '20s–40s', 'Rubbery nodularity, often bilateral, upper outer quadrants, cyclical tenderness', 'Re-examine after a period; investigate focal change'],
          ['Fat necrosis', 'Any, after trauma or surgery', 'Hard, irregular, may tether — mimics cancer', 'History of trauma; needs triple assessment'],
          ['Abscess', 'Lactating (peripheral) or young smokers (periareolar)', 'Hot, red, very tender, fluctuant; fever', 'Ultrasound-guided aspiration + antibiotics; incise if skin thin/necrotic'],
          ['Phyllodes tumour', '40s', 'Large, rapidly growing, smooth, mobile', 'Benign to malignant; wide excision'],
          ['Carcinoma', 'Mostly > 50', 'Hard, irregular, ill-defined, may be fixed to skin or muscle, painless', 'Skin dimpling, nipple retraction, peau d’orange, axillary nodes'],
        ],
      },
      source: 'Macleod’s 14e · Ch 11 · pp 215–216',
    },
    {
      id: 'discharge',
      title: 'Nipple discharge and nipple changes',
      table: {
        head: ['Discharge', 'Likely cause'],
        rows: [
          ['Milky, both sides, many ducts', 'Galactorrhoea — pregnancy/lactation, drugs (antipsychotics, metoclopramide), prolactinoma, hypothyroidism'],
          ['Clear/yellow/green, many ducts, often older woman', 'Physiological or duct ectasia'],
          ['Single duct, blood-stained or clear, spontaneous', 'Intraductal papilloma (most common) — exclude DCIS/carcinoma'],
          ['Purulent, with periareolar inflammation, smoker', 'Periductal mastitis / non-lactational abscess, mammary duct fistula'],
        ],
      },
      items: [
        '**Investigate single-duct or blood-stained discharge**: dipstick for blood, cytology, mammography + ultrasound, ± ductoscopy/ductography; **microdochectomy** (single duct excision) gives the diagnosis and cures a papilloma. **Total duct excision (Hadfield’s)** for multi-duct problems in older women.',
        '**Nipple inversion**: longstanding and bilateral is usually benign; new and unilateral needs triple assessment. Duct ectasia gives a slit-like central retraction; cancer pulls the nipple off-centre.',
        '**Paget’s disease of the nipple**: eczematous, red, scaly or ulcerated nipple, unilateral, starts on the nipple and spreads to the areola; underlying DCIS or invasive cancer — punch biopsy. Eczema starts on the areola, is often bilateral and itchy.',
        '**Galactorrhoea** work-up: pregnancy test, prolactin, TFT, drug review; MRI pituitary if prolactin high.',
      ],
      source: 'Macleod’s 14e · Ch 11 · pp 213–214 (Figs 11.6–11.7)',
    },
    {
      id: 'triple',
      title: 'Triple assessment and scoring',
      items: [
        '**Clinical**: P1 normal, P2 benign, P3 uncertain/probably benign, P4 suspicious, P5 malignant.',
        '**Imaging**: ultrasound for women < 40 (dense breasts) and to characterise any lump; mammography + ultrasound ≥ 40 (U1–5 / M1–5). MRI for lobular cancer extent, dense breasts, implants, BRCA carriers.',
        '**Pathology**: ultrasound-guided **core biopsy** (B1 normal, B2 benign, B3 uncertain, B4 suspicious, B5a in situ, B5b invasive). FNA cytology is used for axillary nodes and cysts.',
        'Discussed at the breast MDT; any discordance (e.g. P4 with B2) needs further sampling or excision.',
      ],
      source: 'Macleod’s 14e · Ch 11 · p 216 (Box 11.2)',
    },
    {
      id: 'cancer',
      title: 'Breast cancer',
      items: [
        '**Types**: invasive ductal (no special type, ~75%), invasive lobular (~10–15%, often multifocal/bilateral, hard to see on mammography), special types (mucinous, tubular, medullary); **DCIS** (pre-invasive, often microcalcification on screening).',
        '**Receptors** guide treatment: ER/PR positive (~75% — endocrine therapy), HER2 positive (~15% — trastuzumab), triple-negative (chemotherapy; BRCA1 association).',
        '**Staging**: TNM; CT chest/abdomen/pelvis and bone scan for locally advanced or symptomatic disease.',
        '**Surgery**: breast-conserving (wide local excision + whole-breast radiotherapy) or mastectomy (± reconstruction). **Axilla**: sentinel lymph node biopsy if clinically and ultrasound node-negative; axillary clearance or radiotherapy if nodes involved.',
        '**Adjuvant**: radiotherapy after WLE; endocrine therapy — tamoxifen (premenopausal), aromatase inhibitor (letrozole, anastrozole — postmenopausal) for 5–10 years; trastuzumab for HER2+; chemotherapy for high-risk disease. **Neoadjuvant** chemotherapy for large tumours, HER2+ and triple-negative disease.',
        '**Prognosis**: Nottingham Prognostic Index = 0.2 × size (cm) + grade (1–3) + node score (1–3).',
        '**Screening** (UK): mammography every 3 years from 50 to 71; earlier, annual MRI for high-risk/BRCA carriers.',
      ],
    },
  ],
  cases: ['breast-cancer', 'fibroadenoma', 'duct-papilloma'],
  qa: [
    { q: 'How do you examine the breast?', a: 'Consent and a chaperone; undress to the waist, sitting on the side of the bed. Inspect with hands on thighs, then pressed on the hips, then raised above the head and leaning forward — for asymmetry, lumps, skin dimpling/tethering, peau d’orange, nipple inversion, eczema or discharge. Lie her at 45° with her hand behind her head and palpate each breast with the flat of the fingers clock-face from the periphery to the nipple (normal side first), including the axillary tail and under the nipple. Characterise any lump and test fixation with the pectorals contracted; try to express discharge; then examine the axillary, supraclavicular and cervical nodes. Complete with triple assessment.', k: ['breast examination', 'examine breast lump'] },
    { q: 'What is triple assessment?', a: 'Clinical assessment (history + examination), imaging (ultrasound in women < 40; mammography + ultrasound if ≥ 40) and pathology (ultrasound-guided core biopsy; FNA for nodes/cysts). Each is scored 1–5 and the results are discussed at the MDT; discordant results need further tissue.', k: ['triple test'] },
    { q: 'Why ultrasound rather than mammography in young women?', a: 'Younger breasts are glandular and radiologically dense, so mammography is less sensitive (and the radiation risk is relatively higher). Ultrasound characterises solid vs cystic lumps well.' },
    { q: 'Describe Macleod’s positions for inspecting the breasts.', a: 'Hands resting on the thighs (relaxed), hands pressed on the hips (pectorals contracted — shows tethering), arms raised above the head and leaning forward (exposes the lower breast, accentuates dimpling). Then palpate lying at 45° with the hand behind the head.', k: ['breast examination positions'] },
    { q: 'How do you test whether a breast lump is fixed to the chest wall?', a: 'Hold the lump between finger and thumb, ask the patient to press her hands on her hips to contract pectoralis major, and try to move the lump in the direction of the muscle fibres. A lump that moves with the contracted muscle (but is free when relaxed) is fixed — suggests malignancy.' },
    { q: 'What are the characteristics of a fibroadenoma?', a: 'A smooth, rubbery, discrete, painless, highly mobile lump (“breast mouse”) in a woman aged 15–35. It is a benign overgrowth of the terminal duct lobular unit. Diagnosed by triple assessment; excised if large (> 3–4 cm), growing, symptomatic or at the patient’s request.', k: ['breast mouse'] },
    { q: 'What is the commonest cause of blood-stained nipple discharge?', a: 'Intraductal papilloma — a benign tumour in a major duct near the nipple, usually single-duct discharge in a woman aged 35–55. DCIS or carcinoma must be excluded (imaging, cytology, microdochectomy).', k: ['bloody discharge', 'papilloma'] },
    { q: 'How do you investigate nipple discharge?', a: 'Establish one or many ducts, uni/bilateral, colour, spontaneous or expressed. Dipstick for blood, cytology, mammography + ultrasound ± ductoscopy. Single-duct or blood-stained discharge → microdochectomy. Milky bilateral discharge → pregnancy test, prolactin, TFT, drug history.' },
    { q: 'What is microdochectomy vs total duct excision?', a: 'Microdochectomy excises a single discharging duct (diagnostic and curative for a papilloma; preserves breastfeeding). Total duct excision (Hadfield’s operation) removes all major ducts behind the nipple — for multi-duct discharge or duct ectasia/periductal mastitis in women not planning to breastfeed.' },
    { q: 'What is Paget’s disease of the nipple?', a: 'An eczema-like change of the nipple (red, scaly, crusting, ulcerated) caused by malignant cells from an underlying DCIS or invasive carcinoma infiltrating the epidermis. Unilateral, starts on the nipple and spreads to the areola (eczema starts on the areola, is usually bilateral). Punch biopsy + triple assessment.' },
    { q: 'What is duct ectasia?', a: 'Dilatation and inflammation of the major subareolar ducts, usually in perimenopausal/older women: thick green/cream discharge from several ducts, slit-like nipple retraction, sometimes a subareolar mass. Benign; exclude cancer; duct excision if troublesome.' },
    { q: 'What is periductal mastitis?', a: 'Inflammation around the subareolar ducts in young women — strongly associated with smoking. Causes periareolar pain, inflammation, non-lactational abscess, nipple retraction and mammary duct fistula. Treat with antibiotics (anaerobic cover), drainage, smoking cessation; recurrence is common.' },
    { q: 'How do you manage a breast abscess?', a: 'Ultrasound to confirm a collection, repeated ultrasound-guided needle aspiration with antibiotics (flucloxacillin; add metronidazole/co-amoxiclav for non-lactational). Incision and drainage if the skin is thin or necrotic. Encourage continued breastfeeding or expressing from the affected side in lactational abscess.' },
    { q: 'What are the signs of breast cancer on inspection?', a: 'Asymmetry, a visible lump, skin dimpling or tethering, peau d’orange (lymphoedema), erythema, ulceration, nipple retraction (off-centre), nipple deviation, Paget’s change, blood-stained discharge.' },
    { q: 'What is peau d’orange?', a: 'Orange-peel skin: lymphoedema of the breast skin from blocked dermal lymphatics, with the skin pitted at hair follicles. Associated with locally advanced or inflammatory breast cancer (also infection).', k: ['orange peel'] },
    { q: 'What are the risk factors for breast cancer?', a: 'Female sex, age, previous breast cancer or atypical hyperplasia, family history/BRCA1/2 (and TP53, PALB2), prolonged oestrogen exposure (early menarche, late menopause, nulliparity, first pregnancy > 30, no breastfeeding), HRT and combined pill, postmenopausal obesity, alcohol, previous chest radiotherapy (Hodgkin’s mantle field).' },
    { q: 'What do BRCA1 and BRCA2 confer?', a: 'Autosomal dominant tumour-suppressor gene mutations. BRCA1: lifetime breast cancer risk ~60–70% and ovarian ~40%, often triple-negative. BRCA2: breast ~45–70%, ovarian ~15%, male breast and prostate cancer. Options: MRI surveillance, risk-reducing mastectomy and salpingo-oophorectomy.' },
    { q: 'What is the significance of ER/PR and HER2 status?', a: 'ER/PR-positive tumours respond to endocrine therapy (tamoxifen, aromatase inhibitors) and have a better prognosis. HER2-positive tumours are more aggressive but respond to trastuzumab (and pertuzumab). Triple-negative tumours rely on chemotherapy and have a worse prognosis.', k: ['receptor status', 'triple negative'] },
    { q: 'Tamoxifen or an aromatase inhibitor?', a: 'Tamoxifen (a selective oestrogen receptor modulator) for premenopausal women — side effects: hot flushes, VTE, endometrial cancer. Aromatase inhibitors (anastrozole, letrozole) for postmenopausal women — they block peripheral oestrogen production; side effects: arthralgia, osteoporosis (monitor bone density).' },
    { q: 'What is a sentinel lymph node biopsy?', a: 'Identifying and removing the first draining axillary node(s) using radioisotope ± blue dye injected near the tumour/areola. If negative, axillary clearance (with its lymphoedema and nerve injury risks) is avoided. Used when the axilla is clinically and ultrasound negative.', k: ['SLNB'] },
    { q: 'What is the Nottingham Prognostic Index?', a: 'NPI = 0.2 × tumour size (cm) + histological grade (1–3) + lymph node score (1 = none, 2 = 1–3 nodes, 3 = ≥ 4 nodes). Lower scores predict better survival (< 3.4 good; > 5.4 poor).', k: ['NPI'] },
    { q: 'When is mastectomy chosen over wide local excision?', a: 'Large tumour relative to breast size, multicentric disease, extensive DCIS, central tumour (relative), contraindication to radiotherapy (previous radiotherapy, pregnancy), BRCA carriers or patient preference. WLE + radiotherapy gives equivalent survival when feasible.', k: ['breast conserving surgery', 'WLE'] },
    { q: 'What is DCIS?', a: 'Ductal carcinoma in situ: malignant cells confined within the ducts (basement membrane intact), usually found as microcalcification on screening mammography. Treated by excision with clear margins (± radiotherapy) or mastectomy if extensive; it can progress to invasive cancer.' },
    { q: 'What is the UK breast screening programme?', a: 'Mammography every 3 years for women aged 50–71 (self-referral after 71). Higher-risk women (strong family history, BRCA, previous mantle radiotherapy) have earlier and/or MRI surveillance.' },
    { q: 'What causes gynaecomastia?', a: 'Physiological (neonates, puberty, old age), drugs (spironolactone, digoxin, oestrogens, anti-androgens, cimetidine, cannabis, anabolic steroids), chronic liver disease, thyrotoxicosis, renal failure, hypogonadism (Klinefelter’s), testicular or adrenal tumours (hCG/oestrogen-secreting). Examine the testes.' },
  ],
}

export default t
