import type { Topic } from '../types'

const t: Topic = {
  id: 'complicated-hernia',
  title: 'Complicated hernia',
  short: 'Hernia',
  blurb:
    'When a hernia stops being a nuisance and becomes an emergency: irreducible, obstructed and strangulated hernias, how to tell them apart at the bedside, the anatomy that decides inguinal from femoral, and the operations that fix them.',
  keyPoints: [
    'Irreducible (incarcerated) → obstructed (bowel lumen blocked) → strangulated (blood supply cut off: ischaemia, then gangrene).',
    'Strangulation: tense, tender, irreducible, no cough impulse, red overlying skin, signs of obstruction and systemic toxicity — an emergency operation.',
    'Inguinal hernias appear above and medial to the pubic tubercle; femoral hernias below and lateral. Femoral hernias strangulate most often.',
    'At the bedside: reduce the hernia, press over the deep ring (mid-inguinal point) and ask the patient to cough — controlled = indirect, reappears = direct.',
    'Always examine the hernial orifices in any patient with bowel obstruction — a small femoral hernia in an elderly woman is easily missed.',
    'Never force reduction of a hernia that may be strangulated (reduction en masse returns dead bowel into the abdomen).',
  ],
  sections: [
    {
      id: 'definitions',
      title: 'Definitions',
      items: [
        '**Hernia**: protrusion of a viscus or part of it through a defect in the wall of its containing cavity. Parts: sac (peritoneum), neck (the narrowest point, where compression happens), contents, coverings.',
        '**Reducible**: contents return to the abdomen spontaneously or with gentle pressure.',
        '**Irreducible (incarcerated)**: cannot be reduced — usually adhesions within the sac or a narrow neck; not necessarily ischaemic.',
        '**Obstructed**: bowel in the sac with its lumen blocked → intestinal obstruction, blood supply still intact.',
        '**Strangulated**: blood supply compromised — venous congestion, then arterial occlusion, ischaemia, gangrene and perforation.',
        '**Richter’s hernia**: only part of the bowel wall (antimesenteric) is trapped — can strangulate and perforate without causing obstruction. Typical of femoral hernias.',
        '**Sliding hernia**: a viscus (sigmoid, caecum or bladder) forms part of the sac wall.',
        '**Eponyms**: Littre’s (Meckel’s diverticulum in the sac), Amyand’s (appendix in an inguinal hernia), de Garengeot’s (appendix in a femoral hernia), Maydl’s (W-loop: the strangulated loop is inside the abdomen), pantaloon (direct + indirect).',
      ],
      source: 'Macleod’s 14e · Ch 6 · pp 110–111 (Fig 6.21)',
    },
    {
      id: 'anatomy',
      title: 'Anatomy that decides the diagnosis',
      items: [
        '**Inguinal canal**: from the deep ring (mid-inguinal point, midway between ASIS and pubic symphysis, just above the femoral pulse) to the superficial ring (just above and lateral to the pubic tubercle).',
        '**Indirect inguinal hernia**: through the deep ring, lateral to the inferior epigastric vessels, down the canal; may reach the scrotum. 85% of inguinal hernias; younger men; patent processus vaginalis.',
        '**Direct inguinal hernia**: through Hesselbach’s triangle (posterior wall weakness), medial to the inferior epigastric vessels; rarely enters the scrotum; older men; broad neck, low strangulation risk.',
        '**Hesselbach’s triangle**: inguinal ligament (below), inferior epigastric vessels (lateral), lateral border of rectus abdominis (medial).',
        '**Femoral canal**: below the inguinal ligament, medial to the femoral vein. Boundaries of the femoral ring: inguinal ligament (anterior), pectineal ligament (posterior), lacunar ligament (medial), femoral vein (lateral). Narrow and rigid — hence strangulation.',
        'Femoral hernias are commoner in women (but inguinal hernias are still the commonest hernia in women).',
      ],
      table: {
        head: ['', 'Inguinal', 'Femoral'],
        rows: [
          ['Position', 'Above and medial to the pubic tubercle', 'Below and lateral to the pubic tubercle'],
          ['Typical patient', 'Men (all ages)', 'Older women'],
          ['Cough impulse', 'Usually present', 'Often absent (narrow neck)'],
          ['Strangulation risk', 'Low (indirect > direct)', 'High — often presents as an emergency'],
        ],
      },
      source: 'Macleod’s 14e · Ch 6 · p 110 (Fig 6.19)',
    },
    {
      id: 'history',
      title: 'History',
      items: [
        '**The lump**: when noticed, size change, does it go back (on lying down, by hand), how long has it been irreducible.',
        '**Pain**: dull dragging ache is typical of an uncomplicated hernia; constant severe pain in a lump that has become hard and tender suggests strangulation.',
        '**Obstruction**: colicky central abdominal pain, vomiting (bilious, later faeculent), distension, absolute constipation (no flatus).',
        '**Precipitants / raised intra-abdominal pressure**: chronic cough, constipation and straining, prostatism, heavy lifting, ascites, pregnancy, obesity.',
        '**Previous hernia repair** or abdominal surgery (incisional hernia, adhesions).',
        '**Fitness**: comorbidities, anticoagulants, smoking — for theatre.',
      ],
      source: 'Macleod’s 14e · Ch 6 · p 102 (groin swellings)',
    },
    {
      id: 'exam',
      title: 'Examination of a groin hernia',
      kind: 'steps',
      intro: 'Explain, consent, offer a chaperone; expose from the umbilicus to the knees, keeping the genitals covered as far as possible.',
      items: [
        '**Standing**: inspect both groins and the scrotum for a lump; note size, shape, overlying skin (erythema suggests strangulation).',
        '**Cough**: look for an impulse over the inguinal and femoral canals and the scrotum.',
        '**Locate** the lump relative to the pubic tubercle and inguinal ligament — above and medial = inguinal, below and lateral = femoral.',
        '**Palpate**: tenderness, temperature, consistency, a cough impulse; can you get above it (a scrotal lump you can get above is not a hernia)?',
        '**Lying**: does it reduce spontaneously? If not tender, try gentle reduction (the patient can often do it).',
        '**Deep-ring occlusion test**: press two fingers over the mid-inguinal point and ask the patient to cough or stand — controlled = indirect, reappears medially = direct.',
        '**Auscultate** over the lump for bowel sounds.',
        '**Examine the other side**, the scrotum/testes, and the abdomen (distension, tenderness, scars, other hernias — umbilical, incisional).',
        '**Complete**: abdominal examination for obstruction, and DRE where indicated.',
      ],
      note: 'A strangulated hernia is tense, tender and irreducible with no cough impulse — do not try to reduce it.',
      source: 'Macleod’s 14e · Ch 6 · pp 110–111',
    },
    {
      id: 'strangulation',
      title: 'Recognising strangulation',
      items: [
        '**Local**: hernia irreducible, tense, very tender, warm, red or dusky overlying skin; no cough impulse.',
        '**Obstruction**: colicky pain, vomiting, distension, tinkling or absent bowel sounds.',
        '**Systemic**: fever, tachycardia, hypotension, rising lactate and white cell count — late signs.',
        'Change from colicky to constant pain with abdominal tenderness means ischaemia.',
        'A Richter’s hernia can strangulate without obstruction — beware a tender groin lump in an elderly patient with diarrhoea or vague pain.',
      ],
      source: 'Macleod’s 14e · Ch 6 · pp 97, 111',
    },
    {
      id: 'investigations',
      title: 'Investigations',
      items: [
        '**Bloods**: FBC (leucocytosis), U&E (dehydration from vomiting, AKI), CRP, **VBG/lactate** (ischaemia), amylase, group and save, clotting.',
        '**Imaging is not needed** for an obviously strangulated groin hernia — go to theatre.',
        '**Abdominal X-ray**: dilated small bowel loops; gas in the hernia.',
        '**CT abdomen/pelvis**: obstruction with a transition point at a hernia, obturator or internal hernias, signs of ischaemia (reduced enhancement, free fluid, pneumatosis).',
        '**Ultrasound** for diagnostic doubt in an uncomplicated groin lump (occult hernia, lymph node, saphena varix).',
      ],
    },
    {
      id: 'management',
      title: 'Management',
      items: [
        '**Resuscitate**: IV access, fluids, analgesia, NBM, NG tube if vomiting or obstructed, urinary catheter, correct electrolytes; antibiotics if strangulation is suspected.',
        '**Emergency surgery** for a strangulated or obstructed hernia. Inspect the bowel after releasing the constriction — viable bowel pinks up, has peristalsis and mesenteric pulsation (warm saline packs, wait 5–10 min); resect non-viable bowel.',
        '**Femoral hernia approaches**: low (Lockwood, below the inguinal ligament), high (Lotheissen, through the inguinal canal), or McEvedy (high extraperitoneal) — the high approaches allow bowel resection.',
        '**Inguinal repair**: Lichtenstein tension-free open mesh repair, or laparoscopic TEP/TAPP (preferred for bilateral and recurrent hernias).',
        '**Mesh in emergencies**: acceptable in a clean field even with bowel strangulation (no resection); avoid permanent mesh in a contaminated field (suture repair or biological mesh).',
        '**Elective**: femoral hernias should all be repaired promptly; symptomatic inguinal hernias repaired; minimally symptomatic inguinal hernias in men may be watched.',
        '**Taxis** (gentle manual reduction, with analgesia) only for an early irreducible hernia without signs of strangulation, then admit and observe.',
      ],
    },
    {
      id: 'other',
      title: 'Other hernias to know',
      items: [
        '**Incisional**: at a previous scar (risk: wound infection, obesity, smoking, steroids, malnutrition, midline laparotomy). Wide necks rarely strangulate; narrow ones can. Repair with retrorectus (Rives–Stoppa) mesh, component separation for large defects, or laparoscopic IPOM.',
        '**Umbilical/paraumbilical**: in adults acquired (obesity, ascites, pregnancy); narrow neck — can incarcerate. In cirrhosis with ascites the skin may ulcerate and rupture.',
        '**Obturator**: elderly thin women; small bowel obstruction with pain down the medial thigh (Howship–Romberg sign — pain on internal rotation of the hip); diagnosed on CT.',
        '**Spigelian**: through the linea semilunaris at the arcuate line, under the external oblique — easily missed; ultrasound/CT.',
        '**Epigastric**: midline through the linea alba between xiphoid and umbilicus; usually fat only.',
        '**Hiatus hernia**: sliding (type I, 90%) or para-oesophageal (rolling) — the latter can volve and strangulate (Borchardt’s triad).',
      ],
    },
  ],
  cases: ['strangulated-inguinal', 'femoral-hernia', 'sbo-femoral', 'inguinal-hernia', 'direct-hernia'],
  qa: [
    { q: 'How do you examine a groin hernia?', a: 'Expose umbilicus to knees (genitals covered), patient standing. Inspect both groins and the scrotum; ask the patient to cough and look for an impulse. Relate the lump to the pubic tubercle (inguinal above and medial, femoral below and lateral). Palpate: tenderness, consistency, cough impulse, can you get above it. Lie the patient down — does it reduce (spontaneously or gently by the patient)? Occlude the deep ring at the mid-inguinal point and ask them to cough: controlled = indirect. Examine the other side, the scrotum and the abdomen.', k: ['hernia examination', 'inguinal hernia examination'] },
    { q: 'Define irreducible, obstructed and strangulated hernia.', a: 'Irreducible (incarcerated): contents cannot be returned to the abdomen. Obstructed: bowel lumen within the hernia is blocked (intestinal obstruction) but blood supply is intact. Strangulated: the blood supply to the contents is compromised — ischaemia leading to gangrene; a surgical emergency.', k: ['incarcerated', 'definitions'] },
    { q: 'What are the signs of a strangulated hernia?', a: 'A tense, very tender, irreducible lump with no cough impulse, often with red or dusky overlying skin; features of bowel obstruction (colic, vomiting, distension, absolute constipation); and systemic toxicity — fever, tachycardia, hypotension, raised WCC and lactate. Colicky pain becoming constant suggests ischaemia.' },
    { q: 'How do you distinguish an inguinal from a femoral hernia?', a: 'By its relation to the pubic tubercle: an inguinal hernia emerges above and medial to it; a femoral hernia lies below and lateral to it (below the inguinal ligament, in the femoral canal medial to the femoral vein).', k: ['pubic tubercle'] },
    { q: 'How do you tell a direct from an indirect inguinal hernia clinically?', a: 'Reduce the hernia with the patient lying, then occlude the deep ring with two fingers at the mid-inguinal point and ask the patient to cough or stand. If the hernia is controlled it is indirect; if it reappears (medially) it is direct. The distinction is unreliable clinically and is confirmed at operation (relation to the inferior epigastric vessels).', k: ['deep ring occlusion test', 'internal ring'] },
    { q: 'What are the boundaries of the inguinal canal?', a: 'Anterior: external oblique aponeurosis (+ internal oblique laterally). Posterior: transversalis fascia (+ conjoint tendon medially). Roof: arching fibres of internal oblique and transversus abdominis. Floor: inguinal ligament (+ lacunar ligament medially). Mnemonic MALT: 2 Muscles, 2 Aponeuroses, 2 Ligaments, 2 Tendons/fascia.' },
    { q: 'What are the contents of the inguinal canal?', a: 'In men the spermatic cord (vas deferens, testicular artery, pampiniform plexus, artery to the vas, cremasteric artery, genital branch of the genitofemoral nerve, lymphatics, processus vaginalis remnant); in women the round ligament. Both: the ilioinguinal nerve (which enters the canal but not the deep ring).' },
    { q: 'Where is the deep (internal) ring?', a: 'At the mid-inguinal point — midway between the anterior superior iliac spine and the pubic symphysis — about 1–2 cm above the femoral pulse, lateral to the inferior epigastric vessels.', k: ['mid-inguinal point', 'internal ring'] },
    { q: 'What are the boundaries of Hesselbach’s triangle?', a: 'Inguinal ligament inferiorly, inferior epigastric vessels laterally, lateral border of rectus abdominis medially. Direct hernias come through it.', k: ['inguinal triangle'] },
    { q: 'What are the boundaries of the femoral ring?', a: 'Anterior: inguinal ligament. Posterior: pectineal (Cooper’s) ligament. Medial: lacunar ligament. Lateral: femoral vein. It contains fat, lymphatics and Cloquet’s node.', k: ['femoral canal'] },
    { q: 'Why do femoral hernias strangulate so often?', a: 'The femoral ring is narrow with rigid boundaries (especially the sharp lacunar ligament medially), so trapped bowel is easily compressed. Up to 40% present as emergencies — all femoral hernias should be repaired promptly.' },
    { q: 'What is a Richter’s hernia and why is it dangerous?', a: 'Only part of the circumference of the bowel wall (the antimesenteric border) is trapped. The lumen stays open, so there may be no obstruction — yet that part of the wall can strangulate and perforate. Typical of femoral hernias.', k: ['Richter'] },
    { q: 'What is a sliding hernia?', a: 'A hernia in which a retroperitoneal viscus (sigmoid colon on the left, caecum on the right, or bladder) forms part of the wall of the sac — important because opening the sac carelessly can injure that viscus.' },
    { q: 'Name the eponymous hernias.', a: 'Littre’s (Meckel’s diverticulum), Amyand’s (appendix in an inguinal hernia), de Garengeot’s (appendix in a femoral hernia), Richter’s (part of the bowel wall), Maydl’s (W-loop; the strangulated loop is intra-abdominal), Spigelian (linea semilunaris), Petersen’s (internal hernia after gastric bypass), pantaloon (combined direct and indirect).' },
    { q: 'How do you assess bowel viability at operation?', a: 'After releasing the constriction: colour (pink, not black/green), sheen, visible peristalsis, pulsation in the mesenteric vessels, bleeding from cut edges. Wrap doubtful bowel in warm saline packs and re-inspect after 5–10 minutes; resect if non-viable. Indocyanine green fluorescence can help.' },
    { q: 'What are the approaches to a femoral hernia repair?', a: 'Low (Lockwood) — below the inguinal ligament, for elective repair. High (Lotheissen) — through the posterior wall of the inguinal canal. High extraperitoneal (McEvedy) — vertical incision over the canal; best in emergencies as it allows bowel resection. Laparoscopic TEP/TAPP is also used.' },
    { q: 'What is a Lichtenstein repair?', a: 'An open tension-free inguinal hernia repair: after dealing with the sac, a polypropylene mesh is sutured to the inguinal ligament and conjoint tendon/rectus sheath, reinforcing the posterior wall, with a slit around the spermatic cord.', k: ['mesh repair'] },
    { q: 'When is laparoscopic inguinal hernia repair preferred?', a: 'Bilateral hernias, recurrence after open repair, and in women (to see and repair an occult femoral hernia). Options: TEP (totally extraperitoneal) and TAPP (transabdominal preperitoneal).', k: ['TEP', 'TAPP'] },
    { q: 'What are the complications of inguinal hernia repair?', a: 'Early: haematoma, seroma, wound infection, urinary retention. Late: chronic groin pain (ilioinguinal, iliohypogastric or genital branch of the genitofemoral nerve), recurrence, mesh infection, testicular atrophy (ischaemic orchitis from cord damage), injury to the vas deferens.' },
    { q: 'What is “reduction en masse”?', a: 'Forcibly reducing a strangulated hernia together with its constricting neck/sac, so the bowel disappears from the groin but stays strangulated inside the abdomen. Avoid forceful reduction of a tender, tense hernia.' },
    { q: 'When can you attempt to reduce an irreducible hernia (taxis)?', a: 'Only an early irreducible hernia without features of strangulation (not tense, not very tender, no obstruction, no toxicity), with analgesia and the patient lying with knees flexed. Admit and observe afterwards; the hernia still needs repair.', k: ['taxis'] },
    { q: 'What is the commonest cause of small bowel obstruction?', a: 'Adhesions in patients who have had abdominal surgery (in high-income countries); hernias where elective repair is less available, and in patients with no previous surgery. Always examine the hernial orifices.' },
    { q: 'What is the Howship–Romberg sign?', a: 'Pain down the medial thigh to the knee, worse on internal rotation/extension of the hip — compression of the obturator nerve by an obturator hernia (typically elderly thin women presenting with small bowel obstruction).', k: ['obturator hernia'] },
    { q: 'What are the risk factors for an incisional hernia?', a: 'Patient: obesity, smoking, diabetes, malnutrition, steroids, chronic cough, connective tissue disease. Operation: midline laparotomy, emergency surgery, poor closure technique (small-bite closure with a suture:wound length ratio of at least 4:1 reduces risk). Post-operative: wound infection, dehiscence, ascites.' },
    { q: 'Can you put a mesh in an emergency hernia repair?', a: 'Yes in a clean field — a strangulated hernia without bowel resection or contamination. With gross contamination (resection, perforation) avoid permanent synthetic mesh: suture repair, a biological/biosynthetic mesh, or a staged repair.' },
    { q: 'What is the differential of a groin lump?', a: 'Inguinal or femoral hernia, lymph nodes, saphena varix (cough impulse, thrill, disappears lying down), femoral artery aneurysm (expansile), hydrocele of the cord/canal of Nuck, undescended or ectopic testis, lipoma of the cord, psoas abscess (lateral, with back symptoms), sebaceous cyst.', k: ['differential diagnosis'] },
    { q: 'How do you distinguish a saphena varix from a femoral hernia?', a: 'A saphena varix is a dilatation of the long saphenous vein at the saphenofemoral junction: soft, compressible, disappears on lying down, has a fluid thrill when the varicosities below are tapped, a bluish tinge and a cough impulse; associated varicose veins. Duplex ultrasound confirms.' },
    { q: 'Why might a patient with ascites develop an umbilical hernia, and what is the danger?', a: 'Raised intra-abdominal pressure and weak tissues. The overlying skin may ulcerate and rupture, leaking ascites (Flood syndrome) — a high-mortality emergency; control ascites and consider repair when stable.' },
  ],
}

export default t
