import type { Topic } from '../types'

const t: Topic = {
  id: 'distension',
  title: 'Abdominal distension',
  short: 'Distension',
  blurb:
    'A swollen abdomen is fat, fluid, flatus, faeces, fetus — or a growth. The session is about telling them apart at the bedside, recognising bowel obstruction and its dangerous variants (closed loop, volvulus, strangulation), and assessing and treating ascites.',
  keyPoints: [
    'The 5 (6) Fs: Fat, Fluid (ascites), Flatus (obstruction, ileus), Faeces, Fetus — and Fulminant growth / Full bladder.',
    'Tympanic percussion = gas; dullness in the flanks that shifts when the patient rolls = ascites.',
    'Small bowel obstruction: early vomiting, central colic, late constipation. Large bowel: early constipation, marked distension, late vomiting.',
    'Always examine the hernial orifices and do a rectal examination in obstruction.',
    'AXR rule 3–6–9: small bowel > 3 cm, colon > 6 cm, caecum > 9 cm are dilated. Coffee-bean loop from the pelvis to the RUQ = sigmoid volvulus.',
    'Ascites: SAAG ≥ 11 g/L = portal hypertension; neutrophils > 250/mm³ in the fluid = spontaneous bacterial peritonitis.',
  ],
  sections: [
    {
      id: 'causes',
      title: 'Causes — the Fs',
      table: {
        head: ['Cause', 'Clues'],
        rows: [
          ['Fat', 'Slowly increasing girth, generalised obesity, sunken umbilicus'],
          ['Fluid (ascites)', 'Bulging flanks, everted umbilicus, shifting dullness, fluid thrill; stigmata of liver disease or malignancy'],
          ['Flatus', 'Tympanic, tense; obstruction (colic, vomiting, constipation) or ileus (silent)'],
          ['Faeces', 'Constipation, indentable masses, loaded rectum'],
          ['Fetus', 'Woman of childbearing age — pregnancy test'],
          ['Growth / full bladder', 'Localised dull mass (ovarian tumour, huge liver/spleen, retention — dull suprapubic mass you can’t get below)'],
        ],
      },
      note: 'Functional bloating fluctuates through the day and settles overnight (irritable bowel syndrome).',
      source: 'Macleod’s 14e · Ch 6 · p 99; p 106 (Fig 6.12)',
    },
    {
      id: 'obstruction',
      title: 'Bowel obstruction',
      table: {
        head: ['', 'Small bowel', 'Large bowel'],
        rows: [
          ['Common causes', 'Adhesions, hernias, Crohn’s stricture, tumour, gallstone ileus, intussusception', 'Colorectal cancer, sigmoid volvulus, diverticular stricture, pseudo-obstruction'],
          ['Pain', 'Central colic, frequent', 'Lower abdominal colic, less frequent'],
          ['Vomiting', 'Early, bilious', 'Late, may be faeculent'],
          ['Distension', 'Moderate, central', 'Marked, flanks'],
          ['Constipation', 'Late', 'Early (absolute)'],
          ['AXR', 'Central loops > 3 cm; valvulae conniventes cross the full width', 'Peripheral loops > 6 cm (caecum > 9 cm); haustra cross part of the width'],
        ],
      },
      items: [
        '**Closed-loop obstruction** (both ends blocked — volvulus, or a large-bowel obstruction with a competent ileocaecal valve): rapid distension, high risk of ischaemia and caecal perforation.',
        '**Strangulation**: constant pain, tenderness, peritonism, fever, tachycardia, raised lactate — operate.',
        '**Paralytic ileus**: no colic, absent bowel sounds; after surgery, electrolyte disturbance (low K⁺, Mg²⁺), opioids, sepsis, retroperitoneal haematoma.',
        '**Pseudo-obstruction (Ogilvie’s)**: massive colonic dilatation without a mechanical cause in frail, ill patients; risk of caecal perforation if > 12 cm.',
      ],
      source: 'Macleod’s 14e · Ch 6 · pp 97–99',
    },
    {
      id: 'history',
      title: 'History',
      items: [
        '**Onset and pace**: hours (obstruction, volvulus), weeks (ascites, tumour), years (obesity).',
        '**Obstructive symptoms**: colic, vomiting (when, bilious or faeculent), last flatus and bowel motion, change in bowel habit and rectal bleeding before this (cancer).',
        '**Previous abdominal surgery** (adhesions), known hernias, previous volvulus.',
        '**Liver disease**: alcohol, viral hepatitis risk factors, jaundice, previous variceal bleeding, ankle swelling.',
        '**Malignancy**: weight loss, appetite, early satiety; in women, ovarian cancer symptoms (bloating, pelvic pain, urinary frequency).',
        '**Cardiac/renal**: breathlessness, orthopnoea (right heart failure), frothy urine (nephrotic).',
        '**Drugs**: opioids, anticholinergics, antipsychotics (constipation, pseudo-obstruction); diuretics.',
        'Elderly, institutionalised, constipated patients on psychiatric drugs: think **sigmoid volvulus**.',
      ],
    },
    {
      id: 'exam',
      title: 'Examination',
      kind: 'steps',
      items: [
        '**General**: hydration, cachexia, jaundice, signs of chronic liver disease (palmar erythema, spider naevi, gynaecomastia, asterixis), lymph nodes including Virchow’s.',
        '**Inspect**: generalised or localised swelling, flanks (bulge in ascites), umbilicus (everted in ascites, sunken in obesity), scars, hernias, visible peristalsis, dilated veins (caput medusae).',
        '**Palpate**: tenderness and peritonism, masses, organomegaly (may need dipping/ballotting if ascites), hernial orifices.',
        '**Percuss**: tympanic (gas) vs dull (fluid/mass); **shifting dullness** — percuss from the midline to the flank until dull, keep your finger there, roll the patient away, wait ~10 s, re-percuss: resonant = ascites.',
        '**Fluid thrill** in tense ascites: flick one flank, feel the other, with the patient’s or an assistant’s hand edge in the midline.',
        '**Auscultate**: tinkling (obstruction), absent (ileus/peritonitis), succussion splash (gastric outlet obstruction).',
        '**Complete**: DRE (empty rectum in obstruction, tumour, faecal loading), external genitalia, legs for oedema, JVP.',
      ],
      source: 'Macleod’s 14e · Ch 6 · pp 104–110 (Figs 6.17–6.18)',
    },
    {
      id: 'investigations',
      title: 'Investigations',
      items: [
        '**Bloods**: FBC, U&E (dehydration, low K⁺), LFT and albumin, coagulation, CRP, lactate/VBG, amylase; Ca-125 in women with ascites.',
        '**AXR**: dilated loops and their pattern; coffee-bean sign (sigmoid volvulus), embryo/comma shape in the left upper quadrant (caecal volvulus).',
        '**CT abdomen/pelvis with contrast**: cause and level (transition point), closed loop, ischaemia (poor wall enhancement, pneumatosis, free fluid), tumour staging, “whirl” sign of volvulus.',
        '**Water-soluble contrast (Gastrografin) study** in adhesional small bowel obstruction: contrast in the colon within 24 h predicts resolution and is mildly therapeutic.',
        '**Ultrasound**: ascites, liver texture, portal vein, ovarian masses.',
        '**Diagnostic ascitic tap**: cell count (neutrophils > 250/mm³ = SBP), albumin (SAAG), total protein, Gram stain and culture (in blood culture bottles), cytology, amylase, glucose.',
      ],
    },
    {
      id: 'ascites',
      title: 'Ascites',
      table: {
        head: ['SAAG', 'Meaning', 'Causes'],
        rows: [
          ['≥ 11 g/L (high gradient)', 'Portal hypertension', 'Cirrhosis, alcoholic hepatitis, heart failure, constrictive pericarditis, Budd–Chiari, portal vein thrombosis, massive liver metastases'],
          ['< 11 g/L (low gradient)', 'Not portal hypertension', 'Peritoneal carcinomatosis, TB peritonitis, pancreatitis, nephrotic syndrome, serositis'],
        ],
      },
      items: [
        '**SAAG** = serum albumin − ascitic albumin (same day).',
        '**SBP**: fever, abdominal pain, confusion or simply deterioration in a cirrhotic — ascitic neutrophils > 250/mm³; IV antibiotics (cefotaxime/co-amoxiclav) + albumin; long-term prophylaxis (ciprofloxacin/co-trimoxazole) afterwards.',
        '**Treatment of cirrhotic ascites**: salt restriction (< 5 g/day salt), spironolactone ± furosemide, daily weights (lose ≤ 0.5 kg/day without oedema); therapeutic paracentesis with **20% albumin (about 8 g per litre removed when > 5 L)**; TIPS or transplant for refractory ascites.',
        '**Malignant ascites**: therapeutic paracentesis, indwelling drain, treat the primary.',
      ],
      source: 'Macleod’s 14e · Ch 6 · pp 109–110 (Box 6.14)',
    },
    {
      id: 'management',
      title: 'Managing obstruction',
      items: [
        '**“Drip and suck”**: IV fluids and electrolyte replacement (especially potassium), NG tube on free drainage, NBM, analgesia and antiemetic, catheter and fluid balance, VTE prophylaxis.',
        '**Operate urgently** for strangulation, closed loop, peritonitis, an obstructed hernia, or failure to resolve (usually within 48–72 h for adhesions).',
        '**Adhesional SBO** without strangulation: conservative + Gastrografin challenge; most settle.',
        '**Sigmoid volvulus**: endoscopic decompression (flexible sigmoidoscopy + flatus tube); recurrence is common, so offer elective sigmoid colectomy; gangrene or perforation → Hartmann’s procedure.',
        '**Caecal volvulus**: surgery (right hemicolectomy) — endoscopic decompression rarely works.',
        '**Malignant large bowel obstruction**: resection (Hartmann’s or resection with anastomosis ± stoma), defunctioning stoma, or a colonic stent as a bridge or palliation.',
        '**Pseudo-obstruction**: treat the cause (electrolytes, drugs), neostigmine (with cardiac monitoring), colonoscopic decompression; surgery if perforation threatens.',
      ],
    },
  ],
  cases: ['sigmoid-volvulus', 'liver-disease', 'sbo-femoral', 'caecal-cancer'],
  qa: [
    { q: 'What are the causes of abdominal distension?', a: 'The 5 Fs: Fat, Fluid (ascites, also a cystic tumour or full bladder), Flatus (obstruction, ileus, pseudo-obstruction), Faeces, Fetus — plus a large growth (ovarian tumour, organomegaly).', k: ['5 Fs', 'six Fs'] },
    { q: 'How do you elicit shifting dullness?', a: 'With the patient supine, percuss from the midline towards the flank until the note becomes dull. Keep your finger there, ask the patient to roll away from you, wait about 10 seconds, and percuss again. If the dull area is now resonant, shifting dullness is present (about 500 mL+ of ascites).', k: ['ascites test'] },
    { q: 'How do you test for a fluid thrill?', a: 'Place one hand flat on one flank and flick the other flank; ask the patient or an assistant to press the edge of a hand into the midline to stop transmission through fat. A ripple felt in the far hand = fluid thrill — present only in gross, tense ascites.' },
    { q: 'How do you differentiate small and large bowel obstruction?', a: 'SBO: central colic, early bilious vomiting, moderate central distension, late constipation; AXR central loops > 3 cm with valvulae conniventes across the full width. LBO: earlier absolute constipation, marked distension, late (faeculent) vomiting; AXR peripheral loops > 6 cm (caecum > 9 cm) with haustra crossing part of the width.', k: ['SBO vs LBO'] },
    { q: 'What is the 3-6-9 rule?', a: 'On an AXR, small bowel is dilated if > 3 cm, colon if > 6 cm, and caecum if > 9 cm (caecal perforation risk rises sharply above 12 cm).' },
    { q: 'What are the causes of small bowel obstruction?', a: 'Extraluminal: adhesions (commonest after surgery), hernias (external or internal), volvulus, tumours. Intramural: Crohn’s strictures, tumours, radiation stricture, ischaemia. Intraluminal: gallstone ileus, bezoar, intussusception, foreign body.' },
    { q: 'What are the causes of large bowel obstruction?', a: 'Colorectal cancer (most common), sigmoid or caecal volvulus, diverticular stricture, faecal impaction, hernia, and functional pseudo-obstruction (Ogilvie’s).' },
    { q: 'What is a closed-loop obstruction and why is it dangerous?', a: 'A segment of bowel blocked at both ends — volvulus, a loop trapped in a hernia, or large-bowel obstruction with a competent ileocaecal valve. Gas and fluid cannot escape, pressure rises fast, blood supply fails and the bowel (often the caecum) perforates. Needs urgent decompression or surgery.' },
    { q: 'What is the conservative management of bowel obstruction?', a: '“Drip and suck”: NBM, wide-bore NG tube on free drainage, IV fluids with potassium, analgesia, antiemetic, catheter and strict fluid balance, serial examination, and correction of electrolytes. Suitable for adhesional SBO without signs of strangulation.' },
    { q: 'What are the indications for surgery in bowel obstruction?', a: 'Signs of strangulation or peritonitis (constant pain, tenderness, fever, tachycardia, raised lactate/WCC), closed-loop obstruction, obstructed/strangulated hernia, no previous surgery (no adhesions to blame — likely a hernia or tumour), and failure of conservative treatment (typically 48–72 h).' },
    { q: 'What is the Gastrografin challenge?', a: 'In adhesional SBO, 100 mL of water-soluble contrast is given via the NG tube and an AXR taken (usually at 6–24 h). Contrast in the colon predicts resolution without surgery; its hyperosmolarity may also help resolve the obstruction.', k: ['water-soluble contrast'] },
    { q: 'What is sigmoid volvulus and who gets it?', a: 'Twisting of a long redundant sigmoid colon on its narrow mesentery → closed-loop large bowel obstruction. Typically elderly, institutionalised patients with chronic constipation, neurological disease or psychiatric drugs; common in parts of Africa, the Middle East and South America.' },
    { q: 'What does sigmoid volvulus look like on AXR?', a: 'A massively dilated inverted-U loop of sigmoid without haustra (“coffee bean”) arising from the pelvis and pointing towards the right upper quadrant, with proximal colonic dilatation. CT shows the “whirl” of the twisted mesentery.', k: ['coffee bean sign'] },
    { q: 'How is sigmoid volvulus managed?', a: 'Resuscitate; endoscopic decompression (flexible sigmoidoscopy and a flatus tube left in place) if no signs of ischaemia. Recurrence is common (> 50%), so offer elective sigmoid colectomy on the same admission. Gangrene, perforation or failed decompression → emergency Hartmann’s procedure.' },
    { q: 'How does caecal volvulus differ?', a: 'It occurs in younger patients with a mobile caecum; AXR shows a dilated caecum displaced to the left upper quadrant (“embryo” shape) with small bowel dilatation. Endoscopic decompression rarely works — treatment is surgical (right hemicolectomy).' },
    { q: 'What is Ogilvie’s syndrome?', a: 'Acute colonic pseudo-obstruction: massive colonic dilatation without a mechanical blockage, in frail or post-operative patients (cardiac, orthopaedic, sepsis, electrolyte disturbance, opioids). Treat the causes; neostigmine (atropine and ECG monitoring for bradycardia) or colonoscopic decompression; surgery if caecum > 12 cm or perforation.', k: ['pseudo-obstruction'] },
    { q: 'What is the serum–ascites albumin gradient (SAAG)?', a: 'Serum albumin minus ascitic albumin. ≥ 11 g/L indicates portal hypertension (cirrhosis, heart failure, Budd–Chiari); < 11 g/L indicates a non-portal cause (malignancy, TB, pancreatitis, nephrotic syndrome).', k: ['SAAG'] },
    { q: 'What do you send from a diagnostic ascitic tap?', a: 'Cell count with differential (neutrophils > 250/mm³ = SBP), albumin (for SAAG) and total protein, Gram stain and culture (inoculate blood culture bottles at the bedside), cytology, and amylase/glucose/LDH as indicated.' },
    { q: 'How do you treat spontaneous bacterial peritonitis?', a: 'IV broad-spectrum antibiotics (e.g. cefotaxime or piperacillin–tazobactam per local guidance) and IV albumin (reduces hepatorenal syndrome), then long-term prophylaxis (ciprofloxacin or co-trimoxazole).', k: ['SBP'] },
    { q: 'How is ascites from cirrhosis managed?', a: 'Salt restriction, spironolactone (± furosemide), daily weights, avoid NSAIDs; large-volume paracentesis for tense ascites with human albumin (about 8 g per litre removed when > 5 L) to prevent circulatory dysfunction; TIPS or liver transplant for refractory ascites.' },
    { q: 'How do you distinguish ascites from a large ovarian cyst?', a: 'Ascites: dull flanks, resonant centre (bowel floats up), shifting dullness. Ovarian cyst: dull centrally, resonant flanks (bowel pushed aside), no shifting dullness, you can’t get below it; ultrasound confirms.' },
    { q: 'What are the causes of paralytic ileus?', a: 'Post-operative (especially bowel handling), electrolyte disturbance (hypokalaemia, hypomagnesaemia, hyponatraemia), drugs (opioids, anticholinergics), sepsis/peritonitis, retroperitoneal haematoma or inflammation (pancreatitis), spinal/pelvic fractures, hypothyroidism.', k: ['ileus'] },
    { q: 'What is gallstone ileus?', a: 'A large gallstone erodes through a cholecystoduodenal fistula and obstructs the terminal ileum. Rigler’s triad on imaging: small bowel obstruction, pneumobilia (air in the biliary tree) and an ectopic (often calcified) gallstone. Treatment: enterolithotomy.', k: ['Rigler triad'] },
  ],
}

export default t
