import type { Topic } from '../types'

const t: Topic = {
  id: 'dysphagia',
  title: 'Dysphagia and heartburn',
  short: 'Dysphagia',
  blurb:
    'Difficulty swallowing is an alarm symptom until proven otherwise. The session covers the history that localises and characterises dysphagia, reflux disease and its complications (Barrett’s, stricture, hiatus hernia), achalasia, and the work-up and treatment of oesophageal cancer.',
  keyPoints: [
    'New dysphagia at any age needs an urgent OGD (2-week-wait pathway): exclude cancer.',
    'Ask: solids, liquids or both? Intermittent or progressive? Where does it stick? Regurgitation, heartburn, odynophagia, weight loss?',
    'Progressive dysphagia to solids then liquids with weight loss = oesophageal cancer. Solids and liquids from the start, with regurgitation = achalasia (a motility disorder).',
    'GORD: burning retrosternal pain rising upwards, worse lying flat or bending, acid taste, waterbrash. Complications: oesophagitis, stricture, Barrett’s → adenocarcinoma.',
    'Squamous cell carcinoma: upper/middle third, smoking, alcohol. Adenocarcinoma: lower third/junction, reflux, Barrett’s, obesity.',
    'Examination looks for the consequences: weight loss, anaemia, Virchow’s node, hepatomegaly, an epigastric mass, aspiration.',
  ],
  sections: [
    {
      id: 'history',
      title: 'History of dysphagia',
      items: [
        '**Onset** (recent or longstanding) and **course** — intermittent (ring, web, spasm) or **progressive** (stricture, cancer).',
        '**Solids, liquids or both**: mechanical obstruction → solids first; motility disorder → both from the start; neurological (bulbar) → liquids worse, choking, nasal regurgitation, cough.',
        '**Level** where food sticks (poor guide to the true level) and whether it passes or must be regurgitated.',
        '**Regurgitation** of undigested food (achalasia, pouch), halitosis, gurgling in the neck (pharyngeal pouch), nocturnal cough and chest infections (aspiration).',
        '**Odynophagia** (painful swallowing — oesophagitis, candida, ulcer; implies intact mucosa, so cancer less likely), heartburn, chest pain.',
        '**Weight loss**, appetite, anaemia symptoms, haematemesis/melaena, hoarseness (recurrent laryngeal nerve invasion).',
        '**Risk factors**: smoking, alcohol, long-standing reflux, Barrett’s, obesity, hot drinks, caustic ingestion, previous radiotherapy; NSAIDs/bisphosphonates/doxycycline (pill oesophagitis).',
        'Do not confuse with **globus** (a lump in the throat between meals, not interfering with swallowing) or **early satiety**.',
      ],
      source: 'Macleod’s 14e · Ch 6 · pp 98–99',
    },
    {
      id: 'heartburn',
      title: 'Heartburn and reflux',
      items: [
        '**Heartburn**: a hot, burning retrosternal discomfort **rising upwards**, worse lying flat, bending forward or after large/fatty meals, relieved by antacids.',
        '**Associated**: acid or bitter taste (regurgitation), **waterbrash** (sudden mouthful of saliva), cough, hoarseness, asthma, dental erosion.',
        'Distinguish from **cardiac pain**: heavy/tight, exertional, radiating to the arm/jaw, with breathlessness — do an ECG if in doubt.',
        '**Alarm features** needing endoscopy: dysphagia, weight loss, GI bleeding/anaemia, persistent vomiting, epigastric mass, age ≥ 55 with new symptoms.',
      ],
      source: 'Macleod’s 14e · Ch 6 · p 95',
    },
    {
      id: 'causes',
      title: 'Causes of dysphagia',
      table: {
        head: ['Group', 'Causes'],
        rows: [
          ['Oropharyngeal (transfer)', 'Stroke, motor neurone disease, Parkinson’s, myasthenia gravis, bulbar/pseudobulbar palsy, pharyngeal pouch, head and neck cancer'],
          ['Oesophageal — mechanical (luminal/mural)', 'Carcinoma, peptic stricture, Schatzki ring, webs (Plummer–Vinson), eosinophilic oesophagitis, foreign body, caustic stricture'],
          ['Oesophageal — extrinsic', 'Mediastinal nodes, lung cancer, retrosternal goitre, aortic aneurysm, enlarged left atrium, para-oesophageal hernia'],
          ['Oesophageal — motility', 'Achalasia, diffuse oesophageal spasm, systemic sclerosis (CREST), Chagas’ disease'],
        ],
      },
      source: 'Macleod’s 14e · Ch 6 · pp 98–99',
    },
    {
      id: 'exam',
      title: 'Examination',
      kind: 'steps',
      intro: 'A general and gastrointestinal examination looking for the cause and the consequences.',
      items: [
        '**General**: weight and BMI, cachexia, dehydration, pallor, jaundice.',
        '**Hands**: clubbing, koilonychia (iron deficiency), signs of systemic sclerosis (sclerodactyly, calcinosis, Raynaud’s), nicotine staining.',
        '**Face and mouth**: angular cheilitis and smooth tongue (iron deficiency — Plummer–Vinson), oral candida, dentition, telangiectasia (CREST).',
        '**Neck**: **Virchow’s node** in the left supraclavicular fossa (Troisier’s sign), cervical nodes, goitre, a pouch (gurgling swelling, usually left side); watch the patient swallow water.',
        '**Chest**: signs of aspiration pneumonia or effusion.',
        '**Abdomen**: epigastric mass, hepatomegaly (metastases), ascites, scars.',
        '**Neurology** if oropharyngeal: cranial nerves (IX, X, XII), bulbar signs, fatigability.',
        '**Complete**: observe a water swallow test (speech and language therapy) where aspiration is a concern.',
      ],
      source: 'Macleod’s 14e · Ch 6 · pp 103–104; Ch 9 · pp 187–189',
    },
    {
      id: 'investigations',
      title: 'Investigations',
      items: [
        '**OGD + biopsies** — first line for any new dysphagia (2-week-wait): cancer, stricture, oesophagitis (Los Angeles grade A–D), Barrett’s (Prague C&M), eosinophilic oesophagitis (biopsies).',
        '**Barium swallow**: first for suspected pharyngeal pouch (blind OGD risks perforation) and to show achalasia (“bird’s beak”) or a ring.',
        '**High-resolution manometry**: gold standard for achalasia (incomplete LOS relaxation, absent peristalsis — Chicago types I–III) and spasm; before anti-reflux surgery.',
        '**24-hour pH ± impedance**: confirms reflux before surgery or when PPI fails (DeMeester score).',
        '**Bloods**: FBC (iron deficiency), ferritin, U&E, LFT, albumin.',
        '**Cancer staging**: CT chest/abdomen/pelvis, PET-CT, endoscopic ultrasound (T and N stage), staging laparoscopy for junctional/gastric tumours.',
      ],
    },
    {
      id: 'gord',
      title: 'GORD and hiatus hernia',
      items: [
        '**Pathophysiology**: transient LOS relaxation, low LOS pressure, hiatus hernia, delayed gastric emptying, obesity, pregnancy, smoking, alcohol, fatty meals, drugs (nitrates, calcium-channel blockers, anticholinergics).',
        '**Treatment**: lifestyle (weight loss, raise the bed head, avoid late meals and triggers, stop smoking), PPI for 4–8 weeks then lowest effective dose; H₂ antagonists/alginates as adjuncts.',
        '**Surgery** (laparoscopic **Nissen 360° fundoplication**, or partial Toupet 270°) for proven reflux with persistent volume regurgitation, PPI intolerance or patient preference — after pH studies and manometry. Side effects: dysphagia, gas-bloat, inability to belch/vomit.',
        '**Complications**: oesophagitis, peptic stricture (dilatation + PPI), **Barrett’s oesophagus** (intestinal metaplasia — surveillance OGD; radiofrequency ablation/endoscopic resection for dysplasia), adenocarcinoma, aspiration.',
        '**Hiatus hernia**: type I sliding (~90%, GOJ moves up), type II rolling/para-oesophageal (fundus beside a normally placed GOJ — can volve and strangulate), type III mixed, type IV other organs. **Borchardt’s triad** (gastric volvulus): severe epigastric pain, unproductive retching, inability to pass an NG tube.',
      ],
    },
    {
      id: 'achalasia',
      title: 'Achalasia and other motility disorders',
      items: [
        '**Achalasia**: loss of inhibitory neurons in the myenteric plexus → LOS fails to relax and peristalsis is absent. Dysphagia to **solids and liquids from the start**, regurgitation of undigested food (especially lying down), chest pain, slow weight loss, aspiration pneumonia.',
        '**Barium swallow**: dilated oesophagus tapering to a “bird’s beak”; **manometry** confirms (Chicago I–III); OGD excludes **pseudoachalasia** (cancer at the cardia).',
        '**Treatment**: pneumatic balloon dilatation, laparoscopic **Heller cardiomyotomy + partial fundoplication** (Dor), **POEM** (per-oral endoscopic myotomy), botulinum toxin for frail patients; small increased risk of SCC.',
        '**Diffuse oesophageal spasm**: intermittent dysphagia and chest pain (mimics angina); “corkscrew” barium swallow.',
        '**Pharyngeal pouch (Zenker’s)**: posterior herniation through **Killian’s dehiscence** (between thyropharyngeus and cricopharyngeus); elderly men; regurgitation of old food, halitosis, gurgling, cough, aspiration; barium swallow; endoscopic stapled diverticulotomy or open excision.',
        '**Plummer–Vinson syndrome**: iron-deficiency anaemia + post-cricoid web + dysphagia in middle-aged women; premalignant (post-cricoid SCC).',
      ],
    },
    {
      id: 'cancer',
      title: 'Oesophageal cancer',
      table: {
        head: ['', 'Squamous cell carcinoma', 'Adenocarcinoma'],
        rows: [
          ['Site', 'Upper and middle third', 'Lower third and gastro-oesophageal junction'],
          ['Risk factors', 'Smoking, alcohol, hot drinks, achalasia, caustic stricture, Plummer–Vinson, low socioeconomic status', 'GORD, Barrett’s, obesity, smoking, male sex'],
          ['Epidemiology', 'Commonest worldwide (Asia, Africa, Iran–Central Asia belt)', 'Commonest in the West; rising'],
        ],
      },
      items: [
        '**Presentation**: progressive dysphagia (solids → liquids), weight loss, odynophagia, regurgitation, anaemia, hoarseness, cough on swallowing (tracheo-oesophageal fistula), Virchow’s node.',
        '**Staging**: OGD + biopsy, CT CAP, PET-CT, EUS, staging laparoscopy (junctional tumours); MDT discussion; fitness assessment (cardiopulmonary exercise testing).',
        '**Curative**: neoadjuvant chemotherapy (e.g. FLOT for junctional adenocarcinoma) or chemoradiotherapy (CROSS) then **oesophagectomy** — Ivor Lewis (abdomen + right thorax), McKeown (three-stage, neck anastomosis), transhiatal. Definitive chemoradiotherapy is often used for SCC.',
        '**Oesophagectomy complications**: anastomotic leak, pneumonia, chylothorax, recurrent laryngeal nerve palsy, conduit necrosis, stricture.',
        '**Palliation**: self-expanding metal stent, radiotherapy/brachytherapy, chemotherapy, nutritional support.',
      ],
    },
  ],
  cases: ['oesophageal-cancer', 'achalasia'],
  qa: [
    { q: 'What questions do you ask a patient with dysphagia?', a: 'Onset and duration; intermittent or progressive; solids, liquids or both; the level it sticks; regurgitation (undigested food, nocturnal); odynophagia; heartburn; weight loss and appetite; hoarseness, cough and chest infections; GI bleeding; risk factors (smoking, alcohol, reflux, Barrett’s).', k: ['dysphagia history'] },
    { q: 'What distinguishes mechanical from motility dysphagia?', a: 'Mechanical obstruction (cancer, stricture) affects solids first and progresses to liquids; motility disorders (achalasia, spasm) affect solids and liquids from the start and are often intermittent at first.' },
    { q: 'What are the red flags in dysphagia and dyspepsia?', a: 'Dysphagia at any age, weight loss, GI bleeding or iron-deficiency anaemia, persistent vomiting, an epigastric mass, age ≥ 55 with new upper GI symptoms — all need urgent endoscopy (UK 2-week-wait).', k: ['alarm symptoms', '2 week wait', 'ALARMS'] },
    { q: 'What is odynophagia and what does it suggest?', a: 'Pain on swallowing, often with hot drinks. It suggests oesophagitis (reflux, pill-induced), oesophageal candida or herpes (immunosuppression), or ulceration. Because the mucosa is sensitive and intact, cancer is less likely.' },
    { q: 'Differentiate heartburn from cardiac pain.', a: 'Heartburn is burning, retrosternal, rising upwards, related to meals, lying flat or bending, with an acid taste or waterbrash, relieved by antacids. Cardiac pain is tight/heavy, exertional, radiates to the arm/jaw, with breathlessness or sweating, relieved by rest/GTN. When in doubt, ECG and troponin.' },
    { q: 'What is achalasia?', a: 'A primary motility disorder: degeneration of inhibitory neurons of the myenteric plexus means the lower oesophageal sphincter fails to relax and the body loses peristalsis. Dysphagia to solids and liquids, regurgitation, chest pain, weight loss, aspiration.' },
    { q: 'How is achalasia diagnosed and treated?', a: 'Barium swallow (dilated oesophagus, smooth “bird’s beak” taper); high-resolution manometry is the gold standard; OGD to exclude pseudoachalasia (cardia cancer). Treatment: pneumatic dilatation, laparoscopic Heller myotomy with partial (Dor) fundoplication, POEM, or botulinum toxin for frail patients.', k: ['Heller', 'POEM', 'bird beak'] },
    { q: 'What is pseudoachalasia?', a: 'An achalasia-like picture caused by a tumour (usually adenocarcinoma at the cardia) infiltrating the LOS. Suspect in older patients with short history and rapid weight loss — always do an OGD (± EUS/CT).' },
    { q: 'What are the complications of GORD?', a: 'Oesophagitis (ulceration, bleeding), peptic stricture (dysphagia), Barrett’s oesophagus (→ dysplasia → adenocarcinoma), aspiration (cough, asthma, pneumonia), laryngitis and dental erosion.' },
    { q: 'What is Barrett’s oesophagus?', a: 'Replacement of the normal squamous lining of the distal oesophagus by columnar epithelium with intestinal metaplasia, caused by chronic reflux. A premalignant condition (adenocarcinoma risk ~0.3% per year): PPI, surveillance OGD with biopsies; endoscopic resection and radiofrequency ablation for dysplasia.' },
    { q: 'What is the Los Angeles classification?', a: 'Endoscopic grading of reflux oesophagitis: A — mucosal breaks ≤ 5 mm; B — > 5 mm, not continuous between folds; C — continuous between ≥ 2 folds but < 75% of circumference; D — ≥ 75% of circumference.', k: ['LA grade', 'oesophagitis grading'] },
    { q: 'What are the types of hiatus hernia?', a: 'Type I sliding (~90%): GOJ moves into the chest, causes reflux. Type II rolling/para-oesophageal: fundus herniates beside a normally sited GOJ — risk of volvulus, strangulation. Type III mixed. Type IV other organs (colon, spleen) in the sac.' },
    { q: 'What is Borchardt’s triad?', a: 'Acute gastric volvulus (e.g. in a para-oesophageal hernia): severe epigastric pain, retching without vomiting, and inability to pass a nasogastric tube. A surgical emergency.' },
    { q: 'When is anti-reflux surgery indicated?', a: 'Proven GORD (pH/impedance studies, manometry to exclude a motility disorder) with persistent symptoms — especially volume regurgitation — despite PPI, PPI intolerance or reluctance to take lifelong medication, or large para-oesophageal hernias. Laparoscopic Nissen (360°) or Toupet (270°) fundoplication.', k: ['Nissen fundoplication'] },
    { q: 'What are the side effects of a Nissen fundoplication?', a: 'Dysphagia (often temporary), gas-bloat syndrome, inability to belch or vomit, increased flatulence, recurrence or slipped wrap.' },
    { q: 'Compare squamous cell carcinoma and adenocarcinoma of the oesophagus.', a: 'SCC: upper/middle third; smoking, alcohol, hot drinks, achalasia, Plummer–Vinson; commonest worldwide. Adenocarcinoma: lower third/GOJ; reflux, Barrett’s, obesity; commonest in the West and rising.', k: ['oesophageal cancer types'] },
    { q: 'How is oesophageal cancer staged?', a: 'OGD with biopsy, CT chest/abdomen/pelvis (metastases), PET-CT (occult metastases), endoscopic ultrasound (depth of invasion and nodes), staging laparoscopy for junctional tumours (peritoneal disease); bronchoscopy for upper-third tumours. Then MDT and fitness assessment.' },
    { q: 'What operations are used for oesophageal cancer?', a: 'Ivor Lewis (laparotomy/laparoscopy + right thoracotomy, anastomosis in the chest), McKeown three-stage (abdomen, right chest, neck anastomosis — for higher tumours), transhiatal (abdomen + neck). Usually after neoadjuvant chemotherapy or chemoradiotherapy.', k: ['oesophagectomy', 'Ivor Lewis'] },
    { q: 'What is a pharyngeal pouch?', a: 'A pulsion diverticulum through Killian’s dehiscence — the weak area between the thyropharyngeus and cricopharyngeus parts of the inferior constrictor. Elderly men: dysphagia, regurgitation of undigested food, halitosis, gurgling neck swelling, recurrent aspiration. Diagnose with barium swallow (avoid blind endoscopy — perforation).', k: ['Zenker diverticulum', 'Killian dehiscence'] },
    { q: 'What is Plummer–Vinson syndrome?', a: 'Iron-deficiency anaemia, post-cricoid oesophageal web and dysphagia, typically in middle-aged women. Associated with koilonychia, angular cheilitis, glossitis. Premalignant for post-cricoid SCC. Treat iron deficiency and dilate the web.', k: ['Paterson-Kelly'] },
    { q: 'What is Troisier’s sign?', a: 'An enlarged left supraclavicular lymph node (Virchow’s node) in a patient with abdominal malignancy — usually gastric, but also oesophageal, pancreatic or other intra-abdominal cancers (the thoracic duct drains into the left subclavian vein).', k: ['Virchow node'] },
    { q: 'What is Boerhaave syndrome?', a: 'Spontaneous full-thickness rupture of the distal oesophagus (usually left posterolateral) after forceful vomiting. Mackler’s triad: vomiting, severe chest pain, subcutaneous emphysema. CXR/CT shows pneumomediastinum and effusion; water-soluble contrast swallow confirms. High mortality — resuscitate, NBM, antibiotics, antifungals, surgery or stent.', k: ['oesophageal rupture', 'Mackler triad'] },
    { q: 'What is eosinophilic oesophagitis?', a: 'An allergic inflammatory oesophagitis in young (often atopic) men — intermittent dysphagia and food bolus impaction. OGD: rings (“trachealisation”), furrows, white exudates; diagnosis by biopsy (> 15 eosinophils/hpf). Treat with PPI, topical steroids, dietary elimination, dilatation.' },
    { q: 'How do you manage a food bolus impaction?', a: 'If the patient cannot swallow saliva — urgent OGD to remove or push it through (within hours). Avoid emetics. Afterwards biopsy for eosinophilic oesophagitis and look for a stricture or ring.' },
  ],
}

export default t
