import type { Topic } from '../types'

const t: Topic = {
  id: 'epigastric',
  title: 'Epigastric pain',
  short: 'Epigastric pain',
  blurb:
    'Pain in the epigastrium ranges from dyspepsia to perforation, pancreatitis, gastric cancer and myocardial infarction. The session covers telling them apart from the history (Macleod’s Box 6.2), peptic ulcer disease and H. pylori, gastric outlet obstruction, pancreatitis (acute and chronic) and gastric cancer.',
  keyPoints: [
    'Don’t miss the killers presenting as epigastric pain: perforation, pancreatitis, ruptured/leaking AAA, inferior MI (ECG + troponin).',
    'Duodenal ulcer: pain when hungry/at night, relieved by food or antacids. Gastric ulcer: pain worse with food, weight loss — biopsy to exclude cancer.',
    'H. pylori and NSAIDs cause most peptic ulcers. Test (urea breath or stool antigen, off PPI 2 weeks) and treat (PPI + two antibiotics), then confirm eradication.',
    'Urgent OGD for dysphagia, or age ≥ 55 with weight loss and upper abdominal pain, reflux or dyspepsia; also GI bleeding, anaemia, persistent vomiting, an epigastric mass.',
    'Gastric outlet obstruction: projectile non-bilious vomiting of old food, succussion splash, hypochloraemic hypokalaemic metabolic alkalosis — resuscitate with 0.9% saline + KCl.',
    'Gastric cancer: weight loss, early satiety, epigastric mass, Virchow’s node (Troisier’s sign), Sister Mary Joseph nodule, Krukenberg tumour.',
  ],
  sections: [
    {
      id: 'differentials',
      title: 'Distinguishing the causes',
      table: {
        head: ['Disorder', 'Character and timing', 'Clues'],
        rows: [
          ['Duodenal ulcer', 'Gnawing, epigastric, worse when hungry and at night, relieved by food/antacids; periodic (weeks–months)', 'Pointing sign; H. pylori, NSAIDs, smoking'],
          ['Gastric ulcer', 'Epigastric, worse soon after eating, nausea, weight loss', 'Older; must biopsy (malignancy)'],
          ['Biliary colic', 'Constant, rapidly increasing, epigastric/RUQ, radiates below the right scapula, 1–6 h, after fatty meals', 'Attacks can be counted; normal LFTs between'],
          ['Acute pancreatitis', 'Sudden, constant, severe epigastric pain radiating through to the back, relieved by sitting forward; vomiting', 'Alcohol, gallstones; lipase > 3× ULN'],
          ['Perforated ulcer', 'Sudden, severe, then generalised; shoulder-tip', 'Rigid abdomen, free gas'],
          ['Gastric cancer', 'Vague dyspepsia, early satiety, anorexia, weight loss', 'Age > 55, anaemia, mass, Virchow’s node'],
          ['Inferior MI', 'Epigastric pain without tenderness, sweating, angor animi', 'ECG, troponin'],
          ['Leaking AAA', 'Epigastric/back pain, collapse', 'Pulsatile expansile mass'],
          ['Functional dyspepsia', 'Chronic epigastric pain/fullness, no structural cause', 'Normal OGD; diagnosis of exclusion'],
        ],
      },
      source: 'Macleod’s 14e · Ch 6 · pp 95–97 (Boxes 6.2–6.3)',
    },
    {
      id: 'history',
      title: 'History',
      items: [
        '**SOCRATES**, especially relation to meals (better or worse), nocturnal waking, radiation to the back, periodicity.',
        '**Dyspepsia clusters**: reflux-like (heartburn), ulcer-like (epigastric pain relieved by food/antacids), dysmotility-like (nausea, bloating, early satiety).',
        '**Alarm features**: dysphagia, weight loss, anorexia, vomiting, haematemesis/melaena, anaemia symptoms, early satiety.',
        '**Drugs**: NSAIDs, aspirin, steroids, SSRIs, bisphosphonates, anticoagulants; previous PPI use and response.',
        '**Alcohol** (pancreatitis, gastritis), **smoking**, gallstones, previous pancreatitis, H. pylori treatment, previous gastric surgery.',
        '**Cardiac risk**: is this angina/MI?',
        '**Family history** of gastric cancer.',
      ],
      source: 'Macleod’s 14e · Ch 6 · pp 95–97',
    },
    {
      id: 'exam',
      title: 'Examination',
      kind: 'steps',
      items: [
        '**General**: comfort, cachexia, pallor, jaundice, vital signs (shock, fever).',
        '**Hands**: koilonychia, pallor; signs of chronic liver disease (alcohol).',
        '**Face**: conjunctival pallor, angular cheilitis, jaundice.',
        '**Neck**: **Virchow’s node** (left supraclavicular fossa) — Troisier’s sign.',
        '**Abdomen**: epigastric tenderness and guarding (peritonism → perforation/pancreatitis), epigastric mass (gastric/pancreatic tumour — transmitted pulsation, or an AAA — expansile), hepatomegaly (metastases), ascites, umbilical nodule (Sister Mary Joseph), Cullen’s/Grey Turner’s, succussion splash (gastric outlet obstruction).',
        '**Complete**: DRE (melaena, Blumer’s shelf), pelvic examination in women (Krukenberg), ECG.',
      ],
      source: 'Macleod’s 14e · Ch 6 · pp 103–110',
    },
    {
      id: 'investigations',
      title: 'Investigations',
      items: [
        '**Acute**: ECG and troponin, **lipase/amylase**, FBC, U&E, LFT, calcium, CRP, VBG/lactate, erect CXR (free gas), β-hCG in women.',
        '**H. pylori**: **13C-urea breath test** or **stool antigen** (stop PPI 2 weeks and antibiotics 4 weeks before); serology only shows past exposure; CLO/rapid urease test on OGD biopsy.',
        '**OGD + biopsy**: alarm features, age ≥ 55 with new symptoms, failure of treatment; biopsy every gastric ulcer and repeat OGD at 6–8 weeks to confirm healing.',
        '**CT**: pancreatitis complications (after 72 h), staging of gastric cancer; **EUS** for T/N stage; **staging laparoscopy** for peritoneal disease.',
        '**Ultrasound**: gallstones.',
      ],
    },
    {
      id: 'pud',
      title: 'Peptic ulcer disease and H. pylori',
      items: [
        '**Causes**: *H. pylori* (most duodenal, many gastric ulcers), **NSAIDs/aspirin**, smoking, steroids with NSAIDs, Zollinger–Ellison syndrome (gastrinoma — multiple/atypical ulcers, diarrhoea; MEN1), stress (Curling’s after burns, Cushing’s after head injury).',
        '**Treatment**: PPI (4–8 weeks), stop NSAIDs (or PPI cover), **eradication therapy** — PPI + amoxicillin + clarithromycin (or metronidazole if penicillin-allergic) for 7–14 days; confirm eradication with a breath test (at least 4 weeks after).',
        '**Complications**: bleeding (posterior DU — gastroduodenal artery), **perforation** (anterior DU), gastric outlet obstruction (pyloric stenosis), penetration into the pancreas (back pain).',
        '**Dyspepsia without alarm features** (NICE): review drugs and lifestyle, then “test and treat” for H. pylori or a full-dose PPI for 4 weeks.',
      ],
    },
    {
      id: 'goo',
      title: 'Gastric outlet obstruction',
      items: [
        '**Causes**: distal gastric/pancreatic cancer (now most common), chronic peptic ulcer scarring (pyloric stenosis), external compression; infantile hypertrophic pyloric stenosis in babies.',
        '**Features**: projectile **non-bilious** vomiting of undigested food eaten hours before, early satiety, weight loss, visible gastric peristalsis, **succussion splash** > 4 h after eating.',
        '**Metabolic**: loss of HCl → **hypochloraemic, hypokalaemic metabolic alkalosis**; the kidney retains Na⁺ at the cost of H⁺/K⁺ → **paradoxical aciduria**.',
        '**Management**: NG decompression, IV **0.9% saline with KCl**, PPI, nutrition; OGD (biopsy, balloon dilatation or stent) or surgery (gastrojejunostomy, resection).',
      ],
    },
    {
      id: 'pancreatitis',
      title: 'Pancreatitis',
      items: [
        '**Acute**: causes “I GET SMASHED” (gallstones and alcohol ~80%); diagnosis 2 of 3 (pain, lipase/amylase > 3× ULN, imaging); severity by **Glasgow–Imrie** (≥ 3 severe), CRP > 150 at 48 h, **revised Atlanta** (persistent organ failure > 48 h = severe).',
        '**Acute management**: goal-directed IV fluids (Hartmann’s), analgesia, oxygen, monitor urine output and glucose; **early enteral nutrition**; no prophylactic antibiotics; ERCP within 72 h only for cholangitis/persistent obstruction; **cholecystectomy on the same admission** for mild gallstone pancreatitis; avoid alcohol.',
        '**Local complications**: acute peripancreatic fluid collection, **pseudocyst** (> 4 weeks, wall), acute necrotic collection, walled-off necrosis, infected necrosis (step-up approach: antibiotics → percutaneous/endoscopic drainage → necrosectomy), pseudoaneurysm/haemorrhage, splenic/portal vein thrombosis.',
        '**Systemic**: ARDS, AKI, shock, DIC, hypocalcaemia, hyperglycaemia.',
        '**Chronic pancreatitis**: alcohol (most), recurrent attacks; chronic epigastric pain radiating to the back, **steatorrhoea** (exocrine failure — faecal elastase low), **diabetes** (endocrine failure), weight loss; calcification on CT. Pancreatic enzyme replacement (Creon), analgesia, alcohol and smoking cessation; endoscopic or surgical drainage for duct obstruction.',
      ],
    },
    {
      id: 'gastric-cancer',
      title: 'Gastric cancer',
      items: [
        '**Adenocarcinoma** in > 90% (intestinal and diffuse/signet-ring types — linitis plastica); also lymphoma (MALT — H. pylori), GIST.',
        '**Risk factors**: H. pylori, smoking, salted/smoked/pickled foods, low fruit and vegetable intake, pernicious anaemia and atrophic gastritis, previous partial gastrectomy, blood group A, family history (CDH1 — hereditary diffuse gastric cancer).',
        '**Presentation**: dyspepsia, early satiety, anorexia, weight loss, vomiting (outlet obstruction), dysphagia (cardia), anaemia/GI bleeding; often late.',
        '**Signs**: epigastric mass, **Virchow’s node (Troisier’s sign)**, hepatomegaly, ascites, **Sister Mary Joseph nodule** (umbilicus), **Krukenberg tumour** (ovary), **Blumer’s shelf** (rectovesical/rectouterine pouch on DRE), acanthosis nigricans, Leser–Trélat sign.',
        '**Staging**: OGD + biopsy, CT CAP, EUS, PET-CT, **staging laparoscopy** with peritoneal washings.',
        '**Treatment**: perioperative chemotherapy (FLOT) + gastrectomy (total or subtotal with D2 lymphadenectomy) for resectable disease; endoscopic resection for very early cancers; palliation — stents, palliative chemotherapy, bypass.',
      ],
    },
  ],
  cases: ['gastric-cancer', 'perforated-du', 'pancreatitis'],
  qa: [
    { q: 'What are the causes of epigastric pain?', a: 'Peptic ulcer, gastritis, GORD, functional dyspepsia, biliary colic/cholecystitis, acute and chronic pancreatitis, gastric cancer, perforated ulcer, AAA, inferior MI, pericarditis, lower-lobe pneumonia, and early appendicitis.', k: ['differential diagnosis'] },
    { q: 'How do duodenal and gastric ulcer pain differ?', a: 'Duodenal: gnawing epigastric pain when hungry and at night (waking 2–3 am), relieved by food or antacids; periodic. Gastric: pain soon after eating, food may worsen it, associated nausea and weight loss. The history is unreliable — OGD decides.' },
    { q: 'What are the causes of peptic ulcer disease?', a: 'Helicobacter pylori and NSAIDs/aspirin (together the vast majority), smoking, steroids (with NSAIDs), SSRIs, Zollinger–Ellison syndrome (gastrinoma), stress ulcers in critical illness, burns (Curling’s) and head injury (Cushing’s).', k: ['PUD aetiology'] },
    { q: 'How do you test for Helicobacter pylori?', a: 'Non-invasive: 13C-urea breath test or stool antigen test (stop PPI for 2 weeks and antibiotics for 4 weeks beforehand to avoid false negatives). Invasive: rapid urease (CLO) test, histology or culture on gastric biopsies at OGD. Serology shows exposure but not current infection.', k: ['urea breath test', 'CLO test'] },
    { q: 'What is H. pylori eradication therapy?', a: 'Triple therapy for 7 days (NICE; 14 days in some guidelines): a PPI twice daily + amoxicillin + clarithromycin (or metronidazole). Penicillin allergy: PPI + clarithromycin + metronidazole. Second line includes bismuth quadruple therapy. Confirm eradication with a breath test after treatment.', k: ['triple therapy'] },
    { q: 'What are the alarm features in dyspepsia (urgent OGD)?', a: 'Dysphagia (any age); age ≥ 55 with weight loss and upper abdominal pain, reflux or dyspepsia; upper GI bleeding or iron-deficiency anaemia; persistent vomiting; an epigastric mass; early satiety and weight loss.', k: ['red flags', 'NICE NG12'] },
    { q: 'What are the complications of peptic ulcer disease?', a: 'Haemorrhage (posterior duodenal ulcer eroding the gastroduodenal artery), perforation (anterior duodenal ulcer → peritonitis), gastric outlet obstruction (scarring at the pylorus), penetration (into the pancreas — back pain), and malignancy in gastric ulcers.' },
    { q: 'Why must gastric ulcers be biopsied and re-scoped?', a: 'A proportion are malignant (ulcerated gastric cancer) and can look benign. Take multiple biopsies from the edge and base, and repeat OGD after 6–8 weeks of PPI to confirm healing and re-biopsy if not healed.' },
    { q: 'What metabolic abnormality does gastric outlet obstruction cause?', a: 'Hypochloraemic, hypokalaemic metabolic alkalosis from loss of HCl in vomit. Volume depletion makes the kidney retain Na⁺ in exchange for H⁺ and K⁺, so the urine is paradoxically acidic (paradoxical aciduria). Treat with IV 0.9% saline and potassium.', k: ['pyloric stenosis', 'paradoxical aciduria'] },
    { q: 'What is a succussion splash?', a: 'A splashing sound heard with a stethoscope over the epigastrium when the patient’s abdomen is gently rocked, more than 4 hours after eating/drinking — indicates fluid retained in an obstructed stomach (gastric outlet obstruction).' },
    { q: 'What are the risk factors for gastric cancer?', a: 'H. pylori infection, smoking, diets high in salted, smoked or pickled foods and low in fruit/vegetables, atrophic gastritis/pernicious anaemia, previous partial gastrectomy, adenomatous polyps, blood group A, male sex, family history (CDH1 mutation — hereditary diffuse gastric cancer), low socioeconomic status.' },
    { q: 'What are the signs of metastatic gastric cancer?', a: 'Virchow’s node (left supraclavicular — Troisier’s sign), Sister Mary Joseph nodule (umbilicus), Krukenberg tumour (ovarian metastasis), Blumer’s shelf (peritoneal deposit in the pouch of Douglas on DRE), Irish node (left axilla), hepatomegaly, ascites, jaundice.', k: ['Troisier sign', 'Sister Mary Joseph', 'Krukenberg', 'Blumer shelf'] },
    { q: 'How is gastric cancer staged and treated?', a: 'OGD + biopsy, CT chest/abdomen/pelvis, EUS, PET-CT, staging laparoscopy with peritoneal washings. Resectable disease: perioperative chemotherapy (FLOT) and gastrectomy (subtotal for distal, total for proximal tumours) with D2 lymphadenectomy. Early mucosal cancers: endoscopic resection. Palliative: chemotherapy, stents, bypass, radiotherapy for bleeding.' },
    { q: 'What is linitis plastica?', a: 'Diffuse-type (signet-ring cell) gastric adenocarcinoma infiltrating the whole stomach wall, making it rigid and thickened (“leather bottle stomach”). Poor prognosis; associated with CDH1 mutations.' },
    { q: 'What is Zollinger–Ellison syndrome?', a: 'A gastrin-secreting tumour (gastrinoma, usually in the duodenum or pancreas; 25% with MEN1) causing massive acid secretion: multiple, recurrent or atypically sited peptic ulcers, diarrhoea/steatorrhoea. Raised fasting gastrin (off PPI), secretin stimulation test; high-dose PPI and resection.', k: ['gastrinoma', 'MEN1'] },
    { q: 'What are the features of chronic pancreatitis?', a: 'Recurrent or constant epigastric pain radiating to the back (often after alcohol or meals), weight loss, steatorrhoea (exocrine insufficiency — low faecal elastase) and diabetes (endocrine insufficiency); pancreatic calcification on CT/AXR. Commonest cause is alcohol. Treat with abstinence, enzyme replacement, analgesia, diabetic care, and endoscopic/surgical drainage for ductal obstruction.' },
    { q: 'What is a pancreatic pseudocyst?', a: 'A collection of pancreatic fluid enclosed by a non-epithelialised fibrous wall, forming more than 4 weeks after an attack of interstitial pancreatitis. May cause pain, early satiety, gastric outlet or biliary obstruction, infection, bleeding or rupture. Symptomatic or enlarging cysts are drained (endoscopic cystgastrostomy, percutaneous or surgical).' },
    { q: 'How do you manage acute pancreatitis?', a: 'Supportive: oxygen, goal-directed IV crystalloid (Hartmann’s), analgesia, antiemetics, monitor urine output and glucose, early enteral feeding (oral or NG/NJ) rather than TPN; no prophylactic antibiotics; ERCP for cholangitis or persistent biliary obstruction; cholecystectomy in the same admission for mild gallstone pancreatitis; HDU/ICU for organ failure.' },
    { q: 'Why is inferior MI a mimic of an acute abdomen?', a: 'The inferior myocardium shares segmental innervation with the upper abdomen, so ischaemia may present as epigastric pain with nausea and vomiting but no abdominal tenderness. Always do an ECG (± troponin) in epigastric pain, especially in older or diabetic patients.' },
    { q: 'What is the pointing sign?', a: 'The patient points to a single, localised spot in the epigastrium as the site of pain — typical of a peptic (duodenal) ulcer.' },
  ],
}

export default t
