import type { Topic } from '../types'

const t: Topic = {
  id: 'jaundice',
  title: 'Right hypochondrial pain & jaundice',
  short: 'RUQ & jaundice',
  blurb:
    'Gallstones and their complications dominate this session — biliary colic, cholecystitis, common bile duct stones, cholangitis and gallstone pancreatitis — alongside the jaundiced patient: pre-hepatic, hepatic or obstructive, painful or painless, and the cystic liver lesions (hydatid, abscess) that are common in this region.',
  keyPoints: [
    'Jaundice is visible when bilirubin > ~50 µmol/L. Obstructive jaundice: dark urine, pale stools, itch; LFTs show ALP/GGT ≫ ALT.',
    'Painful jaundice is usually stones; painless jaundice with weight loss is cancer (pancreatic head, cholangiocarcinoma) until proven otherwise.',
    'Charcot’s triad (fever/rigors, jaundice, RUQ pain) = cholangitis; add hypotension and confusion = Reynolds’ pentad. Antibiotics + biliary drainage (ERCP).',
    'Murphy’s sign: arrest of inspiration on palpating the right upper quadrant — acute cholecystitis (check it is negative on the left).',
    'Courvoisier’s law: a palpable gallbladder in a jaundiced patient is unlikely to be due to stones (think pancreatic head cancer).',
    'Ultrasound first: stones, gallbladder wall thickening, CBD dilatation (> 6 mm), liver lesions. Then MRCP/EUS for duct stones, CT for cancer.',
  ],
  sections: [
    {
      id: 'jaundice-types',
      title: 'Types of jaundice',
      table: {
        head: ['', 'Pre-hepatic', 'Hepatic', 'Post-hepatic (obstructive)'],
        rows: [
          ['Bilirubin', 'Unconjugated', 'Mixed', 'Conjugated'],
          ['Urine', 'Normal colour (acholuric), urobilinogen ↑', 'Dark; bilirubin +', 'Dark; bilirubin +++, no urobilinogen'],
          ['Stools', 'Normal', 'Normal', 'Pale'],
          ['LFTs', 'Normal enzymes', 'ALT/AST ↑↑', 'ALP/GGT ↑↑'],
          ['Causes', 'Haemolysis, Gilbert’s', 'Viral/alcoholic hepatitis, cirrhosis, drugs, autoimmune', 'Gallstones, pancreatic head cancer, cholangiocarcinoma, strictures, PSC, drugs (cholestasis)'],
        ],
      },
      note: 'In obstruction, itch comes from bile salts in the skin; steatorrhoea and vitamin K malabsorption (prolonged INR) follow.',
      source: 'Macleod’s 14e · Ch 6 · pp 101–102 (Boxes 6.6–6.7)',
    },
    {
      id: 'history',
      title: 'History',
      items: [
        '**Pain**: site (RUQ/epigastric), onset, character (biliary “colic” is actually constant, building over minutes and lasting hours), radiation (right shoulder/below the scapula), triggers (fatty meals, night), previous attacks.',
        '**Jaundice**: when noticed, painful or painless, itch, **urine and stool colour**, fever and rigors (cholangitis).',
        '**Weight loss, appetite, new-onset diabetes, back pain** (pancreatic cancer).',
        '**Liver risk factors**: alcohol (units), IV drugs, transfusions, tattoos, sexual history, travel, vaccinations, recent drugs (co-amoxiclav, flucloxacillin, statins, paracetamol overdose).',
        '**Contact with dogs and sheep**, rural upbringing (hydatid disease).',
        '**Past history**: gallstones, pancreatitis, ERCP, cholecystectomy, IBD (PSC), haemolytic disease.',
      ],
      source: 'Macleod’s 14e · Ch 6 · pp 96–97, 101',
    },
    {
      id: 'exam',
      title: 'Examination',
      kind: 'steps',
      items: [
        '**General**: jaundice (sclera in natural light), scratch marks, cachexia, fever, distress; vital signs (sepsis in cholangitis).',
        '**Hands**: stigmata of chronic liver disease — clubbing, leuconychia, palmar erythema, Dupuytren’s, asterixis.',
        '**Face/neck/chest**: scleral icterus, xanthelasma (cholestasis), spider naevi, gynaecomastia, Virchow’s node.',
        '**Abdomen — inspect**: distension, scars (Kocher’s, laparoscopic ports), caput medusae.',
        '**Palpate**: RUQ tenderness and guarding; **Murphy’s sign** (fingers under the right costal margin in the mid-clavicular line, patient breathes in — catches breath with pain; repeat on the left); a **palpable gallbladder** (smooth, round, moves with respiration — Courvoisier); hepatomegaly (smooth/tender vs hard/irregular), epigastric mass, splenomegaly.',
        '**Percuss**: liver span, shifting dullness.',
        '**Auscultate**: bowel sounds; hepatic bruit.',
        '**Complete**: DRE (pale stool), urinalysis (bilirubin, urobilinogen), observations.',
      ],
      source: 'Macleod’s 14e · Ch 6 · pp 103–108 (Fig 6.9, Box 6.9)',
    },
    {
      id: 'gallstones',
      title: 'Gallstone disease',
      table: {
        head: ['Condition', 'Features', 'Management'],
        rows: [
          ['Biliary colic', 'Constant RUQ/epigastric pain < 6 h after fatty meals; no fever; tender but no peritonism; normal bloods', 'Analgesia; elective laparoscopic cholecystectomy'],
          ['Acute cholecystitis', 'Pain > 6 h, fever, RUQ tenderness/guarding, Murphy’s +; ↑WCC/CRP; thick-walled gallbladder, pericholecystic fluid', 'Antibiotics, analgesia, fluids; early lap chole (within 1 week, ideally < 72 h); cholecystostomy if unfit'],
          ['Empyema / gangrene / perforation', 'Persistent fever, mass, peritonism, sepsis', 'Urgent drainage/cholecystectomy'],
          ['Choledocholithiasis', 'Biliary pain + obstructive jaundice/deranged LFTs, dilated CBD', 'MRCP/EUS → ERCP (sphincterotomy, stone extraction) → cholecystectomy'],
          ['Ascending cholangitis', 'Charcot’s triad; Reynolds’ pentad if shocked/confused', 'Sepsis Six, IV antibiotics, ERCP drainage within 24–48 h (urgent if severe)'],
          ['Gallstone pancreatitis', 'Epigastric pain to the back, lipase > 3× ULN', 'Supportive; ERCP if cholangitis; cholecystectomy on the same admission (mild)'],
          ['Mirizzi syndrome', 'Stone in the neck/cystic duct compresses the CHD → jaundice', 'Careful (often open) cholecystectomy'],
          ['Gallstone ileus', 'SBO in an elderly woman; pneumobilia', 'Enterolithotomy'],
        ],
      },
      items: [
        '**Risk factors** (“fat, female, fertile, forty”): obesity, female sex, pregnancy, age, rapid weight loss, family history, haemolysis (pigment stones), ileal disease/resection, drugs (OCP, fibrates, octreotide).',
        '**Tokyo guidelines** grade cholecystitis/cholangitis: I mild, II moderate (WCC > 18, palpable mass, > 72 h, local complications), III severe (organ dysfunction).',
        '**Laparoscopic cholecystectomy**: obtain the **critical view of safety** before clipping (only two structures entering the gallbladder). Complications: bile duct injury (0.3–0.5%), bile leak (cystic stump, ducts of Luschka), bleeding, retained CBD stones, port-site hernia.',
      ],
      source: 'Macleod’s 14e · Ch 6 · pp 97, 102, 108',
    },
    {
      id: 'painless',
      title: 'Painless jaundice — malignancy',
      items: [
        '**Pancreatic head adenocarcinoma**: painless progressive jaundice, weight loss, anorexia, back pain, new diabetes, steatorrhoea; palpable gallbladder (Courvoisier), migratory thrombophlebitis (Trousseau’s), hepatomegaly, Virchow’s node. CT pancreas protocol, CA19-9, EUS ± biopsy. Only ~15–20% resectable: **Whipple’s pancreaticoduodenectomy**; otherwise biliary stent + palliative chemotherapy.',
        '**Cholangiocarcinoma**: hilar (Klatskin) or distal; PSC is a risk factor (also liver flukes); MRCP, CA19-9.',
        '**Periampullary/ampullary carcinoma**: may have intermittent jaundice and “silver stool” (bleeding + pale stool).',
        '**Metastases** compressing the hilum; lymphoma.',
        'Pre-procedure in obstructive jaundice: correct **vitamin K** (INR), keep well hydrated (hepatorenal risk), antibiotics around ERCP/PTC.',
      ],
    },
    {
      id: 'cystic',
      title: 'Liver cysts and abscesses',
      items: [
        '**Hydatid cyst** (*Echinococcus granulosus*): dog (definitive host) and sheep (intermediate) — **endemic in Iraq and the Middle East**. Often asymptomatic; RUQ ache, hepatomegaly, a cystic mass; complications: rupture into the biliary tree (colic, jaundice, cholangitis), peritoneum or bronchi, **anaphylaxis**, secondary infection.',
        'Hydatid imaging: ultrasound — cyst with daughter cysts (“honeycomb”), detached laminated membrane (**water-lily sign**), calcified wall; WHO/Gharbi classification; serology (ELISA). CT for planning.',
        'Hydatid treatment: **albendazole** (before and after any procedure), **PAIR** (puncture–aspiration–injection of scolicide–re-aspiration) for suitable cysts, or surgery (cystectomy/pericystectomy) with scolicidal agents (hypertonic saline) and packs soaked in scolicide to prevent spillage. **Never aspirate blindly** — anaphylaxis and seeding.',
        '**Pyogenic liver abscess**: fever, rigors, RUQ pain, tender hepatomegaly; from biliary sepsis or portal pyaemia (appendicitis, diverticulitis); Klebsiella, E. coli, anaerobes. Ultrasound/CT; percutaneous drainage + IV antibiotics; look for the source.',
        '**Amoebic liver abscess** (*Entamoeba histolytica*): travel/endemic area, often single right-lobe abscess (“anchovy sauce” pus), serology; metronidazole (aspirate only if large or failing).',
        '**Simple cysts** are common and harmless; polycystic liver disease is associated with polycystic kidneys.',
      ],
    },
    {
      id: 'investigations',
      title: 'Investigations',
      items: [
        '**Bloods**: FBC, CRP, **LFTs** (pattern: ALP/GGT vs ALT/AST, bilirubin, albumin), **INR**, lipase/amylase, U&E, blood cultures if febrile; hepatitis serology, autoantibodies, ferritin, haemolysis screen as indicated; CA19-9 for suspected malignancy (also raised in cholangitis).',
        '**Urine**: bilirubin and urobilinogen.',
        '**Ultrasound abdomen** first: stones (echogenic with acoustic shadow), wall thickening > 3 mm, pericholecystic fluid, sonographic Murphy’s, CBD diameter (> 6 mm dilated; larger after cholecystectomy/in older people), liver lesions.',
        '**MRCP**: non-invasive biliary tree imaging — CBD stones, strictures; **EUS** for small stones and periampullary tumours.',
        '**ERCP**: therapeutic (sphincterotomy, stone extraction, stenting, brushings); risks pancreatitis, bleeding, perforation, cholangitis.',
        '**CT** (pancreatic protocol) for malignancy and staging; complications of pancreatitis.',
      ],
    },
  ],
  cases: ['cholecystitis', 'cholangitis', 'pancreatic-cancer', 'hydatid-cyst'],
  qa: [
    { q: 'At what bilirubin level does jaundice become visible?', a: 'About 50 µmol/L (≈ 3 mg/dL) in good natural light, first in the sclerae (bilirubin binds elastin) and under the tongue.' },
    { q: 'How do you classify jaundice?', a: 'Pre-hepatic (excess bilirubin production — haemolysis; impaired conjugation — Gilbert’s): unconjugated, normal urine colour. Hepatic (hepatocellular — hepatitis, cirrhosis, drugs): mixed. Post-hepatic/obstructive (gallstones, pancreatic or bile duct cancer, strictures): conjugated, dark urine, pale stools, itch.', k: ['classification of jaundice'] },
    { q: 'Why are the urine dark and stools pale in obstructive jaundice?', a: 'Conjugated bilirubin is water-soluble; when it cannot drain into the gut it spills into the blood and is filtered into the urine (dark). Without bilirubin reaching the gut, no stercobilin is formed, so stools are pale and urine urobilinogen is absent.' },
    { q: 'What is Charcot’s triad?', a: 'Fever (with rigors), jaundice and right upper quadrant pain — ascending cholangitis (infection above a blocked bile duct, usually a stone). Reynolds’ pentad adds hypotension and confusion (severe/suppurative cholangitis).', k: ['cholangitis', 'Reynolds pentad'] },
    { q: 'How do you manage ascending cholangitis?', a: 'ABCDE and Sepsis Six (cultures, IV broad-spectrum antibiotics, fluids, lactate, catheter), correct coagulopathy (vitamin K), and biliary decompression — ERCP with sphincterotomy/stone extraction or stent, urgently (< 24 h) if severe, otherwise within 48–72 h. PTC drainage if ERCP fails. Then cholecystectomy.' },
    { q: 'What is Murphy’s sign?', a: 'Place your hand below the right costal margin in the mid-clavicular line and ask the patient to breathe in deeply; as the inflamed gallbladder descends onto your fingers the patient catches their breath with pain. It must be negative on the left. Suggests acute cholecystitis.', k: ['Murphys'] },
    { q: 'What is Courvoisier’s law?', a: 'In a jaundiced patient a palpable, non-tender gallbladder is unlikely to be due to gallstones — usually malignant obstruction of the distal CBD (pancreatic head, ampulla). Gallstones cause chronic fibrosis, so the gallbladder rarely distends.', k: ['Courvoisier sign'] },
    { q: 'Biliary colic vs acute cholecystitis?', a: 'Biliary colic: constant RUQ/epigastric pain after fatty food lasting < 6 hours from transient cystic duct obstruction, no fever, normal inflammatory markers. Cholecystitis: persistent obstruction with inflammation — pain > 6 h, fever, Murphy’s sign, raised WCC/CRP, thickened gallbladder wall on ultrasound.' },
    { q: 'What are the complications of gallstones?', a: 'In the gallbladder: biliary colic, acute/chronic cholecystitis, empyema, mucocele, gangrene, perforation, Mirizzi syndrome, gallbladder cancer. In the ducts: choledocholithiasis, obstructive jaundice, cholangitis, pancreatitis. In the gut: gallstone ileus.' },
    { q: 'What are the risk factors for gallstones?', a: '“Fat, female, fertile, forty (and fair)”: obesity, female sex, pregnancy/oestrogens, age, rapid weight loss (bariatric surgery), family history/ethnicity; haemolysis (pigment stones); terminal ileal disease or resection (lost bile salts); drugs (OCP, fibrates, octreotide, ceftriaxone).' },
    { q: 'When should a cholecystectomy be done for acute cholecystitis?', a: 'Early laparoscopic cholecystectomy within a week of diagnosis (ideally within 72 hours of symptom onset) — fewer readmissions and similar complications to delayed surgery. For unfit patients: antibiotics ± percutaneous cholecystostomy.' },
    { q: 'What is the critical view of safety?', a: 'During laparoscopic cholecystectomy: the hepatocystic triangle cleared of fat and fibrous tissue, the lower third of the gallbladder separated from the liver bed, and only two structures (cystic duct and cystic artery) seen entering the gallbladder — before anything is clipped or divided, to prevent bile duct injury.', k: ['CVS', 'bile duct injury'] },
    { q: 'What are the boundaries of Calot’s triangle?', a: 'Cystic duct (inferiorly/laterally), common hepatic duct (medially), inferior border of the liver (superiorly). It contains the cystic artery and Lund’s (Calot’s) lymph node.', k: ['hepatocystic triangle'] },
    { q: 'How do you investigate suspected CBD stones?', a: 'LFTs (obstructive pattern) and ultrasound (stones, dilated CBD > 6 mm). If intermediate probability: MRCP or EUS. If high probability or cholangitis: ERCP for clearance. Then cholecystectomy (same admission where possible).', k: ['choledocholithiasis', 'MRCP'] },
    { q: 'What are the complications of ERCP?', a: 'Post-ERCP pancreatitis (most common, ~3–5%), bleeding (after sphincterotomy), duodenal/biliary perforation, cholangitis, contrast reaction, sedation-related problems.' },
    { q: 'What are the features of pancreatic head cancer?', a: 'Painless progressive obstructive jaundice, weight loss, anorexia, epigastric/back pain, new-onset diabetes, steatorrhoea; palpable gallbladder (Courvoisier), hepatomegaly, Virchow’s node, migratory thrombophlebitis (Trousseau’s sign). CA19-9 raised. CT pancreatic protocol; only ~15–20% resectable (Whipple’s).', k: ['pancreatic cancer'] },
    { q: 'What is a Whipple’s procedure?', a: 'Pancreaticoduodenectomy: removal of the pancreatic head, duodenum, distal CBD, gallbladder and (classically) the distal stomach, with reconstruction by pancreaticojejunostomy, hepaticojejunostomy and gastrojejunostomy. Pylorus-preserving versions are common. Complications: pancreatic fistula, delayed gastric emptying, bleeding, diabetes, exocrine insufficiency.' },
    { q: 'What is Mirizzi syndrome?', a: 'Obstructive jaundice from extrinsic compression of the common hepatic duct by a stone impacted in Hartmann’s pouch or the cystic duct (type I), sometimes with a cholecystocholedochal fistula (types II–IV). Important because it raises the risk of bile duct injury at cholecystectomy.' },
    { q: 'What is hydatid disease and how is it acquired?', a: 'Infection with the larval cyst of the tapeworm Echinococcus granulosus. Dogs are the definitive host; sheep and other livestock the intermediate host. Humans are infected by swallowing eggs from dog faeces (contaminated hands, food, water). Endemic in the Middle East including Iraq/Kurdistan. The liver (~70%) and lungs (~20%) are most affected.', k: ['echinococcus', 'hydatid cyst'] },
    { q: 'What does a hydatid cyst look like on ultrasound?', a: 'A well-defined cyst that may contain daughter cysts (rosette/honeycomb), hydatid sand, a detached floating laminated membrane (“water-lily sign”) or a calcified wall. Classified by Gharbi or WHO-IWGE (CE1–CE5). Confirmed with serology (ELISA, indirect haemagglutination).', k: ['water lily sign', 'Gharbi'] },
    { q: 'How is a liver hydatid cyst treated?', a: 'Albendazole (start before and continue after intervention). PAIR (puncture, aspiration, injection of scolicide such as hypertonic saline, re-aspiration) for suitable uncomplicated cysts, or surgery (open/laparoscopic cystectomy or pericystectomy) with scolicide-soaked packs to prevent spillage. Check for biliary communication. Small calcified inactive cysts can be watched.', k: ['PAIR', 'albendazole'] },
    { q: 'What are the complications of a hydatid cyst?', a: 'Rupture into the biliary tree (biliary colic, obstructive jaundice, cholangitis), peritoneum or pleura/bronchi (expectorating cyst contents); anaphylaxis from spilled fluid; secondary bacterial infection (abscess); pressure effects; recurrence and secondary hydatidosis after spillage.' },
    { q: 'How do you tell a pyogenic from an amoebic liver abscess?', a: 'Pyogenic: older, biliary disease or abdominal sepsis (appendicitis, diverticulitis), often multiple, Klebsiella/E. coli/anaerobes; needs drainage + antibiotics. Amoebic: younger man from an endemic area, often a single right-lobe abscess, positive amoebic serology, “anchovy-sauce” pus; responds to metronidazole without drainage in most cases.' },
    { q: 'Why give vitamin K before intervention in obstructive jaundice?', a: 'Vitamin K is fat-soluble and needs bile salts for absorption, so obstruction causes deficiency of factors II, VII, IX and X (prolonged INR). IV vitamin K corrects it within 6–12 hours and reduces bleeding with ERCP, PTC or surgery.' },
    { q: 'What is the normal CBD diameter on ultrasound?', a: 'Up to about 6 mm (some add ~1 mm per decade over 60, and it may be up to 8–10 mm after cholecystectomy). A dilated duct with jaundice indicates extrahepatic obstruction.' },
  ],
}

export default t
