import type { Topic } from '../types'

const t: Topic = {
  id: 'neck-lump',
  title: 'Neck lump',
  short: 'Neck lump',
  blurb:
    'A neck lump is diagnosed largely by where it is and how it moves. The session covers Macleod’s neck and thyroid examination (from in front and behind, swallow and tongue protrusion), the anatomical triangles and node levels, thyroid nodules and goitre with thyroid status, thyroid cancer and thyroidectomy, and the non-thyroid lumps — branchial and thyroglossal cysts, lymph nodes (reactive, TB, lymphoma, metastatic), salivary glands and carotid body tumours.',
  keyPoints: [
    'Site + movement: moves on swallowing = thyroid (or thyroglossal); moves on tongue protrusion = thyroglossal cyst.',
    'In an adult over 40 a persistent lateral neck lump is malignant (usually a node metastasis from head and neck SCC) until proven otherwise — examine the mouth, throat and skin.',
    'Thyroid examination: inspect front and side, swallow water, palpate from behind (swallow again), nodes, trachea, percuss the manubrium, auscultate for a bruit — then assess thyroid status (hands, pulse, eyes, reflexes, shins).',
    'Thyroid nodule work-up: TFT → ultrasound (U-score/TIRADS) → FNA cytology (Thy1–5 / Bethesda I–VI). A hot nodule on scan is rarely malignant.',
    'Papillary carcinoma (~80%) spreads to nodes and has an excellent prognosis; follicular spreads by blood (needs histology); medullary secretes calcitonin (MEN2 — exclude phaeochromocytoma first); anaplastic is rapidly fatal.',
    'After thyroidectomy watch for: haematoma compressing the airway (open the wound at the bedside), recurrent laryngeal nerve palsy (hoarseness), hypocalcaemia (tingling, Chvostek’s/Trousseau’s).',
  ],
  sections: [
    {
      id: 'anatomy',
      title: 'Neck anatomy for lumps',
      items: [
        '**Anterior triangle**: midline, anterior border of sternocleidomastoid (SCM), lower border of the mandible.',
        '**Posterior triangle**: posterior border of SCM, anterior border of trapezius, middle third of the clavicle.',
        '**Lymph node levels**: I submental (Ia) and submandibular (Ib); II upper jugular (to hyoid); III middle jugular (hyoid to cricoid); IV lower jugular (cricoid to clavicle); V posterior triangle; VI central (pre/paratracheal); VII superior mediastinum.',
        'The **thyroid** lies below the cricoid; the isthmus over tracheal rings 2–4. It is invested in pretracheal fascia, so it moves with swallowing.',
      ],
      source: 'Macleod’s 14e · Ch 9 · pp 184–185 (Figs 9.21–9.22); Ch 10 · p 194',
    },
    {
      id: 'causes',
      title: 'Causes by site',
      table: {
        head: ['Site', 'Lump', 'Distinguishing features'],
        rows: [
          ['Midline', 'Thyroglossal cyst', 'Smooth, round, cystic; moves up on tongue protrusion (and swallowing); near the hyoid'],
          ['Midline', 'Thyroid isthmus / pyramidal lobe', 'Moves on swallowing, not on tongue protrusion'],
          ['Midline', 'Dermoid cyst, submental node', 'Subcutaneous, mobile; node with oral/lip infection'],
          ['Anterior triangle', 'Thyroid lobe (goitre, nodule, tumour)', 'Moves on swallowing'],
          ['Anterior triangle', 'Branchial cyst', 'Young adult, anterior border of SCM at the junction of upper and middle thirds; smooth, fluctuant, not transilluminating; cholesterol crystals'],
          ['Anterior triangle', 'Submandibular gland', 'Below the mandible, bimanually palpable; pain with meals (stone)'],
          ['Anterior triangle', 'Parotid', 'In front of/below the ear; facial nerve weakness suggests malignancy'],
          ['Anterior triangle', 'Carotid body tumour', 'At the bifurcation; pulsatile, moves side to side but not up and down, bruit; do not biopsy'],
          ['Anterior/posterior', 'Lymph nodes', 'Reactive (tender, mobile), TB (matted, cold abscess), lymphoma (rubbery), metastatic (hard, fixed)'],
          ['Posterior triangle', 'Cystic hygroma', 'Infants; soft, compressible, brilliantly transilluminates'],
          ['Supraclavicular', 'Virchow’s node', 'Left: gastric/abdominal malignancy (Troisier’s sign); right: lung/oesophagus'],
          ['Supraclavicular', 'Cervical rib', 'Hard bony mass; thoracic outlet symptoms'],
        ],
      },
      note: 'Age rule: child → congenital or inflammatory; young adult → inflammatory, congenital, lymphoma; > 40 → neoplastic until proven otherwise.',
      source: 'Macleod’s 14e · Ch 9 · p 188 (Box 9.10)',
    },
    {
      id: 'history',
      title: 'History',
      items: [
        '**The lump**: duration, growth (rapid — anaplastic, lymphoma, bleed into a cyst), pain, size change with meals (salivary), infection.',
        '**Compression**: dysphagia, stridor/breathlessness, hoarseness (recurrent laryngeal nerve — suggests malignancy).',
        '**Thyroid status** — hyper: weight loss with good appetite, heat intolerance, sweating, palpitations, tremor, anxiety, diarrhoea, oligomenorrhoea, eye symptoms; hypo: weight gain, cold intolerance, lethargy, constipation, dry skin, menorrhagia.',
        '**Systemic/B symptoms**: fevers, night sweats, weight loss (lymphoma, TB); cough, TB contacts.',
        '**Head and neck cancer risks**: smoking, alcohol, betel/khat, HPV; ENT symptoms — sore throat, otalgia, odynophagia, nasal obstruction or bleeding, mouth ulcers.',
        '**Thyroid cancer risks**: neck irradiation in childhood, family history (MEN2, familial medullary), iodine deficiency.',
        '**Drugs**: amiodarone, lithium; previous thyroid surgery or radioiodine.',
      ],
      source: 'Macleod’s 14e · Ch 10 · pp 194–196; Ch 9 · pp 186–187',
    },
    {
      id: 'exam-thyroid',
      title: 'Thyroid and neck examination (Macleod’s)',
      kind: 'steps',
      intro: 'Sit the patient on a chair with space behind it; expose the neck down to the clavicles.',
      items: [
        '**General inspection**: body habitus, agitation or slowness, sweating, dress (layers in hypothyroidism), voice (hoarse, slow).',
        '**Inspect from the front and side** with the neck slightly extended: scars, swellings, asymmetry, distended veins (retrosternal goitre).',
        '**Swallow test**: ask the patient to take a sip of water and swallow — the thyroid and a thyroglossal cyst rise.',
        '**Tongue protrusion**: a thyroglossal cyst rises; the thyroid does not.',
        '**Palpate from behind** with the neck slightly flexed: index fingers just touching below the cricoid; feel both lobes and the isthmus; swallow again. Note size, shape, consistency (soft, firm, hard), nodularity, tenderness, mobility, a thrill; can you get below it?',
        '**Lymph nodes** systematically (levels I–VI, supraclavicular).',
        '**Trachea**: position (deviation by a large lobe).',
        '**Percuss the manubrium** for dullness (retrosternal extension).',
        '**Auscultate** each lobe for a **bruit** (Graves’ — increased blood flow).',
        '**Pemberton’s sign** (raise both arms — facial plethora and distress = thoracic inlet obstruction by a retrosternal goitre).',
        '**Thyroid status**: hands (sweaty/dry, tremor with paper on the outstretched hands, acropachy, onycholysis, palmar erythema), pulse (tachycardia/AF/bradycardia), eyes (lid retraction, exophthalmos from above/behind, lid lag, ophthalmoplegia, chemosis), proximal myopathy (stand from sitting with arms crossed), reflexes (brisk or slow-relaxing), shins (pretibial myxoedema).',
        '**Non-thyroid lump**: examine the oral cavity and oropharynx (with a light and tongue depressor), skin of scalp/face/ears, parotids; transilluminate cystic lumps; auscultate a pulsatile lump.',
      ],
      source: 'Macleod’s 14e · Ch 10 · pp 197–198; Ch 9 · pp 187–189; Ch 3 · pp 31–33',
    },
    {
      id: 'investigations',
      title: 'Investigations',
      items: [
        '**TFT** first (TSH ± free T4/T3); **antibodies**: TSH-receptor (TRAb — Graves’), anti-TPO (Hashimoto’s); **calcitonin** if medullary suspected; calcium.',
        '**Ultrasound** neck: nodule features (solid, hypoechoic, microcalcification, irregular margins, taller-than-wide, abnormal nodes = suspicious) — graded U1–U5 (BTA) or TIRADS.',
        '**FNA cytology** (ultrasound-guided) — UK Thy1–Thy5 / Bethesda I–VI: non-diagnostic, benign, atypia/follicular lesion of undetermined significance, follicular neoplasm, suspicious, malignant.',
        '**Radionuclide scan** (technetium/iodine) when TSH is low: hot (toxic) nodule vs Graves’ vs multinodular.',
        '**CT/MRI** for retrosternal extent and nodal staging (avoid iodinated contrast before radioiodine).',
        '**Flexible nasendoscopy**: vocal cords before thyroid surgery; search for a head and neck primary.',
        '**Non-thyroid**: FBC, ESR/CRP, EBV serology, HIV test, TB tests (CXR, interferon-γ release assay, FNA with AFB stain/PCR/culture), **core or excision biopsy** for lymphoma (FNA insufficient).',
      ],
      source: 'Macleod’s 14e · Ch 10 · p 198 (Box 10.3)',
    },
    {
      id: 'thyroid',
      title: 'Thyroid disease',
      table: {
        head: ['Cancer', 'Share', 'Key features'],
        rows: [
          ['Papillary', '~80%', 'Young women, radiation; lymphatic spread to neck nodes; psammoma bodies, “Orphan Annie” nuclei; excellent prognosis'],
          ['Follicular', '~10%', 'Older; haematogenous spread (bone, lung); FNA cannot distinguish adenoma from carcinoma — needs capsular/vascular invasion on histology (diagnostic lobectomy)'],
          ['Medullary', '~5%', 'Parafollicular C cells → calcitonin (and CEA); 25% familial (RET — MEN2A/2B); screen for phaeochromocytoma and hyperparathyroidism first'],
          ['Anaplastic', '< 2%', 'Elderly, rapidly enlarging hard mass, compressive symptoms; very poor prognosis'],
          ['Lymphoma', 'Rare', 'Background Hashimoto’s; rapid growth; chemo/radiotherapy'],
        ],
      },
      items: [
        '**Differentiated cancer treatment**: hemithyroidectomy for small low-risk tumours; total thyroidectomy (± central/lateral neck dissection) for larger/high-risk; radioiodine ablation; TSH suppression with levothyroxine; follow-up with thyroglobulin.',
        '**Graves’ disease**: TRAb; diffuse goitre with bruit, eye disease, pretibial myxoedema. Treatment: β-blocker, carbimazole (agranulocytosis — stop and check FBC if sore throat/fever; PTU in the first trimester), radioiodine (not in pregnancy or active eye disease), or total thyroidectomy.',
        '**Multinodular goitre**: euthyroid or toxic; surgery for compression, retrosternal extension, suspicion of cancer, cosmetic concern or toxicity.',
        '**Toxic adenoma**: single hot nodule; radioiodine or lobectomy.',
      ],
    },
    {
      id: 'thyroidectomy',
      title: 'Thyroidectomy — complications',
      items: [
        '**Haemorrhage → airway compression** (first hours): stridor, neck swelling, distress — **open the wound at the bedside** (cut skin and subcutaneous sutures, evacuate clot), call for help, return to theatre.',
        '**Recurrent laryngeal nerve injury**: unilateral → hoarse, weak voice and cough; bilateral → stridor and airway obstruction (may need tracheostomy). **External branch of the superior laryngeal nerve** → loss of high pitch (singers).',
        '**Hypocalcaemia** (parathyroid damage, day 1–3): perioral tingling, cramps, **Chvostek’s sign** (tap facial nerve → twitch), **Trousseau’s sign** (BP cuff → carpopedal spasm), prolonged QT; IV calcium gluconate for severe symptoms, oral calcium + alfacalcidol.',
        '**Thyroid storm** (in poorly prepared hyperthyroid patients): fever, tachycardia/AF, agitation — supportive care, β-blocker, PTU, iodine, steroids.',
        '**Hypothyroidism** (expected after total thyroidectomy — levothyroxine), wound infection, keloid, tracheomalacia (rare).',
      ],
    },
    {
      id: 'other',
      title: 'Non-thyroid lumps',
      items: [
        '**Thyroglossal cyst**: remnant of the thyroglossal duct (foramen caecum → thyroid); midline near the hyoid; moves up with tongue protrusion; may become infected. **Sistrunk’s operation** — excise the cyst, tract and the middle third of the hyoid (reduces recurrence).',
        '**Branchial cyst**: second branchial cleft remnant; young adult; anterior border of SCM at the upper/middle third junction; may enlarge with URTI; aspirate contains cholesterol crystals; excise (in older patients exclude a cystic SCC node metastasis — HPV oropharyngeal cancer).',
        '**Reactive lymphadenitis**: tender, mobile, with infection; review in 2–6 weeks — persistent nodes > 1–1.5 cm need investigation.',
        '**TB lymphadenitis (scrofula)**: matted, rubbery or fluctuant posterior/jugular nodes, cold abscess, sinus (collar-stud abscess); common in endemic areas. FNA (caseating granulomas, AFB), culture/PCR; 6 months of anti-TB therapy.',
        '**Lymphoma**: rubbery painless nodes, B symptoms, alcohol-induced pain (Hodgkin); excision/core biopsy.',
        '**Metastatic SCC**: hard, fixed node in a smoker/drinker over 40 (or HPV-positive younger patient): full ENT examination, nasendoscopy, FNA, CT/MRI/PET, panendoscopy.',
        '**Carotid body tumour (paraganglioma)**: at the bifurcation, pulsatile, moves laterally not vertically (Fontaine’s sign), bruit; imaging shows splaying of ICA and ECA (“lyre sign”); **never biopsy**; surgical excision (Shamblin classification).',
        '**Salivary**: submandibular stones (pain and swelling with meals), pleomorphic adenoma (parotid, slow-growing, painless), Warthin’s tumour (older male smokers, bilateral), malignancy (pain, rapid growth, facial nerve palsy).',
      ],
    },
  ],
  cases: ['thyroid-nodule', 'graves', 'mng', 'thyroglossal-cyst'],
  qa: [
    { q: 'How do you examine the thyroid?', a: 'General inspection (habitus, agitation, sweating, voice). Inspect the neck from the front and side with the neck slightly extended; give a sip of water and watch the gland rise on swallowing; ask the patient to protrude the tongue (a thyroglossal cyst rises). Palpate from behind with the neck slightly flexed — isthmus below the cricoid, then each lobe, swallowing again; note size, consistency, nodularity, tenderness, whether you can get below it. Examine the lymph nodes, tracheal position, percuss the manubrium (retrosternal extension), auscultate for a bruit. Then thyroid status: hands (tremor, sweating, acropachy), pulse, eyes (lid retraction, exophthalmos, lid lag, eye movements), proximal myopathy, reflexes, shins.', k: ['thyroid examination', 'goitre examination', 'thyroid status'] },
    { q: 'How do you examine a neck lump?', a: 'Inspect from the front (scars, swellings, asymmetry) and side; ask the patient to swallow (thyroid and thyroglossal cysts rise) and protrude the tongue (thyroglossal cyst rises); palpate from behind (site, size, shape, consistency, tenderness, mobility, fixation, can you get below it), examine lymph node levels systematically, check tracheal position, percuss the manubrium, auscultate for a bruit, transilluminate cystic lumps; then thyroid status and examination of the mouth, throat and skin.', k: ['neck examination'] },
    { q: 'Why does the thyroid move on swallowing?', a: 'It is enclosed in the pretracheal fascia, which is attached to the larynx (thyroid and cricoid cartilages) and hyoid, so the gland rises with the larynx on swallowing.' },
    { q: 'Why does a thyroglossal cyst move with tongue protrusion?', a: 'It arises from a remnant of the thyroglossal duct, which runs from the foramen caecum at the base of the tongue to the thyroid, closely related to the hyoid — the tract remains attached to the tongue base, so the cyst moves up when the tongue is protruded.' },
    { q: 'What is Sistrunk’s operation?', a: 'Excision of a thyroglossal cyst together with its tract and the central (middle third) portion of the hyoid bone, up to the foramen caecum — reducing recurrence from ~50% (cyst alone) to < 5%.' },
    { q: 'What are the boundaries of the anterior and posterior triangles of the neck?', a: 'Anterior: midline, anterior border of sternocleidomastoid and lower border of the mandible. Posterior: posterior border of sternocleidomastoid, anterior border of trapezius and the middle third of the clavicle.', k: ['triangles of the neck'] },
    { q: 'What are the cervical lymph node levels?', a: 'I: submental (Ia) and submandibular (Ib). II: upper jugular (skull base to hyoid). III: middle jugular (hyoid to cricoid). IV: lower jugular (cricoid to clavicle). V: posterior triangle. VI: central compartment (pre/paratracheal). VII: superior mediastinum.', k: ['node levels'] },
    { q: 'What is the “rule of 80” for neck masses?', a: 'In adults (> 40), about 80% of non-thyroid neck masses are neoplastic; 80% of those are malignant; 80% of the malignancies are metastatic; and 80% of the metastases come from a primary above the clavicle (head and neck SCC). Persistent adult neck lumps need urgent assessment.' },
    { q: 'How do you investigate a thyroid nodule?', a: 'TSH first: if low → radionuclide scan (a hot nodule is rarely malignant). If normal/high → ultrasound (U1–U5/TIRADS) → ultrasound-guided FNA for suspicious nodules (Thy1–5/Bethesda I–VI). Calcitonin if medullary suspected. Nasendoscopy before surgery.', k: ['thyroid nodule work up', 'FNA'] },
    { q: 'What are the features of a suspicious thyroid nodule on ultrasound?', a: 'Solid and hypoechoic, microcalcifications, irregular/infiltrative margins, taller-than-wide shape, intranodular vascularity, extrathyroidal extension, and abnormal cervical lymph nodes.' },
    { q: 'What is the Thy (or Bethesda) classification?', a: 'FNA cytology categories: Thy1/Bethesda I non-diagnostic; Thy2/II benign; Thy3a/III atypia of undetermined significance; Thy3f/IV follicular neoplasm (diagnostic lobectomy — FNA cannot assess capsular invasion); Thy4/V suspicious of malignancy; Thy5/VI malignant.', k: ['Bethesda', 'Thy3f'] },
    { q: 'Compare the types of thyroid cancer.', a: 'Papillary (~80%): young women, radiation, lymphatic spread, excellent prognosis. Follicular (~10%): haematogenous spread to bone/lung, diagnosed on histology. Medullary (~5%): C cells, calcitonin, MEN2/RET — exclude phaeochromocytoma first. Anaplastic: elderly, rapidly growing, fatal. Lymphoma: on a background of Hashimoto’s.', k: ['papillary', 'follicular', 'medullary', 'anaplastic'] },
    { q: 'Why can’t FNA diagnose follicular carcinoma?', a: 'Follicular carcinoma and follicular adenoma look the same cytologically; the diagnosis depends on capsular or vascular invasion, which needs histology of the whole nodule — hence diagnostic hemithyroidectomy for Thy3f/Bethesda IV nodules.' },
    { q: 'What must you exclude before operating on a medullary thyroid cancer?', a: 'Phaeochromocytoma (MEN2) — check plasma/urinary metanephrines; an undiagnosed phaeochromocytoma can cause a hypertensive crisis at induction. Also check calcium (hyperparathyroidism in MEN2A) and test for a RET mutation.' },
    { q: 'What are the complications of thyroidectomy?', a: 'Early: haemorrhage with airway compression (open the wound at the bedside), recurrent laryngeal nerve palsy (hoarseness; bilateral — stridor), hypocalcaemia (parathyroid injury), thyroid storm, wound infection. Late: hypothyroidism, permanent hypoparathyroidism, external branch of superior laryngeal nerve palsy (voice pitch), keloid.', k: ['thyroid surgery complications'] },
    { q: 'What do you do for a tense neck haematoma after thyroidectomy?', a: 'An airway emergency: call for senior/anaesthetic help, sit the patient up, give oxygen, and open the wound at the bedside — cut the skin and subcutaneous (and strap muscle) sutures to evacuate the clot (SCOOP: Skin exposure, Cut sutures, Open skin, Open muscles, Pack) — then return to theatre.', k: ['SCOOP', 'airway'] },
    { q: 'What are Chvostek’s and Trousseau’s signs?', a: 'Signs of hypocalcaemia (e.g. after thyroidectomy). Chvostek’s: tapping the facial nerve in front of the ear causes twitching of the facial muscles. Trousseau’s: inflating a BP cuff above systolic for up to 3 minutes causes carpal spasm (flexed wrist and MCP joints, extended fingers).' },
    { q: 'What are the signs of Graves’ disease specifically (not just thyrotoxicosis)?', a: 'Diffuse smooth goitre with a bruit/thrill, Graves’ ophthalmopathy (proptosis, chemosis, ophthalmoplegia, periorbital oedema), pretibial myxoedema and thyroid acropachy — caused by TSH-receptor antibodies. Lid retraction and lid lag occur in any thyrotoxicosis.', k: ['Graves ophthalmopathy'] },
    { q: 'How is Graves’ disease treated?', a: 'β-blocker for symptoms; antithyroid drugs (carbimazole for 12–18 months, titration or block-and-replace; PTU in the first trimester); radioiodine (avoid in pregnancy, breastfeeding, active eye disease); total thyroidectomy (large goitre, eye disease, pregnancy planning, drug failure). Smoking cessation for eye disease.' },
    { q: 'What is the important side effect of carbimazole?', a: 'Agranulocytosis (rare, sudden). Patients must stop it and get an urgent FBC if they develop a sore throat, mouth ulcers or fever. Also rash, cholestatic jaundice, and teratogenicity in the first trimester.' },
    { q: 'What is a branchial cyst?', a: 'A remnant of the second branchial cleft presenting in a young adult as a smooth, fluctuant, non-transilluminating lump at the anterior border of sternocleidomastoid at the junction of its upper and middle thirds, often enlarging with URTIs. Aspirate contains cholesterol crystals. Excise; in patients > 40 exclude a cystic nodal metastasis from oropharyngeal SCC.' },
    { q: 'What are the features of tuberculous cervical lymphadenitis?', a: 'Painless, firm or matted lymph nodes (often posterior triangle/jugular chain), which may soften into a cold abscess or discharge through the skin (collar-stud abscess, sinus); systemic symptoms may be mild. Diagnose by FNA/excision (caseating granulomas, AFB, culture, PCR); treat with 6 months of anti-TB therapy.', k: ['scrofula', 'collar stud abscess'] },
    { q: 'What is a carotid body tumour?', a: 'A paraganglioma at the carotid bifurcation: a painless, pulsatile lump in the upper anterior triangle that moves side to side but not vertically, with a bruit. Imaging (duplex/CT/MR angiography) shows splaying of the internal and external carotids (lyre sign). Never biopsy; excise (Shamblin grade guides difficulty).', k: ['paraganglioma', 'lyre sign'] },
    { q: 'What is Pemberton’s sign?', a: 'Raising both arms above the head for about a minute causes facial congestion/plethora, distended neck veins and sometimes stridor — obstruction at the thoracic inlet by a retrosternal goitre.' },
    { q: 'What causes a diffuse goitre?', a: 'Physiological (puberty, pregnancy), iodine deficiency (endemic), Graves’ disease, Hashimoto’s thyroiditis, subacute (de Quervain’s) thyroiditis (painful, tender), drugs (lithium, amiodarone), dyshormonogenesis.' },
  ],
}

export default t
