import type { Topic } from '../types'

const t: Topic = {
  id: 'periop',
  title: 'Pre- & post-operative care',
  short: 'Peri-op care',
  blurb:
    'Getting a patient safely through an operation: pre-operative assessment (fitness, ASA, investigations, drugs, fasting, consent, VTE), the post-operative ward round (fluids, analgesia, monitoring), and recognising the complications — fever, low urine output, confusion, bleeding, leaks, VTE — with a structured ABCDE approach to the deteriorating patient.',
  keyPoints: [
    'Assess the deteriorating patient with ABCDE and act on NEWS2: ≥ 5 urgent review, ≥ 7 emergency (critical care).',
    'Post-op fever by day: lungs (day 1–2), urine (day 3), wound (day 5), leak/collection (day 5–7), VTE (day 5–10), plus drugs, lines and transfusion.',
    'Low urine output (< 0.5 mL/kg/h): check the catheter first, then fluid status; give a fluid challenge if dry; look for sepsis, bleeding and nephrotoxins.',
    'Anastomotic leak (day 3–7): tachycardia, fever, abdominal pain, ileus, rising CRP — CT with contrast, resuscitate, antibiotics, back to theatre or drain.',
    'Fasting: 6 h food, 2 h clear fluids. Stop warfarin 5 days, clopidogrel 7 days, DOACs 1–3 days; bridge only high thrombotic risk.',
    'Maintenance fluids per day: 25–30 mL/kg water, ~1 mmol/kg Na⁺, K⁺ and Cl⁻, 50–100 g glucose.',
  ],
  sections: [
    {
      id: 'preop',
      title: 'Pre-operative assessment',
      items: [
        '**History**: the surgical problem, comorbidities (cardiac — angina, MI, failure, valve disease; respiratory — COPD, asthma, OSA; diabetes; renal; liver; bleeding disorders), **functional capacity** (can they climb a flight of stairs ≈ 4 METs?), previous anaesthetics and complications, family history (malignant hyperthermia, suxamethonium apnoea).',
        '**Drugs and allergies**: anticoagulants, antiplatelets, insulin and oral hypoglycaemics, steroids, ACE inhibitors, OCP/HRT, MAOIs, herbal remedies; allergies (latex, antibiotics, chlorhexidine).',
        '**Social**: smoking (stop — wound and chest complications), alcohol (withdrawal risk), support at home.',
        '**Examination**: airway (Mallampati, mouth opening, neck movement, teeth), cardiorespiratory, BMI, site of surgery.',
        '**ASA grade**: I healthy; II mild systemic disease; III severe systemic disease; IV severe disease that is a constant threat to life; V moribund, not expected to survive without surgery; VI brain-dead organ donor. Add “E” for emergency.',
      ],
    },
    {
      id: 'preop-tests',
      title: 'Pre-operative investigations (guided by ASA and surgery grade)',
      items: [
        '**FBC** (anaemia — correct before major surgery), **U&E** (renal function, K⁺), LFT/coagulation if liver disease or anticoagulation, **group and save/crossmatch** for surgery with blood loss.',
        '**ECG** for cardiovascular/renal disease or diabetes and older patients having major surgery; echocardiogram for murmurs or heart failure.',
        '**HbA1c** in diabetics; pregnancy test in women of childbearing age; sickle test if at risk.',
        '**CXR** only with a specific indication; **CPET** to quantify risk before major surgery.',
        '**MRSA screening**; urine dipstick if indicated.',
      ],
      source: 'NICE NG45',
    },
    {
      id: 'preop-plan',
      title: 'Drugs, fasting and preparation',
      items: [
        '**Fasting**: no food for 6 h, clear fluids up to 2 h (“2–4–6”: clear fluids 2, breast milk 4, food/formula 6). ERAS: carbohydrate drinks up to 2 h before.',
        '**Warfarin**: stop 5 days before (INR < 1.5); bridge with LMWH only if high thrombotic risk (mechanical mitral valve, recent VTE/stroke). **DOACs**: stop 24–48 h before (longer with poor renal function or high-bleeding-risk surgery). **Clopidogrel/ticagrelor**: 5–7 days (discuss if recent coronary stent). **Aspirin**: usually continue.',
        '**Diabetes**: omit oral hypoglycaemics on the day (metformin depends on renal function and contrast), reduce long-acting insulin by ~20% the night before; **variable-rate insulin infusion** if more than one meal will be missed or poorly controlled.',
        '**Steroids**: continue and give **stress-dose hydrocortisone** at induction (adrenal suppression).',
        '**Stop the combined pill/HRT 4 weeks** before major surgery (VTE).',
        '**VTE risk assessment**: mechanical prophylaxis (stockings, intermittent pneumatic compression) + LMWH unless contraindicated; extended 28-day prophylaxis after major abdominal/pelvic cancer surgery.',
        '**Consent**: the procedure, benefits, risks (common and serious), alternatives including doing nothing (Montgomery); mark the site; WHO Surgical Safety Checklist (sign in, time out, sign out).',
        '**Bowel preparation**, antibiotic prophylaxis at induction (within 60 min of incision), stoma site marking.',
      ],
    },
    {
      id: 'eras',
      title: 'Enhanced recovery (ERAS)',
      items: [
        '**Before**: education, prehabilitation, stop smoking/alcohol, correct anaemia, carbohydrate loading, no routine bowel prep (colonic), minimal fasting.',
        '**During**: minimally invasive surgery, goal-directed fluids (avoid overload), normothermia, regional anaesthesia, avoid routine NG tubes and drains, PONV prophylaxis.',
        '**After**: early oral intake and mobilisation (day 0–1), multimodal opioid-sparing analgesia, early catheter removal, VTE prophylaxis, planned discharge criteria.',
      ],
    },
    {
      id: 'postop',
      title: 'The post-operative ward round',
      items: [
        '**Read the operation note** (what was done, blood loss, drains, specific instructions) and observations/NEWS chart.',
        '**Ask**: pain, nausea/vomiting, flatus/bowels, eating/drinking, passing urine, breathing, mobilising, calf pain.',
        '**Examine**: general appearance, pulse/BP/temperature/RR/SpO₂, chest, abdomen (distension, tenderness, bowel sounds), **wound** (erythema, discharge, dehiscence), **drains** (volume and character: blood, bile, pus, enteric content), stoma (colour, output), catheter and urine output, calves, IV sites, delirium.',
        '**Review**: fluid balance chart, drug chart (analgesia, antiemetics, VTE prophylaxis, antibiotics, restarting usual medicines), bloods (Hb, U&E, CRP), plan for diet, mobilisation, lines, drains and discharge.',
        '**Fluids**: maintenance per day — **25–30 mL/kg water, ~1 mmol/kg Na⁺, K⁺ and Cl⁻, 50–100 g glucose** (e.g. 0.18% saline/4% glucose with KCl); replace losses (vomiting, NG, drains, stoma) and stop IV fluids once drinking.',
        '**Analgesia**: WHO ladder, multimodal (paracetamol, NSAIDs if safe, opioids — PCA), epidural/regional blocks; laxatives and antiemetics alongside opioids.',
      ],
    },
    {
      id: 'complications',
      title: 'Post-operative complications by time',
      table: {
        head: ['When', 'Complications'],
        rows: [
          ['Immediate (< 24 h)', 'Primary or reactive haemorrhage, anaesthetic complications, airway problems, hypothermia, PONV, atelectasis, urinary retention'],
          ['Early (1–30 days)', 'Atelectasis/pneumonia, wound infection (day 5–7), anastomotic leak (day 3–7), ileus, UTI, DVT/PE (day 5–10), delirium, AKI, secondary haemorrhage (day 7–10, infection), wound dehiscence (day 7–10)'],
          ['Late (> 30 days)', 'Incisional hernia, adhesions and obstruction, chronic pain, keloid/hypertrophic scars, recurrence of disease'],
        ],
      },
    },
    {
      id: 'fever',
      title: 'Post-operative fever',
      items: [
        '**Day 0–2**: physiological inflammatory response, atelectasis (common, often over-blamed), aspiration, transfusion reaction.',
        '**Day 3–5**: pneumonia, UTI (catheter), cannula/line infection.',
        '**Day 5–7**: wound infection, **anastomotic leak, intra-abdominal collection**, C. difficile.',
        '**Day 5–10+**: DVT/PE, drug fever.',
        'Mnemonic — the 5 Ws: **Wind** (lungs), **Water** (urine), **Wound**, **Walking** (VTE), **What did we do?** (drugs, lines, transfusion).',
        'Assess with ABCDE; examine chest, wound, abdomen, calves, lines; send cultures, urine, CRP/FBC; CXR; CT abdomen if leak/collection suspected.',
      ],
    },
    {
      id: 'oliguria',
      title: 'Low urine output',
      items: [
        '**Definition**: < 0.5 mL/kg/h for > 6 h (or < 400 mL/day).',
        '**First**: is the catheter blocked? Flush or replace it; bladder scan if no catheter (retention).',
        '**Pre-renal** (commonest): hypovolaemia (inadequate fluids, bleeding, third-space losses, vomiting/NG/drains), sepsis, cardiac failure.',
        '**Renal**: ATN from prolonged hypotension, nephrotoxins (NSAIDs, aminoglycosides, contrast, ACE inhibitors), rhabdomyolysis.',
        '**Post-renal**: retention, blocked catheter, ureteric injury (pelvic surgery).',
        '**Management**: assess fluid status (pulse, BP, CRT, JVP, mucosae, fluid balance), **fluid challenge** 250–500 mL crystalloid over 15 min and reassess, stop nephrotoxins, check U&E/K⁺ and VBG, treat sepsis; escalate if persistent (AKI criteria, hyperkalaemia, acidosis).',
      ],
    },
    {
      id: 'deteriorating',
      title: 'The deteriorating patient (ABCDE)',
      kind: 'steps',
      items: [
        '**Approach safely**; ask “Are you alright?”; if unresponsive check pulse and breathing and call for help (cardiac arrest call if no pulse).',
        '**A — Airway**: talking? Stridor, gurgling, snoring? Head tilt/chin lift, jaw thrust, suction, airway adjuncts; high-flow oxygen 15 L via non-rebreathe mask.',
        '**B — Breathing**: RR, SpO₂, chest movement, trachea, percussion, auscultation; ABG; CXR; treat (bronchodilators, drain a pneumothorax).',
        '**C — Circulation**: HR, BP, CRT, peripheral temperature, JVP, urine output; IV access ×2, bloods (FBC, U&E, lactate, cultures, crossmatch), fluid bolus 500 mL crystalloid and reassess; ECG; look for bleeding (drains, wound, abdomen).',
        '**D — Disability**: AVPU/GCS, pupils, **capillary glucose**, drug chart (opioids — naloxone), pain.',
        '**E — Exposure**: temperature, wound, drains, calves, rashes, abdomen; then reassess ABCDE, escalate (SBAR), document and plan.',
      ],
      note: 'NEWS2 response: 1–4 ward nurse assessment; 5–6 (or any single score of 3) urgent doctor review; ≥ 7 emergency response, consider critical care.',
      source: 'Macleod’s 14e · Ch 18 · pp 339–346',
    },
    {
      id: 'specifics',
      title: 'Specific complications',
      items: [
        '**Anastomotic leak** (day 3–7): tachycardia (often first), fever, abdominal pain out of keeping, prolonged ileus, peritonism, confusion, rising CRP (> 150–200 mg/L on day 3–4 is a warning), enteric content in a drain. CT with contrast; resuscitate, antibiotics, then percutaneous drainage (contained) or relaparotomy/laparoscopy ± stoma.',
        '**Post-operative haemorrhage**: primary (during surgery), reactive (within 24 h — slipped ligature as BP rises), secondary (7–10 days — infection eroding a vessel). Signs: tachycardia, hypotension, falling Hb, blood in drains, distension. Resuscitate, correct clotting, return to theatre or embolise.',
        '**Wound infection**: day 5–7 erythema, pain, discharge; open and drain the wound, swab, antibiotics if cellulitis or systemic signs.',
        '**Wound dehiscence/burst abdomen** (day 7–10): pink serosanguinous discharge heralds it; cover with saline-soaked sterile packs, reassure, analgesia, return to theatre for mass closure.',
        '**Paralytic ileus**: distension, vomiting, absent bowel sounds, no flatus; correct K⁺/Mg²⁺/Na⁺, reduce opioids, NG tube if vomiting, mobilise; exclude mechanical obstruction or a leak if prolonged.',
        '**Post-operative confusion**: hypoxia, sepsis (chest, urine, wound, leak), hypoglycaemia, hyponatraemia, drugs (opioids, anticholinergics), alcohol withdrawal (day 2–4), urinary retention, constipation, pain, stroke/MI.',
        '**PE**: sudden breathlessness, pleuritic pain, tachycardia, hypoxia — CTPA; treatment-dose anticoagulation (discuss bleeding risk with the surgeon).',
      ],
    },
    {
      id: 'clavien',
      title: 'Clavien–Dindo classification',
      table: {
        head: ['Grade', 'Definition'],
        rows: [
          ['I', 'Deviation from the normal course without pharmacological/surgical intervention (antiemetics, analgesics, physio, wound opened at bedside allowed)'],
          ['II', 'Needs drugs beyond grade I, blood transfusion or parenteral nutrition'],
          ['IIIa / IIIb', 'Needs surgical, endoscopic or radiological intervention — without (a) or under (b) general anaesthesia'],
          ['IVa / IVb', 'Life-threatening: single (a) or multi-organ (b) dysfunction needing critical care'],
          ['V', 'Death'],
        ],
      },
    },
  ],
  cases: ['postop-leak', 'ileostomy'],
  qa: [
    { q: 'What is the ASA classification?', a: 'American Society of Anesthesiologists physical status: I normal healthy; II mild systemic disease (controlled hypertension, smoker, BMI 30–40); III severe systemic disease (poorly controlled diabetes, COPD, BMI ≥ 40, stable angina); IV severe disease that is a constant threat to life (recent MI, sepsis); V moribund, not expected to survive without the operation; VI brain-dead donor. “E” = emergency.', k: ['ASA grade'] },
    { q: 'What are the fasting times before surgery?', a: 'Food (including milk) 6 hours, breast milk 4 hours, clear fluids 2 hours (“2–4–6”). In ERAS, carbohydrate-rich clear drinks are encouraged up to 2 hours before. Emergency patients are treated as “full stomach” (rapid sequence induction).', k: ['nil by mouth', 'NBM', '2-4-6'] },
    { q: 'How do you manage warfarin before elective surgery?', a: 'Stop 5 days before (aim INR < 1.5 the day before; give oral vitamin K if still raised). Bridging LMWH only for high thrombotic risk (mechanical mitral valve, recent VTE < 3 months, recent stroke). Restart 12–24 h after surgery when haemostasis is secure.', k: ['anticoagulation', 'bridging'] },
    { q: 'How long before surgery do you stop DOACs?', a: 'Typically 24 hours for low-bleeding-risk and 48 hours for high-bleeding-risk surgery with normal renal function; longer (up to 72–96 h) for dabigatran with impaired renal function. No bridging needed. Restart 24–72 h after surgery.', k: ['apixaban', 'rivaroxaban', 'dabigatran'] },
    { q: 'How do you manage diabetes around surgery?', a: 'Aim for a short starve and first on the list. Reduce long-acting insulin by about 20% the evening before; omit short-acting and most oral agents on the morning of surgery (metformin can continue once-daily if eGFR normal and one meal missed); variable-rate IV insulin infusion if more than one meal will be missed or glucose is poorly controlled (HbA1c > 69). Check glucose hourly; restart usual treatment when eating.', k: ['VRIII', 'sliding scale', 'insulin'] },
    { q: 'Why give steroid cover peri-operatively?', a: 'Long-term steroids suppress the hypothalamic–pituitary–adrenal axis, so the patient cannot mount a cortisol stress response — risk of Addisonian crisis (hypotension). Give hydrocortisone at induction (e.g. 50–100 mg) and continue stress doses post-operatively depending on the size of surgery.' },
    { q: 'What VTE prophylaxis do surgical patients need?', a: 'Risk-assess everyone. Mechanical (anti-embolism stockings, intermittent pneumatic compression) plus pharmacological (LMWH such as enoxaparin 40 mg daily, adjusted for weight and renal function) unless the bleeding risk is high. Extended 28-day prophylaxis after major abdominal/pelvic cancer surgery. Early mobilisation and hydration.', k: ['DVT prophylaxis', 'LMWH'] },
    { q: 'What are the elements of informed consent?', a: 'The patient has capacity, consent is voluntary, and they are given sufficient information: the diagnosis, the procedure, its benefits, material risks (what a reasonable patient would want to know, and what this patient would — Montgomery), alternatives including no treatment. Documented and the site marked.' },
    { q: 'What is the WHO Surgical Safety Checklist?', a: 'Three pauses: Sign in (before anaesthesia — identity, site, consent, allergies, airway, blood loss risk), Time out (before incision — team introductions, procedure, antibiotics within 60 min, anticipated events, imaging), Sign out (before leaving theatre — procedure recorded, counts correct, specimens labelled, concerns for recovery).' },
    { q: 'What are maintenance fluid requirements for an adult?', a: 'Per 24 hours: 25–30 mL/kg water, approximately 1 mmol/kg each of sodium, potassium and chloride, and 50–100 g glucose (to limit ketosis). E.g. a 70 kg adult: ~2 L of 0.18% saline/4% glucose with 20–40 mmol KCl per litre. Replace ongoing losses separately and reassess daily (NICE CG174).', k: ['IV fluids', 'NICE CG174'] },
    { q: 'What are the causes of post-operative fever by day?', a: 'Day 0–2: inflammatory response, atelectasis, transfusion reaction. Day 3–5: pneumonia, UTI, line infection. Day 5–7: wound infection, anastomotic leak/collection. Day 5–10: DVT/PE. Any time: drug fever. Mnemonic 5 Ws: Wind, Water, Wound, Walking, What did we do (drugs/lines).', k: ['5 Ws', 'pyrexia'] },
    { q: 'How do you assess a patient with low urine output post-operatively?', a: 'Check the catheter (flush/replace) or bladder scan; assess fluid status (HR, BP, CRT, JVP, mucous membranes, fluid balance, drains); review drugs (NSAIDs, ACEi, gentamicin); bloods (U&E, K⁺, VBG). If hypovolaemic give a 250–500 mL crystalloid bolus over 15 min and reassess; treat sepsis or bleeding; escalate if persistent oliguria, AKI or hyperkalaemia.', k: ['oliguria'] },
    { q: 'What are the signs of an anastomotic leak?', a: 'Usually day 3–7: tachycardia (often the first sign), fever, increasing abdominal pain and distension, prolonged ileus, peritonism, new arrhythmia (AF), confusion, oliguria; enteric/faeculent fluid in a drain; rising CRP (> 150–200 mg/L on day 3–4) and WCC. CT with contrast confirms.', k: ['anastomotic leak'] },
    { q: 'How is an anastomotic leak managed?', a: 'ABCDE resuscitation, NBM, IV fluids, broad-spectrum antibiotics, senior review. A small contained collection may be drained percutaneously; generalised peritonitis or a large leak needs relaparotomy/laparoscopy — washout and usually taking down or defunctioning the anastomosis (end stoma or loop ileostomy). Often critical care.' },
    { q: 'What is the difference between primary, reactive and secondary haemorrhage?', a: 'Primary: during the operation. Reactive: within 24 hours, as blood pressure recovers and a ligature slips or a vessel in spasm opens. Secondary: 7–10 days later, from infection eroding a vessel.' },
    { q: 'What is wound dehiscence and how do you manage a burst abdomen?', a: 'Separation of the wound layers, typically day 7–10; heralded by pink serosanguinous discharge. With a burst abdomen (evisceration): reassure, cover the bowel with sterile saline-soaked packs, analgesia, IV fluids, NBM, and return to theatre for mass closure. Risk factors: obesity, malnutrition, steroids, infection, raised intra-abdominal pressure, poor technique.' },
    { q: 'What are the causes of post-operative confusion?', a: 'Hypoxia, sepsis (chest, urine, wound, leak), metabolic (hypoglycaemia, hyponatraemia, hypercalcaemia, uraemia), drugs (opioids, sedatives, anticholinergics), alcohol or benzodiazepine withdrawal, urinary retention, constipation, pain, sleep deprivation, MI or stroke. Treat the cause; reorientate; avoid sedatives where possible.', k: ['delirium'] },
    { q: 'What is a paralytic ileus and how is it managed?', a: 'Temporary loss of gut motility after surgery (especially bowel handling), worsened by opioids, electrolyte disturbance (low K⁺, Mg²⁺, Na⁺), sepsis or retroperitoneal irritation. Distension, vomiting, absent bowel sounds, no flatus. Correct electrolytes, minimise opioids, NG tube if vomiting, IV fluids, mobilise; consider PN if prolonged; exclude obstruction or a leak (CT).' },
    { q: 'What is NEWS2 and how do you respond?', a: 'The National Early Warning Score: points for respiratory rate, SpO₂ (scale 1 or 2), supplemental oxygen, systolic BP, pulse, consciousness (including new confusion) and temperature. 0–4: ward-based response (low); 5–6 or a single parameter scoring 3: urgent review by a doctor; ≥ 7: emergency response, consider critical care.', k: ['early warning score'] },
    { q: 'Describe the ABCDE approach.', a: 'Airway (patent? obstruction — manoeuvres, suction, adjuncts, oxygen), Breathing (RR, SpO₂, chest exam, ABG, CXR), Circulation (HR, BP, CRT, JVP, urine output, IV access, bloods, fluid challenge, ECG), Disability (AVPU/GCS, pupils, glucose, drugs), Exposure (temperature, wounds, drains, calves, rashes). Treat as you find; reassess; call for help early.', k: ['ABCDE'] },
    { q: 'What is the Clavien–Dindo classification?', a: 'A grading of post-operative complications by the treatment needed: I no intervention; II drugs, transfusion or TPN; III intervention (IIIa without, IIIb under general anaesthesia); IV life-threatening, critical care (IVa single organ, IVb multi-organ); V death.' },
    { q: 'What are the principles of enhanced recovery after surgery (ERAS)?', a: 'Pre-op: education, prehabilitation, optimisation, carbohydrate loading, minimal fasting. Intra-op: minimally invasive surgery, goal-directed fluids, normothermia, regional analgesia, avoid routine drains/NG tubes. Post-op: early eating, early mobilisation, multimodal opioid-sparing analgesia, early removal of catheters and lines.', k: ['ERAS', 'enhanced recovery'] },
    { q: 'When should antibiotic prophylaxis be given?', a: 'For clean-contaminated and contaminated surgery (and clean surgery with implants/mesh): a single dose IV within 60 minutes before skin incision, repeated if the operation is long or blood loss large. Not continued post-operatively unless treating established infection.' },
    { q: 'What is the WHO analgesic ladder?', a: 'Step 1: non-opioid (paracetamol, NSAID) ± adjuvant. Step 2: weak opioid (codeine, tramadol) + non-opioid. Step 3: strong opioid (morphine, oxycodone) + non-opioid. Post-operatively use multimodal analgesia — regular paracetamol, NSAIDs if safe, opioids as needed (PCA), regional techniques — with laxatives and antiemetics.', k: ['pain relief'] },
  ],
}

export default t
