import type { Topic } from '../types'

const t: Topic = {
  id: 'perianal',
  title: 'Painful perianal conditions',
  short: 'Perianal',
  blurb:
    'Anal pain is common, distressing and usually benign — but the diagnosis is made by looking. The session covers the history that separates fissure, abscess, thrombosed haemorrhoids and fistula, a sensitive and correct perianal and rectal examination (Macleod’s left lateral position, inspection, DRE, proctoscopy), and the treatment of each condition — without missing anal cancer, Crohn’s disease or Fournier’s gangrene.',
  keyPoints: [
    'Sharp tearing pain on defecation lasting minutes to hours, bright red blood on the paper = anal fissure (posterior midline in 90%). Don’t force a DRE — inspect.',
    'Constant throbbing pain, a hot tender swelling, fever = perianal abscess: incision and drainage (antibiotics alone don’t treat it).',
    'Sudden painful purple lump at the anal margin = thrombosed external haemorrhoid (perianal haematoma); excise within 72 h, otherwise conservative.',
    'Recurrent abscess or persistent discharge = fistula-in-ano. Goodsall’s rule: posterior external openings track to the posterior midline; anterior ones run straight in.',
    'Describe positions as a clock face with the patient in the lithotomy position (12 o’clock anterior, 6 o’clock posterior). Internal haemorrhoids at 3, 7 and 11.',
    'Lateral or multiple fissures, or a non-healing ulcer → think Crohn’s, TB, syphilis, HIV, anal cancer — examine under anaesthesia and biopsy.',
  ],
  sections: [
    {
      id: 'anatomy',
      title: 'Anatomy that matters',
      items: [
        '**Anal canal** ~4 cm; the **dentate (pectinate) line** marks the change from columnar (above — visceral nerves, painless) to squamous (below — somatic, very sensitive) epithelium. Anal glands open into crypts at the dentate line.',
        '**Internal sphincter**: smooth muscle, involuntary (resting tone — spasm causes fissure pain). **External sphincter**: skeletal, voluntary (squeeze). The **puborectalis** sling forms the anorectal ring.',
        '**Haemorrhoids** are vascular cushions (left lateral, right anterior, right posterior — **3, 7 and 11 o’clock** in lithotomy). Internal above the dentate line; external below.',
        '**Clock face**: always quoted with the patient in lithotomy — 12 anterior (scrotum/vagina), 6 posterior (coccyx).',
      ],
    },
    {
      id: 'causes',
      title: 'Causes of anal pain',
      table: {
        head: ['Condition', 'Pain', 'Other features'],
        rows: [
          ['Anal fissure', 'Severe, sharp/tearing on defecation, lasting minutes–hours after', 'Bright red blood on paper; constipation; sentinel tag; posterior midline'],
          ['Perianal abscess', 'Constant, throbbing, worse sitting, building over days', 'Hot, red, tender swelling, fever; may discharge'],
          ['Thrombosed external haemorrhoid', 'Sudden, constant, maximal at 48–72 h', 'Tense blue/purple lump at the anal verge'],
          ['Prolapsed thrombosed internal haemorrhoids', 'Severe, constant', 'Irreducible, oedematous, dusky prolapse'],
          ['Fistula-in-ano', 'Intermittent, relieved when it discharges', 'Persistent discharge, recurrent abscess; external opening'],
          ['Pilonidal abscess', 'Throbbing in the natal cleft (not anal)', 'Midline pits, hair; young hirsute men'],
          ['Anal cancer', 'Usually late; pain, bleeding, mass', 'Non-healing ulcer, inguinal nodes; HPV, HIV, smoking'],
          ['Proctalgia fugax', 'Sudden severe cramp for seconds–minutes, often at night', 'Normal examination; functional'],
          ['Fournier’s gangrene', 'Severe pain out of proportion, then numbness', 'Diabetic/immunocompromised; crepitus, skin necrosis, sepsis — emergency'],
        ],
      },
    },
    {
      id: 'history',
      title: 'History',
      items: [
        '**Pain**: onset, relation to defecation (during/after — fissure; constant — abscess/thrombosis), character, duration, sitting.',
        '**Bleeding**: on the paper, in the pan, mixed with stool, colour (bright red outlet bleeding vs dark).',
        '**Lump**: prolapse with defecation, reducible or not; swelling, discharge (pus, mucus, faecal), itch.',
        '**Bowels**: constipation and straining, diarrhoea, change in habit (cancer), tenesmus, incontinence (before any sphincter surgery).',
        '**Systemic**: fever, rigors, weight loss.',
        '**Associations**: Crohn’s disease (abdominal pain, diarrhoea), diabetes/immunosuppression (abscess, Fournier’s), HIV and STIs, anoreceptive intercourse, pregnancy and childbirth (anterior fissure, haemorrhoids, sphincter injury), previous anal surgery.',
        '**Drugs**: opioids, iron (constipation), anticoagulants.',
      ],
    },
    {
      id: 'exam',
      title: 'Perianal and rectal examination (Macleod’s)',
      kind: 'steps',
      intro: 'Explain why it is needed and what it involves; it may be uncomfortable but should not be painful; obtain verbal consent; offer a chaperone and record their name (or the refusal).',
      items: [
        '**Position**: left lateral, buttocks at the edge of the couch, knees drawn up to the chest, heels clear of the perineum; cover the patient.',
        '**Gloves and good light**. Gently part the buttocks.',
        '**Inspect the perianal skin**: excoriation, skin tags (a sentinel tag points to a fissure), external haemorrhoids, thrombosed haemorrhoid, **fissure** (gently evert the anal margin — usually posterior midline), **abscess** (red, swollen, tender), **external fistula openings**, ulcers, warts, scars, prolapse.',
        '**Ask the patient to strain**: prolapsing haemorrhoids, rectal prolapse, perineal descent.',
        '**Palpate** the perianal skin: tenderness, induration (fistula track), fluctuance.',
        '**DRE** (if not too painful — with a fissure, defer or use topical anaesthetic): lubricated index finger, pulp on the anal verge, gentle steady pressure, enter in the direction of the umbilicus.',
        '**Tone and squeeze**: resting tone (spasm with fissure; laxity), ask the patient to squeeze.',
        '**Palpate around the rectum**: masses (distance from the anal verge, % circumference), tenderness (abscess, pelvic peritonitis), internal fistula opening (induration at the dentate line), prostate or cervix anteriorly.',
        '**Withdraw and inspect the glove**: stool colour, fresh blood, melaena, mucus, pus.',
        '**Proctoscopy** (after DRE): anal canal and lower rectum — internal haemorrhoids (ask to strain), fissure, internal opening, proctitis.',
        '**Clean the patient**, allow them to dress, explain the findings; document with the clock face (lithotomy).',
      ],
      note: 'If pain prevents examination, examination under anaesthesia (EUA) is appropriate — do not force it.',
      source: 'Macleod’s 14e · Ch 6 · pp 111–113 (Figs 6.22–6.24, Box 6.15)',
    },
    {
      id: 'fissure',
      title: 'Anal fissure',
      items: [
        '**A linear tear in the anoderm below the dentate line**, from passing hard stool; internal sphincter spasm reduces blood flow and stops healing (a vicious cycle).',
        '**Site**: posterior midline (~90%); anterior midline in ~10% of women (especially postpartum). **Off-midline, multiple or painless fissures** → Crohn’s, TB, HIV, syphilis, cancer.',
        '**Acute** (< 6 weeks) vs **chronic** (> 6 weeks): sentinel skin tag, hypertrophied anal papilla, visible internal sphincter fibres at the base.',
        '**Treatment**: stool softeners, fibre and fluids, sitz baths, topical anaesthetic; then **topical GTN 0.4%** (headaches) or **diltiazem 2%** for 6–8 weeks; **botulinum toxin** injection; **lateral internal sphincterotomy** for chronic fissures that fail (high cure rate; small risk of incontinence to flatus — avoid in women with obstetric injury).',
      ],
    },
    {
      id: 'abscess',
      title: 'Anorectal abscess and fistula-in-ano',
      items: [
        '**Cryptoglandular origin**: infection of an anal gland at the dentate line spreads into the spaces around the sphincters.',
        '**Types**: perianal (commonest — tender swelling at the verge), ischiorectal (large, buttock, more systemic), intersphincteric (deep pain, little to see, tender on DRE), supralevator (rare, pelvic pain).',
        '**Treatment of an abscess**: **incision and drainage** promptly (cruciate or elliptical incision close to the anal verge, break loculi, leave open/packed); antibiotics only as an adjunct for cellulitis, diabetes, immunosuppression or systemic sepsis. Check glucose. Look for an associated fistula at EUA (do not probe aggressively).',
        '**Fistula-in-ano** develops after ~30–50% of abscesses: an abnormal track between the anal canal and perianal skin — persistent discharge, recurrent abscesses, itching.',
        '**Parks classification**: intersphincteric (~45%), trans-sphincteric (~30%), suprasphincteric (~20%), extrasphincteric (~5%).',
        '**Goodsall’s rule**: with the patient in lithotomy and a transverse line across the anus, external openings **posterior** to the line follow a curved track to an internal opening in the **posterior midline**; **anterior** openings run radially straight to the nearest crypt (anterior openings > 3 cm from the verge may behave like posterior ones).',
        '**Investigation**: EUA, **MRI pelvis** for complex/recurrent fistulae; endoanal ultrasound.',
        '**Treatment**: **fistulotomy** (lay open) for low fistulae with little sphincter involved; **seton** (draining or cutting) for high fistulae; sphincter-saving options — LIFT procedure, advancement flap, fistula plug/glue. Crohn’s fistulae: setons + biologics.',
      ],
    },
    {
      id: 'haemorrhoids',
      title: 'Haemorrhoids',
      table: {
        head: ['Goligher grade', 'Description', 'Treatment'],
        rows: [
          ['I', 'Bleed, do not prolapse', 'Diet (fibre, fluids), avoid straining; rubber band ligation if persistent'],
          ['II', 'Prolapse on straining, reduce spontaneously', 'Rubber band ligation (or injection sclerotherapy)'],
          ['III', 'Prolapse, need manual reduction', 'Banding; HAL/RAR (Doppler-guided ligation) or haemorrhoidectomy'],
          ['IV', 'Permanently prolapsed, irreducible', 'Haemorrhoidectomy (Milligan–Morgan open or Ferguson closed); stapled haemorrhoidopexy'],
        ],
      },
      items: [
        '**Internal haemorrhoids** are painless (above the dentate line) — bright red bleeding on the paper/pan, prolapse, mucus, itch. They hurt only when **thrombosed/strangulated** (prolapsed, irreducible, oedematous): analgesia, ice packs, stool softeners, bed rest; emergency haemorrhoidectomy is sometimes needed.',
        '**Thrombosed external haemorrhoid (perianal haematoma)**: sudden painful tense purple lump at the verge. Within ~72 h: excision under local anaesthetic gives fastest relief; later: conservative (it resolves over 1–2 weeks).',
        '**Always** examine to exclude a rectal cancer in rectal bleeding: proctoscopy and sigmoidoscopy; colonoscopy if age, change in bowel habit, anaemia or family history.',
        '**Haemorrhoidectomy complications**: pain, bleeding (reactive/secondary), urinary retention, anal stenosis, incontinence.',
      ],
    },
    {
      id: 'other',
      title: 'Other conditions',
      items: [
        '**Pilonidal sinus/abscess**: hair penetrating the skin of the natal cleft (midline pits); young hirsute men, sedentary jobs. Abscess → incision and drainage **off the midline**; definitive surgery for chronic sinus — Bascom, Karydakis or Limberg flap (off-midline closure heals better), hair removal.',
        '**Anal cancer**: squamous cell carcinoma; HPV (16/18), HIV, smoking, immunosuppression, anoreceptive intercourse; bleeding, pain, mass, non-healing ulcer, inguinal nodes. Biopsy at EUA; treatment is **chemoradiotherapy (Nigro protocol: 5-FU + mitomycin)**; abdominoperineal resection for residual/recurrent disease.',
        '**Perianal Crohn’s**: oedematous skin tags, multiple/complex fistulae, abscesses, off-midline fissures, strictures; MRI, EUA with setons, biologics.',
        '**Fournier’s gangrene**: necrotising fasciitis of the perineum/genitalia (polymicrobial; diabetes, alcohol, immunosuppression): pain out of proportion, swelling, crepitus, skin necrosis, sepsis — resuscitation, broad-spectrum IV antibiotics, **urgent radical debridement**, often a diverting stoma.',
        '**Rectal prolapse**: full-thickness (concentric rings) vs mucosal (radial folds); elderly women; perineal (Delorme’s, Altemeier’s) or abdominal (rectopexy) repair.',
        '**Pruritus ani**, **perianal warts** (HPV), **herpes**, **syphilitic chancre** — consider STI screening.',
      ],
    },
  ],
  cases: ['perianal-abscess', 'anal-fissure', 'thrombosed-haemorrhoids'],
  qa: [
    { q: 'What are the causes of anal pain?', a: 'Anal fissure, perianal/ischiorectal abscess, thrombosed external haemorrhoid (perianal haematoma), prolapsed thrombosed internal haemorrhoids, fistula-in-ano (when blocked), pilonidal abscess, anal cancer, perianal Crohn’s, infections (herpes, syphilis), proctalgia fugax and levator ani syndrome, and Fournier’s gangrene.', k: ['anal pain differential'] },
    { q: 'How do you position a patient for a rectal examination?', a: 'Left lateral position: lying on the left side, buttocks at the edge of the couch, knees drawn up towards the chest and heels clear of the perineum. Cover the patient; good light; gloves; chaperone present.', k: ['left lateral', 'DRE position'] },
    { q: 'Describe the steps of a digital rectal examination.', a: 'Explain, consent, chaperone, left lateral position, gloves. Inspect the perianal area (tags, fissures, haemorrhoids, fistulae, abscess, warts) and ask the patient to strain. Lubricate, place the pulp of the index finger on the anal verge and enter gently. Assess resting tone and voluntary squeeze; palpate the whole circumference (masses, tenderness), the prostate or cervix; withdraw and inspect the glove (blood, melaena, mucus, stool colour). Clean the patient and explain the findings.', k: ['DRE', 'PR exam'] },
    { q: 'How do you describe the position of a perianal lesion?', a: 'Using a clock face with the patient in the lithotomy position: 12 o’clock anterior (towards the scrotum/vagina), 6 o’clock posterior (towards the coccyx). State the distance from the anal verge.', k: ['clock face', 'lithotomy'] },
    { q: 'What is an anal fissure and where does it occur?', a: 'A longitudinal tear in the sensitive anoderm of the lower anal canal (below the dentate line), usually from passing a hard stool. ~90% are in the posterior midline (poorest blood supply); ~10% anterior, mainly in women after childbirth. Fissures off the midline suggest Crohn’s, TB, HIV, syphilis or malignancy.' },
    { q: 'What are the features of a chronic anal fissure?', a: 'Present > 6 weeks, with a sentinel skin tag at the outer end, a hypertrophied anal papilla at the inner end, indurated edges and exposed transverse fibres of the internal sphincter in the base.', k: ['sentinel pile', 'sentinel tag'] },
    { q: 'How do you treat an anal fissure?', a: 'First: stool softeners, high-fibre diet and fluids, warm baths, topical anaesthetic (lidocaine). Then a chemical sphincterotomy for 6–8 weeks: topical GTN 0.4% (headache) or diltiazem 2% (better tolerated). Refractory: botulinum toxin injection, or lateral internal sphincterotomy (most effective; small risk of incontinence).', k: ['GTN', 'diltiazem', 'sphincterotomy'] },
    { q: 'Why is a fissure so painful and slow to heal?', a: 'It lies in the somatically innervated anoderm below the dentate line. Pain causes spasm of the internal sphincter, which raises resting pressure and reduces blood flow to the posterior midline, preventing healing — the rationale for relaxing the sphincter (GTN, diltiazem, botox, sphincterotomy).' },
    { q: 'What are the types of anorectal abscess?', a: 'Perianal (commonest, at the anal verge), ischiorectal (in the ischioanal fossa — large, buttock swelling, systemically unwell), intersphincteric (between the sphincters — deep rectal pain, few external signs, tender on DRE), supralevator (above levator ani — rare, pelvic pain).' },
    { q: 'How do you manage a perianal abscess?', a: 'Prompt incision and drainage (under GA or local), with an incision close to the anal verge, breaking down loculi and leaving the cavity open/packed; send pus for culture. Antibiotics are not a substitute — only as an adjunct for cellulitis, diabetes, immunosuppression or sepsis. Check blood glucose; follow up for a fistula.', k: ['incision and drainage', 'I&D'] },
    { q: 'What is a fistula-in-ano?', a: 'An abnormal epithelialised track connecting the anal canal (an anal gland/crypt at the dentate line) to the perianal skin, usually following an anorectal abscess. Presents with persistent or intermittent discharge, recurrent abscesses and irritation. Associated with Crohn’s, TB, HIV, malignancy and radiotherapy.' },
    { q: 'What is Goodsall’s rule?', a: 'With the patient in lithotomy and a transverse line drawn through the anus: an external opening posterior to the line usually has a curved track to an internal opening in the posterior midline; an external opening anterior to the line usually has a short, straight radial track to the nearest crypt. Exception: anterior openings more than 3 cm from the verge may track to the posterior midline.', k: ['Goodsall'] },
    { q: 'What is the Parks classification of fistula-in-ano?', a: 'Based on the relationship to the sphincters: intersphincteric (~45%), trans-sphincteric (~30%), suprasphincteric (~20%) and extrasphincteric (~5%). Superficial fistulae (not involving the sphincters) are sometimes added.', k: ['Parks'] },
    { q: 'How is a fistula-in-ano treated?', a: 'EUA ± MRI to define the anatomy. Low fistulae (little sphincter): fistulotomy (laying open). High/complex fistulae: a draining seton to control sepsis, then sphincter-preserving procedures — LIFT (ligation of the intersphincteric fistula tract), endorectal advancement flap, plug or glue — or a cutting seton. Crohn’s fistulae: setons plus biologics.', k: ['seton', 'fistulotomy', 'LIFT'] },
    { q: 'What is the Goligher classification of haemorrhoids?', a: 'Grade I: bleed but do not prolapse. II: prolapse on straining, reduce spontaneously. III: prolapse and need manual reduction. IV: permanently prolapsed and irreducible.', k: ['haemorrhoid grading', 'piles'] },
    { q: 'Where are internal haemorrhoids found?', a: 'At the three primary vascular cushions: left lateral, right anterior and right posterior — 3, 7 and 11 o’clock with the patient in lithotomy.' },
    { q: 'Why are internal haemorrhoids painless?', a: 'They arise above the dentate line, where the mucosa has visceral (autonomic) innervation insensitive to pain. They cause painless bright red bleeding and prolapse — pain means thrombosis, strangulation or another diagnosis (fissure, abscess).' },
    { q: 'How do you treat haemorrhoids?', a: 'All: high-fibre diet, fluids, avoid straining, topical preparations for symptoms. Grade I–II (and some III): rubber band ligation (or injection sclerotherapy). Grade III: banding, haemorrhoidal artery ligation (HAL/RAR). Grade IV or failed treatment: haemorrhoidectomy (Milligan–Morgan/Ferguson) or stapled haemorrhoidopexy.', k: ['banding', 'haemorrhoidectomy'] },
    { q: 'How do you manage a thrombosed external haemorrhoid?', a: 'If seen within about 72 hours of onset with severe pain: excision of the thrombosed haemorrhoid under local anaesthetic (faster relief, fewer recurrences). After 72 hours: conservative — analgesia, stool softeners, sitz baths, topical treatments; it resolves over 1–2 weeks.', k: ['perianal haematoma'] },
    { q: 'What are the complications of haemorrhoidectomy?', a: 'Pain, urinary retention, bleeding (reactive within 24 h, secondary at 7–10 days from infection), infection, anal stenosis, faecal incontinence, recurrence.' },
    { q: 'What is a pilonidal sinus?', a: 'A sinus in the natal cleft caused by hairs penetrating the skin (midline pits), with recurrent abscesses and discharge — typically young, hairy men. Abscess: incision and drainage off the midline. Chronic: excision with off-midline closure (Bascom, Karydakis, Limberg flap), hair removal and hygiene.', k: ['pilonidal'] },
    { q: 'What is Fournier’s gangrene?', a: 'Necrotising fasciitis of the perineum, scrotum or perianal region, polymicrobial, often in diabetic, alcoholic or immunosuppressed patients, sometimes from a perianal abscess. Severe pain out of proportion, swelling, crepitus, skin discoloration/necrosis and rapid sepsis. A surgical emergency: resuscitation, broad-spectrum antibiotics and urgent radical debridement (repeated), often a defunctioning stoma.', k: ['necrotising fasciitis'] },
    { q: 'What are the features and treatment of anal cancer?', a: 'Usually squamous cell carcinoma associated with HPV 16/18, HIV, smoking, immunosuppression and anoreceptive intercourse. Bleeding, pain, a mass or non-healing ulcer, pruritus, inguinal lymphadenopathy. Biopsy at EUA, MRI and CT staging. First-line treatment is chemoradiotherapy (Nigro: 5-FU + mitomycin C); abdominoperineal resection for residual/recurrent disease.', k: ['Nigro'] },
    { q: 'What is proctoscopy and what does it show?', a: 'Inspection of the anal canal and lower rectum with a lubricated proctoscope (after DRE), in the left lateral position, directed towards the umbilicus; the obturator is removed and the mucosa inspected while withdrawing, with the patient straining. Shows internal haemorrhoids, fissures, internal fistula openings, proctitis, polyps and prolapse.', k: ['proctoscope'] },
  ],
}

export default t
