import { baseRules, before, COMM_ACTIONS, completionSteps, prepSteps, step } from './builders'
import type { StationAction, StationDef } from './types'

const A: StationAction[] = [
  ...COMM_ACTIONS,
  { id: 'lump.inspect', label: 'Inspect: site, shape, colour, surrounding skin, punctum, scars', short: 'Inspect', view: 'lump', group: 'Look', contact: false },
  { id: 'lump.measure', label: 'Measure the lump with a tape measure', short: 'Measure', view: 'lump', group: 'Look', contact: true, cue: 'measure' },
  { id: 'lump.temp', label: 'Feel the temperature with the back of your hand', short: 'Temperature', view: 'lump', group: 'Feel', contact: true },
  { id: 'lump.tender', label: 'Gently palpate — tenderness? (watch the face)', short: 'Tenderness', view: 'lump', group: 'Feel', contact: true, cue: 'press' },
  { id: 'lump.surface', label: 'Palpate the shape, surface and edge', short: 'Surface & edge', view: 'lump', group: 'Feel', contact: true, cue: 'press' },
  { id: 'lump.consistency', label: 'Assess consistency (soft, firm, rubbery, hard)', short: 'Consistency', view: 'lump', group: 'Feel', contact: true, cue: 'press' },
  { id: 'lump.fluctuation', label: 'Test for fluctuation (two-finger test)', short: 'Fluctuation', view: 'lump', group: 'Feel', contact: true, cue: 'press' },
  { id: 'lump.skin', label: 'Is it attached to the skin? (move the skin over it)', short: 'Skin fixity', view: 'lump', group: 'Feel', contact: true },
  { id: 'lump.deep', label: 'Mobility over deep structures (tense the underlying muscle)', short: 'Deep fixity', view: 'lump', group: 'Feel', contact: true },
  { id: 'lump.pulsation', label: 'Pulsatile? Expansile or transmitted?', short: 'Pulsatility', view: 'lump', group: 'Feel', contact: true },
  { id: 'lump.compress', label: 'Compressible or reducible? Cough impulse?', short: 'Compressible?', view: 'lump', group: 'Feel', contact: true, cue: 'press' },
  { id: 'lump.slip', label: 'Slip sign: does the edge slip away under your finger?', short: 'Slip sign', view: 'lump', group: 'Feel', contact: true, cue: 'press' },
  { id: 'lump.transilluminate', label: 'Transilluminate with a pen torch', short: 'Transilluminate', view: 'lump', group: 'Special', contact: true, cue: 'transilluminate' },
  { id: 'lump.auscultate', label: 'Auscultate for a bruit', short: 'Auscultate', view: 'lump', group: 'Special', contact: true },
  { id: 'lump.nodes', label: 'Examine the regional lymph nodes', short: 'Lymph nodes', view: 'lump', group: 'Special', contact: true },
  { id: 'lump.distal', label: 'Check distal neurovascular status', short: 'Neurovascular', view: 'lump', group: 'Special', contact: true },
  { id: 'complete.skin', label: 'State: examine the rest of the skin for similar lumps', short: 'Other lumps', view: 'any', group: 'Completion', contact: false },
]

const contact = new Set(A.filter((a) => a.contact).map((a) => a.id))

export const LUMP: StationDef = {
  kind: 'lump',
  title: 'Examination of a lump',
  task: 'Examine this lump',
  consentText: 'You explain that you would like to look at and feel the lump, and that you will be gentle.',
  positionText: 'You position the patient comfortably so the lump is well lit and accessible.',
  exposeText: 'You expose the lump and the corresponding area on the other side for comparison.',
  exposure: 'gowned',
  views: [{ id: 'lump', label: 'The lump' }],
  actions: A,
  steps: [
    ...prepSteps({ chaperone: 'normal', position: 'Position so the lump is comfortably accessible', expose: 'Expose the lump and the opposite side for comparison' }),
    step('lk.inspect', 'Inspection', 'Inspect the lump and surrounding skin', 1, ['lump.inspect'], 'Site, shape, colour and overlying skin (punctum, erythema, ulceration, scars) often give the diagnosis before you touch.'),
    step('lk.measure', 'Inspection', 'Measure it', 1, ['lump.measure'], 'Measure in two dimensions with a tape — “about the size of a grape” is not a clinical measurement.'),
    step('fl.temp', 'Palpation', 'Temperature', 1, ['lump.temp'], 'A warm lump suggests inflammation or high vascularity (abscess, vascular tumour).'),
    step('fl.tender', 'Palpation', 'Tenderness', 1, ['lump.tender'], 'Tenderness implies inflammation or infection.'),
    step('fl.surface', 'Palpation', 'Shape, surface and edge', 1, ['lump.surface'], 'Smooth, well-defined edges suggest a benign lesion; irregular, ill-defined edges raise concern.'),
    step('fl.consistency', 'Palpation', 'Consistency', 1, ['lump.consistency'], 'Soft (lipoma), firm (cyst, fibroma), rubbery (lymphoma), hard (carcinoma, calcified).'),
    step('fl.fluctuation', 'Palpation', 'Fluctuation', 1, ['lump.fluctuation'], 'Fluctuation indicates fluid (cyst, abscess) — test in two planes at right angles.'),
    step('fl.fixity', 'Palpation', 'Attachment to skin and deep structures', 2, (x) => (['lump.skin', 'lump.deep'].filter((a) => x.log.some((e) => e.action === a)).length / 2), 'Epidermoid cysts are tethered to the skin (punctum); malignant lumps may be fixed deeply. Tense the underlying muscle to test deep fixity.', { action: 'lump.skin' }),
    step('fl.pulsation', 'Palpation', 'Pulsatility', 1, ['lump.pulsation'], 'An expansile pulsation means an aneurysm — do not needle it!'),
    step('fl.compress', 'Palpation', 'Compressibility / reducibility', 0.5, ['lump.compress'], 'Compressible: vascular malformation, haemangioma. Reducible with cough impulse: hernia.'),
    step('sp.transilluminate', 'Special tests', 'Transillumination', 1, ['lump.transilluminate'], 'Clear fluid transilluminates (hydrocele, cystic hygroma, some cysts); solids and blood/pus do not.'),
    step('sp.auscultate', 'Special tests', 'Auscultate', 0.5, ['lump.auscultate'], 'A bruit suggests a vascular lesion (AV malformation, aneurysm, vascular tumour).'),
    step('sp.nodes', 'Special tests', 'Regional lymph nodes', 1, ['lump.nodes'], 'Infection and malignancy spread to the draining nodes.'),
    ...completionSteps([step('end.other', 'Completion', 'Look for similar lumps elsewhere', 0.5, ['complete.skin'], 'Multiple lipomas (familial lipomatosis, Dercum’s), neurofibromas (NF1).')]),
  ],
  rules: [
    ...baseRules((a) => contact.has(a), () => false),
    before('lump.inspect', ['lump.tender', 'lump.surface', 'lump.consistency', 'lump.fluctuation'], 'Inspect before you palpate.'),
    before('comm.pain', 'lump.tender', 'Ask whether the lump is tender before pressing on it.'),
  ],
  normal: {
    'lump.inspect': { text: 'No abnormality seen.' },
    'lump.measure': { text: 'Nothing to measure.' },
    'lump.temp': { text: 'Normal temperature.' },
    'lump.tender': { text: 'Non-tender.' },
    'lump.surface': { text: 'Smooth, well-defined.' },
    'lump.consistency': { text: 'Soft.' },
    'lump.fluctuation': { text: 'Not fluctuant.' },
    'lump.skin': { text: 'The skin moves freely over it.' },
    'lump.deep': { text: 'Mobile over the deep structures.' },
    'lump.pulsation': { text: 'Not pulsatile.' },
    'lump.compress': { text: 'Not compressible or reducible; no cough impulse.' },
    'lump.slip': { text: 'Negative slip sign.' },
    'lump.transilluminate': { text: 'Does not transilluminate.' },
    'lump.auscultate': { text: 'No bruit.' },
    'lump.nodes': { text: 'No regional lymphadenopathy.' },
    'lump.distal': { text: 'Distal pulses, sensation and power are normal.' },
    'complete.skin': { text: 'No other lumps on the skin.' },
  },
}
