import { baseRules, before, COMM_ACTIONS, completionSteps, prepSteps, step } from './builders'
import type { StationAction, StationDef } from './types'

const A: StationAction[] = [
  ...COMM_ACTIONS,
  { id: 'thy.general', label: 'General inspection: demeanour, weight, dress, sweating', short: 'General', view: 'neck', group: 'General', contact: false },
  { id: 'thy.hands', label: 'Inspect the hands: sweating, palmar erythema, acropachy, onycholysis', short: 'Hands', view: 'hands', group: 'Hands', contact: true },
  { id: 'thy.tremor', label: 'Fine tremor: hands outstretched (paper on the backs of the hands)', short: 'Tremor', view: 'hands', group: 'Hands', contact: false, cue: 'tremor' },
  { id: 'thy.pulse', label: 'Radial pulse — rate and rhythm', short: 'Pulse', view: 'hands', group: 'Hands', contact: true },
  { id: 'thy.eyes', label: 'Inspect the eyes: exophthalmos (from the side and above), lid retraction, chemosis', short: 'Eyes', view: 'neck', group: 'Eyes', contact: false, cue: 'eyes' },
  { id: 'thy.lidlag', label: 'Lid lag: follow my finger down slowly', short: 'Lid lag', view: 'neck', group: 'Eyes', contact: false, cue: 'lid-lag' },
  { id: 'thy.eom', label: 'Eye movements (“H” test) — ask about double vision', short: 'Eye movements', view: 'neck', group: 'Eyes', contact: false },
  { id: 'thy.neckInspect', label: 'Inspect the neck from the front (swelling, scars, veins)', short: 'Inspect neck', view: 'neck', group: 'Neck', contact: false },
  { id: 'thy.swallow', label: 'Sip of water — hold — swallow (watch the lump)', short: 'Swallow', view: 'neck', group: 'Neck', contact: false, cue: 'swallow' },
  { id: 'thy.tongue', label: 'Stick your tongue out (watch the lump)', short: 'Tongue out', view: 'neck', group: 'Neck', contact: false, cue: 'tongue' },
  { id: 'thy.palpate', label: 'Palpate the thyroid from behind (with swallowing)', short: 'Palpate thyroid', view: 'neck', group: 'Neck', contact: true, cue: 'press', hotspot: (lm) => [0, lm.sternalNotch[1] - 14] },
  { id: 'thy.nodes', label: 'Palpate the cervical lymph nodes', short: 'Lymph nodes', view: 'neck', group: 'Neck', contact: true },
  { id: 'thy.trachea', label: 'Check the position of the trachea', short: 'Trachea', view: 'neck', group: 'Neck', contact: true },
  { id: 'thy.percuss', label: 'Percuss over the manubrium (retrosternal extension)', short: 'Percuss sternum', view: 'neck', group: 'Neck', contact: true },
  { id: 'thy.bruit', label: 'Auscultate the thyroid for a bruit', short: 'Bruit', view: 'neck', group: 'Neck', contact: true },
  { id: 'thy.pemberton', label: 'Pemberton’s sign: raise both arms above the head for 1 minute', short: 'Pemberton’s', view: 'neck', group: 'Neck', contact: false, cue: 'pemberton' },
  { id: 'thy.reflexes', label: 'Ankle reflexes (slow relaxation?)', short: 'Reflexes', view: 'neck', group: 'Thyroid status', contact: true },
  { id: 'thy.proximal', label: 'Proximal myopathy: stand from a chair with arms crossed', short: 'Proximal power', view: 'neck', group: 'Thyroid status', contact: false },
  { id: 'thy.shins', label: 'Inspect the shins (pretibial myxoedema)', short: 'Shins', view: 'neck', group: 'Thyroid status', contact: false },
]

const contact = new Set(A.filter((a) => a.contact).map((a) => a.id))

export const THYROID: StationDef = {
  kind: 'thyroid',
  title: 'Thyroid & neck examination',
  task: 'Examine this patient’s neck',
  consentText: 'You explain that you would like to examine the neck and look for signs of thyroid over- or under-activity, including the hands and eyes.',
  positionText: 'You sit the patient on a chair with space behind it, and put a glass of water within reach.',
  exposeText: 'You ask the patient to expose the neck down to the clavicles.',
  exposure: 'torso',
  views: [
    { id: 'neck', label: 'Face & neck', closeup: 'neck' },
    { id: 'hands', label: 'Hands', closeup: 'hands' },
  ],
  actions: A,
  steps: [
    ...prepSteps({ chaperone: 'normal', position: 'Sit the patient on a chair with room behind it', expose: 'Expose the neck down to the clavicles' }),
    step('gen.general', 'General inspection', 'General inspection', 1, ['thy.general'], 'Restless, sweaty and thin (thyrotoxic) or slow, dry and overweight (hypothyroid)?'),
    step('hands.hands', 'Hands', 'Inspect the hands', 1, ['thy.hands'], 'Warm sweaty palms, palmar erythema, thyroid acropachy (clubbing-like), onycholysis in hyperthyroidism.'),
    step('hands.tremor', 'Hands', 'Test for a fine tremor', 1, ['thy.tremor'], 'A fine postural tremor is a sign of thyrotoxicosis.'),
    step('hands.pulse', 'Hands', 'Pulse rate and rhythm', 1, ['thy.pulse'], 'Sinus tachycardia or AF (thyrotoxicosis); bradycardia (hypothyroidism).'),
    step('eyes.inspect', 'Eyes', 'Inspect the eyes', 1, ['thy.eyes'], 'Exophthalmos (sclera visible below the iris), proptosis (best seen from above), lid retraction (sclera above the iris), chemosis — Graves’ eye disease.'),
    step('eyes.lidlag', 'Eyes', 'Test for lid lag', 1, ['thy.lidlag'], 'The upper lid lags behind the globe on downgaze — sympathetic overactivity.'),
    step('eyes.eom', 'Eyes', 'Eye movements', 0.5, ['thy.eom'], 'Restricted movements and diplopia from extraocular muscle involvement (ophthalmoplegia).'),
    step('neck.inspect', 'Neck', 'Inspect the neck', 1, ['thy.neckInspect'], 'Look for a swelling, scars (collar incision), dilated veins (retrosternal goitre).'),
    step('neck.swallow', 'Neck', 'Swallow test', 2, ['thy.swallow'], 'The thyroid is invested in pretracheal fascia and moves up on swallowing.'),
    step('neck.tongue', 'Neck', 'Tongue protrusion test', 1, ['thy.tongue'], 'A thyroglossal cyst moves up with tongue protrusion (attached to the foramen caecum via the tract).'),
    step('neck.palpate', 'Neck', 'Palpate the thyroid from behind', 2, ['thy.palpate'], 'Size, shape (diffuse, multinodular, solitary nodule), consistency, tenderness, and whether it moves on swallowing.'),
    step('neck.nodes', 'Neck', 'Cervical lymph nodes', 1, ['thy.nodes'], 'Papillary carcinoma spreads to cervical nodes.'),
    step('neck.trachea', 'Neck', 'Tracheal position', 0.5, ['thy.trachea'], 'A large goitre can deviate the trachea.'),
    step('neck.percuss', 'Neck', 'Percuss for retrosternal extension', 0.5, ['thy.percuss'], 'Dullness over the manubrium suggests retrosternal extension.'),
    step('neck.bruit', 'Neck', 'Auscultate for a bruit', 1, ['thy.bruit'], 'A bruit over the gland indicates increased vascularity — Graves’ disease.'),
    step('neck.pemberton', 'Neck', 'Pemberton’s sign', 0.5, ['thy.pemberton'], 'Facial plethora and distended neck veins with arms raised: thoracic inlet obstruction by a retrosternal goitre.'),
    step('status.signs', 'Thyroid status', 'Assess thyroid status (reflexes, myopathy, shins)', 1, (x) => ['thy.reflexes', 'thy.proximal', 'thy.shins'].filter((a) => x.log.some((e) => e.action === a)).length / 2, 'Slow-relaxing reflexes (hypo), proximal myopathy (hyper), pretibial myxoedema (Graves’).', { action: 'thy.reflexes' }),
    ...completionSteps(),
  ],
  rules: [
    ...baseRules((a) => contact.has(a), () => false),
    before('thy.neckInspect', 'thy.palpate', 'Inspect the neck — including the swallow test — before you palpate.'),
  ],
  normal: {
    'thy.general': { text: 'The patient appears comfortable and calm, appropriately dressed, of normal build.' },
    'thy.hands': { text: 'Hands warm and dry. No palmar erythema, acropachy or onycholysis.' },
    'thy.tremor': { text: 'No tremor.' },
    'thy.pulse': { text: 'Pulse regular.' },
    'thy.eyes': { text: 'No exophthalmos, lid retraction or chemosis.' },
    'thy.lidlag': { text: 'No lid lag.' },
    'thy.eom': { text: 'Full eye movements without diplopia.' },
    'thy.neckInspect': { text: 'No visible neck swelling or scars.' },
    'thy.swallow': { text: 'Nothing moves abnormally on swallowing.' },
    'thy.tongue': { text: 'Nothing moves on tongue protrusion.' },
    'thy.palpate': { text: 'The thyroid is not palpably enlarged.' },
    'thy.nodes': { text: 'No cervical lymphadenopathy.' },
    'thy.trachea': { text: 'Trachea central.' },
    'thy.percuss': { text: 'Resonant over the manubrium.' },
    'thy.bruit': { text: 'No bruit.' },
    'thy.pemberton': { text: 'Pemberton’s sign negative.' },
    'thy.reflexes': { text: 'Ankle reflexes normal.' },
    'thy.proximal': { text: 'Stands from the chair without using the arms.' },
    'thy.shins': { text: 'No pretibial myxoedema.' },
  },
}
