import { baseRules, before, COMM_ACTIONS, completionSteps, prepSteps, step } from './builders'
import type { StationAction, StationDef } from './types'

/* ------------------------------ Peripheral arterial ------------------------------ */

const ART: StationAction[] = [
  ...COMM_ACTIONS,
  { id: 'art.general', label: 'General inspection (amputations, walking aids, cigarettes, oxygen)', short: 'General', view: 'bed', group: 'General', contact: false },
  { id: 'art.hands', label: 'Hands: tar staining, xanthomata, capillary refill', short: 'Hands', view: 'bed', group: 'General', contact: true },
  { id: 'art.radial', label: 'Radial pulse: rate, rhythm (AF?), radio-radial delay', short: 'Radial pulse', view: 'bed', group: 'General', contact: true },
  { id: 'art.aorta', label: 'Palpate the abdominal aorta (AAA?)', short: 'Aorta', view: 'bed', group: 'General', contact: true },
  { id: 'art.inspect', label: 'Inspect both legs: colour, hair, skin, muscle wasting, ulcers, gangrene, scars', short: 'Inspect legs', view: 'legs', group: 'Legs', contact: false },
  { id: 'art.toes', label: 'Inspect between the toes and the heels', short: 'Toes & heels', view: 'feet', group: 'Legs', contact: true },
  { id: 'art.temp', label: 'Compare temperature with the backs of your hands (both legs)', short: 'Temperature', view: 'legs', group: 'Legs', contact: true },
  { id: 'art.crt', label: 'Capillary refill in the toes', short: 'CRT (toes)', view: 'feet', group: 'Legs', contact: true },
  { id: 'art.femoral', label: 'Femoral pulses (mid-inguinal point)', short: 'Femoral', view: 'legs', group: 'Pulses', contact: true, intimate: false, hotspot: (lm) => lm.midInguinalR },
  { id: 'art.popliteal', label: 'Popliteal pulses (knee flexed 30°, both hands)', short: 'Popliteal', view: 'legs', group: 'Pulses', contact: true, hotspot: () => [-44, 548] },
  { id: 'art.pt', label: 'Posterior tibial pulses (behind the medial malleolus)', short: 'Posterior tibial', view: 'feet', group: 'Pulses', contact: true, hotspot: () => [-33, 730] },
  { id: 'art.dp', label: 'Dorsalis pedis pulses (lateral to extensor hallucis longus)', short: 'Dorsalis pedis', view: 'feet', group: 'Pulses', contact: true, hotspot: () => [-40, 770] },
  { id: 'art.bruit', label: 'Auscultate for femoral (and carotid) bruits', short: 'Bruits', view: 'legs', group: 'Pulses', contact: true },
  { id: 'art.buerger', label: 'Buerger’s test: elevate the legs, then hang them over the bed', short: 'Buerger’s test', view: 'buerger', group: 'Special tests', contact: true, cue: 'elevate' },
  { id: 'art.sensation', label: 'Sensation in the feet (neuropathy)', short: 'Sensation', view: 'feet', group: 'Special tests', contact: true },
  { id: 'complete.abpi', label: 'State: measure the ankle–brachial pressure index (handheld Doppler)', short: 'ABPI', view: 'any', group: 'Completion', contact: false, cue: 'doppler' },
  { id: 'complete.cvs', label: 'State: full cardiovascular examination', short: 'CVS exam', view: 'any', group: 'Completion', contact: false },
]

const artContact = new Set(ART.filter((a) => a.contact).map((a) => a.id))

export const ARTERIAL: StationDef = {
  kind: 'arterial',
  title: 'Peripheral arterial examination',
  task: 'Examine this patient’s lower limb arterial system',
  consentText: 'You explain that you would like to examine the circulation in the legs, including feeling pulses in the groins, and ask if that is okay.',
  positionText: 'You lie the patient flat on the couch with the head on one pillow.',
  exposeText: 'You expose both legs from the groins to the toes, keeping the underwear on.',
  exposure: 'legs',
  views: [
    { id: 'bed', label: 'Bedside', shot: { cx: 0, cy: 330, w: 420, h: 720 } },
    { id: 'legs', label: 'Legs', shot: { cx: 0, cy: 590, w: 300, h: 460 } },
    { id: 'feet', label: 'Feet', shot: { cx: 0, cy: 752, w: 190, h: 150 } },
    { id: 'buerger', label: 'Buerger’s', closeup: 'buerger' },
  ],
  actions: ART,
  steps: [
    ...prepSteps({ chaperone: 'normal', position: 'Lie the patient flat', expose: 'Expose both legs from the groins to the toes (underwear on)' }),
    step('gen.general', 'General inspection', 'General inspection', 1, ['art.general'], 'Look for amputations, walking aids, cigarettes, nicotine-stained fingers and oxygen.'),
    step('gen.hands', 'General inspection', 'Hands', 0.5, ['art.hands'], 'Tar staining (smoking), xanthomata (hyperlipidaemia), peripheral perfusion.'),
    step('gen.radial', 'General inspection', 'Radial pulse', 1, ['art.radial'], 'AF is a source of emboli; radio-radial delay suggests subclavian stenosis.'),
    step('gen.aorta', 'General inspection', 'Palpate the aorta', 1, ['art.aorta'], 'AAA coexists with peripheral arterial disease.'),
    step('lg.inspect', 'Legs', 'Inspect both legs', 2, ['art.inspect'], 'Pallor, cyanosis or dependent rubor; hair loss, shiny thin skin, muscle wasting, ulcers, gangrene, scars (bypass or harvest), amputations.'),
    step('lg.toes', 'Legs', 'Inspect between the toes and the heels', 1, ['art.toes'], 'Ulcers hide between the toes and on the heels — always look.'),
    step('lg.temp', 'Legs', 'Temperature gradient', 1, ['art.temp'], 'A cold leg (or a sharp temperature change) localises the level of arterial disease.'),
    step('lg.crt', 'Legs', 'Capillary refill in the toes', 0.5, ['art.crt'], 'CRT > 2 s indicates poor perfusion.'),
    step('pu.femoral', 'Pulses', 'Femoral pulses', 1, ['art.femoral'], 'At the mid-inguinal point (halfway between ASIS and pubic symphysis). Compare both sides.'),
    step('pu.popliteal', 'Pulses', 'Popliteal pulses', 1, ['art.popliteal'], 'Knee slightly flexed, fingertips of both hands pressing into the popliteal fossa. An easily felt popliteal pulse suggests an aneurysm.'),
    step('pu.pt', 'Pulses', 'Posterior tibial pulses', 1, ['art.pt'], 'Midway between the medial malleolus and the Achilles tendon.'),
    step('pu.dp', 'Pulses', 'Dorsalis pedis pulses', 1, ['art.dp'], 'Lateral to the extensor hallucis longus tendon on the dorsum of the foot (absent in ~10% of normal people).'),
    step('pu.bruit', 'Pulses', 'Auscultate for bruits', 0.5, ['art.bruit'], 'A femoral bruit indicates turbulent flow from stenosis.'),
    step('sp.buerger', 'Special tests', 'Buerger’s test', 2, ['art.buerger'], 'Elevate the legs: pallor at < 20° (Buerger’s angle) indicates severe ischaemia. Then hang them over the side: reactive hyperaemia (“sunset foot”) confirms it.'),
    step('sp.sensation', 'Special tests', 'Sensation', 0.5, ['art.sensation'], 'Diabetic neuropathy coexists with, and worsens, ischaemic ulceration.'),
    ...completionSteps([
      step('end.abpi', 'Completion', 'ABPI with a handheld Doppler', 1, ['complete.abpi'], 'ABPI < 0.9 = PAD; < 0.5 = severe (critical ischaemia likely); > 1.3 = incompressible calcified vessels (diabetes).'),
      step('end.cvs', 'Completion', 'Offer a cardiovascular examination', 0.5, ['complete.cvs'], 'Atherosclerosis is systemic — heart, carotids and aorta.'),
    ]),
  ],
  rules: [...baseRules((a) => artContact.has(a), () => false), before('art.inspect', ['art.femoral', 'art.popliteal', 'art.pt', 'art.dp'], 'Inspect the legs before palpating the pulses.')],
  normal: {
    'art.general': { text: 'Comfortable at rest; no walking aids, oxygen or amputations.' },
    'art.hands': { text: 'No tar staining or xanthomata; capillary refill < 2 s.' },
    'art.radial': { text: 'Radial pulse regular, no radio-radial delay.' },
    'art.aorta': { text: 'Aorta not expansile.' },
    'art.inspect': { text: 'Both legs are pink with normal hair distribution, no ulcers, gangrene or scars.' },
    'art.toes': { text: 'No ulcers between the toes or on the heels.' },
    'art.temp': { text: 'Both legs are warm, with no temperature gradient.' },
    'art.crt': { text: 'Capillary refill < 2 s in the toes.' },
    'art.femoral': { text: 'Femoral pulses palpable and equal.' },
    'art.popliteal': { text: 'Popliteal pulses palpable.' },
    'art.pt': { text: 'Posterior tibial pulses palpable.' },
    'art.dp': { text: 'Dorsalis pedis pulses palpable.' },
    'art.bruit': { text: 'No femoral bruits.' },
    'art.buerger': { text: 'Buerger’s test negative: the feet stay pink at 90°.' },
    'art.sensation': { text: 'Normal light-touch sensation.' },
    'complete.abpi': { text: 'ABPI 1.05 right, 1.02 left.', media: 'doppler:triphasic' },
    'complete.cvs': { text: 'Heart sounds normal; no carotid bruits.' },
  },
}

/* ------------------------------ Varicose veins ------------------------------ */

const VEN: StationAction[] = [
  ...COMM_ACTIONS,
  { id: 'ven.stand', label: 'Ask the patient to stand', short: 'Stand up', view: 'standing', group: 'Standing', contact: false, cue: 'stand' },
  { id: 'ven.inspect', label: 'Inspect from the front: varicosities, skin changes, ulcers, oedema, scars', short: 'Inspect front', view: 'standing', group: 'Standing', contact: false },
  { id: 'ven.back', label: 'Inspect from behind (short saphenous territory)', short: 'Inspect back', view: 'standing', group: 'Standing', contact: false, cue: 'turn' },
  { id: 'ven.palpate', label: 'Palpate the varicosities: tenderness, warmth, hardness (thrombophlebitis)', short: 'Palpate veins', view: 'standing', group: 'Standing', contact: true },
  { id: 'ven.oedema', label: 'Check for pitting oedema', short: 'Oedema', view: 'standing', group: 'Standing', contact: true },
  { id: 'ven.sfj', label: 'Palpate the saphenofemoral junction (saphena varix?)', short: 'SFJ', view: 'standing', group: 'Standing', contact: true, hotspot: (lm) => [lm.pubicTubercleR[0] - 14, lm.pubicTubercleR[1] + 12] },
  { id: 'ven.cough', label: 'Cough impulse at the SFJ', short: 'Cough impulse', view: 'standing', group: 'Standing', contact: true, cue: 'cough' },
  { id: 'ven.tap', label: 'Tap test (percuss the vein, feel the impulse proximally)', short: 'Tap test', view: 'standing', group: 'Standing', contact: true },
  { id: 'ven.doppler', label: 'Handheld Doppler at the SFJ (reflux > 0.5 s after calf squeeze?)', short: 'Doppler', view: 'standing', group: 'Special tests', contact: true, cue: 'doppler' },
  { id: 'ven.tourniquet', label: 'Tourniquet (Trendelenburg) test', short: 'Tourniquet test', view: 'lying', group: 'Special tests', contact: true, cue: 'tourniquet' },
  { id: 'ven.pulses', label: 'Check the foot pulses (arterial supply before compression)', short: 'Foot pulses', view: 'lying', group: 'Special tests', contact: true },
  { id: 'complete.duplex', label: 'State: venous duplex ultrasound', short: 'Duplex', view: 'any', group: 'Completion', contact: false },
  { id: 'complete.abpi', label: 'State: ABPI before any compression', short: 'ABPI', view: 'any', group: 'Completion', contact: false },
  { id: 'complete.abdomen', label: 'State: abdominal (and pelvic) examination for secondary causes', short: 'Abdomen', view: 'any', group: 'Completion', contact: false },
]

const venContact = new Set(VEN.filter((a) => a.contact).map((a) => a.id))

export const VENOUS: StationDef = {
  kind: 'venous',
  title: 'Varicose vein examination',
  task: 'Examine this patient’s legs (varicose veins)',
  consentText: 'You explain that you would like to examine the veins in both legs, first standing then lying.',
  positionText: 'You ask the patient to stand on a step, facing you, so the veins fill.',
  exposeText: 'You expose both legs from the groins to the feet, keeping the underwear on.',
  exposure: 'legs',
  views: [
    { id: 'standing', label: 'Standing', shot: { cx: 0, cy: 600, w: 320, h: 520 } },
    { id: 'lying', label: 'Lying', shot: { cx: 0, cy: 600, w: 320, h: 500 } },
  ],
  actions: VEN,
  steps: [
    ...prepSteps({ chaperone: 'normal', position: 'Examine standing (veins fill)', expose: 'Expose both legs from the groins to the feet (underwear on)' }),
    step('st.stand', 'Standing', 'Examine standing', 1, ['ven.stand'], 'Varicose veins fill and become visible on standing.'),
    step('st.inspect', 'Standing', 'Inspect from the front', 2, ['ven.inspect'], 'Distribution (GSV medially, SSV posterior calf), skin changes of chronic venous insufficiency (haemosiderin, eczema, lipodermatosclerosis, atrophie blanche), ulcers at the gaiter area, oedema, scars.'),
    step('st.back', 'Standing', 'Inspect from behind', 1, ['ven.back'], 'Short saphenous varicosities lie on the back of the calf.'),
    step('st.palpate', 'Standing', 'Palpate the veins', 0.5, ['ven.palpate'], 'Hard, tender, red veins = superficial thrombophlebitis.'),
    step('st.oedema', 'Standing', 'Pitting oedema', 0.5, ['ven.oedema'], 'Oedema accompanies chronic venous insufficiency (C3).'),
    step('st.sfj', 'Standing', 'Palpate the saphenofemoral junction', 1, ['ven.sfj'], '2–4 cm below and lateral to the pubic tubercle. A soft swelling that disappears lying down with a cough thrill = saphena varix.'),
    step('st.cough', 'Standing', 'Cough impulse at the SFJ', 1, ['ven.cough'], 'A palpable thrill on coughing suggests SFJ incompetence.'),
    step('st.tap', 'Standing', 'Tap test', 0.5, ['ven.tap'], 'An impulse transmitted proximally implies incompetent valves between the two points.'),
    step('sp.doppler', 'Special tests', 'Handheld Doppler', 1, ['ven.doppler'], 'Reflux lasting > 0.5 s after calf compression at the SFJ confirms incompetence. Duplex has replaced the tourniquet test in practice.'),
    step('sp.tourniquet', 'Special tests', 'Tourniquet (Trendelenburg) test', 1, ['ven.tourniquet'], 'Elevate the leg to empty the veins, apply a tourniquet just below the SFJ, stand up: if the veins stay empty, the SFJ is the site of incompetence.'),
    step('sp.pulses', 'Special tests', 'Check arterial pulses', 1, ['ven.pulses'], 'Arterial disease must be excluded before compression therapy.'),
    ...completionSteps([
      step('end.duplex', 'Completion', 'Venous duplex scan', 1, ['complete.duplex'], 'NICE CG168: refer symptomatic varicose veins for duplex ultrasound to map reflux and plan treatment.'),
      step('end.abpi', 'Completion', 'ABPI before compression', 1, ['complete.abpi'], 'ABPI < 0.8: compression is contraindicated or must be modified.'),
      step('end.abdomen', 'Completion', 'Look for secondary causes', 0.5, ['complete.abdomen'], 'Pelvic masses, pregnancy, previous DVT.'),
    ]),
  ],
  rules: [...baseRules((a) => venContact.has(a), () => false), before('ven.stand', 'ven.inspect', 'Inspect with the patient standing — veins collapse when lying.', 0.5)],
  normal: {
    'ven.stand': { text: 'The patient stands.' },
    'ven.inspect': { text: 'No visible varicosities, skin changes, ulcers or oedema.' },
    'ven.back': { text: 'No varicosities on the back of the calves.' },
    'ven.palpate': { text: 'No tender or hard veins.' },
    'ven.oedema': { text: 'No pitting oedema.' },
    'ven.sfj': { text: 'No saphena varix.' },
    'ven.cough': { text: 'No cough impulse at the SFJ.' },
    'ven.tap': { text: 'No transmitted impulse.' },
    'ven.doppler': { text: 'No reflux at the SFJ.', media: 'doppler:venous-normal' },
    'ven.tourniquet': { text: 'The veins do not refill.' },
    'ven.pulses': { text: 'Foot pulses palpable.' },
    'complete.duplex': { text: 'Duplex requested.' },
    'complete.abpi': { text: 'ABPI 1.0 bilaterally.' },
    'complete.abdomen': { text: 'Abdomen and pelvis normal.' },
  },
}
