import type { CaseDef } from '../../engine/types'
import { FBC } from './helpers'

const c: CaseDef = {
  id: 'anal-fissure',
  title: 'Acute posterior anal fissure',
  presenting: 'Tearing pain on opening the bowels, with bright red blood',
  specialty: 'Colorectal',
  exam: 'perianal',
  difficulty: 1,
  setting: 'GP surgery',
  stem: 'GP surgery. Emily Clarke, 28, has severe pain when she opens her bowels. Take a history, examine her perianal area with a chaperone and agree a management plan.',
  components: ['history', 'exam', 'diagnosis', 'viva'],
  tags: ['perianal pain', 'rectal bleeding', 'fissure', 'constipation'],
  patient: {
    name: 'Emily Clarke',
    title: 'Ms Clarke',
    age: 28,
    sex: 'female',
    dob: '12/10/1997',
    occupation: 'a nurse',
    appearance: { sex: 'female', age: 28, skinTone: 1, habitus: 'average', hair: 'bun', hairColor: 'blonde', eyeColor: 'blue' },
    persona: { mood: 'anxious', style: 'normal' },
  },
  vitals: { hr: 80, rhythm: 'regular', sbp: 116, dbp: 72, rr: 14, spo2: 99, temp: 36.7, avpu: 'A', pain: 3 },
  visual: { perianal: { kind: 'fissure', clock: 6, spasm: true } },
  history: {
    opening: 'Going to the toilet is agony — like passing broken glass — and then it throbs for an hour afterwards.',
    answers: {
      'ano.pain': { text: 'Sharp, tearing pain as it comes out, then a deep throbbing ache for an hour or two. I’m scared to go.', cue: 'winces at the memory' },
      'pain.onset': 'About four weeks ago, after a really hard, painful stool.',
      'pain.severity': 'Nine when I go; three or four in between.',
      'ano.blood_type': 'Bright red, on the paper when I wipe — a few streaks. Not mixed in.',
      'gi.stool_blood': 'Just streaks on the paper.',
      'ano.lump': 'No lump.',
      'ano.discharge': 'No.',
      'ano.itch': 'A little itchy.',
      'ano.prolapse': 'Nothing comes down.',
      'gi.constipation': 'I’ve been constipated since starting night shifts — and I hold on because it hurts.',
      'gi.bowel_change': 'Only the constipation. No diarrhoea.',
      'gi.weight': 'No weight loss.',
      'gi.mucus': 'No.',
      'sys.fever': 'No.',
      'pmh.gi': 'No bowel conditions — no Crohn’s or colitis.',
      'pmh.conditions': 'Nothing.',
      'gyn.pregnant': 'No.',
      'gyn.lmp': 'Two weeks ago.',
      'sx.sexual': 'No anal intercourse, and no STI risks.',
      'dh.meds': 'Codeine from a friend for the pain, which made it worse.',
      'dh.allergies': 'None.',
      'sh.diet': 'Lots of takeaways on shift; not much fruit or veg; I don’t drink much water.',
      'comm.questions': 'Please don’t say you need to put a finger in — I can’t bear it.',
    },
    key: ['comm.open', 'ano.pain', 'pain.onset', 'ano.blood_type', 'ano.lump', 'gi.constipation', 'gi.bowel_change', 'gi.weight', 'pmh.gi', 'dh.meds', 'sh.diet'],
    critical: ['ano.pain', 'ano.blood_type'],
    ideas: 'I thought it might be piles.',
    concerns: 'That it’ll never heal — and the bleeding.',
    expectations: 'Something to make going to the toilet bearable.',
    social: { diet: 'Low fibre, poor fluid intake on night shifts.' },
  },
  keyed: {
    'comm.pain': { text: '', says: 'It hurts the moment anything touches it. Please be careful.' },
    'pr.inspect': {
      text: 'Gently parting the buttocks: a longitudinal split in the anoderm in the posterior midline (6 o’clock), with a red raw base and clean edges; no sentinel tag. The sphincter is visibly clenched.',
      abnormal: true,
      meaning: 'An acute posterior midline fissure. A lateral or multiple fissures suggest Crohn’s, HIV, syphilis, TB or cancer.',
    },
    'pr.strain': { text: 'She tries to bear down but stops — it hurts.', reaction: 0.5 },
    'pr.palpate': { text: 'The perianal skin is soft with no induration or fluctuance. Touching the margin at 6 o’clock causes a sharp flinch.', reaction: 0.7, abnormal: true },
    'pr.lubricate': { text: 'You lubricate your finger.' },
    'pr.insert': {
      text: 'As your finger touches the anal margin she cries out and the sphincter clamps shut. You stop.',
      abnormal: true,
      reaction: 1,
      says: 'Stop — please stop!',
      meaning: 'With a clear fissure and spasm, do not force a DRE — the diagnosis is made on inspection; use topical anaesthetic or examine under anaesthesia if needed.',
    },
    'pr.tone': { text: 'Not possible — too painful.' },
    'pr.sweep': { text: 'Not possible — too painful. You should not persist.', reaction: 1 },
    'pr.anterior': { text: 'Not possible.' },
    'pr.glove': { text: 'A trace of bright red blood on the glove tip.' },
    'pr.proctoscope': { text: 'You must not pass a proctoscope through an acutely painful fissure.', reaction: 1 },
    'pr.nodes': { text: 'No inguinal lymphadenopathy.' },
    'complete.scope': { text: 'No flexible sigmoidoscopy needed now: young, with typical symptoms and no red flags — but if it does not heal or symptoms change, the bowel should be examined.' },
  },
  investigations: {
    fbc: { values: FBC(128, 6.4, 3.9, 252, 88, 'female'), interpretation: 'Normal — minor bleeding only.' },
    proctoscopy: { report: 'Not performed — too painful with a visible fissure.', interpretation: 'Not indicated acutely.' },
    flexi: { report: 'Not indicated at present.', interpretation: 'Only for atypical features, red flags or non-healing.' },
  },
  investigationRubric: {
    essential: [],
    helpful: [{ id: 'fbc', why: 'If concerned about blood loss.' }],
    avoid: [
      { id: 'proctoscopy', why: 'Painful and unnecessary — the fissure is seen on inspection.' },
      { id: 'colonoscopy', why: 'No red flags in a 28-year-old with a typical fissure.' },
    ],
  },
  diagnosis: {
    correct: 'fissure',
    differentials: ['haemorrhoids', 'perianal-abscess', 'perianal-haematoma', 'crohns', 'anal-cancer'],
  },
  management: {
    essential: [
      { id: 'laxatives', why: 'Bulk-forming laxative (± osmotic) to keep stools soft.' },
      { id: 'lifestyle', why: 'More fibre and fluids; don’t delay the urge to go.' },
      { id: 'topical-gtn', why: '!Topical diltiazem 2% (or GTN 0.4%) twice daily for 6–8 weeks to relax the internal sphincter and let the fissure heal.' },
      { id: 'analgesia', why: 'Paracetamol, warm baths, topical lidocaine before defecation.' },
    ],
    helpful: [
      { id: 'botox-lis', why: 'If chronic and not healed after 6–8 weeks of topical therapy: botulinum toxin, then lateral internal sphincterotomy.' },
      { id: 'reassure', why: 'Most acute fissures heal with conservative treatment.' },
    ],
    avoid: [
      { id: 'eua-drainage', why: 'No abscess.' },
      { id: 'haemorrhoidectomy', why: 'Not haemorrhoids.' },
    ],
  },
  viva: [
    {
      id: 'why-posterior',
      q: 'Why do most fissures occur in the posterior midline?',
      answer: 'The posterior anoderm is the least well perfused, and the sphincter fibres there give least support. Spasm of the internal sphincter further reduces blood flow, creating a cycle of pain, spasm and ischaemia that prevents healing.',
      topic: 'Pathology',
    },
    {
      id: 'chronic',
      q: 'What makes a fissure chronic?',
      options: ['Lasting > 6 weeks, with a sentinel tag, hypertrophied papilla or exposed sphincter fibres', 'Any bleeding', 'Pain lasting an hour after defecation', 'Occurring in a woman'],
      correct: 0,
      answer: 'A fissure present for more than 6 weeks, often with a sentinel skin tag at its outer end, a hypertrophied anal papilla at its inner end and visible internal sphincter fibres in its base.',
      topic: 'Definitions',
    },
    {
      id: 'atypical',
      q: 'When should a fissure prompt further investigation?',
      answer: 'Lateral, multiple or painless fissures, or non-healing ones: consider Crohn’s, HIV, syphilis, TB and anal cancer (EUA and biopsy).',
      topic: 'Red flags',
    },
    {
      id: 'gtn',
      q: 'What side effect limits topical GTN?',
      answer: 'Headache (in up to half), which is why topical diltiazem is often preferred; both are ‘chemical sphincterotomies’.',
      topic: 'Treatment',
    },
  ],
  teaching: {
    summary:
      'Acute posterior anal fissure in a 28-year-old with constipation: severe tearing pain on defecation lasting an hour or two, bright red blood on the paper, a visible posterior midline split and marked spasm — DRE deferred; treated with stool softeners and topical diltiazem.',
    keyFindings: [
      '‘Passing glass’ pain on defecation, then throbbing for 1–2 hours',
      'Bright red blood on the paper; constipation from night shifts and low fibre',
      'Posterior midline fissure at 6 o’clock; no sentinel tag (acute)',
      'Severe sphincter spasm — DRE and proctoscopy not tolerated (and not needed)',
    ],
    pearls: [
      'The history makes the diagnosis; gentle parting of the buttocks confirms it.',
      'Do not force a DRE through a painful fissure.',
      'Codeine constipates — avoid it.',
      'Atypical (lateral or multiple) fissures need investigation.',
    ],
    presentation:
      'Ms Clarke is a 28-year-old nurse with four weeks of severe, tearing pain on defecation followed by a throbbing ache for one to two hours, with bright red blood on the toilet paper, after a hard stool. She is constipated on night shifts with a low-fibre diet and has been taking codeine. There are no red flags, no lump, discharge or change in bowel habit, and no history of inflammatory bowel disease. With a chaperone, in the left lateral position, gentle parting of the buttocks shows an acute fissure in the posterior midline at 6 o’clock with no sentinel tag; the sphincter is in spasm and she could not tolerate a rectal examination, which I did not force. This is an acute anal fissure. I would stop the codeine and treat her with a bulk laxative, fibre and fluids, analgesia and topical diltiazem for six to eight weeks, with review and referral for botulinum toxin or sphincterotomy if it becomes chronic.',
    references: ['Macleod’s Clinical Examination, 14th ed. — Ch. 6: rectal examination; anal spasm and fissure (pp. 111–112)', 'NICE CKS: anal fissure'],
  },
}

export default c
