import type { CaseDef, RegionFinding } from '../../engine/types'
import { COAG, CRP, FBC, lab, LFT, r, UE, VBG } from './helpers'

const peritonism = (light: 2 | 3, deep: 2 | 3): RegionFinding => r(light, deep, 'involuntary', { rebound: true, percussionTender: true })

const c: CaseDef = {
  id: 'anastomotic-leak',
  title: 'Anastomotic leak with pelvic sepsis on day 5 after laparoscopic anterior resection',
  presenting: 'Unwell on day 5 after bowel surgery',
  specialty: 'Colorectal',
  exam: 'abdominal',
  difficulty: 3,
  setting: 'Surgical ward',
  stem: 'Surgical ward, 02:00. You are the FY1 on call. Robert Turner, 66, is on day 5 after a laparoscopic anterior resection for a rectosigmoid cancer. The nurse is worried: his NEWS2 has risen to 7. Assess him, examine his abdomen, request investigations and start management.',
  components: ['history', 'exam', 'investigations', 'diagnosis', 'viva'],
  tags: ['post-operative care', 'sepsis', 'NEWS2', 'anastomotic leak', 'pre-operative assessment'],
  patient: {
    name: 'Robert Turner',
    title: 'Mr Turner',
    age: 66,
    sex: 'male',
    dob: '17/06/1960',
    occupation: 'a retired electrician',
    appearance: {
      sex: 'male',
      age: 66,
      skinTone: 3,
      habitus: 'overweight',
      hair: 'receding',
      hairColor: 'grey',
      eyeColor: 'hazel',
      facialHair: 'stubble',
      flushed: 0.45,
      sweaty: true,
      dehydrated: true,
      distension: 1,
      distensionType: 'gas',
      scars: ['lap-colorectal'],
      lines: { cannula: 'left-forearm', drip: true, drain: 'left' },
    },
    persona: { mood: 'anxious', style: 'normal' },
  },
  vitals: { hr: 124, rhythm: 'irregular', sbp: 102, dbp: 64, rr: 24, spo2: 94, temp: 38.4, avpu: 'A', pain: 7, bm: 13.6 },
  bedside: { drip: true, vomitBowl: 'bilious' },
  history: {
    opening: { text: 'I’ve felt rotten since yesterday evening, doctor. My tummy’s getting more and more painful, I’ve been shivering, and I was sick an hour ago.', cue: 'lies still, flushed, wincing as he speaks' },
    answers: {
      'pain.site': { text: 'Low down — mostly in the middle and on the left.', cue: 'points to the lower abdomen above the pubic bone' },
      'pain.onset': 'It was getting better after the operation. Then since yesterday afternoon it’s got worse and worse.',
      'pain.character': 'A deep, constant ache. Not like the wound pain.',
      'pain.radiation': 'Down into my back passage a bit.',
      'pain.moved': 'No.',
      'pain.timing': 'Constant.',
      'pain.exacerbating': 'Moving, coughing — the nurse helping me sit up was agony.',
      'pain.relieving': 'Lying still.',
      'pain.severity': 'Seven.',
      'pain.analgesia_taken': 'Paracetamol, and they gave me morphine an hour ago. It took the edge off.',
      'sys.fever': 'Hot and cold all night.',
      'sys.rigors': 'I was shaking like a leaf at about midnight.',
      'gi.nausea': 'Yes.',
      'gi.vomiting': 'Once, about an hour ago.',
      'gi.vomit_content': 'Green. No blood.',
      'gi.appetite': 'I was managing soup and toast on day three. Since yesterday I can’t face anything.',
      'gi.bowels_last': 'Day three — a loose one with a little blood; the nurses said that was expected. Nothing since.',
      'gi.flatus': 'I was passing wind until yesterday. Not since.',
      'gi.distension': 'Yes, it feels blown up.',
      'gi.diarrhoea': 'No — just that one loose one.',
      'gu.output': 'They took the catheter out on day two. I’ve hardly passed anything since this afternoon.',
      'gu.dysuria': 'No burning.',
      'ros.sob': 'I’m breathing faster, but I don’t feel short of breath.',
      'ros.cough': 'A little dry cough. Nothing coming up.',
      'ros.chest_pain': 'No.',
      'ros.palpitations': 'My heart’s racing — it feels like it’s fluttering.',
      'ros.calf': 'No — I’ve had the stockings on, and the injection every evening.',
      'ros.wound': 'The little wounds are fine. The nurse checked them this evening.',
      'ros.dizzy': 'A bit woozy when they sat me up.',
      'pmh.conditions': 'Type 2 diabetes and high blood pressure. The bowel cancer was picked up by the screening test.',
      'pmh.diabetes': 'Yes — metformin and gliclazide at home. They’ve been checking my sugars four times a day in here.',
      'pmh.heart': 'No heart problems. I’ve never had an irregular heartbeat before.',
      'pmh.bp': 'Yes, high blood pressure — I take ramipril.',
      'pmh.surgery': 'The keyhole bowel operation five days ago — they took out part of the lower bowel and joined it back together. No bag. Nothing before that.',
      'pmh.cancer': 'The bowel cancer, found on the home screening kit in the summer. They said they got it all out.',
      'dh.meds': 'At home: metformin, gliclazide, ramipril and atorvastatin. In here they’ve been giving me the blood-thinning injection, painkillers and an anti-sickness drug.',
      'dh.allergies': 'Penicillin — I came out in a rash all over.',
      'dh.anticoag': 'Just the injection in my tummy every evening.',
      'dh.steroids': 'No.',
      'dh.nsaids': 'No.',
      'sh.smoking': 'I stopped ten years ago.',
      'sh.alcohol': 'A few pints at the weekend.',
      'sh.living': 'With my wife.',
      'sh.mobility': 'I was walking to the toilet with the physio until yesterday.',
      'pre.last_meal': 'A few spoonfuls of soup at lunchtime yesterday. Sips of water since.',
      'comm.questions': 'Has something gone wrong with the join?',
    },
    key: [
      'comm.open',
      'pain.site',
      'pain.onset',
      'pain.character',
      'pain.severity',
      'sys.fever',
      'sys.rigors',
      'gi.vomiting',
      'gi.bowels_last',
      'gi.flatus',
      'gu.output',
      'ros.cough',
      'ros.sob',
      'ros.calf',
      'ros.wound',
      'ros.palpitations',
      'pmh.surgery',
      'pmh.diabetes',
      'dh.allergies',
    ],
    critical: ['dh.allergies', 'pmh.surgery'],
    ideas: 'The surgeon warned me about a leak from the join.',
    concerns: 'That I’ll need another operation and end up with a bag.',
    expectations: 'For someone to sort it out tonight.',
    social: { smoking: 'Ex-smoker; stopped ten years ago.', alcohol: 'About ten units a week.', mobility: 'Walking to the toilet with the physiotherapist until yesterday.' },
  },
  abdo: {
    general: {
      endOfBed:
        'Mr Turner is lying still in bed, flushed and sweaty and breathing fast. IV fluid is running through a cannula in his left forearm, and a drain comes out of the left iliac fossa: the bottle holds 80 mL of cloudy, brownish fluid with a faeculent smell. A vomit bowl contains a little green fluid. His wounds are covered with clean dressings and he is wearing compression stockings. There is no urinary catheter.',
      lyingStill: true,
    },
    hands: { temperature: 'warm', crt: 3, pulseVolume: 'bounding' },
    face: { mucosa: 'dry', tongue: 'dry-furred' },
    abdomen: {
      movesWithRespiration: 'reduced',
      inspectionExtra:
        'Mild distension. The port-site wounds and the low transverse extraction wound are clean and dry, without redness or discharge. A drain exits in the left iliac fossa.',
      coughPain: true,
      rigidity: 'localised',
      regions: {
        SP: peritonism(3, 3),
        LIF: peritonism(2, 3),
        RIF: r(1, 2, 'voluntary'),
        UMB: r(1, 2, 'voluntary'),
        LF: r(1, 1),
      },
      bowelSounds: 'reduced',
    },
    legs: { oedema: 'none', calves: 'Calves soft and non-tender; compression stockings in place.' },
    completion: {
      dre: 'Leave this to the senior surgeon: so soon after a low anastomosis, a digital examination should only be done by someone who will act on what they feel.',
      'cvs-resp': 'Irregularly irregular pulse of about 124 (new atrial fibrillation). Reduced air entry at both bases with a few fine crackles that clear on coughing; no bronchial breathing.',
      urinalysis: 'Concentrated urine: specific gravity 1.030, glucose 2+, ketones 1+; leucocytes and nitrites negative.',
    },
  },
  criticalSteps: ['gen.obs', 'abdo.inspect', 'palp.peritonism'],
  investigations: {
    fbc: { values: FBC(118, 18.6, 16.2, 412), interpretation: 'Neutrophil leucocytosis; mild post-operative anaemia.' },
    crp: { values: CRP(286), interpretation: 'CRP 286 on day 5. A CRP above about 150 from day 3 after bowel surgery should prompt a search for a leak.' },
    ue: {
      values: UE(134, 5.4, 14.2, 168, '37'),
      interpretation: 'Acute kidney injury (pre-op creatinine 82) from sepsis and hypovolaemia. Hold ramipril and metformin.',
    },
    lft: { values: LFT(18, 34, 112, 66, 26), interpretation: 'Low albumin (acute phase response); mild cholestatic changes of sepsis.' },
    vbg: {
      values: VBG(7.3, 18, -6.8, 3.4, 5.3, 14.2),
      interpretation: 'Metabolic acidosis with a lactate of 3.4 — sepsis with hypoperfusion. Glucose 14.2: stress hyperglycaemia in a diabetic.',
    },
    lactate: { values: [lab('Lactate', 3.4, 'mmol/L', '0.5–2.0', 'H')], interpretation: 'Raised — sepsis with hypoperfusion.' },
    cultures: { report: 'Gram-negative bacilli in both aerobic bottles at 14 hours (later identified as Escherichia coli).', interpretation: 'Bacteraemia with a gut organism.', abnormal: true },
    ecg: {
      report: 'Atrial fibrillation with a ventricular rate of 124. Normal axis. No acute ST changes.',
      interpretation: 'New fast AF — a classic sign of an intra-abdominal septic complication after surgery.',
      abnormal: true,
    },
    troponin: { values: [lab('hs-Troponin T', 12, 'ng/L', '< 14')], interpretation: 'Not raised.' },
    bm: { report: '13.6 mmol/L', interpretation: 'Hyperglycaemia: needs a variable-rate insulin infusion while he is nil by mouth.' },
    'urine-dip': { report: 'Specific gravity 1.030. Glucose 2+, ketones 1+. Leucocytes −, nitrites −.', interpretation: 'Concentrated urine; no evidence of a urinary infection.' },
    'cxr-erect': {
      report: 'A small volume of free gas under both hemidiaphragms. Bibasal linear atelectasis. No consolidation or effusion.',
      interpretation: 'Free gas is expected for several days after laparoscopy, so it does not prove a leak on its own — CT is needed.',
      abnormal: true,
    },
    'ct-ap': {
      report:
        'With IV and rectal contrast: extraluminal contrast and gas at the posterior aspect of the colorectal anastomosis, communicating with a 6 × 5 cm rim-enhancing presacral collection. Free fluid in the pelvis and left paracolic gutter, with a little free gas. Mildly dilated small bowel (ileus). The drain tip lies anterior to the collection.',
      interpretation: 'Anastomotic leak with a pelvic abscess.',
      abnormal: true,
    },
    ctpa: { report: 'No pulmonary embolus. Bibasal atelectasis.', interpretation: 'PE excluded — the tachycardia comes from abdominal sepsis.' },
    coag: { values: COAG(13.6, 1.2, 33), interpretation: 'Near-normal clotting. His last enoxaparin was at 18:00 — relevant to theatre and any epidural.' },
    gs: { report: 'Group A RhD positive. Antibody screen negative. Sample valid for 72 hours.' },
  },
  investigationRubric: {
    essential: [
      { id: 'fbc', why: 'Leucocytosis.' },
      { id: 'crp', why: 'A CRP above about 150 after day 3 suggests a septic complication.' },
      { id: 'ue', why: 'Oliguria — acute kidney injury.' },
      { id: 'vbg', why: 'Lactate measures the severity of sepsis.' },
      { id: 'cultures', why: 'Before antibiotics (Sepsis Six).' },
      { id: 'ecg', why: 'New irregular tachycardia.' },
      { id: 'ct-ap', why: '!CT with IV (± rectal) contrast is the key test for a suspected anastomotic leak or collection.' },
    ],
    helpful: [
      { id: 'cxr-erect', why: 'Look for a chest source — remembering that free gas is normal for days after laparoscopy.' },
      { id: 'urine-dip', why: 'Urinary source; concentrated urine.' },
      { id: 'bm', why: 'Diabetic, septic and nil by mouth.' },
      { id: 'lactate', why: 'Sepsis severity.' },
      { id: 'lft', why: 'Baseline.' },
      { id: 'coag', why: 'Before theatre; he is on LMWH.' },
      { id: 'gs', why: 'Likely return to theatre.' },
    ],
  },
  diagnosis: {
    correct: 'anastomotic-leak',
    differentials: ['lower-lobe-pneumonia', 'pe', 'uti', 'ileus', 'atelectasis', 'ssi', 'c-diff', 'mi'],
  },
  management: {
    essential: [
      { id: 'abcde', why: 'NEWS2 of 7 — an emergency response.' },
      { id: 'sepsis6', why: 'Sepsis with hypotension, a lactate of 3.4 and AKI: complete the Sepsis Six within the hour.' },
      { id: 'o2', why: 'SpO₂ 94% and tachypnoeic.' },
      { id: 'fluids', why: 'Give a fluid bolus (e.g. 500 mL crystalloid) and reassess — he is oliguric and hypotensive.' },
      { id: 'abx-iv', why: 'Broad-spectrum IV antibiotics covering gut organisms. He is allergic to penicillin, so use the local non-penicillin regimen.' },
      { id: 'catheter', why: 'Re-catheterise him to measure hourly urine output.' },
      { id: 'nbm', why: 'He is likely to need theatre.' },
      { id: 'senior', why: '!Escalate now: a leak with peritonism, sepsis and new AF needs the registrar and the consultant tonight.' },
      {
        id: 'return-theatre',
        why: '!Sepsis with peritonism from a leak usually means a return to theatre: washout plus a defunctioning ileostomy, or taking down the anastomosis (Hartmann’s).',
      },
    ],
    helpful: [
      { id: 'iv-access', why: 'Second large-bore cannula.' },
      { id: 'fluid-balance', why: 'Strict fluid balance.' },
      { id: 'icu', why: 'Critical care review: septic, AKI, new AF.' },
      { id: 'ng', why: 'Vomiting with an ileus.' },
      { id: 'analgesia', why: 'Titrated analgesia.' },
      { id: 'antiemetic', why: 'Nausea and vomiting.' },
      { id: 'glucose-monitoring', why: 'Variable-rate insulin infusion while he is nil by mouth; metformin and gliclazide held.' },
      { id: 'hartmanns', why: 'One option at re-operation for a large leak.' },
      { id: 'drainage-radiological', why: 'An alternative only for a small, contained collection in a stable patient.' },
      { id: 'consent', why: 'Consent, including for a stoma.' },
      { id: 'stoma-nurse', why: 'Stoma site marking and counselling if time allows.' },
    ],
    avoid: [
      { id: 'diet-normal', why: 'Nil by mouth.' },
      { id: 'nsaid', why: 'He has an acute kidney injury.' },
      { id: 'abx-oral', why: 'He is septic — antibiotics must be IV.' },
      { id: 'laxatives', why: 'No role with a leak and an ileus.' },
    ],
  },
  viva: [
    {
      id: 'fever-timing',
      q: 'How does the timing of a post-operative fever help you find its cause?',
      answer:
        'Day 0–2: the inflammatory response to surgery, atelectasis, transfusion or drug reactions. Day 3–5: pneumonia, urinary infection (especially after a catheter), line infection and an early anastomotic leak. Day 5–7: anastomotic leak, intra-abdominal collection and wound infection. After the first week: DVT/PE, C. difficile and deep collections. Work through the “Ws” — wind, water, wound, walking (DVT), wonder drugs — and ask what the operation itself put at risk.',
      topic: 'Post-operative care',
    },
    {
      id: 'leak-sign',
      q: 'Which is often the earliest sign of an anastomotic leak?',
      options: ['Unexplained tachycardia or new atrial fibrillation', 'Wound dehiscence', 'Bradycardia', 'Hiccups'],
      correct: 0,
      answer:
        'A persistent tachycardia, new AF, fever, prolonged ileus, a rising CRP, or simply a patient who is “not right” on days 3–7 should prompt a CT. Peritonism may come later, and drains are unreliable.',
      topic: 'Complications',
    },
    {
      id: 'risk',
      q: 'What are the risk factors for an anastomotic leak?',
      answer:
        'Patient factors: male sex, obesity, smoking, diabetes, malnutrition and low albumin, steroids or immunosuppression, ASA grade 3 or more, and pre-operative pelvic radiotherapy. Technical factors: a low (rectal) anastomosis — the lower, the riskier — tension, poor blood supply, contamination, a long operation and blood loss. A defunctioning loop ileostomy does not prevent a leak but lessens its consequences.',
      topic: 'Complications',
    },
    {
      id: 'fasting',
      q: 'Before an elective general anaesthetic, what are the standard minimum fasting times?',
      options: ['Food 6 hours; clear fluids 2 hours', 'Nothing by mouth after midnight', 'Food 4 hours; clear fluids 4 hours', 'Food 2 hours; clear fluids 1 hour'],
      correct: 0,
      answer:
        'Six hours for food (including milk) and two hours for clear fluids; many units now let patients sip clear fluids until they are sent for. Prolonged fasting causes dehydration, insulin resistance and distress, so enhanced recovery pathways use carbohydrate-loading drinks.',
      topic: 'Pre-operative care',
    },
    {
      id: 'diabetes-preop',
      q: 'How would you manage his diabetes medicines around elective surgery?',
      answer:
        'Following CPOC guidance: check HbA1c beforehand and optimise if it is very high, and put him early on the list to shorten starvation. Metformin is usually continued unless he will miss more than one meal, his renal function is poor or contrast is planned (stop it in AKI). Omit the gliclazide on the day of surgery because of the risk of hypoglycaemia. Monitor capillary glucose at least hourly while starved, and use a variable-rate IV insulin infusion if he will miss more than one meal or his glucose stays above 12 mmol/L.',
      topic: 'Pre-operative care',
    },
    {
      id: 'eras',
      q: 'Name some elements of an enhanced recovery (ERAS) pathway for bowel surgery.',
      answer:
        'Before surgery: counselling, prehabilitation, correcting anaemia, stopping smoking, carbohydrate loading and minimal fasting. During: laparoscopic surgery, goal-directed fluids, keeping the patient warm, short-acting anaesthesia, and avoiding routine NG tubes and drains. After: multimodal, opioid-sparing analgesia, early eating and drinking, early mobilisation, early catheter removal, VTE prophylaxis and clear discharge criteria.',
      topic: 'Peri-operative care',
    },
  ],
  teaching: {
    summary:
      'Anastomotic leak after a laparoscopic anterior resection: on day 5, a diabetic man who had been recovering develops increasing lower abdominal pain, rigors, vomiting, oliguria and new fast AF, with localised peritonism, a faeculent drain and a CRP of 286. CT confirms a leak with a presacral collection.',
    keyFindings: [
      'Day 5 after laparoscopic anterior resection; recovering well until yesterday',
      'Worsening lower abdominal pain, rigors, a bilious vomit, no flatus, oliguria',
      'NEWS2 7: new fast AF at 124, BP 102/64, RR 24, SpO₂ 94%, T 38.4 °C',
      'Lower abdominal peritonism; turbid, faeculent drain fluid; clean wounds; soft calves',
      'WCC 18.6, CRP 286, AKI (creatinine 168), lactate 3.4; E. coli bacteraemia; penicillin allergy',
      'CT: extraluminal contrast at the anastomosis with a 6 cm presacral collection',
    ],
    pearls: [
      'A patient who is “not right” after bowel surgery has a leak until proven otherwise — look for tachycardia, new AF, fever and ileus.',
      'Work through the causes of post-operative fever systematically: chest, urine, wound, legs, lines, drugs — and the operation.',
      'Check the drug chart: allergies, anticoagulants, and what to hold in AKI (ACE inhibitors, metformin, NSAIDs).',
      'Free gas on a chest X-ray is expected for days after laparoscopy; CT is the test.',
      'Escalate early: sepsis plus peritonism after an anastomosis is a senior decision about theatre.',
    ],
    presentation:
      'Mr Turner is a 66-year-old man with type 2 diabetes who is day 5 after a laparoscopic anterior resection for a rectosigmoid cancer. Having recovered well at first, since yesterday he has had worsening lower abdominal pain, rigors, a bilious vomit, no flatus and very little urine. His NEWS2 is 7: he is in new fast atrial fibrillation at 124, with a blood pressure of 102/64, respiratory rate 24, saturations 94% on air and temperature 38.4. He is flushed and lying still, with a mildly distended abdomen, localised peritonism in the suprapubic region and left iliac fossa, reduced bowel sounds and turbid, faeculent fluid in his pelvic drain; his wounds are clean, his chest has only basal crackles that clear on coughing, and his calves are soft. He has a leucocytosis of 18.6, a CRP of 286, an acute kidney injury and a lactate of 3.4, and he is allergic to penicillin. I am concerned about an anastomotic leak with sepsis. I would start the Sepsis Six with a non-penicillin regimen, give oxygen and a fluid bolus, re-catheterise him, keep him nil by mouth, hold his ramipril and metformin, escalate immediately to my registrar and critical care, and arrange an urgent CT, which shows a leak with a presacral collection. He is likely to need a return to theatre for a washout and a defunctioning stoma.',
    references: [
      'NICE NG51: Suspected sepsis — recognition, diagnosis and early management',
      'Centre for Perioperative Care (CPOC): Guideline for perioperative care for people with diabetes mellitus undergoing elective and emergency surgery (2021)',
      'Gustafsson UO, et al. ERAS Society guidelines for perioperative care in elective colorectal surgery (2018)',
      'Royal College of Physicians: National Early Warning Score (NEWS) 2',
    ],
  },
}

export default c
