import type { CaseDef } from '../../engine/types'

const c: CaseDef = {
  id: 'appendicitis',
  title: 'Acute appendicitis',
  presenting: 'Right iliac fossa pain',
  specialty: 'Emergency general surgery',
  exam: 'abdominal',
  difficulty: 1,
  setting: 'Emergency department',
  stem: 'You are the FY1 on the general surgical take. James Carter, 24, has been referred from the emergency department with abdominal pain. Take a focused history, examine his abdomen, request appropriate investigations and outline your management.',
  components: ['history', 'exam', 'investigations', 'diagnosis', 'viva'],
  tags: ['acute abdomen', 'RIF pain', 'peritonism', 'Rovsing', 'Alvarado'],
  patient: {
    name: 'James Carter',
    title: 'Mr Carter',
    age: 24,
    sex: 'male',
    dob: '14/03/2002',
    occupation: 'a software developer',
    appearance: {
      sex: 'male',
      age: 24,
      skinTone: 3,
      habitus: 'average',
      hair: 'short',
      hairColor: 'darkbrown',
      eyeColor: 'brown',
      facialHair: 'stubble',
      flushed: 0.35,
      dehydrated: true,
      lines: { cannula: 'left-hand' },
    },
    persona: { mood: 'anxious', style: 'normal' },
  },
  vitals: { hr: 102, rhythm: 'regular', sbp: 128, dbp: 78, rr: 18, spo2: 98, temp: 38.0, avpu: 'A', pain: 7 },
  bedside: { vomitBowl: 'clear' },
  history: {
    opening: {
      text: 'I’ve had this awful pain in my tummy since yesterday. It started around my belly button, but now it’s really bad down here on the right.',
      cue: 'points to his right lower abdomen',
    },
    answers: {
      'pain.site': { text: 'Down here, low on the right side.', cue: 'points with one finger to the right iliac fossa' },
      'pain.onset': 'It started yesterday afternoon — about eighteen hours ago. It came on gradually, a dull ache around my belly button.',
      'pain.moved': 'Yes! It started in the middle, around my belly button, then overnight it moved down to the right and got much sharper.',
      'pain.character': 'Now it’s sharp and constant. At first it was more of a dull, crampy ache.',
      'pain.radiation': 'No, it stays here on the right.',
      'pain.timing': 'It’s constant now. It doesn’t go away at all.',
      'pain.exacerbating': 'Moving, coughing… every bump in the taxi on the way here was agony.',
      'pain.relieving': 'Lying still with my knees bent helps a bit.',
      'pain.severity': 'About seven out of ten.',
      'pain.previous': 'No, never had anything like this.',
      'pain.analgesia_taken': 'I took two paracetamol last night. It didn’t really touch it.',
      'gi.nausea': 'Yes, I’ve felt sick since it started.',
      'gi.vomiting': 'I was sick twice this morning.',
      'gi.vomit_content': 'Just what I’d eaten. No blood, and it wasn’t green.',
      'gi.appetite': 'No appetite at all. I couldn’t face dinner last night — which isn’t like me at all.',
      'gi.bowels_last': 'Yesterday morning. It was normal.',
      'gi.flatus': 'Yes, I think so.',
      'gi.diarrhoea': 'No.',
      'gi.bowel_change': 'No, they’re normal.',
      'sys.fever': 'I felt hot and sweaty last night.',
      'sys.rigors': 'No, no shaking.',
      'gu.dysuria': 'No, that’s fine.',
      'gu.loin': 'No, not in my back.',
      'scr.swelling': 'No, nothing like that down there.',
      'pmh.conditions': 'I’m fit and well. I had asthma as a kid but grew out of it.',
      'dh.allergies': 'Penicillin — I came out in a rash all over when I was little.',
      'fh.general': 'My dad has high blood pressure. Nothing else I know of.',
      'sh.smoking': 'Only socially at the weekend — maybe five a week.',
      'sh.alcohol': 'A few pints at the weekend, maybe ten or twelve units.',
      'sh.living': 'I live with my girlfriend in a flat.',
      'pre.last_meal': 'A sandwich at lunchtime yesterday. Nothing since, apart from sips of water.',
      'comm.questions': 'Will I need an operation? And how long will I be off work?',
    },
    key: [
      'comm.open',
      'pain.site',
      'pain.onset',
      'pain.moved',
      'pain.character',
      'pain.radiation',
      'pain.exacerbating',
      'pain.severity',
      'gi.nausea',
      'gi.vomiting',
      'gi.appetite',
      'gi.bowels_last',
      'sys.fever',
      'gu.dysuria',
      'pmh.surgery',
      'dh.meds',
      'dh.allergies',
      'pre.last_meal',
    ],
    critical: ['dh.allergies'],
    ideas: 'My mate had appendicitis last year and it sounds exactly like what he had.',
    concerns: 'I’m worried I’ll need an operation — I’ve never had one before.',
    expectations: 'I just want the pain to stop and to know what’s going on.',
    social: { smoking: 'Only socially — maybe five a week.', alcohol: 'A few pints at the weekend.' },
  },
  abdo: {
    general: {
      endOfBed:
        'Mr Carter is lying very still on the trolley with his knees slightly drawn up. He looks flushed and uncomfortable, and winces whenever he shifts position. There is a cannula in his left hand and a sick bowl on the locker. No drains, stomas or catheter.',
      lyingStill: true,
    },
    face: { mucosa: 'dry', tongue: 'dry-furred' },
    abdomen: {
      movesWithRespiration: 'reduced',
      coughPain: true,
      regions: {
        RIF: { light: 2, deep: 3, guarding: 'involuntary', rebound: true, percussionTender: true, note: 'tympanic' },
        SP: { light: 1, deep: 1, guarding: 'voluntary', rebound: false, percussionTender: false, note: 'tympanic' },
        UMB: { light: 0, deep: 1, guarding: 'none', rebound: false, percussionTender: false, note: 'tympanic' },
        RF: { light: 0, deep: 1, guarding: 'none', rebound: false, percussionTender: false, note: 'tympanic' },
      },
      rovsing: true,
      psoas: false,
      obturator: false,
      bowelSounds: 'reduced',
    },
    completion: {
      dre: 'Tenderness high on the right side of the rectum; no mass; soft brown stool, no blood. (DRE is no longer routine in suspected appendicitis, but right-sided tenderness suggests a pelvic appendix.)',
      genitalia: 'Normal external genitalia. Both testes lie normally, are non-tender, with no swelling — important to exclude testicular torsion in any young man with lower abdominal pain.',
      urinalysis: 'Leucocytes +, ketones ++, nitrites −, blood −.',
    },
  },
  criticalSteps: ['palp.peritonism'],
  investigations: {
    fbc: {
      values: [
        { name: 'Haemoglobin', value: '148', unit: 'g/L', range: '130–170' },
        { name: 'White cells', value: '14.8', unit: '×10⁹/L', range: '4.0–11.0', flag: 'H' },
        { name: 'Neutrophils', value: '12.1', unit: '×10⁹/L', range: '2.0–7.5', flag: 'H' },
        { name: 'Platelets', value: '291', unit: '×10⁹/L', range: '150–400' },
        { name: 'MCV', value: '87', unit: 'fL', range: '80–100' },
      ],
      interpretation: 'Neutrophil leucocytosis — acute bacterial inflammation.',
    },
    crp: { values: [{ name: 'CRP', value: '68', unit: 'mg/L', range: '< 5', flag: 'H' }], interpretation: 'Raised CRP.' },
    ue: {
      values: [
        { name: 'Sodium', value: '138', unit: 'mmol/L', range: '135–145' },
        { name: 'Potassium', value: '4.0', unit: 'mmol/L', range: '3.5–5.3' },
        { name: 'Urea', value: '7.1', unit: 'mmol/L', range: '2.5–7.8' },
        { name: 'Creatinine', value: '91', unit: 'µmol/L', range: '60–110' },
        { name: 'eGFR', value: '> 90', unit: 'mL/min/1.73m²', range: '> 90' },
      ],
      interpretation: 'Normal renal function (upper-normal urea from reduced intake).',
    },
    'urine-dip': {
      report: 'Leucocytes +, ketones ++, nitrites −, blood −, protein −.',
      interpretation: 'Sterile pyuria can occur when an inflamed appendix lies against the ureter or bladder; ketones reflect fasting and vomiting. Not a UTI.',
    },
    vbg: {
      values: [
        { name: 'pH', value: '7.37', range: '7.35–7.45' },
        { name: 'Lactate', value: '1.4', unit: 'mmol/L', range: '0.5–2.0' },
        { name: 'Glucose', value: '5.6', unit: 'mmol/L', range: '4.0–7.8' },
      ],
      interpretation: 'Normal lactate.',
    },
    'us-abdo': {
      report: 'A non-compressible, blind-ending tubular structure in the right iliac fossa measuring 9 mm in diameter with surrounding echogenic inflamed fat and a trace of free fluid. Appearances consistent with acute appendicitis.',
      interpretation: 'Supports acute appendicitis.',
    },
    'ct-ap': {
      report: 'Dilated (11 mm) thick-walled appendix with mucosal hyperenhancement, periappendiceal fat stranding and a 6 mm appendicolith. No extraluminal gas or collection.',
      interpretation: 'Acute uncomplicated appendicitis with an appendicolith.',
    },
    axr: { report: 'Non-specific bowel gas pattern. No obstruction.', interpretation: 'AXR adds nothing in suspected appendicitis.' },
  },
  investigationRubric: {
    essential: [
      { id: 'fbc', why: 'Leucocytosis/neutrophilia supports the diagnosis (and scores 3 in Alvarado).' },
      { id: 'crp', why: 'A normal CRP and WCC make appendicitis much less likely.' },
      { id: 'ue', why: 'Baseline renal function before IV fluids, contrast and theatre.' },
      { id: 'urine-dip', why: 'Excludes UTI/renal colic as alternatives.' },
    ],
    helpful: [
      { id: 'gs', why: 'Pre-operative group & save.' },
      { id: 'us-abdo', why: 'Ultrasound helps when the diagnosis is uncertain (first-line in the young and in women).' },
      { id: 'ct-ap', why: 'CT is highly accurate in adults when the diagnosis is uncertain.' },
      { id: 'coag', why: 'Pre-operative, particularly if septic.' },
    ],
    avoid: [{ id: 'axr', why: 'An abdominal X-ray does not help diagnose appendicitis and adds radiation.' }],
  },
  diagnosis: {
    correct: 'appendicitis',
    differentials: ['mesenteric-adenitis', 'testicular-torsion', 'renal-colic', 'crohns', 'gastroenteritis'],
  },
  management: {
    essential: [
      { id: 'analgesia', why: 'Early analgesia is humane and does not mask signs.' },
      { id: 'nbm', why: 'Prepare for theatre.' },
      { id: 'fluids', why: 'He is tachycardic, febrile and has been vomiting.' },
      { id: 'abx-iv', why: 'Start IV antibiotics once the diagnosis is made — he is penicillin-allergic, so use a non-penicillin regimen per local policy.' },
      { id: 'senior', why: 'Discuss with the registrar.' },
      { id: 'lap-appendicectomy', why: '!Definitive treatment for acute appendicitis.' },
      { id: 'consent', why: 'Consent for laparoscopic appendicectomy (possible conversion to open).' },
    ],
    helpful: [
      { id: 'antiemetic', why: 'He is nauseated and vomiting.' },
      { id: 'vte', why: 'VTE risk assessment and prophylaxis.' },
    ],
    avoid: [
      { id: 'discharge', why: 'He has localised peritonism and a raised WCC — he must not go home.' },
      { id: 'diet-normal', why: 'Keep nil by mouth before likely surgery.' },
      { id: 'laxatives', why: 'No role — and risky with peritonitis.' },
    ],
  },
  viva: [
    {
      id: 'alvarado',
      q: 'Which of these is a component of the Alvarado score?',
      options: ['Migration of pain to the right iliac fossa', 'Diarrhoea', 'Pain radiating to the back', 'Haematuria'],
      correct: 0,
      answer:
        'Alvarado (MANTRELS, /10): Migration of pain to the RIF 1, Anorexia 1, Nausea/vomiting 1, Tenderness in RIF 2, Rebound tenderness 1, Elevated temperature ≥ 37.3 °C 1, Leucocytosis > 10 2, Shift to the left (neutrophilia) 1. A score ≥ 7 indicates high probability. Mr Carter scores 10.',
      topic: 'Scores',
    },
    {
      id: 'mcburney',
      q: 'Where is McBurney’s point?',
      options: [
        'One-third of the way from the ASIS to the umbilicus',
        'The midpoint of the inguinal ligament',
        'One-third of the way from the umbilicus to the ASIS',
        'The tip of the right 9th costal cartilage',
      ],
      correct: 0,
      answer: 'One-third of the distance from the anterior superior iliac spine to the umbilicus — the surface marking of the base of the appendix and the usual point of maximal tenderness.',
      topic: 'Anatomy',
    },
    {
      id: 'rovsing',
      q: 'Describe Rovsing’s sign and explain why it occurs.',
      answer:
        'Deep palpation of the left iliac fossa produces pain in the right iliac fossa. Pressure displaces bowel contents and gas towards the caecum and moves the parietal peritoneum, stretching the inflamed peritoneum over the appendix.',
      topic: 'Signs',
    },
    {
      id: 'pain-shift',
      q: 'Why does appendicitis pain begin around the umbilicus and then move to the right iliac fossa?',
      answer:
        'Early inflammation distends the appendix and stimulates visceral (autonomic) afferents of the midgut entering the cord at T10, so pain is referred poorly-localised to the periumbilical region. When the inflammation reaches the parietal peritoneum (somatic innervation), pain becomes sharp and localises to the RIF.',
      topic: 'Physiology',
    },
    {
      id: 'complications',
      q: 'List complications of appendicitis and of appendicectomy.',
      answer:
        'Appendicitis: perforation, generalised peritonitis, appendix mass or abscess, pylephlebitis/portal pyaemia, sepsis. Appendicectomy: wound/port-site infection, intra-abdominal or pelvic abscess, ileus, bleeding, stump appendicitis/leak, port-site hernia, later adhesional obstruction, VTE.',
      topic: 'Complications',
    },
    {
      id: 'female',
      q: 'If this were a 24-year-old woman, which test must be done before anything else?',
      options: ['Urine or serum β-hCG', 'CT abdomen', 'Abdominal X-ray', 'Serum amylase'],
      correct: 0,
      answer: 'A pregnancy test. Ectopic pregnancy must be excluded in every woman of reproductive age with abdominal pain, and pregnancy changes imaging (ultrasound/MRI rather than CT) and drug choices.',
      topic: 'Safety',
    },
  ],
  teaching: {
    summary:
      'Classic acute appendicitis: periumbilical visceral pain migrating to the RIF, anorexia, nausea and vomiting, low-grade fever, localised peritonism at McBurney’s point, a positive Rovsing’s sign and a neutrophil leucocytosis.',
    keyFindings: [
      'Lying still — movement and coughing hurt (peritonism)',
      'Tachycardia 102, temperature 38.0 °C',
      'RIF tenderness with involuntary guarding and percussion tenderness',
      'Rovsing’s sign positive',
      'WCC 14.8 with neutrophilia, CRP 68',
      'Penicillin allergy — changes the antibiotic choice',
    ],
    pearls: [
      'Always start palpating as far away from the pain as possible (here the left upper quadrant) and watch the face.',
      'Pain on coughing and percussion tenderness are kinder tests of peritonism than rebound.',
      'Examine the testes in every young man with lower abdominal pain — torsion can present this way.',
      'Sterile pyuria does not exclude appendicitis.',
      'Every woman of childbearing age with abdominal pain needs a pregnancy test.',
    ],
    presentation:
      'Mr Carter is a 24-year-old man presenting with an 18-hour history of abdominal pain that began periumbilically and migrated to the right iliac fossa, associated with anorexia, nausea, two episodes of vomiting and subjective fever. He is penicillin-allergic. On examination he is flushed, tachycardic at 102 and febrile at 38.0 °C, lying still. He has right iliac fossa tenderness with involuntary guarding and percussion tenderness, pain on coughing and a positive Rovsing’s sign; bowel sounds are reduced. Bloods show a neutrophil leucocytosis (WCC 14.8) and CRP 68. The most likely diagnosis is acute appendicitis (Alvarado 10), with mesenteric adenitis, testicular torsion and renal colic as differentials. I would keep him nil by mouth, give IV fluids, analgesia and antiemetics, start non-penicillin IV antibiotics, inform my registrar and consent him for a laparoscopic appendicectomy.',
    references: [
      'Macleod’s Clinical Examination, 14th ed. — Ch. 6, The gastrointestinal system: examination of the abdomen and the acute abdomen',
      'Di Saverio S, et al. WSES Jerusalem guidelines for diagnosis and treatment of acute appendicitis (2020 update)',
    ],
  },
}

export default c
