import type { CaseDef } from '../../engine/types'
import { CRP, FBC, lab, LFT, r, UE, VBG } from './helpers'

const c: CaseDef = {
  id: 'bariatric-leak',
  title: 'Staple-line leak after laparoscopic sleeve gastrectomy',
  presenting: 'Tachycardia and abdominal pain after weight-loss surgery',
  specialty: 'Upper GI',
  exam: 'abdominal',
  difficulty: 3,
  setting: 'Surgical ward',
  stem: 'You are the FY1 on the surgical ward. Rebecca Shaw, 41, is on day 3 after a laparoscopic sleeve gastrectomy. The nurse is worried because her heart rate has crept up overnight. Assess her, examine her abdomen, investigate and start management.',
  components: ['history', 'exam', 'investigations', 'diagnosis', 'viva'],
  tags: ['bariatric', 'post-operative', 'leak', 'sepsis', 'tachycardia'],
  patient: {
    name: 'Rebecca Shaw',
    title: 'Ms Shaw',
    age: 41,
    sex: 'female',
    dob: '03/02/1985',
    occupation: 'a call-centre manager',
    appearance: {
      sex: 'female',
      age: 41,
      skinTone: 2,
      habitus: 'obese',
      hair: 'long',
      hairColor: 'brown',
      eyeColor: 'brown',
      sweaty: true,
      flushed: 0.3,
      striae: true,
      scars: ['lap-chole'],
      lines: { cannula: 'left-hand', drip: true, oxygen: 'nasal', drain: 'left' },
    },
    persona: { mood: 'anxious', style: 'normal' },
  },
  vitals: { hr: 126, rhythm: 'regular', sbp: 112, dbp: 70, rr: 24, spo2: 94, o2: '2 L/min nasal', temp: 38.3, avpu: 'A', pain: 7 },
  history: {
    opening: { text: 'I was doing well yesterday… but since last night I’ve had this pain under my left ribs and I just feel awful. My heart’s racing.', cue: 'shifts uncomfortably, holding her left upper abdomen' },
    answers: {
      'pain.site': { text: 'Up here, under the left ribs, and right at the top of my stomach.', cue: 'points to the left upper quadrant and epigastrium' },
      'pain.onset': 'It started late last night and has got steadily worse.',
      'pain.character': 'A constant, deep ache. Sharp when I breathe in.',
      'pain.radiation': 'Into the tip of my left shoulder.',
      'pain.timing': 'It’s there all the time now.',
      'pain.exacerbating': 'Deep breaths and moving.',
      'pain.relieving': 'Nothing really. The morphine takes the edge off.',
      'pain.severity': 'Seven out of ten. Much worse than after the operation.',
      'pain.previous': 'After the op it was just sore at the little cuts — this is different.',
      'gi.nausea': 'Yes, I feel sick.',
      'gi.vomiting': 'Once this morning.',
      'gi.vomit_content': 'Just a bit of fluid. No blood.',
      'gi.appetite': 'I can’t face the sips of water they want me to drink.',
      'gi.bowels_last': 'Not since the operation.',
      'gi.flatus': 'A little wind yesterday.',
      'sys.fever': 'I’ve been hot and shivery overnight.',
      'sys.rigors': 'I was shaking at about four this morning.',
      'ros.sob': 'I feel a bit short of breath.',
      'ros.chest_pain': 'Only the pain under my ribs when I breathe in.',
      'ros.cough': 'No.',
      'ros.palpitations': 'My heart’s been racing all night.',
      'gu.output': 'The nurses say I haven’t passed much urine.',
      'pmh.conditions': 'Type 2 diabetes, high blood pressure and sleep apnoea — I use a CPAP machine.',
      'pmh.surgery': 'The sleeve gastrectomy three days ago. A caesarean years ago.',
      'pmh.diabetes': 'Type 2, on metformin. They stopped it for the operation.',
      'dh.meds': 'Metformin and ramipril at home, both on hold. Here they’re giving me injections in my tummy, morphine and something for my stomach.',
      'dh.anticoag': 'Just the daily blood-thinning injection.',
      'dh.allergies': 'Penicillin gives me a rash.',
      'sh.smoking': 'I stopped two years ago for the surgery.',
      'sh.alcohol': 'Hardly ever.',
      'sh.weight': 'I’ve tried everything — slimming clubs, a year in the weight-management service, the injections. I was 128 kilos.',
      'comm.questions': 'Is something wrong with the operation?',
    },
    key: [
      'comm.open',
      'pain.site',
      'pain.onset',
      'pain.character',
      'pain.radiation',
      'pain.severity',
      'sys.fever',
      'ros.sob',
      'ros.chest_pain',
      'gi.vomiting',
      'gu.output',
      'pmh.surgery',
      'pmh.conditions',
      'dh.anticoag',
      'dh.allergies',
    ],
    critical: ['pmh.surgery', 'dh.allergies'],
    ideas: 'I wondered if I’d eaten too fast — I had more water than they said.',
    concerns: 'My friend had a leak after the same operation. Is that what this is?',
    expectations: 'I need you to find out what’s wrong and fix it.',
    social: { smoking: 'Ex-smoker, stopped two years ago.', alcohol: 'Rarely.', living: 'Lives with her partner and two teenage sons.' },
    pmh: 'Type 2 diabetes, hypertension, obstructive sleep apnoea on CPAP.',
    allergies: 'Penicillin — rash.',
  },
  abdo: {
    general: {
      endOfBed:
        'Ms Shaw is a woman with severe obesity, sitting propped up, flushed and clammy, breathing fast and shallowly with nasal oxygen. There are five small dressed laparoscopic port sites. A left upper quadrant drain contains a little cloudy, slightly brown fluid. Her observation chart shows the heart rate climbing from 88 to 126 overnight, and the catheter bag has only 15 mL an hour.',
    },
    hands: { temperature: 'warm', crt: 3 },
    face: { mucosa: 'dry' },
    abdomen: {
      shape: 'obese',
      inspectionExtra: 'Five dressed port sites; the left upper quadrant drain holds cloudy, turbid fluid.',
      coughPain: true,
      movesWithRespiration: 'reduced',
      regions: {
        LUQ: r(2, 3, 'voluntary', { percussionTender: true }),
        EPI: r(2, 3, 'voluntary', { percussionTender: true }),
        LF: r(1, 2),
        UMB: r(1, 1),
        RUQ: r(1, 1),
      },
      bowelSounds: 'reduced',
    },
    completion: { obs: 'NEWS2 9: HR 126, RR 24, SpO₂ 94% on 2 L, temp 38.3 °C, BP 112/70 — urgent escalation.', urinalysis: 'Ketones +; otherwise negative.' },
  },
  criticalSteps: ['gen.obs', 'palp.peritonism'],
  investigations: {
    fbc: { values: FBC(121, 18.6, 16.2, 288, 86, 'female'), interpretation: 'Neutrophil leucocytosis.' },
    crp: { values: CRP(286), interpretation: 'A CRP this high on day 3 after a sleeve is a red flag for a leak.' },
    ue: { values: UE(137, 4.6, 9.4, 112, '52', 'female'), interpretation: 'Acute kidney injury (sepsis, under-filling).' },
    lft: { values: LFT(18, 34, 98, 41, 31) },
    vbg: { values: VBG(7.32, 19, -5.4, 3.2, 4.6, 11.8), interpretation: 'Metabolic acidosis with a raised lactate — sepsis.' },
    cultures: { report: 'Sent before antibiotics.' },
    gs: { report: 'Group O RhD positive. Antibody screen negative.' },
    'drain-fluid': { report: 'Cloudy brown fluid; amylase 4,800 U/L; Gram stain: mixed organisms and yeasts.', interpretation: 'Gastric content in the drain — leak confirmed until proven otherwise.', abnormal: true },
    'ct-ap': {
      report: 'CT with IV and oral water-soluble contrast: extravasation of oral contrast at the upper end of the staple line near the angle of His, with a 7 cm gas- and fluid-containing collection in the left upper quadrant abutting the spleen. Small left pleural effusion.',
      interpretation: 'Proximal staple-line leak with a perigastric collection.',
      abnormal: true,
    },
    'contrast-swallow': {
      report: 'Water-soluble swallow: a small leak of contrast from the proximal staple line into the left upper quadrant.',
      interpretation: 'Leak — but a normal swallow does not exclude one.',
      abnormal: true,
    },
    ecg: { report: 'Sinus tachycardia 126 bpm. No ST changes.', interpretation: 'Sinus tachycardia (not AF).' },
    ctpa: { report: 'No pulmonary embolus. Left basal atelectasis and small effusion.', interpretation: 'No PE.' },
    'cxr-erect': { report: 'Left basal atelectasis and blunting of the left costophrenic angle. Small amount of free gas — expected 3 days after laparoscopy.', interpretation: 'Free gas is unhelpful this soon after laparoscopy.' },
    troponin: { values: [lab('hs-Troponin T', 11, 'ng/L', '< 14')] },
  },
  investigationRubric: {
    essential: [
      { id: 'fbc', why: 'Leucocytosis.' },
      { id: 'crp', why: 'A rising CRP after day 2 suggests a complication.' },
      { id: 'ue', why: 'AKI from sepsis.' },
      { id: 'vbg', why: 'Lactate and acid–base status.' },
      { id: 'cultures', why: 'Sepsis — cultures before antibiotics.' },
      { id: 'ct-ap', why: 'CT with oral and IV contrast is the test of choice for a suspected leak (if she is stable enough for the scanner).' },
      { id: 'gs', why: 'Likely return to theatre.' },
    ],
    helpful: [
      { id: 'drain-fluid', why: 'Cloudy drain fluid with high amylase is strongly suggestive.' },
      { id: 'contrast-swallow', why: 'Less sensitive than CT.' },
      { id: 'ecg', why: 'Exclude AF and MI as the cause of tachycardia.' },
      { id: 'ctpa', why: 'PE is the main differential of post-op tachycardia and hypoxia — often combined with the CT abdomen.' },
      { id: 'lft', why: 'Baseline.' },
    ],
    avoid: [{ id: 'colonoscopy', why: 'No role.' }],
  },
  diagnosis: {
    correct: 'sleeve-leak',
    accept: ['anastomotic-leak'],
    differentials: ['pe', 'lower-lobe-pneumonia', 'pancreatitis', 'mi', 'ssi'],
  },
  management: {
    essential: [
      { id: 'abcde', why: 'NEWS2 of 9 — ABCDE now.' },
      { id: 'sepsis6', why: 'Sepsis with a likely source.' },
      { id: 'o2', why: 'Hypoxic — oxygen to target.' },
      { id: 'fluids', why: 'Tachycardic and oliguric.' },
      { id: 'abx-iv', why: 'Broad-spectrum IV antibiotics (penicillin allergy) plus an antifungal.' },
      { id: 'nbm', why: 'Stop all oral intake — sips feed the leak.' },
      { id: 'catheter', why: 'Hourly urine output.' },
      { id: 'senior', why: 'Tell the bariatric registrar and consultant now — a leak is a surgical emergency.' },
      { id: 'leak-control', why: '!Source control: laparoscopic washout and drainage (± repair) if unstable or with peritonitis; radiological drainage ± endoscopic stent if stable and contained.' },
      { id: 'nutrition', why: 'She will be nil by mouth for weeks — feeding jejunostomy or parenteral nutrition.' },
    ],
    helpful: [
      { id: 'icu', why: 'Septic with obesity, OSA and diabetes — HDU/ICU.' },
      { id: 'analgesia', why: 'IV analgesia; continue CPAP with opioids.' },
      { id: 'ppi-iv', why: 'Protects the stomach.' },
      { id: 'glucose-monitoring', why: 'Diabetic and septic.' },
      { id: 'vte', why: 'Very high VTE risk — continue LMWH (weight-adjusted).' },
      { id: 'consent', why: 'For return to theatre.' },
    ],
    avoid: [
      { id: 'diet-normal', why: 'Nil by mouth.' },
      { id: 'discharge', why: 'Tachycardia > 120 after bariatric surgery is a leak until proven otherwise.' },
      { id: 'ng', why: 'Never pass a blind NG tube after a sleeve — it can perforate the staple line; any tube is placed by the surgeon or under vision.' },
      { id: 'nsaid', why: 'Ulcer risk and AKI.' },
    ],
  },
  viva: [
    {
      id: 'sign',
      q: 'What is the most sensitive early sign of a leak after bariatric surgery?',
      options: ['Sustained tachycardia (> 120 bpm)', 'Abdominal rigidity', 'Fever above 39 °C', 'Shoulder-tip pain'],
      correct: 0,
      answer: 'A persistent tachycardia, often with tachypnoea and rising oxygen requirements. In severe obesity peritonism is hard to feel, so a fast pulse is never ‘just pain’ — it needs urgent senior review and CT.',
      topic: 'Signs',
    },
    {
      id: 'where',
      q: 'Where do sleeve gastrectomy leaks usually occur, and why?',
      answer: 'At the proximal end of the staple line near the angle of His (gastro-oesophageal junction): the blood supply there is poorest, the wall is thin, and the high-pressure tube of the sleeve pushes against a narrow incisura.',
      topic: 'Anatomy',
    },
    {
      id: 'diff',
      q: 'Give the important differentials of tachycardia and breathlessness on day 3 after surgery.',
      answer: 'Anastomotic or staple-line leak, pulmonary embolism, pneumonia or atelectasis, bleeding, fluid overload, AF, MI, pain and withdrawal. Leak and PE are the two you must not miss — CT can look for both.',
      topic: 'Differentials',
    },
    {
      id: 'ops',
      q: 'Compare sleeve gastrectomy and Roux-en-Y gastric bypass.',
      answer: 'Sleeve: removes ~80% of the stomach along the greater curve — restrictive and hormonal (less ghrelin), no bypass of bowel, but can worsen reflux. Bypass: small gastric pouch joined to a Roux limb — restrictive plus malabsorptive, better for reflux and diabetes, but risks internal hernia, marginal ulcer and more deficiencies.',
      topic: 'Operations',
    },
  ],
  teaching: {
    summary:
      'Day-3 staple-line leak after laparoscopic sleeve gastrectomy: a patient with severe obesity whose heart rate climbs above 120, with fever, tachypnoea, left shoulder-tip pain, oliguria, cloudy drain fluid and a very high CRP, but only modest abdominal signs.',
    keyFindings: [
      'Heart rate 88 → 126 overnight, RR 24, SpO₂ 94% on 2 L, temp 38.3 °C — NEWS2 9',
      'Left upper quadrant and epigastric tenderness with guarding; left shoulder-tip pain',
      'Cloudy brown drain fluid with a high amylase',
      'CRP 286, WCC 18.6, lactate 3.2, AKI',
      'CT: contrast leak at the proximal staple line with a left upper quadrant collection',
    ],
    pearls: [
      'Peritonism is hard to elicit in severe obesity — trust the pulse, respiratory rate and CRP.',
      'Never pass a blind NG tube after upper GI or bariatric surgery.',
      'PE is the great mimic of a leak after bariatric surgery; both can be seen on the same CT.',
      'Patients with OSA should keep using CPAP after surgery, especially on opioids.',
    ],
    presentation:
      'Ms Shaw is a 41-year-old woman with type 2 diabetes, hypertension and obstructive sleep apnoea, on day 3 after a laparoscopic sleeve gastrectomy, who developed left upper abdominal pain radiating to the left shoulder tip overnight with fever and rigors. Her heart rate has risen from 88 to 126, with a respiratory rate of 24, saturations of 94% on 2 litres, a temperature of 38.3 and oliguria, giving a NEWS2 of 9. She is tender with guarding in the left upper quadrant and epigastrium, and her drain contains cloudy brown fluid. CRP is 286, lactate 3.2 and she has an AKI. CT with oral contrast shows a leak at the proximal staple line with a perigastric collection. I would manage her with the Sepsis Six, nil by mouth, IV antibiotics and an antifungal, escalate immediately to the bariatric team for source control and arrange critical care and nutritional support.',
    references: [
      'Macleod’s Clinical Examination, 14th ed. — Ch. 18: the deteriorating patient (NEWS2, ABCDE)',
      'NICE CG189: Obesity — bariatric surgery; BOMSS guidance on post-operative complications',
    ],
  },
}

export default c
