import type { CaseDef } from '../../engine/types'
import { FBC, lab, LFT, r, UE } from './helpers'

const c: CaseDef = {
  id: 'bariatric-assessment',
  title: 'Severe obesity (BMI 47) with type 2 diabetes, OSA and reflux — suitable for gastric bypass',
  presenting: 'Referral for weight-loss surgery',
  specialty: 'Upper GI',
  exam: 'abdominal',
  difficulty: 1,
  setting: 'Outpatient clinic',
  stem: 'Bariatric surgery clinic. Daniel Hughes, 38, has been referred by the specialist weight-management service. Take a focused history, examine him, request investigations and discuss whether surgery is appropriate and which operation.',
  components: ['history', 'exam', 'investigations', 'diagnosis', 'viva'],
  tags: ['bariatric', 'obesity', 'BMI', 'diabetes', 'OSA'],
  patient: {
    name: 'Daniel Hughes',
    title: 'Mr Hughes',
    age: 38,
    sex: 'male',
    dob: '17/09/1988',
    occupation: 'a bus driver',
    appearance: {
      sex: 'male',
      age: 38,
      skinTone: 3,
      habitus: 'obese',
      hair: 'short',
      hairColor: 'darkbrown',
      eyeColor: 'brown',
      facialHair: 'beard',
      striae: true,
      umbilicus: 'deep',
    },
    persona: { mood: 'calm', style: 'chatty' },
  },
  vitals: { hr: 88, rhythm: 'regular', sbp: 148, dbp: 94, rr: 16, spo2: 95, temp: 36.6, avpu: 'A', pain: 0, bm: 9.8 },
  history: {
    opening: 'My GP sent me — I’ve tried everything to lose weight and my diabetes is getting worse. I want to talk about the surgery.',
    answers: {
      'gi.weight': 'I’m 142 kilos now — about 1.74 metres. I’ve gone up and down for years, mostly up.',
      'sh.weight': { text: 'Slimming World twice, a year with the weight-management team — dietitian, exercise, the lot — and I was on the weekly injections for eight months. I lose a stone and it comes straight back.', cue: 'shrugs' },
      'sh.diet': 'I snack a lot on shift. Takeaways after late finishes. Fizzy drinks — I’ve cut down.',
      'pmh.conditions': 'Type 2 diabetes, high blood pressure, sleep apnoea they think, and bad knees.',
      'pmh.diabetes': 'Diagnosed four years ago. Now on metformin and gliclazide, and they’ve mentioned insulin.',
      'pmh.bp': 'Yes, on amlodipine and ramipril.',
      'ros.snoring': 'My wife says I snore like a train and stop breathing. I nearly nodded off at a red light last month — it frightened me.',
      'gi.reflux': 'Terrible heartburn most nights. I sleep on three pillows and take omeprazole.',
      'gi.dysphagia': 'No.',
      'ros.joints': 'Both knees ache going up stairs.',
      'pmh.heart': 'No heart problems that I know of.',
      'pmh.clots': 'No.',
      'pmh.surgery': 'Never had an operation.',
      'pmh.anaesthetic': 'Never had one.',
      'dh.meds': 'Metformin, gliclazide, amlodipine, ramipril, omeprazole.',
      'dh.allergies': 'None.',
      'sh.smoking': 'I stopped vaping last year.',
      'sh.alcohol': 'A few beers at the weekend.',
      'sh.drugs': 'No.',
      'sh.occupation': 'I drive buses. My licence could be at risk with the sleepiness.',
      'sh.mobility': 'I get breathless on stairs. I walk the dog for twenty minutes.',
      'sh.living': 'With my wife and two kids.',
      'fh.general': 'Mum has diabetes; dad had a heart attack at 58.',
      'thy.heat': 'No.',
      'sys.fatigue': 'Tired all the time.',
      'ros.sob': 'Only on stairs or hills.',
      'comm.questions': 'Which operation would be best for me — and will it fix my diabetes?',
    },
    key: [
      'comm.open',
      'gi.weight',
      'sh.weight',
      'sh.diet',
      'pmh.conditions',
      'pmh.diabetes',
      'ros.snoring',
      'gi.reflux',
      'dh.meds',
      'dh.allergies',
      'sh.smoking',
      'sh.alcohol',
      'sh.occupation',
      'ice.expectations',
    ],
    critical: ['sh.weight', 'ros.snoring'],
    ideas: 'I think I just can’t keep it off on my own.',
    concerns: 'I’m scared of the operation — and of losing my driving licence.',
    expectations: 'I want to get my diabetes under control and be around for my kids.',
    social: { smoking: 'Stopped vaping a year ago.', alcohol: 'About 8 units at weekends.', living: 'Wife and two children.', diet: 'Snacks and takeaways on shifts.' },
    pmh: 'Type 2 diabetes, hypertension, suspected OSA, knee osteoarthritis, reflux.',
    allergies: 'None known.',
  },
  abdo: {
    general: {
      endOfBed:
        'Mr Hughes is a man with severe obesity sitting comfortably in the chair, talking easily. He is slightly breathless after walking in from the waiting room. There is velvety dark skin at the back of his neck.',
    },
    hands: { temperature: 'warm', crt: 2 },
    neck: { virchow: false, nodes: 'Acanthosis nigricans at the back of the neck and in the axillae (insulin resistance); collar size 19 inches.' },
    chest: { spiderNaevi: false, gynaecomastia: false },
    abdomen: {
      shape: 'obese',
      inspectionExtra: 'Pale striae on the flanks. No scars. No visible hernia; a deep umbilicus.',
      regions: { RUQ: r(0, 0, 'none', { note: 'dull' }) },
      liver: { edgeCm: 2, spanCm: 16, texture: 'smooth' },
      bowelSounds: 'normal',
    },
    legs: { oedema: 'ankle', calves: 'Soft, non-tender; mild bilateral pitting ankle oedema.' },
    completion: { obs: 'Weight 142 kg, height 1.74 m: BMI 46.9. Waist 132 cm. BP 148/94.', urinalysis: 'Glucose ++; protein trace.' },
  },
  investigations: {
    lipids: {
      values: [lab('Total cholesterol', '5.9', 'mmol/L', '< 5.0', 'H'), lab('LDL', '3.8', 'mmol/L', '< 3.0', 'H'), lab('Triglycerides', '3.1', 'mmol/L', '< 1.7', 'H'), lab('HbA1c', '71', 'mmol/mol', '< 42', 'H')],
      interpretation: 'Poorly controlled diabetes and dyslipidaemia.',
    },
    fbc: { values: FBC(146, 8.2, 5.1, 262), interpretation: 'Normal.' },
    ue: { values: UE(139, 4.3, 5.8, 92, '> 90'), interpretation: 'Normal renal function (baseline before surgery).' },
    lft: { values: LFT(12, 68, 104, 72, 41), interpretation: 'Raised ALT and GGT — likely fatty liver disease (MASLD).' },
    tft: { values: [lab('TSH', '2.1', 'mU/L', '0.3–4.2'), lab('Free T4', '14.6', 'pmol/L', '12–22')], interpretation: 'Euthyroid — hypothyroidism excluded.' },
    haematinics: {
      values: [lab('Ferritin', '42', 'µg/L', '30–300'), lab('Vitamin B12', '230', 'ng/L', '190–900'), lab('Folate', '4.1', 'µg/L', '> 3.9'), lab('25-OH vitamin D', '24', 'nmol/L', '> 50', 'L')],
      interpretation: 'Vitamin D deficiency; low-normal B12 (on metformin) — correct before surgery.',
    },
    'sleep-study': { report: 'STOP-BANG 7. Overnight polygraphy: apnoea–hypopnoea index 38/h with desaturation to 78%.', interpretation: 'Severe obstructive sleep apnoea — start CPAP before surgery; he must inform the DVLA and stop driving until treated.', abnormal: true },
    ogd: { report: 'Los Angeles grade B oesophagitis with a 3 cm sliding hiatus hernia. No Barrett’s. Stomach and duodenum normal; CLO test negative.', interpretation: 'Reflux disease with a hiatus hernia — favours a gastric bypass over a sleeve.', abnormal: true },
    ecg: { report: 'Sinus rhythm 86 bpm. Normal axis. No ischaemic changes.', interpretation: 'Normal.' },
    'us-abdo': { report: 'Diffusely bright liver consistent with steatosis. Gallbladder normal, no stones.', interpretation: 'Fatty liver.' },
    glucose: { values: [lab('Glucose (random)', '11.2', 'mmol/L', '4.0–7.8', 'H')] },
  },
  investigationRubric: {
    essential: [
      { id: 'lipids', why: 'HbA1c and lipids: diabetes control and cardiovascular risk.' },
      { id: 'tft', why: 'Exclude hypothyroidism as a contributor.' },
      { id: 'sleep-study', why: 'Suspected OSA must be diagnosed and treated (CPAP) before anaesthesia.' },
      { id: 'haematinics', why: 'Baseline micronutrients — deficiencies are common and worsen after surgery.' },
      { id: 'fbc', why: 'Baseline.' },
      { id: 'ue', why: 'Baseline renal function.' },
      { id: 'lft', why: 'Fatty liver disease.' },
    ],
    helpful: [
      { id: 'ogd', why: 'Reflux symptoms: oesophagitis, hiatus hernia and Barrett’s change the choice of operation.' },
      { id: 'ecg', why: 'Pre-operative cardiovascular assessment.' },
      { id: 'us-abdo', why: 'Gallstones and fatty liver.' },
    ],
    avoid: [{ id: 'ct-ap', why: 'Not needed for assessment.' }],
  },
  diagnosis: {
    correct: 'obesity',
    differentials: ['hypothyroidism', 'cushings', 'gord'],
  },
  management: {
    essential: [
      { id: 'bariatric-mdt', why: 'Surgery is decided by the bariatric MDT after medical, dietetic and psychological assessment.' },
      { id: 'cpap', why: 'Severe OSA — CPAP before surgery reduces anaesthetic risk; he must stop driving and inform the DVLA until treated.' },
      { id: 'bariatric-surgery', why: '!He qualifies (BMI ≥ 40, or ≥ 35 with comorbidity, after non-surgical measures). With reflux and diabetes, a Roux-en-Y gastric bypass is preferred over a sleeve.' },
      { id: 'lifelong-supplements', why: 'Lifelong multivitamin, iron, calcium/vitamin D and B12, and annual bloods.' },
      { id: 'lifestyle', why: 'Diet and activity changes before and after surgery decide long-term success.' },
    ],
    helpful: [
      { id: 'tier3', why: 'Already completed — the prerequisite for surgery.' },
      { id: 'statin-antiplatelet', why: 'Statin for cardiovascular risk (no antiplatelet in primary prevention).' },
      { id: 'dietitian', why: 'Pre-operative liver-shrinking diet for 2 weeks.' },
    ],
    avoid: [
      { id: 'reassure', why: 'He has severe obesity with serious comorbidities — he needs a plan.' },
      { id: 'watchful-waiting', why: 'Non-surgical measures have already failed.' },
    ],
  },
  viva: [
    {
      id: 'criteria',
      q: 'Who is eligible for bariatric surgery under NICE guidance?',
      answer: 'BMI ≥ 40, or 35–40 with a significant obesity-related disease that surgery could improve (type 2 diabetes, hypertension, OSA); non-surgical measures tried; fit for anaesthesia and surgery; committed to long-term follow-up. Expedited assessment for BMI ≥ 35 with recent-onset diabetes; lower thresholds for people of Asian family background.',
      topic: 'Indications',
    },
    {
      id: 'bmi',
      q: 'How is BMI calculated, and what are the WHO classes?',
      answer: 'Weight (kg) ÷ height (m)². 25–29.9 overweight; 30–34.9 class I; 35–39.9 class II; ≥ 40 class III obesity (Macleod’s Box 3.7). Waist circumference adds information about central fat.',
      topic: 'Assessment',
    },
    {
      id: 'which',
      q: 'Why choose a gastric bypass rather than a sleeve for this man?',
      options: ['Reflux with a hiatus hernia and type 2 diabetes', 'He is a man', 'He has knee arthritis', 'His BMI is above 45'],
      correct: 0,
      answer: 'A sleeve is a high-pressure tube that often worsens reflux, whereas a Roux-en-Y bypass treats it, and bypass gives slightly better diabetes remission. A sleeve suits someone without reflux who wants to avoid malabsorption.',
      topic: 'Operations',
    },
    {
      id: 'deficiency',
      q: 'Which deficiencies follow a gastric bypass?',
      answer: 'Iron, vitamin B12, folate, calcium and vitamin D (bone disease), thiamine (especially with vomiting — Wernicke’s), and protein malnutrition. Hence lifelong supplements and annual blood tests.',
      topic: 'Complications',
    },
  ],
  teaching: {
    summary:
      'A 38-year-old man with class III obesity (BMI 47) and type 2 diabetes, hypertension, severe obstructive sleep apnoea and reflux with a hiatus hernia, after failed specialist weight management — eligible for bariatric surgery, with a gastric bypass the better choice.',
    keyFindings: [
      'BMI 46.9, waist 132 cm, acanthosis nigricans',
      'Failed slimming groups, a year of tier 3 weight management and GLP-1 injections',
      'HbA1c 71 on two agents; hypertension; fatty liver',
      'Loud snoring, witnessed apnoeas, sleepiness at the wheel — AHI 38 (severe OSA)',
      'Nightly reflux; OGD: oesophagitis and a hiatus hernia',
    ],
    pearls: [
      'Always ask what has been tried — surgery follows, not replaces, non-surgical measures.',
      'Screen for OSA (STOP-BANG) and act on sleepiness in drivers.',
      'Reflux pushes the choice towards a bypass rather than a sleeve.',
      'Bariatric surgery is the most effective treatment for type 2 diabetes in severe obesity.',
    ],
    presentation:
      'Mr Hughes is a 38-year-old bus driver with class III obesity — weight 142 kg, BMI 47 — referred for bariatric surgery after failing commercial programmes, a year of specialist weight management and GLP-1 therapy. He has type 2 diabetes with an HbA1c of 71 on metformin and gliclazide, hypertension, fatty liver disease, knee osteoarthritis and nightly reflux. He snores with witnessed apnoeas and has nearly fallen asleep at the wheel; a sleep study shows severe OSA. On examination he has acanthosis nigricans, central obesity with striae and mild ankle oedema. OGD shows oesophagitis with a hiatus hernia. He meets NICE criteria; I would start CPAP and advise him not to drive until treated, correct his vitamin D, and refer him to the bariatric MDT with a view to a Roux-en-Y gastric bypass, with lifelong supplements and follow-up.',
    references: [
      'Macleod’s Clinical Examination, 14th ed. — Ch. 3: general examination, body mass index (Box 3.7, p. 29)',
      'NICE CG189 (updated): Obesity — identification, assessment and management',
    ],
  },
}

export default c
