import type { CaseDef } from '../../engine/types'
import { COAG, FBC, lab, LFT, r, UE, VBG } from './helpers'

const c: CaseDef = {
  id: 'bleeding-du',
  title: 'Upper GI bleed from a posterior duodenal ulcer (NSAIDs and aspirin)',
  presenting: 'Vomiting blood and black stools',
  specialty: 'Upper GI',
  exam: 'abdominal',
  difficulty: 2,
  setting: 'Emergency department',
  stem: 'Emergency department. Keith Morgan, 66, has vomited blood twice and has passed black stools. Assess and resuscitate him, take a focused history, examine him, investigate and manage him.',
  components: ['history', 'exam', 'investigations', 'diagnosis', 'viva'],
  tags: ['upper GI bleed', 'melaena', 'haematemesis', 'NSAIDs', 'Glasgow–Blatchford'],
  patient: {
    name: 'Keith Morgan',
    title: 'Mr Morgan',
    age: 66,
    sex: 'male',
    dob: '30/10/1959',
    occupation: 'a retired plumber',
    appearance: { sex: 'male', age: 66, skinTone: 2, habitus: 'overweight', hair: 'receding', hairColor: 'grey', eyeColor: 'brown', pallor: 0.55, sweaty: true, lines: { cannula: 'left-forearm', drip: true } },
    persona: { mood: 'anxious', style: 'brief' },
  },
  vitals: { hr: 114, rhythm: 'regular', sbp: 96, dbp: 58, rr: 22, spo2: 97, temp: 36.4, avpu: 'A', pain: 2 },
  history: {
    opening: { text: 'I’ve been sick twice this morning — it was blood. And my stools have been black since yesterday.', cue: 'looks pale and clammy' },
    answers: {
      'gi.vomiting': 'Twice since six this morning.',
      'gi.vomit_content': { text: 'The first time like coffee grounds, the second time bright red with clots — about a cupful.', cue: 'gestures a cup' },
      'gi.melaena': 'Yes — black, sticky and tar-like, and it smells terrible. Three times since yesterday.',
      'gi.stool_colour': 'Black.',
      'pain.site': 'A gnawing ache at the top of my stomach.',
      'gi.reflux': 'Indigestion for a few weeks, worse at night; eating helped.',
      'ros.dizzy': 'I nearly fainted getting off the toilet.',
      'ros.chest_pain': 'No chest pain.',
      'ros.sob': 'A bit breathless walking to the ambulance.',
      'gi.weight': 'No weight loss.',
      'gi.dysphagia': 'No.',
      'gi.appetite': 'Normal until today.',
      'dh.meds': 'Aspirin, naproxen for my knees, ramipril and a statin.',
      'dh.nsaids': 'Naproxen twice a day for six months for my knees.',
      'dh.anticoag': 'Aspirin — no warfarin or the newer ones.',
      'dh.steroids': 'No.',
      'dh.otc': 'Gaviscon.',
      'dh.allergies': 'None.',
      'pmh.conditions': 'Angina — I had a stent three years ago. High blood pressure. Arthritis in the knees.',
      'pmh.heart': 'A stent three years ago.',
      'pmh.gi': 'Never had an ulcer or a camera test.',
      'sh.alcohol': 'Two or three pints at the weekend.',
      'sh.smoking': 'Stopped ten years ago.',
      'comm.questions': 'Am I going to need a transfusion?',
    },
    key: [
      'comm.open',
      'gi.vomit_content',
      'gi.melaena',
      'ros.dizzy',
      'ros.chest_pain',
      'pain.site',
      'gi.reflux',
      'gi.weight',
      'dh.nsaids',
      'dh.anticoag',
      'dh.steroids',
      'pmh.conditions',
      'pmh.gi',
      'sh.alcohol',
      'dh.allergies',
    ],
    critical: ['dh.nsaids', 'dh.anticoag', 'sh.alcohol'],
    ideas: 'Maybe my stomach lining is torn from the tablets.',
    concerns: 'I’ve heard you can bleed to death from an ulcer.',
    expectations: 'Stop the bleeding.',
    social: { alcohol: 'About 8 units a week.', smoking: 'Ex-smoker.' },
    pmh: 'Ischaemic heart disease (PCI 3 years ago), hypertension, knee osteoarthritis.',
  },
  abdo: {
    general: {
      endOfBed:
        'Mr Morgan is pale, sweaty and anxious, lying flat. There is a vomit bowl containing dark blood and clots. One cannula is in the left forearm with fluids running.',
    },
    hands: { temperature: 'cool', crt: 4, pallorCreases: true, pulseVolume: 'weak' },
    face: { conjunctiva: 'pale', mucosa: 'dry' },
    chest: { spiderNaevi: false, gynaecomastia: false },
    abdomen: {
      shape: 'flat',
      regions: { EPI: r(1, 2) },
      bowelSounds: 'hyperactive',
      liver: { edgeCm: 0, spanCm: 11 },
      spleen: { tipCm: 0 },
      shiftingDullness: false,
    },
    completion: { dre: 'Black, tarry, offensive stool on the glove — melaena.', obs: 'Postural drop: SBP falls to 78 on sitting up.' },
  },
  criticalSteps: ['gen.obs', 'end.completion'],
  investigations: {
    fbc: { values: FBC(78, 12.1, 9.8, 312, 86), interpretation: 'Acute anaemia (Hb may underestimate the loss early).' },
    ue: { values: UE(138, 4.8, 18.6, 102, '68'), interpretation: 'Urea raised out of proportion to creatinine — digested blood in the gut.' },
    lft: { values: LFT(12, 24, 82, 38, 36), interpretation: 'Normal — no liver disease.' },
    coag: { values: COAG(12, 1.1, 30), interpretation: 'Normal.' },
    xm: { report: '4 units crossmatched.' },
    gs: { report: 'Group A RhD positive.' },
    vbg: { values: VBG(7.34, 21, -3.8, 2.8), interpretation: 'Raised lactate — hypoperfusion.' },
    ecg: { report: 'Sinus tachycardia 114 bpm; old inferior Q waves; no acute ST change.', interpretation: 'No acute ischaemia (demand ischaemia is a risk).' },
    troponin: { values: [lab('hs-Troponin T', 16, 'ng/L', '< 14', 'H')], interpretation: 'Slightly raised — demand; repeat.' },
    ogd: {
      report: 'Fresh and altered blood in the stomach. A 15 mm ulcer on the posterior wall of the duodenal bulb with a non-bleeding visible vessel (Forrest IIa). Treated with adrenaline injection and two haemostatic clips. CLO test positive.',
      interpretation: 'High-risk posterior duodenal ulcer, endoscopic haemostasis achieved; H. pylori positive.',
      abnormal: true,
    },
    'cxr-erect': { report: 'No free gas. Normal.' },
  },
  investigationRubric: {
    essential: [
      { id: 'fbc', why: 'Haemoglobin (repeat — it lags behind the bleed).' },
      { id: 'ue', why: 'Urea for the Glasgow–Blatchford score.' },
      { id: 'coag', why: 'Correct any coagulopathy.' },
      { id: 'xm', why: 'Active bleeding with shock — crossmatch.' },
      { id: 'lft', why: 'Liver disease changes management (varices).' },
      { id: 'ogd', why: 'Within 24 hours — immediately after resuscitation in an unstable patient — to diagnose and treat.' },
    ],
    helpful: [
      { id: 'vbg', why: 'Lactate and Hb at the bedside.' },
      { id: 'ecg', why: 'Cardiac history and shock.' },
      { id: 'troponin', why: 'Demand ischaemia.' },
      { id: 'gs', why: 'Covered by the crossmatch.' },
    ],
    avoid: [{ id: 'ct-ap', why: 'Endoscopy, not CT, is the first test for upper GI bleeding (CT angiography only if endoscopy fails).' }],
  },
  diagnosis: {
    correct: 'bleeding-pu',
    accept: ['peptic-ulcer'],
    differentials: ['variceal-bleed', 'mallory-weiss', 'gastritis', 'gastric-cancer', 'oesophageal-cancer'],
  },
  management: {
    essential: [
      { id: 'abcde', why: 'Shocked: HR 114, SBP 96, postural drop.' },
      { id: 'iv-access', why: 'Two large-bore cannulae.' },
      { id: 'fluids', why: 'Crystalloid while blood is coming.' },
      { id: 'transfusion', why: 'Hb 78 with active bleeding and ischaemic heart disease — transfuse (restrictive target ~70–80 g/L is the default, but treat the shock).' },
      { id: 'nbm', why: 'Endoscopy.' },
      { id: 'catheter', why: 'Urine output.' },
      { id: 'senior', why: 'Gastroenterology/surgical registrar; GBS 13.' },
      { id: 'ogd-haemostasis', why: '!Urgent OGD with dual endoscopic therapy (adrenaline plus clips or thermal) for a high-risk ulcer.' },
      { id: 'ppi-iv', why: 'High-dose PPI after successful endoscopic haemostasis (not before endoscopy, per NICE).' },
      { id: 'hold-anticoag', why: 'Stop naproxen for good; hold aspirin briefly and restart it soon after haemostasis because of his stent (discuss with cardiology).' },
      { id: 'h-pylori', why: 'CLO-positive — eradication therapy reduces rebleeding.' },
    ],
    helpful: [
      { id: 'o2', why: 'If saturations fall.' },
      { id: 'ir-embolisation', why: 'If rebleeding after repeat endoscopy — then surgery if that fails.' },
      { id: 'fluid-balance', why: 'Strict input and output.' },
    ],
    avoid: [
      { id: 'nsaid', why: 'Caused the ulcer.' },
      { id: 'discharge', why: 'GBS 13 — high risk.' },
      { id: 'terlipressin', why: 'For variceal bleeding — no evidence of liver disease here.' },
    ],
  },
  viva: [
    {
      id: 'gbs',
      q: 'What does the Glasgow–Blatchford score use, and what is it for?',
      answer: 'Urea, haemoglobin, systolic BP, pulse, melaena, syncope, liver disease and heart failure. It is calculated before endoscopy: a score of 0–1 identifies patients who may be managed as outpatients; higher scores need admission and endoscopy. The Rockall score (with endoscopy findings) predicts rebleeding and mortality.',
      topic: 'Scores',
    },
    {
      id: 'urea',
      q: 'Why is the urea disproportionately high in an upper GI bleed?',
      options: ['Blood proteins are digested and absorbed as urea', 'Acute kidney failure always occurs', 'The liver makes extra urea in shock', 'It is a laboratory artefact'],
      correct: 0,
      answer: 'Blood in the upper gut is digested; the absorbed protein raises urea, while creatinine stays relatively normal. Hypovolaemia adds a pre-renal component.',
      topic: 'Interpretation',
    },
    {
      id: 'forrest',
      q: 'What is the Forrest classification?',
      answer: 'Endoscopic stigmata of ulcer bleeding: Ia spurting, Ib oozing, IIa non-bleeding visible vessel, IIb adherent clot, IIc flat pigmented spot, III clean base. Ia–IIa (± IIb) need endoscopic therapy because of the rebleeding risk.',
      topic: 'Endoscopy',
    },
    {
      id: 'posterior',
      q: 'Why are posterior duodenal ulcers dangerous?',
      answer: 'They can erode the gastroduodenal artery, which runs behind the first part of the duodenum, causing major haemorrhage. Anterior ulcers tend to perforate instead.',
      topic: 'Anatomy',
    },
  ],
  teaching: {
    summary:
      'Upper GI bleed from a posterior duodenal ulcer in a 66-year-old on naproxen and aspirin: coffee-ground then fresh haematemesis, melaena, near-syncope, tachycardia and hypotension, Hb 78 with a disproportionately raised urea (GBS 13); OGD shows a visible vessel treated with adrenaline and clips; H. pylori positive.',
    keyFindings: [
      'Haematemesis (coffee grounds then fresh blood) and melaena; near-syncope',
      'Naproxen twice daily for 6 months plus aspirin; weeks of epigastric pain',
      'HR 114, BP 96/58, postural drop, cool and pale; melaena on DRE',
      'Hb 78, urea 18.6 with normal creatinine; normal LFTs and clotting',
      'OGD: posterior DU with a non-bleeding visible vessel (Forrest IIa)',
    ],
    pearls: [
      'Resuscitate first; calculate the Glasgow–Blatchford score before endoscopy.',
      'A raised urea with normal creatinine points to an upper GI source.',
      'Always ask about NSAIDs, aspirin, anticoagulants, steroids, SSRIs and alcohol.',
      'Look for stigmata of liver disease: varices change the whole management.',
    ],
    presentation:
      'Mr Morgan is a 66-year-old man with ischaemic heart disease and a coronary stent who presents with two episodes of haematemesis — first coffee grounds, then fresh blood — and black, tarry stools since yesterday, with near-syncope. He has had epigastric pain for weeks and takes naproxen twice daily and aspirin. He is pale and sweaty with a pulse of 114, BP 96/58 and a postural drop; the abdomen is soft with mild epigastric tenderness and DRE confirms melaena. There are no signs of chronic liver disease. Hb is 78, urea 18.6 with normal creatinine, and the Glasgow–Blatchford score is 13. I would resuscitate him with two large-bore cannulae, fluids and blood, keep him nil by mouth and arrange urgent OGD, which showed a posterior duodenal ulcer with a visible vessel treated with adrenaline and clips; then IV PPI, stop naproxen, eradicate H. pylori and restart aspirin early after discussion with cardiology.',
    references: ['Macleod’s Clinical Examination, 14th ed. — Ch. 6: gastrointestinal bleeding; Ch. 18: the shocked patient', 'NICE CG141: Acute upper gastrointestinal bleeding'],
  },
}

export default c
