import type { CaseDef } from '../../engine/types'

const c: CaseDef = {
  id: 'breast-cancer',
  title: 'Invasive carcinoma of the left breast with axillary node involvement',
  presenting: 'Lump in the left breast',
  specialty: 'Breast',
  exam: 'breast',
  difficulty: 2,
  setting: 'Outpatient clinic',
  stem: 'One-stop breast clinic (urgent suspected-cancer referral). Janet Morris, 64, has a lump in her left breast. Take a history, examine her breasts with a chaperone, request investigations and outline the next steps.',
  components: ['history', 'exam', 'investigations', 'diagnosis', 'viva'],
  tags: ['breast lump', 'tethering', 'triple assessment', '2WW'],
  patient: {
    name: 'Janet Morris',
    title: 'Mrs Morris',
    age: 64,
    sex: 'female',
    dob: '12/05/1962',
    occupation: 'a retired nurse',
    appearance: { sex: 'female', age: 64, skinTone: 1, habitus: 'overweight', hair: 'short', hairColor: 'grey', eyeColor: 'hazel', glasses: true },
    persona: { mood: 'anxious', style: 'normal' },
  },
  vitals: { hr: 82, rhythm: 'regular', sbp: 142, dbp: 86, rr: 15, spo2: 98, temp: 36.5, avpu: 'A', pain: 0 },
  visual: { breast: { lump: { side: 'left', clock: 2, distCm: 3.5, sizeCm: 3, visible: true, tethered: true }, nipple: { side: 'left', change: 'retracted' }, nodes: 'left' } },
  history: {
    opening: 'I found a hard lump in my left breast, and I think my nipple on that side looks different.',
    answers: {
      'lump.when': 'About two months ago, but I put off coming.',
      'lump.change': 'I think it’s got bigger.',
      'lump.pain': 'It doesn’t hurt.',
      'lump.other': 'I think there might be something in my left armpit too.',
      'br.nipple_change': 'The left nipple has started pulling in, over the last few weeks.',
      'br.nipple_discharge': 'No discharge.',
      'br.skin': 'There’s a little dimple above the nipple when I lift my arm.',
      'br.menarche': 'Eleven.',
      'br.menopause': 'At fifty-four.',
      'br.hormones': 'I took HRT for about eight years after the menopause.',
      'br.children': 'One son — I had him at thirty-six. I didn’t breastfeed.',
      'br.fh': 'My sister had breast cancer at fifty-eight.',
      'br.screening': 'I missed my last screening mammogram — it would have been two years ago.',
      'gi.weight': 'No weight loss.',
      'ros.joints': 'My back’s fine — no new pains.',
      'ros.sob': 'No shortness of breath.',
      'gi.jaundice': 'No.',
      'pmh.conditions': 'High blood pressure.',
      'dh.meds': 'Ramipril.',
      'dh.allergies': 'No allergies.',
      'sh.alcohol': 'A glass or two of wine most evenings.',
      'sh.smoking': 'I’ve never smoked.',
      'comm.questions': 'It’s cancer, isn’t it? Will I lose my breast?',
    },
    key: [
      'comm.open',
      'lump.when',
      'lump.change',
      'lump.pain',
      'lump.other',
      'br.nipple_change',
      'br.nipple_discharge',
      'br.skin',
      'br.menopause',
      'br.hormones',
      'br.fh',
      'br.screening',
      'gi.weight',
      'ros.joints',
      'ros.sob',
    ],
    critical: ['br.fh', 'br.nipple_change'],
    ideas: 'I was a nurse — I know what a hard lump like this can mean.',
    concerns: 'That it has spread, and that I’ll lose my breast.',
    expectations: 'To be straight with me.',
  },
  keyed: {
    'comm.pain': { text: '', says: 'No, it doesn’t hurt.' },
    'br.inspectSide': {
      text: 'The left breast contour is subtly flattened in the upper outer quadrant, and the left nipple is retracted towards 2 o’clock. No peau d’orange, erythema or ulceration. No scars.',
      abnormal: true,
      meaning: 'Recent nipple retraction and contour change are red flags.',
    },
    'br.inspectHips': { text: 'With the pectorals tensed, skin dimpling appears over the upper outer quadrant of the left breast.', abnormal: true, meaning: 'Tethering — the tumour is pulling on the suspensory (Cooper’s) ligaments.' },
    'br.inspectUp': { text: 'With the arms raised the dimpling becomes more obvious, and the left nipple is drawn upwards and outwards.', abnormal: true },
    'br.palpNormal': { text: 'The right breast is normal with no discrete lump.' },
    'br.palpAffected': { text: 'In the upper outer quadrant of the left breast there is a hard, irregular lump.', abnormal: true },
    'br.lump': {
      text: 'Left breast, 2 o’clock, 3.5 cm from the nipple: a 3 cm hard, irregular, ill-defined, non-tender lump. It is tethered to the overlying skin.',
      abnormal: true,
      meaning: 'Hard, irregular, ill-defined and tethered → carcinoma until proven otherwise.',
    },
    'br.fixity': { text: 'The lump moves with the pectorals relaxed and still moves (less freely) with them tensed — tethered to skin but not fixed to pectoralis major.', abnormal: true, meaning: 'Not fixed to the chest wall (would suggest T4 disease).' },
    'br.nipple': { text: 'The left nipple is retracted; no discharge can be expressed.', abnormal: true },
    'br.axillaR': { text: 'No palpable right axillary nodes.' },
    'br.axillaL': { text: 'A single firm, mobile 1.5 cm lymph node in the left axilla (central group).', abnormal: true, meaning: 'Palpable ipsilateral axillary node — likely nodal spread; needs ultrasound ± biopsy.' },
    'br.scf': { text: 'No supraclavicular or cervical lymphadenopathy.' },
    'complete.triple': { text: 'Triple assessment: clinical, imaging (mammography + ultrasound, including the axilla) and core biopsy of the lump and node.' },
    'complete.spine': { text: 'No spinal tenderness, no hepatomegaly, chest clear.' },
  },
  criticalSteps: ['prep.chaperone', 'in.hips', 'ln.axilla'],
  investigations: {
    mammo: { report: 'Left upper outer quadrant: 28 mm irregular spiculated mass with associated architectural distortion and nipple retraction (M5).', interpretation: 'Highly suspicious of malignancy (M5).', abnormal: true },
    'us-breast': { report: 'Left breast 2 o’clock, 35 mm from the nipple: 26 mm irregular, hypoechoic, taller-than-wide mass with posterior acoustic shadowing (U5). Left axilla: one abnormal node with a thickened cortex (15 mm).', interpretation: 'Malignant appearance (U5) with an abnormal axillary node.', abnormal: true },
    core: { report: 'Invasive carcinoma of no special type (ductal), grade 2 (B5b). ER positive (Allred 8/8), PR positive, HER2 negative. Axillary node core: metastatic carcinoma.', interpretation: 'Invasive breast cancer, hormone-receptor positive, HER2 negative, node positive.', abnormal: true },
  },
  investigationRubric: {
    essential: [
      { id: 'mammo', why: '!Mammography (with ultrasound) at 40 and over.' },
      { id: 'us-breast', why: 'Characterises the lump and assesses the axilla.' },
      { id: 'core', why: '!Histology with receptor status (ER/PR/HER2) guides treatment.' },
    ],
    helpful: [{ id: 'fbc', why: 'Baseline.' }, { id: 'lft', why: 'Baseline; raised ALP/transaminases may suggest metastases.' }],
    avoid: [{ id: 'ct-cap', why: 'Staging CT is not routine for early breast cancer without symptoms or high-risk features — decided at MDT.' }],
  },
  diagnosis: { correct: 'breast-cancer', differentials: ['fat-necrosis', 'phyllodes', 'breast-cyst', 'breast-abscess'] },
  management: {
    essential: [
      { id: 'triple-assessment', why: '!Same-day triple assessment in the one-stop clinic.' },
      { id: '2ww', why: 'Urgent suspected-cancer pathway.' },
      { id: 'mdt', why: 'All results discussed at the breast MDT to plan treatment.' },
      { id: 'breaking-news', why: 'Break bad news honestly and compassionately with a breast care nurse present.' },
    ],
    helpful: [{ id: 'excision', why: 'Surgery (wide local excision or mastectomy with axillary surgery) is the likely mainstay — after MDT.' }],
    avoid: [{ id: 'reassure', why: '!False reassurance is dangerous — this lump has malignant features.' }],
  },
  viva: [
    {
      id: 'tether-fix',
      q: 'What is the difference between tethering and fixity of a breast lump?',
      answer: 'Tethering: the lump is attached to the skin via Cooper’s ligaments — the skin dimples when the lump is moved or the arms are raised/pectorals tensed, but the lump can still move. Fixity: the lump cannot be moved independently of a structure — fixed to skin (skin moves with it, may ulcerate) or fixed to pectoralis major/chest wall (immobile when the muscle is tensed), implying locally advanced disease.',
      topic: 'Examination',
    },
    {
      id: 'receptors',
      q: 'Her tumour is ER-positive, HER2-negative and she is postmenopausal. Which adjuvant endocrine therapy is usually used?',
      options: ['Tamoxifen only in premenopausal women; aromatase inhibitor (e.g. letrozole/anastrozole) in postmenopausal women', 'Trastuzumab (Herceptin)', 'No endocrine therapy', 'Carbimazole'],
      correct: 0,
      answer: 'Postmenopausal ER-positive breast cancer is usually treated with an aromatase inhibitor (letrozole, anastrozole, exemestane) for 5+ years; tamoxifen is used premenopausally. Trastuzumab targets HER2-positive disease. Watch bone health (DEXA) on aromatase inhibitors.',
      topic: 'Treatment',
    },
    {
      id: 'risk',
      q: 'List risk factors for breast cancer from her history.',
      answer: 'Age, a first-degree relative with breast cancer, prolonged oestrogen exposure (early menarche at 11, late menopause, late first pregnancy at 36, no breastfeeding), HRT use for 8 years, alcohol intake, and being overweight. (BRCA1/2 or other gene carriage should be considered with a strong family history.)',
      topic: 'Risk',
    },
    {
      id: 'lymph',
      q: 'Name the axillary lymph node groups you palpate.',
      answer: 'Anterior (pectoral), posterior (subscapular), lateral (humeral), central and apical — plus the supraclavicular nodes. Support the patient’s arm so the axillary muscles relax, and palpate against the chest wall.',
      topic: 'Anatomy',
    },
  ],
  teaching: {
    summary:
      'A postmenopausal woman with a hard, irregular, tethered upper-outer-quadrant lump, nipple retraction and a palpable ipsilateral axillary node — invasive breast cancer, confirmed on triple assessment (M5, U5, B5b; ER+/HER2−; node positive).',
    keyFindings: ['Left UOQ, 2 o’clock, 3.5 cm from nipple, 3 cm', 'Hard, irregular, ill-defined, tethered to skin', 'Dimpling accentuated with hands on hips and arms raised', 'Nipple retraction; 1.5 cm mobile left axillary node'],
    pearls: [
      'Inspect in three positions — tethering may only appear when the pectorals are tensed or the arms raised.',
      'Examine the normal breast first and palpate every quadrant plus the axillary tail.',
      'Support the arm when examining the axilla, and always check the supraclavicular fossae.',
      'Offer a chaperone and document it (GMC).',
    ],
    presentation:
      'I examined Mrs Janet Morris, a 64-year-old woman, with a chaperone present. On inspection there is flattening of the contour of the left upper outer quadrant with retraction of the left nipple, and skin dimpling that becomes apparent with the pectorals tensed and the arms raised. The right breast is normal. In the left breast at 2 o’clock, 3.5 cm from the nipple, there is a 3 cm hard, irregular, ill-defined, non-tender lump tethered to the skin but not fixed to pectoralis major. There is a firm, mobile 1.5 cm left axillary lymph node, with no supraclavicular lymphadenopathy. These features are highly suspicious of left breast carcinoma with axillary nodal involvement. She needs urgent triple assessment with mammography, ultrasound of the breast and axilla, and core biopsy, followed by MDT discussion.',
    references: ['Macleod’s Clinical Examination, 14th ed. — Ch. 13: The breasts', 'NICE NG101: Early and locally advanced breast cancer', 'NICE NG12: Suspected cancer — breast'],
  },
}

export default c
