import type { CaseDef } from '../../engine/types'
import { CRP, FBC, lab, LFT, r, UE } from './helpers'

const c: CaseDef = {
  id: 'cholecystitis',
  title: 'Acute calculous cholecystitis',
  presenting: 'Right upper quadrant pain and fever',
  specialty: 'Hepatobiliary',
  exam: 'abdominal',
  difficulty: 1,
  setting: 'Surgical assessment unit',
  stem: 'Sandra Hughes, 46, has been sent to the surgical assessment unit by her GP with upper abdominal pain. Take a history, examine her abdomen, request investigations and outline your plan.',
  components: ['history', 'exam', 'investigations', 'diagnosis', 'viva'],
  tags: ['RUQ pain', 'gallstones', 'Murphy', 'Tokyo guidelines'],
  patient: {
    name: 'Sandra Hughes',
    title: 'Mrs Hughes',
    age: 46,
    sex: 'female',
    dob: '02/11/1979',
    occupation: 'an office manager',
    appearance: {
      sex: 'female',
      age: 46,
      skinTone: 2,
      habitus: 'overweight',
      hair: 'bob',
      hairColor: 'brown',
      eyeColor: 'blue',
      flushed: 0.4,
      scars: ['pfannenstiel'],
      lines: { cannula: 'right-forearm', drip: true },
    },
    persona: { mood: 'anxious', style: 'chatty' },
  },
  vitals: { hr: 98, rhythm: 'regular', sbp: 134, dbp: 82, rr: 18, spo2: 97, temp: 38.3, avpu: 'A', pain: 7 },
  bedside: { drip: true, vomitBowl: 'empty' },
  history: {
    opening: {
      text: 'I’ve got this terrible pain under my ribs on the right. It started after dinner the night before last and it just won’t go away this time.',
      cue: 'presses her hand under her right ribs',
    },
    answers: {
      'pain.site': { text: 'Here, just under my ribs on the right.', cue: 'points to the right upper quadrant' },
      'pain.onset': 'About a day and a half ago, a couple of hours after a big takeaway. It built up over an hour or so.',
      'pain.character': 'A constant, gnawing ache. Before, the attacks used to come in waves.',
      'pain.radiation': 'It goes round to my back — up under my right shoulder blade.',
      'pain.moved': 'No, it’s always been under my ribs on the right.',
      'pain.timing': 'It’s been constant since it started.',
      'pain.exacerbating': 'Taking a deep breath, moving, and the car journey here — every bump.',
      'pain.relieving': 'Nothing really helps it this time.',
      'pain.severity': 'Seven, maybe eight out of ten.',
      'pain.previous': 'I’ve had four or five attacks like this over the last year, always after fatty food — but they went away in a couple of hours. This one hasn’t.',
      'pain.analgesia_taken': 'Paracetamol and ibuprofen. They took the edge off for a bit.',
      'gi.nausea': 'Yes, horribly nauseous.',
      'gi.vomiting': 'I was sick three times yesterday.',
      'gi.vomit_content': 'Just bitter, yellowish stuff. No blood.',
      'gi.appetite': 'I can’t face food at all.',
      'gi.bowels_last': 'Yesterday morning, normal.',
      'gi.jaundice': 'No, I don’t think so — my husband hasn’t said anything.',
      'gi.dark_urine': 'No, it looks normal.',
      'gi.stool_colour': 'No, normal colour.',
      'gi.itch': 'No.',
      'sys.fever': 'I’ve been hot and shivery since last night.',
      'sys.rigors': 'Shivery, but not proper uncontrollable shaking.',
      'gyn.lmp': 'About three weeks ago. They’re regular.',
      'gyn.pregnant': 'No — I had my tubes tied after my second baby.',
      'gyn.contraception': 'I had a sterilisation, so nothing else.',
      'pmh.conditions': 'High blood pressure. That’s it.',
      'pmh.surgery': 'Two caesareans, and the sterilisation at the second one.',
      'pmh.gi': 'The doctor said last year it might be gallstones, but I never had the scan.',
      'dh.meds': 'Amlodipine five milligrams once a day.',
      'fh.general': 'My mum had her gallbladder out in her fifties.',
      'sh.alcohol': 'A glass or two of wine at the weekend.',
      'sh.living': 'With my husband and our two kids — they’re eleven and eight.',
      'pre.last_meal': 'A few sips of water this morning. Nothing to eat since yesterday lunchtime.',
      'comm.questions': 'Is it my gallbladder? Will I need it out?',
    },
    key: [
      'comm.open',
      'pain.site',
      'pain.onset',
      'pain.character',
      'pain.radiation',
      'pain.previous',
      'pain.exacerbating',
      'pain.severity',
      'gi.nausea',
      'gi.vomiting',
      'sys.fever',
      'gi.jaundice',
      'gi.dark_urine',
      'gi.stool_colour',
      'gyn.lmp',
      'gyn.pregnant',
      'pmh.conditions',
      'dh.meds',
      'dh.allergies',
      'sh.alcohol',
    ],
    critical: ['gyn.pregnant'],
    ideas: 'I wondered if it’s my gallbladder — my mum had exactly the same thing.',
    concerns: 'I’ve got two kids at home. I can’t be stuck in hospital for long.',
    expectations: 'I want it sorted properly this time so it doesn’t keep coming back.',
    pmh: 'High blood pressure.',
    psh: 'Two caesarean sections.',
    meds: 'Amlodipine 5 mg once daily.',
  },
  abdo: {
    general: {
      endOfBed:
        'Mrs Hughes is lying still, propped up on two pillows, looking flushed and unwell. She catches her breath when she breathes in deeply. There is a cannula in her right forearm with IV fluids running and an empty sick bowl on the locker. She does not look jaundiced.',
      lyingStill: true,
    },
    hands: { temperature: 'hot' },
    face: { mucosa: 'dry', tongue: 'dry-furred' },
    abdomen: {
      coughPain: true,
      regions: {
        RUQ: r(2, 3, 'voluntary', { percussionTender: true }),
        EPI: r(1, 1),
        RF: r(0, 1),
      },
      gallbladder: { palpable: false, murphy: true },
    },
    completion: {
      urinalysis: 'Ketones +; otherwise negative.',
      pregnancy: 'Urine β-hCG: negative.',
    },
  },
  criticalSteps: ['org.gb', 'end.pregnancy'],
  investigations: {
    fbc: { values: FBC(134, 15.6, 12.9, 312, 87, 'female'), interpretation: 'Neutrophil leucocytosis.' },
    crp: { values: CRP(142), interpretation: 'Marked inflammatory response.' },
    lft: { values: LFT(19, 58, 162, 98, 38), interpretation: 'Mildly raised ALP/GGT/ALT with a normal bilirubin — common in acute cholecystitis (local inflammation, oedema). Consider MRCP if they rise or the duct is dilated.' },
    amylase: { values: [lab('Amylase', 64, 'U/L', '30–110'), lab('Lipase', 41, 'U/L', '< 60')], interpretation: 'Normal — makes gallstone pancreatitis unlikely.' },
    ue: { values: UE(137, 3.9, 6.2, 71, '> 90', 'female'), interpretation: 'Normal renal function.' },
    'urine-hcg': { report: 'Negative.', interpretation: 'Not pregnant.' },
    'us-abdo': {
      report:
        'Distended gallbladder with a thickened oedematous wall (5 mm), pericholecystic fluid and multiple mobile calculi, the largest 18 mm, with one impacted in the neck. Positive sonographic Murphy’s sign. Common bile duct 5 mm (not dilated). Liver and pancreas normal.',
      interpretation: 'Acute calculous cholecystitis. No duct dilatation.',
      abnormal: true,
    },
    mrcp: { report: 'Gallstones within the gallbladder. Normal-calibre common bile duct with no filling defect.', interpretation: 'No choledocholithiasis.' },
    ecg: { report: 'Sinus rhythm, rate 96. No ST-segment changes.', interpretation: 'Normal — an inferior MI can mimic upper abdominal pain.' },
    'cxr-erect': { report: 'Clear lungs. No free subdiaphragmatic gas.', interpretation: 'No right lower lobe pneumonia or perforation.' },
    cultures: { report: 'Sent before antibiotics. No growth at 48 hours.' },
    'ct-ap': { report: 'Distended gallbladder with wall thickening and pericholecystic stranding in keeping with acute cholecystitis. No perforation or abscess.', interpretation: 'Consistent with acute cholecystitis — but ultrasound is first-line.', abnormal: true },
  },
  investigationRubric: {
    essential: [
      { id: 'fbc', why: 'WCC is part of the Tokyo criteria (systemic inflammation).' },
      { id: 'crp', why: 'Raised CRP supports inflammation (Tokyo criterion B).' },
      { id: 'lft', why: 'Deranged LFTs or jaundice raise suspicion of CBD stones or cholangitis.' },
      { id: 'amylase', why: 'Exclude gallstone pancreatitis.' },
      { id: 'us-abdo', why: 'First-line imaging: stones, wall thickening, pericholecystic fluid, duct size.' },
      { id: 'urine-hcg', why: 'Pregnancy test for every woman of reproductive age (even if sterilised).' },
    ],
    helpful: [
      { id: 'ue', why: 'Baseline before fluids and theatre.' },
      { id: 'ecg', why: 'Exclude an inferior MI presenting with epigastric/RUQ pain.' },
      { id: 'cultures', why: 'She is febrile — take cultures before antibiotics.' },
      { id: 'gs', why: 'Pre-operative.' },
      { id: 'mrcp', why: 'NICE: consider MRCP if LFTs are abnormal even when the duct is not dilated.' },
    ],
    avoid: [{ id: 'ercp', why: 'ERCP is for proven common bile duct stones or cholangitis — it carries a risk of pancreatitis.' }],
  },
  diagnosis: {
    correct: 'cholecystitis',
    differentials: ['biliary-colic', 'cholangitis', 'pancreatitis', 'peptic-ulcer', 'lower-lobe-pneumonia', 'mi'],
  },
  management: {
    essential: [
      { id: 'analgesia', why: 'Adequate analgesia.' },
      { id: 'abx-iv', why: 'IV antibiotics for acute cholecystitis (per local guidelines).' },
      { id: 'fluids', why: 'Febrile, vomiting and dry.' },
      { id: 'senior', why: 'Discuss with the registrar.' },
      { id: 'lap-chole-early', why: '!NICE CG188: offer laparoscopic cholecystectomy within 1 week of diagnosis.' },
    ],
    helpful: [
      { id: 'antiemetic', why: 'Nausea and vomiting.' },
      { id: 'nbm', why: 'Nil by mouth initially if surgery is likely soon.' },
      { id: 'vte', why: 'VTE risk assessment and prophylaxis.' },
      { id: 'consent', why: 'Consent for laparoscopic cholecystectomy.' },
    ],
    avoid: [
      { id: 'discharge', why: 'She is septic with acute cholecystitis — admit.' },
      { id: 'lap-chole-interval', why: 'NICE recommends early surgery; delaying to 6 weeks risks recurrent attacks and readmission.' },
      { id: 'ercp', why: 'No evidence of CBD stones or cholangitis.' },
    ],
  },
  viva: [
    {
      id: 'murphy',
      q: 'What is Murphy’s sign?',
      options: [
        'Arrest of inspiration on palpation at the tip of the right 9th costal cartilage, absent on the left',
        'Pain in the RIF on palpation of the LIF',
        'Periumbilical bruising',
        'A palpable gallbladder in a jaundiced patient',
      ],
      correct: 0,
      answer: 'The patient stops breathing in abruptly as the inflamed gallbladder descends onto the examining fingers at the tip of the right 9th costal cartilage. It must be absent on the left side to be valid.',
      topic: 'Signs',
    },
    {
      id: 'nice-timing',
      q: 'According to NICE (CG188), when should laparoscopic cholecystectomy be offered for acute cholecystitis?',
      options: ['Within 1 week of diagnosis', 'After 6 weeks, once inflammation has settled', 'Only after a second attack', 'Only if the gallbladder perforates'],
      correct: 0,
      answer: 'Offer laparoscopic cholecystectomy within 1 week of diagnosis of acute cholecystitis. If the patient is too unwell, percutaneous cholecystostomy is an option; surgery can follow later.',
      topic: 'Guidelines',
    },
    {
      id: 'spectrum',
      q: 'Distinguish biliary colic, acute cholecystitis and ascending cholangitis.',
      answer:
        'Biliary colic: transient obstruction of the cystic duct — RUQ/epigastric pain < 6 h, no fever, normal bloods. Acute cholecystitis: persistent obstruction with gallbladder wall inflammation — constant pain > 6 h, fever, Murphy’s sign, raised WCC/CRP. Ascending cholangitis: infection of an obstructed common bile duct — Charcot’s triad (fever/rigors, jaundice, RUQ pain), deranged cholestatic LFTs; needs urgent biliary drainage.',
      topic: 'Reasoning',
    },
    {
      id: 'tokyo',
      q: 'What are the Tokyo (TG18) diagnostic criteria for acute cholecystitis?',
      answer:
        'A — local inflammation: Murphy’s sign, RUQ mass/pain/tenderness. B — systemic inflammation: fever, raised CRP, raised WCC. C — characteristic imaging findings. Suspected diagnosis = one of A + one of B; definite = A + B + C. Severity is graded I (mild) to III (organ dysfunction).',
      topic: 'Classification',
    },
    {
      id: 'charcot',
      q: 'Which feature would suggest ascending cholangitis rather than cholecystitis?',
      options: ['Jaundice with fever and RUQ pain', 'A positive Murphy’s sign', 'Pain radiating to the right shoulder', 'Vomiting'],
      correct: 0,
      answer: 'Charcot’s triad — fever (often with rigors), jaundice and RUQ pain. Add hypotension and confusion for Reynolds’ pentad (severe, suppurative cholangitis).',
      topic: 'Reasoning',
    },
    {
      id: 'complications',
      q: 'List complications of acute cholecystitis.',
      answer: 'Empyema, gangrene, perforation (pericholecystic abscess or biliary peritonitis), cholecystoenteric fistula with gallstone ileus, Mirizzi syndrome, sepsis; also CBD stones → cholangitis or pancreatitis.',
      topic: 'Complications',
    },
  ],
  teaching: {
    summary:
      'Acute calculous cholecystitis: > 6 h of constant RUQ pain radiating to the right scapula after previous episodes of biliary colic, with fever, RUQ tenderness and a positive Murphy’s sign, raised inflammatory markers and ultrasound evidence of an inflamed stone-filled gallbladder.',
    keyFindings: [
      'Previous self-limiting post-prandial attacks (biliary colic) — now constant pain > 36 h',
      'Fever 38.3 °C, tachycardia, WCC 15.6, CRP 142',
      'RUQ tenderness with guarding and a positive Murphy’s sign (negative on the left)',
      'Not jaundiced; CBD not dilated — cholangitis unlikely',
      'US: thick-walled gallbladder, pericholecystic fluid, impacted stone',
    ],
    pearls: [
      'Always compare Murphy’s manoeuvre on the left — a true positive is one-sided.',
      'A woman who has been sterilised still needs a pregnancy test.',
      'Ultrasound, not CT, is the first-line investigation for suspected gallbladder disease.',
      'Upper abdominal pain: remember inferior MI and right lower lobe pneumonia — ECG and CXR.',
      'NICE: early laparoscopic cholecystectomy (within 1 week) is safer and cheaper than interval surgery.',
    ],
    presentation:
      'Mrs Hughes is a 46-year-old woman with 36 hours of constant right upper quadrant pain radiating to the right scapula, with nausea, vomiting and fever, on a background of recurrent post-prandial biliary-type pain. She is hypertensive, has had two caesarean sections, and is sterilised. On examination she is febrile (38.3 °C) and mildly tachycardic, not jaundiced, with right upper quadrant tenderness, voluntary guarding and a positive Murphy’s sign that is absent on the left. Her WCC is 15.6 and CRP 142 with mildly raised ALP and ALT, a normal bilirubin and normal amylase; pregnancy test is negative. Ultrasound shows a thick-walled gallbladder with pericholecystic fluid and gallstones, and a normal-calibre bile duct. This is acute calculous cholecystitis (Tokyo grade I). I would give analgesia, antiemetics, IV fluids and IV antibiotics, and plan laparoscopic cholecystectomy within a week, considering MRCP given her abnormal LFTs.',
    references: [
      'NICE CG188 Gallstone disease: diagnosis and management (2014)',
      'Tokyo Guidelines 2018 (TG18) for acute cholecystitis',
      'Macleod’s Clinical Examination, 14th ed. — Ch. 6: palpation of the gallbladder and Murphy’s sign',
    ],
  },
}

export default c
