import type { CaseDef } from '../../engine/types'
import { COAG, CRP, FBC, lab, LFT, r, UE, VBG } from './helpers'

const c: CaseDef = {
  id: 'cholangitis',
  title: 'Acute ascending cholangitis from choledocholithiasis',
  presenting: 'Fever, jaundice and RUQ pain',
  specialty: 'Hepatobiliary',
  exam: 'abdominal',
  difficulty: 2,
  setting: 'Emergency department',
  stem: 'Samuel Okoye, 72, has been brought in by his daughter, who noticed his eyes turning yellow. He has had fevers and abdominal pain. Assess, investigate and manage him.',
  components: ['history', 'exam', 'investigations', 'diagnosis', 'viva'],
  tags: ['jaundice', 'sepsis', 'Charcot', 'ERCP'],
  patient: {
    name: 'Samuel Okoye',
    title: 'Mr Okoye',
    age: 72,
    sex: 'male',
    dob: '25/09/1954',
    occupation: 'a retired bus driver',
    appearance: {
      sex: 'male',
      age: 72,
      skinTone: 6,
      habitus: 'overweight',
      hair: 'receding',
      hairColor: 'grey',
      eyeColor: 'brown',
      jaundice: 0.7,
      sweaty: true,
      lines: { cannula: 'left-hand', drip: true },
    },
    persona: { mood: 'drowsy', style: 'brief' },
  },
  vitals: { hr: 112, rhythm: 'regular', sbp: 98, dbp: 58, rr: 22, spo2: 96, temp: 39.1, avpu: 'A', pain: 6 },
  bedside: { drip: true, catheterUrine: 'tea' },
  history: {
    opening: { text: 'I’ve had pain under my ribs on the right for two days… and terrible shivers. My daughter says I’ve gone yellow.', cue: 'shivering under the blanket' },
    answers: {
      'pain.site': { text: 'Here, under the right ribs.', cue: 'points to the right upper quadrant' },
      'pain.onset': 'Two days ago. It came on over a few hours.',
      'pain.character': 'A constant ache.',
      'pain.radiation': 'A little into my back.',
      'pain.severity': 'Six.',
      'pain.previous': 'I’ve had gallbladder attacks. They found stones on a scan last year — I’m on the waiting list for the operation.',
      'sys.fever': 'Burning up, then freezing.',
      'sys.rigors': 'Yes — shaking so badly my teeth were chattering. Twice last night.',
      'gi.jaundice': 'My daughter noticed my eyes were yellow yesterday.',
      'gi.dark_urine': 'Very dark — like strong tea.',
      'gi.stool_colour': 'Pale, almost grey.',
      'gi.itch': 'A little itchy.',
      'gi.nausea': 'Yes.',
      'gi.vomiting': 'Once.',
      'gi.weight': 'No.',
      'ros.dizzy': 'A bit light-headed when I stand.',
      'pmh.conditions': 'Diabetes and blood pressure.',
      'pmh.gi': 'Gallstones, on the list for surgery.',
      'dh.meds': 'Metformin, gliclazide and amlodipine.',
      'dh.allergies': 'None.',
      'sh.alcohol': 'I don’t drink.',
      'sh.smoking': 'Never.',
      'sh.living': 'With my daughter’s family.',
      'comm.questions': 'Is it my gallbladder? Will I need the operation now?',
    },
    key: ['comm.open', 'pain.site', 'pain.onset', 'pain.previous', 'sys.fever', 'sys.rigors', 'gi.jaundice', 'gi.dark_urine', 'gi.stool_colour', 'gi.itch', 'pmh.conditions', 'dh.meds', 'dh.allergies', 'sh.alcohol'],
    critical: ['sys.rigors'],
    concerns: 'I feel very unwell — worse than any of the gallstone attacks.',
    expectations: 'To be fixed properly.',
  },
  abdo: {
    general: {
      endOfBed:
        'Mr Okoye looks unwell, shivering and sweaty, with visibly yellow sclerae. IV fluids are running through a cannula in his left hand, and a catheter bag contains dark, tea-coloured urine.',
    },
    hands: { temperature: 'hot', crt: 2.5 },
    face: { sclera: 'icteric', mucosa: 'dry' },
    abdomen: {
      regions: {
        RUQ: r(2, 2, 'voluntary', { percussionTender: true }),
        EPI: r(1, 1),
      },
      liver: { edgeCm: 2, texture: 'smooth', tender: true, spanCm: 14 },
      gallbladder: { palpable: false, murphy: false },
    },
    completion: { urinalysis: 'Bilirubin +++, urobilinogen negative, glucose ++, ketones +.' },
  },
  criticalSteps: ['face.eyes'],
  investigations: {
    fbc: { values: FBC(136, 18.4, 16.3, 188), interpretation: 'Neutrophilia.' },
    lft: { values: LFT(92, 188, 412, 510, 34), interpretation: 'Cholestatic (obstructive) picture: bilirubin, ALP and GGT markedly raised.' },
    crp: { values: CRP(214) },
    ue: { values: UE(135, 4.3, 11.8, 136, '45'), interpretation: 'AKI (sepsis).' },
    vbg: { values: VBG(7.33, 20, -4.6, 2.6, 4.3, 14.2), interpretation: 'Raised lactate and glucose — sepsis in a diabetic.' },
    cultures: { report: 'Escherichia coli isolated from 2 of 2 sets.', interpretation: 'Gram-negative bacteraemia (typical of biliary sepsis).', abnormal: true },
    coag: { values: COAG(14.4, 1.3, 33), interpretation: 'Mildly raised INR — check before ERCP/sphincterotomy.' },
    amylase: { values: [lab('Amylase', 70, 'U/L', '30–110')], interpretation: 'Normal — no associated pancreatitis.' },
    'us-abdo': {
      report: 'Gallbladder contains multiple calculi with a normal wall. Common bile duct dilated to 11 mm with an echogenic, shadowing stone in the distal duct. Mild intrahepatic duct dilatation.',
      interpretation: 'Choledocholithiasis with biliary obstruction.',
      abnormal: true,
    },
    mrcp: { report: 'Two filling defects in the distal CBD (8 and 6 mm) with upstream dilatation.', interpretation: 'CBD stones — MRCP is useful when ultrasound is inconclusive.', abnormal: true },
  },
  investigationRubric: {
    essential: [
      { id: 'fbc', why: 'Tokyo criteria (inflammation).' },
      { id: 'lft', why: 'Cholestasis confirms biliary obstruction.' },
      { id: 'crp', why: 'Inflammation.' },
      { id: 'ue', why: 'Organ dysfunction (AKI) grades severity.' },
      { id: 'us-abdo', why: 'Duct dilatation and the cause (stones).' },
      { id: 'cultures', why: 'Before antibiotics — biliary sepsis is often bacteraemic.' },
    ],
    helpful: [
      { id: 'vbg', why: 'Lactate in sepsis.' },
      { id: 'coag', why: 'INR before ERCP; vitamin K malabsorption.' },
      { id: 'amylase', why: 'Associated gallstone pancreatitis?' },
      { id: 'mrcp', why: 'If ultrasound does not show the cause.' },
    ],
  },
  diagnosis: {
    correct: 'cholangitis',
    accept: ['choledocholithiasis'],
    differentials: ['cholecystitis', 'pancreatic-cancer', 'hepatitis', 'pancreatitis', 'cholangiocarcinoma'],
  },
  management: {
    essential: [
      { id: 'sepsis6', why: 'Septic: oxygen, cultures, antibiotics, fluids, lactate, urine output within the hour.' },
      { id: 'abx-iv', why: 'IV antibiotics covering Gram-negatives and enterococci.' },
      { id: 'fluids', why: 'Hypotensive and in AKI.' },
      { id: 'biliary-decompression', why: '!Urgent biliary drainage (ERCP with stone extraction/stent) — the source of sepsis is an obstructed, infected duct.' },
      { id: 'senior', why: 'Senior review; involve gastroenterology/ERCP team.' },
    ],
    helpful: [
      { id: 'gastro-ercp', why: 'Arrange ERCP.' },
      { id: 'catheter', why: 'Urine output (already in place).' },
      { id: 'glucose-monitoring', why: 'Diabetic, septic; stop metformin while acutely unwell.' },
      { id: 'analgesia', why: 'Analgesia.' },
      { id: 'vte', why: 'VTE prophylaxis.' },
      { id: 'lap-chole-interval', why: 'Cholecystectomy after recovery (ideally within weeks) to prevent recurrence.' },
    ],
    avoid: [
      { id: 'discharge', why: 'Septic shock risk.' },
      { id: 'lap-chole-early', why: 'Removing the gallbladder does not decompress the infected common bile duct — drain the duct first.' },
    ],
  },
  viva: [
    {
      id: 'charcot',
      q: 'What is Charcot’s triad, and what is Reynolds’ pentad?',
      answer: 'Charcot’s triad: fever/rigors, jaundice and RUQ pain. Reynolds’ pentad adds hypotension (shock) and confusion — severe (suppurative) cholangitis with high mortality needing emergency decompression.',
      topic: 'Signs',
    },
    {
      id: 'organisms',
      q: 'Which organisms usually cause cholangitis?',
      options: ['E. coli, Klebsiella, Enterococcus', 'Staphylococcus aureus and streptococci', 'Candida', 'Mycobacterium tuberculosis'],
      correct: 0,
      answer: 'Enteric Gram-negatives (E. coli, Klebsiella, Enterobacter), enterococci and anaerobes ascending from the duodenum into obstructed bile.',
      topic: 'Microbiology',
    },
    {
      id: 'why-drain',
      q: 'Why is antibiotic treatment alone not enough?',
      answer: 'Bile under pressure behind the stone drives bacteria into the bloodstream (cholangiovenous reflux) and antibiotics penetrate poorly into obstructed bile. Source control — decompression by ERCP (or PTC if ERCP fails) — is essential; urgency depends on the Tokyo severity grade.',
      topic: 'Management',
    },
    {
      id: 'lft-pattern',
      q: 'His LFTs show bilirubin 92, ALP 412, ALT 188. What pattern is this?',
      options: ['Obstructive (cholestatic)', 'Hepatitic', 'Isolated unconjugated hyperbilirubinaemia', 'Normal'],
      correct: 0,
      answer: 'Obstructive: ALP and GGT rise disproportionately to ALT (though ALT can rise sharply early in acute obstruction). Dark urine (conjugated bilirubin) and pale stools confirm post-hepatic jaundice.',
      topic: 'Interpretation',
    },
  ],
  teaching: {
    summary:
      'Ascending cholangitis in a diabetic 72-year-old with known gallstones: Charcot’s triad (rigors, jaundice, RUQ pain), sepsis with hypotension and AKI, a cholestatic LFT picture, E. coli bacteraemia and a dilated CBD with a distal stone.',
    keyFindings: [
      'Rigors, jaundice and RUQ pain — Charcot’s triad',
      'Dark urine, pale stools — obstructive jaundice',
      'Sepsis: T 39.1 °C, HR 112, BP 98/58, lactate 2.6, AKI',
      'Icteric sclerae — easier to see than skin jaundice in darker skin',
      'US: CBD 11 mm with a distal stone',
    ],
    pearls: [
      'Look at the sclerae in natural light — especially in darker skin.',
      'Obstructive jaundice + fever = cholangitis until proven otherwise.',
      'Treat sepsis immediately, but source control is drainage of the duct.',
      'Check the INR before ERCP; give vitamin K if prolonged.',
    ],
    presentation:
      'Mr Okoye is a 72-year-old diabetic man with known gallstones awaiting cholecystectomy, presenting with two days of right upper quadrant pain, rigors and jaundice, with dark urine and pale stools. He is septic: temperature 39.1 °C, HR 112, BP 98/58, lactate 2.6, with an AKI. He has icteric sclerae and right upper quadrant tenderness with a tender liver edge; Murphy’s sign is negative. Bloods show a cholestatic picture (bilirubin 92, ALP 412, GGT 510), WCC 18.4 and CRP 214, and blood cultures grow E. coli. Ultrasound shows a CBD of 11 mm with a distal stone. This is acute ascending cholangitis secondary to choledocholithiasis. I would start the Sepsis Six with IV antibiotics and fluids, and arrange urgent ERCP for biliary decompression and stone extraction, followed by cholecystectomy once recovered.',
    references: ['Tokyo Guidelines 2018 (TG18) for acute cholangitis', 'NICE CG188 Gallstone disease', 'Macleod’s Clinical Examination, 14th ed. — Ch. 6: jaundice'],
  },
}

export default c
