import type { CaseDef } from '../../engine/types'
import { lab } from './helpers'

const c: CaseDef = {
  id: 'claudication',
  title: 'Intermittent claudication (left superficial femoral artery disease)',
  presenting: 'Calf pain on walking',
  specialty: 'Vascular',
  exam: 'arterial',
  difficulty: 2,
  setting: 'Outpatient clinic',
  stem: 'Vascular clinic. Steven Ward, 64, gets pain in his left calf when he walks. Take a history, examine his lower limb arterial system, request investigations and discuss management.',
  components: ['history', 'exam', 'investigations', 'diagnosis', 'viva'],
  tags: ['vascular', 'claudication', 'best medical therapy', 'exercise'],
  patient: {
    name: 'Steven Ward',
    title: 'Mr Ward',
    age: 64,
    sex: 'male',
    dob: '17/03/1962',
    occupation: 'a postman',
    appearance: { sex: 'male', age: 64, skinTone: 1, habitus: 'overweight', hair: 'receding', hairColor: 'grey', eyeColor: 'brown', facialHair: 'none' },
    persona: { mood: 'calm', style: 'chatty' },
  },
  vitals: { hr: 76, rhythm: 'regular', sbp: 152, dbp: 90, rr: 14, spo2: 97, temp: 36.6, avpu: 'A', pain: 0 },
  visual: {
    legs: {
      right: { pulses: { femoral: 'normal', popliteal: 'normal', pt: 'normal', dp: 'normal' } },
      left: { hairLoss: true, buergerAngle: 50, pulses: { femoral: 'normal', popliteal: 'absent', pt: 'weak', dp: 'absent' } },
    },
  },
  history: {
    opening: 'I get a cramping pain in my left calf when I walk. It’s getting in the way of my round.',
    answers: {
      'pain.site': 'The left calf.',
      'pain.character': 'A tight, cramping ache.',
      'pain.onset': 'About eight months ago.',
      'pain.relieving': 'If I stand still for a minute or two it goes away.',
      'pain.exacerbating': 'Walking — especially uphill or fast.',
      'vas.claudication': 'Yes, every time I walk a certain distance.',
      'vas.distance': 'About 150 yards on the flat, less uphill. It’s always about the same distance.',
      'vas.rest_pain': 'No, never at rest or at night.',
      'vas.ulcers': 'No sores or wounds.',
      'vas.cold': 'Maybe the left foot is a bit cooler.',
      'vas.ed': 'No problems there.',
      'ros.chest_pain': 'No chest pain.',
      'ros.joints': 'My back and hips are fine — the pain isn’t in my back or buttocks.',
      'pmh.conditions': 'High blood pressure. Nothing else.',
      'pmh.diabetes': 'Not diabetic as far as I know.',
      'pmh.heart': 'No heart problems.',
      'pmh.stroke': 'No.',
      'dh.meds': 'Amlodipine.',
      'dh.allergies': 'None.',
      'sh.smoking': 'Fifteen a day for forty years.',
      'sh.alcohol': 'About twenty units a week.',
      'sh.occupation': 'A postman — I walk for a living, so this is a real problem.',
      'fh.general': 'My dad had a heart attack at sixty-two.',
      'comm.questions': 'Will I need an operation to unblock it?',
    },
    key: ['comm.open', 'pain.site', 'pain.character', 'pain.relieving', 'vas.distance', 'vas.rest_pain', 'vas.ulcers', 'ros.chest_pain', 'ros.joints', 'pmh.diabetes', 'pmh.heart', 'pmh.stroke', 'dh.meds', 'sh.smoking', 'sh.occupation'],
    critical: ['vas.rest_pain', 'sh.smoking'],
    ideas: 'Maybe it’s my circulation.',
    concerns: 'Losing my job if I can’t do my round.',
    expectations: 'I want to be able to walk properly again.',
  },
  keyed: {
    'art.general': { text: 'A well-looking, overweight man, comfortable at rest. No walking aids or amputations.' },
    'art.hands': { text: 'Nicotine staining of the right index finger. No xanthomata. Capillary refill < 2 s.', abnormal: true },
    'art.radial': { text: 'Radial pulse 76 and regular, no radio-radial delay.' },
    'art.aorta': { text: 'Aorta not expansile.' },
    'art.inspect': { text: 'Some hair loss over the left shin; otherwise normal colour and skin with no ulcers, gangrene or scars. No muscle wasting.', abnormal: true },
    'art.toes': { text: 'No ulcers between the toes or on the heels.' },
    'art.temp': { text: 'The left foot is slightly cooler than the right.', abnormal: true },
    'art.crt': { text: 'Capillary refill 3 s on the left, < 2 s on the right.', abnormal: true },
    'art.femoral': { text: 'Both femoral pulses are normal.' },
    'art.popliteal': { text: 'Left popliteal pulse absent; right normal.', abnormal: true, meaning: 'Normal femoral but absent popliteal localises the disease to the left superficial femoral artery.' },
    'art.pt': { text: 'Left posterior tibial weak; right normal.', abnormal: true },
    'art.dp': { text: 'Left dorsalis pedis absent; right normal.', abnormal: true },
    'art.bruit': { text: 'No femoral bruits.' },
    'art.buerger': { text: 'Buerger’s test: the left foot pales at about 50°; no dependent rubor. The right foot stays pink.', abnormal: true, meaning: 'Buerger’s angle > 20° — not critical ischaemia.' },
    'art.sensation': { text: 'Normal sensation.' },
    'complete.abpi': { text: 'Handheld Doppler: left PT biphasic, DP monophasic. ABPI left 0.62, right 1.02.', abnormal: true, media: 'doppler:biphasic', meaning: 'ABPI 0.5–0.9: peripheral arterial disease in the claudication range.' },
    'complete.cvs': { text: 'Normal heart sounds; no carotid bruits.' },
  },
  criticalSteps: ['pu.femoral', 'pu.popliteal'],
  investigations: {
    abpi: { report: 'ABPI left 0.62, right 1.02. Post-exercise left ankle pressure falls further.', interpretation: 'Left-leg peripheral arterial disease.', abnormal: true },
    'duplex-art': { report: 'Left superficial femoral artery: 8 cm occlusion in the adductor canal with collateral reconstitution of the popliteal artery. Two-vessel run-off. Right leg: no significant disease.', interpretation: 'Left SFA occlusion (the commonest site).', abnormal: true },
    lipids: { values: [lab('Total cholesterol', '6.1', 'mmol/L', '< 5.0', 'H'), lab('LDL', '3.9', 'mmol/L', '< 3.0', 'H'), lab('HbA1c', '46', 'mmol/mol', '< 42', 'H')], interpretation: 'Hypercholesterolaemia and prediabetes.', abnormal: true },
    ecg: { report: 'Sinus rhythm, left ventricular hypertrophy voltage criteria.', interpretation: 'LVH — hypertension.', abnormal: true },
  },
  investigationRubric: {
    essential: [{ id: 'abpi', why: '!Confirms and quantifies PAD.' }, { id: 'lipids', why: 'Cardiovascular risk factors (lipids, HbA1c).' }],
    helpful: [{ id: 'duplex-art', why: 'Only if revascularisation is being considered after best medical therapy and exercise.' }, { id: 'ecg', why: 'Coexisting cardiovascular disease.' }],
    avoid: [{ id: 'cta', why: 'Not needed at this stage — imaging for planning only if intervention is considered.' }],
  },
  diagnosis: { correct: 'pad', differentials: ['clti', 'dvt', 'varicose-veins'] },
  management: {
    essential: [
      { id: 'statin-antiplatelet', why: 'Best medical therapy: atorvastatin 80 mg, clopidogrel 75 mg, BP control.' },
      { id: 'smoking-cessation', why: '!Stopping smoking is the most effective intervention.' },
      { id: 'exercise', why: 'NICE: supervised exercise programme (2 h/week for 3 months) before considering intervention.' },
    ],
    helpful: [{ id: 'lifestyle', why: 'Weight loss, diet, alcohol reduction.' }],
    avoid: [
      { id: 'vascular', why: 'Immediate vascular referral is for CLTI or acute ischaemia, not stable claudication.' },
      { id: 'amputation', why: 'Claudication rarely progresses to limb loss (~1–2% per year).' },
    ],
  },
  viva: [
    {
      id: 'level',
      q: 'His pain is in the calf. Where is the arterial disease likely to be?',
      options: ['Aorto-iliac', 'Superficial femoral / popliteal', 'Crural (below the knee)', 'Subclavian'],
      correct: 1,
      answer: 'Calf claudication usually reflects femoro-popliteal disease (the SFA in the adductor canal is the commonest site). Buttock/thigh claudication ± erectile dysfunction suggests aorto-iliac disease (Leriche syndrome); foot claudication suggests crural disease.',
      topic: 'Localisation',
    },
    {
      id: 'spinal',
      q: 'How would you distinguish vascular claudication from neurogenic (spinal) claudication?',
      answer: 'Vascular: reproducible calf cramp at a fixed distance, relieved within minutes by standing still; pulses reduced. Neurogenic (spinal stenosis): pain, numbness or weakness in the buttocks/legs on standing or walking, variable distance, relieved by sitting or bending forward (flexion), better walking uphill or cycling; pulses normal.',
      topic: 'Differentials',
    },
    {
      id: 'prognosis',
      q: 'What is the main cause of death in patients with intermittent claudication?',
      answer: 'Cardiovascular events (myocardial infarction and stroke). Claudication is a marker of systemic atherosclerosis: roughly 20% have a cardiovascular event within 5 years, whereas only 1–2% per year progress to CLTI. Hence the emphasis on best medical therapy and smoking cessation.',
      topic: 'Prognosis',
    },
  ],
  teaching: {
    summary: 'Reproducible left calf claudication at ~150 yards with normal femoral but absent popliteal and foot pulses and ABPI 0.62 — intermittent claudication from left SFA occlusion. First-line: best medical therapy, smoking cessation and supervised exercise.',
    keyFindings: ['Normal femoral, absent left popliteal and DP, weak PT', 'Mild hair loss and coolness of the left foot', 'No rest pain or tissue loss; Buerger’s angle 50°', 'ABPI left 0.62'],
    pearls: ['The level at which the pulses disappear localises the disease.', 'Ask about rest pain and tissue loss — they turn claudication into CLTI.', 'Claudication kills through the heart and brain, not the leg.'],
    presentation:
      'I examined Mr Steven Ward, a 64-year-old man who looked well at rest. His pulse was 76 and regular, with nicotine staining of the right index finger. The left leg shows mild hair loss over the shin, with no ulcers or gangrene, including between the toes and on the heels. The left foot is slightly cooler than the right, with a capillary refill of 3 seconds. Both femoral pulses are normal without bruits; on the left the popliteal and dorsalis pedis pulses are absent and the posterior tibial is weak, while all right-sided pulses are normal. Buerger’s angle on the left is about 50° with no dependent rubor, and sensation is normal. These findings are consistent with left superficial femoral artery disease causing intermittent claudication. I would complete my examination with an ABPI and a cardiovascular examination.',
    references: ['Macleod’s Clinical Examination, 14th ed. — Ch. 5: peripheral arterial examination', 'NICE CG147: Peripheral arterial disease — diagnosis and management'],
  },
}

export default c
