import type { CaseDef } from '../../engine/types'
import { FBC, lab, UE } from './helpers'

const c: CaseDef = {
  id: 'clti',
  title: 'Chronic limb-threatening ischaemia of the right leg',
  presenting: 'Painful right foot with a non-healing ulcer',
  specialty: 'Vascular',
  exam: 'arterial',
  difficulty: 3,
  setting: 'Surgical ward',
  stem: 'You are the FY1 on the vascular ward. Raymond Cole, 72, has been admitted from clinic with night pain in his right foot and an ulcer on his ankle. Take a history, examine his peripheral arterial system, request investigations and outline management.',
  components: ['history', 'exam', 'investigations', 'diagnosis', 'viva'],
  tags: ['vascular', 'rest pain', 'ulcer', 'gangrene', 'Buerger’s test', 'ABPI'],
  patient: {
    name: 'Raymond Cole',
    title: 'Mr Cole',
    age: 72,
    sex: 'male',
    dob: '25/11/1953',
    occupation: 'a retired lorry driver',
    appearance: { sex: 'male', age: 72, skinTone: 2, habitus: 'thin', hair: 'bald', hairColor: 'grey', eyeColor: 'grey', facialHair: 'stubble', lines: { cannula: 'left-hand' } },
    persona: { mood: 'irritable', style: 'brief' },
  },
  vitals: { hr: 84, rhythm: 'regular', sbp: 158, dbp: 88, rr: 16, spo2: 95, temp: 36.7, avpu: 'A', pain: 6 },
  bedside: { walkingFrame: true },
  visual: {
    legs: {
      right: {
        pallor: 0.55,
        hairLoss: true,
        shiny: true,
        cold: true,
        ulcer: { kind: 'arterial', site: 'lateral-malleolus', sizeCm: 1.5 },
        gangrene: [2],
        buergerAngle: 15,
        pulses: { femoral: 'weak', popliteal: 'absent', pt: 'absent', dp: 'absent' },
      },
      left: { hairLoss: true, buergerAngle: 60, pulses: { femoral: 'normal', popliteal: 'normal', pt: 'weak', dp: 'absent' } },
    },
  },
  history: {
    opening: { text: 'My right foot is killing me at night. I have to sleep in the chair now, and I’ve got a sore on my ankle that won’t heal.', cue: 'rubs his right foot' },
    answers: {
      'pain.site': 'The right foot — mostly the toes and the front of the foot.',
      'pain.onset': 'Walking’s been bad for a couple of years, but the night pain started about six weeks ago.',
      'pain.character': 'A deep, gnawing, burning ache.',
      'pain.timing': 'Worst at night in bed. It wakes me after an hour or so.',
      'pain.relieving': 'Hanging my leg out of bed helps, or sleeping in the chair.',
      'pain.severity': 'Six out of ten now; eight or nine at night.',
      'vas.rest_pain': 'Yes — every night now. I sleep in the chair with my foot down.',
      'vas.claudication': 'For two years I’ve had cramp in my right calf when I walk.',
      'vas.distance': 'Maybe fifty yards now before I have to stop.',
      'vas.ulcers': 'This sore on the outside of my right ankle has been there about a month. And the end of my second toe went black last week.',
      'vas.cold': 'The right foot is always cold and it looks pale.',
      'vas.ed': 'Yes, for a few years, if I’m honest.',
      'vas.dvt': 'Never had a clot.',
      'ros.chest_pain': 'I had a heart attack six years ago and had stents.',
      'pmh.conditions': 'Heart attack, type 2 diabetes, high blood pressure and high cholesterol.',
      'pmh.diabetes': 'Type 2 diabetes for twelve years, on tablets. My sugars aren’t great.',
      'pmh.heart': 'Heart attack six years ago — two stents.',
      'pmh.stroke': 'No strokes.',
      'dh.meds': 'Metformin, gliclazide, aspirin, ramipril and a statin — but I stopped the statin because of my muscles.',
      'dh.allergies': 'No allergies.',
      'sh.smoking': 'I smoke twenty a day — have done since I was fifteen.',
      'sh.alcohol': 'A few pints at the weekend.',
      'sh.mobility': 'I use a frame now. I live on my own in a ground-floor flat.',
      'fh.general': 'My father died of a stroke at sixty.',
      'comm.questions': 'Am I going to lose my foot?',
    },
    key: [
      'comm.open',
      'pain.site',
      'pain.timing',
      'pain.relieving',
      'vas.rest_pain',
      'vas.claudication',
      'vas.distance',
      'vas.ulcers',
      'vas.cold',
      'ros.chest_pain',
      'pmh.diabetes',
      'pmh.heart',
      'pmh.stroke',
      'dh.meds',
      'sh.smoking',
      'sh.mobility',
    ],
    critical: ['vas.rest_pain', 'sh.smoking'],
    ideas: 'I suppose it’s my circulation — the smoking, the doctor keeps telling me.',
    concerns: 'Losing my leg. My brother-in-law had his off.',
    expectations: 'I want the pain sorted so I can sleep.',
  },
  keyed: {
    'comm.pain': { text: '', says: 'Mind my right foot — it’s agony, and don’t touch the sore.', meaning: 'Rest pain: be gentle and examine the painful foot last.' },
    'art.general': { text: 'A thin, older man sitting on the edge of the bed with his right leg hanging down. A walking frame is beside him and there is a smell of cigarette smoke. No amputations.', abnormal: true, meaning: 'Hanging the leg down relieves ischaemic rest pain (gravity improves perfusion).' },
    'art.hands': { text: 'Heavy nicotine staining of the right index and middle fingers. No xanthomata. Capillary refill 2 s.', abnormal: true },
    'art.radial': { text: 'Radial pulse 84, regular; no radio-radial delay.' },
    'art.aorta': { text: 'The aorta is palpable but not expansile.', meaning: 'No AAA — but screen with ultrasound as PAD and AAA coexist.' },
    'art.inspect': {
      text: 'The right foot and lower leg are pale, hairless and shiny, with slight muscle wasting of the calf. On the right lateral malleolus there is a 1.5 cm punched-out ulcer with a pale, sloughy base and no granulation tissue. The tip of the right second toe is black and mummified with a red line of demarcation. The left leg is hairless but otherwise normal in colour.',
      abnormal: true,
      meaning: 'Arterial ulcers are small, deep, “punched-out” and painful, over pressure points and the lateral malleolus. Dry gangrene with a demarcation line = tissue loss → chronic limb-threatening ischaemia.',
    },
    'art.toes': { text: 'Between the toes and on the heels: no further ulcers or skin breaks. The right heel is intact.', meaning: 'Always look between the toes and at the heels — ulcers hide there.' },
    'art.temp': { text: 'The right foot is cold to the mid-calf compared with the left, which is cool only at the toes.', abnormal: true, meaning: 'A temperature gradient localises the level of disease.' },
    'art.crt': { text: 'Capillary refill in the right toes is 5 seconds; left 3 seconds.', abnormal: true },
    'art.femoral': { text: 'Right femoral pulse weak; left femoral pulse normal. No radio-femoral delay.', abnormal: true },
    'art.popliteal': { text: 'Right popliteal pulse absent; left popliteal pulse palpable and normal (not unusually prominent).', abnormal: true },
    'art.pt': { text: 'Right posterior tibial absent; left posterior tibial weak.', abnormal: true },
    'art.dp': { text: 'Dorsalis pedis absent on both sides.', abnormal: true },
    'art.bruit': { text: 'A bruit is heard over the right femoral artery.', abnormal: true, media: 'bruit', meaning: 'Turbulent flow from iliac/femoral stenosis.' },
    'art.buerger': {
      text: 'Buerger’s test: the right foot turns white at about 15° of elevation (Buerger’s angle 15°); the left at about 60°. On hanging the legs over the side of the bed, the right foot slowly turns a dusky red (“sunset foot”).',
      abnormal: true,
      meaning: 'Buerger’s angle < 20° indicates severe ischaemia; reactive hyperaemia on dependency confirms it.',
    },
    'art.sensation': { text: 'Reduced sensation to monofilament in both feet in a stocking distribution.', abnormal: true, meaning: 'Diabetic peripheral neuropathy — it worsens ulceration and can mask pain.' },
    'complete.abpi': {
      text: 'Handheld Doppler: right PT and DP signals monophasic; left biphasic. ABPI right 0.35, left 0.68.',
      abnormal: true,
      media: 'doppler:monophasic',
      meaning: 'ABPI < 0.5 = severe ischaemia. In diabetes calcified vessels can falsely elevate ABPI — toe pressures are more reliable.',
    },
    'complete.cvs': { text: 'Heart sounds normal; no carotid bruits.' },
  },
  criticalSteps: ['lg.inspect', 'lg.toes', 'pu.femoral'],
  investigations: {
    abpi: { report: 'ABPI right 0.35 (monophasic signals), left 0.68 (biphasic). Right toe pressure 22 mmHg.', interpretation: 'Severe right-leg ischaemia (ABPI < 0.5; toe pressure < 30 mmHg) consistent with CLTI; moderate left-sided disease.', abnormal: true },
    'duplex-art': { report: 'Right: 70–99% stenosis of the external iliac artery; occlusion of the superficial femoral artery from its origin to the adductor canal with reconstitution of the popliteal artery; diseased crural vessels with a single-vessel (peroneal) run-off. Left: SFA stenosis 50–70%.', interpretation: 'Multilevel right-leg disease suitable for revascularisation planning.', abnormal: true },
    cta: { report: 'Confirms right external iliac stenosis and a long SFA occlusion with peroneal run-off. No AAA.', interpretation: 'Road map for revascularisation.', abnormal: true },
    fbc: { values: FBC(128, 9.8, 6.9, 310), interpretation: 'Mild anaemia; no leucocytosis.' },
    ue: { values: UE(138, 4.6, 7.9, 118, '56'), interpretation: 'Mild CKD — important before iodinated contrast.' },
    lipids: { values: [lab('Total cholesterol', '6.4', 'mmol/L', '< 5.0', 'H'), lab('LDL', '4.1', 'mmol/L', '< 3.0', 'H'), lab('HbA1c', '72', 'mmol/mol', '< 48', 'H')], interpretation: 'Poorly controlled lipids and diabetes.', abnormal: true },
    ecg: { report: 'Sinus rhythm 84 bpm. Q waves in II, III, aVF (old inferior MI).', interpretation: 'Old inferior infarct; no acute changes.', abnormal: true },
  },
  investigationRubric: {
    essential: [
      { id: 'abpi', why: '!Quantifies ischaemia (with toe pressures in diabetes).' },
      { id: 'duplex-art', why: 'First-line imaging to localise disease.' },
      { id: 'lipids', why: 'Risk factor assessment: lipids and HbA1c.' },
    ],
    helpful: [
      { id: 'cta', why: 'CT angiography plans revascularisation (check renal function first).' },
      { id: 'fbc', why: 'Anaemia worsens tissue oxygen delivery.' },
      { id: 'ue', why: 'Renal function before contrast.' },
      { id: 'ecg', why: 'Coexisting coronary disease.' },
    ],
  },
  diagnosis: { correct: 'clti', accept: ['arterial-ulcer'], differentials: ['diabetic-foot', 'venous-ulcer', 'pad', 'ali'] },
  management: {
    essential: [
      { id: 'vascular', why: '!CLTI needs urgent vascular team assessment for revascularisation.' },
      { id: 'analgesia', why: 'Rest pain is severe — adequate analgesia (often opioids) is essential.' },
      { id: 'statin-antiplatelet', why: 'Best medical therapy: high-intensity statin (try an alternative if intolerant), antiplatelet, BP and glucose control.' },
      { id: 'smoking-cessation', why: '!The single most important modifiable risk factor.' },
      { id: 'revascularisation', why: 'Endovascular or surgical bypass to heal tissue loss and save the limb.' },
    ],
    helpful: [
      { id: 'glucose-monitoring', why: 'Tight diabetic control aids healing.' },
      { id: 'vte', why: 'Inpatient VTE prophylaxis.' },
      { id: 'mdt', why: 'Multidisciplinary foot team (vascular, diabetes, podiatry, orthotics).' },
    ],
    avoid: [
      { id: 'compression', why: '!Compression bandaging is contraindicated with ABPI < 0.5 — it can cause further tissue loss.' },
      { id: 'amputation', why: 'Primary amputation is not first-line while revascularisation may save the limb.' },
    ],
  },
  viva: [
    {
      id: 'fontaine',
      q: 'What defines chronic limb-threatening ischaemia (CLTI)?',
      options: ['Claudication at < 200 m', 'Ischaemic rest pain > 2 weeks, or tissue loss (ulceration/gangrene), with objective evidence of PAD', 'Sudden onset of a painful, pulseless leg', 'ABPI between 0.8 and 0.9'],
      correct: 1,
      answer: 'CLTI (Global Vascular Guidelines 2019): PAD with ischaemic rest pain for more than 2 weeks, or tissue loss (non-healing ulcer or gangrene), with objective haemodynamic evidence (e.g. ABPI < 0.4, ankle pressure < 50 mmHg, toe pressure < 30 mmHg). Fontaine III–IV / Rutherford 4–6.',
      topic: 'Definitions',
    },
    {
      id: 'ulcers',
      q: 'Contrast an arterial with a venous ulcer.',
      answer: 'Arterial: small, deep, punched-out, painful (worse at night/elevation), pale/necrotic base, on pressure points, toes, heels and the lateral malleolus; cold, pale, hairless foot with absent pulses. Venous: large, shallow, irregular with sloping edges, granulating or sloughy base, relatively painless, in the gaiter area over the medial malleolus; warm limb with varicose veins, haemosiderin, lipodermatosclerosis and eczema; pulses present.',
      topic: 'Ulcers',
    },
    {
      id: 'abpi',
      q: 'How is ABPI calculated and interpreted?',
      answer: 'Highest ankle systolic pressure (DP or PT) divided by the highest brachial systolic pressure, per leg. > 1.3: incompressible calcified vessels (diabetes, CKD) — unreliable; 0.9–1.3 normal; 0.5–0.9 PAD (claudication range); < 0.5 severe/critical ischaemia. Compression therapy is safe only if ABPI > 0.8.',
      topic: 'Investigations',
    },
    {
      id: 'six-ps',
      q: 'His leg suddenly becomes white, cold and numb. What are the features of acute limb ischaemia?',
      answer: 'The 6 Ps: pain, pallor, pulselessness, perishingly cold, paraesthesia and paralysis. Sensory loss and paralysis mean the limb is threatened — this is a vascular emergency: IV heparin and urgent revascularisation (embolectomy, thrombolysis or bypass).',
      topic: 'Emergencies',
    },
  ],
  teaching: {
    summary:
      'A smoker with diabetes and ischaemic heart disease has rest pain relieved by dependency, a punched-out lateral malleolar ulcer, dry gangrene of a toe, absent right-leg pulses below a weak femoral, Buerger’s angle 15° and ABPI 0.35 — chronic limb-threatening ischaemia needing urgent vascular revascularisation.',
    keyFindings: [
      'Pale, hairless, shiny, cold right leg with calf wasting',
      'Punched-out ulcer on the lateral malleolus; dry gangrene of the 2nd toe',
      'Weak right femoral; absent popliteal, PT and DP; femoral bruit',
      'Buerger’s angle 15° with dependent rubor; ABPI 0.35 with monophasic signals',
    ],
    pearls: [
      'Rest pain is worse at night and relieved by hanging the leg out of bed.',
      'Always inspect between the toes and the heels.',
      'Feel for a temperature gradient with the backs of your hands, comparing both legs.',
      'In diabetes, calcified arteries can make ABPI falsely normal — use toe pressures.',
      'Never apply compression without an ABPI.',
    ],
    presentation:
      'I examined Mr Raymond Cole, a 72-year-old man, who was sitting with his right leg hanging over the side of the bed; he has a walking frame and nicotine-stained fingers. His pulse is 84 and regular. The right lower leg and foot are pale, hairless and shiny with calf wasting, a 1.5 cm punched-out ulcer over the lateral malleolus with a pale sloughy base, and dry gangrene of the tip of the second toe. The right foot is cold to the mid-calf with a capillary refill time of 5 seconds. The right femoral pulse is weak with a bruit, and the right popliteal, posterior tibial and dorsalis pedis pulses are absent; on the left, femoral and popliteal are present with a weak posterior tibial and absent dorsalis pedis. Buerger’s angle is 15° on the right with dependent rubor. There is reduced sensation in a stocking distribution. These findings are consistent with chronic limb-threatening ischaemia of the right leg with tissue loss. I would complete the examination with an ABPI and toe pressures, and refer urgently to the vascular team.',
    references: ['Macleod’s Clinical Examination, 14th ed. — Ch. 5: The cardiovascular system (peripheral arterial examination)', 'Global Vascular Guidelines on CLTI (2019)', 'NICE CG147: Peripheral arterial disease'],
  },
}

export default c
