import type { CaseDef } from '../../engine/types'
import { COAG, FBC, LFT, UE, VBG } from './helpers'

const c: CaseDef = {
  id: 'diverticular-bleed',
  title: 'Acute lower GI bleed from a diverticulum (on apixaban)',
  presenting: 'Passing large amounts of fresh blood from the back passage',
  specialty: 'Colorectal',
  exam: 'abdominal',
  difficulty: 2,
  setting: 'Emergency department',
  stem: 'Emergency department. Margaret Owens, 78, has passed a large amount of dark red blood and clots from her back passage. Assess her, take a history, examine her, investigate and manage.',
  components: ['history', 'exam', 'investigations', 'diagnosis', 'viva'],
  tags: ['lower GI bleed', 'diverticular disease', 'anticoagulation', 'Oakland score'],
  patient: {
    name: 'Margaret Owens',
    title: 'Mrs Owens',
    age: 78,
    sex: 'female',
    dob: '04/02/1948',
    occupation: 'a retired teacher',
    appearance: { sex: 'female', age: 78, skinTone: 1, habitus: 'average', hair: 'short', hairColor: 'white', eyeColor: 'blue', glasses: true, pallor: 0.4, lines: { cannula: 'left-hand' } },
    persona: { mood: 'anxious', style: 'normal' },
  },
  vitals: { hr: 106, rhythm: 'irregular', sbp: 108, dbp: 64, rr: 20, spo2: 96, temp: 36.6, avpu: 'A', pain: 1 },
  history: {
    opening: 'I had a sudden urge to go and the toilet was full of blood — dark red, with clots. It’s happened three times since lunchtime.',
    answers: {
      'gi.stool_blood': { text: 'Lots of dark red blood and clots, mixed with a bit of stool. Not black.', cue: 'shudders' },
      'ano.blood_type': 'It filled the pan — not just on the paper.',
      'pain.site': 'No pain at all, just a little crampy before I go.',
      'gi.bowel_change': 'No change in my bowels before today.',
      'gi.weight': 'No weight loss.',
      'gi.melaena': 'No black stools.',
      'gi.vomiting': 'No.',
      'gi.reflux': 'No indigestion.',
      'ros.dizzy': 'I felt faint on the toilet.',
      'ros.chest_pain': 'No.',
      'pmh.gi': 'A colonoscopy five years ago showed diverticular disease — “pockets in the bowel”. No polyps.',
      'pmh.conditions': 'Atrial fibrillation, high blood pressure.',
      'pmh.heart': 'Atrial fibrillation for years.',
      'dh.meds': 'Apixaban, bisoprolol, amlodipine.',
      'dh.anticoag': 'Apixaban — last dose this morning at eight.',
      'dh.nsaids': 'Only paracetamol.',
      'dh.allergies': 'None.',
      'sh.alcohol': 'A sherry at Christmas.',
      'sh.living': 'With my husband; independent.',
      'comm.questions': 'Is it cancer?',
    },
    key: ['comm.open', 'gi.stool_blood', 'ano.blood_type', 'pain.site', 'gi.bowel_change', 'gi.weight', 'gi.melaena', 'ros.dizzy', 'pmh.gi', 'dh.anticoag', 'dh.nsaids', 'pmh.conditions'],
    critical: ['dh.anticoag'],
    ideas: 'My friend had bleeding from her diverticula.',
    concerns: 'That it’s bowel cancer.',
    expectations: 'To stop the bleeding and know what it is.',
    pmh: 'AF on apixaban, hypertension, diverticular disease.',
  },
  abdo: {
    general: { endOfBed: 'Mrs Owens is pale and anxious, lying on a trolley with a bedpan containing dark red blood and clots. She is alert.' },
    hands: { temperature: 'cool', crt: 3, pallorCreases: true },
    face: { conjunctiva: 'pale' },
    abdomen: { shape: 'flat', bowelSounds: 'hyperactive' },
    completion: { dre: 'Fresh dark red blood and clots on the glove; no mass; no haemorrhoids or fissure seen.' },
  },
  criticalSteps: ['gen.obs', 'end.completion'],
  investigations: {
    fbc: { values: FBC(96, 9.1, 6.8, 228, 88, 'female'), interpretation: 'Hb 96 (128 three months ago) — and still falling.' },
    ue: { values: UE(140, 4.1, 7.2, 84, '58', 'female'), interpretation: 'Normal urea — argues against an upper GI source.' },
    coag: { values: COAG(14, 1.3, 33), interpretation: 'Mildly prolonged (apixaban).' },
    lft: { values: LFT(10, 18, 72, 22, 36) },
    xm: { report: '4 units crossmatched.' },
    vbg: { values: VBG(7.38, 23, -2.1, 2.2), interpretation: 'Mildly raised lactate.' },
    cta: {
      report: 'Active contrast extravasation into the lumen of the proximal descending colon from a diverticulum. Extensive diverticulosis; no mass.',
      interpretation: 'Active diverticular haemorrhage — localised for embolisation.',
      abnormal: true,
    },
    colonoscopy: { report: 'After the bleeding settled: extensive diverticulosis, old blood in the descending colon, no polyps or cancer.', interpretation: 'Diverticular bleed; cancer excluded.' },
    ogd: { report: 'Normal oesophagus, stomach and duodenum.', interpretation: 'No upper GI source.' },
    ecg: { report: 'AF, rate 106. No acute ischaemia.' },
  },
  investigationRubric: {
    essential: [
      { id: 'fbc', why: 'Hb, compared with her baseline.' },
      { id: 'ue', why: 'A raised urea suggests an upper GI source.' },
      { id: 'coag', why: 'On apixaban.' },
      { id: 'xm', why: 'Ongoing bleeding.' },
      { id: 'cta', why: 'Haemodynamically unstable lower GI bleed (shock index > 1): CT angiography locates active bleeding before embolisation.' },
    ],
    helpful: [
      { id: 'vbg', why: 'Lactate and quick Hb.' },
      { id: 'lft', why: 'Liver disease.' },
      { id: 'ecg', why: 'AF, tachycardia.' },
      { id: 'colonoscopy', why: 'Once stable, to find the cause and exclude cancer.' },
      { id: 'ogd', why: 'If unstable with a suspected upper GI source.' },
    ],
  },
  diagnosis: {
    correct: 'diverticular-bleed',
    differentials: ['angiodysplasia', 'colorectal-cancer', 'ischaemic-colitis', 'haemorrhoids', 'bleeding-pu'],
  },
  management: {
    essential: [
      { id: 'abcde', why: 'Tachycardic, borderline BP.' },
      { id: 'iv-access', why: 'Two large-bore cannulae.' },
      { id: 'fluids', why: 'Resuscitate.' },
      { id: 'hold-anticoag', why: 'Hold apixaban; consider reversal (andexanet alfa or PCC) if life-threatening; discuss restarting later.' },
      { id: 'transfusion', why: 'If Hb < 70 (or < 80 with cardiovascular disease) or ongoing bleeding with instability.' },
      { id: 'senior', why: 'Surgical registrar and interventional radiology.' },
      { id: 'ir-embolisation', why: '!CT angiography, then catheter angiography and embolisation of the bleeding vessel.' },
      { id: 'colonoscopy-later', why: 'To confirm the source and exclude cancer.' },
    ],
    helpful: [
      { id: 'catheter', why: 'Urine output.' },
      { id: 'observe', why: 'Most diverticular bleeds stop spontaneously.' },
      { id: 'laparotomy', why: 'Last resort if bleeding continues despite embolisation.' },
    ],
    avoid: [
      { id: 'discharge', why: 'Oakland score > 8 and ongoing bleeding.' },
      { id: 'nsaid', why: 'Increase diverticular bleeding.' },
    ],
  },
  viva: [
    {
      id: 'oakland',
      q: 'Which score helps decide discharge in lower GI bleeding?',
      answer: 'The Oakland score (age, sex, previous LGIB admission, DRE findings, heart rate, systolic BP, haemoglobin). A score of 8 or less with no other reason for admission allows outpatient investigation (BSG).',
      topic: 'Scores',
    },
    {
      id: 'causes',
      q: 'Name the common causes of lower GI bleeding.',
      answer: 'Diverticular disease (commonest acute major bleed), angiodysplasia, haemorrhoids and fissure, colorectal cancer and polyps, colitis (ischaemic, inflammatory, infective), post-polypectomy bleeding — and a brisk upper GI bleed.',
      topic: 'Causes',
    },
    {
      id: 'upper',
      q: 'When could fresh rectal bleeding come from the upper GI tract?',
      options: ['A brisk upper GI bleed with shock and a raised urea', 'Never', 'Only in children', 'Only with haematemesis'],
      correct: 0,
      answer: 'About 1 in 10–15 patients with haematochezia and shock have an upper GI source — suspect it with a raised urea, and consider OGD first.',
      topic: 'Differentials',
    },
    {
      id: 'dre',
      q: 'Why is a rectal examination essential here?',
      answer: 'To confirm the nature of the blood, find a low rectal tumour, and look for an anal cause (haemorrhoids, fissure). Proctoscopy can follow.',
      topic: 'Examination',
    },
  ],
  teaching: {
    summary:
      'Diverticular haemorrhage in a 78-year-old on apixaban: sudden painless large-volume dark red rectal bleeding with clots, tachycardia and a falling Hb, a normal urea and known diverticulosis; CT angiography shows active bleeding for embolisation.',
    keyFindings: [
      'Three episodes of painless, large-volume dark red blood and clots',
      'Apixaban for AF; known diverticular disease',
      'HR 106 (AF), BP 108/64, pale; soft non-tender abdomen',
      'Fresh blood on DRE; no mass, no haemorrhoids',
      'Hb 96 (baseline 128), normal urea; CTA active extravasation in the descending colon',
    ],
    pearls: [
      'Painless, sudden, large-volume bleeding in an older patient = diverticular until proven otherwise.',
      'Ask about anticoagulants and antiplatelets in every bleed.',
      'Shock index (HR/SBP) > 1 → CT angiography first.',
      'Colonoscopy later to exclude cancer.',
    ],
    presentation:
      'Mrs Owens is a 78-year-old woman with atrial fibrillation on apixaban and known diverticular disease who presents with three episodes of sudden, painless, large-volume dark red rectal bleeding with clots and a near-faint, without change in bowel habit or weight loss. She is pale with a heart rate of 106 in AF and BP 108/64; the abdomen is soft and non-tender and DRE shows fresh blood with no mass. Hb has fallen from 128 to 96 with a normal urea. CT angiography shows active extravasation from a descending colonic diverticulum. I would resuscitate her, hold her apixaban and consider reversal, crossmatch blood, and refer to interventional radiology for embolisation, followed by colonoscopy once she has settled.',
    references: ['Macleod’s Clinical Examination, 14th ed. — Ch. 6: rectal bleeding and rectal examination (pp. 111–113)', 'BSG guideline on acute lower gastrointestinal bleeding (2019)'],
  },
}

export default c
