import type { CaseDef } from '../../engine/types'
import { CRP, FBC, lab, LFT, r, UE } from './helpers'

const c: CaseDef = {
  id: 'diverticulitis',
  title: 'Complicated sigmoid diverticulitis with a pericolic abscess (Hinchey Ib)',
  presenting: 'Left iliac fossa pain and fever',
  specialty: 'Colorectal',
  exam: 'abdominal',
  difficulty: 2,
  setting: 'Surgical assessment unit',
  stem: 'Patricia Doyle, 68, has been referred by her GP with four days of lower abdominal pain and fever despite oral antibiotics. Take a history, examine her abdomen, investigate and outline your management.',
  components: ['history', 'exam', 'investigations', 'diagnosis', 'viva'],
  tags: ['LIF pain', 'diverticular disease', 'Hinchey', 'abscess'],
  patient: {
    name: 'Patricia Doyle',
    title: 'Mrs Doyle',
    age: 68,
    sex: 'female',
    dob: '30/04/1958',
    occupation: 'a retired primary-school teacher',
    appearance: {
      sex: 'female',
      age: 68,
      skinTone: 2,
      habitus: 'overweight',
      hair: 'bob',
      hairColor: 'grey',
      eyeColor: 'green',
      flushed: 0.3,
      glasses: true,
      lines: { cannula: 'right-hand' },
    },
    persona: { mood: 'calm', style: 'chatty' },
  },
  vitals: { hr: 96, rhythm: 'regular', sbp: 142, dbp: 86, rr: 18, spo2: 97, temp: 38.4, avpu: 'A', pain: 6 },
  history: {
    opening: { text: 'I’ve had this pain low down on the left for four days now. The GP gave me antibiotics two days ago but I’m getting worse, and I’ve had fevers.', cue: 'rests her hand over her left lower abdomen' },
    answers: {
      'pain.site': { text: 'Down here on the left, above my hip.', cue: 'points to the left iliac fossa' },
      'pain.onset': 'Four days ago. It came on gradually and has built up since.',
      'pain.character': 'A constant, sore, dragging ache.',
      'pain.radiation': 'No, it stays there.',
      'pain.timing': 'Constant.',
      'pain.exacerbating': 'Walking, bending, bumps in the car.',
      'pain.relieving': 'Lying still with a hot-water bottle.',
      'pain.severity': 'About six, seven at night.',
      'pain.previous': 'Twice in the last two years — milder. The GP called it “diverticulitis” and antibiotics sorted it.',
      'gi.nausea': 'A bit queasy.',
      'gi.vomiting': 'No.',
      'gi.appetite': 'Off my food.',
      'gi.bowel_change': 'Looser than usual this week — two or three times a day.',
      'gi.diarrhoea': 'Loose, yes, a couple of times a day.',
      'gi.stool_blood': 'No blood.',
      'gi.mucus': 'No.',
      'gi.weight': 'No, if anything I’ve put weight on.',
      'gi.flatus': 'Yes.',
      'sys.fever': 'Fevers and sweats, especially at night.',
      'sys.rigors': 'I had one bad shivering fit last night.',
      'gu.frequency': 'I’ve been going to the loo a bit more, but it doesn’t burn.',
      'gu.dysuria': 'No burning.',
      'gyn.bleeding': 'No — nothing since the change.',
      'pmh.conditions': 'Type 2 diabetes and blood pressure.',
      'pmh.gi': 'A colonoscopy three years ago showed diverticular disease — nothing else.',
      'pmh.surgery': 'Nothing.',
      'dh.meds': 'Metformin, amlodipine, and the co-amoxiclav from the GP.',
      'dh.allergies': 'None.',
      'fh.cancer': 'No bowel cancer in the family.',
      'sh.diet': 'I don’t eat much fruit or veg, to be honest. Lots of bread.',
      'sh.smoking': 'Never.',
      'sh.alcohol': 'The odd glass of wine.',
      'sh.living': 'With my husband.',
      'comm.questions': 'Could this be cancer? My friend had bowel cancer.',
    },
    key: [
      'comm.open',
      'pain.site',
      'pain.onset',
      'pain.character',
      'pain.severity',
      'pain.previous',
      'gi.bowel_change',
      'gi.stool_blood',
      'gi.weight',
      'sys.fever',
      'gu.frequency',
      'pmh.gi',
      'pmh.conditions',
      'dh.meds',
      'dh.allergies',
      'fh.cancer',
    ],
    ideas: 'I suppose it’s the diverticulitis again, but worse.',
    concerns: 'That it might be cancer — or that I’ll end up with a bag.',
    expectations: 'To get rid of the infection properly this time.',
    pmh: 'Type 2 diabetes; hypertension.',
    meds: 'Metformin 1 g twice daily, amlodipine 5 mg, co-amoxiclav for 2 days.',
  },
  abdo: {
    general: {
      endOfBed:
        'Mrs Doyle is sitting up in bed, flushed and looking unwell but able to hold a conversation. She shifts carefully when she moves. A cannula is in her right hand. No drains, stomas or catheter.',
    },
    hands: { temperature: 'hot' },
    abdomen: {
      coughPain: true,
      regions: {
        LIF: r(2, 3, 'involuntary', {
          percussionTender: true,
          mass: { description: 'a tender, ill-defined, fixed 5 cm mass deep in the left iliac fossa', label: 'tender LIF mass (phlegmon/abscess)', sizeCm: 5, tender: true },
        }),
        SP: r(1, 2, 'voluntary'),
        LF: r(1, 1),
      },
    },
    completion: {
      dre: 'Tenderness on the left side of the rectum. No mass, no blood; soft brown stool.',
      urinalysis: 'Leucocytes +, nitrites −, blood −, glucose +.',
    },
  },
  investigations: {
    fbc: { values: FBC(128, 17.2, 14.6, 402, 86, 'female'), interpretation: 'Leucocytosis despite oral antibiotics.' },
    crp: { values: CRP(186) },
    ue: { values: UE(137, 4.2, 6.9, 84, '64', 'female'), interpretation: 'Mildly reduced eGFR — consider withholding metformin around IV contrast.' },
    lft: { values: LFT(10, 24, 102, 30, 36) },
    'urine-dip': { report: 'Leucocytes +, nitrites −, blood −, glucose +.', interpretation: 'Sterile pyuria from adjacent sigmoid inflammation against the bladder — not a UTI (nitrites negative).', abnormal: true },
    glucose: { values: [lab('Glucose (random)', 13.8, 'mmol/L', '4.0–7.8', 'H')], interpretation: 'Hyperglycaemia with sepsis — monitor and adjust diabetes treatment.' },
    'ct-ap': {
      report:
        'Sigmoid diverticular disease with marked wall thickening and pericolic fat stranding. A 4.5 cm rim-enhancing pericolic collection containing a small locule of gas lies adjacent to the sigmoid colon. No free gas, no distant collection.',
      interpretation: 'Complicated diverticulitis — pericolic abscess (Hinchey Ib). An abscess > 3–4 cm is suitable for percutaneous drainage.',
      abnormal: true,
    },
    cultures: { report: 'Gram-negative bacilli in 1 of 2 sets at 24 hours.', interpretation: 'Bacteraemia.', abnormal: true },
    vbg: { values: [lab('Lactate', 1.6, 'mmol/L', '0.5–2.0'), lab('pH', '7.38', '', '7.35–7.45')] },
    colonoscopy: { report: 'Procedure not performed: colonoscopy is contraindicated in acute diverticulitis (perforation risk).', interpretation: 'Arrange after 6 weeks to exclude malignancy.', abnormal: true },
    'us-pelvis': { report: 'Small post-menopausal uterus and atrophic ovaries. No adnexal mass.', interpretation: 'No gynaecological cause.' },
  },
  investigationRubric: {
    essential: [
      { id: 'fbc', why: 'Inflammatory response.' },
      { id: 'crp', why: 'Inflammatory response; > 150 suggests complicated disease.' },
      { id: 'ue', why: 'Renal function before IV contrast (she takes metformin).' },
      { id: 'ct-ap', why: 'NICE NG147: CT with contrast to confirm diverticulitis and identify complications (abscess, perforation) when complicated disease is suspected.' },
    ],
    helpful: [
      { id: 'cultures', why: 'Febrile with rigors.' },
      { id: 'urine-dip', why: 'Urinary symptoms: exclude UTI; consider a colovesical fistula if pneumaturia.' },
      { id: 'glucose', why: 'Diabetic and septic.' },
      { id: 'lft', why: 'Baseline.' },
      { id: 'vbg', why: 'Lactate in sepsis.' },
    ],
    avoid: [{ id: 'colonoscopy', why: 'Colonoscopy in acute diverticulitis risks perforation — arrange it at 6 weeks.' }],
  },
  diagnosis: {
    correct: 'diverticular-abscess',
    accept: ['diverticulitis'],
    differentials: ['colorectal-cancer', 'perforated-diverticulitis', 'ischaemic-colitis', 'pyelonephritis', 'ovarian-cyst', 'crohns'],
  },
  management: {
    essential: [
      { id: 'abx-iv', why: 'Failed oral treatment with an abscess — IV antibiotics per local policy.' },
      { id: 'fluids', why: 'Febrile, tachycardic, off food.' },
      { id: 'analgesia', why: 'NICE advises paracetamol; avoid NSAIDs and use opioids with caution in diverticulitis.' },
      { id: 'drainage-radiological', why: '!A pericolic abscess of 4.5 cm should be drained percutaneously under CT/US guidance.' },
      { id: 'senior', why: 'Senior colorectal review.' },
    ],
    helpful: [
      { id: 'glucose-monitoring', why: 'Diabetic, septic; withhold metformin around contrast/AKI risk.' },
      { id: 'vte', why: 'VTE prophylaxis.' },
      { id: 'antiemetic', why: 'Nausea.' },
      { id: 'observe', why: 'Serial examination for signs of perforation.' },
    ],
    avoid: [
      { id: 'hartmanns', why: 'Surgery is reserved for generalised peritonitis (Hinchey III–IV) or failure of drainage/antibiotics.' },
      { id: 'laparotomy', why: 'No generalised peritonitis.' },
      { id: 'discharge', why: 'Septic with an abscess, having failed oral treatment.' },
      { id: 'nsaid', why: 'NSAIDs may increase the risk of perforation in diverticulitis.' },
    ],
  },
  viva: [
    {
      id: 'hinchey',
      q: 'Describe the Hinchey classification. Where does she fit?',
      options: ['Ib — pericolic abscess', 'Ia — phlegmon only', 'III — purulent peritonitis', 'IV — faecal peritonitis'],
      correct: 0,
      answer: 'Hinchey (modified): 0 mild clinical diverticulitis; Ia pericolic inflammation/phlegmon; Ib pericolic or mesocolic abscess; II pelvic, distant or retroperitoneal abscess; III generalised purulent peritonitis; IV generalised faecal peritonitis. Mrs Doyle has a pericolic abscess — Ib.',
      topic: 'Classification',
    },
    {
      id: 'pathogenesis',
      q: 'How do sigmoid diverticula form?',
      answer:
        'They are pulsion (false) diverticula: mucosa and submucosa herniate through weak points in the circular muscle where the vasa recta penetrate the bowel wall. High intraluminal pressure — from a low-fibre diet and segmentation of the narrow sigmoid — drives them. Inflammation follows obstruction of a diverticulum’s neck and micro-perforation.',
      topic: 'Pathology',
    },
    {
      id: 'nice',
      q: 'According to NICE NG147, how is uncomplicated acute diverticulitis managed in the community?',
      answer:
        'If systemically well, consider a “no antibiotic” approach with paracetamol and safety-netting (re-present if symptoms persist or worsen); offer oral antibiotics if systemically unwell, immunosuppressed or with significant comorbidity. Refer for same-day assessment if pain is uncontrolled, complications are suspected or oral fluids are not tolerated.',
      topic: 'Guidelines',
    },
    {
      id: 'colonoscopy',
      q: 'Why and when would you arrange a colonoscopy?',
      answer: 'About 6 weeks after recovery — to exclude a colorectal cancer that can mimic or coexist with diverticular disease (especially after complicated diverticulitis). Not during the acute episode, because of the perforation risk.',
      topic: 'Follow-up',
    },
    {
      id: 'complications',
      q: 'List the complications of diverticular disease.',
      answer: 'Diverticulitis, abscess, perforation with purulent or faecal peritonitis, fistula (colovesical — pneumaturia and faecaluria; colovaginal; colocutaneous), stricture causing large-bowel obstruction, and diverticular bleeding (painless, often brisk).',
      topic: 'Complications',
    },
  ],
  teaching: {
    summary:
      'Complicated sigmoid diverticulitis in a 68-year-old with previous episodes, failing oral antibiotics: LIF pain, fever and rigors, a tender LIF mass, raised inflammatory markers and a 4.5 cm pericolic abscess on CT (Hinchey Ib), managed with IV antibiotics and percutaneous drainage.',
    keyFindings: [
      'Four days of constant LIF pain, fever, rigors, loose stools',
      'Two previous milder episodes; colonoscopy showed diverticular disease',
      'LIF tenderness, guarding and a tender, fixed 5 cm mass',
      'WCC 17.2, CRP 186, bacteraemia',
      'CT: 4.5 cm pericolic abscess, no free gas',
    ],
    pearls: [
      '“Left-sided appendicitis”: think diverticulitis in older adults with LIF pain.',
      'Sterile pyuria can occur when inflamed bowel sits on the bladder.',
      'Ask about pneumaturia and faecaluria — colovesical fistula.',
      'Abscess > 3–4 cm: percutaneous drainage; generalised peritonitis: surgery.',
      'Always arrange colonoscopy after recovery to exclude cancer.',
    ],
    presentation:
      'Mrs Doyle is a 68-year-old woman with type 2 diabetes who presents with four days of constant left iliac fossa pain, fever with rigors and loose stools despite two days of oral co-amoxiclav, on a background of two previous episodes of diverticulitis. She is febrile at 38.4 °C and mildly tachycardic. There is left iliac fossa tenderness with guarding and a tender, fixed, 5 cm mass. WCC is 17.2, CRP 186, and blood cultures grow Gram-negative bacilli. CT shows sigmoid diverticulitis with a 4.5 cm pericolic abscess and no free gas — Hinchey Ib. I would admit her for IV antibiotics, fluids and paracetamol-based analgesia, monitor her glucose, and arrange CT-guided percutaneous drainage, with a colonoscopy after six weeks to exclude malignancy.',
    references: ['NICE NG147 Diverticular disease: diagnosis and management (2019)', 'Macleod’s Clinical Examination, 14th ed. — Ch. 6: abdominal masses'],
  },
}

export default c
