import type { CaseDef } from '../../engine/types'

const c: CaseDef = {
  id: 'duct-papilloma',
  title: 'Intraductal papilloma (single-duct blood-stained nipple discharge)',
  presenting: 'Blood-stained discharge from the right nipple',
  specialty: 'Breast',
  exam: 'breast',
  difficulty: 2,
  setting: 'Outpatient clinic',
  stem: 'One-stop breast clinic. Priya Nair, 44, has noticed blood-stained discharge from her right nipple. Take a history, examine her breasts with a chaperone, request investigations and explain the next steps.',
  components: ['history', 'exam', 'investigations', 'diagnosis', 'viva'],
  tags: ['nipple discharge', 'breast', 'triple assessment'],
  patient: {
    name: 'Priya Nair',
    title: 'Mrs Nair',
    age: 44,
    sex: 'female',
    dob: '08/04/1982',
    occupation: 'a pharmacist',
    appearance: { sex: 'female', age: 44, skinTone: 4, habitus: 'average', hair: 'long', hairColor: 'black', eyeColor: 'brown' },
    persona: { mood: 'anxious', style: 'normal' },
  },
  vitals: { hr: 78, rhythm: 'regular', sbp: 124, dbp: 78, rr: 14, spo2: 99, temp: 36.6, avpu: 'A', pain: 0 },
  visual: { breast: { nipple: { side: 'right', change: 'discharge' } } },
  history: {
    opening: 'I’ve been finding spots of blood on my bra, and they’re coming from my right nipple.',
    answers: {
      'br.nipple_discharge': { text: 'Small spots, red-brown, on the inside of my bra cup — maybe three or four times a week for the last six weeks. It comes on its own, without squeezing.', cue: 'touches the right breast' },
      'br.nipple_change': 'The nipple itself looks normal — it hasn’t turned in.',
      'br.skin': 'No changes to the skin.',
      'lump.when': 'I haven’t felt a lump. I’ve checked.',
      'lump.pain': 'It isn’t painful.',
      'br.cyclical': 'It doesn’t seem to change with my periods.',
      'br.menarche': 'At twelve.',
      'br.children': 'Two children; I breastfed both for about a year.',
      'br.hormones': 'I have a Mirena coil. No HRT.',
      'br.fh': 'My aunt on my father’s side had breast cancer in her sixties. No one else.',
      'br.screening': 'I’m not old enough for the screening mammogram yet.',
      'gyn.lmp': 'Two weeks ago — regular.',
      'gyn.pregnant': 'No, I have the coil.',
      'gi.weight': 'No weight loss.',
      'sys.fatigue': 'No.',
      'ros.headache': 'No headaches or problems with my eyesight.',
      'dh.meds': 'Nothing regular.',
      'dh.allergies': 'None.',
      'pmh.conditions': 'Nothing.',
      'sh.smoking': 'Never.',
      'sh.alcohol': 'A glass of wine at weekends.',
      'comm.questions': 'Is it cancer?',
    },
    key: [
      'comm.open',
      'br.nipple_discharge',
      'br.nipple_change',
      'lump.when',
      'br.skin',
      'br.cyclical',
      'br.hormones',
      'br.fh',
      'gyn.pregnant',
      'dh.meds',
      'ice.concerns',
    ],
    critical: ['br.nipple_discharge', 'lump.when'],
    ideas: 'I looked it up — it said it could be a growth in the duct.',
    concerns: 'Blood always means cancer, doesn’t it?',
    expectations: 'I want to know today if it’s serious.',
    social: { smoking: 'Never.', alcohol: 'About 4 units a week.' },
  },
  keyed: {
    'comm.pain': { text: '', says: 'No, nothing hurts.' },
    'br.inspectSide': { text: 'The breasts are symmetrical with normal contour and skin. Both nipples are everted; there is a dried brown crust on the tip of the right nipple. No eczema or ulceration of the areola.', abnormal: true, meaning: 'Crusting from discharge — Paget’s disease would involve the nipple first and spread to the areola.' },
    'br.inspectHips': { text: 'No dimpling or contour change with the pectorals tensed.' },
    'br.inspectUp': { text: 'No tethering or asymmetry with the arms raised.' },
    'br.palpNormal': { text: 'The left breast is normal.' },
    'br.palpAffected': { text: 'No discrete lump in the right breast; normal glandular nodularity. Pressing at 9 o’clock on the edge of the areola reproduces the discharge.', abnormal: true, meaning: 'A trigger point localises the duct responsible.' },
    'br.lump': { text: 'There is no palpable lump.' },
    'br.fixity': { text: 'Nothing to assess — no lump.' },
    'br.nipple': {
      text: 'Gentle pressure at 9 o’clock on the right areola expresses a bead of blood-stained fluid from a single duct opening. The left nipple produces nothing.',
      abnormal: true,
      meaning: 'Spontaneous, single-duct, blood-stained discharge — the pattern of an intraductal papilloma, but DCIS or carcinoma must be excluded.',
    },
    'br.axillaR': { text: 'No palpable right axillary nodes.' },
    'br.axillaL': { text: 'No palpable left axillary nodes.' },
    'br.scf': { text: 'No supraclavicular nodes.' },
    'complete.triple': { text: 'Triple assessment: clinical examination, imaging (mammography and ultrasound of the retroareolar ducts) and biopsy of any lesion; test the discharge for blood.' },
  },
  investigations: {
    mammo: { report: 'Dense breasts. No mass or suspicious calcification. No architectural distortion.', interpretation: 'Normal (M1) — dense tissue limits sensitivity.' },
    'us-breast': {
      report: 'Right breast, 9 o’clock, 1 cm from the nipple: a dilated duct containing a 7 mm solid, vascular intraductal lesion. Axilla normal.',
      interpretation: 'Intraductal mass (U3, indeterminate) — needs biopsy.',
      abnormal: true,
    },
    core: {
      report: 'Ultrasound-guided core biopsy: intraductal papilloma without atypia (B3 — uncertain malignant potential).',
      interpretation: 'Benign papilloma — but B3 lesions are excised or removed by vacuum biopsy because of a small risk of adjacent atypia or DCIS.',
      abnormal: true,
    },
    fna: { report: 'Fluid cytology from the discharge: red cells and benign ductal cells.', interpretation: 'Cytology of discharge is of limited value.' },
    'urine-hcg': { report: 'Negative.' },
  },
  investigationRubric: {
    essential: [
      { id: 'mammo', why: 'Age ≥ 40: mammography as part of triple assessment.' },
      { id: 'us-breast', why: 'Shows a dilated duct and intraductal lesion behind the nipple.' },
      { id: 'core', why: 'Histology of any lesion seen.' },
    ],
    helpful: [{ id: 'fna', why: 'Discharge cytology is rarely helpful.' }],
    avoid: [{ id: 'ct-cap', why: 'No indication for staging.' }],
  },
  diagnosis: {
    correct: 'intraductal-papilloma',
    differentials: ['breast-cancer', 'duct-ectasia', 'fibrocystic', 'breast-abscess'],
  },
  management: {
    essential: [
      { id: 'triple-assessment', why: 'Every single-duct, spontaneous or blood-stained discharge needs triple assessment.' },
      { id: 'microdochectomy', why: '!Diagnostic and therapeutic: excise the discharging duct (or vacuum-assisted excision of the papilloma) and send it for histology.' },
      { id: 'reassure', why: 'Explain that most blood-stained discharge is caused by a benign papilloma, while confirming it with histology.' },
    ],
    helpful: [
      { id: 'mdt', why: 'B3 results are discussed at the breast MDT.' },
      { id: '2ww', why: 'Urgent breast clinic referral for unilateral nipple discharge, bloody, or in women ≥ 50.' },
    ],
    avoid: [
      { id: 'watchful-waiting', why: 'Single-duct blood-stained discharge must be investigated and the duct excised.' },
      { id: 'abx-oral', why: 'No infection.' },
    ],
  },
  viva: [
    {
      id: 'worrying',
      q: 'Which features of nipple discharge are worrying?',
      answer: 'Single duct, unilateral, spontaneous, blood-stained or clear watery, persistent, in an older woman, or with a lump or nipple change. Reassuring: bilateral, multiduct, only on squeezing, green/cream/milky.',
      topic: 'History',
    },
    {
      id: 'causes',
      q: 'Match the discharge to its usual cause.',
      answer: 'Blood-stained single duct: intraductal papilloma (or DCIS/cancer). Green–brown multiduct, older women: duct ectasia. Milky bilateral: galactorrhoea (pregnancy, prolactinoma, drugs). Purulent: periductal mastitis or abscess (smokers).',
      topic: 'Causes',
    },
    {
      id: 'examine',
      q: 'How do you examine for nipple discharge?',
      options: ['Press systematically around the areola to find the trigger point, then note the duct and colour', 'Squeeze the nipple hard between finger and thumb', 'Only inspect — never touch the nipple', 'Ask the patient to express it at home'],
      correct: 0,
      answer: 'After inspecting and palpating both breasts and axillae, press gently around the areola like a clock face to find the trigger point; note which duct discharges, its colour, and whether it is single or multiple; test it for blood.',
      topic: 'Examination',
    },
    {
      id: 'b3',
      q: 'What does a B3 biopsy mean?',
      answer: 'A lesion of uncertain malignant potential (e.g. papilloma, radial scar, atypical hyperplasia). It is discussed at the MDT and usually removed by vacuum-assisted excision or surgery because nearby atypia or DCIS can be missed by core biopsy.',
      topic: 'Investigations',
    },
  ],
  teaching: {
    summary:
      'Intraductal papilloma in a 44-year-old: spontaneous, single-duct, blood-stained discharge from the right nipple with a trigger point at 9 o’clock and no lump; ultrasound shows a dilated duct with a small intraductal mass; core biopsy B3 papilloma — treated by microdochectomy.',
    keyFindings: [
      'Six weeks of spontaneous blood-stained spotting from the right nipple',
      'No lump, no nipple retraction, no skin change',
      'Trigger point at 9 o’clock; single-duct blood-stained discharge',
      'Ultrasound: dilated duct with a 7 mm intraductal lesion',
      'Core biopsy: papilloma without atypia (B3)',
    ],
    pearls: [
      'Blood-stained, single-duct, spontaneous discharge needs triple assessment.',
      'Find the trigger point by pressing around the areola — it tells the surgeon which duct to excise.',
      'Papilloma is the commonest cause of bloody discharge, but DCIS must be excluded.',
      'Paget’s disease starts on the nipple; eczema starts on the areola.',
    ],
    presentation:
      'Mrs Nair is a 44-year-old pharmacist with six weeks of spontaneous, blood-stained discharge from the right nipple, with no lump, pain, nipple inversion or skin change. Her paternal aunt had breast cancer in her sixties and she uses a Mirena coil. On examination the breasts are symmetrical, with dried crust on the right nipple but no eczema; there is no palpable lump or lymphadenopathy, and pressure at 9 o’clock on the right areola produces blood-stained discharge from a single duct. Mammography is normal, ultrasound shows a dilated duct with a 7 mm intraductal lesion, and core biopsy shows a papilloma without atypia. This is an intraductal papilloma. I would explain that it is benign and arrange excision of the duct by microdochectomy, with histology and MDT review.',
    references: ['Macleod’s Clinical Examination, 14th ed. — Ch. 11: the breast — nipple discharge and examination (pp. 212–216)', 'Association of Breast Surgery: nipple discharge guidance'],
  },
}

export default c
