import type { CaseDef } from '../../engine/types'

const c: CaseDef = {
  id: 'fibroadenoma',
  title: 'Fibroadenoma of the right breast',
  presenting: 'Lump in the right breast',
  specialty: 'Breast',
  exam: 'breast',
  difficulty: 1,
  setting: 'Outpatient clinic',
  stem: 'One-stop breast clinic. Priya Shah, 23, found a lump in her right breast. Take a history, examine her breasts (a chaperone is available), request investigations and explain the plan.',
  components: ['history', 'exam', 'investigations', 'diagnosis', 'viva'],
  tags: ['breast lump', 'triple assessment', 'young woman'],
  patient: {
    name: 'Priya Shah',
    title: 'Ms Shah',
    age: 23,
    sex: 'female',
    dob: '21/08/2002',
    occupation: 'a pharmacy student',
    appearance: { sex: 'female', age: 23, skinTone: 3, habitus: 'average', hair: 'long', hairColor: 'black', eyeColor: 'brown' },
    persona: { mood: 'anxious', style: 'normal' },
  },
  vitals: { hr: 78, rhythm: 'regular', sbp: 112, dbp: 70, rr: 14, spo2: 99, temp: 36.6, avpu: 'A', pain: 0 },
  visual: { breast: { lump: { side: 'right', clock: 10, distCm: 4, sizeCm: 2 } } },
  history: {
    opening: 'I found a lump in my right breast in the shower about three weeks ago and I’ve been really worried.',
    answers: {
      'lump.when': 'Three weeks ago — I found it in the shower.',
      'lump.change': 'It hasn’t changed since I found it.',
      'lump.pain': 'It doesn’t hurt. It sort of moves around when I press it.',
      'lump.other': 'No other lumps that I can feel.',
      'br.cyclical': 'It doesn’t seem to change with my periods.',
      'br.nipple_discharge': 'No discharge.',
      'br.nipple_change': 'My nipples look normal.',
      'br.skin': 'No changes in the skin.',
      'br.menarche': 'I was twelve.',
      'br.hormones': 'I’m on the combined pill.',
      'br.children': 'No children.',
      'br.fh': 'No — nobody in my family has had breast or ovarian cancer.',
      'br.screening': 'No, I’ve never had a mammogram.',
      'gyn.lmp': 'Two weeks ago.',
      'gi.weight': 'No weight loss.',
      'pmh.conditions': 'I’m healthy.',
      'dh.allergies': 'No allergies.',
      'sh.smoking': 'I don’t smoke.',
      'comm.questions': 'Is it cancer? Will I need an operation?',
    },
    key: ['comm.open', 'lump.when', 'lump.change', 'lump.pain', 'br.cyclical', 'br.nipple_discharge', 'br.nipple_change', 'br.skin', 'br.hormones', 'br.fh', 'gyn.lmp', 'gi.weight'],
    critical: ['br.fh'],
    ideas: 'I’ve been reading online and I’m scared it’s cancer.',
    concerns: 'Cancer — and whether I’ll need surgery.',
    expectations: 'To find out what it is today if possible.',
  },
  keyed: {
    'comm.pain': { text: '', says: 'No, it isn’t painful.' },
    'br.inspectSide': { text: 'Both breasts are symmetrical with normal skin and nipples. No visible lump, dimpling or scars.' },
    'br.inspectHips': { text: 'No tethering or dimpling with the pectorals tensed.' },
    'br.inspectUp': { text: 'No tethering; inframammary folds and axillae normal.' },
    'br.palpNormal': { text: 'The left breast has normal, mildly nodular glandular texture throughout with no discrete lump.' },
    'br.palpAffected': { text: 'In the upper outer quadrant of the right breast there is a discrete lump.', abnormal: true },
    'br.lump': {
      text: 'Right breast, 10 o’clock, 4 cm from the nipple: a 2 cm, smooth, well-defined, rubbery, non-tender lump that is extremely mobile — it slips away under your fingers.',
      abnormal: true,
      meaning: 'A small, smooth, rubbery, highly mobile lump in a young woman is a classic fibroadenoma (“breast mouse”). It still needs triple assessment.',
    },
    'br.fixity': { text: 'Not fixed to skin or to pectoralis major — it moves freely with the pectorals tensed.' },
    'br.nipple': { text: 'Normal nipples; no discharge can be expressed.' },
    'br.axillaR': { text: 'No palpable right axillary lymph nodes.' },
    'br.axillaL': { text: 'No palpable left axillary lymph nodes.' },
    'br.scf': { text: 'No supraclavicular or cervical lymphadenopathy.' },
    'complete.triple': { text: 'Triple assessment: clinical examination, imaging (ultrasound — she is under 40) and core biopsy.' },
  },
  criticalSteps: ['prep.chaperone', 'pa.normal', 'ln.axilla'],
  investigations: {
    'us-breast': { report: 'Right breast 10 o’clock, 4 cm from the nipple: 19 × 11 mm oval, circumscribed, wider-than-tall, homogeneously hypoechoic solid lesion (U3 — probably benign; biopsy recommended). Axilla normal.', interpretation: 'Probable fibroadenoma (U3).', abnormal: true },
    core: { report: 'Fibroadenoma. No atypia or malignancy (B2).', interpretation: 'Benign (B2) — concordant with clinical and imaging findings.' },
    mammo: { report: 'Dense breast tissue limits assessment. No suspicious mass or calcification seen.', interpretation: 'Mammography is of limited value under 40 because of dense glandular tissue.' },
  },
  investigationRubric: {
    essential: [
      { id: 'us-breast', why: '!Ultrasound is the first-line imaging under 40.' },
      { id: 'core', why: 'Core biopsy completes triple assessment.' },
    ],
    avoid: [{ id: 'mammo', why: 'Not routinely used under 40 — dense tissue and radiation.' }],
  },
  diagnosis: { correct: 'fibroadenoma', differentials: ['breast-cyst', 'breast-cancer', 'phyllodes', 'fibrocystic'] },
  management: {
    essential: [{ id: 'triple-assessment', why: '!Every breast lump needs triple assessment, even in young women.' }],
    helpful: [
      { id: 'reassure', why: 'Once concordant benign results are back: reassure; most fibroadenomas stay the same or shrink.' },
      { id: 'excision', why: 'Only if > 3 cm, growing, symptomatic or the patient prefers.' },
    ],
    avoid: [{ id: 'mdt', why: 'Not necessary for a concordant benign result — though discordant results must go to MDT.' }],
  },
  viva: [
    {
      id: 'triple',
      q: 'What does triple assessment consist of?',
      options: ['History, examination and blood tests', 'Clinical examination, imaging (US ± mammography) and biopsy (core/FNA)', 'Mammography, MRI and CT', 'Ultrasound, FNA and tumour markers'],
      correct: 1,
      answer: 'Clinical assessment (history and examination), imaging (ultrasound under 40; mammography + ultrasound 40 and over) and pathology (usually image-guided core biopsy). A lump is only reassured as benign when all three are concordant.',
      topic: 'Assessment',
    },
    {
      id: 'phyllodes',
      q: 'Which lesion can mimic a fibroadenoma but grows rapidly and needs wide excision?',
      answer: 'Phyllodes tumour — a fibroepithelial tumour, usually in women aged 40–50, that grows rapidly and can be large. It ranges from benign to malignant and is treated by wide local excision with clear margins because it recurs locally.',
      topic: 'Differentials',
    },
    {
      id: 'clock',
      q: 'How do you document the position of a breast lump?',
      answer: 'By side, clock-face position as you look at the patient (12 o’clock superior), and distance from the nipple in cm, e.g. “right breast, 10 o’clock, 4 cm from the nipple” — plus size, shape, consistency, mobility and fixity.',
      topic: 'Examination',
    },
  ],
  teaching: {
    summary: 'A young woman with a small, smooth, rubbery, highly mobile, non-tender lump and no worrying features — a fibroadenoma, confirmed by triple assessment (ultrasound U3, core biopsy B2).',
    keyFindings: ['Right breast 10 o’clock, 4 cm from the nipple', '2 cm, smooth, rubbery, well-defined', 'Highly mobile, not fixed to skin or muscle', 'No nipple, skin or nodal changes'],
    pearls: ['Always offer a chaperone and document it.', 'Examine the normal side first.', 'Under 40: ultrasound (not mammography) is the first-line imaging.', 'Every lump gets triple assessment — age alone never reassures.'],
    presentation:
      'I examined Ms Priya Shah, a 23-year-old woman, with a chaperone present. On inspection, sitting with her arms by her sides, on her hips and raised, the breasts were symmetrical with no skin or nipple changes. On palpation, the left breast was normal. In the right breast at 10 o’clock, 4 cm from the nipple, there is a 2 cm smooth, well-defined, rubbery, non-tender lump that is highly mobile and not fixed to skin or muscle. There is no nipple discharge and no axillary or supraclavicular lymphadenopathy. The most likely diagnosis is a fibroadenoma. I would complete triple assessment with an ultrasound and core biopsy.',
    references: ['Macleod’s Clinical Examination, 14th ed. — Ch. 13: The breasts', 'NICE NG12: Suspected cancer — breast', 'Association of Breast Surgery: best practice diagnostic guidelines'],
  },
}

export default c
