import type { CaseDef } from '../../engine/types'
import { CRP, FBC, lab, LFT, r, UE } from './helpers'

const c: CaseDef = {
  id: 'gastric-cancer',
  title: 'Advanced gastric adenocarcinoma with a Virchow’s node and liver metastases',
  presenting: 'Epigastric pain, early fullness and weight loss',
  specialty: 'Upper GI',
  exam: 'abdominal',
  difficulty: 2,
  setting: 'Outpatient clinic',
  stem: 'Upper GI clinic (urgent suspected-cancer referral). Stanley Turner, 71, has had epigastric pain and weight loss. Take a history, examine his abdomen, investigate and plan management.',
  components: ['history', 'exam', 'investigations', 'diagnosis', 'viva'],
  tags: ['epigastric pain', 'weight loss', 'cancer', 'Virchow’s node', '2WW'],
  patient: {
    name: 'Stanley Turner',
    title: 'Mr Turner',
    age: 71,
    sex: 'male',
    dob: '09/09/1955',
    occupation: 'a retired factory worker',
    appearance: { sex: 'male', age: 71, skinTone: 1, habitus: 'thin', hair: 'short', hairColor: 'white', eyeColor: 'grey', pallor: 0.45, cachexia: true },
    persona: { mood: 'stoic', style: 'brief' },
  },
  vitals: { hr: 88, rhythm: 'regular', sbp: 118, dbp: 72, rr: 15, spo2: 97, temp: 36.7, avpu: 'A', pain: 3 },
  history: {
    opening: 'I’ve had a gnawing pain at the top of my stomach for three months, I feel full after a few mouthfuls, and I’ve lost a lot of weight.',
    answers: {
      'pain.site': { text: 'Here, at the top of my stomach.', cue: 'points to the epigastrium' },
      'pain.onset': 'Gradually over three months.',
      'pain.character': 'A gnawing ache.',
      'pain.timing': 'Most of the day; worse after food.',
      'pain.severity': 'Three or four.',
      'pain.relieving': 'Antacids used to help; they don’t now.',
      'gi.appetite': 'I’m full after a few mouthfuls. I’ve gone off meat.',
      'gi.weight': 'A stone and a half — ten kilos — in three months.',
      'gi.vomiting': 'Sometimes I bring up food I ate hours before.',
      'gi.vomit_content': 'Old food. No blood.',
      'gi.melaena': 'My stools have been darker at times.',
      'gi.dysphagia': 'No.',
      'gi.jaundice': 'No.',
      'sys.fatigue': 'Exhausted. Breathless on the stairs.',
      'pmh.conditions': 'Nothing much. Indigestion for years.',
      'pmh.gi': 'They said I had a stomach bug — H. pylori — years ago.',
      'dh.meds': 'Omeprazole from the GP for a month; it didn’t help.',
      'dh.nsaids': 'No.',
      'dh.allergies': 'None.',
      'fh.cancer': 'My brother had stomach cancer.',
      'sh.smoking': 'Thirty a day until five years ago.',
      'sh.alcohol': 'Very little.',
      'sh.diet': 'Lots of salted and smoked fish growing up.',
      'comm.questions': 'Be honest with me — is it cancer?',
    },
    key: ['comm.open', 'pain.site', 'pain.timing', 'gi.appetite', 'gi.weight', 'gi.vomiting', 'gi.melaena', 'gi.dysphagia', 'sys.fatigue', 'dh.meds', 'dh.nsaids', 'fh.cancer', 'sh.smoking'],
    critical: ['gi.weight', 'fh.cancer'],
    ideas: 'I think it’s what my brother had.',
    concerns: 'I don’t want to suffer like he did.',
    expectations: 'I want to know where I stand.',
    pmh: 'Dyspepsia; H. pylori infection years ago.',
  },
  abdo: {
    general: { endOfBed: 'Mr Turner is a thin, pale, elderly man whose clothes are loose on him. He is comfortable at rest.' },
    hands: { temperature: 'warm', crt: 2, pallorCreases: true, koilonychia: true },
    face: { conjunctiva: 'pale', mucosa: 'moist' },
    neck: { virchow: true, nodes: 'A hard, non-tender, fixed 1.5 cm node in the left supraclavicular fossa (Virchow’s node — Troisier’s sign).' },
    abdomen: {
      shape: 'scaphoid',
      regions: {
        EPI: r(1, 2, 'none', { note: 'dull', mass: { description: 'A hard, irregular, non-tender 6 cm mass in the epigastrium that does not move with respiration.', sizeCm: 6, label: 'epigastric mass' } }),
      },
      liver: { edgeCm: 3, spanCm: 15, texture: 'hard-irregular' },
      succussionSplash: true,
      bowelSounds: 'normal',
    },
    completion: { dre: 'Dark stool; faecal occult blood would be positive.' },
  },
  criticalSteps: ['neck.nodes', 'org.liver'],
  investigations: {
    ogd: {
      report: 'A large ulcerated, heaped-up tumour on the lesser curve and antrum narrowing the pylorus, with retained food. Biopsies: poorly differentiated adenocarcinoma (intestinal type).',
      interpretation: 'Gastric adenocarcinoma with partial gastric outlet obstruction.',
      abnormal: true,
    },
    'ct-cap': {
      report: 'Thick-walled antrum and lesser curve with perigastric and coeliac nodes; three liver metastases (largest 4 cm); small-volume ascites; left supraclavicular node.',
      interpretation: 'Metastatic gastric cancer (stage IV).',
      abnormal: true,
    },
    fbc: { values: FBC(92, 7.4, 4.9, 452, 72), interpretation: 'Microcytic anaemia — iron deficiency from chronic blood loss.' },
    lft: { values: LFT(19, 44, 284, 196, 28), interpretation: 'Raised ALP and GGT, low albumin — liver metastases and malnutrition.' },
    ue: { values: UE(133, 3.4, 6.1, 74, '> 90'), interpretation: 'Mild hypokalaemia from vomiting.' },
    crp: { values: CRP(34) },
    haematinics: { values: [lab('Ferritin', '6', 'µg/L', '30–300', 'L')], interpretation: 'Iron deficiency.' },
    cea: { values: [lab('CEA', '48', 'µg/L', '< 5', 'H')], interpretation: 'Raised (not diagnostic; useful for monitoring).' },
    'us-abdo': { report: 'Multiple solid liver lesions; small-volume ascites.', interpretation: 'Liver metastases.', abnormal: true },
  },
  investigationRubric: {
    essential: [
      { id: 'ogd', why: 'Diagnosis and biopsy.' },
      { id: 'ct-cap', why: 'Staging.' },
      { id: 'fbc', why: 'Anaemia.' },
      { id: 'lft', why: 'Liver involvement, nutrition.' },
      { id: 'ue', why: 'Vomiting.' },
    ],
    helpful: [
      { id: 'haematinics', why: 'Iron deficiency.' },
      { id: 'cea', why: 'Baseline marker.' },
      { id: 'us-abdo', why: 'Liver lesions (CT is better).' },
      { id: 'crp', why: 'Baseline.' },
    ],
    avoid: [{ id: 'cxr-erect', why: 'Adds little.' }],
  },
  diagnosis: {
    correct: 'gastric-cancer',
    differentials: ['peptic-ulcer', 'goo', 'pancreatic-cancer', 'lymphoma', 'liver-mets'],
  },
  management: {
    essential: [
      { id: '2ww', why: '≥ 55 with weight loss and dyspepsia — urgent OGD.' },
      { id: 'breaking-news', why: 'Honest, compassionate conversation; he has asked directly.' },
      { id: 'mdt', why: 'Upper GI MDT.' },
      { id: 'palliative', why: '!Metastatic disease: palliative chemotherapy if fit, symptom control, and a stent or bypass for outlet obstruction.' },
      { id: 'dietitian', why: '10 kg weight loss, early satiety.' },
    ],
    helpful: [
      { id: 'iron', why: 'Iron-deficiency anaemia.' },
      { id: 'transfusion', why: 'If symptomatic anaemia.' },
      { id: 'analgesia', why: 'Pain.' },
    ],
    avoid: [
      { id: 'gastrectomy', why: 'Curative resection is not appropriate with liver metastases.' },
      { id: 'reassure', why: 'Red-flag symptoms.' },
    ],
  },
  viva: [
    {
      id: 'virchow',
      q: 'What is Troisier’s sign?',
      options: ['A palpable left supraclavicular (Virchow’s) node in abdominal malignancy', 'Periumbilical bruising', 'Pain on deep inspiration in the RUQ', 'A palpable gallbladder with jaundice'],
      correct: 0,
      answer: 'An enlarged left supraclavicular node (Virchow’s node) from gastric or other abdominal cancer — the thoracic duct drains into the left subclavian vein near it. Other signs of spread: Sister Mary Joseph nodule (umbilicus), Krukenberg tumours (ovaries), Blumer’s shelf on rectal examination.',
      topic: 'Signs',
    },
    {
      id: 'alarm',
      q: 'What are the ALARMS features in dyspepsia?',
      answer: 'Anaemia, Loss of weight, Anorexia, Recent onset of progressive symptoms, Melaena or haematemesis, Swallowing difficulty — plus an abdominal mass and age over 55. Any of these need urgent endoscopy.',
      topic: 'History',
    },
    {
      id: 'risk',
      q: 'What are the risk factors for gastric cancer?',
      answer: 'H. pylori, smoking, a diet high in salted, smoked and pickled food, pernicious anaemia/atrophic gastritis, previous partial gastrectomy, male sex, family history (and CDH1 mutation for diffuse type), blood group A.',
      topic: 'Risk',
    },
    {
      id: 'splash',
      q: 'What does a succussion splash indicate?',
      answer: 'Fluid retained in the stomach more than 3–4 hours after a meal — gastric outlet obstruction (pyloric tumour or a scarred ulcer).',
      topic: 'Signs',
    },
  ],
  teaching: {
    summary:
      'Metastatic gastric adenocarcinoma in a 71-year-old: three months of epigastric pain, early satiety, vomiting of old food, 10 kg weight loss and iron-deficiency anaemia, with an epigastric mass, a succussion splash, a hard craggy liver and a left supraclavicular node.',
    keyFindings: [
      'Epigastric pain, early satiety, 10 kg weight loss, vomiting of food eaten hours earlier',
      'Brother with gastric cancer; past H. pylori; ex-smoker',
      'Pallor, koilonychia; left supraclavicular node (Troisier’s sign)',
      'Hard epigastric mass, succussion splash, hard irregular hepatomegaly',
      'OGD: ulcerated antral tumour; CT: liver metastases',
    ],
    pearls: [
      'Always feel the left supraclavicular fossa in upper GI symptoms.',
      'Dyspepsia with alarm features → urgent OGD, not a PPI trial.',
      'A succussion splash means gastric outlet obstruction.',
      'Treatment intent depends on staging: be honest about prognosis.',
    ],
    presentation:
      'Mr Turner is a 71-year-old man with three months of gnawing epigastric pain, early satiety, vomiting of old food and 10 kilograms of weight loss, with dark stools and fatigue. He had H. pylori infection, smoked for many years and his brother had gastric cancer. He is cachectic and pale with koilonychia and a hard left supraclavicular node, a hard irregular epigastric mass, a succussion splash and hard, irregular hepatomegaly. He has a microcytic anaemia and raised ALP. OGD shows an ulcerated antral tumour — adenocarcinoma — and CT shows liver metastases. This is metastatic gastric cancer; I would break the news honestly, involve the upper GI MDT and palliative care, consider palliative chemotherapy and a stent for outlet obstruction, and support his nutrition.',
    references: ['Macleod’s Clinical Examination, 14th ed. — Ch. 6: dyspepsia, abdominal masses and the left supraclavicular node', 'NICE NG12: suspected cancer — upper GI'],
  },
}

export default c
