import type { CaseDef } from '../../engine/types'
import { FBC, lab } from './helpers'

const c: CaseDef = {
  id: 'graves',
  title: 'Graves’ disease with thyroid eye disease',
  presenting: 'Weight loss, palpitations and a neck swelling',
  specialty: 'Endocrine',
  exam: 'thyroid',
  difficulty: 2,
  setting: 'Outpatient clinic',
  stem: 'Endocrine surgery clinic. Aisha Rahman, 29, was referred with a swelling in her neck and palpitations. Take a history, examine her thyroid status and neck, request investigations and discuss management.',
  components: ['history', 'exam', 'investigations', 'diagnosis', 'viva'],
  tags: ['thyroid', 'thyrotoxicosis', 'eye signs', 'bruit'],
  patient: {
    name: 'Aisha Rahman',
    title: 'Ms Rahman',
    age: 29,
    sex: 'female',
    dob: '14/02/1997',
    occupation: 'a junior accountant',
    appearance: { sex: 'female', age: 29, skinTone: 4, habitus: 'thin', hair: 'bun', hairColor: 'black', eyeColor: 'brown', sweaty: true, flushed: 0.25 },
    persona: { mood: 'anxious', style: 'chatty' },
  },
  vitals: { hr: 112, rhythm: 'regular', sbp: 134, dbp: 68, rr: 16, spo2: 99, temp: 37.3, avpu: 'A', pain: 0 },
  visual: {
    neck: {
      goitre: { kind: 'diffuse', size: 2 },
      proptosis: 0.8,
      lidRetraction: true,
      lidLag: true,
      tremor: 0.7,
      sweaty: true,
      onycholysis: true,
      palmarErythema: true,
    },
  },
  history: {
    opening: { text: 'I’ve lost nearly a stone without trying, my heart races all the time, and my friend said my neck looks swollen.', cue: 'fidgets in her chair' },
    answers: {
      'gi.weight': 'About six kilos in three months — and I’m eating more than ever.',
      'gi.appetite': 'I’m starving all the time.',
      'thy.heat': 'I can’t stand the heat. I have the window open even in winter and I sweat all the time.',
      'thy.tremor': 'Yes, my hands shake — it’s embarrassing when I’m typing.',
      'thy.mood': 'I feel on edge and irritable. I snap at people and I can’t sleep.',
      'thy.eyes': 'My eyes feel gritty and people say I look startled. No double vision though.',
      'thy.voice': 'No, my voice is normal.',
      'thy.breathing': 'No problems breathing or swallowing.',
      'thy.radiation': 'No, never.',
      'thy.fh': 'My mum has an underactive thyroid, and my aunt has type 1 diabetes.',
      'ros.palpitations': 'Yes, all the time — especially at night. It feels fast but regular.',
      'ros.sob': 'I get out of breath climbing stairs, which never used to happen.',
      'gi.diarrhoea': 'I’m opening my bowels three or four times a day — looser than usual.',
      'gyn.cycle': 'My periods have become really light and irregular.',
      'gyn.pregnant': 'No, I’m not pregnant.',
      'gyn.contraception': 'I use condoms.',
      'lump.when': 'I only noticed the neck swelling about a month ago.',
      'lump.pain': 'It isn’t painful.',
      'pmh.conditions': 'Nothing before this.',
      'dh.meds': 'Nothing.',
      'dh.allergies': 'No allergies.',
      'sh.smoking': 'I smoke about five a day — more since I’ve been stressed.',
      'sh.alcohol': 'I don’t drink.',
      'comm.questions': 'Is it serious? Will I need an operation? We’re hoping to start a family next year.',
    },
    key: [
      'comm.open',
      'gi.weight',
      'gi.appetite',
      'thy.heat',
      'thy.tremor',
      'thy.mood',
      'thy.eyes',
      'thy.voice',
      'thy.breathing',
      'ros.palpitations',
      'gi.diarrhoea',
      'gyn.cycle',
      'gyn.pregnant',
      'thy.fh',
      'sh.smoking',
      'dh.meds',
    ],
    critical: ['gyn.pregnant', 'thy.eyes'],
    ideas: 'I’ve read online it might be my thyroid.',
    concerns: 'I’m worried about my eyes, and whether the treatment will affect having a baby.',
    expectations: 'I want to feel normal again.',
  },
  keyed: {
    'comm.pain': { text: '', says: 'No, nothing hurts.' },
    'thy.general': { text: 'A thin, restless young woman who cannot keep still, is warm and slightly sweaty, and is dressed in light clothes. She appears to stare.', abnormal: true, meaning: 'Restlessness, weight loss and heat intolerance on sight suggest thyrotoxicosis.' },
    'thy.hands': { text: 'Warm, sweaty palms with palmar erythema. Onycholysis of the ring and little fingernails. No clubbing (acropachy).', abnormal: true, meaning: 'Warm sweaty hands and onycholysis (Plummer’s nails) are peripheral signs of hyperthyroidism.' },
    'thy.tremor': { text: 'A fine postural tremor, exaggerated by the sheet of paper on her outstretched hands.', abnormal: true, meaning: 'Fine tremor from sympathetic overactivity.' },
    'thy.pulse': { text: 'Radial pulse 112 bpm, regular, bounding.', abnormal: true, meaning: 'Sinus tachycardia. Always check for atrial fibrillation in thyrotoxicosis.' },
    'thy.eyes': {
      text: 'Bilateral exophthalmos — sclera is visible below the irises — with lid retraction (sclera visible above the irises). Viewed from above, the eyes protrude beyond the brow. Mild conjunctival injection; no chemosis.',
      abnormal: true,
      meaning: 'Exophthalmos and proptosis are specific to Graves’ disease (thyroid eye disease); lid retraction can occur in any thyrotoxicosis.',
    },
    'thy.lidlag': { text: 'Lid lag is present: the upper lids lag behind the globes as she follows your finger downwards.', abnormal: true },
    'thy.eom': { text: 'Full range of eye movements; no diplopia.', meaning: 'Restricted upgaze or diplopia indicates extraocular muscle involvement — refer urgently if vision is threatened.' },
    'thy.neckInspect': { text: 'A visible, smooth, symmetrical swelling in the lower anterior neck. No scars or dilated veins.', abnormal: true },
    'thy.swallow': { text: 'The swelling moves up on swallowing.', abnormal: true, meaning: 'Moves with swallowing → thyroid (invested in pretracheal fascia).' },
    'thy.tongue': { text: 'It does not move on tongue protrusion.', meaning: 'Excludes a thyroglossal cyst.' },
    'thy.palpate': {
      text: 'From behind: a diffusely enlarged, smooth, soft, non-tender goitre involving both lobes and the isthmus, about twice normal size. No discrete nodules. You can get below it.',
      abnormal: true,
      meaning: 'A smooth diffuse goitre in a thyrotoxic young woman = Graves’ disease until proven otherwise.',
    },
    'thy.nodes': { text: 'No cervical lymphadenopathy.' },
    'thy.trachea': { text: 'Trachea central.' },
    'thy.percuss': { text: 'Resonant over the manubrium — no retrosternal extension.' },
    'thy.bruit': { text: 'A soft bruit is audible over both lobes.', abnormal: true, media: 'bruit', meaning: 'A thyroid bruit reflects increased vascularity — characteristic of Graves’ disease.' },
    'thy.pemberton': { text: 'Pemberton’s sign is negative.' },
    'thy.reflexes': { text: 'Brisk ankle reflexes.', abnormal: true },
    'thy.proximal': { text: 'She stands from the chair with her arms crossed, but with some effort.', abnormal: true, meaning: 'Mild proximal myopathy is common in thyrotoxicosis.' },
    'thy.shins': { text: 'No pretibial myxoedema.' },
  },
  criticalSteps: ['eyes.inspect', 'neck.swallow', 'neck.palpate'],
  investigations: {
    tft: {
      values: [lab('TSH', '< 0.01', 'mU/L', '0.3–4.2', 'LL'), lab('Free T4', '42.5', 'pmol/L', '12–22', 'HH'), lab('Free T3', '16.8', 'pmol/L', '3.1–6.8', 'HH'), lab('TSH-receptor antibodies (TRAb)', '12.4', 'IU/L', '< 1.8', 'H')],
      interpretation: 'Primary hyperthyroidism with positive TSH-receptor antibodies — Graves’ disease.',
    },
    fbc: { values: FBC(128, 6.1, 3.4, 260, 86, 'female'), interpretation: 'Normal — a useful baseline before carbimazole (agranulocytosis risk).' },
    'us-neck': { report: 'Diffusely enlarged, heterogeneous, hypoechoic thyroid with markedly increased vascularity on colour Doppler (“thyroid inferno”). No discrete nodules. No lymphadenopathy.', interpretation: 'Appearances of Graves’ disease.', abnormal: true },
    ecg: { report: 'Sinus tachycardia, 110 bpm. Normal axis and intervals.', interpretation: 'Sinus tachycardia — no AF.', abnormal: true },
    'urine-hcg': { report: 'Negative.', interpretation: 'Not pregnant — important before choosing treatment.' },
  },
  investigationRubric: {
    essential: [{ id: 'tft', why: '!Confirms hyperthyroidism (suppressed TSH, raised fT4/fT3); TRAb confirms Graves’.' }, { id: 'urine-hcg', why: 'Pregnancy changes the choice of antithyroid drug and rules out radioiodine.' }],
    helpful: [
      { id: 'fbc', why: 'Baseline before carbimazole.' },
      { id: 'ecg', why: 'Look for AF.' },
      { id: 'us-neck', why: 'Diffuse vascular gland; not essential if TRAb positive.' },
    ],
    avoid: [{ id: 'fna', why: 'There is no nodule — FNA has no role in a diffuse Graves’ goitre.' }],
  },
  diagnosis: { correct: 'graves', accept: ['hyperthyroidism'], differentials: ['toxic-mng', 'solitary-nodule', 'hashimoto', 'mng'] },
  management: {
    essential: [
      { id: 'carbimazole', why: 'First-line: antithyroid drug for 12–18 months (titration or block-and-replace). Warn about agranulocytosis (sore throat/fever → urgent FBC).' },
      { id: 'propranolol', why: 'Rapid symptom control (tremor, palpitations) until euthyroid.' },
      { id: 'smoking-cessation', why: '!Smoking strongly worsens thyroid eye disease and reduces treatment response.' },
    ],
    helpful: [
      { id: 'reassure', why: 'Explain the condition, pregnancy planning (switch to propylthiouracil in the first trimester) and contraception.' },
      { id: 'thyroidectomy', why: 'An option later: relapse after drugs, large goitre, or patient choice — especially with eye disease or plans for pregnancy.' },
    ],
    avoid: [{ id: 'theatre', why: 'Emergency surgery is not indicated.' }],
  },
  viva: [
    {
      id: 'eye',
      q: 'Which sign is specific to Graves’ disease rather than thyrotoxicosis of any cause?',
      options: ['Lid lag', 'Lid retraction', 'Exophthalmos / proptosis', 'Fine tremor'],
      correct: 2,
      answer: 'Exophthalmos (with proptosis, chemosis, ophthalmoplegia) and pretibial myxoedema and thyroid acropachy are specific to Graves’ disease (autoimmune). Lid lag and lid retraction are sympathetic signs that can occur in any cause of thyrotoxicosis.',
      topic: 'Signs',
    },
    {
      id: 'carb',
      q: 'What is the most important side-effect to warn a patient about when starting carbimazole?',
      options: ['Hair loss', 'Agranulocytosis', 'Hypokalaemia', 'Photosensitivity'],
      correct: 1,
      answer: 'Agranulocytosis (about 1 in 500): stop the drug and have an urgent FBC if they develop a sore throat, mouth ulcers, fever or other signs of infection. Carbimazole is also teratogenic in the first trimester (propylthiouracil is preferred then, but carries a risk of hepatotoxicity).',
      topic: 'Drugs',
    },
    {
      id: 'options',
      q: 'Outline the three definitive treatment options for Graves’ disease.',
      answer: '1) Antithyroid drugs (carbimazole/PTU) for 12–18 months — about 50% relapse. 2) Radioactive iodine — effective, but contraindicated in pregnancy/breastfeeding and can worsen active eye disease (steroid cover if mild); avoid pregnancy for 6 months. 3) Total thyroidectomy — rapid and definitive; risks include recurrent laryngeal nerve injury (hoarse voice), hypocalcaemia from hypoparathyroidism, bleeding (airway compromise), and lifelong levothyroxine.',
      topic: 'Management',
    },
    {
      id: 'storm',
      q: 'What is thyroid storm and how is it managed?',
      answer: 'A life-threatening decompensated thyrotoxicosis (fever, tachyarrhythmia, heart failure, agitation/confusion, GI upset), often triggered by infection, surgery or stopping medication. Management in HDU/ICU: supportive care and cooling, high-dose propranolol, propylthiouracil (blocks conversion of T4 to T3), then iodine (Lugol’s) an hour later, IV hydrocortisone, and treat the trigger.',
      topic: 'Emergencies',
    },
  ],
  teaching: {
    summary:
      'A young woman with weight loss, heat intolerance, palpitations and tremor has a smooth diffuse goitre with a bruit, exophthalmos, lid retraction and lid lag — Graves’ disease, confirmed by suppressed TSH, high fT4/fT3 and positive TSH-receptor antibodies.',
    keyFindings: [
      'Restless, thin, sweaty; sinus tachycardia 112',
      'Fine tremor, warm sweaty hands, onycholysis, palmar erythema',
      'Exophthalmos, lid retraction and lid lag',
      'Smooth diffuse goitre that moves on swallowing, with a bruit',
    ],
    pearls: [
      'In a thyroid OSCE assess three things: the gland (look, feel, listen), thyroid status, and eye signs.',
      'Look at the eyes from the side and from above to judge proptosis.',
      'A bruit over a diffuse goitre suggests Graves’ disease.',
      'Always ask about pregnancy plans — it changes drug choice and rules out radioiodine.',
    ],
    presentation:
      'I examined Ms Aisha Rahman, a 29-year-old woman who appeared thin, restless and sweaty. She had a regular tachycardia of 112, warm sweaty hands with palmar erythema and onycholysis, and a fine postural tremor. There was bilateral exophthalmos with lid retraction and lid lag, without ophthalmoplegia. In the neck there was a visible, smooth, diffuse goitre about twice normal size that moved on swallowing but not on tongue protrusion; it was soft and non-tender with no nodules or lymphadenopathy, the trachea was central, there was no retrosternal dullness, and a bruit was audible over both lobes. Reflexes were brisk. These findings suggest Graves’ disease. I would confirm with thyroid function tests and TSH-receptor antibodies.',
    references: ['Macleod’s Clinical Examination, 14th ed. — Ch. 10: The endocrine system (thyroid)', 'NICE NG145: Thyroid disease — assessment and management (2019)'],
  },
}

export default c
