import type { CaseDef } from '../../engine/types'
import { CRP, FBC, lab, LFT, r, UE } from './helpers'

const c: CaseDef = {
  id: 'hydatid-cyst',
  title: 'Hydatid cyst of the liver (Echinococcus granulosus)',
  presenting: 'Dull right upper quadrant ache and a feeling of fullness',
  specialty: 'Hepatobiliary',
  exam: 'abdominal',
  difficulty: 3,
  setting: 'Outpatient clinic',
  stem: 'Hepatobiliary clinic. Omar Haddad, 39, has had a dull ache under his right ribs for four months. Take a history, examine his abdomen, request investigations and outline management.',
  components: ['history', 'exam', 'investigations', 'diagnosis', 'viva'],
  tags: ['RUQ pain', 'liver cyst', 'hepatomegaly', 'parasite'],
  patient: {
    name: 'Omar Haddad',
    title: 'Mr Haddad',
    age: 39,
    sex: 'male',
    dob: '06/03/1987',
    occupation: 'a farmer',
    appearance: { sex: 'male', age: 39, skinTone: 4, habitus: 'average', hair: 'short', hairColor: 'black', eyeColor: 'brown', facialHair: 'stubble', jaundice: 0.15 },
    persona: { mood: 'calm', style: 'normal' },
  },
  vitals: { hr: 76, rhythm: 'regular', sbp: 126, dbp: 78, rr: 14, spo2: 98, temp: 36.8, avpu: 'A', pain: 3 },
  history: {
    opening: 'I have had a heavy, dull pain under my right ribs for about four months. My stomach feels full on the right.',
    answers: {
      'pain.site': { text: 'Under the right ribs, and sometimes in the right shoulder.', cue: 'presses his right upper quadrant' },
      'pain.onset': 'Slowly — I can’t say exactly when.',
      'pain.character': 'Dull and heavy, like a weight.',
      'pain.radiation': 'Sometimes to the right shoulder.',
      'pain.timing': 'Most of the time; worse after a big meal.',
      'pain.severity': 'Three out of ten.',
      'pain.exacerbating': 'Bending forward, big meals.',
      'pain.relieving': 'Paracetamol helps a little.',
      'gi.jaundice': 'My wife said my eyes looked a little yellow last week.',
      'gi.itch': 'A bit itchy recently.',
      'gi.dark_urine': 'Maybe darker in the mornings.',
      'gi.stool_colour': 'Normal colour.',
      'gi.nausea': 'Sometimes.',
      'gi.appetite': 'A bit less than usual.',
      'gi.weight': 'Maybe two kilos.',
      'sys.fever': 'No fevers.',
      'sys.rigors': 'No.',
      'ros.cough': 'No.',
      'ros.joints': 'Once I had an itchy rash — hives — for a day.',
      'sh.animals': 'I keep sheep, and we have three dogs that help with the flock. The dogs get the offal when we slaughter.',
      'sh.occupation': 'Farmer — sheep and some goats.',
      'sh.travel': 'I grew up in a farming village in the Middle East and moved here five years ago.',
      'sh.alcohol': 'I don’t drink.',
      'sh.smoking': 'Never.',
      'pmh.conditions': 'Healthy.',
      'pmh.surgery': 'None.',
      'dh.meds': 'Only paracetamol.',
      'dh.allergies': 'None.',
      'fh.general': 'My uncle had an operation on his liver for a cyst many years ago.',
      'comm.questions': 'What is this lump in my liver?',
    },
    key: [
      'comm.open',
      'pain.site',
      'pain.character',
      'pain.timing',
      'gi.jaundice',
      'gi.itch',
      'gi.dark_urine',
      'gi.stool_colour',
      'gi.weight',
      'sys.fever',
      'sh.animals',
      'sh.occupation',
      'sh.travel',
      'sh.alcohol',
      'dh.meds',
    ],
    critical: ['sh.animals'],
    ideas: 'My uncle had a liver cyst from the dogs — I wondered about that.',
    concerns: 'That it could burst.',
    expectations: 'To get rid of it safely.',
    social: { travel: 'Grew up in a rural sheep-farming area; moved five years ago.', smoking: 'Never.', alcohol: 'None.' },
  },
  abdo: {
    general: { endOfBed: 'Mr Haddad looks well and comfortable. There is a faint yellow tinge to his sclerae.' },
    hands: { temperature: 'warm', crt: 2 },
    face: { sclera: 'icteric' },
    abdomen: {
      shape: 'flat',
      inspectionExtra: 'A subtle fullness under the right costal margin.',
      regions: {
        RUQ: r(1, 1, 'none', { note: 'dull', mass: { description: 'A smooth, rounded, non-tender swelling continuous with the liver edge, 5 cm below the right costal margin; it moves down with inspiration. Slightly cystic in feel.', sizeCm: 9, tender: false, movesWithRespiration: true, label: 'smooth RUQ mass (liver)' } }),
        EPI: r(0, 0, 'none', { note: 'dull' }),
      },
      liver: { edgeCm: 5, spanCm: 18, texture: 'smooth', tender: false },
      gallbladder: { palpable: false, murphy: false },
      spleen: { tipCm: 0 },
      bowelSounds: 'normal',
    },
    completion: { urinalysis: 'Bilirubin +.' },
  },
  criticalSteps: ['org.liver'],
  investigations: {
    'us-abdo': {
      report: 'A 9 cm well-defined cyst in segments VI/VII of the right lobe of the liver containing multiple internal daughter cysts (‘honeycomb’ appearance) and floating echogenic debris (‘hydatid sand’). Mild intrahepatic duct dilatation adjacent to the cyst. Gallbladder normal.',
      interpretation: 'Hydatid cyst (WHO CE2 — active).',
      abnormal: true,
    },
    'ct-ap': {
      report: 'A 9 cm multiloculated cyst with daughter cysts and a peripherally calcified wall in the right lobe; mild compression of the right hepatic duct. No other cysts in the liver; lungs clear on the included bases.',
      interpretation: 'Hepatic hydatid cyst, probably compressing the right duct.',
      abnormal: true,
    },
    'hydatid-serology': { report: 'Echinococcus granulosus IgG ELISA positive (confirmed by western blot).', interpretation: 'Supports hydatid disease (a negative test does not exclude it).', abnormal: true },
    fbc: {
      values: [...FBC(142, 9.4, 5.2, 276), lab('Eosinophils', '1.1', '×10⁹/L', '0.0–0.5', 'H')],
      interpretation: 'Eosinophilia — common in helminth infection.',
    },
    lft: { values: LFT(36, 48, 212, 168, 40), interpretation: 'Mild cholestatic picture — compression of, or communication with, the bile ducts.' },
    crp: { values: CRP(8) },
    ue: { values: UE(140, 4.2, 4.8, 82, '> 90') },
    mrcp: { report: 'No communication with the biliary tree demonstrated; mild compression of the right hepatic duct.', interpretation: 'No frank cystobiliary communication.' },
    core: { report: 'Biopsy not performed.', interpretation: 'Never biopsy or blindly aspirate a suspected hydatid cyst — risk of anaphylaxis and spread.' },
    'cxr-erect': { report: 'Clear lungs. No pulmonary cysts.' },
  },
  investigationRubric: {
    essential: [
      { id: 'us-abdo', why: 'First-line: daughter cysts and hydatid sand are characteristic.' },
      { id: 'hydatid-serology', why: 'Confirms the diagnosis.' },
      { id: 'lft', why: 'Cholestasis suggests duct compression or communication.' },
      { id: 'fbc', why: 'Eosinophilia.' },
      { id: 'ct-ap', why: 'Maps the cyst(s) for treatment planning.' },
    ],
    helpful: [
      { id: 'mrcp', why: 'Looks for communication with the bile ducts.' },
      { id: 'cxr-erect', why: 'The lung is the second commonest site.' },
      { id: 'crp', why: 'Infection of the cyst.' },
    ],
    avoid: [{ id: 'core', why: 'Percutaneous biopsy can cause anaphylaxis and seed the peritoneum.' }],
  },
  diagnosis: {
    correct: 'hydatid-cyst',
    differentials: ['liver-abscess', 'liver-mets', 'choledocholithiasis', 'cholangiocarcinoma', 'hepatitis'],
  },
  management: {
    essential: [
      { id: 'albendazole', why: '!Albendazole before and after intervention; then surgery (cystectomy) or PAIR (puncture, aspiration, injection of scolicide, re-aspiration) depending on the cyst stage.' },
      { id: 'mdt', why: 'Hepatobiliary MDT: stage (WHO-IWGE) and choose treatment.' },
      { id: 'consent', why: 'Discuss risks — rupture, anaphylaxis, bile leak.' },
      { id: 'reassure', why: 'Explain the cause (dog tapeworm eggs) and that it is treatable.' },
    ],
    helpful: [
      { id: 'lifestyle', why: 'Deworm the dogs regularly, don’t feed them offal, wash hands — and check family members.' },
      { id: 'analgesia', why: 'For the ache.' },
    ],
    avoid: [
      { id: 'drainage-radiological', why: 'Simple drainage without scolicide and drug cover risks anaphylaxis and spillage.' },
      { id: 'discharge', why: 'An active cyst near the ducts needs treatment.' },
    ],
  },
  viva: [
    {
      id: 'lifecycle',
      q: 'Describe the life cycle of Echinococcus granulosus.',
      answer: 'Dogs are the definitive host (adult tapeworm in the gut) and pass eggs in faeces. Sheep (and humans, accidentally) swallow the eggs; larvae cross the gut wall and lodge in the liver (~70%) and lungs (~20%), forming slowly growing cysts. Dogs are reinfected by eating infected sheep offal.',
      topic: 'Microbiology',
    },
    {
      id: 'comp',
      q: 'What are the complications of a hydatid cyst?',
      answer: 'Rupture into the biliary tree (cholangitis, obstructive jaundice), into the peritoneum (anaphylaxis, secondary hydatidosis) or into the chest; secondary bacterial infection (abscess); compression of ducts and vessels.',
      topic: 'Complications',
    },
    {
      id: 'aspirate',
      q: 'Why should you not aspirate a suspected hydatid cyst diagnostically?',
      options: ['Risk of anaphylaxis and seeding of protoscolices', 'It is always sterile', 'It is too deep to reach', 'Aspiration is diagnostic'],
      correct: 0,
      answer: 'Cyst fluid is highly antigenic: leakage can cause anaphylaxis and spread protoscolices to form new cysts. PAIR is only done deliberately, under albendazole cover with a scolicide.',
      topic: 'Management',
    },
    {
      id: 'jaundice',
      q: 'How do you classify jaundice?',
      answer: 'Pre-hepatic (haemolysis: unconjugated, no bilirubin in urine), hepatic (hepatitis, cirrhosis, drugs) and post-hepatic/obstructive (stones, tumour, compression: pale stools, dark urine, itch, raised ALP and GGT).',
      topic: 'Jaundice',
    },
  ],
  teaching: {
    summary:
      'Hepatic hydatid cyst in a sheep farmer who feeds offal to his dogs: four months of dull RUQ ache, smooth hepatomegaly with a cystic mass, mild cholestatic jaundice and eosinophilia; ultrasound shows daughter cysts and hydatid sand, serology is positive.',
    keyFindings: [
      'Dull, heavy RUQ ache for four months; early fullness after meals',
      'Sheep farmer with working dogs fed on offal; uncle had a liver cyst',
      'Mild scleral icterus, itch; smooth hepatomegaly 5 cm with a cystic RUQ mass',
      'Eosinophilia; mildly cholestatic LFTs',
      'Ultrasound: 9 cm cyst with daughter cysts and hydatid sand; serology positive',
    ],
    pearls: [
      'Ask about dogs, sheep, farming and where they grew up in every patient with a liver cyst.',
      'Daughter cysts and hydatid sand on ultrasound are characteristic.',
      'Never biopsy or blindly aspirate a possible hydatid cyst.',
      'Albendazole covers every intervention.',
    ],
    presentation:
      'Mr Haddad is a 39-year-old sheep farmer who grew up in a rural sheep-farming area, with four months of a dull, heavy right upper quadrant ache radiating to the right shoulder, early fullness and, recently, mild itch and yellow eyes. His working dogs are fed offal, and his uncle had a liver cyst removed. On examination he has mild scleral icterus and smooth hepatomegaly 5 centimetres below the costal margin with a non-tender, cystic swelling that moves with respiration. Bloods show eosinophilia and a mild cholestatic picture. Ultrasound shows a 9 centimetre cyst with daughter cysts and hydatid sand, and serology is positive. This is a hepatic hydatid cyst. I would start albendazole and refer to the hepatobiliary MDT for surgery or PAIR, avoiding any biopsy, and advise deworming the dogs.',
    references: ['Macleod’s Clinical Examination, 14th ed. — Ch. 6: palpation of the liver and jaundice', 'WHO-IWGE expert consensus on cystic echinococcosis'],
  },
}

export default c
