import type { CaseDef, CaseMeta } from '../../engine/types'

/**
 * The ward list. Metadata is kept here so the library renders instantly; the
 * full case (history script, findings, results, viva) loads on demand.
 */
export const CASES: CaseMeta[] = [
  {
    id: 'appendicitis',
    presenting: 'Right iliac fossa pain',
    specialty: 'Emergency general surgery',
    exam: 'abdominal',
    difficulty: 1,
    setting: 'Emergency department',
    patientLabel: 'James Carter',
    sex: 'male',
    age: 24,
    tags: ['acute abdomen', 'RIF pain'],
    load: () => import('./appendicitis').then((m) => m.default),
  },
  {
    id: 'cholecystitis',
    presenting: 'Right upper quadrant pain and fever',
    specialty: 'Hepatobiliary',
    exam: 'abdominal',
    difficulty: 1,
    setting: 'Surgical assessment unit',
    patientLabel: 'Sandra Hughes',
    sex: 'female',
    age: 46,
    tags: ['RUQ pain', 'gallstones'],
    load: () => import('./cholecystitis').then((m) => m.default),
  },
  {
    id: 'sbo-femoral',
    presenting: 'Vomiting and abdominal distension',
    specialty: 'Emergency general surgery',
    exam: 'abdominal',
    difficulty: 2,
    setting: 'Emergency department',
    patientLabel: 'Edith Clarke',
    sex: 'female',
    age: 83,
    tags: ['obstruction', 'hernia', 'elderly'],
    load: () => import('./sbo-femoral').then((m) => m.default),
  },
  {
    id: 'perforated-du',
    presenting: 'Sudden severe epigastric pain',
    specialty: 'Upper GI',
    exam: 'abdominal',
    difficulty: 2,
    setting: 'Emergency department',
    patientLabel: 'Marcus Reid',
    sex: 'male',
    age: 52,
    tags: ['peritonitis', 'NSAIDs'],
    load: () => import('./perforated-du').then((m) => m.default),
  },
  {
    id: 'pancreatitis',
    presenting: 'Epigastric pain radiating to the back',
    specialty: 'Hepatobiliary',
    exam: 'abdominal',
    difficulty: 2,
    setting: 'Emergency department',
    patientLabel: 'Daniel Kowalski',
    sex: 'male',
    age: 44,
    tags: ['epigastric pain', 'alcohol'],
    load: () => import('./pancreatitis').then((m) => m.default),
  },
  {
    id: 'diverticulitis',
    presenting: 'Left iliac fossa pain and fever',
    specialty: 'Colorectal',
    exam: 'abdominal',
    difficulty: 2,
    setting: 'Surgical assessment unit',
    patientLabel: 'Patricia Doyle',
    sex: 'female',
    age: 68,
    tags: ['LIF pain', 'abscess'],
    load: () => import('./diverticulitis').then((m) => m.default),
  },
  {
    id: 'cholangitis',
    presenting: 'Fever, jaundice and RUQ pain',
    specialty: 'Hepatobiliary',
    exam: 'abdominal',
    difficulty: 2,
    setting: 'Emergency department',
    patientLabel: 'Samuel Okoye',
    sex: 'male',
    age: 72,
    tags: ['jaundice', 'sepsis'],
    load: () => import('./cholangitis').then((m) => m.default),
  },
  {
    id: 'ruptured-aaa',
    presenting: 'Collapse with abdominal and back pain',
    specialty: 'Vascular',
    exam: 'abdominal',
    difficulty: 3,
    setting: 'Emergency department',
    patientLabel: 'George Harris',
    sex: 'male',
    age: 74,
    tags: ['shock', 'vascular'],
    load: () => import('./ruptured-aaa').then((m) => m.default),
  },
  {
    id: 'mesenteric-ischaemia',
    presenting: 'Severe central abdominal pain',
    specialty: 'Vascular',
    exam: 'abdominal',
    difficulty: 3,
    setting: 'Emergency department',
    patientLabel: 'Margaret Walsh',
    sex: 'female',
    age: 79,
    tags: ['AF', 'lactate'],
    load: () => import('./mesenteric-ischaemia').then((m) => m.default),
  },
  {
    id: 'pancreatic-cancer',
    presenting: 'Painless jaundice and weight loss',
    specialty: 'Hepatobiliary',
    exam: 'abdominal',
    difficulty: 2,
    setting: 'Surgical assessment unit',
    patientLabel: 'Ahmed Hassan',
    sex: 'male',
    age: 68,
    tags: ['jaundice', 'cancer'],
    load: () => import('./pancreatic-cancer').then((m) => m.default),
  },
  {
    id: 'caecal-cancer',
    presenting: 'Tiredness, weight loss and a lump in the tummy',
    specialty: 'Colorectal',
    exam: 'abdominal',
    difficulty: 2,
    setting: 'Outpatient clinic',
    patientLabel: 'Joyce Palmer',
    sex: 'female',
    age: 76,
    tags: ['RIF mass', 'anaemia'],
    load: () => import('./caecal-cancer').then((m) => m.default),
  },
  {
    id: 'liver-disease',
    presenting: 'OSCE: examine this abdomen — swelling',
    specialty: 'Hepatobiliary',
    exam: 'abdominal',
    difficulty: 2,
    setting: 'Surgical ward',
    patientLabel: 'Kwame Mensah',
    sex: 'male',
    age: 55,
    tags: ['OSCE', 'ascites', 'stigmata'],
    load: () => import('./liver-disease').then((m) => m.default),
  },
  {
    id: 'ileostomy',
    presenting: 'OSCE: examine this abdomen — stoma',
    specialty: 'Colorectal',
    exam: 'abdominal',
    difficulty: 1,
    setting: 'Outpatient clinic',
    patientLabel: 'Tom Bennett',
    sex: 'male',
    age: 34,
    tags: ['OSCE', 'stoma'],
    load: () => import('./ileostomy').then((m) => m.default),
  },

  /* ------------------------------ Examination stations ------------------------------ */
  {
    id: 'inguinal-hernia',
    presenting: 'Lump in the right groin',
    specialty: 'Hernia & abdominal wall',
    exam: 'groin',
    difficulty: 1,
    setting: 'Outpatient clinic',
    patientLabel: 'Daniel Okafor',
    sex: 'male',
    age: 38,
    tags: ['OSCE', 'hernia'],
    load: () => import('./inguinal-hernia').then((m) => m.default),
  },
  {
    id: 'femoral-hernia',
    presenting: 'OSCE: examine this patient’s groin',
    specialty: 'Hernia & abdominal wall',
    exam: 'groin',
    difficulty: 2,
    setting: 'Outpatient clinic',
    patientLabel: 'Margaret Hill',
    sex: 'female',
    age: 71,
    tags: ['OSCE', 'hernia', 'femoral'],
    load: () => import('./femoral-hernia').then((m) => m.default),
  },
  {
    id: 'direct-hernia',
    presenting: 'OSCE: examine this gentleman’s groin',
    specialty: 'Hernia & abdominal wall',
    exam: 'groin',
    difficulty: 2,
    setting: 'Outpatient clinic',
    patientLabel: 'George Palmer',
    sex: 'male',
    age: 76,
    tags: ['OSCE', 'hernia'],
    load: () => import('./direct-hernia').then((m) => m.default),
  },
  {
    id: 'lipoma',
    presenting: 'Lump on the forearm',
    specialty: 'Skin & soft tissue',
    exam: 'lump',
    difficulty: 1,
    setting: 'Outpatient clinic',
    patientLabel: 'Paul Whitaker',
    sex: 'male',
    age: 47,
    tags: ['lump', 'sarcoma red flags'],
    load: () => import('./lipoma').then((m) => m.default),
  },
  {
    id: 'epidermoid-cyst',
    presenting: 'OSCE: examine this lump on the back',
    specialty: 'Skin & soft tissue',
    exam: 'lump',
    difficulty: 1,
    setting: 'Outpatient clinic',
    patientLabel: 'Chloe Barker',
    sex: 'female',
    age: 32,
    tags: ['OSCE', 'lump'],
    load: () => import('./epidermoid-cyst').then((m) => m.default),
  },
  {
    id: 'graves',
    presenting: 'Weight loss, palpitations and a neck swelling',
    specialty: 'Endocrine',
    exam: 'thyroid',
    difficulty: 2,
    setting: 'Outpatient clinic',
    patientLabel: 'Aisha Rahman',
    sex: 'female',
    age: 29,
    tags: ['thyroid', 'eye signs'],
    load: () => import('./graves').then((m) => m.default),
  },
  {
    id: 'mng',
    presenting: 'Neck swelling',
    specialty: 'Endocrine',
    exam: 'thyroid',
    difficulty: 2,
    setting: 'Outpatient clinic',
    patientLabel: 'Linda Carter',
    sex: 'female',
    age: 58,
    tags: ['thyroid', 'goitre'],
    load: () => import('./mng').then((m) => m.default),
  },
  {
    id: 'thyroglossal-cyst',
    presenting: 'OSCE: examine this patient’s neck lump',
    specialty: 'Endocrine',
    exam: 'thyroid',
    difficulty: 1,
    setting: 'Outpatient clinic',
    patientLabel: 'Holly Evans',
    sex: 'female',
    age: 19,
    tags: ['OSCE', 'neck lump'],
    load: () => import('./thyroglossal-cyst').then((m) => m.default),
  },
  {
    id: 'fibroadenoma',
    presenting: 'Lump in the right breast',
    specialty: 'Breast',
    exam: 'breast',
    difficulty: 1,
    setting: 'Outpatient clinic',
    patientLabel: 'Priya Shah',
    sex: 'female',
    age: 23,
    tags: ['breast lump', 'triple assessment'],
    load: () => import('./fibroadenoma').then((m) => m.default),
  },
  {
    id: 'breast-cancer',
    presenting: 'Lump in the left breast',
    specialty: 'Breast',
    exam: 'breast',
    difficulty: 2,
    setting: 'Outpatient clinic',
    patientLabel: 'Janet Morris',
    sex: 'female',
    age: 64,
    tags: ['breast lump', '2WW'],
    load: () => import('./breast-cancer').then((m) => m.default),
  },
  {
    id: 'clti',
    presenting: 'Painful right foot with a non-healing ulcer',
    specialty: 'Vascular',
    exam: 'arterial',
    difficulty: 3,
    setting: 'Surgical ward',
    patientLabel: 'Raymond Cole',
    sex: 'male',
    age: 72,
    tags: ['rest pain', 'gangrene', 'Buerger’s test'],
    load: () => import('./clti').then((m) => m.default),
  },
  {
    id: 'claudication',
    presenting: 'Calf pain on walking',
    specialty: 'Vascular',
    exam: 'arterial',
    difficulty: 2,
    setting: 'Outpatient clinic',
    patientLabel: 'Steven Ward',
    sex: 'male',
    age: 64,
    tags: ['claudication', 'ABPI'],
    load: () => import('./claudication').then((m) => m.default),
  },
  {
    id: 'venous-ulcer',
    presenting: 'Leg ulcer and varicose veins',
    specialty: 'Vascular',
    exam: 'venous',
    difficulty: 2,
    setting: 'Outpatient clinic',
    patientLabel: 'Beverley Grant',
    sex: 'female',
    age: 58,
    tags: ['varicose veins', 'ulcer'],
    load: () => import('./venous-ulcer').then((m) => m.default),
  },
  {
    id: 'testicular-torsion',
    presenting: 'Sudden severe left testicular pain',
    specialty: 'Urology',
    exam: 'scrotal',
    difficulty: 2,
    setting: 'Emergency department',
    patientLabel: 'Ethan Brooks',
    sex: 'male',
    age: 15,
    tags: ['acute scrotum', 'emergency'],
    load: () => import('./testicular-torsion').then((m) => m.default),
  },
  {
    id: 'hydrocele',
    presenting: 'OSCE: examine this gentleman’s scrotum',
    specialty: 'Urology',
    exam: 'scrotal',
    difficulty: 1,
    setting: 'Outpatient clinic',
    patientLabel: 'Harold Jenkins',
    sex: 'male',
    age: 67,
    tags: ['OSCE', 'scrotal swelling'],
    load: () => import('./hydrocele').then((m) => m.default),
  },
  {
    id: 'testicular-tumour',
    presenting: 'Painless lump in the left testis',
    specialty: 'Urology',
    exam: 'scrotal',
    difficulty: 2,
    setting: 'Outpatient clinic',
    patientLabel: 'Marcus Bell',
    sex: 'male',
    age: 29,
    tags: ['scrotal lump', 'cancer'],
    load: () => import('./testicular-tumour').then((m) => m.default),
  },
]

export const CASE_META: Record<string, CaseMeta> = Object.fromEntries(CASES.map((c) => [c.id, c]))

const cache = new Map<string, CaseDef>()

export async function loadCase(id: string): Promise<CaseDef | null> {
  if (cache.has(id)) return cache.get(id)!
  const meta = CASE_META[id]
  if (!meta) return null
  const c = await meta.load()
  cache.set(id, c)
  return c
}

export function cachedCase(id: string): CaseDef | undefined {
  return cache.get(id)
}
