import type { CaseDef } from '../../engine/types'

const c: CaseDef = {
  id: 'inguinal-hernia',
  title: 'Right indirect inguinal hernia',
  presenting: 'Lump in the right groin',
  specialty: 'Hernia & abdominal wall',
  exam: 'groin',
  difficulty: 1,
  setting: 'Outpatient clinic',
  stem: 'General surgery clinic. Daniel Okafor, 38, has been referred by his GP with a lump in his right groin. Take a focused history, examine his groin and discuss your management.',
  components: ['history', 'exam', 'diagnosis', 'viva'],
  tags: ['OSCE', 'hernia', 'groin lump', 'deep ring occlusion'],
  patient: {
    name: 'Daniel Okafor',
    title: 'Mr Okafor',
    age: 38,
    sex: 'male',
    dob: '02/06/1987',
    occupation: 'a scaffolder',
    appearance: {
      sex: 'male',
      age: 38,
      skinTone: 5,
      habitus: 'average',
      hair: 'crop',
      hairColor: 'black',
      eyeColor: 'brown',
      facialHair: 'stubble',
      hernias: [{ kind: 'inguinal-indirect', side: 'right', size: 'medium', visible: 'standing' }],
    },
    persona: { mood: 'calm', style: 'normal' },
  },
  vitals: { hr: 68, rhythm: 'regular', sbp: 126, dbp: 78, rr: 14, spo2: 99, temp: 36.7, avpu: 'A', pain: 1 },
  history: {
    opening: { text: 'I’ve got this lump in my right groin. It comes and goes, and it’s been bothering me at work.', cue: 'points to his right groin' },
    answers: {
      'lump.when': 'About three months ago. I noticed it after a long day lifting boards at work.',
      'lump.how': 'I felt a bulge in the shower one evening, just above my — you know, the crease at the top of my leg.',
      'lump.change': 'It seems to come out more now than it did at first. It’s maybe the size of a golf ball when it’s out.',
      'lump.pain': 'It’s not really painful — more of a dragging ache by the end of the day.',
      'lump.reduce': 'Yes — when I lie down it goes away on its own, or I can push it back in myself.',
      'lump.cough': 'Definitely. If I cough or lift something heavy it pops straight out.',
      'lump.obstruct': 'No, it’s never got stuck. No sickness, and I’m going to the toilet normally.',
      'lump.lifting': 'All the time — I’m a scaffolder. I lift heavy poles and boards all day.',
      'lump.other': 'No, just this one. The left side is fine.',
      'scr.swelling': 'Sometimes it seems to go a little way down towards my right testicle when it’s been out all day.',
      'gi.constipation': 'No, my bowels are regular.',
      'gu.stream': 'No problems passing water.',
      'ros.cough': 'No, I don’t have a cough.',
      'pmh.conditions': 'Nothing — I’m fit and well.',
      'pmh.surgery': 'Never had an operation.',
      'pmh.anaesthetic': 'I’ve never had an anaesthetic.',
      'dh.meds': 'I don’t take anything regularly.',
      'dh.anticoag': 'No blood thinners.',
      'dh.allergies': 'No allergies.',
      'fh.general': 'My dad had a hernia repaired when he was about fifty.',
      'sh.smoking': 'I stopped smoking five years ago. I used to smoke about ten a day.',
      'sh.alcohol': 'A few beers at the weekend.',
      'sh.occupation': 'I’m a self-employed scaffolder — if I’m not working, I’m not earning.',
      'sh.living': 'With my wife and two kids.',
      'comm.questions': 'Do I need an operation? And how long would I be off work afterwards?',
    },
    key: [
      'comm.open',
      'lump.when',
      'lump.change',
      'lump.pain',
      'lump.reduce',
      'lump.cough',
      'lump.obstruct',
      'lump.lifting',
      'scr.swelling',
      'gi.constipation',
      'gu.stream',
      'ros.cough',
      'pmh.conditions',
      'dh.anticoag',
      'dh.allergies',
      'sh.smoking',
      'sh.occupation',
    ],
    critical: ['lump.obstruct'],
    ideas: 'I think it’s a hernia — my dad had one.',
    concerns: 'I’m worried it could get stuck, and I can’t afford much time off work.',
    expectations: 'I’d like it fixed so I can keep working without it getting worse.',
  },
  keyed: {
    'comm.pain': { text: '', says: 'It’s not painful now — just aches by the end of the day.' },
    'groin.inspect': {
      text: 'Standing, there is a smooth, oval swelling about 4 × 3 cm in the right groin, lying above the medial half of the inguinal ligament and extending obliquely down towards the top of the scrotum. The skin is normal; there are no scars. The left groin looks normal.',
      abnormal: true,
      meaning: 'An oblique swelling above the inguinal ligament, heading towards the scrotum, is the typical shape of an indirect inguinal hernia.',
    },
    'groin.coughLook': { text: 'On coughing, the right groin swelling visibly enlarges. Nothing appears on the left.', abnormal: true, meaning: 'A visible cough impulse — the swelling communicates with the abdominal cavity.' },
    'groin.palpate': {
      text: 'A soft, non-tender, smooth swelling of normal temperature, about 4 × 3 cm. It feels compressible.',
      abnormal: true,
    },
    'groin.tubercle': {
      text: 'The swelling lies above and medial to the right pubic tubercle.',
      abnormal: true,
      meaning: 'Above and medial to the pubic tubercle = inguinal; below and lateral = femoral.',
    },
    'groin.coughFeel': { text: 'There is a strong expansile cough impulse over the swelling.', abnormal: true, meaning: 'An expansile (not just transmitted) impulse confirms a hernia.' },
    'groin.getAbove': {
      text: 'You cannot get above the swelling — it is continuous with the inguinal canal. It is separate from the testis.',
      abnormal: true,
      meaning: 'Unable to get above = arises from the abdomen (hernia), not from within the scrotum.',
    },
    'groin.scrotum': { text: 'Both testes are present, normal in size and consistency, and separate from the swelling. Epididymes and cords are normal.' },
    'groin.other': { text: 'The left groin is normal, with no palpable cough impulse at the superficial ring.' },
    'groin.lie': { text: 'On lying down, the swelling becomes smaller.', abnormal: true },
    'groin.reduce': {
      text: 'Mr Okafor reduces the swelling easily himself, upwards and laterally along the line of the inguinal canal. It is completely reducible.',
      abnormal: true,
      meaning: 'A reducible hernia is not incarcerated or strangulated — elective repair can be planned.',
    },
    'groin.deepRing': {
      text: 'With firm pressure over the deep ring (just above the midpoint of the inguinal ligament), the hernia does NOT reappear when he coughs.',
      abnormal: true,
      meaning: 'Controlled by deep ring occlusion → indirect inguinal hernia (though this test is only about 60% accurate — the operative finding is definitive).',
    },
    'groin.release': {
      text: 'On releasing the pressure and asking him to cough, the swelling reappears at the deep ring and runs obliquely down along the canal towards the scrotum.',
      abnormal: true,
      meaning: 'Oblique descent from the deep ring is typical of an indirect hernia; a direct hernia bulges straight forward medially.',
    },
    'groin.auscultate': { text: 'Faint bowel sounds are audible over the swelling.', abnormal: true, media: 'bowel:normal', meaning: 'Bowel sounds suggest bowel within the sac (an enterocele).' },
    'complete.abdomen': { text: 'Abdomen soft and non-tender; no masses, scars or other hernias.' },
    'complete.dre': { text: 'Not indicated here — no symptoms of prostatism or constipation.' },
  },
  criticalSteps: ['st.tubercle', 'ly.deepRing'],
  investigations: {},
  investigationRubric: { essential: [] },
  diagnosis: {
    correct: 'indirect-ih',
    accept: [],
    differentials: ['direct-ih', 'femoral-hernia', 'hydrocele-cord', 'saphena-varix', 'inguinal-lymph'],
  },
  management: {
    essential: [
      { id: 'hernia-elective', why: 'Symptomatic inguinal hernia in a fit man: elective mesh repair (open Lichtenstein or laparoscopic TEP/TAPP).' },
      { id: 'reassure', why: 'Explain the diagnosis, the small risk of strangulation, and safety-net: an irreducible, painful lump with vomiting needs emergency attention.' },
    ],
    helpful: [{ id: 'lifestyle', why: 'Avoid heavy lifting until repaired; manage constipation or cough if present.' }],
    avoid: [
      { id: 'hernia-emergency', why: 'The hernia is reducible and non-tender — there is no indication for emergency surgery.' },
      { id: 'theatre', why: 'Not an emergency.' },
    ],
  },
  viva: [
    {
      id: 'canal',
      q: 'What forms the posterior wall of the inguinal canal?',
      options: ['External oblique aponeurosis', 'Transversalis fascia, reinforced medially by the conjoint tendon', 'The inguinal ligament', 'Internal oblique and transversus abdominis arching fibres'],
      correct: 1,
      answer: 'Posterior wall: transversalis fascia, reinforced medially by the conjoint tendon. Anterior: external oblique aponeurosis (+ internal oblique laterally). Roof: arching fibres of internal oblique and transversus abdominis. Floor: inguinal ligament (lacunar ligament medially). (“MALT”: Muscles, Aponeuroses, Ligaments, Transversalis fascia.)',
      topic: 'Anatomy',
    },
    {
      id: 'indirect-direct',
      q: 'How do indirect and direct inguinal hernias differ?',
      answer: 'Indirect: passes through the deep ring LATERAL to the inferior epigastric vessels, along the canal inside the spermatic cord (processus vaginalis), often into the scrotum; more common, younger patients; controlled by deep ring pressure; narrower neck so higher risk of strangulation. Direct: bulges through Hesselbach’s triangle MEDIAL to the inferior epigastric vessels (weak posterior wall), older men, rarely enters the scrotum, reduces easily and is not controlled by deep ring pressure.',
      topic: 'Anatomy',
    },
    {
      id: 'hesselbach',
      q: 'What are the boundaries of Hesselbach’s triangle?',
      options: [
        'Inferior epigastric vessels, lateral border of rectus abdominis, inguinal ligament',
        'Inguinal ligament, sartorius, adductor longus',
        'Pubic tubercle, ASIS, umbilicus',
        'Femoral vein, lacunar ligament, pectineal ligament',
      ],
      correct: 0,
      answer: 'Laterally the inferior epigastric vessels, medially the lateral border of rectus abdominis, inferiorly the inguinal ligament. Direct hernias emerge through it. (Sartorius, adductor longus and the inguinal ligament bound the femoral triangle.)',
      topic: 'Anatomy',
    },
    {
      id: 'complications',
      q: 'What complications of mesh inguinal hernia repair should you mention when consenting?',
      answer: 'Bleeding/haematoma (including scrotal), wound infection, mesh infection, recurrence (~1–5%), chronic post-operative groin pain (up to ~10% have some, ~2% severe), damage to the vas or testicular vessels (ischaemic orchitis, testicular atrophy), urinary retention, seroma, and anaesthetic risks. Return to heavy manual work usually after 2–4 weeks depending on the approach and surgeon advice.',
      topic: 'Management',
    },
  ],
  teaching: {
    summary:
      'A young manual worker with a reducible right groin lump that appears on standing and straining, lies above and medial to the pubic tubercle, has an expansile cough impulse and is controlled by deep ring occlusion — a right indirect inguinal hernia, best treated by elective mesh repair.',
    keyFindings: [
      'Swelling above and medial to the pubic tubercle (inguinal, not femoral)',
      'Expansile cough impulse; cannot get above it',
      'Reducible; controlled by pressure over the deep ring',
      'Reappears obliquely along the canal on release',
    ],
    pearls: [
      'Always examine standing first — a hernia may be invisible lying down.',
      'The pubic tubercle is the key landmark: inguinal hernias are above and medial, femoral hernias below and lateral.',
      'The deep ring lies 1.5–2 cm above the femoral pulse (mid-inguinal point), at the midpoint of the inguinal ligament.',
      'Examine the other side and the scrotum — hernias are often bilateral, and scrotal swellings you cannot get above are hernias.',
      'Ask about symptoms of obstruction and causes of raised intra-abdominal pressure (chronic cough, constipation, prostatism).',
    ],
    presentation:
      'I examined Mr Daniel Okafor, a 38-year-old scaffolder, who looked well. Standing, there was a 4 × 3 cm smooth, soft, non-tender swelling in the right groin lying above and medial to the pubic tubercle, extending obliquely towards the scrotum, with a visible and palpable expansile cough impulse. I could not get above the swelling and both testes were normal and separate from it. Lying down, he reduced it easily; with pressure over the deep ring the hernia was controlled on coughing and reappeared obliquely along the canal on release. The left groin was normal. These findings are consistent with a reducible right indirect inguinal hernia. I would complete my examination by examining the abdomen, and I would offer him an elective mesh repair.',
    references: [
      'Macleod’s Clinical Examination, 14th ed. — Ch. 6: The gastrointestinal system (examination of the groin)',
      'HerniaSurge Group. International guidelines for groin hernia management. Hernia 2018',
    ],
  },
}

export default c
