import type { CaseDef } from '../../engine/types'
import { CRP, FBC, lab, LFT, r, UE, VBG } from './helpers'

const c: CaseDef = {
  id: 'internal-hernia',
  title: 'Internal hernia after laparoscopic Roux-en-Y gastric bypass',
  presenting: 'Colicky upper abdominal pain after a gastric bypass',
  specialty: 'Upper GI',
  exam: 'abdominal',
  difficulty: 3,
  setting: 'Emergency department',
  stem: 'Natalie Price, 38, has come to the emergency department with abdominal pain and vomiting. She had weight-loss surgery 20 months ago. Take a history, examine her abdomen, request investigations and start management.',
  components: ['history', 'exam', 'investigations', 'diagnosis', 'viva'],
  tags: ['bariatric surgery', 'internal hernia', 'pain out of proportion', 'pregnancy test'],
  patient: {
    name: 'Natalie Price',
    title: 'Ms Price',
    age: 38,
    sex: 'female',
    dob: '21/03/1988',
    occupation: 'a primary school teacher',
    appearance: {
      sex: 'female',
      age: 38,
      skinTone: 2,
      habitus: 'overweight',
      hair: 'long',
      hairColor: 'brown',
      eyeColor: 'green',
      sweaty: true,
      pallor: 0.2,
      striae: true,
      scars: ['lap-bariatric'],
      lines: { cannula: 'left-hand' },
    },
    persona: { mood: 'anxious', style: 'normal' },
  },
  vitals: { hr: 112, rhythm: 'regular', sbp: 128, dbp: 82, rr: 20, spo2: 98, temp: 37.2, avpu: 'A', pain: 8 },
  bedside: { vomitBowl: 'clear' },
  history: {
    opening: { text: 'I’ve had these awful cramping pains in the top of my tummy since last night. They keep coming in waves and I can’t stop being sick.', cue: 'shifts restlessly on the trolley, unable to get comfortable' },
    answers: {
      'pain.site': { text: 'Up here, under my ribs, more on the left… and round the middle.', cue: 'points to the left upper quadrant and epigastrium' },
      'pain.onset': 'Yesterday evening, about an hour after dinner. It came on quite quickly.',
      'pain.character': 'Cramping — like something twisting and squeezing. It eases a bit, then comes back.',
      'pain.radiation': 'Sometimes through to my back.',
      'pain.moved': 'No, it’s stayed up here.',
      'pain.timing': 'It comes in waves every few minutes. Since this morning there’s an ache in between that doesn’t go away.',
      'pain.exacerbating': 'Eating or drinking. Even a few sips of water set it off.',
      'pain.relieving': 'Curling up in a ball helps a little. Nothing else.',
      'pain.severity': 'Eight now. Ten at the worst.',
      'pain.previous': 'I’ve had a few shorter attacks over the last three months — cramps after meals that wore off after an hour or two. I thought that was just the bypass.',
      'pain.analgesia_taken': 'Paracetamol. I’m not allowed ibuprofen since the operation.',
      'gi.nausea': 'All the time.',
      'gi.vomiting': 'Four or five times since last night.',
      'gi.vomit_content': 'Watery and frothy, with bits of my dinner at first. Not green, and no blood.',
      'gi.bowels_last': 'Yesterday morning. Normal.',
      'gi.flatus': 'A little, yes.',
      'gi.distension': 'It feels tight up top, but my tummy doesn’t look swollen.',
      'gi.appetite': 'I can’t keep anything down at the moment.',
      'gi.weight': 'I’ve lost about seven stone since the operation — that was the point. It’s been steady for the last few months.',
      'gi.reflux': 'Not since the bypass.',
      'gi.melaena': 'No.',
      'gi.jaundice': 'No.',
      'sys.fever': 'No, just clammy.',
      'gyn.lmp': 'About five weeks ago, I think. They’ve been all over the place since I lost the weight.',
      'gyn.pregnant': 'I don’t think so… we’re not trying. I’m on the pill, but I’m not sure it works properly after the bypass.',
      'gyn.contraception': 'The combined pill.',
      'pmh.conditions': 'Before the operation I had type 2 diabetes and sleep apnoea. The diabetes has gone and I don’t need the CPAP machine any more.',
      'pmh.surgery': 'A keyhole gastric bypass — a Roux-en-Y, they called it — twenty months ago at the bariatric centre. Nothing else.',
      'pmh.diabetes': 'I used to have it. I came off metformin after the bypass.',
      'pmh.gi': 'Only the bypass. They scanned my gallbladder before the operation and it was fine.',
      'dh.meds': 'A bariatric multivitamin and iron every day, calcium with vitamin D, B12 injections every three months, and the pill.',
      'dh.nsaids': 'No — they told me never to take them after the bypass.',
      'dh.anticoag': 'No.',
      'dh.steroids': 'No.',
      'sh.smoking': 'I stopped before the operation — they made me.',
      'sh.alcohol': 'Hardly ever. It goes straight to my head now.',
      'sh.living': 'With my partner and our two children.',
      'fh.general': 'Mum has diabetes.',
      'pre.last_meal': 'Dinner at about six last night. Only sips of water since, and they came straight back up.',
      'comm.questions': 'Is this something to do with the bypass?',
    },
    key: [
      'comm.open',
      'pain.site',
      'pain.onset',
      'pain.character',
      'pain.timing',
      'pain.exacerbating',
      'pain.severity',
      'pain.previous',
      'gi.vomiting',
      'gi.vomit_content',
      'gi.bowels_last',
      'gi.flatus',
      'pmh.surgery',
      'gyn.lmp',
      'gyn.pregnant',
      'dh.meds',
      'dh.nsaids',
      'dh.allergies',
    ],
    critical: ['pmh.surgery', 'gyn.lmp'],
    ideas: 'I wondered if something had gone wrong with the bypass. I read online that the bowel can get twisted.',
    concerns: 'That I’ll need another big operation… and the children are at home.',
    expectations: 'Something for the pain, and someone from the bariatric team to see me.',
    social: {
      smoking: 'I stopped two years ago, before the operation. I smoked about ten a day for fifteen years.',
      alcohol: 'Very little since the bypass.',
      diet: 'Small meals, protein first, like the dietitian taught me.',
    },
  },
  abdo: {
    general: {
      endOfBed:
        'Ms Price is lying curled on her side on the trolley, pale and clammy, and keeps changing position as each cramp comes. The monitor shows a sinus tachycardia. There is a cannula in her left hand and a vomit bowl of thin, watery fluid beside her. She has loose folds of skin over her arms and abdomen after major weight loss.',
      restless: true,
    },
    hands: { temperature: 'cool', crt: 2.5 },
    face: { mucosa: 'dry', tongue: 'dry-furred' },
    abdomen: {
      inspectionExtra: 'Lax, redundant abdominal skin after massive weight loss. No visible distension or peristalsis.',
      regions: {
        EPI: r(1, 2),
        LUQ: r(1, 2, 'voluntary'),
        UMB: r(0, 1),
      },
      bowelSounds: 'hyperactive',
    },
    completion: {
      dre: 'Soft brown stool in the rectum; no blood or melaena.',
    },
  },
  criticalSteps: ['abdo.inspect', 'gen.obs'],
  investigations: {
    fbc: { values: FBC(124, 13.8, 11.6, 318, 84, 'female'), interpretation: 'Neutrophil leucocytosis. Haemoglobin preserved.' },
    ue: { values: UE(137, 3.4, 7.1, 72, '> 90', 'female'), interpretation: 'Mild hypokalaemia from vomiting; renal function normal.' },
    crp: { values: CRP(24), interpretation: 'Only modestly raised — inflammatory markers are often unremarkable early in an internal hernia.' },
    lft: { values: LFT(14, 22, 84, 30, 36), interpretation: 'Normal.' },
    amylase: {
      values: [lab('Amylase', 88, 'U/L', '30–110'), lab('Lipase', 41, 'U/L', '< 60')],
      interpretation: 'Normal. Obstruction of the biliopancreatic limb can raise amylase and mimic pancreatitis.',
    },
    vbg: { values: VBG(7.36, 22, -2.6, 2.6, 3.4, 5.6), interpretation: 'Lactate 2.6. A raised lactate is a late, insensitive sign of bowel ischaemia — a normal value would not exclude it.' },
    'urine-hcg': { report: 'Negative.', interpretation: 'Not pregnant. Always check: fertility rises after bariatric surgery and the pill is poorly absorbed.' },
    axr: {
      report: 'A few mildly dilated small-bowel loops in the left upper quadrant. Surgical staple lines in the left upper quadrant. No free gas.',
      interpretation: 'Non-specific. Plain films are often unhelpful after a bypass — CT is the test of choice.',
      abnormal: true,
    },
    'us-abdo': {
      report: 'Several small gallstones in a thin-walled gallbladder. No pericholecystic fluid; sonographic Murphy’s sign negative. CBD 5 mm. Pancreas obscured by bowel gas.',
      interpretation: 'Gallstones are common after rapid weight loss, but there is no cholecystitis here. They do not explain her picture.',
      abnormal: true,
    },
    'ct-ap': {
      report:
        'Post Roux-en-Y gastric bypass. Clustered, mildly dilated loops of jejunum in the left upper quadrant with a whorled “swirl” of mesenteric vessels and fat at the mesenteric root, engorged mesenteric veins, and the jejunojejunostomy displaced to the right of the midline. A small amount of free fluid. Bowel wall enhancement preserved. Gastric pouch and remnant stomach not distended.',
      interpretation: 'Internal hernia, most likely through Petersen’s space. The mesenteric swirl is the most sensitive CT sign, but a normal CT does not exclude an internal hernia.',
      abnormal: true,
    },
    coag: { values: [lab('PT', 11.6, 's', '10–13'), lab('INR', 1.0, '', '0.8–1.2'), lab('APTT', 30, 's', '25–35')], interpretation: 'Normal.' },
    gs: { report: 'Group A RhD positive. Antibody screen negative.' },
  },
  investigationRubric: {
    essential: [
      { id: 'urine-hcg', why: 'A woman of reproductive age with a late period and unreliable oral contraception after a bypass.' },
      { id: 'fbc', why: 'Baseline; leucocytosis.' },
      { id: 'ue', why: 'Vomiting causes hypokalaemia; renal function is needed before contrast CT.' },
      { id: 'vbg', why: 'Lactate — although a normal value does not exclude ischaemia.' },
      { id: 'ct-ap', why: '!CT with IV contrast is the investigation of choice: look for a mesenteric swirl, clustered loops and engorged mesenteric vessels.' },
    ],
    helpful: [
      { id: 'crp', why: 'Baseline inflammatory marker.' },
      { id: 'lft', why: 'Biliary differentials — gallstones are common after rapid weight loss.' },
      { id: 'amylase', why: 'Pancreatitis is a differential.' },
      { id: 'gs', why: 'She is likely to need theatre.' },
      { id: 'coag', why: 'Pre-operative.' },
    ],
  },
  diagnosis: {
    correct: 'internal-hernia',
    differentials: ['marginal-ulcer', 'sbo-adhesions', 'biliary-colic', 'pancreatitis', 'perforated-pu', 'ectopic'],
  },
  management: {
    essential: [
      { id: 'analgesia', why: 'Titrated IV opioid. Pain out of proportion to the signs is itself a warning sign of ischaemia.' },
      { id: 'fluids', why: 'Tachycardic and dry from vomiting.' },
      { id: 'nbm', why: 'Nil by mouth — she is obstructed and likely to need theatre.' },
      { id: 'senior', why: 'Immediate senior review: an internal hernia can strangulate most of the small bowel.' },
      { id: 'bariatric-team', why: 'Involve the bariatric team (or the regional bariatric centre) early.' },
      {
        id: 'lap-internal-hernia',
        why: '!Urgent laparoscopy: reduce the hernia, check bowel viability and close every mesenteric defect (Petersen’s space and the jejunojejunostomy).',
      },
      { id: 'theatre', why: 'Book the emergency theatre.' },
    ],
    helpful: [
      { id: 'iv-access', why: 'Large-bore access.' },
      { id: 'maintenance-fluids', why: 'Replace potassium lost through vomiting.' },
      { id: 'antiemetic', why: 'Repeated vomiting.' },
      { id: 'consent', why: 'Consent for diagnostic laparoscopy and possible bowel resection.' },
      { id: 'fluid-balance', why: 'Strict fluid balance.' },
      { id: 'vte', why: 'VTE prophylaxis.' },
    ],
    avoid: [
      { id: 'ng', why: 'Never pass an NG tube blindly after a gastric bypass: it cannot decompress the excluded remnant stomach and risks perforating the small pouch or its anastomosis.' },
      { id: 'nsaid', why: 'NSAIDs cause marginal ulcers after gastric bypass — avoid them for life.' },
      { id: 'drip-suck', why: 'An internal hernia will not settle with “drip and suck”, and it can strangulate the whole small bowel.' },
      { id: 'discharge', why: 'Never discharge a bypass patient with obstructive symptoms and pain out of proportion — even a normal CT does not exclude an internal hernia.' },
    ],
  },
  viva: [
    {
      id: 'indications',
      q: 'Under NICE guidance, which of these adults can be considered for bariatric surgery (assuming non-surgical measures have been tried)?',
      options: ['BMI 36 with type 2 diabetes', 'BMI 32 with no other conditions', 'BMI 34 with knee osteoarthritis only', 'BMI 38 with no other conditions'],
      correct: 0,
      answer:
        'Bariatric surgery is considered for a BMI of 40 or more, or 35–40 with a significant obesity-related condition that weight loss would improve (type 2 diabetes, hypertension, obstructive sleep apnoea), provided non-surgical measures have been tried and the person commits to long-term follow-up. Recent-onset type 2 diabetes earns an expedited assessment at lower BMIs, and thresholds are lower for people of South Asian, Chinese, other Asian, Middle Eastern, Black African or African-Caribbean family background.',
      topic: 'Indications',
    },
    {
      id: 'procedures',
      q: 'Compare a sleeve gastrectomy with a Roux-en-Y gastric bypass.',
      answer:
        'Sleeve gastrectomy removes about three-quarters of the stomach along the greater curve, leaving a narrow tube. It is restrictive with hormonal effects (less ghrelin), has no anastomosis and is technically simpler, but can worsen reflux. A Roux-en-Y gastric bypass makes a small (~30 mL) gastric pouch joined to a Roux limb of jejunum; food bypasses the remnant stomach, duodenum and proximal jejunum (the biliopancreatic limb), which rejoins at the jejunojejunostomy. It combines restriction, mild malabsorption and strong incretin effects — better for reflux and diabetes — but brings internal hernias, marginal ulcers, dumping and micronutrient deficiencies.',
      topic: 'Operations',
    },
    {
      id: 'why-hernia',
      q: 'Why are internal hernias a late complication of a gastric bypass?',
      answer:
        'The bypass creates mesenteric defects: Petersen’s space (between the Roux limb mesentery and the transverse mesocolon), the jejunojejunostomy mesenteric defect, and the mesocolic window if the limb is retrocolic. As mesenteric fat disappears with weight loss, the defects widen and small bowel slips through, often intermittently, months to years later. Closing the defects at the first operation reduces the risk. The story is recurrent post-prandial colicky pain with few signs, and the herniated bowel can strangulate.',
      topic: 'Pathophysiology',
    },
    {
      id: 'leak',
      q: 'What is the most sensitive early sign of a staple-line or anastomotic leak after bariatric surgery?',
      options: ['A sustained tachycardia (> 120 bpm)', 'Board-like rigidity', 'A raised serum amylase', 'Shoulder-tip pain'],
      correct: 0,
      answer:
        'A persistent tachycardia is often the only early sign: peritonism is hard to elicit through a thick abdominal wall. Unexplained tachycardia after bariatric surgery is a leak until proven otherwise — CT with oral contrast, or a return to theatre.',
      topic: 'Complications',
    },
    {
      id: 'deficiencies',
      q: 'Which long-term nutritional deficiencies follow a gastric bypass?',
      answer:
        'Iron (the duodenum is bypassed), vitamin B₁₂ (less acid and intrinsic factor — 3-monthly injections), folate, calcium and vitamin D (secondary hyperparathyroidism and osteoporosis), thiamine (Wernicke’s encephalopathy with persistent vomiting — give thiamine before glucose), fat-soluble vitamins, zinc and copper. Patients need lifelong supplements and annual blood tests.',
      topic: 'Follow-up',
    },
    {
      id: 'pregnancy',
      q: 'Why does a pregnancy test matter so much in this patient?',
      answer:
        'Fertility rises quickly with weight loss, and oral contraceptives are poorly absorbed after a malabsorptive operation, so women are advised to use a long-acting method and to avoid pregnancy for 12–18 months after surgery. A positive test changes the differential (ectopic pregnancy) and the choice of imaging and drugs — and internal hernia in pregnancy is a recognised, dangerous emergency.',
      topic: 'Safety',
    },
  ],
  teaching: {
    summary:
      'Internal hernia after a laparoscopic Roux-en-Y gastric bypass: 20 months after surgery and 45 kg lighter, a young woman has recurrent post-prandial colicky upper abdominal pain, now constant, with vomiting and a tachycardia — but a soft abdomen. CT shows the mesenteric swirl sign.',
    keyFindings: [
      'Laparoscopic Roux-en-Y gastric bypass 20 months ago, with about 45 kg of weight loss',
      'Recurrent post-prandial colicky left upper quadrant pain, now continuous, with non-bilious vomiting',
      'Tachycardia of 112 with pain out of proportion to a soft, mildly tender abdomen',
      'Upper abdominal port-site scars, lax skin and striae; hyperactive bowel sounds',
      'Lactate 2.6; negative pregnancy test; CT: mesenteric swirl with clustered jejunal loops',
    ],
    pearls: [
      'After bariatric surgery, abdominal pain with a tachycardia is a surgical emergency until proven otherwise.',
      'Pain out of proportion to the signs suggests ischaemia — a soft abdomen is not reassuring.',
      'A normal CT does not exclude an internal hernia; if the pain persists, the bariatric team should laparoscope.',
      'Never pass a blind NG tube or prescribe NSAIDs for a bypass patient.',
      'Always do a pregnancy test: fertility rises and the pill is unreliable after a bypass.',
    ],
    presentation:
      'Ms Price is a 38-year-old teacher who had a laparoscopic Roux-en-Y gastric bypass 20 months ago and has lost about 45 kg. She presents with 18 hours of colicky left upper quadrant and epigastric pain brought on by eating, now with a constant background ache and repeated non-bilious vomiting, after three months of shorter, similar attacks. She is tachycardic at 112 with a lactate of 2.6, yet her abdomen is soft, with upper abdominal port-site scars, only mild left upper quadrant tenderness, no peritonism and hyperactive bowel sounds. Her pregnancy test is negative. CT shows a mesenteric swirl with clustered jejunal loops in the left upper quadrant, in keeping with an internal hernia through Petersen’s space. I would keep her nil by mouth, give IV fluids with potassium, analgesia and an antiemetic, avoid a blind NG tube and NSAIDs, involve my registrar and the bariatric team immediately, and arrange urgent laparoscopy to reduce the hernia, check the bowel and close the mesenteric defects.',
    references: [
      'NICE guidance on overweight and obesity management (formerly CG189)',
      'O’Kane M, et al. BOMSS guidelines on peri-operative and postoperative biochemical monitoring and micronutrient replacement after bariatric surgery (2020)',
      'Macleod’s Clinical Examination, 14th ed. — Ch. 6: the acute abdomen',
    ],
  },
}

export default c
