import type { CaseDef } from '../../engine/types'

const c: CaseDef = {
  id: 'lipoma',
  title: 'Lipoma of the forearm',
  presenting: 'Lump on the forearm',
  specialty: 'Skin & soft tissue',
  exam: 'lump',
  difficulty: 1,
  setting: 'Outpatient clinic',
  stem: 'Minor-ops clinic. Paul Whitaker, 47, has a lump on his right forearm. Take a brief history, examine the lump, and explain your diagnosis and plan.',
  components: ['history', 'exam', 'diagnosis', 'viva'],
  tags: ['OSCE', 'lump', 'lipoma', 'slip sign', 'sarcoma red flags'],
  patient: {
    name: 'Paul Whitaker',
    title: 'Mr Whitaker',
    age: 47,
    sex: 'male',
    dob: '23/04/1979',
    occupation: 'an electrician',
    appearance: { sex: 'male', age: 47, skinTone: 1, habitus: 'overweight', hair: 'short', hairColor: 'brown', eyeColor: 'blue', facialHair: 'none' },
    persona: { mood: 'calm', style: 'normal' },
  },
  vitals: { hr: 70, rhythm: 'regular', sbp: 132, dbp: 80, rr: 14, spo2: 98, temp: 36.6, avpu: 'A', pain: 0 },
  visual: { lump: { site: 'forearm', side: 'right', w: 4.5, h: 3.5, kind: 'lipoma', lobulated: true, domed: 0.42 } },
  history: {
    opening: { text: 'I’ve got this lump on my arm. My wife keeps telling me to get it looked at.', cue: 'rests his right forearm on the table' },
    answers: {
      'lump.when': 'I first noticed it maybe three or four years ago.',
      'lump.how': 'I just felt it when I was rolling my sleeves up.',
      'lump.change': 'It’s grown very slowly — maybe a bit bigger than it was, but not much.',
      'lump.pain': 'No, it doesn’t hurt at all. It just catches on things sometimes at work.',
      'lump.other': 'I think there might be a small one on my back as well, but I’m not sure.',
      'lump.discharge': 'No, nothing has ever come out of it.',
      'lump.skin': 'No, the skin looks normal.',
      'gi.weight': 'No, if anything I’ve put weight on.',
      'sys.sweats': 'No night sweats.',
      'sys.fatigue': 'No, I feel fine.',
      'pmh.conditions': 'Just a bit of high cholesterol.',
      'dh.meds': 'Atorvastatin.',
      'dh.allergies': 'None.',
      'fh.general': 'My dad had lots of these fatty lumps.',
      'sh.smoking': 'Never smoked.',
      'sh.occupation': 'I’m an electrician — it bumps on things when I’m working in tight spaces.',
      'comm.questions': 'Is it cancer? And can you just cut it out?',
    },
    key: ['comm.open', 'lump.when', 'lump.change', 'lump.pain', 'lump.other', 'lump.discharge', 'lump.skin', 'gi.weight', 'sys.sweats', 'fh.general'],
    critical: ['lump.change'],
    ideas: 'I think it’s just a fatty lump.',
    concerns: 'My wife worries it could be cancer.',
    expectations: 'I’d like to know what it is and whether it can be removed.',
  },
  keyed: {
    'lump.inspect': {
      text: 'On the dorsum of the right forearm there is a smooth, broad, slightly lobulated swelling about 4–5 cm across. The overlying skin is normal: no punctum, erythema, scars or visible veins.',
      abnormal: true,
    },
    'lump.measure': { text: 'The lump measures 4.5 cm × 3.5 cm.', abnormal: true, meaning: 'Under 5 cm — size over 5 cm is a red flag for sarcoma.' },
    'lump.temp': { text: 'The temperature over the lump is the same as the surrounding skin.' },
    'lump.tender': { text: 'Non-tender.' },
    'lump.surface': { text: 'Smooth, slightly lobulated surface with a well-defined but soft, indistinct edge.', abnormal: true, meaning: 'Lobulation with a soft edge is typical of a lipoma.' },
    'lump.consistency': { text: 'Soft, “doughy” consistency.', abnormal: true },
    'lump.fluctuation': { text: 'Pseudo-fluctuant — soft fat can mimic fluctuation, but there is no true fluid thrill in two planes.', meaning: 'Lipomas can feel fluctuant because fat is soft at body temperature — hence the “pseudo-fluctuation”.' },
    'lump.skin': { text: 'The skin moves freely over the lump — it is not tethered.', meaning: 'Unlike an epidermoid cyst, which is attached to the skin at its punctum.' },
    'lump.deep': { text: 'The lump remains mobile when he tenses his forearm muscles — it lies superficial to the deep fascia.', meaning: 'A superficial (subcutaneous) location is reassuring; deep lumps need imaging.' },
    'lump.pulsation': { text: 'Not pulsatile.' },
    'lump.compress': { text: 'Not compressible or reducible; no cough impulse.' },
    'lump.slip': { text: 'Positive slip sign: pressing on the edge, the lump slips away from under your finger.', abnormal: true, meaning: 'The slip sign is characteristic of a lipoma.' },
    'lump.transilluminate': { text: 'It does not transilluminate.' },
    'lump.auscultate': { text: 'No bruit.' },
    'lump.nodes': { text: 'No epitrochlear or axillary lymphadenopathy.' },
    'lump.distal': { text: 'Normal radial pulse, sensation and hand function.' },
    'complete.skin': { text: 'There is a similar, smaller soft lump on his upper back.', abnormal: true, meaning: 'Multiple lipomas are common (and familial multiple lipomatosis exists).' },
  },
  criticalSteps: ['lk.measure', 'fl.fixity'],
  investigations: {},
  investigationRubric: { essential: [] },
  diagnosis: {
    correct: 'lipoma',
    differentials: ['sarcoma', 'epidermoid-cyst', 'ganglion', 'dermatofibroma'],
  },
  management: {
    essential: [{ id: 'reassure', why: 'Explain it is a benign fatty lump, and safety-net: come back if it grows quickly, becomes painful, or exceeds 5 cm.' }],
    helpful: [{ id: 'excision', why: 'Excision under local anaesthetic is reasonable as it is symptomatic (catches at work); send for histology.' }],
    avoid: [{ id: '2ww', why: 'No red flags (small, superficial, slow-growing, painless) — a suspected-cancer referral is not needed.' }],
  },
  viva: [
    {
      id: 'redflags',
      q: 'Which features of a soft-tissue lump should prompt urgent imaging for sarcoma?',
      options: ['Size > 5 cm, increasing size, deep to fascia, painful, recurrence after excision', 'Soft, lobulated, slip sign positive', 'Present for many years unchanged', 'Positive transillumination'],
      correct: 0,
      answer: 'Red flags: size > 5 cm, increasing size, deep to the deep fascia, pain, and recurrence after previous excision. NICE (NG12) recommends an urgent direct-access ultrasound (within 2 weeks) for an adult with an unexplained lump that is increasing in size, and a suspected sarcoma referral if ultrasound suggests sarcoma or is uncertain.',
      topic: 'Red flags',
    },
    {
      id: 'describe',
      q: 'How would you systematically describe any lump?',
      answer: 'Site, size (measure), shape, surface, edge, colour and overlying skin; temperature, tenderness; consistency; fluctuation; fixity to skin and to deep structures; pulsatility (expansile or transmitted); compressibility/reducibility and cough impulse; transillumination; auscultation; regional lymph nodes; and the neurovascular status distal to it.',
      topic: 'Examination',
    },
    {
      id: 'slip',
      q: 'What is the slip sign?',
      answer: 'When you press gently on the edge of a lipoma, the lump slips away from under your finger because its soft, lobulated edge is compressed laterally. It is characteristic of lipomas.',
      topic: 'Examination',
    },
  ],
  teaching: {
    summary:
      'A slowly growing, soft, lobulated, mobile subcutaneous lump under 5 cm with a positive slip sign and normal overlying skin — a benign lipoma. The key is to screen for sarcoma red flags.',
    keyFindings: ['4.5 × 3.5 cm soft, lobulated, subcutaneous lump', 'Normal skin, not tethered; mobile over deep structures', 'Positive slip sign; no transillumination; not tender', 'Similar lump on the back'],
    pearls: [
      'Always measure a lump — size > 5 cm is a sarcoma red flag.',
      'Test fixity to both skin (epidermoid cyst) and deep structures (tense the muscle underneath).',
      'Lipomas can feel pseudo-fluctuant — fat is soft at body temperature.',
    ],
    presentation:
      'I examined Mr Paul Whitaker, a 47-year-old man. On the dorsum of his right forearm there is a 4.5 × 3.5 cm smooth, lobulated swelling with normal overlying skin and no punctum. It is non-tender, of normal temperature and soft with a slightly indistinct edge; it is not tethered to the skin, is mobile over the deep structures with the muscle tensed, and the slip sign is positive. It is not pulsatile, compressible or transilluminable, and there is no regional lymphadenopathy. There is a similar smaller lump on his back. The most likely diagnosis is a lipoma. There are no sarcoma red flags, so I would reassure him and offer excision under local anaesthetic as it catches at work.',
    references: ['Macleod’s Clinical Examination, 14th ed. — Ch. 3: examination of a lump', 'NICE NG12: Suspected cancer — recognition and referral (sarcoma)'],
  },
}

export default c
