import type { CaseDef } from '../../engine/types'
import { note, r } from './helpers'

const c: CaseDef = {
  id: 'liver-disease',
  title: 'Chronic liver disease (alcohol-related cirrhosis) with ascites and portal hypertension',
  presenting: 'OSCE: examine this patient’s abdomen (swollen abdomen)',
  specialty: 'Hepatobiliary',
  exam: 'abdominal',
  difficulty: 2,
  setting: 'Surgical ward',
  stem: 'OSCE station (10 minutes). Kwame Mensah, 55, has noticed his abdomen swelling. Please examine his abdomen, then present your findings and answer the examiner’s questions.',
  components: ['exam', 'diagnosis', 'viva'],
  tags: ['OSCE', 'stigmata', 'ascites', 'shifting dullness', 'splenomegaly'],
  patient: {
    name: 'Kwame Mensah',
    title: 'Mr Mensah',
    age: 55,
    sex: 'male',
    dob: '19/02/1971',
    occupation: 'a taxi driver',
    appearance: {
      sex: 'male',
      age: 55,
      skinTone: 6,
      habitus: 'average',
      hair: 'crop',
      hairColor: 'black',
      eyeColor: 'brown',
      distension: 3,
      distensionType: 'fluid',
      umbilicus: 'everted',
      caputMedusae: true,
      spiderNaevi: 7,
      gynaecomastia: true,
      bodyHairLoss: true,
      jaundice: 0.45,
      scars: ['lap-chole'],
    },
    persona: { mood: 'calm', style: 'normal' },
  },
  vitals: { hr: 92, rhythm: 'regular', sbp: 106, dbp: 62, rr: 18, spo2: 97, temp: 36.9, avpu: 'A', pain: 1 },
  history: {
    opening: 'My tummy has been swelling up over the last couple of months. My ankles too.',
    answers: {
      'sh.alcohol': 'I used to drink heavily — a bottle of spirits a day for twenty years. I stopped six months ago.',
      'pmh.conditions': 'They told me my liver was damaged last year.',
      'pmh.surgery': 'My gallbladder was taken out with keyhole surgery years ago.',
      'dh.meds': 'Spironolactone and propranolol.',
      'gi.jaundice': 'My eyes have been a bit yellow on and off.',
      'gi.melaena': 'No black stools.',
      'ros.ankles': 'Yes, my ankles swell by the evening.',
      'thy.mood': 'Sometimes I get muddled, my wife says.',
    },
    key: ['comm.open', 'sh.alcohol', 'pmh.conditions', 'dh.meds'],
  },
  abdo: {
    general: {
      endOfBed:
        'Mr Mensah is sitting comfortably at 45°. His abdomen is grossly distended with full flanks. His sclerae look yellow. There is no drain, catheter or stoma. A bottle of spironolactone tablets is on the locker.',
    },
    hands: {
      clubbing: true,
      leukonychia: true,
      palmarErythema: true,
      dupuytren: true,
      asterixis: true,
      temperature: 'warm',
    },
    face: { sclera: 'icteric', fetor: 'hepaticus', parotids: true },
    chest: { spiderNaevi: true, gynaecomastia: true, hairLoss: true },
    abdomen: {
      shape: 'distended',
      regions: {
        RF: note('dull'),
        LF: note('dull'),
        RIF: note('dull'),
        LIF: note('dull'),
        SP: note('dull'),
        UMB: note('tympanic'),
        EPI: note('tympanic'),
        LUQ: r(0, 0, 'none', { note: 'dull', mass: { description: 'a firm edge in the left upper quadrant that moves down on inspiration, with a notch, which you cannot get above', label: 'splenomegaly (4 cm)', sizeCm: 4, movesWithRespiration: true } }),
      },
      liver: { edgeCm: 0, spanCm: 8 },
      spleen: { tipCm: 4 },
      shiftingDullness: true,
      fluidThrill: false,
      inspectionExtra: 'The umbilicus is everted and dilated veins radiate from it.',
    },
    legs: { oedema: 'to-knee' },
    completion: {
      dre: 'Normal; no melaena.',
      urinalysis: 'Bilirubin +; otherwise negative.',
      genitalia: 'Testicular atrophy.',
      'cvs-resp': 'Heart sounds normal; stony dullness at the right base (small hepatic hydrothorax).',
    },
  },
  criticalSteps: ['perc.shifting', 'hands.flap'],
  investigations: {},
  investigationRubric: { essential: [] },
  diagnosis: {
    correct: 'cirrhosis',
    differentials: ['liver-mets', 'hepatitis', 'pancreatic-cancer'],
  },
  management: { essential: [] },
  viva: [
    {
      id: 'stigmata',
      q: 'List the peripheral stigmata of chronic liver disease you looked for.',
      answer:
        'Hands: clubbing, leukonychia, palmar erythema, Dupuytren’s contracture, asterixis (encephalopathy). Face: jaundice, parotid enlargement, fetor hepaticus. Chest: spider naevi (SVC distribution, > 5 abnormal), gynaecomastia, loss of body hair. Abdomen: caput medusae, ascites, splenomegaly (portal hypertension), small or large liver, testicular atrophy. Legs: oedema, bruising.',
      topic: 'Examination',
    },
    {
      id: 'shifting',
      q: 'How do you demonstrate shifting dullness?',
      answer: 'Percuss from the umbilicus towards the flank until the note becomes dull. Keep your finger there, roll the patient away from you onto their side, wait about 30 seconds for the fluid to redistribute, then percuss again. If the dull point becomes resonant, dullness has “shifted” — ascites. A fluid thrill is only present with tense, gross ascites.',
      topic: 'Technique',
    },
    {
      id: 'spleen-kidney',
      q: 'How do you distinguish an enlarged spleen from an enlarged left kidney?',
      options: [
        'The spleen has a notch, you cannot get above it, it moves towards the RIF on inspiration and is dull to percussion; the kidney is ballotable and has resonant bowel over it',
        'The kidney has a notch and moves with respiration; the spleen is ballotable',
        'Both are identical on examination',
        'Only ultrasound can distinguish them',
      ],
      correct: 0,
      answer: 'Spleen: notch on the medial border, cannot get above it, moves diagonally towards the RIF with inspiration, dull to percussion, not ballotable. Kidney: can get above it, ballotable, moves little and vertically, resonant (colon in front).',
      topic: 'Examination',
    },
    {
      id: 'saag',
      q: 'His ascitic tap shows a serum–ascites albumin gradient (SAAG) of 18 g/L. What does this mean?',
      answer: 'SAAG ≥ 11 g/L indicates portal hypertension (cirrhosis, heart failure, Budd–Chiari). SAAG < 11 g/L suggests a non-portal cause: malignancy (peritoneal carcinomatosis), TB, pancreatitis, nephrotic syndrome. Also send cell count — neutrophils > 250/mm³ indicates spontaneous bacterial peritonitis.',
      topic: 'Investigation',
    },
    {
      id: 'child',
      q: 'Which parameters make up the Child–Pugh score?',
      options: ['Bilirubin, albumin, INR, ascites, encephalopathy', 'ALT, ALP, GGT, bilirubin, albumin', 'Age, WCC, glucose, LDH, AST', 'Sodium, creatinine, bilirubin, INR'],
      correct: 0,
      answer: 'Bilirubin, albumin, prothrombin time/INR, ascites and encephalopathy — graded A–C. (MELD uses bilirubin, INR and creatinine ± sodium.)',
      topic: 'Scores',
    },
  ],
  teaching: {
    summary:
      'Decompensated alcohol-related cirrhosis: stigmata of chronic liver disease in the hands, face and chest, jaundice, asterixis, moderate ascites with shifting dullness, splenomegaly and caput medusae (portal hypertension), and pitting oedema.',
    keyFindings: [
      'Clubbing, leukonychia, palmar erythema, Dupuytren’s, asterixis',
      'Icteric sclerae, fetor hepaticus, parotid enlargement',
      '> 5 spider naevi, gynaecomastia, loss of body hair',
      'Distended abdomen, everted umbilicus, caput medusae, shifting dullness',
      '4 cm splenomegaly; liver not palpable (small cirrhotic liver); oedema to the knees',
    ],
    pearls: [
      'Present findings system by system: “There are stigmata of chronic liver disease… with evidence of decompensation (jaundice, ascites, encephalopathy) and portal hypertension (splenomegaly, caput medusae).”',
      'Always offer to complete with a DRE (melaena from varices) and to examine the external genitalia (testicular atrophy).',
      'In darker skin, look for jaundice in the sclerae and palms.',
      'A small liver with splenomegaly = cirrhosis with portal hypertension.',
    ],
    presentation:
      'I examined Mr Kwame Mensah, a 55-year-old man. From the end of the bed he looked comfortable with a grossly distended abdomen and icteric sclerae. In the hands there was clubbing, leukonychia, palmar erythema, bilateral Dupuytren’s contracture and asterixis. He had fetor hepaticus and parotid enlargement, more than five spider naevi, gynaecomastia and loss of body hair. The abdomen was distended with full flanks, an everted umbilicus, caput medusae and laparoscopic cholecystectomy scars. There was no hepatomegaly; there was a 4 cm splenomegaly, shifting dullness was present, and there was pitting oedema to the knees. These findings are consistent with decompensated chronic liver disease — most likely alcohol-related cirrhosis — with ascites, encephalopathy and portal hypertension. To complete my examination I would perform a DRE for melaena, examine the external genitalia, and review his observations, urine dipstick and a diagnostic ascitic tap.',
    references: ['Macleod’s Clinical Examination, 14th ed. — Ch. 6: examination of the abdomen; stigmata of chronic liver disease', 'BSG/BASL guidelines on the management of ascites in cirrhosis (2021)'],
  },
}

export default c
