import type { CaseDef } from '../../engine/types'
import { FBC, lab, r, UE, VBG } from './helpers'

const c: CaseDef = {
  id: 'mesenteric-ischaemia',
  title: 'Acute mesenteric ischaemia (SMA embolus from atrial fibrillation)',
  presenting: 'Severe central abdominal pain',
  specialty: 'Vascular',
  exam: 'abdominal',
  difficulty: 3,
  setting: 'Emergency department',
  stem: 'Margaret Walsh, 79, has had six hours of severe central abdominal pain. The ED team say her abdomen is “soft”. Assess her fully and decide what is going on.',
  components: ['history', 'exam', 'investigations', 'diagnosis', 'viva'],
  tags: ['AF', 'pain out of proportion', 'lactate', 'CT angiography'],
  patient: {
    name: 'Margaret Walsh',
    title: 'Mrs Walsh',
    age: 79,
    sex: 'female',
    dob: '12/12/1946',
    occupation: 'a retired nurse',
    appearance: {
      sex: 'female',
      age: 79,
      skinTone: 1,
      habitus: 'thin',
      hair: 'bob',
      hairColor: 'white',
      eyeColor: 'blue',
      sweaty: true,
      pallor: 0.3,
      lines: { cannula: 'right-hand' },
    },
    persona: { mood: 'distressed', style: 'normal' },
  },
  vitals: { hr: 128, rhythm: 'irregular', sbp: 126, dbp: 74, rr: 24, spo2: 95, temp: 37.6, avpu: 'A', pain: 9 },
  bedside: { vomitBowl: 'bilious' },
  history: {
    opening: { text: 'The pain in my tummy is unbearable, doctor. It came on suddenly this morning. Nothing is touching it.', cue: 'writhing, unable to get comfortable' },
    answers: {
      'pain.site': { text: 'All around the middle of my tummy.', cue: 'circles the umbilicus' },
      'pain.onset': 'Suddenly, about six hours ago, while I was making breakfast.',
      'pain.character': 'Severe, constant, gripping.',
      'pain.radiation': 'No.',
      'pain.timing': 'Constant — it hasn’t let up at all.',
      'pain.exacerbating': 'Nothing makes it better or worse.',
      'pain.relieving': 'Nothing. Not even the morphine they gave me.',
      'pain.severity': 'Nine. The worst I’ve ever known.',
      'pain.previous': 'For a few months I’ve had a dull ache after meals, so I’ve been eating less.',
      'gi.nausea': 'Yes.',
      'gi.vomiting': 'Twice.',
      'gi.diarrhoea': 'I had to rush to the toilet once — it was loose.',
      'gi.stool_blood': 'There was some dark blood in it.',
      'gi.weight': 'I’ve lost a bit — I’ve been scared to eat because of the ache.',
      'ros.palpitations': 'My heart has been racing on and off.',
      'pmh.conditions': 'Atrial fibrillation, high blood pressure, and my heart is a bit weak.',
      'pmh.heart': 'AF for years. A “weak heart”.',
      'pmh.stroke': 'A mini-stroke five years ago.',
      'dh.meds': 'Bisoprolol and ramipril. I used to take apixaban but they stopped it after I had a fall and a bleed two months ago.',
      'dh.anticoag': 'Not any more — they stopped my apixaban two months ago after a fall.',
      'sh.smoking': 'I gave up twenty years ago.',
      'sh.living': 'On my own. My son lives nearby.',
      'comm.questions': 'What’s happening to me?',
    },
    key: ['comm.open', 'pain.site', 'pain.onset', 'pain.character', 'pain.severity', 'pain.previous', 'gi.vomiting', 'gi.stool_blood', 'gi.weight', 'pmh.conditions', 'pmh.heart', 'dh.meds', 'dh.anticoag', 'dh.allergies'],
    critical: ['dh.anticoag'],
    concerns: 'I’m frightened. I’ve never had pain like this.',
    expectations: 'Please find out what it is.',
  },
  abdo: {
    general: {
      endOfBed:
        'Mrs Walsh is restless and distressed, unable to lie still and repeatedly asking for more pain relief. She looks pale and sweaty. There is a cannula in her right hand and a bowl of bilious vomit beside her. There are no drains or catheter.',
      restless: true,
    },
    hands: { temperature: 'cool', crt: 2.5 },
    face: { mucosa: 'dry' },
    abdomen: {
      shape: 'flat',
      regions: {
        UMB: r(1, 1),
        EPI: r(0, 1),
        RF: r(0, 1),
        LF: r(0, 1),
      },
      bowelSounds: 'reduced',
    },
    completion: { dre: 'Dark red blood mixed with loose stool on the glove. No masses.' },
  },
  criticalSteps: ['hands.pulse'],
  investigations: {
    vbg: { values: VBG(7.24, 16, -9.2, 6.2, 4.9, 8.8), interpretation: 'Severe lactic acidosis out of keeping with the soft abdomen — mesenteric ischaemia until proven otherwise.' },
    ecg: { report: 'Atrial fibrillation with a ventricular rate of 128. No acute ST changes.', interpretation: 'Uncontrolled AF — an embolic source.', abnormal: true },
    fbc: { values: FBC(138, 21.4, 18.9, 310, 90, 'female'), interpretation: 'Marked leucocytosis.' },
    ue: { values: UE(138, 4.9, 11.2, 118, '39', 'female'), interpretation: 'AKI.' },
    amylase: { values: [lab('Amylase', 186, 'U/L', '30–110', 'H')], interpretation: 'Mildly raised — non-specific (seen in ischaemic bowel).' },
    coag: { values: [lab('INR', 1.1, '', '0.8–1.2'), lab('APTT', 29, 's', '25–35')], interpretation: 'Not anticoagulated.' },
    cta: {
      report:
        'Occlusive filling defect in the proximal superior mesenteric artery 4 cm beyond its origin, consistent with an embolus. Jejunal and ileal loops show reduced mural enhancement and wall thickening. No pneumatosis or portal venous gas. Coeliac axis and IMA patent.',
      interpretation: 'Acute embolic SMA occlusion with ischaemic small bowel.',
      abnormal: true,
    },
    axr: { report: 'Gasless abdomen; no dilated loops.', interpretation: 'Normal or non-specific early — gives false reassurance.' },
    troponin: { values: [lab('hs-Troponin T', 22, 'ng/L', '< 14', 'H')], interpretation: 'Mild rise from tachycardia/stress.' },
    gs: { report: 'Group A RhD positive. Antibody screen negative.' },
  },
  investigationRubric: {
    essential: [
      { id: 'vbg', why: 'Lactate: a high lactate with a soft abdomen is a red flag.' },
      { id: 'ecg', why: 'Confirms AF — the embolic source.' },
      { id: 'cta', why: '!CT angiography is the diagnostic test of choice — do not wait for the lactate to rise.' },
      { id: 'fbc', why: 'Leucocytosis.' },
      { id: 'ue', why: 'AKI; contrast risk.' },
    ],
    helpful: [
      { id: 'coag', why: 'Before heparin and theatre.' },
      { id: 'gs', why: 'Pre-operative.' },
      { id: 'amylase', why: 'Exclude pancreatitis.' },
      { id: 'troponin', why: 'Cardiac risk.' },
    ],
    avoid: [{ id: 'axr', why: 'Usually normal early — a false reassurance that delays CT angiography.' }],
  },
  diagnosis: {
    correct: 'mesenteric-ischaemia',
    differentials: ['aaa-rupture', 'perforated-pu', 'pancreatitis', 'sbo-adhesions', 'ischaemic-colitis', 'mi'],
  },
  management: {
    essential: [
      { id: 'abcde', why: 'Sick patient — ABCDE.' },
      { id: 'fluids', why: 'Resuscitate.' },
      { id: 'analgesia', why: 'IV opioids.' },
      { id: 'anticoag-heparin', why: 'Therapeutic unfractionated heparin limits clot propagation.' },
      { id: 'abx-iv', why: 'Broad-spectrum antibiotics (bacterial translocation from ischaemic gut).' },
      { id: 'vascular', why: 'Urgent vascular and general surgical involvement.' },
      { id: 'embolectomy', why: '!Urgent revascularisation (embolectomy/endovascular) with laparotomy to assess and resect non-viable bowel.' },
    ],
    helpful: [
      { id: 'laparotomy', why: 'Laparotomy to inspect bowel viability (often with a planned second look).' },
      { id: 'icu', why: 'Critical care.' },
      { id: 'catheter', why: 'Urine output.' },
      { id: 'ng', why: 'Vomiting / ileus.' },
      { id: 'o2', why: 'Supplemental oxygen.' },
      { id: 'breaking-news', why: 'High mortality — discuss escalation with her and her son early.' },
    ],
    avoid: [
      { id: 'discharge', why: 'Life-threatening diagnosis.' },
      { id: 'drip-suck', why: 'This is not simple obstruction.' },
      { id: 'laxatives', why: 'No role.' },
    ],
  },
  viva: [
    {
      id: 'out-of-proportion',
      q: 'What is the hallmark clinical feature of acute mesenteric ischaemia?',
      options: ['Pain out of proportion to the examination findings', 'Board-like rigidity from the outset', 'A pulsatile mass', 'Painless jaundice'],
      correct: 0,
      answer: 'Severe pain with a soft, only mildly tender abdomen early on (visceral ischaemia before the parietal peritoneum is involved). Peritonism appears late — when the bowel is already infarcting.',
      topic: 'Recognition',
    },
    {
      id: 'causes',
      q: 'What are the causes of acute mesenteric ischaemia?',
      answer:
        'Arterial embolism (~50%, usually AF or mural thrombus after MI — lodges in the SMA just beyond the middle colic origin), arterial thrombosis on atherosclerosis (often with preceding “intestinal angina”: post-prandial pain, food fear, weight loss), non-occlusive mesenteric ischaemia (low-flow states, vasopressors, cardiac failure) and mesenteric venous thrombosis (thrombophilia, portal hypertension).',
      topic: 'Aetiology',
    },
    {
      id: 'lactate',
      q: 'Can a normal lactate exclude mesenteric ischaemia?',
      answer: 'No. Lactate may be normal early (the liver clears portal lactate) and rises as infarction develops. Clinical suspicion should prompt urgent CT angiography regardless.',
      topic: 'Investigation',
    },
    {
      id: 'pulse',
      q: 'Why did examining the radial pulse matter in this station?',
      answer: 'An irregularly irregular pulse identifies AF — the embolic source that turns “severe abdominal pain in an older woman” into suspected mesenteric embolism. She had also stopped her anticoagulant.',
      topic: 'Examination',
    },
  ],
  teaching: {
    summary:
      'Acute embolic mesenteric ischaemia in a 79-year-old with atrial fibrillation whose anticoagulation had been stopped: sudden severe central abdominal pain out of proportion to a soft abdomen, dark rectal blood, an irregularly irregular pulse and a lactate of 6.2.',
    keyFindings: [
      'Sudden severe central pain, unrelieved by morphine; restless, not lying still',
      'Soft abdomen with only mild tenderness — pain out of proportion to signs',
      'Irregularly irregular pulse 128 (AF); apixaban stopped 2 months ago',
      'Dark blood in the stool; lactate 6.2, metabolic acidosis',
      'CT angiogram: SMA embolus with ischaemic small bowel',
    ],
    pearls: [
      'Always feel the pulse yourself — AF changes the differential.',
      'A soft abdomen does not exclude a catastrophe.',
      'Lactate is supportive, not diagnostic; CT angiography is the test.',
      'Time is bowel: early heparin, revascularisation and resection of dead gut.',
    ],
    presentation:
      'Mrs Walsh is a 79-year-old woman with atrial fibrillation, whose apixaban was stopped two months ago after a fall, presenting with six hours of sudden severe central abdominal pain unrelieved by morphine, vomiting and dark blood per rectum, on a background of post-prandial pain and weight loss. She is restless, tachycardic at 128 in an irregularly irregular rhythm, with a soft abdomen that is only mildly tender — pain out of proportion to the signs. Lactate is 6.2 with a metabolic acidosis and WCC 21. CT angiography shows an embolic occlusion of the superior mesenteric artery with ischaemic small bowel. This is acute mesenteric ischaemia. I would resuscitate her, give IV analgesia, antibiotics and therapeutic heparin, and refer urgently to vascular and general surgery for revascularisation and laparotomy, while discussing the high risk with her and her son.',
    references: ['ESVS 2017 guidelines on the management of diseases of mesenteric arteries and veins', 'Macleod’s Clinical Examination, 14th ed. — Ch. 4: the pulse; Ch. 6: the acute abdomen'],
  },
}

export default c
