import type { CaseDef } from '../../engine/types'
import { lab } from './helpers'

const c: CaseDef = {
  id: 'mng',
  title: 'Multinodular goitre (euthyroid)',
  presenting: 'Neck swelling',
  specialty: 'Endocrine',
  exam: 'thyroid',
  difficulty: 2,
  setting: 'Outpatient clinic',
  stem: 'Endocrine surgery clinic. Linda Carter, 58, has noticed her neck getting bigger. Take a focused history, examine her neck, request investigations and explain your plan.',
  components: ['history', 'exam', 'investigations', 'diagnosis', 'viva'],
  tags: ['thyroid', 'goitre', 'euthyroid', 'U-grade'],
  patient: {
    name: 'Linda Carter',
    title: 'Mrs Carter',
    age: 58,
    sex: 'female',
    dob: '07/07/1967',
    occupation: 'a hairdresser',
    appearance: { sex: 'female', age: 58, skinTone: 1, habitus: 'overweight', hair: 'bob', hairColor: 'blonde', eyeColor: 'blue' },
    persona: { mood: 'anxious', style: 'chatty' },
  },
  vitals: { hr: 74, rhythm: 'regular', sbp: 136, dbp: 82, rr: 14, spo2: 98, temp: 36.6, avpu: 'A', pain: 0 },
  visual: { neck: { goitre: { kind: 'multinodular', size: 2 } } },
  history: {
    opening: 'My neck has been getting bigger for a few years. My daughter says it’s really noticeable now.',
    answers: {
      'lump.when': 'At least three or four years — it’s grown very slowly.',
      'lump.change': 'Slowly bigger. Nothing sudden.',
      'lump.pain': 'No, it doesn’t hurt.',
      'lump.other': 'No other lumps.',
      'gi.dysphagia': 'Occasionally a big tablet feels like it sticks, but food goes down fine.',
      'thy.breathing': 'No noisy breathing. I can lie flat without any problem.',
      'thy.voice': 'My voice hasn’t changed.',
      'thy.heat': 'I don’t mind either — no real change.',
      'thy.tremor': 'No shaking.',
      'thy.mood': 'My mood is fine.',
      'thy.eyes': 'No eye problems.',
      'thy.radiation': 'No, never had radiotherapy.',
      'thy.fh': 'My sister has a goitre too — hers has never been treated.',
      'gi.weight': 'Stable.',
      'ros.palpitations': 'No palpitations.',
      'pmh.conditions': 'Just high blood pressure.',
      'dh.meds': 'Amlodipine.',
      'dh.allergies': 'No allergies.',
      'sh.smoking': 'I gave up ten years ago.',
      'comm.questions': 'Is it cancer? Will I need an operation?',
    },
    key: ['comm.open', 'lump.when', 'lump.change', 'lump.pain', 'gi.dysphagia', 'thy.breathing', 'thy.voice', 'thy.heat', 'thy.tremor', 'thy.eyes', 'thy.radiation', 'thy.fh', 'gi.weight', 'ros.palpitations'],
    critical: ['thy.breathing', 'thy.voice'],
    ideas: 'I think it’s a goitre, like my sister’s.',
    concerns: 'I’m frightened it might be cancer.',
    expectations: 'I want to know what it is and whether it needs to come out.',
  },
  keyed: {
    'thy.general': { text: 'A comfortable, well-looking woman, appropriately dressed. No signs of thyroid over- or under-activity from the end of the bed.' },
    'thy.hands': { text: 'Warm, dry hands. No tremor, palmar erythema, onycholysis or acropachy.' },
    'thy.tremor': { text: 'No tremor.' },
    'thy.pulse': { text: 'Pulse 74, regular.' },
    'thy.eyes': { text: 'No exophthalmos, lid retraction or chemosis.' },
    'thy.lidlag': { text: 'No lid lag.' },
    'thy.eom': { text: 'Full eye movements.' },
    'thy.neckInspect': { text: 'A visible, asymmetrical, lumpy swelling of the lower anterior neck, larger on the left. No scars or dilated veins.', abnormal: true },
    'thy.swallow': { text: 'The whole swelling moves up on swallowing.', abnormal: true, meaning: 'Moves with swallowing → it is thyroid.' },
    'thy.tongue': { text: 'It does not move on tongue protrusion.' },
    'thy.palpate': {
      text: 'From behind: an enlarged, firm, non-tender thyroid with multiple nodules in both lobes — the largest about 3 cm in the left lobe. You can get below the lower border of both lobes.',
      abnormal: true,
      meaning: 'Multiple nodules in both lobes = multinodular goitre. Being able to get below the gland makes retrosternal extension unlikely.',
    },
    'thy.nodes': { text: 'No cervical lymphadenopathy.', meaning: 'Lymphadenopathy would raise concern for papillary carcinoma.' },
    'thy.trachea': { text: 'Trachea central.' },
    'thy.percuss': { text: 'Resonant over the manubrium.' },
    'thy.bruit': { text: 'No bruit.' },
    'thy.pemberton': { text: 'Pemberton’s sign negative: no facial plethora or venous distension after a minute with the arms raised.' },
    'thy.reflexes': { text: 'Normal ankle reflexes.' },
    'thy.proximal': { text: 'Stands easily from the chair.' },
    'thy.shins': { text: 'Normal shins.' },
  },
  criticalSteps: ['neck.swallow', 'neck.palpate', 'neck.nodes'],
  investigations: {
    tft: { values: [lab('TSH', '0.9', 'mU/L', '0.3–4.2'), lab('Free T4', '16.1', 'pmol/L', '12–22'), lab('Free T3', '4.9', 'pmol/L', '3.1–6.8')], interpretation: 'Euthyroid.' },
    'us-neck': {
      report: 'Enlarged thyroid with multiple nodules in both lobes, the largest 31 mm in the left lobe: mixed solid-cystic, spongiform, well-defined with a smooth halo, no microcalcification (U2 — benign features). No suspicious cervical lymph nodes. No retrosternal extension.',
      interpretation: 'Multinodular goitre with benign (U2) features — FNA is not required.',
      abnormal: true,
    },
  },
  investigationRubric: {
    essential: [
      { id: 'tft', why: '!Establish thyroid status — a toxic MNG changes management.' },
      { id: 'us-neck', why: 'Characterises nodules (U-grade) and decides whether FNA is needed.' },
    ],
    helpful: [{ id: 'calcium', why: 'Useful baseline if surgery is considered.' }],
    avoid: [{ id: 'fna', why: 'FNA of U2 (benign) nodules is not indicated — only for U3–U5 or clinically suspicious nodules.' }],
  },
  diagnosis: { correct: 'mng', differentials: ['toxic-mng', 'thyroid-cancer', 'hashimoto', 'solitary-nodule'] },
  management: {
    essential: [{ id: 'reassure', why: 'Benign, euthyroid, no compressive symptoms: explain and safety-net (rapid growth, voice change, stridor, dysphagia).' }],
    helpful: [
      { id: 'watchful-waiting', why: 'Clinical and ultrasound surveillance is reasonable.' },
      { id: 'thyroidectomy', why: 'Offer total thyroidectomy if compressive symptoms develop, it extends retrosternally, it becomes toxic, or for cosmesis.' },
    ],
    avoid: [{ id: 'carbimazole', why: 'She is euthyroid.' }],
  },
  viva: [
    {
      id: 'moves',
      q: 'Why does the thyroid move on swallowing?',
      options: ['It is attached to the hyoid by the thyroglossal duct', 'It is invested in the pretracheal fascia, which is attached to the larynx', 'It is attached to the sternum', 'Because of the platysma'],
      correct: 1,
      answer: 'The thyroid is enclosed in the pretracheal fascia, which is attached to the thyroid and cricoid cartilages, so the gland rises with the larynx on swallowing. A thyroglossal cyst also moves with tongue protrusion because of its tract to the foramen caecum.',
      topic: 'Anatomy',
    },
    {
      id: 'surgery-risks',
      q: 'What are the specific risks of thyroidectomy?',
      answer: 'Recurrent laryngeal nerve injury (hoarseness; bilateral → airway obstruction), external branch of the superior laryngeal nerve injury (loss of high pitch — important for singers), hypocalcaemia from parathyroid damage/devascularisation, bleeding with neck haematoma (can compromise the airway — open the wound at the bedside), hypothyroidism (lifelong levothyroxine after total thyroidectomy), thyroid storm (rare), and scarring.',
      topic: 'Surgery',
    },
    {
      id: 'cancer-signs',
      q: 'Which features make a thyroid nodule suspicious for cancer?',
      answer: 'Clinical: rapid growth, hard or fixed nodule, cervical lymphadenopathy, hoarseness (recurrent laryngeal nerve invasion), stridor, age < 20 or > 60, male sex, previous neck irradiation, family history of thyroid cancer/MEN2. Ultrasound (U4–U5): solid hypoechoic, microcalcification, irregular margins, taller-than-wide, abnormal vascularity, suspicious nodes.',
      topic: 'Red flags',
    },
  ],
  teaching: {
    summary: 'A slowly enlarging, asymmetrical, nodular goitre that moves on swallowing, in a clinically euthyroid woman without compressive symptoms — a benign multinodular goitre, confirmed on TFTs and ultrasound (U2).',
    keyFindings: ['Asymmetrical nodular goitre, larger on the left', 'Moves on swallowing, not on tongue protrusion', 'Can get below it; resonant manubrium; Pemberton’s negative', 'Clinically euthyroid; no lymphadenopathy'],
    pearls: [
      'Try to get below the gland — if you can’t, suspect retrosternal extension and percuss the manubrium and test Pemberton’s sign.',
      'Always palpate the cervical nodes: lymphadenopathy with a thyroid nodule suggests papillary carcinoma.',
      'Ultrasound U-grade (U1–U5) decides who needs FNA; Thy1–Thy5 is the cytology grade.',
    ],
    presentation:
      'I examined Mrs Linda Carter, a 58-year-old woman who looked well and clinically euthyroid: her pulse was 74 and regular with no tremor, eye signs or peripheral stigmata. There was a visible, asymmetrical swelling of the lower anterior neck that moved on swallowing but not with tongue protrusion. On palpation from behind there was a firm, non-tender, nodular goitre involving both lobes, with the largest nodule about 3 cm in the left lobe; I could get below the gland. There was no lymphadenopathy, the trachea was central, the manubrium was resonant, there was no bruit, and Pemberton’s sign was negative. These findings are consistent with a multinodular goitre. I would check thyroid function and arrange an ultrasound of the neck.',
    references: ['Macleod’s Clinical Examination, 14th ed. — Ch. 10: The endocrine system (thyroid)', 'British Thyroid Association: Guidelines for the management of thyroid cancer (U and Thy grading)', 'NICE NG145: Thyroid disease'],
  },
}

export default c
