import type { CaseDef } from '../../engine/types'
import { CRP, FBC, lab, LFT, UE } from './helpers'

const c: CaseDef = {
  id: 'oesophageal-cancer',
  title: 'Adenocarcinoma of the lower oesophagus',
  presenting: 'Food sticking when swallowing and weight loss',
  specialty: 'Upper GI',
  exam: 'abdominal',
  difficulty: 2,
  setting: 'Outpatient clinic',
  stem: 'Upper GI clinic (urgent suspected-cancer referral). Graham Fletcher, 67, has difficulty swallowing. Take a history, examine him, request investigations and explain the plan.',
  components: ['history', 'exam', 'investigations', 'diagnosis', 'viva'],
  tags: ['dysphagia', 'weight loss', 'cancer', '2WW', 'Barrett’s'],
  patient: {
    name: 'Graham Fletcher',
    title: 'Mr Fletcher',
    age: 67,
    sex: 'male',
    dob: '25/07/1959',
    occupation: 'a retired lorry driver',
    appearance: { sex: 'male', age: 67, skinTone: 1, habitus: 'thin', hair: 'receding', hairColor: 'grey', eyeColor: 'blue', pallor: 0.35, cachexia: true },
    persona: { mood: 'stoic', style: 'brief' },
  },
  vitals: { hr: 84, rhythm: 'regular', sbp: 132, dbp: 80, rr: 15, spo2: 97, temp: 36.5, avpu: 'A', pain: 1 },
  history: {
    opening: 'Food’s been getting stuck when I swallow. It started with bread and meat; now even mashed potato is a struggle.',
    answers: {
      'gi.dysphagia': 'Yes — for about three months, and it’s getting worse.',
      'gi.dysphagia_type': { text: 'Solids first — bread, steak. Now soft food too. Drinks still go down, mostly.', cue: 'mimes food sticking' },
      'gi.dysphagia_level': { text: 'It sticks here, behind the bottom of the breastbone.', cue: 'points to the lower sternum' },
      'gi.regurgitation': 'Sometimes it comes back up straight away, undigested.',
      'gi.odynophagia': 'It aches a bit when it sticks.',
      'gi.weight': 'I’ve lost about nine kilos in three months. My belt’s on the last notch.',
      'gi.appetite': 'I’m hungry, but I’m frightened to eat.',
      'gi.reflux': 'I’ve had heartburn for twenty years. I take omeprazole — it used to be bad at night.',
      'gi.vomiting': 'Only when food comes back up.',
      'gi.vomit_content': 'Food. No blood.',
      'gi.melaena': 'No black stools.',
      'thy.voice': 'My voice is fine.',
      'ros.cough': 'Sometimes I cough when I eat.',
      'ros.chest_pain': 'No chest pain.',
      'sys.fatigue': 'Very tired.',
      'pmh.conditions': 'Reflux, high blood pressure. They said I had a “Barrett’s” years ago but I never went back for the camera test.',
      'pmh.gi': 'Barrett’s oesophagus found about ten years ago. I missed the follow-ups.',
      'dh.meds': 'Omeprazole and amlodipine.',
      'dh.allergies': 'None.',
      'sh.smoking': 'Thirty a day for forty years.',
      'sh.alcohol': 'Four or five pints a night until recently.',
      'sh.living': 'Lives alone; my daughter visits.',
      'fh.cancer': 'No cancers in the family.',
      'comm.questions': 'Is it cancer, doctor?',
    },
    key: [
      'comm.open',
      'gi.dysphagia',
      'gi.dysphagia_type',
      'gi.dysphagia_level',
      'gi.regurgitation',
      'gi.odynophagia',
      'gi.weight',
      'gi.reflux',
      'gi.melaena',
      'thy.voice',
      'pmh.gi',
      'dh.meds',
      'sh.smoking',
      'sh.alcohol',
    ],
    critical: ['gi.weight', 'gi.dysphagia_type'],
    ideas: 'I’ve been worried it’s something growing.',
    concerns: 'My mate had throat cancer.',
    expectations: 'I want to know what’s going on and be able to eat again.',
    social: { smoking: '60 pack-years.', alcohol: '~70 units a week until recently.', living: 'Alone.' },
    pmh: 'GORD, Barrett’s oesophagus (lost to surveillance), hypertension.',
  },
  abdo: {
    general: {
      endOfBed: 'Mr Fletcher is thin and pale, with loose clothes and temporal wasting. He is comfortable at rest.',
    },
    hands: { temperature: 'warm', crt: 2, pallorCreases: true, tarStaining: true },
    face: { conjunctiva: 'pale', mucosa: 'moist', angularCheilitis: true },
    neck: { virchow: false, nodes: 'No supraclavicular or cervical lymphadenopathy.' },
    abdomen: {
      shape: 'scaphoid',
      bowelSounds: 'normal',
      liver: { edgeCm: 0, spanCm: 10 },
    },
    completion: { dre: 'Brown stool; no melaena.', obs: 'Weight 61 kg (70 kg three months ago): 13% weight loss.' },
  },
  criticalSteps: ['neck.nodes'],
  investigations: {
    ogd: {
      report: 'At 35 cm from the incisors: a friable, ulcerated, circumferential tumour narrowing the lumen, extending to the gastro-oesophageal junction at 39 cm, arising in a segment of Barrett’s mucosa. The scope passed with difficulty. Biopsies taken.',
      interpretation: 'Malignant-looking stricture of the lower oesophagus — histology: moderately differentiated adenocarcinoma.',
      abnormal: true,
    },
    'ct-cap': {
      report: 'Thickening of the distal oesophagus over 5 cm with periesophageal fat stranding and two enlarged paraoesophageal nodes (12 mm). No liver, lung or peritoneal metastases.',
      interpretation: 'Locally advanced (cT3 N1 M0) — potentially curable.',
      abnormal: true,
    },
    'pet-ct': { report: 'FDG-avid distal oesophageal tumour and paraoesophageal nodes. No distant disease.', interpretation: 'No metastases — proceed to curative-intent treatment.', abnormal: true },
    eus: { report: 'Tumour through the muscularis propria into the adventitia (T3); two malignant-looking nodes (N1).', interpretation: 'Accurate local T and N staging.', abnormal: true },
    fbc: { values: FBC(104, 6.8, 4.4, 410, 74), interpretation: 'Microcytic anaemia — likely chronic blood loss from the tumour.' },
    ue: { values: UE(134, 3.6, 4.1, 68, '> 90'), interpretation: 'Normal.' },
    lft: { values: LFT(8, 22, 96, 44, 29), interpretation: 'Low albumin — malnutrition.' },
    crp: { values: CRP(12) },
    'contrast-swallow': { report: 'An irregular ‘apple-core’ stricture of the distal oesophagus with shouldered margins and proximal dilatation.', interpretation: 'Malignant stricture appearance — OGD and biopsy are still essential.', abnormal: true },
    haematinics: { values: [lab('Ferritin', '9', 'µg/L', '30–300', 'L')], interpretation: 'Iron deficiency.' },
  },
  investigationRubric: {
    essential: [
      { id: 'ogd', why: 'First-line test for dysphagia: see and biopsy the lesion.' },
      { id: 'ct-cap', why: 'Staging for distant spread.' },
      { id: 'fbc', why: 'Anaemia.' },
      { id: 'lft', why: 'Albumin (nutrition) and liver metastases.' },
      { id: 'ue', why: 'Baseline; dehydration.' },
    ],
    helpful: [
      { id: 'pet-ct', why: 'Detects occult metastases before radical treatment.' },
      { id: 'eus', why: 'Local T and N staging.' },
      { id: 'haematinics', why: 'Iron deficiency.' },
      { id: 'contrast-swallow', why: 'Only if OGD is unavailable or to map a stricture.' },
    ],
    avoid: [{ id: 'manometry', why: 'Exclude a mechanical cause first — manometry is for motility disorders.' }],
  },
  diagnosis: {
    correct: 'oesophageal-cancer',
    differentials: ['peptic-stricture', 'achalasia', 'gastric-cancer', 'pharyngeal-pouch', 'gord'],
  },
  management: {
    essential: [
      { id: '2ww', why: 'Dysphagia, or ≥ 55 with weight loss and reflux — urgent direct-access OGD within 2 weeks.' },
      { id: 'breaking-news', why: 'Explain the diagnosis honestly, with his daughter present if he wishes.' },
      { id: 'mdt', why: 'Upper GI cancer MDT decides treatment after staging.' },
      { id: 'oesophagectomy', why: '!Locally advanced, no metastases, reasonably fit: neoadjuvant chemotherapy (or chemoradiotherapy) then oesophagectomy.' },
      { id: 'dietitian', why: '13% weight loss — nutritional support (± feeding jejunostomy or stent while awaiting treatment).' },
    ],
    helpful: [
      { id: 'iron', why: 'Iron-deficiency anaemia.' },
      { id: 'smoking-cessation', why: 'Improves surgical outcome.' },
      { id: 'alcohol-support', why: 'Heavy drinker — withdrawal and thiamine.' },
      { id: 'palliative', why: 'If unfit or metastatic: stent for swallowing, palliative chemo or radiotherapy.' },
    ],
    avoid: [
      { id: 'reassure', why: 'Progressive dysphagia with weight loss is cancer until proven otherwise.' },
      { id: 'watchful-waiting', why: 'Delay worsens outcome.' },
      { id: 'heller', why: 'That is for achalasia.' },
    ],
  },
  viva: [
    {
      id: 'redflags',
      q: 'Which features of dysphagia point to cancer?',
      answer: 'Progressive dysphagia for solids then liquids over weeks to months, weight loss, age over 55, anaemia, a long history of reflux or Barrett’s, smoking and alcohol. A motility disorder (achalasia) typically affects solids and liquids from the start.',
      topic: 'History',
    },
    {
      id: 'types',
      q: 'Compare the two main types of oesophageal cancer.',
      options: [
        'Adenocarcinoma: lower third, reflux/Barrett’s/obesity; squamous: upper/middle, smoking/alcohol',
        'Both arise only in the upper third',
        'Squamous is linked to Barrett’s',
        'Adenocarcinoma is commonest in the upper third',
      ],
      correct: 0,
      answer: 'Adenocarcinoma (commonest in the UK) arises in the lower third and GOJ from Barrett’s metaplasia; risks are reflux, obesity and male sex. Squamous cell carcinoma arises in the upper and middle thirds; risks are smoking, alcohol, achalasia and hot drinks.',
      topic: 'Pathology',
    },
    {
      id: 'exam',
      q: 'What would you look for on examination of a patient with dysphagia?',
      answer: 'Weight and BMI, cachexia, pallor (anaemia), koilonychia and angular cheilitis (iron deficiency), a left supraclavicular node (Troisier’s sign), hepatomegaly or ascites (metastases), and signs of aspiration in the chest. Look in the mouth and at the neck too (goitre, pouch).',
      topic: 'Examination',
    },
    {
      id: 'barretts',
      q: 'What is Barrett’s oesophagus?',
      answer: 'Replacement of the normal squamous lining of the lower oesophagus by columnar (intestinal-type) epithelium due to chronic reflux. It is premalignant — patients have endoscopic surveillance, and dysplasia is treated endoscopically.',
      topic: 'Pathology',
    },
  ],
  teaching: {
    summary:
      'Lower oesophageal adenocarcinoma in a 67-year-old smoker and drinker with long-standing reflux and untreated Barrett’s: three months of progressive dysphagia (solids → soft food) felt behind the lower sternum, 13% weight loss and iron-deficiency anaemia; staged cT3 N1 M0 for neoadjuvant therapy and oesophagectomy.',
    keyFindings: [
      'Progressive dysphagia over 3 months: solids, then soft food',
      'Sticks behind the lower sternum; regurgitation of undigested food',
      '9 kg (13%) weight loss; pallor, angular cheilitis',
      'Barrett’s oesophagus lost to surveillance; 60 pack-years; heavy alcohol',
      'OGD: ulcerated stricture 35–39 cm; biopsy adenocarcinoma',
    ],
    pearls: [
      'Dysphagia is a red-flag symptom at any age — urgent OGD.',
      'Ask solids vs liquids, progression, the level it sticks and weight loss.',
      'Always feel for a left supraclavicular (Virchow’s) node.',
      'Nutrition matters: a third of patients are malnourished at diagnosis.',
    ],
    presentation:
      'Mr Fletcher is a 67-year-old retired lorry driver with three months of progressive dysphagia, first to solids and now to soft foods, sticking behind the lower sternum with regurgitation, and 9 kilograms of weight loss. He has twenty years of reflux and Barrett’s oesophagus that was never followed up, has smoked 60 pack-years and drinks heavily. On examination he is thin and pale with angular cheilitis but no supraclavicular lymphadenopathy, hepatomegaly or ascites. He has a microcytic anaemia and a low albumin. OGD shows an ulcerated malignant stricture from 35 to 39 centimetres, and biopsies confirm adenocarcinoma; CT and PET stage it as T3 N1 with no metastases. I would break the news sensitively, refer him to the upper GI MDT for neoadjuvant chemotherapy and oesophagectomy, and arrange dietetic support.',
    references: ['Macleod’s Clinical Examination, 14th ed. — Ch. 6: dysphagia (history) and the gastrointestinal examination', 'NICE NG12: suspected cancer — recognition and referral'],
  },
}

export default c
