import type { CaseDef } from '../../engine/types'
import { COAG, FBC, lab, LFT, r, UE } from './helpers'

const c: CaseDef = {
  id: 'pancreatic-cancer',
  title: 'Carcinoma of the head of the pancreas (painless obstructive jaundice)',
  presenting: 'Painless jaundice and weight loss',
  specialty: 'Hepatobiliary',
  exam: 'abdominal',
  difficulty: 2,
  setting: 'Surgical assessment unit',
  stem: 'Ahmed Hassan, 68, was referred urgently by his GP after his family noticed he had turned yellow. Take a history, examine his abdomen, investigate and discuss the next steps.',
  components: ['history', 'exam', 'investigations', 'diagnosis', 'viva'],
  tags: ['jaundice', 'Courvoisier', 'weight loss', 'cancer pathway'],
  patient: {
    name: 'Ahmed Hassan',
    title: 'Mr Hassan',
    age: 68,
    sex: 'male',
    dob: '07/05/1958',
    occupation: 'a retired accountant',
    appearance: {
      sex: 'male',
      age: 68,
      skinTone: 4,
      habitus: 'thin',
      hair: 'bald',
      hairColor: 'grey',
      eyeColor: 'brown',
      facialHair: 'moustache',
      glasses: true,
      jaundice: 0.85,
      cachexia: true,
      excoriations: true,
    },
    persona: { mood: 'anxious', style: 'normal' },
  },
  vitals: { hr: 84, rhythm: 'regular', sbp: 128, dbp: 74, rr: 16, spo2: 98, temp: 36.8, avpu: 'A', pain: 2 },
  history: {
    opening: { text: 'My family say I’ve gone yellow — it’s been getting worse for about three weeks. And I can’t stop itching.', cue: 'scratches his forearms' },
    answers: {
      'pain.site': 'There’s no real pain. Just a vague ache in the top of my stomach, sometimes going into my back.',
      'pain.onset': 'The ache has been there on and off for a couple of months.',
      'pain.character': 'Dull. Nagging.',
      'pain.radiation': 'Sometimes into the middle of my back.',
      'pain.severity': 'Two or three at most.',
      'gi.jaundice': 'About three weeks ago my wife noticed my eyes. Now my skin too. It’s getting deeper.',
      'gi.itch': 'The itching is driving me mad, especially at night.',
      'gi.dark_urine': 'Very dark — like cola.',
      'gi.stool_colour': 'Pale, greasy, they float and are hard to flush.',
      'gi.weight': 'About eight kilos in three months without trying. My belts are on the last notch.',
      'gi.appetite': 'I’ve gone right off food.',
      'gi.nausea': 'A little.',
      'gi.vomiting': 'No.',
      'sys.fever': 'No fevers or shivers.',
      'sys.rigors': 'No.',
      'sys.fatigue': 'Exhausted.',
      'pmh.conditions': 'They found diabetes two months ago. Before that, nothing.',
      'pmh.diabetes': 'Diagnosed two months ago — out of the blue. They started metformin.',
      'pmh.gi': 'No gallstones or liver problems that I know of.',
      'dh.meds': 'Metformin, since two months ago.',
      'sh.smoking': 'I smoked twenty a day for forty years — stopped five years ago.',
      'sh.alcohol': 'I don’t drink.',
      'sh.travel': 'No travel.',
      'fh.cancer': 'My brother had cancer of the pancreas.',
      'comm.questions': 'Is it cancer? Please tell me honestly.',
    },
    key: ['comm.open', 'gi.jaundice', 'pain.site', 'gi.itch', 'gi.dark_urine', 'gi.stool_colour', 'gi.weight', 'gi.appetite', 'sys.fever', 'pmh.diabetes', 'pmh.gi', 'sh.smoking', 'sh.alcohol', 'sh.travel', 'fh.cancer', 'dh.meds'],
    critical: ['gi.weight'],
    ideas: 'I’m worried it’s the same thing my brother had.',
    concerns: 'Cancer. My brother died within a year.',
    expectations: 'To know what it is, and to know the truth.',
    social: { smoking: 'Ex-smoker: 40 pack-years, stopped 5 years ago.', alcohol: 'None.', living: 'With his wife.' },
  },
  abdo: {
    general: {
      endOfBed:
        'Mr Hassan is a thin man who looks cachectic, with obvious jaundice — best seen in his sclerae — and scratch marks on his forearms. He is comfortable at rest. No drains or lines.',
    },
    hands: { armMarks: 'Linear excoriations (scratch marks) on both forearms.' },
    face: { sclera: 'icteric' },
    abdomen: {
      shape: 'scaphoid',
      regions: {
        RUQ: r(0, 1, 'none', {
          mass: { description: 'a smooth, globular, non-tender mass that moves down with respiration at the tip of the right 9th costal cartilage', label: 'palpable gallbladder', sizeCm: 6, movesWithRespiration: true },
        }),
      },
      gallbladder: { palpable: true, murphy: false },
      liver: { edgeCm: 0, spanCm: 12 },
    },
    completion: { urinalysis: 'Bilirubin +++, urobilinogen negative, glucose +.' },
  },
  criticalSteps: ['org.gb', 'neck.nodes'],
  investigations: {
    lft: { values: LFT(214, 142, 780, 1020, 31), interpretation: 'Severe obstructive picture.' },
    coag: { values: COAG(15.8, 1.5, 34), interpretation: 'Raised INR from vitamin K malabsorption (no bile salts in the gut) — correct with IV vitamin K.' },
    fbc: { values: FBC(121, 7.2, 4.8, 330), interpretation: 'Mild anaemia.' },
    ue: { values: UE(137, 4.1, 5.8, 82, '> 90'), interpretation: 'Normal.' },
    glucose: { values: [lab('Glucose (random)', 12.6, 'mmol/L', '4.0–7.8', 'H'), lab('HbA1c', 64, 'mmol/mol', '< 42', 'H')], interpretation: 'New-onset diabetes can be the first sign of pancreatic cancer.' },
    ca199: { values: [lab('CA 19-9', 1840, 'U/mL', '< 37', 'HH')], interpretation: 'Very high — supports pancreatic malignancy (but also rises in any biliary obstruction; not a diagnostic test on its own).' },
    'us-abdo': {
      report: 'Dilated intrahepatic ducts and common bile duct (15 mm) down to the pancreatic head, where the view is obscured. Distended gallbladder without calculi. No liver lesions seen.',
      interpretation: 'Low (distal) biliary obstruction without gallstones — suspicious of a periampullary/pancreatic head tumour.',
      abnormal: true,
    },
    'ct-ap': {
      report:
        'Pancreas-protocol CT: 3.2 cm hypoenhancing mass in the pancreatic head causing dilatation of both the common bile duct and the pancreatic duct (“double duct sign”). Abuts the superior mesenteric vein < 180°; no arterial involvement. No liver metastases or ascites.',
      interpretation: 'Pancreatic head adenocarcinoma — potentially resectable on imaging.',
      abnormal: true,
    },
    'ct-cap': { report: 'No pulmonary or hepatic metastases. No distant lymphadenopathy.', interpretation: 'No distant disease.' },
    fna: { report: 'EUS-guided FNA of the pancreatic head mass: adenocarcinoma.', interpretation: 'Tissue diagnosis of pancreatic ductal adenocarcinoma.', abnormal: true },
    mrcp: { report: 'Abrupt tapering of the distal CBD and pancreatic duct at the pancreatic head with upstream dilatation. No stones.', interpretation: 'Malignant-looking distal stricture.', abnormal: true },
  },
  investigationRubric: {
    essential: [
      { id: 'lft', why: 'Confirm obstructive jaundice.' },
      { id: 'us-abdo', why: 'First-line: duct dilatation and level of obstruction; gallstones?' },
      { id: 'ct-ap', why: 'NICE NG85: pancreatic-protocol CT for suspected pancreatic cancer — diagnosis and staging.' },
      { id: 'coag', why: 'INR is often raised — correct before any intervention.' },
    ],
    helpful: [
      { id: 'ca199', why: 'Supportive tumour marker; baseline for follow-up.' },
      { id: 'glucose', why: 'New diabetes.' },
      { id: 'fbc', why: 'Baseline.' },
      { id: 'ue', why: 'Baseline before contrast.' },
      { id: 'ct-cap', why: 'Staging.' },
      { id: 'fna', why: 'EUS-guided biopsy when tissue is needed (e.g. before chemotherapy).' },
      { id: 'mrcp', why: 'Defines the biliary anatomy.' },
    ],
  },
  diagnosis: {
    correct: 'pancreatic-cancer',
    differentials: ['cholangiocarcinoma', 'choledocholithiasis', 'chronic-pancreatitis', 'liver-mets', 'hepatitis'],
  },
  management: {
    essential: [
      { id: '2ww', why: 'Urgent suspected-cancer referral to the specialist HPB team.' },
      { id: 'mdt', why: 'Discuss at the specialist pancreatic cancer MDT.' },
      { id: 'breaking-news', why: 'He has asked for honesty — explain sensitively, with his wife present if he wishes, and involve a specialist nurse.' },
      { id: 'whipple', why: '!If staging confirms resectable disease and he is fit: pancreaticoduodenectomy (Whipple’s), usually with adjuvant chemotherapy.' },
    ],
    helpful: [
      { id: 'vitamin-k', why: 'Correct the raised INR.' },
      { id: 'glucose-monitoring', why: 'Diabetes (type 3c).' },
      { id: 'nutrition', why: 'Dietitian review; pancreatic enzyme replacement (Creon) for steatorrhoea.' },
      { id: 'senior', why: 'Consultant-led care.' },
    ],
    avoid: [
      { id: 'lap-chole-early', why: 'There is no cholecystitis or gallstone disease.' },
      { id: 'ercp', why: 'Stone extraction is irrelevant — and NICE advises against routine pre-operative biliary drainage in people fit for surgery (unless cholangitis or delay).' },
      { id: 'discharge', why: 'He needs an urgent cancer pathway, not reassurance.' },
    ],
  },
  viva: [
    {
      id: 'courvoisier',
      q: 'State Courvoisier’s law.',
      options: [
        'In a jaundiced patient, a palpable non-tender gallbladder is unlikely to be due to gallstones',
        'A tender gallbladder with jaundice indicates cancer',
        'Gallstones always cause a palpable gallbladder',
        'Jaundice with fever indicates cholangitis',
      ],
      correct: 0,
      answer: 'In the presence of jaundice, a palpable (non-tender) gallbladder is unlikely to be due to stones — chronic gallstone disease leaves a fibrosed gallbladder that cannot distend. It suggests distal obstruction from a pancreatic head or periampullary tumour. (Exceptions exist, e.g. a stone in the CBD with a separate one in Hartmann’s pouch.)',
      topic: 'Signs',
    },
    {
      id: 'features',
      q: 'Which features of his history are red flags for pancreatic cancer?',
      answer: 'Painless progressive obstructive jaundice with pruritus, weight loss and anorexia, steatorrhoea, back pain, new-onset diabetes in an older adult, smoking, and a family history (first-degree relative). NICE: refer urgently for over-40s with jaundice.',
      topic: 'Recognition',
    },
    {
      id: 'whipple',
      q: 'What does a Whipple’s procedure involve?',
      answer: 'Pancreaticoduodenectomy: removal of the pancreatic head, duodenum, distal bile duct and gallbladder (± distal stomach), then reconstruction with pancreaticojejunostomy, hepaticojejunostomy and gastro/duodenojejunostomy. Only ~15–20% of patients are resectable at diagnosis.',
      topic: 'Surgery',
    },
    {
      id: 'inr',
      q: 'Why is his INR raised?',
      options: ['Vitamin K malabsorption from absent bile salts', 'Liver metastases', 'Warfarin', 'Disseminated intravascular coagulation'],
      correct: 0,
      answer: 'Bile salts are needed to absorb fat-soluble vitamins (A, D, E, K). Without them, vitamin K-dependent factors (II, VII, IX, X) fall. It corrects with IV vitamin K — unlike coagulopathy from liver failure.',
      topic: 'Physiology',
    },
    {
      id: 'trousseau',
      q: 'What is Trousseau’s sign of malignancy?',
      answer: 'Migratory superficial thrombophlebitis associated with occult malignancy, classically pancreatic adenocarcinoma (hypercoagulability). Not to be confused with Trousseau’s sign of hypocalcaemia (carpal spasm with a BP cuff).',
      topic: 'Signs',
    },
  ],
  teaching: {
    summary:
      'Carcinoma of the head of the pancreas: painless, progressive obstructive jaundice with pruritus, pale stools, dark urine, weight loss and new-onset diabetes in an ex-smoker, with a palpable non-tender gallbladder (Courvoisier) and a “double duct sign” on CT.',
    keyFindings: [
      'Painless progressive jaundice for 3 weeks with pruritus and scratch marks',
      'Dark urine, pale floating stools (steatorrhoea)',
      '8 kg weight loss; new-onset diabetes; 40 pack-year smoking history; brother had pancreatic cancer',
      'Palpable, smooth, non-tender gallbladder — Courvoisier’s sign',
      'INR 1.5, CA 19-9 1840, CT: 3.2 cm pancreatic head mass with double duct sign',
    ],
    pearls: [
      'Painless jaundice in an older adult is cancer until proven otherwise.',
      'Palpate for the gallbladder at the tip of the right 9th costal cartilage in every jaundiced patient.',
      'Feel for Virchow’s node and look for ascites — signs of inoperability.',
      'Check and correct the INR; always ask about new diabetes and weight loss.',
    ],
    presentation:
      'Mr Hassan is a 68-year-old ex-smoker with three weeks of painless progressive jaundice, pruritus, dark urine and pale floating stools, 8 kg of weight loss, and diabetes diagnosed two months ago; his brother died of pancreatic cancer. He is cachectic and deeply jaundiced with excoriations, and has a smooth, non-tender, palpable gallbladder; there is no hepatomegaly, ascites or Virchow’s node. Bloods show an obstructive picture (bilirubin 214, ALP 780), an INR of 1.5 and a CA 19-9 of 1840. Ultrasound shows a dilated biliary tree to the pancreatic head without gallstones, and pancreatic-protocol CT shows a 3.2 cm pancreatic head mass with a double duct sign and no metastases. The most likely diagnosis is pancreatic head adenocarcinoma, potentially resectable. I would correct his INR with vitamin K, refer urgently to the HPB MDT for staging and consideration of a Whipple’s procedure, and break the news honestly with specialist nurse support.',
    references: ['NICE NG85 Pancreatic cancer in adults (2018)', 'NICE NG12 Suspected cancer: recognition and referral', 'Macleod’s Clinical Examination, 14th ed. — Ch. 6: jaundice and the gallbladder'],
  },
}

export default c
