import type { CaseDef } from '../../engine/types'
import { CRP, FBC, lab, r, UE } from './helpers'

const c: CaseDef = {
  id: 'pancreatitis',
  title: 'Acute alcohol-related pancreatitis (Glasgow–Imrie score 2)',
  presenting: 'Epigastric pain radiating to the back',
  specialty: 'Hepatobiliary',
  exam: 'abdominal',
  difficulty: 2,
  setting: 'Emergency department',
  stem: 'Daniel Kowalski, 44, presents with severe upper abdominal pain and vomiting. Take a history, examine him, request investigations — including those needed to score severity — and plan his management.',
  components: ['history', 'exam', 'investigations', 'diagnosis', 'viva'],
  tags: ['epigastric pain', 'alcohol', 'Glasgow-Imrie', 'Atlanta'],
  patient: {
    name: 'Daniel Kowalski',
    title: 'Mr Kowalski',
    age: 44,
    sex: 'male',
    dob: '17/01/1982',
    occupation: 'a chef',
    appearance: {
      sex: 'male',
      age: 44,
      skinTone: 1,
      habitus: 'average',
      hair: 'crop',
      hairColor: 'blonde',
      eyeColor: 'blue',
      facialHair: 'stubble',
      flushed: 0.25,
      sweaty: true,
      spiderNaevi: 2,
      lines: { cannula: 'left-hand' },
    },
    persona: { mood: 'irritable', style: 'brief' },
  },
  vitals: { hr: 112, rhythm: 'regular', sbp: 118, dbp: 74, rr: 22, spo2: 94, temp: 37.9, avpu: 'A', pain: 8 },
  bedside: { vomitBowl: 'bilious' },
  history: {
    opening: { text: 'It’s this pain in the top of my stomach — it goes right through to my back. I’ve been throwing up all night.', cue: 'sits hunched forward, arms wrapped around his stomach' },
    answers: {
      'pain.site': { text: 'Up here in the middle, under my ribs.', cue: 'points to the epigastrium' },
      'pain.onset': 'Last night about eleven, after a heavy weekend. It built up over an hour and it’s been getting worse.',
      'pain.character': 'A deep, boring pain. Constant.',
      'pain.radiation': 'Straight through to my back, between my shoulder blades.',
      'pain.timing': 'Constant — it never goes.',
      'pain.exacerbating': 'Lying flat is the worst. Eating anything.',
      'pain.relieving': 'Sitting up and leaning forward helps a bit.',
      'pain.severity': 'Eight. Maybe nine.',
      'pain.previous': 'I’ve had a bit of tummy ache after a big night before, but nothing like this.',
      'gi.nausea': 'Yes.',
      'gi.vomiting': 'Maybe ten times. I can’t keep water down.',
      'gi.vomit_content': 'Yellow-green bile now. No blood.',
      'gi.bowels_last': 'Yesterday, normal.',
      'gi.jaundice': 'No.',
      'gi.stool_colour': 'No, normal.',
      'sys.fever': 'Hot and sweaty.',
      'sh.alcohol': 'Honestly? A bottle of vodka most days off, and beer on shift. Probably sixty units a week, more at weekends. Last drink was about ten last night.',
      'sh.smoking': 'Ten a day.',
      'sh.drugs': 'No.',
      'sh.living': 'On my own since the divorce.',
      'pmh.conditions': 'Nothing. I don’t go to doctors.',
      'pmh.gi': 'No gallstones that I know of.',
      'dh.meds': 'Nothing regular.',
      'fh.general': 'Nothing I know of.',
      'ros.chest_pain': 'No chest pain — it’s my stomach.',
      'pre.last_meal': 'A kebab at about nine last night. Nothing since — can’t keep it down.',
      'comm.questions': 'Can I get something for the sickness?',
    },
    key: [
      'comm.open',
      'pain.site',
      'pain.onset',
      'pain.character',
      'pain.radiation',
      'pain.relieving',
      'pain.severity',
      'gi.vomiting',
      'gi.jaundice',
      'sh.alcohol',
      'pmh.gi',
      'dh.meds',
      'dh.allergies',
      'sh.smoking',
      'ros.chest_pain',
    ],
    critical: ['sh.alcohol'],
    ideas: 'Probably something I ate. Or the drink, I suppose.',
    concerns: 'I can’t lose my job over this.',
    expectations: 'Something for the pain and the sickness, then home.',
    social: { alcohol: 'About 60 units a week.', smoking: 'Ten a day.' },
  },
  abdo: {
    general: {
      endOfBed:
        'Mr Kowalski is sitting up on the trolley, hunched forward and restless, looking sweaty and unwell. There is a bowl of bilious vomit beside him and a cannula in his left hand. He smells faintly of alcohol.',
      restless: true,
    },
    hands: { temperature: 'warm', tremor: true, crt: 2 },
    face: { mucosa: 'dry', tongue: 'dry-furred', fetor: 'alcohol' },
    abdomen: {
      movesWithRespiration: 'reduced',
      regions: {
        EPI: r(2, 3, 'voluntary', { percussionTender: true }),
        LUQ: r(1, 2, 'voluntary'),
        RUQ: r(1, 2),
        UMB: r(1, 1),
      },
      bowelSounds: 'reduced',
    },
    completion: { urinalysis: 'Ketones ++; glucose +.' },
  },
  investigations: {
    amylase: { values: [lab('Amylase', 1680, 'U/L', '30–110', 'HH'), lab('Lipase', 2410, 'U/L', '< 60', 'HH')], interpretation: 'More than 3× the upper limit — with typical pain this meets the Atlanta criteria for acute pancreatitis.' },
    fbc: { values: FBC(158, 16.8, 14.2, 182, 99), interpretation: 'WCC > 15 scores 1 on Glasgow–Imrie. High-normal MCV (alcohol).' },
    ue: { values: UE(136, 3.6, 9.2, 102, '78'), interpretation: 'Urea < 16 — no Glasgow point, but rising urea predicts severity.' },
    lft: {
      values: [lab('Bilirubin', 24, 'µmol/L', '< 21', 'H'), lab('ALT', 88, 'U/L', '< 40', 'H'), lab('AST', 142, 'U/L', '< 40', 'H'), lab('ALP', 140, 'U/L', '30–130', 'H'), lab('GGT', 420, 'U/L', '< 60', 'HH'), lab('Albumin', 34, 'g/L', '35–50', 'L'), lab('LDH', 540, 'U/L', '135–225', 'H')],
      interpretation: 'Very high GGT and AST > ALT suggest alcohol. AST < 200 and LDH < 600 → no Glasgow point. Albumin 34 (> 32) → no point.',
    },
    calcium: { values: [lab('Adjusted calcium', '2.02', 'mmol/L', '2.20–2.60', 'L'), lab('Phosphate', 0.9, 'mmol/L', '0.8–1.5')], interpretation: 'Low calcium (fat saponification) — but ≥ 2.0 so no Glasgow point.' },
    glucose: { values: [lab('Glucose (random)', 11.4, 'mmol/L', '4.0–7.8', 'H')], interpretation: 'Glucose > 10 scores 1 on Glasgow–Imrie.' },
    abg: {
      values: [lab('pH', '7.36', '', '7.35–7.45'), lab('pO₂', 8.9, 'kPa', '> 10', 'L'), lab('pCO₂', 4.4, 'kPa', '4.7–6.0', 'L'), lab('HCO₃⁻', 21, 'mmol/L', '22–26', 'L'), lab('Lactate', 1.8, 'mmol/L', '0.5–2.0')],
      interpretation: 'pO₂ 8.9 kPa — hypoxaemic but above 8 kPa, so no Glasgow point. Watch for ARDS.',
    },
    crp: { values: CRP(48), interpretation: 'CRP at 48 h (> 150 mg/L) is a better severity marker than at admission.' },
    'us-abdo': {
      report: 'No gallstones; normal gallbladder wall. CBD 4 mm. The pancreas is bulky and hypoechoic with a small amount of peripancreatic fluid. Liver shows increased echogenicity (fatty change).',
      interpretation: 'No gallstones — alcohol is the likely cause. Fatty liver.',
      abnormal: true,
    },
    lipids: { values: [lab('Triglycerides', 2.1, 'mmol/L', '< 1.7', 'H'), lab('Total cholesterol', 5.2, 'mmol/L', '< 5.0', 'H'), lab('HbA1c', 39, 'mmol/mol', '< 42')], interpretation: 'Triglycerides are not high enough (> 11) to cause pancreatitis.' },
    'ct-ap': {
      report: 'Diffusely oedematous pancreas with peripancreatic fat stranding and a small acute peripancreatic fluid collection. No necrosis (early scan).',
      interpretation: 'Interstitial oedematous pancreatitis. CT within the first 72 hours rarely changes management and underestimates necrosis.',
      abnormal: true,
    },
    ecg: { report: 'Sinus tachycardia 112. No ischaemic changes.', interpretation: 'No MI.' },
    'cxr-erect': { report: 'No free gas. Small left pleural effusion.', interpretation: 'No perforation; effusion is common in pancreatitis.', abnormal: true },
  },
  investigationRubric: {
    essential: [
      { id: 'amylase', why: 'Diagnosis: amylase/lipase > 3× the upper limit.' },
      { id: 'fbc', why: 'WCC for severity scoring.' },
      { id: 'ue', why: 'Urea for severity scoring and fluid status.' },
      { id: 'lft', why: 'LDH/AST and albumin for scoring; cholestasis suggests gallstones.' },
      { id: 'calcium', why: 'Calcium < 2.0 mmol/L scores on Glasgow–Imrie.' },
      { id: 'abg', why: 'pO₂ < 8 kPa scores on Glasgow–Imrie; assesses respiratory compromise.' },
      { id: 'us-abdo', why: 'Look for gallstones in every patient (determines ERCP/cholecystectomy).' },
    ],
    helpful: [
      { id: 'glucose', why: 'Glucose > 10 scores on Glasgow–Imrie.' },
      { id: 'crp', why: 'Repeat at 48 h: > 150 predicts severe disease.' },
      { id: 'lipids', why: 'Exclude hypertriglyceridaemia as a cause.' },
      { id: 'ecg', why: 'Exclude MI.' },
      { id: 'cxr-erect', why: 'Exclude perforation; look for effusion/ARDS.' },
    ],
    avoid: [{ id: 'ct-ap', why: 'CT is not needed in the first 72 hours when the diagnosis is clear — reserve it for diagnostic doubt or deterioration.' }],
  },
  diagnosis: {
    correct: 'pancreatitis',
    differentials: ['perforated-pu', 'mi', 'cholecystitis', 'aaa-rupture', 'mesenteric-ischaemia', 'dka'],
  },
  management: {
    essential: [
      { id: 'fluids', why: 'Goal-directed IV crystalloid — guided by HR, BP and urine output (avoid over-aggressive fluids).' },
      { id: 'analgesia', why: 'Severe pain — opioids are safe and appropriate.' },
      { id: 'o2', why: 'SpO₂ 94% with pO₂ 8.9 kPa.' },
      { id: 'catheter', why: 'Monitor urine output to guide fluids.' },
      { id: 'alcohol-support', why: 'Alcohol withdrawal prophylaxis (e.g. chlordiazepoxide) and IV Pabrinex (thiamine) to prevent Wernicke’s.' },
      { id: 'senior', why: 'Inform the registrar; reassess severity at 48 hours.' },
    ],
    helpful: [
      { id: 'antiemetic', why: 'Persistent vomiting.' },
      { id: 'nutrition', why: 'Early oral/enteral feeding as tolerated reduces complications — prolonged nil by mouth is unnecessary.' },
      { id: 'vte', why: 'VTE prophylaxis.' },
      { id: 'glucose-monitoring', why: 'Hyperglycaemia.' },
      { id: 'fluid-balance', why: 'Strict fluid balance.' },
    ],
    avoid: [
      { id: 'abx-iv', why: 'Prophylactic antibiotics are not recommended in acute pancreatitis — only for proven or strongly suspected infection.' },
      { id: 'laparotomy', why: 'Surgery has no role in early acute pancreatitis.' },
      { id: 'ercp', why: 'ERCP is for gallstone pancreatitis with cholangitis or persistent biliary obstruction — not alcohol-related disease.' },
      { id: 'discharge', why: 'He needs admission, fluids and monitoring.' },
    ],
  },
  viva: [
    {
      id: 'glasgow',
      q: 'Calculate his modified Glasgow–Imrie score. What does it mean?',
      options: ['2 — not predicted severe, reassess at 48 h', '0 — mild', '4 — predicted severe, refer to ICU', '6 — predicted severe'],
      correct: 0,
      answer:
        'PANCREAS within 48 h: PaO₂ < 8 kPa (8.9 — no), Age > 55 (no), Neutrophils/WCC > 15 (yes), Calcium < 2.0 (2.02 — no), Renal: urea > 16 (no), Enzymes: LDH > 600 or AST > 200 (no), Albumin < 32 (no), Sugar: glucose > 10 (yes). Score 2. A score ≥ 3 predicts severe pancreatitis — re-score at 48 hours.',
      topic: 'Scores',
    },
    {
      id: 'atlanta',
      q: 'How is acute pancreatitis diagnosed (revised Atlanta 2012)?',
      answer:
        'Two of three: (1) typical upper abdominal pain (epigastric, radiating to the back), (2) serum amylase or lipase > 3× the upper limit of normal, (3) characteristic imaging findings (CT, MRI or US). Severity: mild (no organ failure or local complications), moderately severe (transient organ failure < 48 h or local complications), severe (persistent organ failure > 48 h).',
      topic: 'Classification',
    },
    {
      id: 'causes',
      q: 'List the causes of acute pancreatitis.',
      answer:
        '“I GET SMASHED”: Idiopathic, Gallstones, Ethanol, Trauma, Steroids, Mumps (and other viruses), Autoimmune, Scorpion venom, Hypertriglyceridaemia/Hypercalcaemia/Hypothermia, ERCP, Drugs (e.g. azathioprine, thiazides, valproate). Gallstones and alcohol account for ~80%.',
      topic: 'Aetiology',
    },
    {
      id: 'calcium',
      q: 'Why is his calcium low?',
      answer: 'Released lipases cause fat necrosis; the fatty acids bind calcium (saponification). Low albumin also lowers total calcium, so use the adjusted value.',
      topic: 'Physiology',
    },
    {
      id: 'complications',
      q: 'What are the local and systemic complications?',
      answer:
        'Local: acute peripancreatic fluid collection, pseudocyst (> 4 weeks), acute necrotic collection → walled-off necrosis, infected necrosis, haemorrhage/pseudoaneurysm, splenic/portal vein thrombosis. Systemic: SIRS, ARDS, AKI, shock, DIC, hypocalcaemia, hyperglycaemia, multi-organ failure. Later: chronic pancreatitis, diabetes.',
      topic: 'Complications',
    },
    {
      id: 'antibiotics',
      q: 'Should he receive prophylactic antibiotics?',
      options: ['No — only for proven or suspected infection', 'Yes — always', 'Yes — if amylase > 1000', 'Yes — if he drinks alcohol'],
      correct: 0,
      answer: 'No. Trials show no benefit of prophylactic antibiotics; they are used for infected necrosis or another confirmed infection (e.g. cholangitis, pneumonia).',
      topic: 'Management',
    },
  ],
  teaching: {
    summary:
      'Acute alcohol-related pancreatitis: constant epigastric pain boring through to the back, relieved by leaning forward, profuse vomiting, a markedly raised amylase and lipase, and no gallstones on ultrasound. Glasgow–Imrie score 2 at presentation.',
    keyFindings: [
      'Pain radiating to the back, better sitting forward',
      'Heavy alcohol use (≈ 60 units/week); no gallstones on US',
      'Amylase 1680, lipase 2410 (> 3× ULN)',
      'WCC 16.8 and glucose 11.4 — two Glasgow–Imrie points',
      'Tachycardic, SpO₂ 94%, pO₂ 8.9 kPa, small left effusion',
    ],
    pearls: [
      'The Glasgow score uses the worst values within 48 hours — score again.',
      'Signs may seem mild compared with the pain; Cullen’s and Grey Turner’s signs are late and rare.',
      'Ultrasound for gallstones in every patient — it changes management.',
      'No prophylactic antibiotics; start early enteral nutrition.',
      'Think Wernicke’s: give thiamine before glucose in heavy drinkers.',
    ],
    presentation:
      'Mr Kowalski is a 44-year-old chef with 12 hours of severe constant epigastric pain radiating to his back, relieved by leaning forward, with profuse bilious vomiting after a weekend of heavy drinking; he drinks about 60 units a week. He is tachycardic at 112, mildly febrile and has saturations of 94% on air. There is epigastric tenderness with voluntary guarding and reduced bowel sounds; no Cullen’s or Grey Turner’s signs. Amylase is 1680 and lipase 2410. His Glasgow–Imrie score is 2 (WCC 16.8, glucose 11.4) with a calcium of 2.02 and pO₂ of 8.9 kPa. Ultrasound shows no gallstones. This is acute alcohol-related pancreatitis, currently not predicted to be severe. I would give goal-directed IV fluids with a catheter to monitor urine output, oxygen, opioid analgesia and antiemetics, start alcohol-withdrawal prophylaxis and IV Pabrinex, begin early enteral feeding as tolerated, avoid prophylactic antibiotics, and repeat the severity score and CRP at 48 hours.',
    references: [
      'Banks PA, et al. Revised Atlanta classification of acute pancreatitis (2012)',
      'NICE NG104 Pancreatitis (2018)',
      'Macleod’s Clinical Examination, 14th ed. — Ch. 6: the acute abdomen',
    ],
  },
}

export default c
