import type { CaseDef, RegionFinding } from '../../engine/types'
import { CRP, FBC, lab, LFT, r, UE, VBG } from './helpers'

const peritonitis = (light: 2 | 3, deep: 2 | 3): RegionFinding => r(light, deep, 'involuntary', { percussionTender: true, rebound: true })

const c: CaseDef = {
  id: 'perforated-du',
  title: 'Perforated duodenal ulcer with generalised peritonitis',
  presenting: 'Sudden severe epigastric pain',
  specialty: 'Upper GI',
  exam: 'abdominal',
  difficulty: 2,
  setting: 'Emergency department',
  stem: 'Marcus Reid, 52, has been brought to resus with sudden-onset abdominal pain. Assess him, examine his abdomen, request investigations and start management.',
  components: ['history', 'exam', 'investigations', 'diagnosis', 'viva'],
  tags: ['acute abdomen', 'peritonitis', 'NSAIDs', 'free gas'],
  patient: {
    name: 'Marcus Reid',
    title: 'Mr Reid',
    age: 52,
    sex: 'male',
    dob: '09/08/1974',
    occupation: 'a builder',
    appearance: {
      sex: 'male',
      age: 52,
      skinTone: 5,
      habitus: 'average',
      hair: 'receding',
      hairColor: 'black',
      eyeColor: 'brown',
      facialHair: 'stubble',
      sweaty: true,
      pallor: 0.25,
      lines: { cannula: 'right-hand', oxygen: 'mask' },
    },
    persona: { mood: 'distressed', style: 'brief' },
  },
  vitals: { hr: 118, rhythm: 'regular', sbp: 108, dbp: 68, rr: 26, spo2: 96, o2: '4 L/min via mask', temp: 37.8, avpu: 'A', pain: 9 },
  history: {
    opening: { text: 'The pain hit me like a knife about four hours ago… worst pain I’ve ever had. Now it’s everywhere.', cue: 'lies rigidly still, speaking in short breaths' },
    answers: {
      'pain.site': { text: 'It started up here… now it’s all over.', cue: 'points to his epigastrium, then sweeps a hand across the whole abdomen' },
      'pain.onset': 'Suddenly. I was lifting a bag of cement and it just hit me. About four hours ago.',
      'pain.character': 'Sharp. Burning. Constant.',
      'pain.radiation': 'Up into the top of my right shoulder.',
      'pain.moved': 'It started at the top of my stomach and spread everywhere.',
      'pain.timing': 'Constant. It never lets up.',
      'pain.exacerbating': 'Any movement… even breathing. The ambulance ride was agony.',
      'pain.relieving': 'Keeping dead still.',
      'pain.severity': 'Ten. The worst of my life.',
      'pain.previous': 'Never like this. I’ve had indigestion for months though.',
      'gi.reflux': 'Burning in the top of my stomach for months. Worse at night — eating sometimes helped. I’ve been living on Gaviscon.',
      'gi.nausea': 'Yes.',
      'gi.vomiting': 'Once, in the ambulance.',
      'gi.vomit_content': 'Just liquid. No blood.',
      'gi.melaena': 'No.',
      'gi.bowels_last': 'This morning. Normal.',
      'gi.appetite': 'Fine until today.',
      'sys.fever': 'Just sweating.',
      'dh.meds': 'Nothing from the doctor. Ibuprofen and naproxen most days for my back — whatever’s in the van.',
      'dh.nsaids': 'Yes… every day for months. My back’s shot from work.',
      'dh.steroids': 'No.',
      'dh.anticoag': 'No.',
      'pmh.conditions': 'Bad back. I never see the doctor.',
      'pmh.gi': 'Just the indigestion. Never been checked.',
      'sh.smoking': 'Twenty a day since I was fifteen.',
      'sh.alcohol': 'A few pints most nights — thirty units a week, maybe more.',
      'sh.living': 'With my wife.',
      'pre.last_meal': 'A bacon roll at about seven this morning. A cup of tea at ten.',
      'fh.general': 'My dad died of a heart attack at fifty-five.',
      'comm.questions': 'Am I going to be alright?',
    },
    key: [
      'comm.open',
      'pain.site',
      'pain.onset',
      'pain.character',
      'pain.radiation',
      'pain.severity',
      'pain.exacerbating',
      'gi.reflux',
      'gi.vomiting',
      'gi.melaena',
      'dh.nsaids',
      'dh.meds',
      'dh.steroids',
      'dh.allergies',
      'sh.smoking',
      'sh.alcohol',
      'pre.last_meal',
    ],
    critical: ['dh.nsaids'],
    ideas: 'I thought I’d pulled something lifting at first.',
    concerns: 'Am I going to die? My dad dropped dead at fifty-five.',
    expectations: 'Please just make the pain stop.',
    social: { smoking: 'Twenty a day for 37 years.', alcohol: 'About thirty units a week.' },
  },
  abdo: {
    general: {
      endOfBed:
        'Mr Reid is lying absolutely still on the trolley, grey and sweaty, taking rapid shallow breaths through an oxygen mask. He winces at the slightest movement of the trolley and keeps his knees drawn up. There is a cannula in his right hand.',
      lyingStill: true,
    },
    hands: { temperature: 'cool', crt: 2.5 },
    face: { mucosa: 'dry' },
    abdomen: {
      movesWithRespiration: 'absent',
      coughPain: true,
      rigidity: 'generalised',
      regions: {
        EPI: peritonitis(3, 3),
        RUQ: peritonitis(3, 3),
        LUQ: peritonitis(2, 3),
        RF: peritonitis(2, 3),
        UMB: peritonitis(2, 3),
        LF: peritonitis(2, 3),
        RIF: peritonitis(2, 3),
        SP: peritonitis(2, 2),
        LIF: peritonitis(2, 2),
      },
      liver: { edgeCm: 0, spanCm: 4 },
      bowelSounds: 'absent',
    },
    completion: { dre: 'Tender generally; no masses; brown stool, no melaena.' },
  },
  criticalSteps: ['gen.obs', 'palp.peritonism'],
  investigations: {
    'cxr-erect': {
      report: 'Crescent of free gas beneath the right hemidiaphragm (pneumoperitoneum). Lungs clear.',
      interpretation: 'Free intraperitoneal gas — a perforated viscus until proven otherwise.',
      image: 'cxr-free-gas',
      abnormal: true,
    },
    fbc: { values: FBC(142, 16.4, 14.1, 260), interpretation: 'Neutrophilia.' },
    ue: { values: UE(139, 4.4, 8.8, 118, '62'), interpretation: 'Early pre-renal AKI.' },
    crp: { values: CRP(38), interpretation: 'CRP lags behind — it may still be low within hours of perforation.' },
    amylase: {
      values: [lab('Amylase', 260, 'U/L', '30–110', 'H'), lab('Lipase', 72, 'U/L', '< 60', 'H')],
      interpretation: 'Mildly raised (< 3× ULN) — common after perforation. Do not misdiagnose pancreatitis.',
    },
    vbg: { values: VBG(7.31, 19, -5.1, 3.4, 4.4, 8.1), interpretation: 'Metabolic acidosis with raised lactate — sepsis/hypoperfusion.' },
    lft: { values: LFT(14, 28, 92, 51, 38) },
    ecg: { report: 'Sinus tachycardia 118 bpm. No ST-segment changes.', interpretation: 'No evidence of MI (an important mimic).' },
    troponin: { values: [lab('hs-Troponin T', 9, 'ng/L', '< 14')] },
    'ct-ap': {
      report: 'Moderate pneumoperitoneum with free fluid in the upper abdomen and pelvis. Focal wall defect in the anterior first part of the duodenum with surrounding inflammatory stranding.',
      interpretation: 'Perforated duodenal ulcer.',
      abnormal: true,
    },
    gs: { report: 'Group B RhD positive. Antibody screen negative.' },
    coag: { values: [lab('INR', 1.1, '', '0.8–1.2'), lab('APTT', 31, 's', '25–35')] },
    cultures: { report: 'Sent. Awaiting growth.' },
  },
  investigationRubric: {
    essential: [
      { id: 'cxr-erect', why: 'Free gas under the diaphragm confirms perforation (sit the patient up for 10–15 minutes first).' },
      { id: 'fbc', why: 'Baseline; leucocytosis.' },
      { id: 'ue', why: 'AKI from sepsis and third-space losses.' },
      { id: 'amylase', why: 'Pancreatitis is the main differential — but amylase can rise modestly with perforation.' },
      { id: 'vbg', why: 'Lactate and acid–base status guide resuscitation.' },
      { id: 'gs', why: 'Emergency theatre.' },
    ],
    helpful: [
      { id: 'ct-ap', why: 'More sensitive than CXR; defines the site when the diagnosis is uncertain.' },
      { id: 'ecg', why: 'Exclude an MI presenting as epigastric pain.' },
      { id: 'troponin', why: 'Exclude MI.' },
      { id: 'crp', why: 'Baseline.' },
      { id: 'coag', why: 'Pre-operative.' },
      { id: 'cultures', why: 'Sepsis.' },
    ],
  },
  diagnosis: {
    correct: 'perforated-pu',
    differentials: ['pancreatitis', 'mi', 'aaa-rupture', 'mesenteric-ischaemia', 'perforated-diverticulitis', 'boerhaave'],
  },
  management: {
    essential: [
      { id: 'abcde', why: 'He is peritonitic and shocked — ABCDE first.' },
      { id: 'o2', why: 'Tachypnoeic — oxygen to target saturations.' },
      { id: 'fluids', why: 'Resuscitate: tachycardic, oliguric, raised lactate.' },
      { id: 'analgesia', why: 'Severe pain — IV opioid titrated.' },
      { id: 'nbm', why: 'Nil by mouth.' },
      { id: 'ng', why: 'Decompress the stomach to reduce ongoing contamination.' },
      { id: 'catheter', why: 'Monitor urine output.' },
      { id: 'ppi-iv', why: 'IV proton pump inhibitor.' },
      { id: 'abx-iv', why: 'Broad-spectrum IV antibiotics for peritonitis.' },
      { id: 'senior', why: 'Immediate senior review.' },
      { id: 'perforation-repair', why: '!Definitive treatment: laparoscopic or open repair with an omental patch and peritoneal lavage.' },
      { id: 'theatre', why: 'Emergency theatre.' },
    ],
    helpful: [
      { id: 'sepsis6', why: 'Meets sepsis criteria.' },
      { id: 'iv-access', why: 'Two large-bore cannulae.' },
      { id: 'icu', why: 'High-risk emergency laparotomy — post-operative critical care.' },
      { id: 'consent', why: 'Consent for laparotomy/laparoscopy.' },
      { id: 'fluid-balance', why: 'Strict fluid balance.' },
      { id: 'antiemetic', why: 'Nausea.' },
      { id: 'vte', why: 'VTE prophylaxis post-operatively.' },
    ],
    avoid: [
      { id: 'nsaid', why: 'NSAIDs caused this ulcer — stop them all.' },
      { id: 'discharge', why: 'Generalised peritonitis is a surgical emergency.' },
      { id: 'diet-normal', why: 'Nil by mouth.' },
      { id: 'laxatives', why: 'No role.' },
    ],
  },
  viva: [
    {
      id: 'free-gas',
      q: 'On an erect chest X-ray, where does free intraperitoneal gas collect?',
      options: ['Beneath the hemidiaphragms', 'At the lung apices', 'Behind the heart', 'In the pelvis'],
      correct: 0,
      answer: 'Under the diaphragm — most easily seen on the right, above the liver (on the left the gastric bubble can confuse). Sit the patient upright for 10–15 minutes first; up to a quarter of perforations show no free gas, so CT is used if doubt remains.',
      topic: 'Imaging',
    },
    {
      id: 'shoulder',
      q: 'Why does he feel pain at the tip of his right shoulder?',
      answer: 'Air and gastric contents irritate the peritoneum on the undersurface of the diaphragm, supplied by the phrenic nerve (C3–5). Pain is referred to the C4 dermatome over the shoulder tip (Kehr’s sign).',
      topic: 'Physiology',
    },
    {
      id: 'rigidity',
      q: 'What does board-like rigidity of the abdomen signify?',
      answer: 'Involuntary, sustained contraction of the abdominal wall muscles from diffuse irritation of the parietal peritoneum — generalised peritonitis (here a chemical peritonitis from gastric/duodenal contents, becoming bacterial with time).',
      topic: 'Signs',
    },
    {
      id: 'amylase',
      q: 'Serum amylase after a perforated duodenal ulcer is typically…',
      options: ['Often mildly raised (usually < 3× the upper limit)', 'Always normal', 'Always > 3× the upper limit', 'Only raised if the ulcer is gastric'],
      correct: 0,
      answer: 'Amylase leaks from the duodenum into the peritoneal cavity and is absorbed, so it is often mildly raised. A level > 3× ULN with a compatible picture supports pancreatitis — but imaging settles doubt.',
      topic: 'Interpretation',
    },
    {
      id: 'boey',
      q: 'Which score predicts mortality in perforated peptic ulcer?',
      options: ['Boey score', 'Glasgow–Imrie score', 'Alvarado score', 'Rockall score'],
      correct: 0,
      answer: 'The Boey score: shock on admission, delay to surgery > 24 h, and major medical comorbidity (one point each). The PULP score is an alternative. Rockall is for upper GI bleeding; Glasgow–Imrie for pancreatitis.',
      topic: 'Scores',
    },
    {
      id: 'recurrence',
      q: 'After repair, how would you prevent recurrence?',
      answer: 'Stop NSAIDs (or add PPI cover if essential), test for and eradicate Helicobacter pylori, continue a PPI, support smoking cessation and alcohol reduction. For gastric ulcers, repeat OGD with biopsies at 6–8 weeks to exclude malignancy.',
      topic: 'Management',
    },
  ],
  teaching: {
    summary:
      'Perforated duodenal ulcer in a smoker taking daily NSAIDs: sudden “knife-like” epigastric pain becoming generalised, shoulder-tip pain, a patient lying rigidly still with a board-like, silent abdomen, and free gas under the diaphragm.',
    keyFindings: [
      'Sudden severe epigastric pain → generalised; right shoulder-tip pain',
      'Months of dyspepsia, daily ibuprofen/naproxen, 20 cigarettes a day, heavy alcohol',
      'Tachycardia 118, tachypnoea, lactate 3.4 — early septic shock',
      'Lying still, generalised rigidity, percussion tenderness, absent bowel sounds',
      'Erect CXR: free gas under the right hemidiaphragm',
    ],
    pearls: [
      'Patients with peritonitis lie still; patients with colic writhe.',
      'Ask every patient with upper abdominal pain about NSAIDs, aspirin and steroids.',
      'Loss of liver dullness on percussion can hint at free gas.',
      'A mildly raised amylase does not make it pancreatitis.',
      'Resuscitate in parallel with diagnosis — do not delay theatre for non-essential imaging.',
    ],
    presentation:
      'Mr Reid is a 52-year-old builder who presented four hours after the sudden onset of severe epigastric pain that has become generalised, with right shoulder-tip radiation and one vomit. He has months of dyspepsia, takes ibuprofen and naproxen daily for back pain, smokes 20 a day and drinks about 30 units a week. He is tachycardic at 118, tachypnoeic at 26 and mildly febrile, with a lactate of 3.4. He is lying still with a rigid, board-like abdomen, generalised percussion tenderness and absent bowel sounds. An erect chest X-ray shows free gas under the right hemidiaphragm, and CT confirms a perforated anterior duodenal ulcer. I would resuscitate him with oxygen, IV fluids and analgesia, keep him nil by mouth with an NG tube and catheter, start IV PPI and broad-spectrum antibiotics, and arrange emergency laparoscopic or open repair with an omental patch, followed by H. pylori eradication and stopping NSAIDs.',
    references: [
      'Macleod’s Clinical Examination, 14th ed. — Ch. 6: the acute abdomen and peritonism',
      'WSES guidelines on perforated and bleeding peptic ulcer (2020)',
    ],
  },
}

export default c
