import type { CaseDef } from '../../engine/types'
import { CRP, FBC, lab, UE } from './helpers'

const c: CaseDef = {
  id: 'perianal-abscess',
  title: 'Perianal abscess (with undiagnosed diabetes)',
  presenting: 'Throbbing pain and swelling beside the anus',
  specialty: 'Colorectal',
  exam: 'perianal',
  difficulty: 1,
  setting: 'Surgical assessment unit',
  stem: 'Surgical assessment unit. Jamal Rahman, 33, has a painful swelling near his back passage. Take a history, examine the perianal area with a chaperone, investigate and plan management.',
  components: ['history', 'exam', 'investigations', 'diagnosis', 'viva'],
  tags: ['perianal', 'abscess', 'sepsis', 'diabetes'],
  patient: {
    name: 'Jamal Rahman',
    title: 'Mr Rahman',
    age: 33,
    sex: 'male',
    dob: '15/03/1993',
    occupation: 'a taxi driver',
    appearance: { sex: 'male', age: 33, skinTone: 4, habitus: 'overweight', hair: 'short', hairColor: 'black', eyeColor: 'brown', facialHair: 'beard', flushed: 0.2 },
    persona: { mood: 'irritable', style: 'normal' },
  },
  vitals: { hr: 98, rhythm: 'regular', sbp: 132, dbp: 82, rr: 16, spo2: 98, temp: 38.1, avpu: 'A', pain: 8, bm: 15.8 },
  visual: { perianal: { kind: 'abscess', clock: 7, distCm: 2.5, sizeCm: 3 } },
  history: {
    opening: { text: 'I’ve got a really painful lump next to my bottom. I can’t sit down — I had to stop working.', cue: 'perches on one buttock' },
    answers: {
      'pain.site': 'Just to the left of my back passage, towards the back.',
      'pain.onset': 'Started three days ago and getting worse every day.',
      'pain.character': 'Throbbing. Constant.',
      'pain.timing': 'All the time — it kept me awake.',
      'pain.severity': 'Eight.',
      'pain.exacerbating': 'Sitting, walking, going to the toilet.',
      'ano.pain': 'Going to the toilet hurts because it presses on the lump, but the pain is there all the time anyway.',
      'ano.lump': 'Yes — hot, hard and swollen.',
      'ano.discharge': 'No pus has come out yet.',
      'ano.blood_type': 'No bleeding.',
      'ano.continence': 'No problems.',
      'sys.fever': 'Hot and sweaty last night.',
      'sys.rigors': 'No.',
      'gi.bowel_change': 'No change. No diarrhoea.',
      'gi.weight': 'I’ve lost a bit of weight without trying. I’ve been really thirsty and up in the night to wee.',
      'gu.frequency': 'Yes, up three or four times a night lately.',
      'pmh.conditions': 'Nothing — I never see the doctor.',
      'pmh.surgery': 'None.',
      'pmh.diabetes': 'Not that I know of. My mum and dad both have diabetes.',
      'pmh.gi': 'No bowel problems, no Crohn’s.',
      'dh.meds': 'Ibuprofen from the shop.',
      'dh.allergies': 'None.',
      'sh.smoking': 'Ten a day.',
      'sh.alcohol': 'No.',
      'sh.occupation': 'Taxi driver — I sit all day.',
      'comm.questions': 'Can you just give me antibiotics so I can get back to work?',
    },
    key: ['comm.open', 'pain.site', 'pain.onset', 'pain.character', 'pain.severity', 'ano.pain', 'ano.discharge', 'ano.blood_type', 'sys.fever', 'gi.bowel_change', 'gi.weight', 'pmh.diabetes', 'pmh.gi', 'dh.allergies'],
    critical: ['pmh.diabetes', 'pmh.gi'],
    ideas: 'An infected boil, maybe.',
    concerns: 'Missing work — I’m self-employed.',
    expectations: 'Antibiotics and home today.',
    social: { smoking: '10 a day.', alcohol: 'None.' },
    fh: 'Both parents have type 2 diabetes.',
  },
  keyed: {
    'comm.pain': { text: '', says: 'Yes — the lump on the left side is agony. Please be gentle.' },
    'pr.inspect': {
      text: 'At 7 o’clock (left posterior), 2.5 cm from the anal verge: a 3 cm red, shiny, swollen dome. The rest of the perianal skin is normal; no external openings, fissure or haemorrhoids.',
      abnormal: true,
      meaning: 'A perianal abscess — note its clock position and distance from the verge.',
    },
    'pr.strain': { text: 'Nothing prolapses; straining hurts.' },
    'pr.palpate': {
      text: 'Hot, exquisitely tender and fluctuant centrally, with surrounding induration. He gasps as you touch it.',
      abnormal: true,
      reaction: 0.9,
      says: 'Ow — that’s it, that’s the spot!',
      meaning: 'Fluctuance means pus that needs draining — antibiotics alone will not do.',
    },
    'pr.lubricate': { text: 'You lubricate your finger and warn him.' },
    'pr.insert': { text: 'You insert your finger very gently away from the abscess; he tolerates it with difficulty.', reaction: 0.6 },
    'pr.tone': { text: 'Normal tone and squeeze.' },
    'pr.sweep': { text: 'Tender, boggy swelling in the left posterior wall low in the anal canal; no internal mass; rectum otherwise normal.', abnormal: true, reaction: 0.7, meaning: 'No supralevator extension felt.' },
    'pr.anterior': { text: 'Normal prostate.' },
    'pr.glove': { text: 'Brown stool; no blood or pus.' },
    'pr.proctoscope': { text: 'He cannot tolerate the proctoscope — you stop. It will be done under anaesthesia.', reaction: 0.9, meaning: 'Proctoscopy is not needed acutely; the anal canal is examined at EUA.' },
    'pr.nodes': { text: 'Small tender left inguinal nodes (reactive).', abnormal: true },
  },
  investigations: {
    bm: { values: [lab('Capillary glucose', '15.8', 'mmol/L', '4.0–7.8', 'H')], interpretation: 'Hyperglycaemia — likely undiagnosed diabetes; check ketones.', abnormal: true },
    lipids: { values: [lab('HbA1c', '74', 'mmol/mol', '< 42', 'H')], interpretation: 'Diabetes (HbA1c ≥ 48).', abnormal: true },
    fbc: { values: FBC(148, 15.2, 12.8, 320), interpretation: 'Neutrophilia.' },
    crp: { values: CRP(142) },
    ue: { values: UE(136, 4.4, 5.2, 78, '> 90') },
    'urine-dip': { report: 'Glucose +++, ketones trace.', interpretation: 'Glycosuria.' },
    'mri-pelvis': { report: 'A 3 cm left posterior ischioanal collection with no supralevator or horseshoe extension; no fistula track identified.', interpretation: 'Simple perianal/ischioanal abscess.' },
    cultures: { report: 'Sent — later no growth.' },
  },
  investigationRubric: {
    essential: [
      { id: 'bm', why: 'Diabetes is a common underlying cause — and he has osmotic symptoms.' },
      { id: 'fbc', why: 'Infection.' },
      { id: 'crp', why: 'Infection.' },
    ],
    helpful: [
      { id: 'lipids', why: 'HbA1c confirms diabetes.' },
      { id: 'urine-dip', why: 'Glycosuria, ketones.' },
      { id: 'ue', why: 'Baseline before anaesthesia.' },
      { id: 'mri-pelvis', why: 'Only for recurrent or complex abscesses, or suspected Crohn’s.' },
    ],
    avoid: [{ id: 'colonoscopy', why: 'Not indicated unless Crohn’s is suspected.' }],
  },
  diagnosis: {
    correct: 'perianal-abscess',
    differentials: ['pilonidal', 'fistula', 'thrombosed-piles', 'perianal-haematoma', 'crohns'],
  },
  management: {
    essential: [
      { id: 'eua-drainage', why: '!Incision and drainage under general anaesthesia (EUA) on the next emergency list; look for a fistula but do not lay one open if unsure.' },
      { id: 'analgesia', why: 'Severe pain.' },
      { id: 'consent', why: 'EUA and drainage; explain the risk of a fistula later.' },
      { id: 'glucose-monitoring', why: 'Hyperglycaemia — treat and arrange diabetes follow-up.' },
    ],
    helpful: [
      { id: 'nbm', why: 'Fasting before theatre.' },
      { id: 'abx-iv', why: 'Only if spreading cellulitis, systemic sepsis, diabetes or immunosuppression — not instead of drainage.' },
      { id: 'smoking-cessation', why: 'Smoking is a risk factor.' },
    ],
    avoid: [
      { id: 'abx-oral', why: 'Antibiotics alone do not treat a fluctuant abscess — it needs draining.' },
      { id: 'discharge', why: 'Needs drainage first.' },
    ],
  },
  viva: [
    {
      id: 'types',
      q: 'Classify anorectal abscesses.',
      answer: 'By space: perianal (commonest), ischioanal (ischiorectal), intersphincteric and supralevator; a horseshoe abscess tracks around posteriorly. Most arise from infected anal glands at the dentate line (cryptoglandular theory).',
      topic: 'Anatomy',
    },
    {
      id: 'fistula',
      q: 'What proportion of patients develop a fistula after an abscess, and what does Goodsall’s rule say?',
      answer: 'About a third. Goodsall’s rule: with the patient in lithotomy, an external opening posterior to a transverse line through the anus usually tracks curvilinearly to the posterior midline (6 o’clock); an anterior opening runs straight radially to the nearest crypt (exception: anterior openings > 3 cm from the verge may curve posteriorly).',
      topic: 'Fistula',
    },
    {
      id: 'when',
      q: 'Which underlying conditions should you consider in perianal sepsis?',
      options: ['Diabetes, Crohn’s disease, immunosuppression and HIV', 'Hyperthyroidism', 'Gallstones', 'Varicose veins'],
      correct: 0,
      answer: 'Diabetes, Crohn’s disease (recurrent or complex sepsis), immunosuppression, HIV and malignancy. Always check the glucose.',
      topic: 'Associations',
    },
    {
      id: 'dre',
      q: 'How do you position a patient for a rectal examination?',
      answer: 'Left lateral position with the buttocks at the edge of the couch, knees drawn up to the chest and heels clear of the perineum; explain, gain consent and offer a chaperone first (Macleod’s, pp. 111–112).',
      topic: 'Examination',
    },
  ],
  teaching: {
    summary:
      'Perianal abscess in a 33-year-old with undiagnosed diabetes: three days of constant throbbing pain beside the anus, fever, a hot, tender, fluctuant swelling at 7 o’clock 2.5 cm from the verge, and a capillary glucose of 15.8; drained under anaesthesia.',
    keyFindings: [
      'Three days of constant, throbbing perianal pain, worse sitting; fever',
      'Thirst, nocturia and weight loss; both parents diabetic',
      'Red, hot, fluctuant 3 cm swelling at 7 o’clock, 2.5 cm from the verge',
      'Reactive left inguinal nodes',
      'Glucose 15.8, HbA1c 74; WCC 15.2, CRP 142',
    ],
    pearls: [
      'Pus needs draining — antibiotics alone fail.',
      'Always check the blood glucose in perianal sepsis.',
      'Describe findings by clock face (lithotomy) and distance from the anal verge.',
      'Recurrent or complex abscesses — think Crohn’s and get an MRI.',
    ],
    presentation:
      'Mr Rahman is a 33-year-old taxi driver with three days of constant, throbbing pain and swelling beside the anus, worse on sitting, with fever. He also reports thirst, nocturia and weight loss, and both parents have diabetes; there is no history of Crohn’s disease or change in bowel habit. He is febrile at 38.1 with a capillary glucose of 15.8. With a chaperone, in the left lateral position, there is a 3 centimetre red, hot, exquisitely tender and fluctuant swelling at 7 o’clock, 2.5 centimetres from the anal verge, with reactive inguinal nodes; DRE shows boggy tenderness in the left posterior canal and no mass. WCC is 15 and CRP 142, with an HbA1c of 74. This is a perianal abscess with newly diagnosed diabetes. I would arrange incision and drainage under general anaesthesia, manage his glucose and refer him to the diabetes team.',
    references: ['Macleod’s Clinical Examination, 14th ed. — Ch. 6: rectal examination (pp. 111–113)', 'ACPGBI position statement on the management of perianal abscess'],
  },
}

export default c
