import type { CaseDef } from '../../engine/types'
import { CRP, FBC, lab, UE } from './helpers'

const c: CaseDef = {
  id: 'perianal-abscess',
  title: 'Perianal abscess in a man with poorly controlled type 2 diabetes',
  presenting: 'Painful swelling beside the back passage',
  specialty: 'Colorectal',
  exam: 'abdominal',
  difficulty: 1,
  setting: 'Surgical assessment unit',
  stem: 'Surgical assessment unit. Liam Murphy, 41, has been sent in by his GP with a painful swelling beside his anus. Take a history, examine him (including the perianal region, with a chaperone), request investigations and start management.',
  components: ['history', 'exam', 'investigations', 'diagnosis', 'viva'],
  tags: ['perianal pain', 'abscess', 'diabetes', 'fistula-in-ano'],
  patient: {
    name: 'Liam Murphy',
    title: 'Mr Murphy',
    age: 41,
    sex: 'male',
    dob: '30/01/1985',
    occupation: 'a taxi driver',
    appearance: {
      sex: 'male',
      age: 41,
      skinTone: 4,
      habitus: 'obese',
      hair: 'crop',
      hairColor: 'black',
      eyeColor: 'brown',
      facialHair: 'beard',
      flushed: 0.3,
      sweaty: true,
      lines: { cannula: 'right-hand' },
    },
    persona: { mood: 'irritable', style: 'normal' },
  },
  vitals: { hr: 104, rhythm: 'regular', sbp: 138, dbp: 86, rr: 18, spo2: 98, temp: 38.2, avpu: 'A', pain: 8, bm: 16.4 },
  history: {
    opening: { text: 'I’ve got a really painful lump next to my backside, doc. It’s been getting worse for three days and I can’t sit down.', cue: 'stands beside the trolley rather than sitting, shifting his weight' },
    answers: {
      'pain.site': { text: 'Just to the side of my back passage — on the right, towards the back.', cue: 'gestures awkwardly behind him' },
      'pain.onset': 'Three days ago. A sore spot that’s got bigger and more painful every day.',
      'pain.character': 'Throbbing — like a really bad toothache.',
      'pain.radiation': 'No, it stays there.',
      'pain.timing': 'Constant. It kept me up all last night.',
      'pain.exacerbating': 'Sitting, walking, coughing — and going to the toilet is murder.',
      'pain.relieving': 'Nothing. Lying on my side helps a bit.',
      'pain.severity': 'Eight. Nine when I sit.',
      'pain.previous': 'Never had anything like it.',
      'pain.analgesia_taken': 'Paracetamol and ibuprofen. They barely touch it.',
      'ano.pain': 'It hurts to go — but it’s the lump that hurts, all the time, not just when I go.',
      'ano.lump': 'Yes, a hard, hot swelling. My wife had a look — she says it’s red and about the size of a golf ball.',
      'ano.discharge': 'Nothing’s come out of it yet.',
      'ano.itch': 'No.',
      'ano.continence': 'No problems, never.',
      'ano.blood_type': 'I haven’t seen any blood.',
      'gi.stool_blood': 'No blood.',
      'gi.bowels_last': 'Yesterday. I’ve been putting it off because of the pain.',
      'gi.bowel_change': 'No, normal for me — once a day.',
      'gi.diarrhoea': 'No.',
      'gi.mucus': 'No.',
      'gi.weight': 'No — if anything I’ve put weight on.',
      'sys.fever': 'Hot and sweaty since yesterday.',
      'sys.rigors': 'I had the shivers last night.',
      'gu.dysuria': 'No.',
      'gu.stream': 'I can pass water fine.',
      'pmh.conditions': 'Type 2 diabetes. I’m not great at taking the tablets, to be honest. Nothing else.',
      'pmh.diabetes': 'Yes, for about four years. Metformin. The GP said my last sugar test was too high and wanted to add something else.',
      'pmh.gi': 'No — no Crohn’s or colitis or anything like that.',
      'pmh.surgery': 'None.',
      'dh.meds': 'Metformin, when I remember.',
      'dh.steroids': 'No.',
      'dh.allergies': 'None.',
      'sh.occupation': 'I’m a taxi driver — twelve-hour shifts, sat down all day.',
      'sh.smoking': 'Ten a day.',
      'sh.alcohol': 'A few beers on a Saturday.',
      'sh.living': 'With my wife and three kids.',
      'sh.diet': 'Takeaways mostly — I’m on the road all day.',
      'fh.general': 'My dad’s diabetic too.',
      'pre.last_meal': 'A bacon sandwich at about eight this morning, and a cup of tea at eleven.',
      'comm.questions': 'Will I need an operation? Will it come back?',
    },
    key: [
      'comm.open',
      'pain.site',
      'pain.onset',
      'pain.character',
      'pain.severity',
      'pain.previous',
      'ano.lump',
      'ano.discharge',
      'ano.pain',
      'gi.stool_blood',
      'gi.bowel_change',
      'gi.weight',
      'sys.fever',
      'pmh.diabetes',
      'pmh.gi',
      'dh.steroids',
      'dh.allergies',
      'pre.last_meal',
    ],
    critical: ['pmh.diabetes'],
    ideas: 'I thought it was piles at first, but my wife said it looks like a boil.',
    concerns: 'I’m self-employed. If I can’t sit, I can’t drive, and I don’t get paid.',
    expectations: 'Something to make it stop hurting. Can’t you just give me antibiotics?',
    social: { smoking: 'Ten a day for twenty years.', alcohol: 'A few beers on a Saturday.', diet: 'Takeaways mostly — I’m on the road all day.' },
  },
  abdo: {
    general: {
      endOfBed:
        'Mr Murphy is standing beside the trolley because sitting is too painful. He looks flushed and uncomfortable but talks in full sentences. There is a cannula in his right hand.',
    },
    hands: { temperature: 'warm' },
    completion: {
      dre: 'With consent and a chaperone, in the left lateral position: a 4 cm tense, red, hot, exquisitely tender swelling in the perianal skin at about 7 o’clock (lithotomy position), 2 cm from the anal verge, with surrounding cellulitis and a fluctuant centre. There is no external opening, no fissure and no thrombosed haemorrhoid. A digital examination is too painful to tolerate — it should be done under anaesthesia.',
      genitalia: 'External genitalia appear normal: no perineal or scrotal redness, crepitus or skin necrosis.',
      urinalysis: 'Glucose 3+, ketones trace; leucocytes and nitrites absent.',
    },
  },
  criticalSteps: ['end.completion', 'gen.obs'],
  investigations: {
    bm: { report: '16.4 mmol/L', interpretation: 'Hyperglycaemia — diabetes is a risk factor for perianal sepsis and needs control around surgery.' },
    fbc: { values: FBC(148, 15.2, 12.6, 344), interpretation: 'Neutrophil leucocytosis.' },
    crp: { values: CRP(112), interpretation: 'Raised — a collection.' },
    ue: { values: UE(136, 4.3, 5.8, 82, '> 90'), interpretation: 'Normal renal function.' },
    vbg: {
      values: [lab('pH', '7.39', '', '7.35–7.45'), lab('HCO₃⁻', 24, 'mmol/L', '22–29'), lab('Lactate', 1.4, 'mmol/L', '0.5–2.0'), lab('Blood ketones', 0.4, 'mmol/L', '< 0.6'), lab('Glucose', 16.1, 'mmol/L', '4.0–7.8', 'H')],
      interpretation: 'No acidosis and no significant ketosis — not DKA.',
    },
    lipids: {
      values: [lab('HbA1c', 86, 'mmol/mol', '< 42', 'H'), lab('Total cholesterol', 5.6, 'mmol/L', '< 5.0', 'H')],
      interpretation: 'Poorly controlled diabetes (HbA1c 86) — refer to the diabetes team or GP to intensify treatment.',
    },
    'urine-dip': { report: 'Glucose 3+, ketones trace. Leucocytes −, nitrites −.', interpretation: 'Glycosuria from hyperglycaemia.' },
    'pus-mcs': {
      report: 'Pus from incision and drainage: mixed coliforms and anaerobes (E. coli, Bacteroides).',
      interpretation: 'Gut organisms raise the chance of an underlying fistula-in-ano; skin organisms (Staphylococcus aureus) make one less likely.',
      abnormal: true,
    },
    'mri-pelvis': {
      report: 'A 4 cm perianal collection at 7 o’clock, superficial to the external sphincter. No fistula tract demonstrated.',
      interpretation: 'Simple perianal abscess. MRI is not needed for a first, simple abscess — it is for recurrent or complex disease, or suspected Crohn’s.',
      abnormal: true,
    },
    gs: { report: 'Group B RhD positive. Antibody screen negative.' },
  },
  investigationRubric: {
    essential: [
      { id: 'bm', why: '!Check the glucose: diabetes predisposes to perianal sepsis and must be controlled peri-operatively.' },
      { id: 'fbc', why: 'Leucocytosis.' },
      { id: 'crp', why: 'Inflammatory response.' },
      { id: 'ue', why: 'Baseline before theatre (on metformin).' },
    ],
    helpful: [
      { id: 'lipids', why: 'HbA1c shows long-term diabetic control.' },
      { id: 'vbg', why: 'Exclude ketoacidosis in a febrile, hyperglycaemic diabetic.' },
      { id: 'urine-dip', why: 'Glycosuria and ketones.' },
      { id: 'pus-mcs', why: 'Gut organisms in the pus suggest a fistula.' },
    ],
  },
  diagnosis: {
    correct: 'perianal-abscess',
    differentials: ['fissure', 'thrombosed-haemorrhoid', 'pilonidal', 'fistula', 'fournier', 'crohns'],
  },
  management: {
    essential: [
      { id: 'analgesia', why: 'He is in severe pain.' },
      { id: 'nbm', why: 'Nil by mouth for theatre (he last ate at 08:00).' },
      { id: 'glucose-monitoring', why: 'Glucose 16.4: monitor and control with a variable-rate insulin infusion if needed while he is starved.' },
      {
        id: 'incision-drainage',
        why: '!Incision and drainage under general anaesthesia, with examination under anaesthesia: deroof the abscess, break down loculi, send pus for culture and leave the cavity open. Routine packing is not needed.',
      },
    ],
    helpful: [
      { id: 'abx-iv', why: 'Fever, surrounding cellulitis and diabetes justify antibiotics — but drainage is the treatment.' },
      { id: 'consent', why: 'Consent for EUA and drainage, including the possibility of finding a fistula.' },
      { id: 'senior', why: 'Book onto the emergency list.' },
      { id: 'laxatives', why: 'Stool softeners after surgery.' },
      { id: 'lifestyle', why: 'Diabetes control, weight and smoking.' },
      { id: 'smoking-cessation', why: 'Smoking is a risk factor for perianal sepsis and poor healing.' },
    ],
    avoid: [
      { id: 'discharge', why: 'Pus needs draining today — antibiotics alone will not resolve an abscess.' },
      { id: 'topical-gtn', why: 'GTN and diltiazem treat a fissure, not an abscess.' },
    ],
  },
  viva: [
    {
      id: 'anatomy',
      q: 'Classify anorectal abscesses by their anatomical space.',
      answer:
        'Most start as infection of an anal gland at the dentate line (the cryptoglandular theory). Pus then tracks into one of the spaces: perianal (the commonest, next to the anal verge), ischiorectal (ischioanal — larger, deeper, lateral, with less visible swelling), intersphincteric (deep rectal pain with little to see), or supralevator (rare, pelvic pain and sepsis). Horseshoe abscesses spread around the back of the anal canal.',
      topic: 'Anatomy',
    },
    {
      id: 'fistula-risk',
      q: 'Roughly what proportion of patients develop a fistula-in-ano after a perianal abscess?',
      options: ['About a third', 'Almost all', 'Fewer than 1%', 'About 90%'],
      correct: 0,
      answer:
        'Roughly a third go on to have a fistula-in-ano: the infected anal gland leaves a track between the anal canal and the perianal skin. Recurrence, persistent discharge, or gut organisms in the pus should prompt an MRI and examination under anaesthesia.',
      topic: 'Complications',
    },
    {
      id: 'goodsall',
      q: 'What does Goodsall’s rule predict?',
      answer:
        'The course of a fistula from the position of its external opening. With the patient in lithotomy and a line drawn transversely across the anus, an external opening anterior to the line usually leads straight (radially) to the anal canal, whereas one posterior to it usually curves to an internal opening in the posterior midline. Openings more than 3 cm from the anal verge often break the rule.',
      topic: 'Fistula',
    },
    {
      id: 'fissure',
      q: 'How would you distinguish an anal fissure from an abscess, and how is a fissure treated?',
      answer:
        'A fissure causes sharp, tearing pain during and for an hour or two after defecation, with bright red blood on the paper; there is no swelling or fever, and a posterior midline tear may be seen with a sentinel pile. An abscess gives constant throbbing pain, a hot tender swelling and fever. Fissures are treated with softening of the stool (fibre, fluids, laxatives) and topical GTN or diltiazem for 6–8 weeks, then botulinum toxin or lateral internal sphincterotomy if they fail. Atypical (lateral or multiple) fissures suggest Crohn’s, TB, HIV, syphilis or cancer.',
      topic: 'Differentials',
    },
    {
      id: 'fournier',
      q: 'Which feature should make you worry about Fournier’s gangrene instead?',
      options: ['Pain out of proportion, crepitus or dusky skin spreading across the perineum', 'A fluctuant swelling 2 cm from the anal verge', 'Bright red blood on the toilet paper', 'Itching around the anus'],
      correct: 0,
      answer:
        'Fournier’s gangrene is necrotising fasciitis of the perineum and genitalia. Diabetes, obesity and immunosuppression are risk factors. Look for pain out of proportion, rapidly spreading erythema or dusky skin, crepitus, skin necrosis and systemic toxicity. It needs resuscitation, broad-spectrum IV antibiotics and immediate radical surgical debridement.',
      topic: 'Emergencies',
    },
    {
      id: 'thrombosed',
      q: 'A patient has a sudden, exquisitely painful blue lump at the anal margin after straining. What is it, and how is it managed?',
      answer:
        'A thrombosed external haemorrhoid (perianal haematoma). Within about 72 hours of onset, excision (or incision and evacuation) of the clot under local anaesthetic gives rapid relief; after that, conservative treatment with analgesia, stool softeners, ice and topical agents is preferred because the pain is already settling.',
      topic: 'Differentials',
    },
  ],
  teaching: {
    summary:
      'Perianal abscess in a 41-year-old taxi driver with poorly controlled type 2 diabetes: three days of constant throbbing pain beside the anus, a hot, tender, fluctuant swelling at 7 o’clock, fever and a glucose of 16.4. The treatment is incision and drainage under anaesthesia, not antibiotics alone.',
    keyFindings: [
      'Three days of constant, throbbing perianal pain, worse on sitting, walking and defecation',
      'Fever and rigors; HR 104, T 38.2 °C',
      'Poorly controlled type 2 diabetes (glucose 16.4, HbA1c 86); smoker',
      'Perianal inspection: 4 cm tender, fluctuant, erythematous swelling at 7 o’clock, 2 cm from the anal verge',
      'No external opening, fissure or thrombosed haemorrhoid; no perineal crepitus or necrosis',
    ],
    pearls: [
      'Constant throbbing pain with fever means pus; pain only during and after defecation means a fissure.',
      'Abdominal examination is not complete without inspecting the perianal region — with consent and a chaperone.',
      'Always check the glucose: diabetes predisposes to perianal sepsis and to Fournier’s gangrene.',
      'Ask about Crohn’s symptoms (diarrhoea, weight loss, mouth ulcers) — perianal disease may be its first sign.',
      'Antibiotics do not treat an abscess. Drain it, and warn the patient that about a third develop a fistula.',
    ],
    presentation:
      'Mr Murphy is a 41-year-old taxi driver with poorly controlled type 2 diabetes who presents with three days of constant, throbbing pain beside his anus, worse on sitting, walking and defecation, with fever and rigors. He has no rectal bleeding, change in bowel habit, weight loss or previous perianal problems, and no history of inflammatory bowel disease. He is febrile at 38.2 with a heart rate of 104, and his capillary glucose is 16.4. His abdomen is soft and non-tender. On perianal inspection, with a chaperone, there is a 4 cm tense, red, hot, exquisitely tender, fluctuant swelling at 7 o’clock in the lithotomy position, 2 cm from the anal verge, with surrounding cellulitis; there is no external opening, fissure or thrombosed haemorrhoid, and no perineal crepitus. Digital examination was too painful. The diagnosis is a perianal abscess. I would give analgesia, keep him nil by mouth, control his glucose, check his blood count, CRP and renal function, and book him for examination under anaesthesia with incision and drainage, sending pus for culture. I would warn him that about a third of patients develop a fistula-in-ano, and arrange follow-up for his diabetes.',
    references: [
      'Association of Coloproctology of Great Britain and Ireland (ACPGBI) guidance on the management of anal fistula and abscess',
      'Newton K, et al. Packing of perianal abscess cavities (PPAC2): a multicentre randomised non-inferiority trial. Lancet Gastroenterol Hepatol 2022',
      'Macleod’s Clinical Examination, 14th ed. — Ch. 6: examination of the anus and rectum',
    ],
  },
}

export default c
