import type { CaseDef, RegionFinding } from '../../engine/types'
import { CRP, FBC, lab, LFT, r, UE, VBG } from './helpers'

const perit = (l: 1 | 2 | 3, d: 2 | 3): RegionFinding => r(l, d, 'involuntary', { percussionTender: true })

const c: CaseDef = {
  id: 'postop-leak',
  title: 'Anastomotic leak on day 5 after anterior resection',
  presenting: 'Fever and worsening abdominal pain five days after bowel surgery',
  specialty: 'Colorectal',
  exam: 'abdominal',
  difficulty: 3,
  setting: 'Surgical ward',
  stem: 'Surgical ward, night shift. Derek Collins, 64, is on day 5 after a laparoscopic anterior resection for rectal cancer. The nurse has called because he is febrile and his pain is worse. Assess him, examine him, investigate and manage.',
  components: ['history', 'exam', 'investigations', 'diagnosis', 'viva'],
  tags: ['post-operative', 'sepsis', 'anastomotic leak', 'NEWS2'],
  patient: {
    name: 'Derek Collins',
    title: 'Mr Collins',
    age: 64,
    sex: 'male',
    dob: '22/08/1962',
    occupation: 'a retired electrician',
    appearance: {
      sex: 'male',
      age: 64,
      skinTone: 2,
      habitus: 'overweight',
      hair: 'short',
      hairColor: 'grey',
      eyeColor: 'hazel',
      sweaty: true,
      flushed: 0.3,
      distension: 1,
      distensionType: 'gas',
      scars: ['lap-appendix', 'pfannenstiel'],
      stoma: { type: 'loop-ileostomy', side: 'right', bag: true },
      lines: { cannula: 'left-forearm', drip: true, catheter: true, drain: 'left' },
    },
    persona: { mood: 'irritable', style: 'brief' },
  },
  vitals: { hr: 118, rhythm: 'irregular', sbp: 102, dbp: 60, rr: 24, spo2: 94, o2: '2 L/min nasal', temp: 38.6, avpu: 'A', pain: 7 },
  history: {
    opening: { text: 'I was getting better… eating a bit yesterday. Now my whole belly hurts and I’m shivering.', cue: 'clutches the lower abdomen' },
    answers: {
      'pain.site': { text: 'Low down, all across, and spreading up.', cue: 'sweeps a hand across the lower abdomen' },
      'pain.onset': 'Since about six this evening; it’s getting worse.',
      'pain.character': 'Constant and sharp.',
      'pain.severity': 'Seven, and worse when I move.',
      'pain.exacerbating': 'Moving, coughing.',
      'sys.fever': 'Burning up.',
      'sys.rigors': 'Shaking an hour ago.',
      'gi.nausea': 'Yes.',
      'gi.vomiting': 'Twice tonight.',
      'gi.appetite': 'I can’t eat now.',
      'gi.flatus': 'The bag hasn’t had much in it since this afternoon.',
      'gi.bowels_last': 'Only the bag — not much today.',
      'ros.sob': 'A bit breathless.',
      'ros.chest_pain': 'No chest pain.',
      'ros.cough': 'No cough.',
      'ros.palpitations': 'My heart feels like it’s fluttering.',
      'gu.output': 'The nurse says the catheter bag’s been low.',
      'pmh.surgery': 'The bowel operation for cancer five days ago, with a temporary bag.',
      'pmh.conditions': 'Type 2 diabetes and high blood pressure.',
      'dh.meds': 'Metformin on hold; insulin sliding scale; blood-thinning injections; morphine.',
      'dh.allergies': 'None.',
      'sh.smoking': 'Ten a day.',
      'sh.alcohol': 'Social.',
      'comm.questions': 'Has the join come apart?',
    },
    key: ['comm.open', 'pain.site', 'pain.onset', 'pain.severity', 'sys.fever', 'gi.vomiting', 'gi.flatus', 'ros.sob', 'ros.chest_pain', 'ros.cough', 'gu.output', 'pmh.surgery', 'pmh.conditions', 'dh.allergies'],
    critical: ['pmh.surgery'],
    ideas: 'Something’s gone wrong inside.',
    concerns: 'I don’t want to die after beating the cancer.',
    expectations: 'Fix it.',
    pmh: 'Rectal cancer (laparoscopic anterior resection + loop ileostomy day 5), T2DM, hypertension.',
  },
  abdo: {
    general: {
      endOfBed:
        'Mr Collins is flushed, sweating and breathing quickly, lying still with his knees bent. There is a right iliac fossa loop ileostomy with little output, a left pelvic drain containing cloudy brown fluid, and a catheter with 10 mL of concentrated urine in the last hour.',
      lyingStill: true,
    },
    hands: { temperature: 'warm', crt: 3 },
    face: { mucosa: 'dry', tongue: 'dry-furred' },
    abdomen: {
      shape: 'distended',
      inspectionExtra: 'Laparoscopic port sites and a small Pfannenstiel extraction wound, clean and dry. Right iliac fossa loop ileostomy: pink and healthy, minimal output. Left pelvic drain with turbid, faeculent-smelling fluid.',
      movesWithRespiration: 'reduced',
      coughPain: true,
      rigidity: 'localised',
      regions: { SP: perit(3, 3), LIF: perit(3, 3), RIF: perit(2, 3), UMB: perit(1, 2), LF: r(1, 2, 'voluntary'), RF: r(1, 2, 'voluntary') },
      bowelSounds: 'reduced',
    },
    completion: { obs: 'NEWS2 10: RR 24, SpO₂ 94% on 2 L, BP 102/60, HR 118 irregular, temp 38.6.', urinalysis: 'Ketones +, glucose ++.' },
  },
  criticalSteps: ['gen.obs', 'palp.peritonism'],
  investigations: {
    fbc: { values: FBC(112, 19.4, 17.2, 342), interpretation: 'Neutrophil leucocytosis.' },
    crp: { values: CRP(318), interpretation: 'CRP above 150 on day 3–5 after colorectal surgery strongly suggests a complication such as a leak.' },
    ue: { values: UE(134, 5.2, 13.1, 168, '36'), interpretation: 'AKI.' },
    lft: { values: LFT(19, 32, 104, 58, 26) },
    vbg: { values: VBG(7.28, 17, -7.8, 3.9, 5.2, 14.2), interpretation: 'Metabolic acidosis, lactate 3.9 — septic shock developing.' },
    cultures: { report: 'Sent before antibiotics: Gram-negative rods at 18 hours.' },
    'drain-fluid': { report: 'Turbid brown, faeculent-smelling fluid. Gram stain: mixed Gram-negative rods.', interpretation: 'Faecal contamination — anastomotic leak.', abnormal: true },
    'ct-ap': {
      report: 'Free gas and a 6 cm rim-enhancing gas–fluid collection at the colorectal anastomosis, with rectal contrast extravasating into it; free fluid in the pelvis and paracolic gutters.',
      interpretation: 'Anastomotic leak with a pelvic abscess and peritoneal contamination.',
      abnormal: true,
    },
    ecg: { report: 'New atrial fibrillation, rate 118.', interpretation: 'New AF is a classic sign of post-operative sepsis — look for the leak.', abnormal: true },
    'cxr-erect': { report: 'Small basal atelectasis. Free gas — non-specific 5 days after laparoscopy.' },
    ctpa: { report: 'No PE.', interpretation: 'PE excluded.' },
    gs: { report: 'Group B RhD positive.' },
    glucose: { values: [lab('Glucose', '14.2', 'mmol/L', '4.0–7.8', 'H')] },
  },
  investigationRubric: {
    essential: [
      { id: 'fbc', why: 'Leucocytosis.' },
      { id: 'crp', why: 'Trend — a high CRP on day 3–5 predicts a leak.' },
      { id: 'ue', why: 'AKI.' },
      { id: 'vbg', why: 'Lactate.' },
      { id: 'cultures', why: 'Before antibiotics.' },
      { id: 'ct-ap', why: 'CT with IV (± rectal) contrast confirms a leak and collection.' },
      { id: 'ecg', why: 'Irregular pulse — new AF.' },
    ],
    helpful: [
      { id: 'drain-fluid', why: 'Faeculent fluid is diagnostic.' },
      { id: 'gs', why: 'Return to theatre.' },
      { id: 'ctpa', why: 'PE is a differential of post-op tachycardia.' },
      { id: 'glucose', why: 'Diabetic and septic.' },
    ],
    avoid: [{ id: 'colonoscopy', why: 'Insufflation can disrupt a fresh anastomosis.' }],
  },
  diagnosis: {
    correct: 'anastomotic-leak',
    differentials: ['pe', 'lower-lobe-pneumonia', 'ssi', 'uti', 'ileus'],
  },
  management: {
    essential: [
      { id: 'abcde', why: 'NEWS2 10.' },
      { id: 'sepsis6', why: 'Septic shock evolving.' },
      { id: 'abx-iv', why: 'Broad-spectrum IV antibiotics covering Gram-negatives and anaerobes.' },
      { id: 'fluids', why: 'Hypotension, AKI.' },
      { id: 'nbm', why: 'Theatre.' },
      { id: 'senior', why: 'Consultant surgeon now.' },
      { id: 'relook', why: '!Peritonitis with a leak: return to theatre for washout and control of the anastomosis (take-down to an end colostomy, or repair/drain if the leak is small and already defunctioned).' },
      { id: 'icu', why: 'Septic shock, AKI.' },
    ],
    helpful: [
      { id: 'drainage-radiological', why: 'A contained collection without peritonitis may be drained percutaneously.' },
      { id: 'ng', why: 'Vomiting with ileus.' },
      { id: 'consent', why: 'Return to theatre.' },
      { id: 'glucose-monitoring', why: 'Hyperglycaemia.' },
      { id: 'vte', why: 'Continue prophylaxis.' },
    ],
    avoid: [
      { id: 'diet-normal', why: 'Nil by mouth.' },
      { id: 'observe', why: 'Peritonitis and shock need source control now.' },
      { id: 'discharge', why: 'Septic.' },
    ],
  },
  viva: [
    {
      id: 'fever',
      q: 'Give the causes of post-operative fever by day.',
      answer: 'Day 0–2: inflammatory response, atelectasis, transfusion reaction. Day 3–5: pneumonia, UTI, line infection, anastomotic leak (classically days 3–7). Day 5–7+: wound infection, abscess, DVT/PE. Remember drug fever.',
      topic: 'Post-op',
    },
    {
      id: 'leaksigns',
      q: 'What are the signs of an anastomotic leak?',
      options: ['Tachycardia, new AF, fever, ileus, rising CRP and peritonism', 'Bradycardia and polyuria', 'Only a fever', 'Only a wound discharge'],
      correct: 0,
      answer: 'Tachycardia and new AF, fever, tachypnoea, oliguria, prolonged ileus, abdominal pain and peritonism, faeculent drain fluid and a rising CRP (> 150 on day 3–5).',
      topic: 'Signs',
    },
    {
      id: 'risk',
      q: 'What are the risk factors for anastomotic leak?',
      answer: 'Low colorectal anastomosis, male sex, smoking, obesity, diabetes, steroids, malnutrition, preoperative radiotherapy, emergency surgery, blood loss and technical factors (tension, poor blood supply). A defunctioning ileostomy reduces the consequences rather than the leak itself.',
      topic: 'Risk',
    },
    {
      id: 'news',
      q: 'How does NEWS2 guide escalation?',
      answer: 'Score 0–4: ward-based care; 3 in one parameter: urgent ward review; 5–6: urgent response; 7 or more: emergency response with critical care input (Macleod’s, Ch. 18).',
      topic: 'Escalation',
    },
  ],
  teaching: {
    summary:
      'Anastomotic leak on day 5 after anterior resection: a patient who was improving develops fever, rigors, new AF, tachypnoea, oliguria and lower abdominal peritonism, with faeculent drain fluid, CRP 318 and a leak with pelvic collection on CT.',
    keyFindings: [
      'Day 5 after laparoscopic anterior resection with loop ileostomy',
      'Fever 38.6, rigors, HR 118 in new AF, RR 24, BP 102/60, oliguria — NEWS2 10',
      'Lower abdominal peritonism; reduced stoma output',
      'Faeculent drain fluid; CRP 318, lactate 3.9, AKI',
      'CT: anastomotic leak with a 6 cm pelvic collection',
    ],
    pearls: [
      'New AF after bowel surgery is a leak until proven otherwise.',
      'CRP > 150 on day 3–5 should prompt a CT.',
      'Peritonitis needs source control — antibiotics alone will not do.',
      'Escalate using NEWS2 and SBAR.',
    ],
    presentation:
      'Mr Collins is a 64-year-old man with type 2 diabetes on day 5 after a laparoscopic anterior resection with a defunctioning loop ileostomy for rectal cancer, who developed lower abdominal pain, fever, rigors and vomiting this evening after initially recovering. He has a NEWS2 of 10 with new atrial fibrillation at 118, RR 24, BP 102/60, temperature 38.6 and oliguria. He has peritonism in the lower abdomen, reduced stoma output and faeculent fluid in his pelvic drain. CRP is 318, lactate 3.9 and he has an AKI; CT shows an anastomotic leak with a pelvic collection. I would start the Sepsis Six with broad-spectrum antibiotics, call the consultant, involve critical care and arrange return to theatre for washout and control of the anastomosis.',
    references: ['Macleod’s Clinical Examination, 14th ed. — Ch. 18: the deteriorating patient (NEWS2, ABCDE, sepsis)', 'Association of Coloproctology of GB & Ireland: anastomotic leak guidance'],
  },
}

export default c
