import type { CaseDef } from '../../engine/types'
import { FBC, lab, r, UE, VBG } from './helpers'

const c: CaseDef = {
  id: 'ruptured-aaa',
  title: 'Ruptured abdominal aortic aneurysm',
  presenting: 'Collapse with abdominal and back pain',
  specialty: 'Vascular',
  exam: 'abdominal',
  difficulty: 3,
  setting: 'Emergency department',
  stem: 'George Harris, 74, collapsed at home and is now in resus complaining of abdominal and back pain. Assess and manage him. This is time-critical.',
  components: ['history', 'exam', 'investigations', 'diagnosis', 'viva'],
  tags: ['shock', 'vascular emergency', 'AAA', 'permissive hypotension'],
  patient: {
    name: 'George Harris',
    title: 'Mr Harris',
    age: 74,
    sex: 'male',
    dob: '03/03/1952',
    occupation: 'a retired docker',
    appearance: {
      sex: 'male',
      age: 74,
      skinTone: 2,
      habitus: 'average',
      hair: 'bald',
      hairColor: 'grey',
      eyeColor: 'grey',
      pallor: 0.7,
      sweaty: true,
      visiblePulsation: true,
      lines: { cannula: 'left-forearm', oxygen: 'mask' },
    },
    persona: { mood: 'distressed', style: 'brief' },
  },
  vitals: { hr: 124, rhythm: 'regular', sbp: 82, dbp: 50, rr: 26, spo2: 94, o2: '15 L/min non-rebreathe', temp: 36.1, avpu: 'A', pain: 9 },
  history: {
    opening: { text: 'Terrible pain… in my back and my belly… came on all of a sudden. I went dizzy and blacked out on the kitchen floor.', cue: 'grey and sweating, clutching his left side' },
    answers: {
      'pain.site': { text: 'My back… and here in my belly, going round to the left.', cue: 'points to the middle of his abdomen and his left loin' },
      'pain.onset': 'Suddenly, about an hour ago. I was just getting up from my chair.',
      'pain.character': 'Like something ripping. Constant.',
      'pain.radiation': 'Round to my left side and down into my groin.',
      'pain.severity': 'Ten.',
      'pain.timing': 'Constant.',
      'pain.previous': 'Never.',
      'ros.dizzy': 'I blacked out for a minute. My wife found me.',
      'gi.vomiting': 'No.',
      'gu.haematuria': 'No.',
      'pmh.conditions': 'Blood pressure… a heart attack ten years ago — they put stents in. Chest problems — COPD.',
      'pmh.heart': 'A heart attack ten years ago. Two stents.',
      'vas.claudication': 'My calves ache walking up hills.',
      'pmh.gi': 'Two years ago they found a swelling on the main artery in my tummy — five centimetres they said. I was supposed to go for scans… I missed them.',
      'dh.meds': 'Aspirin, a statin, ramipril, inhalers.',
      'dh.anticoag': 'Just the aspirin.',
      'sh.smoking': 'Forty a day for fifty years. Still smoke.',
      'fh.general': 'My brother had an aneurysm fixed.',
      'comm.questions': 'Am I dying?',
    },
    key: ['comm.open', 'pain.site', 'pain.onset', 'pain.character', 'pain.radiation', 'ros.dizzy', 'pmh.gi', 'pmh.conditions', 'dh.meds', 'dh.anticoag', 'dh.allergies', 'sh.smoking', 'fh.general'],
    critical: ['pmh.gi'],
    ideas: 'Is it my heart again?',
    concerns: 'My wife… she can’t cope on her own.',
    expectations: 'Just help me.',
    social: { smoking: '40 a day for 50 years (100 pack-years).', living: 'With his wife.' },
  },
  abdo: {
    general: {
      endOfBed:
        'Mr Harris looks grey, pale and clammy, and is visibly distressed. He is on high-flow oxygen through a non-rebreathe mask with a cannula in his left forearm. He is conscious but breathing fast.',
      restless: true,
    },
    hands: { temperature: 'cold', crt: 4, pulseVolume: 'weak' },
    face: { conjunctiva: 'pale', mucosa: 'dry' },
    abdomen: {
      regions: {
        EPI: r(1, 2, 'voluntary', {
          mass: { description: 'a large, tender, pulsatile mass above the umbilicus, slightly left of the midline', label: 'expansile pulsatile mass (AAA)', sizeCm: 7, tender: true, pulsatile: 'expansile' },
        }),
        UMB: r(1, 2, 'voluntary'),
        LF: r(1, 2, 'voluntary'),
      },
      aorta: { expansile: true, widthCm: 7, tender: true },
      bruits: { aortic: false },
    },
    completion: { 'femoral-pulses': 'Both femoral pulses are weak but palpable.' },
  },
  criticalSteps: ['org.aorta', 'gen.obs'],
  investigations: {
    vbg: { values: [...VBG(7.26, 17, -8.4, 4.8, 5.1, 9.4), lab('Haemoglobin', 94, 'g/L', '130–170', 'L')], interpretation: 'Metabolic acidosis, lactate 4.8 and falling Hb — haemorrhagic shock.' },
    xm: { report: '10 units of red cells crossmatched; major haemorrhage pack 1 issued (red cells, FFP, platelets).', interpretation: 'Blood ready.' },
    fbc: { values: FBC(96, 14.2, 11.8, 170), interpretation: 'Early Hb underestimates blood loss.' },
    ue: { values: UE(140, 5.1, 10.1, 142, '43'), interpretation: 'AKI from hypoperfusion.' },
    coag: { values: [lab('PT', 14.2, 's', '10–13', 'H'), lab('INR', 1.3, '', '0.8–1.2', 'H'), lab('APTT', 38, 's', '25–35', 'H'), lab('Fibrinogen', 1.4, 'g/L', '1.5–4.0', 'L')], interpretation: 'Early consumptive coagulopathy.' },
    ecg: { report: 'Sinus tachycardia 124. Old Q waves inferiorly. No acute ST elevation.', interpretation: 'No acute MI — but his cardiac history raises operative risk.' },
    'us-abdo': { report: 'Point-of-care ultrasound: infrarenal abdominal aortic aneurysm measuring 7.1 cm with surrounding retroperitoneal fluid.', interpretation: 'Ruptured AAA in a shocked patient — no further imaging should delay theatre.', abnormal: true },
    cta: {
      report: '7.2 cm infrarenal AAA with a large left retroperitoneal haematoma and active contrast extravasation. Suitable neck anatomy for EVAR.',
      interpretation: 'Contained rupture; EVAR-suitable. (Only obtain CT if the patient is stable enough — never let imaging delay control of bleeding.)',
      abnormal: true,
    },
    troponin: { values: [lab('hs-Troponin T', 38, 'ng/L', '< 14', 'H')], interpretation: 'Demand ischaemia from shock.' },
  },
  investigationRubric: {
    essential: [
      { id: 'xm', why: 'Crossmatch (and activate the major haemorrhage protocol) immediately.' },
      { id: 'vbg', why: 'Hb and lactate within minutes.' },
      { id: 'fbc', why: 'Baseline.' },
      { id: 'coag', why: 'Coagulopathy is expected — guides blood products.' },
    ],
    helpful: [
      { id: 'us-abdo', why: 'Point-of-care ultrasound confirms an aneurysm in minutes.' },
      { id: 'ue', why: 'Renal function.' },
      { id: 'ecg', why: 'Ischaemic heart disease is common.' },
      { id: 'cta', why: 'If haemodynamically stable enough: plans EVAR.' },
    ],
  },
  diagnosis: {
    correct: 'aaa-rupture',
    differentials: ['renal-colic', 'mi', 'perforated-pu', 'pancreatitis', 'aortic-dissection', 'mesenteric-ischaemia'],
  },
  management: {
    essential: [
      { id: 'abcde', why: 'Shocked patient: ABCDE.' },
      { id: 'iv-access', why: 'Two large-bore cannulae.' },
      { id: 'mhp', why: 'Activate the major haemorrhage protocol — O-negative/group-specific blood, FFP, platelets.' },
      { id: 'permissive-hypotension', why: '!Target a systolic of ~70–90 mmHg while he is conscious — normalising BP increases bleeding.' },
      { id: 'vascular', why: '!Immediate referral to the on-call vascular surgeon.' },
      { id: 'aaa-repair-emergency', why: 'Emergency repair — EVAR if anatomically suitable, otherwise open.' },
      { id: 'theatre', why: 'Alert theatres/hybrid suite and anaesthetics.' },
    ],
    helpful: [
      { id: 'o2', why: 'High-flow oxygen.' },
      { id: 'analgesia', why: 'Titrated IV opioid.' },
      { id: 'catheter', why: 'Urine output monitoring (without delaying transfer).' },
      { id: 'icu', why: 'Post-operative intensive care.' },
      { id: 'senior', why: 'Senior ED and surgical input.' },
      { id: 'breaking-news', why: 'Explain the gravity; discuss escalation and wishes with him and his wife.' },
    ],
    avoid: [
      { id: 'fluids', why: 'Large-volume crystalloid to “normalise” BP dilutes clotting factors and disrupts clot — use permissive hypotension and blood products.' },
      { id: 'discharge', why: 'Life-threatening haemorrhage.' },
      { id: 'nsaid', why: 'Contraindicated in haemorrhage and AKI.' },
    ],
  },
  viva: [
    {
      id: 'triad',
      q: 'What is the classic triad of a ruptured AAA?',
      options: ['Pain (abdomen/back), hypotension, pulsatile abdominal mass', 'Fever, jaundice, RUQ pain', 'Pain, pallor, pulselessness', 'Headache, hypertension, papilloedema'],
      correct: 0,
      answer: 'Abdominal/back (often left loin to groin) pain, hypotension/collapse, and a pulsatile abdominal mass. All three are present in only about half of cases — any older smoker with “renal colic” deserves an aortic ultrasound.',
      topic: 'Recognition',
    },
    {
      id: 'screening',
      q: 'Describe the NHS AAA screening programme and surveillance intervals.',
      answer:
        'Men are invited for a one-off ultrasound in the year they turn 65. < 3 cm: normal, discharged. 3.0–4.4 cm (small): annual scans. 4.5–5.4 cm (medium): 3-monthly scans. ≥ 5.5 cm (large): refer to a vascular surgeon to be seen within 2 weeks. Men over 65 can self-refer.',
      topic: 'Screening',
    },
    {
      id: 'repair',
      q: 'When is elective repair offered?',
      answer: 'Diameter ≥ 5.5 cm, growth > 1 cm per year, or a symptomatic (tender) aneurysm — provided the patient is fit. Options are EVAR or open repair, decided with the patient after assessing anatomy and fitness.',
      topic: 'Management',
    },
    {
      id: 'permissive',
      q: 'Why use permissive hypotension?',
      answer: 'A lower pressure favours clot formation over the rupture; aggressive crystalloid raises BP, dislodges clot and causes dilutional coagulopathy and hypothermia. Keep him conscious with a systolic of ~70–90 mmHg and give blood products until the aorta is controlled.',
      topic: 'Physiology',
    },
    {
      id: 'risk',
      q: 'Which of these is NOT a risk factor for AAA?',
      options: ['Diabetes mellitus', 'Smoking', 'Male sex', 'Family history'],
      correct: 0,
      answer: 'Diabetes is paradoxically associated with a lower risk of AAA. Risk factors: age, male sex, smoking (the strongest modifiable factor), hypertension, family history, atherosclerosis, COPD.',
      topic: 'Epidemiology',
    },
  ],
  teaching: {
    summary:
      'Ruptured infrarenal AAA in a 74-year-old heavy smoker who missed surveillance of a known 5 cm aneurysm: sudden back and abdominal pain radiating to the left loin, collapse, haemorrhagic shock and a tender, expansile, pulsatile mass.',
    keyFindings: [
      'Sudden “ripping” back and abdominal pain → left loin/groin, syncope',
      'Known 5 cm AAA, missed surveillance; 100 pack-years; brother had an AAA',
      'HR 124, BP 82/50, cold peripheries, CRT 4 s, lactate 4.8',
      'Tender, expansile pulsatile mass ~7 cm above the umbilicus',
      'Bedside ultrasound: 7.1 cm AAA with retroperitoneal fluid',
    ],
    pearls: [
      'Older smoker + “renal colic” = AAA until proven otherwise.',
      'Expansile: your fingers are pushed apart, not just up.',
      'Unstable patient: straight to theatre — don’t lose time in the CT scanner.',
      'Permissive hypotension and blood products, not litres of crystalloid.',
      'Call the vascular surgeon at the first suspicion.',
    ],
    presentation:
      'Mr Harris is a 74-year-old man with a known 5 cm AAA who missed surveillance, presenting one hour after sudden severe “ripping” back and abdominal pain radiating to the left loin, with syncope. He is a heavy smoker with ischaemic heart disease and COPD. He is shocked: HR 124, BP 82/50, cold peripheries, CRT 4 seconds, lactate 4.8 and Hb 94. There is a tender, expansile, pulsatile mass above the umbilicus, and bedside ultrasound shows a 7 cm AAA with retroperitoneal fluid. This is a ruptured abdominal aortic aneurysm. I would call the vascular surgeon immediately, activate the major haemorrhage protocol, maintain permissive hypotension with blood products via two large-bore cannulae, and transfer him to theatre for emergency EVAR or open repair, while explaining the seriousness to him and his wife.',
    references: ['NICE NG156 Abdominal aortic aneurysm: diagnosis and management (2020)', 'NHS AAA Screening Programme', 'Macleod’s Clinical Examination, 14th ed. — Ch. 4/6: the abdominal aorta'],
  },
}

export default c
