import type { CaseDef } from '../../engine/types'
import { CRP, FBC, lab, r, UE, VBG } from './helpers'

const c: CaseDef = {
  id: 'sbo-femoral',
  title: 'Small bowel obstruction from an incarcerated right femoral hernia',
  presenting: 'Vomiting and abdominal distension',
  specialty: 'Emergency general surgery',
  exam: 'abdominal',
  difficulty: 2,
  setting: 'Emergency department',
  stem: 'Edith Clarke, 83, was brought in by ambulance with vomiting and a swollen abdomen. Take a history, examine her, request investigations and decide on management.',
  components: ['history', 'exam', 'investigations', 'diagnosis', 'viva'],
  tags: ['bowel obstruction', 'hernia', 'elderly', 'NELA'],
  patient: {
    name: 'Edith Clarke',
    title: 'Mrs Clarke',
    age: 83,
    sex: 'female',
    dob: '21/06/1943',
    occupation: 'a retired seamstress',
    appearance: {
      sex: 'female',
      age: 83,
      skinTone: 1,
      habitus: 'thin',
      hair: 'bun',
      hairColor: 'white',
      eyeColor: 'blue',
      distension: 2,
      distensionType: 'gas',
      visiblePeristalsis: true,
      scars: ['pfannenstiel'],
      hernias: [{ kind: 'femoral', side: 'right', size: 'medium', visible: 'always', tense: true }],
      dehydrated: true,
      sweaty: true,
      lines: { cannula: 'left-forearm', drip: true },
    },
    persona: { mood: 'distressed', style: 'brief' },
  },
  vitals: { hr: 108, rhythm: 'regular', sbp: 104, dbp: 62, rr: 22, spo2: 95, temp: 37.4, avpu: 'A', pain: 6 },
  bedside: { vomitBowl: 'feculent', drip: true, walkingFrame: true },
  history: {
    opening: { text: 'I’ve been sick all night, dear, and my tummy’s all blown up. I can’t keep anything down.', cue: 'rests a hand on her swollen abdomen' },
    answers: {
      'pain.site': { text: 'All over the middle of my tummy.', cue: 'circles her hand around the umbilicus' },
      'pain.onset': 'It started two days ago. It came on bit by bit.',
      'pain.character': 'It comes in waves — a cramping, twisting pain — then it eases a little.',
      'pain.radiation': 'No, it stays in my tummy.',
      'pain.moved': 'No, it’s always been in the middle.',
      'pain.timing': 'It comes every few minutes, then settles, then comes again.',
      'pain.exacerbating': 'Nothing in particular — it just comes.',
      'pain.relieving': 'Being sick eases it for a little while.',
      'pain.severity': 'About six out of ten, dear — worse when the cramps come.',
      'pain.previous': 'Never like this.',
      'gi.nausea': 'Terribly sick.',
      'gi.vomiting': 'More times than I can count since yesterday. Great big amounts.',
      'gi.vomit_content': 'Green at first. This morning it went brown and it smelled awful — like the toilet.',
      'gi.appetite': 'I can’t eat a thing.',
      'gi.bowels_last': 'Not for three days, dear. Nothing at all.',
      'gi.flatus': 'No — not since yesterday morning.',
      'gi.distension': 'Yes, it’s got bigger and bigger. It’s tight like a drum.',
      'gi.bowel_change': 'I’m usually regular as clockwork.',
      'gi.stool_blood': 'No, never seen blood.',
      'gi.weight': 'I don’t think so.',
      'sys.lumps': {
        text: 'Well… there’s been a little lump at the top of my right leg, in the groin, on and off for a few months. It used to go away when I lay down. But since yesterday it’s been sore and it won’t go back.',
        cue: 'touches her right groin',
      },
      'lump.when': 'A few months ago, I suppose. I didn’t want to bother the doctor.',
      'lump.pain': 'It never hurt before. Now it’s really sore.',
      'lump.reduce': 'It used to disappear when I lay down. Not any more.',
      'lump.change': 'It’s been the same size really, a bit like a grape. Harder now.',
      'lump.cough': 'It used to pop out when I coughed.',
      'sys.fever': 'I’ve felt a bit hot and cold.',
      'gu.output': 'I’ve hardly passed any water today.',
      'pmh.conditions': 'Blood pressure, and arthritis in my knees.',
      'pmh.surgery': 'A hysterectomy when I was about forty-five — through a bikini-line cut. Nothing since.',
      'dh.meds': 'Ramipril for my blood pressure, and paracetamol. Sometimes ibuprofen for my knees.',
      'dh.nsaids': 'Ibuprofen now and then for my knees.',
      'sh.living': 'On my own, in a ground-floor flat. My daughter pops in every day.',
      'sh.mobility': 'I get about with my frame. I do my own washing and cooking.',
      'sh.smoking': 'Never.',
      'sh.alcohol': 'A small sherry at Christmas.',
      'pre.last_meal': 'Nothing since yesterday — I can’t keep it down.',
      'comm.questions': 'Will I be able to go home soon?',
    },
    key: [
      'comm.open',
      'pain.site',
      'pain.onset',
      'pain.character',
      'pain.timing',
      'gi.vomiting',
      'gi.vomit_content',
      'gi.bowels_last',
      'gi.flatus',
      'gi.distension',
      'sys.lumps',
      'pmh.surgery',
      'pmh.conditions',
      'dh.meds',
      'dh.allergies',
      'sh.living',
      'sh.mobility',
    ],
    ideas: 'I thought it was a tummy bug at first.',
    concerns: 'I’m frightened I won’t manage at home on my own after this.',
    expectations: 'Just make the sickness stop, please.',
    social: { living: 'Alone, with daily visits from her daughter.', mobility: 'Walks with a frame, independent with personal care.' },
  },
  abdo: {
    general: {
      endOfBed:
        'Mrs Clarke is a frail, elderly woman who looks dehydrated and unwell, with a visibly distended abdomen. A kidney dish of brown, foul-smelling vomit sits on the locker. A cannula is in her left forearm with fluids running; there is no NG tube or catheter yet. A walking frame stands at the foot of the bed.',
    },
    hands: { temperature: 'cool', crt: 3, pulseVolume: 'weak' },
    face: { mucosa: 'dry', tongue: 'dry-furred', fetor: 'faeculent' },
    abdomen: {
      shape: 'distended',
      regions: {
        UMB: r(1, 2),
        EPI: r(0, 1),
        RF: r(0, 1),
        LF: r(0, 1),
        SP: r(0, 1),
      },
      bowelSounds: 'tinkling',
      hernias: {
        rightFemoral: {
          present: true,
          description: 'A 3 cm firm, tense, tender lump in the right groin, below and lateral to the pubic tubercle. The overlying skin is slightly red and warm.',
          coughImpulse: false,
          reducible: false,
          tender: true,
        },
      },
    },
    completion: {
      dre: 'Empty rectum. No masses, no blood.',
      urinalysis: 'Ketones ++, specific gravity 1.030; otherwise negative.',
    },
  },
  criticalSteps: ['hern.orifices'],
  investigations: {
    fbc: { values: FBC(128, 13.8, 11.6, 390, 90, 'female'), interpretation: 'Leucocytosis.' },
    ue: {
      values: UE(133, 3.1, 14.8, 138, '31', 'female'),
      interpretation: 'Pre-renal acute kidney injury (urea disproportionately high) with hypokalaemia and hyponatraemia from vomiting.',
    },
    crp: { values: CRP(48) },
    vbg: {
      values: VBG(7.47, 31, 5.2, 2.9, 3.1, 7.2),
      interpretation: 'Metabolic alkalosis with hypokalaemia (loss of gastric acid). Raised lactate — worry about strangulated bowel.',
    },
    lft: { values: [lab('Bilirubin', 12, 'µmol/L', '< 21'), lab('ALT', 22, 'U/L', '< 40'), lab('ALP', 88, 'U/L', '30–130'), lab('Albumin', 33, 'g/L', '35–50', 'L')], interpretation: 'Low albumin (acute illness/nutrition).' },
    amylase: { values: [lab('Amylase', 102, 'U/L', '30–110')], interpretation: 'Normal (amylase can rise modestly in obstruction).' },
    axr: {
      report: 'Multiple dilated central small-bowel loops (up to 4.5 cm) with valvulae conniventes crossing the full width of the bowel. Paucity of colonic gas.',
      interpretation: 'Small bowel obstruction (3–6–9 rule: small bowel > 3 cm is dilated).',
      abnormal: true,
    },
    'cxr-erect': { report: 'No free subdiaphragmatic gas. Clear lung fields.', interpretation: 'No perforation.' },
    'ct-ap': {
      report:
        'Dilated, fluid-filled small-bowel loops with a transition point at a right femoral hernia containing a loop of distal ileum. The herniated loop shows reduced mural enhancement with adjacent fluid, concerning for strangulation. Collapsed distal small bowel and colon. No free gas.',
      interpretation: 'Obstructed (and probably strangulated) right femoral hernia — emergency surgery.',
      abnormal: true,
    },
    coag: { values: [lab('INR', 1.1, '', '0.8–1.2'), lab('APTT', 30, 's', '25–35')] },
    gs: { report: 'Group O RhD positive. Antibody screen negative.' },
  },
  investigationRubric: {
    essential: [
      { id: 'fbc', why: 'Leucocytosis may signal strangulation.' },
      { id: 'ue', why: 'Vomiting causes AKI, hypokalaemia and hyponatraemia — correct before theatre.' },
      { id: 'vbg', why: 'Lactate is a marker of bowel ischaemia; also shows the metabolic alkalosis.' },
      { id: 'ct-ap', why: 'CT confirms obstruction, finds the cause (transition point) and signs of strangulation.' },
      { id: 'gs', why: 'Pre-operative.' },
    ],
    helpful: [
      { id: 'axr', why: 'Quick confirmation of small bowel dilatation.' },
      { id: 'crp', why: 'Inflammatory response.' },
      { id: 'coag', why: 'Pre-operative.' },
      { id: 'cxr-erect', why: 'Exclude perforation; pre-operative chest assessment.' },
      { id: 'amylase', why: 'Exclude pancreatitis as a cause of ileus.' },
    ],
  },
  diagnosis: {
    correct: 'sbo-hernia',
    accept: ['strangulated-hernia', 'femoral-hernia'],
    differentials: ['sbo-adhesions', 'lbo-cancer', 'mesenteric-ischaemia', 'ileus', 'sigmoid-volvulus'],
  },
  management: {
    essential: [
      { id: 'fluids', why: 'Dehydrated with AKI — resuscitate with IV crystalloid.' },
      { id: 'ng', why: 'Decompress the stomach: relieves vomiting and reduces aspiration risk.' },
      { id: 'catheter', why: 'Monitor urine output hourly (AKI).' },
      { id: 'analgesia', why: 'Titrated analgesia.' },
      { id: 'senior', why: 'Senior surgical review.' },
      { id: 'hernia-emergency', why: '!An obstructed, possibly strangulated femoral hernia needs urgent surgery — conservative management is not appropriate.' },
      { id: 'theatre', why: 'Book emergency theatre and inform the anaesthetist.' },
    ],
    helpful: [
      { id: 'maintenance-fluids', why: 'Replace potassium once passing urine.' },
      { id: 'antiemetic', why: 'Symptom control (NG tube is the main treatment).' },
      { id: 'nbm', why: 'Nil by mouth.' },
      { id: 'fluid-balance', why: 'Strict input/output.' },
      { id: 'abx-iv', why: 'Suspected strangulation — IV antibiotics are commonly given.' },
      { id: 'icu', why: 'Frail, high-risk emergency laparotomy patient (NELA): plan post-operative critical care.' },
      { id: 'consent', why: 'Consent including possible bowel resection.' },
      { id: 'vte', why: 'VTE prophylaxis.' },
    ],
    avoid: [
      { id: 'drip-suck', why: 'Conservative management suits adhesional obstruction — not an irreducible, tender hernia.' },
      { id: 'gastrografin', why: 'A contrast challenge delays definitive surgery for a strangulating hernia.' },
      { id: 'laxatives', why: 'Never give laxatives in mechanical obstruction.' },
      { id: 'discharge', why: 'She needs emergency surgery.' },
    ],
  },
  viva: [
    {
      id: 'fem-pos',
      q: 'Where does a femoral hernia lie in relation to the pubic tubercle?',
      options: ['Below and lateral', 'Above and medial', 'Directly over it', 'Above and lateral'],
      correct: 0,
      answer: 'A femoral hernia emerges through the femoral canal below the inguinal ligament, so it lies below and lateral to the pubic tubercle. An inguinal hernia lies above and medial to it (though large femoral hernias can curl up over the ligament).',
      topic: 'Anatomy',
    },
    {
      id: 'fem-strang',
      q: 'Why do femoral hernias strangulate so often?',
      options: ['The femoral ring is narrow and bounded by rigid ligaments', 'They usually contain the bladder', 'They are usually very large', 'They mostly occur in young men'],
      correct: 0,
      answer: 'The femoral ring is small and unyielding — bounded by the inguinal ligament anteriorly, the pectineal (Cooper’s) ligament posteriorly, the lacunar ligament medially and the femoral vein laterally. Up to a third present as emergencies, so they should be repaired promptly even when asymptomatic.',
      topic: 'Anatomy',
    },
    {
      id: 'cardinal',
      q: 'What are the cardinal features of intestinal obstruction, and how does the level change them?',
      answer:
        'Colicky abdominal pain, vomiting, distension and absolute constipation (no flatus). Proximal (high) small-bowel obstruction: early, bilious vomiting, little distension, constipation late. Distal/large-bowel obstruction: early distension and constipation, vomiting late and may become faeculent.',
      topic: 'Clinical features',
    },
    {
      id: 'strangulation',
      q: 'Which features suggest the bowel is strangulated?',
      answer:
        'Pain that becomes constant rather than colicky, localised tenderness/peritonism, fever and tachycardia, a tense, tender, irreducible hernia with red overlying skin, rising lactate and WCC, and on CT reduced bowel-wall enhancement, pneumatosis, mesenteric oedema or free fluid.',
      topic: 'Reasoning',
    },
    {
      id: 'commonest',
      q: 'What is the most common cause of small bowel obstruction in the UK?',
      options: ['Adhesions from previous surgery', 'Hernias', 'Malignancy', 'Crohn’s disease'],
      correct: 0,
      answer: 'Adhesions (about 60–75% in countries with high rates of abdominal surgery). Worldwide — and in patients with no previous surgery — obstructed hernias are the leading cause. That is why the hernial orifices must always be examined.',
      topic: 'Epidemiology',
    },
    {
      id: 'electrolytes',
      q: 'Explain her blood gas and electrolytes.',
      answer:
        'Loss of gastric acid (HCl) in vomit causes a hypochloraemic metabolic alkalosis. Volume depletion drives aldosterone secretion, and the kidney conserves sodium at the expense of potassium (and H⁺) → hypokalaemia and a paradoxical aciduria. The pre-renal AKI reflects dehydration; the raised lactate is a warning sign of ischaemic bowel.',
      topic: 'Physiology',
    },
  ],
  teaching: {
    summary:
      'Distal small bowel obstruction in a frail 83-year-old woman caused by an incarcerated, probably strangulating, right femoral hernia. The Pfannenstiel scar tempts you to call it adhesional obstruction — only examining the hernial orifices reveals the true cause.',
    keyFindings: [
      'Colicky central pain, faeculent vomiting, distension and absolute constipation',
      'Dehydrated: tachycardia 108, BP 104/62, cool peripheries, CRT 3 s, AKI',
      'Distended, tympanic abdomen with tinkling bowel sounds',
      'Tense, tender, irreducible lump below and lateral to the right pubic tubercle',
      'Lactate 2.9 — concern for strangulation',
    ],
    pearls: [
      'Always examine the hernial orifices in abdominal pain — above all in obstruction.',
      'A small femoral hernia in a thin elderly woman is easily missed under clothing.',
      'Adhesional SBO may settle with “drip and suck”; an obstructed hernia will not.',
      'Faeculent vomiting means distal, established obstruction.',
      'Vomiting → hypochloraemic, hypokalaemic metabolic alkalosis.',
    ],
    presentation:
      'Mrs Clarke is an 83-year-old independent woman with a two-day history of colicky central abdominal pain, profuse vomiting that is now faeculent, abdominal distension and absolute constipation. She reports a right groin lump that used to reduce but has been painful and irreducible since yesterday. She had a hysterectomy via a Pfannenstiel incision. On examination she is dehydrated, tachycardic at 108 with a blood pressure of 104/62. Her abdomen is distended and tympanic with tinkling bowel sounds and mild diffuse tenderness, and there is a tense, tender, irreducible 3 cm lump below and lateral to the right pubic tubercle without a cough impulse. Bloods show a pre-renal AKI, hypokalaemia and a metabolic alkalosis with a lactate of 2.9. CT confirms small bowel obstruction secondary to an incarcerated right femoral hernia with features of strangulation. I would resuscitate her with IV fluids, insert an NG tube and urinary catheter, give analgesia, correct potassium, inform my registrar and arrange emergency femoral hernia repair with possible small-bowel resection, with post-operative critical care.',
    references: [
      'Macleod’s Clinical Examination, 14th ed. — Ch. 6: the groin and hernial orifices',
      'Bailey & Love’s Short Practice of Surgery — Intestinal obstruction; Hernias',
      'National Emergency Laparotomy Audit (NELA) standards',
    ],
  },
}

export default c
