import type { CaseDef } from '../../engine/types'
import { CRP, FBC, lab, r, UE, VBG } from './helpers'

const tympanic = (light: 0 | 1, deep: 0 | 1 | 2) => r(light, deep, 'none', { note: 'tympanic' })

const c: CaseDef = {
  id: 'sigmoid-volvulus',
  title: 'Sigmoid volvulus',
  presenting: 'Massive abdominal distension and no bowel motion for 4 days',
  specialty: 'Colorectal',
  exam: 'abdominal',
  difficulty: 2,
  setting: 'Emergency department',
  stem: 'Emergency department. Harold Price, 81, has been sent in from his care home because his abdomen has become hugely swollen. Take a history (his carer is with him), examine him, investigate and manage him.',
  components: ['history', 'exam', 'investigations', 'diagnosis', 'viva'],
  tags: ['distension', 'large bowel obstruction', 'volvulus', 'elderly'],
  patient: {
    name: 'Harold Price',
    title: 'Mr Price',
    age: 81,
    sex: 'male',
    dob: '14/01/1945',
    occupation: 'a retired joiner',
    appearance: {
      sex: 'male',
      age: 81,
      skinTone: 1,
      habitus: 'thin',
      hair: 'short',
      hairColor: 'white',
      eyeColor: 'grey',
      distension: 3,
      distensionType: 'gas',
      umbilicus: 'everted',
      dehydrated: true,
      lines: { cannula: 'left-hand' },
    },
    persona: { mood: 'calm', style: 'brief' },
  },
  vitals: { hr: 102, rhythm: 'regular', sbp: 134, dbp: 76, rr: 20, spo2: 95, temp: 37.2, avpu: 'A', pain: 4 },
  history: {
    opening: { text: 'My belly’s like a drum. I can’t go to the toilet and I can’t pass wind.', cue: 'rests a hand on his tight, swollen abdomen' },
    answers: {
      'gi.distension': 'It’s been getting bigger for three or four days. The carers said it was the biggest they’ve seen.',
      'gi.bowels_last': 'Four days ago, maybe five.',
      'gi.flatus': 'No wind for two days.',
      'gi.constipation': 'I’ve always been bunged up. I take two sachets of the powder every day.',
      'pain.site': { text: 'All over — it’s more uncomfortable than painful.', cue: 'circles the whole abdomen' },
      'pain.onset': 'Gradually over a few days.',
      'pain.character': 'A tight, crampy discomfort.',
      'pain.timing': 'It comes and goes.',
      'pain.severity': 'Four.',
      'pain.previous': 'Something like this happened two years ago. They put a tube up the back passage and it all came out.',
      'gi.nausea': 'A bit queasy.',
      'gi.vomiting': 'Once this morning.',
      'gi.vomit_content': 'Brownish.',
      'gi.stool_blood': 'No blood.',
      'gi.appetite': 'Not eating much.',
      'gi.weight': 'I’ve not lost any weight that I know of.',
      'sys.fever': 'No.',
      'pmh.conditions': 'Parkinson’s disease for ten years. I had a stroke three years ago.',
      'pmh.gi': 'Constipation all my life. The tube up the bottom two years ago.',
      'pmh.surgery': 'None.',
      'dh.meds': 'Co-careldopa, a stool softener, laxative sachets, clopidogrel and a statin.',
      'dh.anticoag': 'Clopidogrel.',
      'dh.allergies': 'None.',
      'sh.living': 'In a residential home. I walk with a frame.',
      'sh.mobility': 'Frame; carers help me wash.',
      'sh.smoking': 'Never.',
      'sh.alcohol': 'None.',
      'comm.questions': 'Is it the same thing as last time?',
    },
    key: [
      'comm.open',
      'gi.distension',
      'gi.bowels_last',
      'gi.flatus',
      'gi.constipation',
      'gi.vomiting',
      'pain.site',
      'pain.severity',
      'pain.previous',
      'gi.stool_blood',
      'gi.weight',
      'pmh.conditions',
      'dh.meds',
      'dh.anticoag',
      'sh.living',
    ],
    critical: ['gi.flatus', 'pain.previous'],
    ideas: 'It’s my bowels again, like before.',
    concerns: 'I don’t want a big operation at my age.',
    expectations: 'If you can let the wind out with the tube like last time, that would be grand.',
    social: { living: 'Residential care home; mobilises with a frame.', smoking: 'Never smoked.', alcohol: 'None.' },
    pmh: 'Parkinson’s disease, previous ischaemic stroke, chronic constipation, sigmoid volvulus decompressed endoscopically 2 years ago.',
  },
  abdo: {
    general: {
      endOfBed:
        'Mr Price is a thin, elderly man with a grossly distended, tense, shiny abdomen that rises out of all proportion to his frame. He has a resting tremor of the right hand. He looks comfortable at rest and is not lying rigidly still.',
    },
    hands: { temperature: 'warm', crt: 2.5, tremor: true },
    face: { mucosa: 'dry', tongue: 'dry-furred' },
    abdomen: {
      shape: 'distended',
      inspectionExtra: 'Gross, asymmetrical distension, most marked on the left and in the upper abdomen; the umbilicus is everted. No scars or visible hernias.',
      movesWithRespiration: 'reduced',
      regions: {
        LIF: tympanic(1, 2),
        LF: tympanic(1, 1),
        UMB: tympanic(0, 1),
        EPI: tympanic(0, 1),
        RUQ: tympanic(0, 1),
        LUQ: tympanic(0, 1),
        RF: tympanic(0, 0),
        RIF: tympanic(0, 1),
        SP: tympanic(0, 1),
      },
      liver: { edgeCm: 0, spanCm: 6 },
      bowelSounds: 'hyperactive',
    },
    completion: { dre: 'Empty rectum with normal tone; no masses, no blood.', urinalysis: 'Normal.' },
  },
  criticalSteps: ['hern.orifices', 'palp.peritonism'],
  investigations: {
    axr: {
      report: 'A massively dilated loop of colon arising from the pelvis and extending up to the right upper quadrant, with the shape of a bent inner tube (‘coffee bean’). Its apex lies under the left hemidiaphragm towards the right. Proximal colon moderately dilated.',
      interpretation: 'Sigmoid volvulus — the coffee-bean sign.',
      abnormal: true,
    },
    'ct-ap': {
      report: 'Twisted sigmoid mesentery (‘whirl sign’) with a closed-loop, massively dilated sigmoid colon (14 cm). The bowel wall enhances normally; no free gas or free fluid.',
      interpretation: 'Sigmoid volvulus without ischaemia or perforation.',
      abnormal: true,
    },
    fbc: { values: FBC(128, 10.8, 8.4, 244), interpretation: 'Mild anaemia; WCC normal.' },
    ue: { values: UE(147, 3.1, 10.6, 128, '46'), interpretation: 'Dehydration with hypokalaemia (worsens ileus).' },
    crp: { values: CRP(24) },
    vbg: { values: VBG(7.4, 26, 0.4, 1.4, 3.1), interpretation: 'Normal lactate — reassuring against ischaemia (not conclusive).' },
    gs: { report: 'Group O RhD positive.' },
    'cxr-erect': { report: 'Raised hemidiaphragms from distension. No free gas.', interpretation: 'No perforation.' },
    flexi: {
      report: 'Twisted mucosa at 22 cm; the scope passed through the twist with a rush of gas and liquid stool. Mucosa beyond is pink and viable. Flatus tube left in situ.',
      interpretation: 'Successful endoscopic decompression; viable mucosa.',
      abnormal: true,
    },
    calcium: { values: [lab('Adjusted calcium', '2.31', 'mmol/L', '2.20–2.60')] },
  },
  investigationRubric: {
    essential: [
      { id: 'axr', why: 'The coffee-bean sign is often diagnostic.' },
      { id: 'ct-ap', why: 'Confirms the volvulus and looks for ischaemia or perforation before decompression.' },
      { id: 'fbc', why: 'Baseline; leucocytosis suggests ischaemia.' },
      { id: 'ue', why: 'Dehydration and low potassium.' },
      { id: 'vbg', why: 'Lactate.' },
      { id: 'gs', why: 'In case of surgery.' },
    ],
    helpful: [
      { id: 'cxr-erect', why: 'Free gas = perforation.' },
      { id: 'crp', why: 'Baseline.' },
      { id: 'flexi', why: 'Diagnostic and therapeutic.' },
      { id: 'calcium', why: 'Electrolytes that worsen dysmotility.' },
    ],
    avoid: [{ id: 'colonoscopy', why: 'Full bowel prep is impossible and dangerous in obstruction — flexible sigmoidoscopy decompresses.' }],
  },
  diagnosis: {
    correct: 'sigmoid-volvulus',
    differentials: ['pseudo-obstruction', 'lbo-cancer', 'caecal-volvulus', 'constipation', 'sbo-adhesions'],
  },
  management: {
    essential: [
      { id: 'abcde', why: 'Systematic assessment.' },
      { id: 'iv-access', why: 'Access and bloods.' },
      { id: 'fluids', why: 'Dehydrated.' },
      { id: 'maintenance-fluids', why: 'Replace potassium.' },
      { id: 'nbm', why: 'Bowel obstruction.' },
      { id: 'catheter', why: 'Fluid balance.' },
      { id: 'senior', why: 'Registrar review.' },
      { id: 'flexi-decompression', why: '!Endoscopic decompression with a flatus tube — first line when there is no peritonitis or ischaemia.' },
      { id: 'elective-sigmoid', why: 'Recurrence is common (up to ~60%) — this is his second episode; discuss elective sigmoid colectomy if fit, or a percutaneous endoscopic colostomy if not.' },
    ],
    helpful: [
      { id: 'ng', why: 'If vomiting.' },
      { id: 'vte', why: 'Immobile and unwell (hold off until endoscopy is done if bleeding concerns).' },
      { id: 'analgesia', why: 'Comfort.' },
      { id: 'consent', why: 'Endoscopic decompression.' },
    ],
    avoid: [
      { id: 'laxatives', why: 'Oral laxatives in an obstructed colon do harm.' },
      { id: 'discharge', why: 'Obstructed.' },
      { id: 'laparotomy', why: 'Only if peritonitis, ischaemia, perforation or failed decompression (then Hartmann’s procedure).' },
    ],
  },
  viva: [
    {
      id: 'who',
      q: 'Who gets sigmoid volvulus, and why?',
      answer: 'Elderly, often institutionalised people with chronic constipation, neurological disease (Parkinson’s, stroke), psychiatric illness and laxative or anticholinergic use. A long, redundant sigmoid on a narrow mesentery twists around its axis, making a closed loop.',
      topic: 'Pathology',
    },
    {
      id: 'xray',
      q: 'Describe the classic abdominal X-ray.',
      options: ['A dilated inverted-U ‘coffee bean’ loop rising from the pelvis', 'A gasless abdomen', 'Free gas under the diaphragm', 'Dilated small bowel with valvulae conniventes only'],
      correct: 0,
      answer: 'A hugely dilated, inverted-U loop without haustra rising from the pelvis towards the right upper quadrant — the coffee-bean (or bent inner-tube) sign. A caecal volvulus instead points to the left upper quadrant.',
      topic: 'Imaging',
    },
    {
      id: 'when-op',
      q: 'When is emergency surgery needed?',
      answer: 'Peritonitis, perforation, ischaemic or gangrenous mucosa at endoscopy, or failed decompression — usually a Hartmann’s procedure (sigmoid colectomy with end colostomy).',
      topic: 'Management',
    },
    {
      id: 'percussion',
      q: 'How do you tell gas distension from ascites on examination?',
      answer: 'Gas: tympanic percussion everywhere, no shifting dullness, often visible peristalsis. Ascites: dull in the flanks with central resonance, and shifting dullness. Remember the 5 Fs: fat, fluid, flatus, faeces, fetus (± a large mass).',
      topic: 'Examination',
    },
  ],
  teaching: {
    summary:
      'Sigmoid volvulus in an elderly man with Parkinson’s disease and chronic constipation: gross, tympanic, relatively painless distension with absolute constipation, a coffee-bean loop on X-ray and a whirl sign on CT; decompressed endoscopically, with elective sigmoid colectomy to discuss because it recurs.',
    keyFindings: [
      'Four days of progressive distension, no flatus for two days, one vomit',
      'Parkinson’s disease, stroke, lifelong constipation, a previous episode decompressed endoscopically',
      'Gross, tense, asymmetrical tympanic distension; mild tenderness, no peritonism; empty rectum',
      'AXR: coffee-bean sign; CT: whirl sign, viable bowel',
      'Normal lactate; hypokalaemia',
    ],
    pearls: [
      'Distension out of proportion to pain in an elderly, institutionalised patient — think volvulus or pseudo-obstruction.',
      'Check the hernial orifices and do a rectal examination in every obstruction.',
      'Peritonism, fever, tachycardia or a raised lactate mean possible ischaemia: CT first and senior review.',
      'Over half recur after decompression alone.',
    ],
    presentation:
      'Mr Price is an 81-year-old care-home resident with Parkinson’s disease, a previous stroke and lifelong constipation who presents with four days of progressive abdominal distension, no bowel movement for four days and no flatus for two, with one vomit and only mild crampy discomfort. He had a similar episode two years ago treated endoscopically. He is mildly tachycardic and dehydrated. His abdomen is grossly and asymmetrically distended and tympanic, with mild tenderness but no peritonism, and the rectum is empty. The abdominal X-ray shows a coffee-bean sign and CT confirms a sigmoid volvulus with viable bowel. I would resuscitate him with IV fluids and potassium, keep him nil by mouth, and arrange flexible sigmoidoscopic decompression with a flatus tube; as this is a recurrence, I would discuss elective sigmoid colectomy with him and his family.',
    references: ['Macleod’s Clinical Examination, 14th ed. — Ch. 6: abdominal distension (the five Fs) and percussion', 'ASCRS clinical practice guidelines for colonic volvulus'],
  },
}

export default c
