import type { CaseDef } from '../../engine/types'
import { CRP, FBC, lab, r, UE, VBG } from './helpers'

const c: CaseDef = {
  id: 'strangulated-inguinal',
  title: 'Strangulated right inguinoscrotal hernia with small bowel obstruction',
  presenting: 'Painful lump in the groin that won’t go back',
  specialty: 'Hernia & abdominal wall',
  exam: 'abdominal',
  difficulty: 2,
  setting: 'Emergency department',
  stem: 'Emergency department. Arthur Bennett, 74, has a painful swelling in his right groin and has been vomiting. Take a history, examine his abdomen and hernial orifices, investigate and manage him.',
  components: ['history', 'exam', 'investigations', 'diagnosis', 'viva'],
  tags: ['hernia', 'strangulation', 'bowel obstruction', 'emergency'],
  patient: {
    name: 'Arthur Bennett',
    title: 'Mr Bennett',
    age: 74,
    sex: 'male',
    dob: '02/11/1951',
    occupation: 'a retired postman',
    appearance: {
      sex: 'male',
      age: 74,
      skinTone: 1,
      habitus: 'average',
      hair: 'bald',
      hairColor: 'white',
      eyeColor: 'blue',
      distension: 1,
      distensionType: 'gas',
      hernias: [{ kind: 'inguinal-indirect', side: 'right', size: 'large', visible: 'always', tense: true, irreducible: true }],
      dehydrated: true,
      sweaty: true,
      pallor: 0.15,
      lines: { cannula: 'right-hand' },
    },
    persona: { mood: 'distressed', style: 'normal' },
  },
  vitals: { hr: 112, rhythm: 'regular', sbp: 128, dbp: 78, rr: 22, spo2: 96, temp: 37.9, avpu: 'A', pain: 8 },
  history: {
    opening: { text: 'My rupture’s come down and it won’t go back. It’s agony, and I’ve been sick all afternoon.', cue: 'grimaces, hand over his right groin' },
    answers: {
      'pain.site': { text: 'The lump in my right groin — and now my whole belly is crampy.', cue: 'points to a swelling running into the right side of the scrotum' },
      'pain.onset': 'I was lifting a bag of compost this morning, about ten hours ago. It popped out and wouldn’t go back.',
      'pain.character': 'The lump is a constant, tight, burning pain. The belly comes in waves.',
      'pain.timing': 'The lump is constant. The cramps come every few minutes.',
      'pain.severity': 'Eight out of ten.',
      'pain.exacerbating': 'Touching it. Coughing.',
      'pain.relieving': 'Nothing.',
      'pain.previous': 'The lump’s been there three years. It always went back when I lay down — until today.',
      'lump.when': 'About three years ago.',
      'lump.reduce': 'It always used to go back lying down or with a push. Not today — I tried.',
      'lump.change': 'It’s got bigger over the years and now goes into my scrotum.',
      'lump.cough': 'It used to get bigger when I coughed.',
      'lump.skin': 'It’s gone red over the top.',
      'gi.nausea': 'Yes.',
      'gi.vomiting': 'Four or five times since lunchtime.',
      'gi.vomit_content': 'Green stuff now.',
      'gi.bowels_last': 'Yesterday morning.',
      'gi.flatus': 'No wind since this morning.',
      'gi.distension': 'My belly feels blown up.',
      'sys.fever': 'Hot and cold.',
      'pmh.conditions': 'High blood pressure. COPD — I get puffed.',
      'pmh.surgery': 'Nothing. They offered to fix the hernia two years ago but I was nervous.',
      'pmh.heart': 'No.',
      'dh.meds': 'Amlodipine, my inhalers, and aspirin.',
      'dh.anticoag': 'Just aspirin.',
      'dh.allergies': 'None.',
      'sh.smoking': 'Forty years of twenty a day; I stopped five years ago.',
      'sh.alcohol': 'A pint on Sunday.',
      'sh.living': 'With my wife. I garden and walk the dog.',
      'pre.last_meal': 'Breakfast at eight — porridge.',
      'comm.questions': 'Will I need an operation tonight?',
    },
    key: [
      'comm.open',
      'pain.site',
      'pain.onset',
      'pain.character',
      'pain.severity',
      'lump.when',
      'lump.reduce',
      'lump.skin',
      'gi.vomiting',
      'gi.vomit_content',
      'gi.bowels_last',
      'gi.flatus',
      'pmh.conditions',
      'dh.anticoag',
      'dh.allergies',
      'pre.last_meal',
    ],
    critical: ['lump.reduce', 'gi.flatus'],
    ideas: 'I think the rupture’s got stuck.',
    concerns: 'I’ve heard the bowel can die if it’s trapped.',
    expectations: 'Please sort it out — whatever it takes.',
    social: { smoking: 'Ex-smoker, 40 pack-years.', alcohol: 'A pint a week.', living: 'With his wife; independent.' },
    pmh: 'Hypertension, COPD.',
    allergies: 'None.',
  },
  abdo: {
    general: {
      endOfBed:
        'Mr Bennett is lying still on the trolley, sweaty and in obvious pain, with a vomit bowl of bile-stained fluid beside him. His abdomen looks mildly distended, and there is a large red swelling in the right groin running into the scrotum.',
    },
    hands: { temperature: 'cool', crt: 3, tarStaining: true },
    face: { mucosa: 'dry', tongue: 'dry-furred' },
    abdomen: {
      shape: 'distended',
      regions: {
        RIF: r(2, 3, 'voluntary'),
        SP: r(1, 2),
        UMB: r(1, 2),
        LIF: r(0, 1),
        RF: r(1, 1),
      },
      bowelSounds: 'tinkling',
      hernias: {
        rightInguinal: {
          present: true,
          description:
            'A 9 × 6 cm tense, very tender swelling arising above and medial to the right pubic tubercle and extending into the scrotum; you cannot get above it. The overlying skin is red and warm. There is no cough impulse and it is irreducible.',
          coughImpulse: false,
          reducible: false,
          tender: true,
        },
      },
    },
    completion: {
      genitalia: 'Both testes are palpable separately below the swelling; the right is pushed down but normal.',
      dre: 'Empty rectum.',
      urinalysis: 'Ketones +.',
    },
  },
  criticalSteps: ['hern.orifices'],
  investigations: {
    fbc: { values: FBC(151, 16.4, 14.2, 301), interpretation: 'Neutrophil leucocytosis.' },
    crp: { values: CRP(96), interpretation: 'Raised.' },
    ue: { values: UE(136, 5.1, 11.8, 138, '44'), interpretation: 'AKI from vomiting and third-space losses.' },
    vbg: { values: VBG(7.31, 20, -4.6, 3.6, 5.1), interpretation: 'Metabolic acidosis with a raised lactate — suggests ischaemic bowel.' },
    lactate: { values: [lab('Lactate', '3.6', 'mmol/L', '0.5–2.0', 'H')], interpretation: 'Raised — strangulation likely.' },
    gs: { report: 'Group A RhD positive. Antibody screen negative.' },
    ecg: { report: 'Sinus tachycardia 112 bpm. No acute changes.' },
    coag: { values: [lab('INR', 1.1, '', '0.8–1.2'), lab('APTT', 30, 's', '25–35')] },
    axr: { report: 'Multiple dilated small bowel loops centrally with valvulae conniventes; a gas-filled loop overlies the right groin.', interpretation: 'Small bowel obstruction.', abnormal: true },
    'ct-ap': {
      report: 'Dilated small bowel loops proximal to a right inguinal hernia containing a thick-walled, poorly enhancing loop of ileum with free fluid in the sac.',
      interpretation: 'Obstructed right inguinal hernia with features of strangulation. (Not needed when the diagnosis is clinically obvious.)',
      abnormal: true,
    },
    'cxr-erect': { report: 'Hyperexpanded lungs (COPD). No free gas.' },
  },
  investigationRubric: {
    essential: [
      { id: 'fbc', why: 'Leucocytosis.' },
      { id: 'ue', why: 'AKI and potassium after vomiting.' },
      { id: 'vbg', why: 'Lactate — raised in ischaemic bowel.' },
      { id: 'gs', why: 'Emergency theatre.' },
      { id: 'ecg', why: 'Pre-operative; 74 with COPD.' },
    ],
    helpful: [
      { id: 'crp', why: 'Baseline.' },
      { id: 'coag', why: 'Pre-operative.' },
      { id: 'axr', why: 'Confirms obstruction — but should not delay theatre.' },
      { id: 'cxr-erect', why: 'Pre-operative baseline in COPD.' },
    ],
    avoid: [{ id: 'us-groin', why: 'Delays surgery — a strangulated hernia is a clinical diagnosis.' }],
  },
  diagnosis: {
    correct: 'strangulated-hernia',
    accept: ['sbo-hernia', 'indirect-ih'],
    differentials: ['femoral-hernia', 'testicular-torsion', 'inguinal-lymph', 'hydrocele', 'sbo-adhesions'],
  },
  management: {
    essential: [
      { id: 'abcde', why: 'Septic and dehydrated.' },
      { id: 'fluids', why: 'Resuscitate before theatre.' },
      { id: 'analgesia', why: 'IV opioid.' },
      { id: 'nbm', why: 'Theatre.' },
      { id: 'ng', why: 'Decompress the obstructed bowel; reduces aspiration risk at induction.' },
      { id: 'catheter', why: 'Fluid balance.' },
      { id: 'abx-iv', why: 'Likely ischaemic bowel.' },
      { id: 'senior', why: 'Registrar now.' },
      { id: 'hernia-emergency', why: '!Emergency hernia repair: inspect the bowel, resect if non-viable; mesh only if the field is clean.' },
      { id: 'theatre', why: 'Emergency list (NCEPOD category 1–2).' },
    ],
    helpful: [
      { id: 'consent', why: 'Including possible bowel resection or laparotomy.' },
      { id: 'iv-access', why: 'Two cannulae.' },
      { id: 'vte', why: 'Post-operatively.' },
      { id: 'fluid-balance', why: 'Strict input and output.' },
    ],
    avoid: [
      { id: 'taxis', why: 'Never force reduction of a tense, red, tender hernia — you may push dead bowel back into the abdomen or reduce it ‘en masse’ inside its sac.' },
      { id: 'discharge', why: 'Surgical emergency.' },
      { id: 'drip-suck', why: 'Conservative treatment is for adhesional obstruction, not a strangulated hernia.' },
    ],
  },
  viva: [
    {
      id: 'define',
      q: 'Define irreducible, obstructed and strangulated hernias.',
      answer: 'Irreducible (incarcerated): the contents cannot be returned. Obstructed: bowel in the sac is blocked (vomiting, distension, absolute constipation). Strangulated: the blood supply to the contents is cut off — ischaemia, then gangrene and perforation. It is a surgical emergency.',
      topic: 'Definitions',
    },
    {
      id: 'tell',
      q: 'How do you tell an inguinal from a femoral hernia at the bedside?',
      options: ['Relation to the pubic tubercle: inguinal above and medial, femoral below and lateral', 'Femoral hernias always reduce', 'Inguinal hernias never reach the scrotum', 'Only femoral hernias have a cough impulse'],
      correct: 0,
      answer: 'Find the pubic tubercle: an inguinal hernia emerges above and medial to it, a femoral hernia below and lateral (Macleod’s, Ch. 6). Only an inguinal hernia reaches the scrotum.',
      topic: 'Examination',
    },
    {
      id: 'signs',
      q: 'Which signs suggest strangulation?',
      answer: 'Local: a tense, very tender, irreducible lump with red, hot skin and no cough impulse. Systemic: tachycardia, fever, raised WCC and lactate, and signs of obstruction or peritonitis. Pain that has changed from intermittent to constant is a warning.',
      topic: 'Signs',
    },
    {
      id: 'viable',
      q: 'At operation, how is bowel viability judged?',
      answer: 'Colour (pink, not black or green), sheen, peristalsis, and pulsation in the mesentery; warm saline packs for 5–10 minutes after releasing the constriction. Non-viable bowel is resected.',
      topic: 'Operations',
    },
  ],
  teaching: {
    summary:
      'Strangulated right indirect inguinoscrotal hernia in a 74-year-old: a long-standing reducible hernia became irreducible after lifting, with a tense, red, tender lump above and medial to the pubic tubercle, no cough impulse, obstruction and a raised lactate.',
    keyFindings: [
      'Three-year reducible right groin hernia; irreducible for 10 hours after lifting',
      'Bilious vomiting, colicky pain, no flatus since the morning',
      'Tense, red, very tender swelling above and medial to the pubic tubercle into the scrotum; no cough impulse',
      'HR 112, temp 37.9, WCC 16.4, lactate 3.6, AKI',
      'Tinkling bowel sounds, mild distension',
    ],
    pearls: [
      'Examine the hernial orifices in every patient with obstruction.',
      'Red skin, tenderness and systemic upset mean strangulation — do not try to reduce it.',
      'A long-standing hernia that is now irreducible and painful needs surgery tonight.',
      'Reduction en masse: the hernia disappears but the bowel stays strangled inside its sac.',
    ],
    presentation:
      'Mr Bennett is a 74-year-old retired postman with a three-year history of a reducible right inguinal hernia who presents 10 hours after it became irreducible while lifting, with constant pain in the lump, colicky abdominal pain, bilious vomiting and no flatus. He has COPD and hypertension and takes aspirin. He is tachycardic at 112, febrile at 37.9 and dehydrated. There is a tense, very tender, red, irreducible swelling above and medial to the right pubic tubercle extending into the scrotum, with no cough impulse; the abdomen is mildly distended with tinkling bowel sounds. WCC is 16, lactate 3.6 and he has an AKI. This is a strangulated inguinal hernia with small bowel obstruction. I would resuscitate him, pass an NG tube and catheter, give analgesia and antibiotics, and arrange emergency hernia repair with assessment of the bowel and resection if non-viable.',
    references: ['Macleod’s Clinical Examination, 14th ed. — Ch. 6: hernias and the groin (pp. 110–111)', 'World Society of Emergency Surgery guidelines on incarcerated and strangulated hernias'],
  },
}

export default c
