import type { CaseDef } from '../../engine/types'

const c: CaseDef = {
  id: 'testicular-torsion',
  title: 'Left testicular torsion',
  presenting: 'Sudden severe left testicular pain',
  specialty: 'Urology',
  exam: 'scrotal',
  difficulty: 2,
  setting: 'Emergency department',
  stem: 'Emergency department. Ethan Brooks, 15, woke three hours ago with severe pain in his left testicle. His mother is with him. Take a focused history, examine him (with a chaperone) and decide on management.',
  components: ['history', 'exam', 'investigations', 'diagnosis', 'viva'],
  tags: ['acute scrotum', 'emergency', 'time-critical', 'cremasteric reflex'],
  patient: {
    name: 'Ethan Brooks',
    title: 'Ethan',
    age: 15,
    sex: 'male',
    dob: '22/01/2011',
    occupation: 'a Year 10 student',
    appearance: { sex: 'male', age: 15, skinTone: 1, habitus: 'thin', hair: 'short', hairColor: 'blonde', eyeColor: 'blue', sweaty: true, pallor: 0.25 },
    persona: { mood: 'distressed', style: 'brief' },
  },
  vitals: { hr: 108, rhythm: 'regular', sbp: 128, dbp: 76, rr: 20, spo2: 99, temp: 37.1, avpu: 'A', pain: 9 },
  bedside: { vomitBowl: 'clear' },
  visual: { scrotum: { side: 'left', kind: 'torsion', size: 2, erythema: 0.6, highRiding: true } },
  history: {
    opening: { text: 'My left ball… it really, really hurts. It woke me up.', cue: 'lies curled on his side, holding his groin' },
    answers: {
      'pain.site': 'The left testicle — and it goes up into my tummy.',
      'pain.onset': 'Suddenly, about three hours ago. It woke me up at five.',
      'pain.character': 'A horrible, deep, sickening pain.',
      'pain.radiation': 'Up into the lower left side of my tummy.',
      'pain.severity': 'Nine out of ten.',
      'pain.previous': 'I had a short twinge like this a few weeks ago but it went away after ten minutes.',
      'gi.nausea': 'I feel really sick.',
      'gi.vomiting': 'I’ve been sick twice.',
      'scr.trauma': 'No, I didn’t hurt it.',
      'scr.swelling': 'It looks swollen and red.',
      'scr.discharge': 'No.',
      'gu.dysuria': 'No stinging when I wee.',
      'gu.frequency': 'No.',
      'sys.fever': 'No fever.',
      'sx.sexual': 'No, I’ve never had sex.',
      'pmh.conditions': 'Nothing.',
      'pmh.surgery': 'Never had an operation.',
      'dh.meds': 'Nothing.',
      'dh.allergies': 'No allergies.',
      'pre.last_meal': 'Dinner last night at about seven.',
      'comm.questions': 'Will I need an operation? Will it be OK?',
    },
    key: ['comm.open', 'pain.site', 'pain.onset', 'pain.radiation', 'pain.severity', 'pain.previous', 'gi.vomiting', 'scr.trauma', 'gu.dysuria', 'sys.fever', 'sx.sexual', 'pre.last_meal', 'dh.allergies'],
    critical: ['pain.onset'],
    ideas: 'I don’t know — is something twisted?',
    concerns: 'That I’ll lose it.',
    expectations: 'Please make the pain stop.',
  },
  keyed: {
    'comm.pain': { text: '', says: 'Please be careful — the left side is agony.', reaction: 0.4 },
    'comm.chaperone': { text: 'You offer a chaperone; his mother and a nurse are present.', says: 'Yes, Mum can stay.' },
    'scr.gloves': { text: 'Gloves on.' },
    'scr.inspect': {
      text: 'The left hemiscrotum is red and swollen. The left testis lies HIGHER than the right, with a horizontal lie. The right testis hangs normally with a vertical lie.',
      abnormal: true,
      meaning: 'A high-riding testis with a horizontal lie (the “bell-clapper” deformity) is the classic sign of torsion.',
    },
    'scr.normal': { text: 'The right testis is normal: smooth, non-tender, normal size, vertical lie.' },
    'scr.affected': { text: 'The left testis is exquisitely tender, swollen and high in the scrotum. He pulls away.', abnormal: true, reaction: 1, says: 'Aaah! Stop — please!' },
    'scr.epididymis': { text: 'The epididymis is difficult to define because of swelling and tenderness; it may lie anteriorly.', abnormal: true, reaction: 0.8 },
    'scr.cord': { text: 'The left cord feels thickened and tender.', abnormal: true, reaction: 0.7 },
    'scr.getAbove': { text: 'You can get above the swelling — it is scrotal.' },
    'scr.separate': { text: 'The swelling is the testis itself.' },
    'scr.transilluminate': { text: 'It does not transilluminate.' },
    'scr.cough': { text: 'No cough impulse.' },
    'scr.lie': { text: 'He lies back; the pain is unchanged. Lifting the testis does not relieve the pain (negative Prehn’s sign).', abnormal: true, meaning: 'Prehn’s sign is unreliable — never use it to exclude torsion.' },
    'scr.cremasteric': { text: 'The cremasteric reflex is ABSENT on the left (present on the right).', abnormal: true, meaning: 'An absent cremasteric reflex strongly supports torsion.' },
    'scr.nodes': { text: 'No inguinal lymphadenopathy.' },
    'complete.abdomen': { text: 'Mild left iliac fossa tenderness (referred pain); abdomen otherwise soft. Hernial orifices clear.' },
  },
  criticalSteps: ['prep.chaperone', 'in.inspect', 'sp.crem'],
  investigations: {
    'urine-dip': { report: 'Negative for leucocytes, nitrites and blood.', interpretation: 'No evidence of infection — makes epididymo-orchitis less likely (but never delay surgery for tests).' },
    'us-scrotal': { report: 'Left testis enlarged and hypoechoic with ABSENT colour Doppler flow; “whirlpool” sign of the spermatic cord. Right testis normal.', interpretation: 'Left testicular torsion — but this scan delayed theatre by over an hour.', abnormal: true },
  },
  investigationRubric: {
    essential: [],
    helpful: [{ id: 'urine-dip', why: 'Quick bedside test — but must not delay surgery.' }],
    avoid: [{ id: 'us-scrotal', why: '!Torsion is a clinical diagnosis: ultrasound delays theatre and a normal scan does not exclude torsion. Explore urgently.' }],
  },
  diagnosis: { correct: 'testicular-torsion', differentials: ['epididymo-orchitis', 'torsion-hydatid', 'strangulated-hernia', 'testicular-tumour', 'renal-colic'] },
  management: {
    essential: [
      { id: 'scrotal-exploration', why: '!Emergency scrotal exploration: salvage is ~90% within 6 hours of onset, falling sharply after that. Bilateral fixation (orchidopexy).' },
      { id: 'urology', why: 'Immediate senior urology/paediatric surgery review.' },
      { id: 'analgesia', why: 'Strong analgesia.' },
      { id: 'nbm', why: 'Nil by mouth for theatre.' },
      { id: 'consent', why: 'Consent (with parental involvement) including possible orchidectomy if the testis is non-viable.' },
    ],
    helpful: [{ id: 'antiemetic', why: 'He is vomiting.' }],
    avoid: [
      { id: 'abx-epididymo', why: '!Treating as epididymo-orchitis without excluding torsion risks losing the testis.' },
      { id: 'discharge', why: 'Never discharge an acute scrotum in a teenager without excluding torsion.' },
    ],
  },
  viva: [
    {
      id: 'time',
      q: 'Why is time so critical in testicular torsion?',
      options: ['Infection sets in after 2 hours', 'Testicular salvage falls from ~90% within 6 hours to < 10% after 24 hours', 'The pain always resolves after 12 hours', 'Because antibiotics are needed within the hour'],
      correct: 1,
      answer: 'Twisting of the spermatic cord cuts off the venous then arterial supply. Salvage rates are about 90% if detorsed within 6 hours, about 50% at 12 hours, and under 10% after 24 hours. Hence: suspect → theatre, without waiting for imaging.',
      topic: 'Pathophysiology',
    },
    {
      id: 'bellclapper',
      q: 'What anatomical abnormality predisposes to intravaginal torsion, and why is the other side fixed too?',
      answer: 'The “bell-clapper” deformity: the tunica vaginalis attaches high on the spermatic cord, so the testis hangs freely and can rotate. It is usually bilateral, so the contralateral testis is fixed at the same operation to prevent future torsion.',
      topic: 'Anatomy',
    },
    {
      id: 'ddx',
      q: 'How can torsion of the hydatid of Morgagni be distinguished clinically?',
      answer: 'Usually in pre-pubertal boys, with more gradual pain localised to the upper pole, a tender nodule there that may show as a “blue dot” through the skin, and a normal cremasteric reflex and testicular lie. If in doubt, explore — it is managed the same way when uncertain.',
      topic: 'Differentials',
    },
  ],
  teaching: {
    summary:
      'A teenager with sudden severe testicular pain waking him from sleep, vomiting, a high-riding horizontally lying exquisitely tender testis and an absent cremasteric reflex — testicular torsion. This is a surgical emergency: take him to theatre for exploration and bilateral fixation without delaying for ultrasound.',
    keyFindings: ['Sudden onset, woke from sleep; previous brief episode', 'Vomiting; pain radiating to the lower abdomen', 'High-riding, horizontal, exquisitely tender left testis', 'Absent cremasteric reflex; negative urine dip'],
    pearls: [
      'Torsion is a clinical diagnosis — don’t let imaging delay theatre.',
      'Previous short-lived episodes (intermittent torsion) are a warning sign.',
      'Always examine the testes in a boy with lower abdominal pain.',
      'Examine the normal side first, and gently.',
    ],
    presentation:
      'I examined Ethan Brooks, a 15-year-old boy, with his mother and a nurse chaperone present. He was in severe pain and tachycardic at 108. The left hemiscrotum was red and swollen, and the left testis was lying higher than the right with a horizontal lie. The right testis was normal. The left testis was exquisitely tender and swollen, the cord was thickened and tender, and the cremasteric reflex was absent on the left. It did not transilluminate and there was no cough impulse. In the context of sudden-onset pain waking him from sleep with vomiting, this is left testicular torsion until proven otherwise. He needs immediate urology review and emergency scrotal exploration with bilateral orchidopexy — I would not delay for an ultrasound.',
    references: ['Macleod’s Clinical Examination, 14th ed. — Ch. 15: The reproductive system (male genitalia)', 'BAUS / NICE CKS: Scrotal pain and swelling', 'EAU Paediatric Urology Guidelines'],
  },
}

export default c
