import type { CaseDef } from '../../engine/types'
import { lab } from './helpers'

const c: CaseDef = {
  id: 'testicular-tumour',
  title: 'Left testicular germ cell tumour (seminoma)',
  presenting: 'Painless lump in the left testis',
  specialty: 'Urology',
  exam: 'scrotal',
  difficulty: 2,
  setting: 'Outpatient clinic',
  stem: 'Urology clinic (urgent referral). Marcus Bell, 29, found a lump in his left testicle. Take a history, examine his scrotum with a chaperone, request investigations and discuss the next steps.',
  components: ['history', 'exam', 'investigations', 'diagnosis', 'viva'],
  tags: ['scrotal lump', 'cancer', 'tumour markers', '2WW'],
  patient: {
    name: 'Marcus Bell',
    title: 'Mr Bell',
    age: 29,
    sex: 'male',
    dob: '05/12/1996',
    occupation: 'a personal trainer',
    appearance: { sex: 'male', age: 29, skinTone: 4, habitus: 'average', hair: 'short', hairColor: 'black', eyeColor: 'brown', facialHair: 'beard' },
    persona: { mood: 'anxious', style: 'normal' },
  },
  vitals: { hr: 76, rhythm: 'regular', sbp: 124, dbp: 76, rr: 14, spo2: 99, temp: 36.6, avpu: 'A', pain: 1 },
  visual: { scrotum: { side: 'left', kind: 'tumour', size: 2 } },
  history: {
    opening: 'I found a lump on my left testicle about six weeks ago. It doesn’t hurt, but it hasn’t gone away.',
    answers: {
      'lump.when': 'About six weeks ago, in the shower.',
      'lump.change': 'I think it’s a bit bigger, and the whole testicle feels heavier.',
      'lump.pain': 'Not painful — maybe a dull ache now and then.',
      'scr.heaviness': 'Yes, a dragging, heavy feeling on the left.',
      'scr.trauma': 'No injury that I know of.',
      'scr.discharge': 'No.',
      'gu.dysuria': 'No.',
      'sys.fever': 'No fevers.',
      'gi.weight': 'No weight loss.',
      'ros.cough': 'No cough.',
      'ros.sob': 'No breathlessness.',
      'ros.joints': 'No back pain.',
      'pmh.conditions': 'I had an operation as a toddler because my left testicle hadn’t come down.',
      'pmh.surgery': 'An orchidopexy on the left side when I was two.',
      'dh.meds': 'Nothing.',
      'dh.allergies': 'No allergies.',
      'fh.cancer': 'My brother had testicular cancer at twenty-five.',
      'sx.sexual': 'I’m in a relationship. We want children in the future.',
      'sh.smoking': 'I don’t smoke.',
      'comm.questions': 'Is it cancer? Will I still be able to have kids?',
    },
    key: ['comm.open', 'lump.when', 'lump.change', 'lump.pain', 'scr.heaviness', 'scr.trauma', 'gi.weight', 'ros.cough', 'ros.joints', 'pmh.surgery', 'fh.cancer', 'sx.sexual'],
    critical: ['pmh.surgery', 'fh.cancer'],
    ideas: 'I’m worried it’s cancer — my brother had it.',
    concerns: 'Cancer, and being able to have children.',
    expectations: 'To be told honestly what happens next.',
  },
  keyed: {
    'comm.pain': { text: '', says: 'It’s not really painful.' },
    'scr.gloves': { text: 'Gloves on.' },
    'scr.inspect': { text: 'The left hemiscrotum looks slightly fuller than the right. Normal skin. A faint scar in the left groin (previous orchidopexy).', abnormal: true, meaning: 'The orchidopexy scar is a clue: undescended testis is the main risk factor for testicular cancer.' },
    'scr.normal': { text: 'The right testis is normal: smooth, rubbery, about 4.5 cm long.' },
    'scr.affected': {
      text: 'The left testis is enlarged, with a hard, irregular, non-tender mass in its lower pole. The mass cannot be separated from the testis.',
      abnormal: true,
      meaning: 'A hard, painless lump arising from the testis is cancer until proven otherwise.',
    },
    'scr.epididymis': { text: 'The epididymis is normal and separate from the mass.' },
    'scr.cord': { text: 'Normal cord; vas palpable.' },
    'scr.getAbove': { text: 'You can get above the swelling.' },
    'scr.separate': { text: 'The mass is part of the testis — not separate from it.', abnormal: true },
    'scr.transilluminate': { text: 'It does not transilluminate.', abnormal: true, meaning: 'Solid lesion.' },
    'scr.cough': { text: 'No cough impulse.' },
    'scr.lie': { text: 'No change lying down.' },
    'scr.cremasteric': { text: 'Cremasteric reflexes present.' },
    'scr.nodes': { text: 'No inguinal lymphadenopathy.', meaning: 'The testis drains to the para-aortic nodes, not the inguinal nodes (unless the scrotal skin is involved or after scrotal surgery).' },
    'complete.abdomen': { text: 'No palpable para-aortic mass, no hepatomegaly. No gynaecomastia. No supraclavicular nodes.' },
  },
  criticalSteps: ['prep.chaperone', 'pa.normal', 'pa.separate'],
  investigations: {
    'us-scrotal': { report: 'Left testis: 28 mm well-defined, homogeneous hypoechoic intratesticular mass with increased vascularity. Right testis normal; no microlithiasis.', interpretation: 'Intratesticular mass — highly suspicious of a germ cell tumour (seminoma appearance).', abnormal: true },
    'testis-markers': {
      values: [lab('AFP', '4', 'kU/L', '< 10'), lab('β-hCG', '14', 'IU/L', '< 5', 'H'), lab('LDH', '312', 'U/L', '135–225', 'H')],
      interpretation: 'Mildly raised β-hCG and LDH with a normal AFP — consistent with seminoma (a raised AFP would indicate a non-seminomatous component).',
      abnormal: true,
    },
    'ct-cap': { report: 'No retroperitoneal lymphadenopathy. No pulmonary or liver metastases.', interpretation: 'Stage I disease.' },
  },
  investigationRubric: {
    essential: [
      { id: 'us-scrotal', why: '!Confirms an intratesticular mass.' },
      { id: 'testis-markers', why: '!AFP, β-hCG and LDH before orchidectomy — for diagnosis, staging and follow-up.' },
    ],
    helpful: [{ id: 'ct-cap', why: 'Staging CT of the chest, abdomen and pelvis.' }],
    avoid: [
      { id: 'fna', why: '!Never biopsy a testicular mass through the scrotum — it risks seeding tumour into the scrotal lymphatics.' },
      { id: 'core', why: '!No transscrotal biopsy.' },
    ],
  },
  diagnosis: { correct: 'testicular-tumour', differentials: ['epididymo-orchitis', 'hydrocele', 'epididymal-cyst', 'varicocele'] },
  management: {
    essential: [
      { id: '2ww', why: 'Urgent suspected-cancer referral (NICE NG12: non-painful enlargement or change in shape/texture of the testis).' },
      { id: 'orchidectomy-inguinal', why: '!Radical INGUINAL orchidectomy with early clamping of the cord — never a scrotal approach.' },
      { id: 'mdt', why: 'Testicular cancer MDT: staging and adjuvant treatment decisions.' },
    ],
    helpful: [
      { id: 'breaking-news', why: 'Explain honestly and sensitively: > 95% cure rate for early seminoma.' },
      { id: 'consent', why: 'Offer sperm banking before surgery and any chemotherapy; offer a testicular prosthesis.' },
    ],
    avoid: [{ id: 'scrotal-biopsy', why: '!Scrotal violation changes lymphatic drainage and worsens staging/outcome.' }],
  },
  viva: [
    {
      id: 'inguinal',
      q: 'Why is orchidectomy performed through an inguinal rather than a scrotal incision?',
      options: [
        'Cosmetic reasons',
        'To avoid seeding tumour into the scrotal skin and its inguinal lymphatic drainage, and to clamp the cord high',
        'Because the inguinal approach is quicker',
        'To allow a hernia repair at the same time',
      ],
      correct: 1,
      answer: 'The testis drains to the para-aortic nodes; the scrotal skin drains to the inguinal nodes. A scrotal approach (or biopsy) risks tumour spillage into a new lymphatic territory. The inguinal approach allows early high clamping and division of the spermatic cord at the deep ring.',
      topic: 'Surgery',
    },
    {
      id: 'markers',
      q: 'Which tumour markers are raised in which testicular tumours?',
      answer: 'Seminoma: AFP normal (a raised AFP means a non-seminomatous component), β-hCG may be mildly raised, LDH raised with bulk. Non-seminomatous germ cell tumours: AFP (yolk sac elements) and/or β-hCG (choriocarcinoma elements) often raised. LDH reflects tumour burden. Markers are used for diagnosis, prognosis and surveillance.',
      topic: 'Investigations',
    },
    {
      id: 'risk',
      q: 'What are the risk factors for testicular cancer?',
      answer: 'Cryptorchidism (undescended testis — even after orchidopexy), previous contralateral tumour, family history (father/brother), germ cell neoplasia in situ, infertility/testicular atrophy, Klinefelter’s syndrome, and white ethnicity. Peak age 15–45.',
      topic: 'Epidemiology',
    },
  ],
  teaching: {
    summary: 'A young man with a hard, painless, irregular lump arising from the left testis, a history of orchidopexy and a brother with testicular cancer — a testicular germ cell tumour. Scan, check AFP/β-hCG/LDH, refer on the cancer pathway, and plan radical inguinal orchidectomy.',
    keyFindings: ['Hard, irregular, non-tender mass arising from the left testis', 'Cannot be separated from the testis', 'Does not transilluminate', 'Left groin orchidopexy scar; no inguinal nodes'],
    pearls: ['A painless hard testicular lump is cancer until proven otherwise.', 'Examine the abdomen for para-aortic nodes and the chest for gynaecomastia (β-hCG).', 'Never biopsy through the scrotum.', 'Offer sperm banking before treatment.'],
    presentation:
      'I examined Mr Marcus Bell, a 29-year-old man, with a chaperone present. There is a faint scar in the left groin from his previous orchidopexy and the left hemiscrotum looks slightly fuller. The right testis is normal. The left testis is enlarged with a hard, irregular, non-tender mass in its lower pole that cannot be separated from the testis; the epididymis and cord are normal, I can get above the swelling, and it does not transilluminate. There is no inguinal or supraclavicular lymphadenopathy and no palpable abdominal mass. These findings are highly suspicious of a left testicular tumour. I would arrange an urgent scrotal ultrasound and serum AFP, β-hCG and LDH, and refer on the urgent suspected-cancer pathway for radical inguinal orchidectomy.',
    references: ['Macleod’s Clinical Examination, 14th ed. — Ch. 15: The reproductive system (male genitalia)', 'NICE NG12: Suspected cancer — testicular', 'EAU Guidelines on Testicular Cancer'],
  },
}

export default c
