import type { CaseDef } from '../../engine/types'
import { FBC } from './helpers'

const c: CaseDef = {
  id: 'thrombosed-haemorrhoids',
  title: 'Thrombosed prolapsed internal haemorrhoids',
  presenting: 'Painful lumps at the back passage that won’t go back',
  specialty: 'Colorectal',
  exam: 'perianal',
  difficulty: 1,
  setting: 'Surgical assessment unit',
  stem: 'Surgical assessment unit. Gary Lewis, 45, has severe pain and lumps at his back passage. Take a history, examine the perianal area with a chaperone, and manage him.',
  components: ['history', 'exam', 'investigations', 'diagnosis', 'viva'],
  tags: ['perianal pain', 'haemorrhoids', 'prolapse', 'constipation'],
  patient: {
    name: 'Gary Lewis',
    title: 'Mr Lewis',
    age: 45,
    sex: 'male',
    dob: '07/07/1981',
    occupation: 'a warehouse manager',
    appearance: { sex: 'male', age: 45, skinTone: 2, habitus: 'overweight', hair: 'crop', hairColor: 'brown', eyeColor: 'brown' },
    persona: { mood: 'distressed', style: 'normal' },
  },
  vitals: { hr: 92, rhythm: 'regular', sbp: 138, dbp: 86, rr: 16, spo2: 99, temp: 37.0, avpu: 'A', pain: 8 },
  visual: { perianal: { kind: 'thrombosed-piles', clock: [3, 7, 11], sizeCm: 2, spasm: true, internalPiles: true } },
  history: {
    opening: { text: 'My piles came down two days ago straining on the toilet and they won’t go back. The pain is unbelievable.', cue: 'stands rather than sits' },
    answers: {
      'ano.lump': 'Three big lumps hanging out. I used to be able to push them back after going to the toilet.',
      'ano.prolapse': 'For a year they’ve come down when I go and I push them back. Now they’re stuck.',
      'ano.pain': 'Constant pain now, not just when I go.',
      'pain.onset': 'Two days ago, after a lot of straining.',
      'pain.severity': 'Eight.',
      'pain.character': 'A constant, tight, throbbing pain.',
      'ano.blood_type': 'Bright red blood on the paper and dripping in the pan after going — for months. A bit more these two days.',
      'gi.stool_blood': 'Bright red, after the stool, not mixed in.',
      'gi.constipation': 'I’m often constipated. I strain a lot.',
      'gi.bowel_change': 'No change in habit.',
      'gi.weight': 'No weight loss.',
      'gi.mucus': 'Some mucus and itching.',
      'ano.itch': 'Itchy at times.',
      'ano.discharge': 'A bit of mucus.',
      'ano.continence': 'Fine.',
      'sys.fever': 'No.',
      'fh.cancer': 'No bowel cancer in the family.',
      'pmh.conditions': 'Nothing.',
      'dh.meds': 'Anusol cream from the chemist.',
      'dh.anticoag': 'No.',
      'dh.allergies': 'None.',
      'sh.diet': 'Not much fibre, I admit. Lots of coffee.',
      'sh.occupation': 'I lift heavy boxes and sit at a desk a lot.',
      'comm.questions': 'Will you have to cut them off?',
    },
    key: ['comm.open', 'ano.lump', 'ano.prolapse', 'ano.pain', 'pain.onset', 'ano.blood_type', 'gi.constipation', 'gi.bowel_change', 'gi.weight', 'fh.cancer', 'dh.anticoag', 'sh.diet'],
    critical: ['ano.blood_type', 'gi.bowel_change'],
    ideas: 'My piles have got stuck.',
    concerns: 'That I’ll need an operation.',
    expectations: 'Something for the pain.',
    social: { diet: 'Low fibre; lots of coffee.' },
  },
  keyed: {
    'comm.pain': { text: '', says: 'Everything down there hurts. Please be gentle.' },
    'pr.inspect': {
      text: 'Three tense, purple-blue, oedematous swellings protrude from the anus at 3, 7 and 11 o’clock, covered partly by swollen anoderm. No ulceration or necrosis; no pus; no fissure seen.',
      abnormal: true,
      meaning: 'Thrombosed, prolapsed internal haemorrhoids at the three primary positions (left lateral, right posterior, right anterior).',
    },
    'pr.strain': { text: 'He cannot strain — too painful.', reaction: 0.6 },
    'pr.palpate': { text: 'The swellings are firm and exquisitely tender; the surrounding skin is oedematous but not indurated or fluctuant.', reaction: 0.9, abnormal: true },
    'pr.lubricate': { text: 'You lubricate your finger.' },
    'pr.insert': {
      text: 'He cannot tolerate a finger past the swollen haemorrhoids; you stop.',
      reaction: 1,
      says: 'No — I can’t, I’m sorry!',
      meaning: 'Acutely thrombosed piles: defer the DRE and proctoscopy — but a rectal examination (± flexible sigmoidoscopy) is needed once settled to exclude other causes of bleeding.',
    },
    'pr.sweep': { text: 'Not possible — too painful.', reaction: 1 },
    'pr.proctoscope': { text: 'You must not pass a proctoscope now.', reaction: 1 },
    'pr.nodes': { text: 'No inguinal lymphadenopathy.' },
    'complete.scope': { text: 'Once settled: DRE, proctoscopy and flexible sigmoidoscopy to exclude a more proximal cause of bleeding (he is 45 with months of bleeding).' },
  },
  investigations: {
    fbc: { values: FBC(138, 8.1, 5.6, 248), interpretation: 'No anaemia.' },
    proctoscopy: { report: 'Not tolerated acutely. At 6 weeks: grade III internal haemorrhoids at 3, 7 and 11 o’clock.', interpretation: 'Haemorrhoids confirmed once settled.' },
    flexi: { report: 'At 6 weeks: normal to the splenic flexure; internal haemorrhoids.', interpretation: 'No other source of bleeding.' },
  },
  investigationRubric: {
    essential: [{ id: 'fbc', why: 'Months of bleeding — check for anaemia.' }],
    helpful: [
      { id: 'flexi', why: 'Once settled, to exclude a proximal cause of rectal bleeding.' },
      { id: 'proctoscopy', why: 'Once the acute episode has settled.' },
    ],
    avoid: [{ id: 'ct-ap', why: 'Not needed.' }],
  },
  diagnosis: {
    correct: 'thrombosed-piles',
    accept: ['haemorrhoids'],
    differentials: ['perianal-haematoma', 'perianal-abscess', 'fissure', 'rectal-cancer', 'anal-cancer'],
  },
  management: {
    essential: [
      { id: 'piles-conservative', why: '!Conservative first: analgesia (avoid codeine), stool softeners, warm baths, ice packs and topical anaesthetic; bed rest with the foot of the bed raised. Most settle in 2–3 weeks.' },
      { id: 'laxatives', why: 'Soft stools without straining.' },
      { id: 'analgesia', why: 'Paracetamol ± NSAID; avoid constipating opioids.' },
      { id: 'lifestyle', why: 'Fibre and fluids; don’t strain or sit on the toilet for long.' },
    ],
    helpful: [
      { id: 'haemorrhoidectomy', why: 'Urgent haemorrhoidectomy is an option in some centres, or electively for recurrent grade III–IV piles.' },
      { id: 'colonoscopy-later', why: 'Flexible sigmoidoscopy or colonoscopy after the episode to exclude another source.' },
    ],
    avoid: [
      { id: 'incision-drainage', why: 'Incising thrombosed internal piles causes bleeding — that approach is for a perianal haematoma seen early.' },
      { id: 'eua-drainage', why: 'No abscess.' },
    ],
  },
  viva: [
    {
      id: 'grades',
      q: 'How are internal haemorrhoids graded?',
      answer: 'I: bleed but do not prolapse. II: prolapse on straining and reduce spontaneously. III: prolapse and need manual reduction. IV: permanently prolapsed (irreducible).',
      topic: 'Classification',
    },
    {
      id: 'positions',
      q: 'Where are the primary haemorrhoidal cushions?',
      options: ['3, 7 and 11 o’clock in the lithotomy position', '12 and 6 o’clock', 'Only at 6 o’clock', 'Anywhere — they are random'],
      correct: 0,
      answer: '3, 7 and 11 o’clock (left lateral, right posterior and right anterior), corresponding to the terminal branches of the superior rectal artery.',
      topic: 'Anatomy',
    },
    {
      id: 'pain',
      q: 'Why are internal haemorrhoids usually painless?',
      answer: 'They lie above the dentate line, which has visceral (autonomic) innervation; pain suggests thrombosis, strangulation, a fissure or a perianal haematoma below the line (somatic innervation by the inferior rectal nerve).',
      topic: 'Anatomy',
    },
    {
      id: 'bleed',
      q: 'Why must you exclude other causes of rectal bleeding?',
      answer: 'Haemorrhoids are common and can coexist with colorectal cancer. Bleeding mixed with stool, change in bowel habit, weight loss, anaemia, a mass or age over ~50 need lower GI endoscopy.',
      topic: 'Red flags',
    },
  ],
  teaching: {
    summary:
      'Thrombosed prolapsed internal haemorrhoids in a 45-year-old with a year of grade III piles: two days of severe constant pain after straining, three tense purple oedematous swellings at 3, 7 and 11 o’clock; DRE deferred; managed conservatively with later endoscopy.',
    keyFindings: [
      'A year of prolapse needing manual reduction (grade III), bright red bleeding on the paper and in the pan',
      'Two days of irreducible, severely painful lumps after straining',
      'Three tense, purple-blue swellings at 3, 7 and 11 o’clock',
      'Too painful for DRE or proctoscopy — deferred',
      'No change in bowel habit or weight loss; normal Hb',
    ],
    pearls: [
      'Internal piles are painless unless thrombosed or strangulated.',
      'Bleeding after the stool, on the paper and dripping in the pan = anal-canal source.',
      'Always plan an examination of the bowel once settled.',
      'Avoid codeine — constipation makes it worse.',
    ],
    presentation:
      'Mr Lewis is a 45-year-old warehouse manager with a year of haemorrhoids that prolapse on defecation and need manual reduction, with bright red bleeding on the paper and in the pan, who now has two days of severe constant pain and irreducible lumps after straining. He is constipated on a low-fibre diet, with no change in bowel habit, weight loss or family history of bowel cancer. With a chaperone, in the left lateral position, there are three tense, purple-blue, oedematous prolapsed haemorrhoids at 3, 7 and 11 o’clock with no necrosis or abscess; he could not tolerate a rectal examination, which I deferred. This is thrombosed prolapsed internal haemorrhoids. I would manage him conservatively with analgesia, stool softeners, warm baths and ice packs, and arrange proctoscopy and flexible sigmoidoscopy once settled, with haemorrhoidectomy if recurrent.',
    references: ['Macleod’s Clinical Examination, 14th ed. — Ch. 6: rectal examination and proctoscopy (pp. 111–113)', 'ACPGBI guidance on haemorrhoidal disease'],
  },
}

export default c
