import type { CaseDef } from '../../engine/types'
import { lab } from './helpers'

const c: CaseDef = {
  id: 'thyroid-nodule',
  title: 'Papillary thyroid carcinoma with a lateral neck node',
  presenting: 'A lump on the right side of the neck',
  specialty: 'Endocrine',
  exam: 'thyroid',
  difficulty: 2,
  setting: 'Outpatient clinic',
  stem: 'Endocrine surgery clinic. Sarah Ahmed, 36, has noticed a lump in her neck. Take a focused history, examine her neck and thyroid status, request investigations and explain the plan.',
  components: ['history', 'exam', 'investigations', 'diagnosis', 'viva'],
  tags: ['neck lump', 'thyroid nodule', 'cancer', 'FNA'],
  patient: {
    name: 'Sarah Ahmed',
    title: 'Ms Ahmed',
    age: 36,
    sex: 'female',
    dob: '27/06/1990',
    occupation: 'a radiographer',
    appearance: { sex: 'female', age: 36, skinTone: 3, habitus: 'average', hair: 'long', hairColor: 'black', eyeColor: 'brown' },
    persona: { mood: 'anxious', style: 'normal' },
  },
  vitals: { hr: 76, rhythm: 'regular', sbp: 118, dbp: 74, rr: 14, spo2: 99, temp: 36.6, avpu: 'A', pain: 0 },
  visual: { neck: { goitre: { kind: 'nodule', side: 'right', size: 1 }, nodes: 'right' } },
  history: {
    opening: 'I noticed a lump on the right side of my neck in the mirror about three months ago. I think it’s getting bigger.',
    answers: {
      'lump.when': 'About three months ago.',
      'lump.how': 'I saw it when I swallowed, doing my make-up.',
      'lump.change': 'Slightly bigger, I think.',
      'lump.pain': 'It doesn’t hurt.',
      'lump.other': 'There might be a smaller one further out on the right side.',
      'thy.voice': 'My voice is normal.',
      'thy.breathing': 'No trouble breathing or lying flat.',
      'gi.dysphagia': 'No trouble swallowing.',
      'thy.heat': 'No — I don’t feel hot or cold.',
      'thy.tremor': 'No shaking.',
      'thy.mood': 'Just worried.',
      'thy.eyes': 'My eyes are fine.',
      'ros.palpitations': 'No.',
      'gi.weight': 'Stable.',
      'thy.radiation': 'I had radiotherapy to my neck as a teenager for Hodgkin’s lymphoma.',
      'thy.fh': 'No thyroid problems in the family.',
      'pmh.cancer': 'Hodgkin’s lymphoma at fifteen — chemotherapy and radiotherapy to the neck. All clear since.',
      'pmh.conditions': 'Nothing else.',
      'dh.meds': 'Nothing.',
      'dh.allergies': 'None.',
      'sys.sweats': 'No night sweats.',
      'sys.fever': 'No.',
      'gyn.pregnant': 'No.',
      'sh.smoking': 'Never.',
      'comm.questions': 'Could it be the lymphoma back, or something else?',
    },
    key: ['comm.open', 'lump.when', 'lump.change', 'lump.pain', 'lump.other', 'thy.voice', 'thy.breathing', 'gi.dysphagia', 'thy.heat', 'thy.radiation', 'thy.fh', 'sys.sweats', 'dh.meds'],
    critical: ['thy.radiation', 'thy.voice'],
    ideas: 'Could the radiotherapy have caused it?',
    concerns: 'Cancer — again.',
    expectations: 'To find out quickly.',
    pmh: 'Hodgkin’s lymphoma aged 15 treated with chemotherapy and neck radiotherapy.',
  },
  keyed: {
    'comm.pain': { text: '', says: 'No, nothing hurts.' },
    'thy.general': { text: 'A well young woman; calm apart from understandable anxiety. Not thin, no restlessness.' },
    'thy.hands': { text: 'Warm, dry hands. No tremor, sweating, onycholysis or acropachy.', meaning: 'Clinically euthyroid.' },
    'thy.tremor': { text: 'No fine tremor with the arms outstretched.' },
    'thy.pulse': { text: 'Pulse 76, regular.' },
    'thy.eyes': { text: 'No lid retraction, exophthalmos or chemosis.' },
    'thy.lidlag': { text: 'No lid lag.' },
    'thy.eom': { text: 'Full eye movements without diplopia.' },
    'thy.neckInspect': {
      text: 'A visible 2.5 cm swelling to the right of the midline in the lower neck. A faint fullness lies further out, deep to the anterior border of the right sternocleidomastoid. No scars.',
      abnormal: true,
    },
    'thy.swallow': { text: 'The swelling moves up when she swallows water.', abnormal: true, meaning: 'Attached to the pretracheal fascia — a thyroid swelling.' },
    'thy.tongue': { text: 'It does not move when she protrudes her tongue.', meaning: 'Not a thyroglossal cyst.' },
    'thy.palpate': {
      text: 'From behind: a 2.5 cm firm-to-hard, slightly irregular, non-tender nodule in the right lobe. The left lobe is normal. You can get below it.',
      abnormal: true,
      meaning: 'A hard, irregular solitary nodule is a red flag for malignancy.',
    },
    'thy.nodes': {
      text: 'A firm, non-tender, mobile 1.5 cm lymph node in the right mid-jugular chain (level III), deep to the sternocleidomastoid.',
      abnormal: true,
      meaning: 'Ipsilateral cervical lymphadenopathy with a thyroid nodule — suspect papillary carcinoma.',
    },
    'thy.trachea': { text: 'The trachea is central.' },
    'thy.percuss': { text: 'No retrosternal dullness.' },
    'thy.bruit': { text: 'No bruit over the thyroid.' },
    'thy.pemberton': { text: 'Pemberton’s sign is negative.' },
    'thy.reflexes': { text: 'Normal reflexes with normal relaxation.' },
    'thy.proximal': { text: 'Normal proximal power.' },
    'thy.shins': { text: 'No pretibial myxoedema.' },
  },
  investigations: {
    tft: { values: [lab('TSH', '1.6', 'mU/L', '0.3–4.2'), lab('Free T4', '15.1', 'pmol/L', '12–22')], interpretation: 'Euthyroid — a ‘hot’ nodule is unlikely, so no isotope scan is needed.' },
    'us-neck': {
      report: 'Right lobe: a 24 mm solid, markedly hypoechoic nodule, taller than wide, with irregular margins and microcalcifications (U5). Right level III node 15 mm, rounded, with microcalcifications and loss of the fatty hilum.',
      interpretation: 'U5 nodule — highly suspicious — with a suspicious ipsilateral node.',
      abnormal: true,
    },
    fna: {
      report: 'Ultrasound-guided FNA of the nodule: papillary carcinoma (Thy5) — nuclear grooves, pseudo-inclusions, ‘Orphan Annie’ nuclei. Node FNA: metastatic papillary carcinoma (thyroglobulin in the washout raised).',
      interpretation: 'Papillary thyroid carcinoma with nodal metastasis.',
      abnormal: true,
    },
    calcium: { values: [lab('Adjusted calcium', '2.38', 'mmol/L', '2.20–2.60')], interpretation: 'Baseline before thyroidectomy.' },
    'ct-cap': { report: 'No pulmonary or bone metastases. Right level III/IV nodes.', interpretation: 'Locoregional disease only.' },
  },
  investigationRubric: {
    essential: [
      { id: 'tft', why: 'Thyroid status: a suppressed TSH would suggest a hot (usually benign) nodule.' },
      { id: 'us-neck', why: 'Characterises the nodule (U1–U5) and the nodes.' },
      { id: 'fna', why: 'Cytology of the U5 nodule and the suspicious node.' },
    ],
    helpful: [
      { id: 'calcium', why: 'Baseline before surgery (hypoparathyroidism risk).' },
      { id: 'ct-cap', why: 'Only for extensive nodal disease or suspected spread (avoid iodinated contrast before radioiodine if possible).' },
    ],
    avoid: [{ id: 'core', why: 'FNA is the standard first test.' }],
  },
  diagnosis: {
    correct: 'thyroid-cancer',
    differentials: ['solitary-nodule', 'mng', 'lymphoma', 'reactive-node', 'branchial-cyst', 'thyroglossal-cyst'],
  },
  management: {
    essential: [
      { id: '2ww', why: 'Thyroid lump with a node and previous neck irradiation — urgent referral.' },
      { id: 'fna-thyroid', why: 'Ultrasound-guided FNA of the nodule and the node.' },
      { id: 'mdt', why: 'Thyroid cancer MDT.' },
      { id: 'laryngoscopy', why: 'Document vocal cord function before surgery (recurrent laryngeal nerve).' },
      { id: 'thyroid-rai', why: '!Total thyroidectomy with central and right lateral neck dissection, then radioactive iodine and TSH suppression as advised.' },
      { id: 'breaking-news', why: 'Explain the diagnosis — with an excellent prognosis.' },
    ],
    helpful: [
      { id: 'consent', why: 'Risks: recurrent laryngeal nerve injury, hypocalcaemia, bleeding, lifelong levothyroxine.' },
    ],
    avoid: [
      { id: 'reassure', why: 'A U5 nodule with a node needs treatment.' },
      { id: 'carbimazole', why: 'She is euthyroid.' },
    ],
  },
  viva: [
    {
      id: 'moves',
      q: 'Why does a thyroid swelling move on swallowing, and a thyroglossal cyst on tongue protrusion?',
      answer: 'The thyroid is enclosed in the pretracheal fascia attached to the larynx, so it rises with the larynx on swallowing. A thyroglossal cyst is tethered to the foramen caecum of the tongue by the remnant of the thyroglossal duct, so it rises when the tongue is protruded (Macleod’s, Ch. 10).',
      topic: 'Examination',
    },
    {
      id: 'types',
      q: 'Name the types of thyroid cancer and how they spread.',
      answer: 'Papillary (~80%, young adults, lymphatic spread, excellent prognosis); follicular (haematogenous spread to bone and lung); medullary (parafollicular C cells, calcitonin, MEN2); anaplastic (elderly, aggressive, poor prognosis); plus thyroid lymphoma (with Hashimoto’s).',
      topic: 'Pathology',
    },
    {
      id: 'redflags',
      q: 'Which features of a thyroid nodule raise concern for cancer?',
      options: ['Hard, fixed, growing nodule with a node, hoarseness or prior neck radiation', 'A soft, smooth, diffuse goitre in pregnancy', 'A tender nodule after a viral illness', 'Bilateral exophthalmos'],
      correct: 0,
      answer: 'Extremes of age, male sex, previous neck irradiation, family history (MEN2), rapid growth, a hard or fixed nodule, hoarse voice (nerve involvement), stridor and cervical lymphadenopathy.',
      topic: 'Assessment',
    },
    {
      id: 'thy',
      q: 'What do the Thy and U classifications mean?',
      answer: 'U1–U5 grade the ultrasound appearance from normal to malignant (BTA). Thy1–Thy5 grade FNA cytology from non-diagnostic to malignant. U3 or above usually needs FNA.',
      topic: 'Investigations',
    },
  ],
  teaching: {
    summary:
      'Papillary thyroid carcinoma in a 36-year-old woman with previous neck radiotherapy: a growing, hard, irregular right-lobe nodule that moves on swallowing (not on tongue protrusion), an ipsilateral level III node, euthyroid; ultrasound U5 and FNA Thy5.',
    keyFindings: [
      'Three-month painless, enlarging right lower neck lump',
      'Neck radiotherapy for Hodgkin’s lymphoma aged 15',
      'Moves on swallowing, not on tongue protrusion — thyroid in origin',
      'Hard, irregular 2.5 cm right-lobe nodule; firm right level III node',
      'Euthyroid; US U5 nodule with suspicious node; FNA Thy5 papillary carcinoma',
    ],
    pearls: [
      'Swallow and tongue protrusion: the two key tests for a midline neck lump.',
      'Always examine the cervical nodes and ask about voice, breathing and radiation.',
      'Check TFTs first — a toxic nodule changes the work-up.',
      'Papillary cancer spreads to nodes; it has an excellent prognosis.',
    ],
    presentation:
      'Ms Ahmed is a 36-year-old radiographer with a three-month history of a painless, enlarging lump in the right lower neck, without voice change, stridor or dysphagia, and no symptoms of thyroid dysfunction. She had neck radiotherapy for Hodgkin’s lymphoma aged 15. She is clinically euthyroid. There is a 2.5 centimetre hard, irregular nodule in the right lobe of the thyroid that moves on swallowing but not on tongue protrusion, and a firm, mobile 1.5 centimetre node in the right level III chain; the trachea is central with no retrosternal extension. TFTs are normal, ultrasound shows a U5 nodule with a suspicious node, and FNA confirms papillary carcinoma with nodal spread. I would refer her to the thyroid cancer MDT for total thyroidectomy with neck dissection after laryngoscopy, followed by radioiodine.',
    references: ['Macleod’s Clinical Examination, 14th ed. — Ch. 10: examination of the thyroid gland (pp. 194–198); Ch. 9: neck lumps (Box 9.10)', 'British Thyroid Association guidelines for thyroid cancer'],
  },
}

export default c
