import type { CaseDef } from '../../engine/types'
import { FBC, lab, LFT, r, UE, VBG } from './helpers'

const c: CaseDef = {
  id: 'upper-gi-bleed',
  title: 'Upper GI haemorrhage from a posterior duodenal ulcer (on apixaban and naproxen)',
  presenting: 'Vomiting blood and black stools',
  specialty: 'Upper GI',
  exam: 'abdominal',
  difficulty: 2,
  setting: 'Emergency department',
  stem: 'Irene Fletcher, 74, was brought in by ambulance after vomiting blood and collapsing at home. Assess her, examine her abdomen, request investigations and start management.',
  components: ['history', 'exam', 'investigations', 'diagnosis', 'viva'],
  tags: ['GI bleeding', 'melaena', 'anticoagulants', 'Glasgow–Blatchford'],
  patient: {
    name: 'Irene Fletcher',
    title: 'Mrs Fletcher',
    age: 74,
    sex: 'female',
    dob: '12/11/1951',
    occupation: 'a retired school secretary',
    appearance: {
      sex: 'female',
      age: 74,
      skinTone: 1,
      habitus: 'average',
      hair: 'short',
      hairColor: 'white',
      eyeColor: 'blue',
      glasses: true,
      pallor: 0.75,
      sweaty: true,
      lines: { cannula: 'right-forearm', drip: true, oxygen: 'nasal' },
    },
    persona: { mood: 'anxious', style: 'normal' },
  },
  vitals: { hr: 116, rhythm: 'irregular', sbp: 92, dbp: 56, rr: 22, spo2: 95, o2: '2 L/min via nasal cannulae', temp: 36.4, avpu: 'A', pain: 3 },
  bedside: { vomitBowl: 'coffee-ground', drip: true },
  history: {
    opening: 'I was sick this morning and it was blood, doctor — lots of it. Then I went dizzy on the toilet and passed out. My husband called the ambulance.',
    answers: {
      'gi.vomiting': 'Twice. Once at home — a lot — and again in the ambulance.',
      'gi.vomit_content': 'The first time it was bright red with clots, a cupful or more. In the ambulance it was dark, like coffee grounds.',
      'gi.melaena': 'Yes — black and sticky, like tar, for two days. The smell was awful. I thought it was something I’d eaten.',
      'gi.stool_blood': 'No red blood. Just the black.',
      'gi.bowels_last': 'This morning, just before I fainted — black again.',
      'gi.nausea': 'A bit queasy still.',
      'ros.dizzy': 'Very light-headed when I stand up. I fainted on the toilet this morning.',
      'ros.sob': 'A little breathless.',
      'ros.chest_pain': 'No chest pain.',
      'ros.palpitations': 'My heart’s racing.',
      'pain.site': { text: 'Just a gnawing ache up here.', cue: 'rubs her epigastrium' },
      'pain.onset': 'The ache has come and gone for about three weeks.',
      'pain.character': 'Gnawing, burning.',
      'pain.timing': 'On and off, worse at night.',
      'pain.relieving': 'Food used to settle it, and Gaviscon.',
      'pain.severity': 'Three now.',
      'gi.reflux': 'Indigestion for a few weeks, mostly at night.',
      'gi.appetite': 'Not bad.',
      'gi.weight': 'No, my weight’s steady.',
      'gi.dysphagia': 'No.',
      'gi.jaundice': 'No.',
      'gi.distension': 'No.',
      'dh.meds': 'Apixaban for my heart rhythm, bisoprolol, ramipril, atorvastatin… and naproxen for my knee.',
      'dh.anticoag': 'Apixaban, five milligrams twice a day, for my AF. My last dose was at nine last night.',
      'dh.nsaids': 'Naproxen — the GP started it about a month ago for my knee. Twice a day.',
      'dh.steroids': 'No.',
      'dh.otc': 'Just Gaviscon.',
      'pmh.conditions': 'Atrial fibrillation, high blood pressure and arthritis in my knees.',
      'pmh.heart': 'AF for five years. No heart attacks.',
      'pmh.gi': 'I’ve never had an ulcer, and no liver trouble.',
      'pmh.clots': 'No — only the blood thinner.',
      'pmh.surgery': 'A hysterectomy in my forties.',
      'sh.alcohol': 'A small sherry at Christmas.',
      'sh.smoking': 'Never.',
      'sh.living': 'With my husband, Frank. He’s in the waiting room.',
      'sh.mobility': 'I walk with a stick because of my knee.',
      'comm.questions': 'Will I need a blood transfusion? And what about my blood thinner?',
    },
    key: [
      'comm.open',
      'gi.vomiting',
      'gi.vomit_content',
      'gi.melaena',
      'ros.dizzy',
      'pain.site',
      'gi.reflux',
      'gi.weight',
      'gi.dysphagia',
      'dh.anticoag',
      'dh.nsaids',
      'dh.meds',
      'dh.steroids',
      'pmh.gi',
      'pmh.heart',
      'sh.alcohol',
    ],
    critical: ['dh.anticoag', 'dh.nsaids'],
    ideas: 'I wondered if the naproxen had upset my stomach.',
    concerns: 'That I’m bleeding to death — and that I’ll have a stroke if I stop the blood thinner.',
    expectations: 'Just stop the bleeding, please.',
    social: { alcohol: 'Rarely — a small sherry at Christmas.', mobility: 'I walk with a stick because of my knee.' },
  },
  abdo: {
    general: {
      endOfBed:
        'Mrs Fletcher is propped up on the trolley, pale and sweaty, with nasal oxygen and IV fluid running through a cannula in her right forearm. A bowl beside her holds dark, coffee-ground vomit, and there is a faint smell of melaena. She is alert but anxious.',
    },
    hands: { temperature: 'cold', crt: 3.5, pallorCreases: true, pulseVolume: 'weak' },
    face: { conjunctiva: 'pale', mucosa: 'dry', tongue: 'pale' },
    abdomen: {
      regions: {
        EPI: r(1, 2),
      },
      bowelSounds: 'hyperactive',
    },
    completion: {
      dre: 'With consent and a chaperone: black, sticky, tarry, foul-smelling stool on the glove — melaena. No palpable rectal mass.',
      'cvs-resp': 'Irregularly irregular tachycardia; heart sounds otherwise unremarkable. Chest clear.',
    },
  },
  criticalSteps: ['gen.obs', 'hands.perfusion'],
  investigations: {
    fbc: { values: FBC(76, 12.1, 9.4, 302, 89, 'female'), interpretation: 'Hb 76 g/L, normocytic — an acute bleed. It may fall further as she haemodilutes.' },
    ue: {
      values: UE(138, 4.6, 19.8, 96, '49', 'female'),
      interpretation: 'Urea raised out of proportion to creatinine — digested blood plus hypovolaemia. Supports an upper GI source.',
    },
    lft: { values: LFT(10, 22, 80, 31, 34), interpretation: 'No evidence of liver disease, so variceal bleeding is unlikely.' },
    coag: {
      values: [lab('PT', 14.6, 's', '10–13', 'H'), lab('INR', 1.3, '', '0.8–1.2', 'H'), lab('APTT', 33, 's', '25–35'), lab('Fibrinogen', 2.8, 'g/L', '1.5–4.0')],
      interpretation: 'Apixaban mildly prolongs the PT, but the INR does not measure its effect — the time of the last dose matters more (an anti-Xa level if available).',
    },
    vbg: { values: [...VBG(7.32, 20, -5.0, 3.2, 4.6, 7.1), lab('Hb (gas)', 74, 'g/L', '115–155', 'L')], interpretation: 'Lactate 3.2 — hypoperfusion from haemorrhage. The gas gives a quick haemoglobin.' },
    xm: { report: '4 units of red cells crossmatched. Group O RhD positive. Antibody screen negative.' },
    gs: { report: 'Group O RhD positive. Antibody screen negative.' },
    ecg: {
      report: 'Atrial fibrillation with a ventricular rate of 116. Widespread ST depression of less than 1 mm. No ST elevation.',
      interpretation: 'Fast AF driven by hypovolaemia, with rate-related ST depression — treat the bleeding, not the rate.',
      abnormal: true,
    },
    troponin: { values: [lab('hs-Troponin T', 22, 'ng/L', '< 14', 'H')], interpretation: 'A small rise — type 2 myocardial injury from anaemia and tachycardia.' },
    ogd: {
      report:
        'Fresh blood and clot in the stomach and duodenum; no varices. A 15 mm ulcer in the posterior wall of the duodenal bulb with a non-bleeding visible vessel (Forrest IIa), treated with adrenaline injection and two haemostatic clips. Scattered erosions in the gastric antrum. CLO (rapid urease) test positive.',
      interpretation: 'Bleeding posterior duodenal ulcer in gastroduodenal artery territory — high risk of rebleeding. Helicobacter pylori positive.',
      abnormal: true,
    },
    cta: {
      report: 'No active contrast extravasation. Clip artefact in the duodenal bulb.',
      interpretation: 'Not needed first-line — CT angiography is for rebleeding after endoscopy, to guide embolisation.',
    },
  },
  investigationRubric: {
    essential: [
      { id: 'fbc', why: 'Haemoglobin guides transfusion.' },
      { id: 'ue', why: 'Urea:creatinine ratio, AKI, and part of the Glasgow–Blatchford score.' },
      { id: 'coag', why: 'She is anticoagulated.' },
      { id: 'lft', why: 'Look for liver disease — varices change management.' },
      { id: 'xm', why: '!Crossmatch now: she is shocked and has bled heavily.' },
      { id: 'ogd', why: '!Endoscopy is diagnostic and therapeutic — immediately after resuscitation in an unstable patient, otherwise within 24 hours.' },
    ],
    helpful: [
      { id: 'vbg', why: 'Lactate and a rapid haemoglobin.' },
      { id: 'ecg', why: 'Fast AF; demand ischaemia.' },
      { id: 'troponin', why: 'Type 2 myocardial injury.' },
      { id: 'gs', why: 'Group and save (if not crossmatched).' },
    ],
  },
  diagnosis: {
    correct: 'bleeding-pu',
    differentials: ['variceal-bleed', 'mallory-weiss', 'gastric-cancer', 'gastritis', 'oesophageal-cancer', 'diverticular-bleed'],
  },
  management: {
    essential: [
      { id: 'abcde', why: 'She is shocked: HR 116, SBP 92, lactate 3.2.' },
      { id: 'iv-access', why: 'Two large-bore cannulae.' },
      { id: 'fluids', why: 'Crystalloid while blood is fetched — but do not over-resuscitate.' },
      { id: 'transfusion', why: 'Hb 76 with shock and ongoing bleeding. Once she is stable, a restrictive threshold applies (transfuse below 70 g/L, aiming for 70–90 g/L).' },
      { id: 'stop-anticoag', why: '!Hold apixaban and naproxen; with a major bleed, discuss reversal (andexanet alfa or prothrombin complex concentrate) with haematology.' },
      { id: 'ogd-urgent', why: '!Endoscopy immediately after resuscitation in an unstable patient (NICE CG141).' },
      { id: 'nbm', why: 'Nil by mouth for endoscopy.' },
      { id: 'senior', why: 'Senior review and the on-call endoscopist.' },
    ],
    helpful: [
      { id: 'o2', why: 'Tachypnoeic and anaemic.' },
      { id: 'catheter', why: 'Hourly urine output to guide resuscitation.' },
      { id: 'fluid-balance', why: 'Strict fluid balance.' },
      { id: 'ppi-iv', why: 'After endoscopic haemostasis of a high-risk ulcer — not as a substitute for endoscopy.' },
      { id: 'h-pylori', why: 'CLO positive — eradication prevents recurrence.' },
      { id: 'icu', why: 'High-dependency monitoring for a high-risk bleed.' },
    ],
    avoid: [
      { id: 'tranexamic-acid', why: 'HALT-IT: tranexamic acid does not reduce deaths from GI bleeding and increases venous thromboembolism.' },
      { id: 'nsaid', why: 'Naproxen caused this ulcer — stop it for good.' },
      { id: 'anticoag-heparin', why: 'Anticoagulation is held while she is bleeding.' },
      { id: 'discharge', why: 'Her Glasgow–Blatchford score is high — she needs admission and endoscopy.' },
    ],
  },
  viva: [
    {
      id: 'gbs',
      q: 'Which score is used before endoscopy to identify upper GI bleeds that can be managed as outpatients?',
      options: ['Glasgow–Blatchford score', 'Full (post-endoscopy) Rockall score', 'Child–Pugh score', 'Boey score'],
      correct: 0,
      answer:
        'The Glasgow–Blatchford score uses urea, haemoglobin, systolic BP, pulse, melaena, syncope, liver disease and heart failure. A score of 0 (≤ 1 in some guidelines) allows early discharge with outpatient endoscopy. The full Rockall score is calculated after endoscopy to predict rebleeding and death.',
      topic: 'Scores',
    },
    {
      id: 'urea',
      q: 'Why is her urea raised out of proportion to her creatinine?',
      answer:
        'Blood in the upper GI tract is digested and absorbed as protein, which is metabolised to urea; hypovolaemia adds pre-renal retention. A high urea:creatinine ratio favours an upper over a lower GI source.',
      topic: 'Interpretation',
    },
    {
      id: 'forrest',
      q: 'What does the Forrest classification describe, and why does a visible vessel matter?',
      answer:
        'It grades the endoscopic stigmata of ulcer bleeding by rebleeding risk: Ia spurting, Ib oozing, IIa non-bleeding visible vessel, IIb adherent clot, IIc flat pigmented spot, III clean base. Ia–IIa (and IIb once the clot is removed) need endoscopic therapy — adrenaline injection combined with a thermal or mechanical (clip) method — followed by high-dose PPI.',
      topic: 'Endoscopy',
    },
    {
      id: 'artery',
      q: 'A posterior duodenal bulb ulcer that bleeds torrentially has usually eroded which artery?',
      options: ['Gastroduodenal artery', 'Left gastric artery', 'Splenic artery', 'Superior mesenteric artery'],
      correct: 0,
      answer: 'The gastroduodenal artery runs behind the first part of the duodenum. Posterior ulcers bleed; anterior ulcers perforate. Lesser-curve gastric ulcers can erode the left gastric artery.',
      topic: 'Anatomy',
    },
    {
      id: 'rebleed',
      q: 'She rebleeds after endoscopic therapy. What next?',
      answer:
        'Resuscitate, then repeat the endoscopy. If that fails or is not possible, choose between interventional radiology (CT angiography then transcatheter embolisation of the gastroduodenal artery), often preferred in frail, high-risk patients, and surgery (duodenotomy and under-running of the vessel). Keep blood products flowing and involve the consultant.',
      topic: 'Management',
    },
    {
      id: 'anticoag',
      q: 'How would you manage her anticoagulation?',
      answer:
        'Hold apixaban now. For life-threatening bleeding, discuss reversal with haematology — andexanet alfa or prothrombin complex concentrate. Once haemostasis is secure, weigh her stroke risk (CHA₂DS₂-VASc) against rebleeding: anticoagulation is usually restarted within about a week, with PPI cover, and the naproxen is stopped for good.',
      topic: 'Anticoagulation',
    },
  ],
  teaching: {
    summary:
      'Upper GI haemorrhage from a posterior duodenal ulcer in a 74-year-old woman on apixaban for AF who was started on naproxen for knee pain: haematemesis, two days of melaena and a syncopal collapse, with shock, a high urea and a haemoglobin of 76.',
    keyFindings: [
      'Fresh haematemesis then coffee-ground vomit; two days of melaena; syncope',
      'Apixaban for AF plus a month of naproxen; three weeks of nocturnal epigastric pain',
      'Fast AF at 116, BP 92/56, cold peripheries, CRT 3.5 s, lactate 3.2',
      'No stigmata of chronic liver disease; mild epigastric tenderness; melaena on rectal examination',
      'Hb 76, urea 19.8 with creatinine 96; OGD: posterior DU with a visible vessel (Forrest IIa), CLO positive',
    ],
    pearls: [
      'Melaena means an upper GI source until proven otherwise, and a high urea supports it.',
      'Always ask about anticoagulants, antiplatelets, NSAIDs and steroids — and when the last dose was taken.',
      'Look for stigmata of liver disease: variceal bleeding needs terlipressin and antibiotics before endoscopy.',
      'Fast AF in a bleeding patient is a sign of hypovolaemia — fill, don’t rate-control.',
      'Tranexamic acid does not help in GI bleeding (HALT-IT); PPIs are given after endoscopy, not instead of it.',
    ],
    presentation:
      'Mrs Fletcher is a 74-year-old woman with atrial fibrillation on apixaban who was started on naproxen a month ago for knee osteoarthritis. She presented with a large haematemesis of fresh blood followed by coffee-ground vomit, two days of melaena and a syncopal episode, after three weeks of nocturnal epigastric pain. She is shocked, in fast AF at 116 with a blood pressure of 92/56, cold peripheries and a lactate of 3.2. She is pale, with mild epigastric tenderness, no stigmata of chronic liver disease and melaena on rectal examination. Her haemoglobin is 76 with a disproportionately raised urea of 19.8, and her Glasgow–Blatchford score is high. My working diagnosis is a bleeding peptic ulcer. I would resuscitate her through two large-bore cannulae with crossmatched blood and cautious fluids, withhold apixaban and naproxen and discuss reversal with haematology, keep her nil by mouth, catheterise her and arrange endoscopy as soon as she is resuscitated. OGD showed a posterior duodenal ulcer with a visible vessel, treated with adrenaline and clips; she now needs high-dose PPI, H. pylori eradication and a planned decision about restarting anticoagulation.',
    references: [
      'NICE CG141: Acute upper gastrointestinal bleeding in over 16s',
      'HALT-IT Trial Collaborators. Effects of a high-dose 24-h infusion of tranexamic acid on death and thromboembolic events in patients with acute gastrointestinal bleeding. Lancet 2020',
      'Macleod’s Clinical Examination, 14th ed. — Ch. 6: gastrointestinal bleeding',
    ],
  },
}

export default c
