import type { CaseDef } from '../../engine/types'
import { COAG, FBC, lab, LFT, note, r, UE, VBG } from './helpers'

const c: CaseDef = {
  id: 'variceal-bleed',
  title: 'Oesophageal variceal haemorrhage in alcohol-related cirrhosis',
  presenting: 'Large vomit of fresh blood',
  specialty: 'Upper GI',
  exam: 'abdominal',
  difficulty: 3,
  setting: 'Emergency department',
  stem: 'Resus. Paul Whitaker, 52, has vomited a large amount of fresh blood at home. Resuscitate him, take a focused history, examine him, investigate and manage him.',
  components: ['history', 'exam', 'investigations', 'diagnosis', 'viva'],
  tags: ['upper GI bleed', 'varices', 'cirrhosis', 'alcohol', 'portal hypertension'],
  patient: {
    name: 'Paul Whitaker',
    title: 'Mr Whitaker',
    age: 52,
    sex: 'male',
    dob: '11/05/1974',
    occupation: 'an unemployed chef',
    appearance: {
      sex: 'male',
      age: 52,
      skinTone: 1,
      habitus: 'thin',
      hair: 'short',
      hairColor: 'brown',
      eyeColor: 'blue',
      facialHair: 'stubble',
      jaundice: 0.45,
      pallor: 0.5,
      sweaty: true,
      distension: 2,
      distensionType: 'fluid',
      umbilicus: 'everted',
      caputMedusae: true,
      spiderNaevi: 0.7,
      gynaecomastia: true,
      lines: { cannula: 'right-forearm', drip: true, oxygen: 'mask' },
    },
    persona: { mood: 'drowsy', style: 'brief' },
  },
  vitals: { hr: 126, rhythm: 'regular', sbp: 84, dbp: 50, rr: 24, spo2: 95, o2: '15 L/min non-rebreathe', temp: 36.2, avpu: 'V', pain: 2 },
  history: {
    opening: { text: 'I just… threw up loads of blood. Bright red. A bucketful.', cue: 'drowsy, speaks slowly, blood on his shirt' },
    answers: {
      'gi.vomiting': 'Three times since this afternoon.',
      'gi.vomit_content': 'Bright red. Clots. Loads of it.',
      'gi.melaena': 'Black stools yesterday.',
      'pain.site': 'Not really painful. My belly’s been swollen for weeks.',
      'gi.distension': 'It’s been getting bigger for a month.',
      'gi.jaundice': 'My eyes have been yellow on and off.',
      'ros.dizzy': 'Very dizzy.',
      'sh.alcohol': { text: 'A bottle of vodka a day… more some days. Since I lost my job.', cue: 'looks away' },
      'pmh.conditions': 'They told me my liver was damaged last year. I didn’t go back.',
      'pmh.gi': 'Liver damage — cirrhosis, they said. I was supposed to have a camera test.',
      'dh.meds': 'Water tablets I stopped taking. Nothing else.',
      'dh.anticoag': 'No.',
      'dh.nsaids': 'Ibuprofen sometimes.',
      'dh.allergies': 'None.',
      'sh.smoking': 'Twenty a day.',
      'sh.drugs': 'No.',
      'sh.living': 'On my own in a flat.',
      'comm.questions': 'Am I dying?',
    },
    key: ['comm.open', 'gi.vomit_content', 'gi.melaena', 'sh.alcohol', 'pmh.gi', 'gi.distension', 'gi.jaundice', 'dh.meds', 'dh.anticoag', 'dh.nsaids', 'ros.dizzy'],
    critical: ['sh.alcohol', 'pmh.gi'],
    ideas: 'It’s the drink, isn’t it.',
    concerns: 'That I’m going to die.',
    expectations: 'Stop the bleeding.',
    social: { alcohol: '~200 units a week.', smoking: '20 a day.', living: 'Alone.' },
    pmh: 'Alcohol-related cirrhosis (diagnosed last year, lost to follow-up).',
  },
  abdo: {
    general: {
      endOfBed:
        'Mr Whitaker is pale, jaundiced, sweaty and drowsy, with fresh blood on his shirt and a bowl of bright red blood and clots. His abdomen is distended. Oxygen by mask; one cannula with fluids running.',
    },
    hands: { temperature: 'cool', crt: 4, palmarErythema: true, leukonychia: true, dupuytren: true, asterixis: true, pulseVolume: 'weak' },
    face: { sclera: 'icteric', conjunctiva: 'pale', mucosa: 'dry', fetor: 'hepaticus', parotids: true },
    chest: { spiderNaevi: true, gynaecomastia: true, hairLoss: true },
    abdomen: {
      shape: 'distended',
      inspectionExtra: 'Dilated veins radiating from the umbilicus (caput medusae); everted umbilicus.',
      regions: {
        LF: note('dull'),
        RF: note('dull'),
        LIF: note('dull'),
        RIF: note('dull'),
        SP: note('dull'),
        UMB: r(0, 1, 'none', { note: 'tympanic' }),
      },
      liver: { edgeCm: 0, spanCm: 8, texture: 'nodular' },
      spleen: { tipCm: 4 },
      shiftingDullness: true,
      bowelSounds: 'hyperactive',
    },
    legs: { oedema: 'to-knee' },
    completion: { dre: 'Melaena on the glove.' },
  },
  criticalSteps: ['gen.obs', 'hands.flap', 'perc.shifting'],
  investigations: {
    fbc: { values: FBC(71, 9.8, 7.6, 64, 104), interpretation: 'Anaemia, thrombocytopenia (hypersplenism) and macrocytosis (alcohol).' },
    coag: { values: COAG(21, 1.9, 42), interpretation: 'Coagulopathy from liver synthetic failure.' },
    lft: { values: LFT(64, 58, 148, 412, 24), interpretation: 'Jaundice, low albumin — decompensated cirrhosis (Child–Pugh C).' },
    ue: { values: UE(131, 3.4, 12.2, 118, '61'), interpretation: 'Hyponatraemia; raised urea from the bleed.' },
    vbg: { values: VBG(7.29, 18, -7.2, 4.8), interpretation: 'Lactic acidosis — haemorrhagic shock (lactate also cleared poorly by the liver).' },
    xm: { report: '6 units crossmatched; FFP and platelets requested.' },
    gs: { report: 'Group O RhD positive.' },
    glucose: { values: [lab('Glucose', '3.6', 'mmol/L', '4.0–7.8', 'L')], interpretation: 'Hypoglycaemia — common in liver failure; treat.' },
    ogd: {
      report: 'Large grade 3 oesophageal varices with a white nipple sign and fresh blood. Six bands applied with haemostasis. Portal hypertensive gastropathy.',
      interpretation: 'Variceal haemorrhage controlled by band ligation.',
      abnormal: true,
    },
    'us-abdo': { report: 'Small, nodular liver; splenomegaly 16 cm; moderate ascites; patent portal vein with reduced flow.', interpretation: 'Cirrhosis with portal hypertension.', abnormal: true },
    cultures: { report: 'Sent.' },
  },
  investigationRubric: {
    essential: [
      { id: 'fbc', why: 'Hb and platelets.' },
      { id: 'coag', why: 'INR — correct and calculate Child–Pugh/MELD.' },
      { id: 'lft', why: 'Liver function.' },
      { id: 'ue', why: 'Urea, sodium, renal function (hepatorenal risk).' },
      { id: 'xm', why: 'Massive haemorrhage — crossmatch.' },
      { id: 'ogd', why: 'Urgent OGD after resuscitation — band ligation.' },
    ],
    helpful: [
      { id: 'vbg', why: 'Lactate and Hb quickly.' },
      { id: 'glucose', why: 'Hypoglycaemia in liver failure.' },
      { id: 'cultures', why: 'Infection is common and triggers bleeding.' },
      { id: 'us-abdo', why: 'Later: liver, spleen, portal vein, HCC.' },
    ],
    avoid: [{ id: 'ct-ap', why: 'Endoscopy first.' }],
  },
  diagnosis: {
    correct: 'variceal-bleed',
    accept: ['cirrhosis'],
    differentials: ['bleeding-pu', 'mallory-weiss', 'gastritis', 'gastric-cancer'],
  },
  management: {
    essential: [
      { id: 'abcde', why: 'Shocked and drowsy — protect the airway (consider intubation before endoscopy).' },
      { id: 'mhp', why: 'Major haemorrhage protocol.' },
      { id: 'iv-access', why: 'Two large-bore cannulae.' },
      { id: 'transfusion', why: 'Restrictive transfusion (target Hb ~70–80): over-transfusion raises portal pressure and worsens bleeding.' },
      { id: 'terlipressin', why: 'Vasoconstrictor that lowers portal pressure — give before endoscopy.' },
      { id: 'abx-prophylaxis', why: 'Prophylactic antibiotics reduce infection, rebleeding and death in cirrhotic bleeds.' },
      { id: 'band-ligation', why: '!Urgent endoscopic band ligation of the oesophageal varices.' },
      { id: 'senior', why: 'Gastroenterology/hepatology and ICU now.' },
      { id: 'icu', why: 'Airway protection and organ support.' },
    ],
    helpful: [
      { id: 'tipss', why: 'If banding fails: balloon tamponade as a bridge, then TIPSS.' },
      { id: 'vitamin-k', why: 'Coagulopathy (limited effect in liver disease).' },
      { id: 'alcohol-support', why: 'IV Pabrinex and withdrawal prophylaxis.' },
      { id: 'glucose-monitoring', why: 'Hypoglycaemia.' },
      { id: 'catheter', why: 'Urine output.' },
      { id: 'o2', why: 'Hypoxia.' },
    ],
    avoid: [
      { id: 'nsaid', why: 'Bleeding and renal failure in cirrhosis.' },
      { id: 'diuretics', why: 'Hypotensive and bleeding — stop them.' },
      { id: 'discharge', why: 'Life-threatening.' },
    ],
  },
  viva: [
    {
      id: 'stigmata',
      q: 'List the peripheral stigmata of chronic liver disease.',
      answer: 'Hands: leukonychia, clubbing, palmar erythema, Dupuytren’s contracture, asterixis (encephalopathy). Face: jaundice, parotid enlargement, fetor hepaticus. Chest: spider naevi, gynaecomastia, loss of body hair. Abdomen: hepatomegaly or a small liver, splenomegaly, ascites, caput medusae (Macleod’s, Ch. 6).',
      topic: 'Examination',
    },
    {
      id: 'terli',
      q: 'Which two drugs are given in suspected variceal bleeding before endoscopy?',
      options: ['Terlipressin and prophylactic antibiotics', 'IV PPI and tranexamic acid', 'Propranolol and spironolactone', 'Vitamin K and FFP only'],
      correct: 0,
      answer: 'Terlipressin (splanchnic vasoconstriction lowers portal pressure) and prophylactic antibiotics (e.g. a third-generation cephalosporin) — both reduce mortality. Tranexamic acid is not recommended.',
      topic: 'Management',
    },
    {
      id: 'portal',
      q: 'Where do portosystemic anastomoses form in portal hypertension?',
      answer: 'Lower oesophagus/gastric fundus (left gastric to oesophageal veins → varices), umbilicus (paraumbilical veins → caput medusae), rectum (superior to middle/inferior rectal veins → rectal varices) and the retroperitoneum.',
      topic: 'Anatomy',
    },
    {
      id: 'secondary',
      q: 'How do you prevent a further variceal bleed?',
      answer: 'Repeated band ligation until varices are eradicated plus a non-selective beta-blocker (propranolol or carvedilol), alcohol abstinence, and consideration of TIPSS or transplant assessment.',
      topic: 'Management',
    },
  ],
  teaching: {
    summary:
      'Variceal haemorrhage in a 52-year-old with alcohol-related cirrhosis: massive fresh haematemesis, shock and drowsiness with jaundice, stigmata of chronic liver disease, ascites, splenomegaly, thrombocytopenia and coagulopathy; terlipressin, antibiotics, restrictive transfusion and band ligation.',
    keyFindings: [
      'Large fresh haematemesis and melaena; HR 126, BP 84/50, drowsy',
      'Bottle of vodka a day; known cirrhosis lost to follow-up',
      'Jaundice, palmar erythema, Dupuytren’s, asterixis, spider naevi, gynaecomastia, caput medusae',
      'Shifting dullness (ascites) and splenomegaly',
      'Hb 71, platelets 64, INR 1.9, bilirubin 64, albumin 24',
    ],
    pearls: [
      'In any upper GI bleed, look for stigmata of liver disease — they change the management.',
      'Terlipressin and antibiotics before endoscopy save lives.',
      'Do not over-transfuse a variceal bleed.',
      'Protect the airway in a drowsy patient vomiting blood.',
    ],
    presentation:
      'Mr Whitaker is a 52-year-old man with alcohol-related cirrhosis, lost to follow-up, who drinks about a bottle of vodka a day and presents with three large vomits of fresh blood and clots and melaena. He is shocked with a pulse of 126 and BP 84/50, drowsy and confused. He is jaundiced with palmar erythema, Dupuytren’s contractures, asterixis, spider naevi, gynaecomastia and caput medusae, and has ascites with shifting dullness and splenomegaly. Hb is 71, platelets 64, INR 1.9, bilirubin 64 and albumin 24. This is a variceal haemorrhage in decompensated cirrhosis. I would activate the major haemorrhage protocol, protect his airway with ICU, give restrictive transfusion, terlipressin and prophylactic antibiotics, and arrange urgent endoscopic band ligation, with TIPSS if that fails.',
    references: ['Macleod’s Clinical Examination, 14th ed. — Ch. 6: signs of chronic liver disease and portal hypertension', 'BSG/Baveno VII guidance on variceal haemorrhage'],
  },
}

export default c
