import type { CaseDef } from '../../engine/types'
import { FBC, lab } from './helpers'

const c: CaseDef = {
  id: 'venous-ulcer',
  title: 'Great saphenous varicose veins with a venous leg ulcer (C6)',
  presenting: 'Leg ulcer and varicose veins',
  specialty: 'Vascular',
  exam: 'venous',
  difficulty: 2,
  setting: 'Outpatient clinic',
  stem: 'Vascular clinic. Beverley Grant, 58, has had an ulcer above her right ankle for two months and long-standing varicose veins. Take a history, examine her legs, request investigations and explain the management.',
  components: ['history', 'exam', 'investigations', 'diagnosis', 'viva'],
  tags: ['varicose veins', 'venous ulcer', 'CEAP', 'tourniquet test', 'Doppler'],
  patient: {
    name: 'Beverley Grant',
    title: 'Mrs Grant',
    age: 58,
    sex: 'female',
    dob: '09/10/1967',
    occupation: 'a hospital catering assistant',
    appearance: { sex: 'female', age: 58, skinTone: 2, habitus: 'overweight', hair: 'bob', hairColor: 'brown', eyeColor: 'hazel' },
    persona: { mood: 'calm', style: 'chatty' },
  },
  vitals: { hr: 74, rhythm: 'regular', sbp: 134, dbp: 80, rr: 14, spo2: 98, temp: 36.7, avpu: 'A', pain: 2 },
  visual: {
    legs: {
      right: {
        varicose: { system: 'gsv', severity: 3 },
        haemosiderin: true,
        lipodermatosclerosis: true,
        eczema: true,
        oedema: 1,
        ulcer: { kind: 'venous', site: 'gaiter', sizeCm: 3.2 },
        tourniquet: 'controlled',
        pulses: { femoral: 'normal', popliteal: 'normal', pt: 'normal', dp: 'normal' },
      },
      left: { varicose: { system: 'gsv', severity: 1 }, pulses: { femoral: 'normal', popliteal: 'normal', pt: 'normal', dp: 'normal' } },
    },
  },
  history: {
    opening: { text: 'I’ve had this sore above my right ankle for two months and it just won’t heal. I’ve had varicose veins for years.', cue: 'points to the inside of her right ankle' },
    answers: {
      'vas.ulcers': 'This one on the inside of my right ankle, for about two months. It started after I knocked it on the dishwasher.',
      'vas.veins': 'Since my second pregnancy, over twenty-five years ago. The right leg is much worse.',
      'vas.aching': 'Yes — heavy and achy by the end of a shift, and itchy around the ankle. Better when I put my feet up.',
      'vas.dvt': 'No, I’ve never had a clot.',
      'vas.claudication': 'No pain in my calves when I walk.',
      'vas.rest_pain': 'No pain at night.',
      'lump.pain': 'The ulcer stings a bit, especially at the end of the day.',
      'ros.ankles': 'My right ankle swells by the evening.',
      'pmh.conditions': 'Just my weight, and a bit of high blood pressure.',
      'pmh.diabetes': 'I’m not diabetic.',
      'pmh.clots': 'No clots.',
      'gyn.pregnant': 'Two children, both normal deliveries.',
      'dh.meds': 'Bendroflumethiazide.',
      'dh.allergies': 'No allergies.',
      'sh.smoking': 'I don’t smoke.',
      'sh.occupation': 'I’m on my feet all day in the hospital kitchen.',
      'fh.general': 'My mum had terrible varicose veins.',
      'comm.questions': 'Will it heal? Can you get rid of my veins?',
    },
    key: ['comm.open', 'vas.ulcers', 'vas.veins', 'vas.aching', 'vas.dvt', 'vas.claudication', 'vas.rest_pain', 'ros.ankles', 'pmh.diabetes', 'dh.meds', 'sh.occupation', 'sh.smoking', 'fh.general'],
    critical: ['vas.dvt', 'vas.claudication'],
    ideas: 'It’s because of my veins, isn’t it?',
    concerns: 'That it will never heal, or that I’ll need an operation.',
    expectations: 'To get it healed and stop it coming back.',
  },
  keyed: {
    'comm.pain': { text: '', says: 'The sore on my ankle stings — please be gentle there.' },
    'ven.stand': { text: 'Mrs Grant stands on the examination step, facing you.' },
    'ven.inspect': {
      text: 'Right leg: extensive tortuous varicosities along the medial thigh and calf in the distribution of the great saphenous vein. The lower third of the leg shows brown haemosiderin staining, red scaly venous eczema and firm, woody lipodermatosclerosis giving an “inverted champagne bottle” shape. Above the medial malleolus there is a 3 cm shallow ulcer with irregular sloping edges and a granulating, partly sloughy base. Mild ankle oedema. Left leg: a few small medial calf varicosities.',
      abnormal: true,
      meaning: 'Varicose veins with skin changes and an active ulcer = CEAP C6. Venous ulcers sit in the gaiter area, classically above the medial malleolus.',
    },
    'ven.back': { text: 'From behind: no varicosities in the short saphenous territory on the back of either calf.', meaning: 'Normal SSV territory — the disease is in the GSV.' },
    'ven.palpate': { text: 'The varicosities are soft and non-tender. No hard, red, tender cords (no thrombophlebitis).' },
    'ven.oedema': { text: 'Mild pitting oedema of the right ankle.', abnormal: true },
    'ven.sfj': { text: 'At the right saphenofemoral junction (2–4 cm below and lateral to the pubic tubercle) there is no saphena varix.' },
    'ven.cough': { text: 'A palpable thrill at the right SFJ on coughing.', abnormal: true, meaning: 'Suggests SFJ incompetence.' },
    'ven.tap': { text: 'Tapping the medial calf varicosity transmits an impulse to your fingers at the SFJ.', abnormal: true, meaning: 'Incompetent valves in the intervening vein.' },
    'ven.doppler': {
      text: 'Handheld Doppler at the right SFJ: on releasing calf compression there is a prolonged whoosh of reflux lasting > 1 second.',
      abnormal: true,
      media: 'doppler:reflux',
      meaning: 'Reflux > 0.5 s confirms saphenofemoral incompetence.',
    },
    'ven.tourniquet': {
      text: 'Tourniquet test: after emptying the veins with the leg raised and applying a tourniquet high on the thigh, the varicosities stay empty on standing; on release they fill rapidly from above.',
      abnormal: true,
      meaning: 'Controlled by a high-thigh tourniquet → the incompetence is at the SFJ.',
    },
    'ven.pulses': { text: 'Femoral, popliteal, posterior tibial and dorsalis pedis pulses are present bilaterally.', meaning: 'Palpable pulses make significant arterial disease unlikely — but an ABPI is still needed before compression.' },
    'complete.duplex': { text: 'Venous duplex requested to map the reflux and plan treatment.' },
    'complete.abpi': { text: 'Handheld Doppler at the ankles: triphasic signals. ABPI right 1.02, left 1.05 — compression is safe.', media: 'doppler:triphasic' },
    'complete.abdomen': { text: 'Abdomen soft; no pelvic masses.' },
  },
  criticalSteps: ['st.stand', 'st.inspect', 'sp.pulses'],
  investigations: {
    abpi: { report: 'ABPI right 1.02, left 1.05 with triphasic signals.', interpretation: 'No significant arterial disease — full compression is safe.' },
    'duplex-venous': {
      report: 'Right: incompetent saphenofemoral junction with reflux (3.2 s) along the great saphenous vein to below the knee, feeding the medial calf varicosities. Competent saphenopopliteal junction. Deep veins patent and competent; no evidence of previous DVT. Left: minor below-knee GSV tributary reflux.',
      interpretation: 'Primary superficial venous reflux (right SFJ/GSV) — suitable for endovenous ablation.',
      abnormal: true,
    },
    fbc: { values: FBC(134, 7.2, 4.5, 260, 88, 'female'), interpretation: 'Normal.' },
    glucose: { values: [lab('Glucose (random)', '5.9', 'mmol/L', '4.0–7.8')], interpretation: 'No diabetes.' },
  },
  investigationRubric: {
    essential: [
      { id: 'abpi', why: '!ABPI before any compression therapy to exclude arterial disease.' },
      { id: 'duplex-venous', why: 'NICE CG168: duplex ultrasound to confirm the diagnosis and map reflux.' },
    ],
    helpful: [{ id: 'glucose', why: 'Diabetes impairs ulcer healing.' }, { id: 'fbc', why: 'Anaemia impairs healing.' }],
    avoid: [{ id: 'cta', why: 'Arterial CT angiography is not indicated with palpable pulses and a normal ABPI.' }],
  },
  diagnosis: { correct: 'venous-ulcer', accept: ['varicose-veins'], differentials: ['arterial-ulcer', 'diabetic-foot', 'dvt', 'clti'] },
  management: {
    essential: [
      { id: 'compression', why: 'Multilayer compression bandaging (after ABPI) is the cornerstone of venous ulcer healing.' },
      { id: 'endovenous', why: 'Early endovenous ablation of superficial reflux speeds healing and reduces recurrence (EVRA trial).' },
    ],
    helpful: [
      { id: 'lifestyle', why: 'Leg elevation, weight loss, keep mobile; emollients and topical steroid for eczema.' },
      { id: 'reassure', why: 'Explain the cause and likely healing time; compression stockings long term to prevent recurrence.' },
    ],
    avoid: [{ id: 'abx-oral', why: 'Antibiotics only for clinical infection (spreading cellulitis) — not for colonised ulcers.' }],
  },
  viva: [
    {
      id: 'ceap',
      q: 'What is her CEAP clinical class?',
      options: ['C2 — varicose veins', 'C3 — oedema', 'C4 — skin changes', 'C6 — active venous ulcer'],
      correct: 3,
      answer: 'CEAP clinical class: C0 no signs; C1 telangiectasia/reticular veins; C2 varicose veins (≥ 3 mm); C3 oedema; C4 skin changes (C4a pigmentation/eczema, C4b lipodermatosclerosis/atrophie blanche, C4c corona phlebectatica); C5 healed ulcer; C6 active ulcer. She is C6.',
      topic: 'Classification',
    },
    {
      id: 'refer',
      q: 'According to NICE (CG168), which patients with varicose veins should be referred to a vascular service?',
      answer: 'Symptomatic primary or recurrent varicose veins; lower-limb skin changes (pigmentation, eczema) thought to be due to chronic venous insufficiency; superficial vein thrombosis with suspected venous incompetence; a venous leg ulcer (active or healed). Refer those who have bled from varicosities urgently.',
      topic: 'Guidelines',
    },
    {
      id: 'trendelenburg',
      q: 'Describe the tourniquet (Trendelenburg) test.',
      answer: 'With the patient lying, elevate the leg to empty the superficial veins. Apply a tourniquet just below the saphenofemoral junction and ask the patient to stand. If the varicosities stay empty, the SFJ is the site of incompetence (confirmed by rapid filling on release). If they fill despite the tourniquet, the incompetence is below it — repeat lower down (mid-thigh perforators, SPJ). Largely replaced by handheld Doppler and duplex.',
      topic: 'Examination',
    },
    {
      id: 'ablation',
      q: 'What is the first-line intervention for truncal varicose veins?',
      answer: 'Endothermal ablation (radiofrequency or endovenous laser); if unsuitable, ultrasound-guided foam sclerotherapy; if unsuitable, open surgery (high tie and stripping). Compression hosiery is only offered if interventional treatment is unsuitable (NICE CG168).',
      topic: 'Management',
    },
  ],
  teaching: {
    summary:
      'Long-standing right GSV varicose veins with haemosiderin, eczema, lipodermatosclerosis and a shallow gaiter-area ulcer above the medial malleolus, palpable pulses, and SFJ reflux on Doppler controlled by a high-thigh tourniquet — a venous leg ulcer (CEAP C6). Treat with compression (after ABPI) and early endovenous ablation.',
    keyFindings: [
      'Tortuous varicosities in the GSV territory (medial thigh and calf)',
      'Haemosiderin, venous eczema, lipodermatosclerosis',
      'Shallow, irregular, granulating ulcer above the medial malleolus',
      'Cough thrill and Doppler reflux at the SFJ; tourniquet-controlled',
      'All pulses palpable; ABPI normal',
    ],
    pearls: [
      'Examine varicose veins STANDING — they empty when the patient lies down.',
      'Look at the back of the calves for the short saphenous system.',
      'Always feel the pulses and check an ABPI before compression.',
      'GSV: medial leg to the SFJ in the groin; SSV: posterolateral calf to the SPJ behind the knee.',
    ],
    presentation:
      'I examined Mrs Beverley Grant, a 58-year-old woman, standing. On the right leg there are extensive tortuous varicosities along the medial thigh and calf in the distribution of the great saphenous vein, with haemosiderin staining, venous eczema and lipodermatosclerosis of the lower third of the leg and mild ankle oedema. Above the right medial malleolus there is a 3 cm shallow ulcer with irregular sloping edges and a granulating, partly sloughy base. The varicosities are soft and non-tender, and there is no varicosity in the short saphenous territory. There is a cough thrill at the right saphenofemoral junction and a positive tap test; handheld Doppler shows reflux at the SFJ, and the tourniquet test is controlled by a high-thigh tourniquet. All peripheral pulses are palpable. These findings are consistent with right great saphenous vein incompetence with an active venous leg ulcer, CEAP C6. I would request an ABPI and a venous duplex scan.',
    references: ['Macleod’s Clinical Examination, 14th ed. — Ch. 5: examination of the veins', 'NICE CG168: Varicose veins — diagnosis and management', 'EVRA trial, NEJM 2018'],
  },
}

export default c
