export interface DiagnosisDef {
  id: string
  name: string
  group: string
  aka?: string[]
}

/** Differential-diagnosis vocabulary for the diagnosis picker. */
export const DIAGNOSES: DiagnosisDef[] = [
  // Acute abdomen
  { id: 'appendicitis', name: 'Acute appendicitis', group: 'Acute abdomen' },
  { id: 'appendix-mass', name: 'Appendix mass / abscess', group: 'Acute abdomen' },
  { id: 'mesenteric-adenitis', name: 'Mesenteric adenitis', group: 'Acute abdomen' },
  { id: 'cholecystitis', name: 'Acute cholecystitis', group: 'Hepatobiliary' },
  { id: 'biliary-colic', name: 'Biliary colic', group: 'Hepatobiliary' },
  { id: 'cholangitis', name: 'Ascending cholangitis', group: 'Hepatobiliary' },
  { id: 'choledocholithiasis', name: 'Choledocholithiasis (CBD stones)', group: 'Hepatobiliary' },
  { id: 'pancreatitis', name: 'Acute pancreatitis', group: 'Hepatobiliary' },
  { id: 'chronic-pancreatitis', name: 'Chronic pancreatitis', group: 'Hepatobiliary' },
  { id: 'pancreatic-cancer', name: 'Carcinoma of the head of pancreas', group: 'Hepatobiliary', aka: ['pancreatic cancer'] },
  { id: 'cholangiocarcinoma', name: 'Cholangiocarcinoma', group: 'Hepatobiliary' },
  { id: 'liver-mets', name: 'Liver metastases', group: 'Hepatobiliary' },
  { id: 'cirrhosis', name: 'Chronic liver disease / cirrhosis with ascites', group: 'Hepatobiliary' },
  { id: 'hepatitis', name: 'Acute hepatitis', group: 'Hepatobiliary' },
  { id: 'perforated-pu', name: 'Perforated peptic ulcer', group: 'Upper GI' },
  { id: 'peptic-ulcer', name: 'Peptic ulcer disease', group: 'Upper GI' },
  { id: 'gastritis', name: 'Gastritis', group: 'Upper GI' },
  { id: 'gastric-cancer', name: 'Gastric carcinoma', group: 'Upper GI' },
  { id: 'goo', name: 'Gastric outlet obstruction', group: 'Upper GI' },
  { id: 'boerhaave', name: 'Oesophageal rupture (Boerhaave’s)', group: 'Upper GI' },
  { id: 'bleeding-pu', name: 'Bleeding peptic ulcer', group: 'Upper GI', aka: ['upper GI bleed'] },
  { id: 'variceal-bleed', name: 'Oesophageal variceal haemorrhage', group: 'Upper GI' },
  { id: 'mallory-weiss', name: 'Mallory–Weiss tear', group: 'Upper GI' },
  { id: 'oesophageal-cancer', name: 'Oesophageal carcinoma', group: 'Upper GI', aka: ['oesophageal adenocarcinoma'] },
  { id: 'achalasia', name: 'Achalasia', group: 'Upper GI' },
  { id: 'peptic-stricture', name: 'Benign peptic oesophageal stricture', group: 'Upper GI' },
  { id: 'gord', name: 'Gastro-oesophageal reflux disease', group: 'Upper GI', aka: ['GORD', 'reflux'] },
  { id: 'pharyngeal-pouch', name: 'Pharyngeal pouch (Zenker’s diverticulum)', group: 'Upper GI' },
  { id: 'marginal-ulcer', name: 'Marginal (anastomotic) ulcer after gastric bypass', group: 'Upper GI' },
  { id: 'sbo-adhesions', name: 'Small bowel obstruction — adhesions', group: 'Obstruction' },
  { id: 'sbo-hernia', name: 'Small bowel obstruction — obstructed hernia', group: 'Obstruction' },
  { id: 'lbo-cancer', name: 'Large bowel obstruction — colorectal cancer', group: 'Obstruction' },
  { id: 'sigmoid-volvulus', name: 'Sigmoid volvulus', group: 'Obstruction' },
  { id: 'caecal-volvulus', name: 'Caecal volvulus', group: 'Obstruction' },
  { id: 'pseudo-obstruction', name: 'Pseudo-obstruction (Ogilvie’s)', group: 'Obstruction' },
  { id: 'ileus', name: 'Paralytic ileus', group: 'Obstruction' },
  { id: 'internal-hernia', name: 'Internal hernia (after gastric bypass)', group: 'Obstruction' },
  { id: 'diverticulitis', name: 'Acute diverticulitis', group: 'Colorectal' },
  { id: 'diverticular-abscess', name: 'Diverticular abscess', group: 'Colorectal' },
  { id: 'perforated-diverticulitis', name: 'Perforated diverticulitis / faecal peritonitis', group: 'Colorectal' },
  { id: 'colorectal-cancer', name: 'Colorectal carcinoma', group: 'Colorectal' },
  { id: 'caecal-cancer', name: 'Caecal carcinoma', group: 'Colorectal' },
  { id: 'crohns', name: 'Crohn’s disease', group: 'Colorectal' },
  { id: 'uc', name: 'Ulcerative colitis', group: 'Colorectal' },
  { id: 'ischaemic-colitis', name: 'Ischaemic colitis', group: 'Colorectal' },
  { id: 'gastroenteritis', name: 'Gastroenteritis', group: 'Colorectal' },
  { id: 'ibs', name: 'Irritable bowel syndrome', group: 'Colorectal' },
  { id: 'constipation', name: 'Constipation', group: 'Colorectal' },
  { id: 'diverticular-bleed', name: 'Diverticular bleeding', group: 'Colorectal' },
  { id: 'c-diff', name: 'Clostridioides difficile colitis', group: 'Colorectal' },
  { id: 'mesenteric-ischaemia', name: 'Acute mesenteric ischaemia', group: 'Vascular' },
  { id: 'aaa-rupture', name: 'Ruptured abdominal aortic aneurysm', group: 'Vascular', aka: ['leaking AAA'] },
  { id: 'aaa', name: 'Abdominal aortic aneurysm (intact)', group: 'Vascular' },
  { id: 'aortic-dissection', name: 'Aortic dissection', group: 'Vascular' },
  { id: 'pad', name: 'Peripheral arterial disease — intermittent claudication', group: 'Vascular' },
  { id: 'clti', name: 'Chronic limb-threatening ischaemia', group: 'Vascular', aka: ['critical limb ischaemia'] },
  { id: 'ali', name: 'Acute limb ischaemia', group: 'Vascular' },
  { id: 'varicose-veins', name: 'Varicose veins (GSV incompetence)', group: 'Vascular' },
  { id: 'venous-ulcer', name: 'Venous leg ulcer', group: 'Vascular' },
  { id: 'arterial-ulcer', name: 'Arterial leg ulcer', group: 'Vascular' },
  { id: 'diabetic-foot', name: 'Diabetic foot ulcer', group: 'Vascular' },
  { id: 'dvt', name: 'Deep vein thrombosis', group: 'Vascular' },
  // Urology
  { id: 'renal-colic', name: 'Renal / ureteric colic', group: 'Urology' },
  { id: 'pyelonephritis', name: 'Acute pyelonephritis', group: 'Urology' },
  { id: 'uti', name: 'Lower urinary tract infection / cystitis', group: 'Urology' },
  { id: 'urinary-retention', name: 'Acute urinary retention', group: 'Urology' },
  { id: 'testicular-torsion', name: 'Testicular torsion', group: 'Urology' },
  { id: 'epididymo-orchitis', name: 'Epididymo-orchitis', group: 'Urology' },
  { id: 'testicular-tumour', name: 'Testicular tumour', group: 'Urology' },
  { id: 'hydrocele', name: 'Hydrocele', group: 'Urology' },
  { id: 'varicocele', name: 'Varicocele', group: 'Urology' },
  { id: 'epididymal-cyst', name: 'Epididymal cyst', group: 'Urology' },
  { id: 'torsion-hydatid', name: 'Torsion of the hydatid of Morgagni', group: 'Urology' },
  // Gynae
  { id: 'ectopic', name: 'Ectopic pregnancy', group: 'Gynaecology' },
  { id: 'ovarian-torsion', name: 'Ovarian torsion', group: 'Gynaecology' },
  { id: 'ovarian-cyst', name: 'Ruptured / haemorrhagic ovarian cyst', group: 'Gynaecology' },
  { id: 'pid', name: 'Pelvic inflammatory disease', group: 'Gynaecology' },
  { id: 'endometriosis', name: 'Endometriosis', group: 'Gynaecology' },
  // Hernia
  { id: 'indirect-ih', name: 'Indirect inguinal hernia', group: 'Hernia' },
  { id: 'direct-ih', name: 'Direct inguinal hernia', group: 'Hernia' },
  { id: 'femoral-hernia', name: 'Femoral hernia', group: 'Hernia' },
  { id: 'strangulated-hernia', name: 'Strangulated / incarcerated hernia', group: 'Hernia' },
  { id: 'umbilical-hernia', name: 'Umbilical / paraumbilical hernia', group: 'Hernia' },
  { id: 'incisional-hernia', name: 'Incisional hernia', group: 'Hernia' },
  { id: 'epigastric-hernia', name: 'Epigastric hernia', group: 'Hernia' },
  { id: 'divarication', name: 'Divarication of the recti', group: 'Hernia' },
  { id: 'saphena-varix', name: 'Saphena varix', group: 'Hernia' },
  { id: 'inguinal-lymph', name: 'Inguinal lymphadenopathy', group: 'Hernia' },
  { id: 'femoral-aneurysm', name: 'Femoral artery aneurysm', group: 'Hernia' },
  { id: 'hydrocele-cord', name: 'Hydrocele of the cord', group: 'Hernia' },
  // Lumps & skin
  { id: 'lipoma', name: 'Lipoma', group: 'Lumps' },
  { id: 'epidermoid-cyst', name: 'Epidermoid (sebaceous) cyst', group: 'Lumps' },
  { id: 'abscess', name: 'Abscess', group: 'Lumps' },
  { id: 'reactive-node', name: 'Reactive lymphadenopathy', group: 'Lumps' },
  { id: 'lymphoma', name: 'Lymphoma', group: 'Lumps' },
  { id: 'metastatic-node', name: 'Metastatic lymph node', group: 'Lumps' },
  { id: 'sarcoma', name: 'Soft-tissue sarcoma', group: 'Lumps' },
  { id: 'ganglion', name: 'Ganglion', group: 'Lumps' },
  { id: 'dermatofibroma', name: 'Dermatofibroma', group: 'Lumps' },
  { id: 'melanoma', name: 'Malignant melanoma', group: 'Lumps' },
  { id: 'bcc', name: 'Basal cell carcinoma', group: 'Lumps' },
  // Neck & endocrine
  { id: 'mng', name: 'Multinodular goitre', group: 'Neck & endocrine' },
  { id: 'graves', name: 'Graves’ disease', group: 'Neck & endocrine' },
  { id: 'toxic-mng', name: 'Toxic multinodular goitre', group: 'Neck & endocrine' },
  { id: 'solitary-nodule', name: 'Solitary thyroid nodule', group: 'Neck & endocrine' },
  { id: 'thyroid-cancer', name: 'Thyroid carcinoma (papillary)', group: 'Neck & endocrine' },
  { id: 'thyroglossal-cyst', name: 'Thyroglossal duct cyst', group: 'Neck & endocrine' },
  { id: 'branchial-cyst', name: 'Branchial cyst', group: 'Neck & endocrine' },
  { id: 'hashimoto', name: 'Hashimoto’s thyroiditis', group: 'Neck & endocrine' },
  { id: 'salivary-tumour', name: 'Pleomorphic adenoma (parotid)', group: 'Neck & endocrine' },
  // Breast
  { id: 'fibroadenoma', name: 'Fibroadenoma', group: 'Breast' },
  { id: 'breast-cancer', name: 'Breast carcinoma', group: 'Breast' },
  { id: 'breast-cyst', name: 'Breast cyst', group: 'Breast' },
  { id: 'breast-abscess', name: 'Breast abscess / mastitis', group: 'Breast' },
  { id: 'fibrocystic', name: 'Fibrocystic change', group: 'Breast' },
  { id: 'fat-necrosis', name: 'Fat necrosis', group: 'Breast' },
  { id: 'duct-ectasia', name: 'Duct ectasia', group: 'Breast' },
  { id: 'intraductal-papilloma', name: 'Intraductal papilloma', group: 'Breast' },
  { id: 'phyllodes', name: 'Phyllodes tumour', group: 'Breast' },
  // Anorectal
  { id: 'haemorrhoids', name: 'Haemorrhoids', group: 'Anorectal' },
  { id: 'fissure', name: 'Anal fissure', group: 'Anorectal' },
  { id: 'perianal-abscess', name: 'Perianal abscess', group: 'Anorectal' },
  { id: 'fistula', name: 'Fistula-in-ano', group: 'Anorectal' },
  { id: 'pilonidal', name: 'Pilonidal sinus / abscess', group: 'Anorectal' },
  { id: 'rectal-cancer', name: 'Rectal carcinoma', group: 'Anorectal' },
  { id: 'thrombosed-haemorrhoid', name: 'Thrombosed external haemorrhoid (perianal haematoma)', group: 'Anorectal' },
  { id: 'fournier', name: 'Fournier’s gangrene', group: 'Anorectal' },
  // Post-operative
  { id: 'anastomotic-leak', name: 'Anastomotic leak', group: 'Post-operative' },
  { id: 'atelectasis', name: 'Post-operative atelectasis', group: 'Post-operative' },
  { id: 'ssi', name: 'Surgical site (wound) infection', group: 'Post-operative' },
  { id: 'pe', name: 'Pulmonary embolism', group: 'Post-operative' },
  // Medical mimics
  { id: 'mi', name: 'Inferior myocardial infarction', group: 'Medical mimics' },
  { id: 'lower-lobe-pneumonia', name: 'Lower lobe pneumonia', group: 'Medical mimics' },
  { id: 'dka', name: 'Diabetic ketoacidosis', group: 'Medical mimics' },
  { id: 'hypercalcaemia', name: 'Hypercalcaemia', group: 'Medical mimics' },
  { id: 'sickle-crisis', name: 'Sickle cell crisis', group: 'Medical mimics' },
  { id: 'porphyria', name: 'Acute intermittent porphyria', group: 'Medical mimics' },
  { id: 'rectus-haematoma', name: 'Rectus sheath haematoma', group: 'Medical mimics' },
  { id: 'hyperthyroidism', name: 'Hyperthyroidism', group: 'Neck & endocrine' },
  { id: 'stoma-ileostomy', name: 'End ileostomy (e.g. after panproctocolectomy)', group: 'Stoma' },
  { id: 'stoma-colostomy', name: 'End colostomy (e.g. after Hartmann’s)', group: 'Stoma' },
]

export const DIAG_BY_ID: Record<string, DiagnosisDef> = Object.fromEntries(DIAGNOSES.map((d) => [d.id, d]))
