export interface MgmtDef {
  id: string
  label: string
  group: 'Resuscitation & supportive' | 'Medication' | 'Escalation & referral' | 'Procedures & operations' | 'Conservative & follow-up'
}

export const MANAGEMENT: MgmtDef[] = [
  // Resuscitation & supportive
  { id: 'abcde', label: 'ABCDE assessment and resuscitation', group: 'Resuscitation & supportive' },
  { id: 'o2', label: 'Oxygen to target saturations (94–98%)', group: 'Resuscitation & supportive' },
  { id: 'iv-access', label: 'Two large-bore IV cannulae', group: 'Resuscitation & supportive' },
  { id: 'fluids', label: 'IV crystalloid fluid resuscitation', group: 'Resuscitation & supportive' },
  { id: 'maintenance-fluids', label: 'IV maintenance fluids with electrolyte replacement', group: 'Resuscitation & supportive' },
  { id: 'mhp', label: 'Activate the major haemorrhage protocol / O-negative blood', group: 'Resuscitation & supportive' },
  { id: 'permissive-hypotension', label: 'Permissive hypotension (target SBP ~70–90 mmHg) until the bleeding is controlled', group: 'Resuscitation & supportive' },
  { id: 'nbm', label: 'Nil by mouth', group: 'Resuscitation & supportive' },
  { id: 'ng', label: 'Nasogastric tube on free drainage', group: 'Resuscitation & supportive' },
  { id: 'catheter', label: 'Urinary catheter with hourly urine output monitoring', group: 'Resuscitation & supportive' },
  { id: 'fluid-balance', label: 'Strict fluid-balance chart', group: 'Resuscitation & supportive' },
  { id: 'sepsis6', label: 'Sepsis Six within 1 hour (O₂, cultures, antibiotics, fluids, lactate, urine output)', group: 'Resuscitation & supportive' },
  { id: 'vte', label: 'VTE prophylaxis (LMWH ± compression stockings, if no contraindication)', group: 'Resuscitation & supportive' },
  { id: 'glucose-monitoring', label: 'Monitor blood glucose', group: 'Resuscitation & supportive' },
  { id: 'nutrition', label: 'Early nutritional support (enteral if possible)', group: 'Resuscitation & supportive' },

  // Medication
  { id: 'analgesia', label: 'Analgesia (paracetamol ± opioid, titrated to pain)', group: 'Medication' },
  { id: 'antiemetic', label: 'Antiemetic', group: 'Medication' },
  { id: 'abx-iv', label: 'IV broad-spectrum antibiotics per local guidelines', group: 'Medication' },
  { id: 'abx-oral', label: 'Oral antibiotics', group: 'Medication' },
  { id: 'ppi-iv', label: 'IV proton pump inhibitor', group: 'Medication' },
  { id: 'anticoag-heparin', label: 'IV unfractionated heparin', group: 'Medication' },
  { id: 'nsaid', label: 'NSAID (e.g. diclofenac)', group: 'Medication' },
  { id: 'laxatives', label: 'Laxatives', group: 'Medication' },
  { id: 'carbimazole', label: 'Carbimazole (antithyroid drug)', group: 'Medication' },
  { id: 'propranolol', label: 'Propranolol for symptom control', group: 'Medication' },
  { id: 'statin-antiplatelet', label: 'Best medical therapy: statin + antiplatelet, BP & diabetes control', group: 'Medication' },
  { id: 'smoking-cessation', label: 'Smoking cessation support', group: 'Medication' },
  { id: 'abx-epididymo', label: 'Antibiotics for epididymo-orchitis (e.g. ceftriaxone + doxycycline)', group: 'Medication' },
  { id: 'topical-gtn', label: 'Topical GTN/diltiazem, stool softeners, fibre', group: 'Medication' },
  { id: 'iron', label: 'Iron replacement (oral or IV)', group: 'Medication' },
  { id: 'vitamin-k', label: 'IV vitamin K (correct coagulopathy)', group: 'Medication' },
  { id: 'diuretics', label: 'Spironolactone ± furosemide with dietary salt restriction', group: 'Medication' },
  { id: 'transfusion', label: 'Red cell transfusion', group: 'Resuscitation & supportive' },

  // Escalation
  { id: 'senior', label: 'Inform the surgical registrar / consultant', group: 'Escalation & referral' },
  { id: 'theatre', label: 'Inform theatres & anaesthetist (book emergency theatre)', group: 'Escalation & referral' },
  { id: 'vascular', label: 'Immediate vascular surgery referral', group: 'Escalation & referral' },
  { id: 'icu', label: 'Critical care (HDU/ICU) referral', group: 'Escalation & referral' },
  { id: 'gynae', label: 'Gynaecology review', group: 'Escalation & referral' },
  { id: 'urology', label: 'Urology review', group: 'Escalation & referral' },
  { id: 'gastro-ercp', label: 'Refer to gastroenterology for ERCP', group: 'Escalation & referral' },
  { id: 'mdt', label: 'Discuss at the multidisciplinary team (MDT) meeting', group: 'Escalation & referral' },
  { id: '2ww', label: 'Urgent suspected-cancer (2-week-wait) pathway', group: 'Escalation & referral' },
  { id: 'consent', label: 'Explain, gain written consent and mark for surgery', group: 'Escalation & referral' },
  { id: 'breaking-news', label: 'Communicate the diagnosis sensitively and involve family', group: 'Escalation & referral' },

  // Procedures
  { id: 'lap-appendicectomy', label: 'Laparoscopic appendicectomy', group: 'Procedures & operations' },
  { id: 'lap-chole-early', label: 'Early laparoscopic cholecystectomy (index admission, ideally within 1 week)', group: 'Procedures & operations' },
  { id: 'lap-chole-interval', label: 'Delayed (interval) cholecystectomy after 6 weeks', group: 'Procedures & operations' },
  { id: 'ercp', label: 'ERCP with sphincterotomy and stone extraction', group: 'Procedures & operations' },
  { id: 'biliary-decompression', label: 'Urgent biliary decompression (ERCP or PTC)', group: 'Procedures & operations' },
  { id: 'biliary-stent', label: 'Endoscopic biliary stent to relieve jaundice (if appropriate)', group: 'Procedures & operations' },
  { id: 'laparotomy', label: 'Emergency laparotomy', group: 'Procedures & operations' },
  { id: 'perforation-repair', label: 'Laparoscopic / open repair of perforation with omental patch & washout', group: 'Procedures & operations' },
  { id: 'hernia-emergency', label: 'Emergency hernia repair ± bowel resection', group: 'Procedures & operations' },
  { id: 'hernia-elective', label: 'Elective hernia repair (e.g. mesh repair)', group: 'Procedures & operations' },
  { id: 'aaa-repair-emergency', label: 'Emergency AAA repair (EVAR if anatomy suitable, or open)', group: 'Procedures & operations' },
  { id: 'aaa-repair-elective', label: 'Elective AAA repair', group: 'Procedures & operations' },
  { id: 'revascularisation', label: 'Revascularisation (angioplasty / bypass)', group: 'Procedures & operations' },
  { id: 'embolectomy', label: 'Embolectomy / thrombolysis / revascularisation', group: 'Procedures & operations' },
  { id: 'hartmanns', label: 'Hartmann’s procedure', group: 'Procedures & operations' },
  { id: 'drainage-radiological', label: 'Radiologically guided percutaneous drainage', group: 'Procedures & operations' },
  { id: 'flexi-decompression', label: 'Endoscopic decompression and flatus tube', group: 'Procedures & operations' },
  { id: 'whipple', label: 'Staging, then consider pancreaticoduodenectomy (Whipple’s) if resectable', group: 'Procedures & operations' },
  { id: 'triple-assessment', label: 'Triple assessment (clinical, imaging, biopsy)', group: 'Procedures & operations' },
  { id: 'excision', label: 'Excision (with histology)', group: 'Procedures & operations' },
  { id: 'incision-drainage', label: 'Incision and drainage', group: 'Procedures & operations' },
  { id: 'scrotal-exploration', label: 'Urgent scrotal exploration with detorsion and bilateral fixation', group: 'Procedures & operations' },
  { id: 'orchidectomy-inguinal', label: 'Radical inguinal orchidectomy', group: 'Procedures & operations' },
  { id: 'scrotal-biopsy', label: 'Trans-scrotal biopsy of the testis', group: 'Procedures & operations' },
  { id: 'thyroidectomy', label: 'Thyroid surgery (hemi- or total thyroidectomy)', group: 'Procedures & operations' },
  { id: 'fna-thyroid', label: 'Ultrasound-guided FNA of the nodule', group: 'Procedures & operations' },
  { id: 'endovenous', label: 'Endovenous (thermal) ablation', group: 'Procedures & operations' },
  { id: 'compression', label: 'Compression therapy (stockings / multilayer bandaging)', group: 'Procedures & operations' },
  { id: 'amputation', label: 'Amputation', group: 'Procedures & operations' },
  { id: 'right-hemicolectomy', label: 'Right hemicolectomy (after staging and MDT)', group: 'Procedures & operations' },
  { id: 'ascitic-tap', label: 'Diagnostic ascitic tap (cell count, albumin/SAAG, culture)', group: 'Procedures & operations' },
  { id: 'varices-screen', label: 'OGD to screen for oesophageal varices', group: 'Procedures & operations' },
  { id: 'hcc-surveillance', label: 'HCC surveillance: 6-monthly ultrasound ± AFP', group: 'Conservative & follow-up' },
  { id: 'stoma-nurse', label: 'Stoma nurse specialist review and patient education', group: 'Conservative & follow-up' },

  // Conservative
  { id: 'drip-suck', label: 'Conservative “drip and suck” with regular review', group: 'Conservative & follow-up' },
  { id: 'gastrografin', label: 'Water-soluble contrast (Gastrografin) challenge', group: 'Conservative & follow-up' },
  { id: 'observe', label: 'Admit for observation and serial examination', group: 'Conservative & follow-up' },
  { id: 'discharge', label: 'Discharge home', group: 'Conservative & follow-up' },
  { id: 'reassure', label: 'Reassure, explain and safety-net', group: 'Conservative & follow-up' },
  { id: 'watchful-waiting', label: 'Watchful waiting', group: 'Conservative & follow-up' },
  { id: 'surveillance', label: 'Ultrasound surveillance', group: 'Conservative & follow-up' },
  { id: 'exercise', label: 'Supervised exercise programme', group: 'Conservative & follow-up' },
  { id: 'diet-normal', label: 'Allow normal diet', group: 'Conservative & follow-up' },
  { id: 'lifestyle', label: 'Lifestyle advice (weight loss, alcohol, diet)', group: 'Conservative & follow-up' },
  { id: 'alcohol-support', label: 'Alcohol cessation support ± Pabrinex / withdrawal prophylaxis', group: 'Conservative & follow-up' },
  { id: 'palliative', label: 'Early palliative care involvement', group: 'Conservative & follow-up' },
  // Schedule topics
  { id: 'leak-control', label: 'Control the leak: return to theatre (washout, drain ± repair) or endoscopic stent/drainage', group: 'Procedures & operations' },
  { id: 'relook', label: 'Return to theatre: laparotomy / laparoscopy, washout, resect or defunction', group: 'Procedures & operations' },
  { id: 'bariatric-mdt', label: 'Bariatric MDT assessment (surgeon, dietitian, psychologist, physician, anaesthetist)', group: 'Escalation & referral' },
  { id: 'tier3', label: 'Tier 3 specialist weight management (diet, activity, behaviour ± GLP-1 agonist)', group: 'Conservative & follow-up' },
  { id: 'bariatric-surgery', label: 'Bariatric surgery (sleeve gastrectomy or Roux-en-Y gastric bypass)', group: 'Procedures & operations' },
  { id: 'lifelong-supplements', label: 'Lifelong vitamin & mineral supplements and annual bloods after bariatric surgery', group: 'Conservative & follow-up' },
  { id: 'ogd-haemostasis', label: 'Urgent OGD with endoscopic haemostasis (adrenaline + clips / thermal)', group: 'Procedures & operations' },
  { id: 'terlipressin', label: 'Terlipressin (vasoconstrictor) before endoscopy', group: 'Medication' },
  { id: 'abx-prophylaxis', label: 'Prophylactic IV antibiotics (variceal bleed in cirrhosis)', group: 'Medication' },
  { id: 'band-ligation', label: 'Endoscopic variceal band ligation', group: 'Procedures & operations' },
  { id: 'tipss', label: 'Balloon tamponade as a bridge; TIPSS if bleeding cannot be controlled', group: 'Procedures & operations' },
  { id: 'h-pylori', label: 'Test for and eradicate Helicobacter pylori', group: 'Medication' },
  { id: 'ppi-oral', label: 'Oral proton pump inhibitor', group: 'Medication' },
  { id: 'hold-anticoag', label: 'Withhold anticoagulants / antiplatelets and reverse if needed', group: 'Medication' },
  { id: 'ir-embolisation', label: 'CT angiography, then interventional radiology embolisation', group: 'Procedures & operations' },
  { id: 'colonoscopy-later', label: 'Colonoscopy once the bleeding has settled', group: 'Conservative & follow-up' },
  { id: 'heller', label: 'Laparoscopic Heller myotomy with partial fundoplication (or POEM / pneumatic dilatation)', group: 'Procedures & operations' },
  { id: 'oesophagectomy', label: 'Staging, MDT, neoadjuvant chemo(radio)therapy then oesophagectomy if fit and resectable', group: 'Procedures & operations' },
  { id: 'gastrectomy', label: 'Staging, MDT, perioperative chemotherapy then gastrectomy if resectable', group: 'Procedures & operations' },
  { id: 'dietitian', label: 'Dietitian review: nutritional support and supplements', group: 'Conservative & follow-up' },
  { id: 'albendazole', label: 'Albendazole, then surgical removal or PAIR (without spilling the cyst)', group: 'Medication' },
  { id: 'eua-drainage', label: 'Examination under anaesthesia with incision and drainage (no primary fistulotomy if unsure)', group: 'Procedures & operations' },
  { id: 'piles-conservative', label: 'Analgesia, stool softeners, warm baths, ice / topical agents; review', group: 'Conservative & follow-up' },
  { id: 'haemorrhoidectomy', label: 'Haemorrhoidectomy (urgent excision only if seen within ~72 h)', group: 'Procedures & operations' },
  { id: 'botox-lis', label: 'Botulinum toxin or lateral internal sphincterotomy if a chronic fissure fails to heal', group: 'Procedures & operations' },
  { id: 'microdochectomy', label: 'Microdochectomy (excision of the discharging duct) with histology', group: 'Procedures & operations' },
  { id: 'chest-physio', label: 'Chest physiotherapy, sitting up and incentive spirometry', group: 'Resuscitation & supportive' },
  { id: 'treatment-anticoag', label: 'Treatment-dose anticoagulation', group: 'Medication' },
  { id: 'taxis', label: 'Attempt manual reduction of the hernia (taxis)', group: 'Procedures & operations' },
  { id: 'cpap', label: 'Start CPAP for obstructive sleep apnoea before surgery', group: 'Escalation & referral' },
  { id: 'thyroid-rai', label: 'Total thyroidectomy with neck dissection, then radioiodine as advised by the MDT', group: 'Procedures & operations' },
  { id: 'laryngoscopy', label: 'Pre-operative laryngoscopy (vocal cord check)', group: 'Escalation & referral' },
  { id: 'elective-sigmoid', label: 'Discuss elective sigmoid colectomy to prevent recurrence', group: 'Conservative & follow-up' },
]

export const MGMT_BY_ID: Record<string, MgmtDef> = Object.fromEntries(MANAGEMENT.map((m) => [m.id, m]))
